### ISSUE TITLE
Add CORS support to CDN (s0.wp.com)

### ISSUE THREAD

**Issue by omerlh** [Automattic/jetpack#10027]
#### Steps to reproduce the issue

Request script hosted on the CDN

#### What I expected

CORS enabled, so I can use SRI

#### What happened instead

No CORS response, which blocks SRI.

I tried to use a plugin that enables SRI on all scripts used by WP. It worked well, but all scripts served from the CDN broken because SRI requires CORS headers.
Can you please check it out and consider adding CORS support?

**Comment by omerlh** [comment]
I'm using this [plugin](https://wordpress.org/plugins/wp-sri/). The plugin basically calculates the HASH of the scripts on the first load and save it. The only problem - SRI requires CORS - see [here](https://github.com/w3c/webappsec/issues/418) for more details. So, once I enable SRI, I see CORS errors:
<img width="1275" alt="screen shot 2018-08-15 at 21 48 37" src="https://user-images.githubusercontent.com/6730584/44166868-2ab84e00-a0d5-11e8-9dc2-e782c50de5e5.png">

**Comment by georgestephanis** [comment]
So I'm gong to tentatively close this as WONTFIX -- there is a path forward on this that we're working on currently, but s0.wordpress.com isn't the right way to do it.  Occasionally the wpcom versions of those files can vary from the .org version, due to release cycles or specific differences, so just pointing at those can break things here. :\

**Comment by omerlh** [comment]
So the only way to support SRI is by not using JetPack caching?

**Comment by zinigor** [comment]
@omerlh Is there a way to ignore SRI signatures for scripts that are not requested from the same host? The files aren't physically there, you won't be able to calculate integrity hashes for them anyway.

**Comment by omerlh** [comment]
What do you mean? The whole point of SRI is for external script, so, for example, if that script is compromised your site will not be affected

**Comment by zinigor** [comment]
Yes, that's what I mean - in order to know whether your script is not compromised, you need to know its integrity hash value. With these files you can't know it in advance - the script is not bundled with Jetpack, but instead loaded from WordPress.com after you connect Jetpack and accept the Terms of Service.

**Comment by omerlh** [comment]
I've put a link to the plugin I'm using - it calculates the hash of the script on the first time the script is downloaded and store it. This is how it is able to implement SRI for all WP scripts...

**Comment by zinigor** [comment]
Oh, yes, now I see what you mean. Currently we're not planning adding CORS headers to existing asset hosting URLs, but as George said we're working on another solution that will eventually allow you to use Jetpack with SRI out of the box. Please stay tuned for updates on #10102 and related issues.

**Comment by omerlh** [comment]
Great, thank you!
