### ISSUE TITLE
Structured Schema Data error with Breadcrumbs

### ISSUE THREAD

**Issue by dwashburngarnetriver** [Automattic/jetpack#10062]
#### Steps to reproduce the issue

1. Turned ON breadcrumbs in WordPress via Customizing ▸ Theme Options ▸ General Options
2. Tested page, for example, at: https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.garnetriver.com%2Ftechnical-staffing%2F
3. Discovered three errors in schema markup for "BreadcrumbList"; two for position and one for item.

#### What I expected
No errors.

#### What happened instead
Google's testing tool reports errors.
A value for the position field is required.
A value for the item field is required.

**Comment by dashkevych** [comment]
**"Turned ON breadcrumbs in WordPress via Customizing ▸ Theme Options ▸ General Options"**
 - I want to add to this that the theme uses Breadcrumbs functionality from Jetpack. I am referring to this function: _jetpack_breadcrumbs()_. This function is executed when the breadcrumbs option is enabled in the Customizer.

**Comment by jeherve** [comment]
Previous work on this topic: #3528

**Comment by ccwalburn** [comment]
Google Search Console is reporting errors for one of our sites because the breadcrumbs are missing field "position". 
![screenshot](https://d.pr/i/hphZeS+)
Image URL: https://d.pr/i/hphZeS

The site reporting this issue uses the Prosperity theme and has breadcrumbs turned on in Customizer > Theme Options > General Options: 
![screenshot](https://d.pr/i/3Y0Nfp+)
Image URL: https://d.pr/i/3Y0Nfp

I see that Google has guidelines that require the "position" field  to be eligible to appear with breadcrumbs in Google Search: https://developers.google.com/search/docs/data-types/breadcrumb

Is this on the radar to be added?

2696455-zen

**Comment by dcoleonline** [comment]
The customer in 2696455-zen reached out again. I'm just leaving a note here to make sure we follow up with them once a developer has looked into this issue.

**Comment by carladoria** [comment]
Also reported in 2971900-zen. Any workaround for the moment?

**Comment by jeherve** [comment]
> Any workaround for the moment?

There is no work-around at the moment, short of using breadcrumbs added by another plugin that would include Schema.org metadata.
