### ISSUE TITLE
Content Options: Smarter featured images are being overrode by the first image in a gallery.

### ISSUE THREAD

**Issue by allancole** [Automattic/jetpack#10123]
When a post has both an image gallery and an image in the content. The smarter featured image script appears to find the first image found in the _gallery_ instead of the first image found in the post.

#### Steps to reproduce the issue

1. Select any theme that displays featured images in archive views
2. Create a new post. First, insert an image into the post followed by a paragraph. Then insert a gallery at the end.
3. In the customizer, goto CONTENT OPTIONS > FEATURED IMAGES and add a check to “Automatically use first image in post.”

#### What I expected
View the post in any archive (category or date archive, etc) and the first inserted image at the top should appear as the featured image.

#### What happened instead
The first image found in the _gallery_ is used for the featured image on archives and the image at the top of the post is not.

This issue was reported by a customer, see: 1404127-zen

Site: https://bioenvelope.co.uk/

**Comment by jeherve** [comment]
This is indeed the expected behaviour. When looking for images in a post, we look at the following things, in this order:

1. Is there a featured image?
2. Is there a slideshow?
3. Is there a gallery?
4. Are there images attached to the post?
5. Are there images in the post content?
6. In some cases, we also fallback to the post author's gravatar.

I would consequently recommend using the featured image field to get the best results possible.
