### ISSUE TITLE
site verify buttons look awkward on mobile

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#10219]
#### Steps to reproduce the issue

Look at site verification tools on mobile, eg Pixel XL

![screenshot_20180925-110515](https://user-images.githubusercontent.com/51896/46037703-c61de500-c0bd-11e8-8762-8334e1e85518.png)

**Comment by jeffgolenski** [comment]
As @Tug mentioned in our slack channel @gravityrail, I think a vertical stack of the elements is the most appropriate way to move forward here. However, we need to keep in mind the different states of this area on mobile as well. 1) Before auto-verified, 2) after auto-verified, 3) during edit screen.

Here are a couple screenshots of how it should look, along with some *rough* scss to make it happen. You may need to make some tweaks in the actual code though!

<img width="571" alt="screen shot 2018-09-26 at 1 07 11 pm" src="https://user-images.githubusercontent.com/214813/46096473-49f2d280-c18d-11e8-8225-f901ff675d34.png">
<img width="553" alt="screen shot 2018-09-26 at 12 49 58 pm" src="https://user-images.githubusercontent.com/214813/46096474-49f2d280-c18d-11e8-8013-22d05527a833.png">
<img width="549" alt="screen shot 2018-09-26 at 12 48 11 pm" src="https://user-images.githubusercontent.com/214813/46096475-4a8b6900-c18d-11e8-89ac-b60f2650e4d4.png">

Could we make an effort to make the other input boxes for bing, etc., also vertically stack like in the above screenshots? Thanks!

`@include breakpoint(phablet) { // from _breakpoint.scss

	// Keep an eye out on whatever else this may affect
	.jp-form-input-with-prefix {
		display: block;
		box-sizing: border-box;

		span:first-child {
			width: 100%;
			display: block;
			text-align: left;
		}
	}

	.jp-form-site-verification-verified {
		border-left: 1px solid #c8d7e1;	
		border-top: 0;
	}

	.jp-form-site-verification-edit-button {
		margin-left: 0;
		margin-top: 5px;
	}

	.jp-form-google-label-unverified .dops-button {
		margin-top: 10px;
		width: 40%;
	}

	.jp-form-google-label-unverified .jp-form-google-separator {
		margin: 25px 0 0;
		display: inline-block;
	}

} // phablet`

**Comment by stephanethomas** [comment]
Just wanted to share some feedback from Google regarding these two buttons that I find relevant:

>Since there’s already “Google” written at the beginning of the row, I’d suggest removing the repeated “Google" from the text on the two buttons and changing the text to clarify exactly what action each of them leads to, e.g. “Auto verify in 1 click” and “Manually paste code”.

I think we could also go with `Verify with Google` for the first button, which is similar to the `Continue with Google` pattern we already use on the [`Login` page](https://wordpress.com/log-in) of WordPress.com. The second button could be `Verify manually`. As mentioned in https://github.com/Automattic/jetpack/issues/10230, the shorter the better (especially since it could be much longer in some languages).

By the way, I don't know what's the usual design pattern in Jetpack for buttons when they are displayed on small viewports but in WordPress.com we usually make them take the whole available width.
