### ISSUE TITLE
If the site has been disconnected from Webmaster tools, then the jetpack UI should not show it as verified

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#10227]
This was raised in the comments for https://github.com/Automattic/jetpack/pull/10220#issuecomment-424833357

#### Steps to reproduce the issue

1. Verify your site with the one click button for Google
2. Click the to your site in search console
3. Remove your site from search console
4. Go back to jetpack and reload the jetpack tools page

#### What I expected

Site should be no longer verified, or perhaps should say that it's verified but not connected to search console

#### What happened instead

Site appears to be verified

An additional note here: Perhaps we should not refer to being verified, but being connected to search console. This is what the original feature actually did, and it's not useful to have a site that is verified but not in search console

**Comment by Tug** [comment]
This will be fixed server side. See D18878

**Comment by stephanethomas** [comment]
> Perhaps we should not refer to being verified, but being connected to search console. This is what the original feature actually did, and it's not useful to have a site that is verified but not in search console

My understanding is that site verification normally doesn't imply 'connecting' to Google Search Console. A user could very well only be interested in confirming the ownership of their site [in order to use G Suite](https://support.google.com/a/answer/63026?hl=en) for example. Let's keep that issue in mind for when we revisit the design of this section though.
