### ISSUE TITLE
Videopress: Provide option to reduce/remove dark overlay

### ISSUE THREAD

**Issue by damiannep** [Automattic/jetpack#10235]
It would be great to have the option to remove the overlay on VideoPress videos, or to reduce the opacity.

User thinks that the overlay is preventing them from representing their work well. In this case, the user decided to use Vimeo instead of VideoPress. I see that there have been other user requests for this but didn't find another open issue. Apologies if this is a duplicate.

Request: #6735053-hc

**Comment by jeherve** [comment]
Could you clarify what you mean by "dark overlay"? What part of the player is that?

**Comment by damiannep** [comment]
It's the overlay on the player start screen.

**Comment by jeherve** [comment]
To be clear (sorry, maybe I am missing something obvious), is this about the borders here:

<img width="805" alt="8b91fbb67e2de8da7ee292e89e04a465 _screenshot 2018-09-27 at 18 09 33" src="https://user-images.githubusercontent.com/426388/46159489-bac6e700-c280-11e8-88a9-21030ce8a393.png">

Or is this about the overlay that appears above the video before you hit play, and that disappears once the video starts playing?

Once you have as many details as possible, and since this seems to be about the VideoPress video player, I would recommend that you open an issue in the GitHub repository where the player is built. Jetpack itself does not control how the player looks like unfortunately.
