### ISSUE TITLE
Markdown block: remove Composing Markdown setting on sites using Gutenberg

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#10294]
There is a setting in Jetpack and Calypso that enables or disables Markdown for Posts and Pages. This is necessary for post-new and the Calypso editor, but not for Gutenberg editors. On sites with Gutenberg, we should not show this setting at all.

<img width="745" alt="captura de pantalla 2018-10-10 a la s 14 54 10" src="https://user-images.githubusercontent.com/1041600/46756043-f4461c00-cc9c-11e8-8749-c9a645b78b4d.png">

(rewritten by @MichaelArestad)

There is an idea to perhaps add another setting that makes the markdown block the default block, but I don't think we should do that for v1.

**Comment by MichaelArestad** [comment]
@jeherve That's a good question. I don't know. If that's the case, perhaps we reword it? Or even better, just leave it off/on/however it was before they switched and and hide the option. What do you think?

**Comment by jeherve** [comment]
Could we just leave it there, but not load the Markdown block in the Gutenberg block when it is disabled?

**Comment by MichaelArestad** [comment]
Not without rewording it. It's not super clear how it works and if it at all relates to Gutenberg. I suspect the confusion would only come from folks familiar with that setting (us).

**Comment by MichaelArestad** [comment]
> If the Classic Editor is installed, show the option noting that it is only for the classic editor?

I think that would do the trick. Maybe something like:
"Write posts or pages in plain-text Markdown syntax"
"This only applies to the Classic Editor because there is a Markdown block available in new editor."

And have that second line be the grey supporting text seen elsewhere in the settings.

**Comment by ockham** [comment]
> Could we just leave it there, but not load the Markdown block in the Gutenberg block when it is disabled?

That's what we're doing now, isn't it?

**Comment by jeherve** [comment]
> That's what we're doing now, isn't it?

Yes, that's how it works today. If the module is off, the block is not visible in the block editor.

To summarize the current behaviour a bit:

The Markdown toggle in Jetpack > Settings is a bit of a special case today; it turns on a module, but also turns on an option. Ultimately though, it does not change the behaviour of the feature that much; if the toggle is on, the feature is on. Here is how it works:

**Default state**:

- Markdown module is off.
- `wpcom_publish_posts_with_markdown` option is off.
- `wpcom_publish_comments_with_markdown` option is off.

**If you use the toggle**:

- Markdown module is on.
- `wpcom_publish_posts_with_markdown` option is on.
- `wpcom_publish_comments_with_markdown` option is off.

**If you use the toggle again**:

- Markdown module is off.
- `wpcom_publish_posts_with_markdown` option is off.
- `wpcom_publish_comments_with_markdown` option is off.

**To turn `wpcom_publish_comments_with_markdown` on:

- You need to go to Jetpack > Settings > Discussion and switch the toggle. If you do so:

- Markdown module is on.
- `wpcom_publish_posts_with_markdown` option is on.
- `wpcom_publish_comments_with_markdown` option is on.

-------

To come back to the original issue, here is what we need to discuss and decide:

**1. Should the module be auto-activated for everyone who connects Jetpack to WordPress.com on a new site?** It would allow us to show the Markdown block in the block editor for everyone. After all, folks starting a new site today should not have to go and manually activate the Markdown module to start seeing the Markdown block in their editor.

This approach has some potential issues / use cases to consider:
- The Markdown module, when active, may also impact the Classic block. Are we okay enabling Markdown by default for everyone using the Classic block (i.e. everyone using the classic editor plugin because they don't want Gutenberg yet, or everyone editing posts that were published before Gutenberg and not converting those posts into blocks). Note that we've recently disabled Markdown processing in all blocks in the new editor to fix a bug (see #10635), but we may bring Markdown back to the classic block in the future (see #10642). 
- The Markdown module also impacts folks who may not use Gutenberg at all because they use a plugin to disable the new editor.

**2. Should we consider making the Markdown block visible regardless of the Markdown module status (i.e. having the block always on, just like the Map block).** It would allow us to show the Markdown block in the block editor for everyone. The block does not depend on the Markdown module code at all. 

This approach can potentially cause some confusion with our users though:
- Some may wonder why there is a Markdown option in Jetpack > Settings if it does not impact the availability of the block in the block editor.
- It may help fuel the idea that Jetpack is bloated, as features will seem to be loaded even when a feature is off in the Jetpack settings.
- It will be more difficult for one to control what blocks are available to the authors on their site; they will need to use the `jetpack_set_available_blocks` filter to remove the Markdown block.

Did I forget an option, or is there something I overlooked?

**Comment by MichaelArestad** [comment]
> 2. Should we consider making the Markdown block visible regardless of the Markdown module status (i.e. having the block always on, just like the Map block).

I lean this direction with this block. Right now there is also no way to turn off the Map block that I'm aware of.

**Comment by jeherve** [comment]
Related discussion: pafL3P-aF-p2

**Comment by nota-bene** [comment]
My opinion:
 
> **1. Should the module be auto-activated for everyone who connects Jetpack to WordPress.com on a new site?**

No, precisely because of the issues you mention.

> **2. Should we consider making the Markdown block visible regardless of the Markdown module status (i.e. having the block always on, just like the Map block).**

Yes. To reduce confusion, the option in Settings could be redesigned, like @MichaelArestad suggested [here](https://github.com/Automattic/jetpack/issues/10294#issuecomment-431109162):

> > If the Classic Editor is installed, show the option noting that it is only for the classic editor?
> 
> I think that would do the trick. Maybe something like:
> "Write posts or pages in plain-text Markdown syntax"
> "This only applies to the Classic Editor because there is a Markdown block available in new editor."
> 
> And have that second line be the grey supporting text seen elsewhere in the settings.

**Comment by jeherve** [comment]
The block is now available at all times, even when the feature is disabled in the Jetpack dashboard. See #13473. Let's update the settings to reflect that?

Calling in Design to the rescue!

**Comment by jeherve** [comment]
See #13495 for a potential way to address this, based on the wording above.
