### ISSUE TITLE
WordPress dashboard: add Jetpack branding to stats widget 

### ISSUE THREAD

**Issue by rickybanister** [Automattic/jetpack#10553]
There is no attribution of the stats widget on the dashboard to Jetpack. Let's add a logo, powered by, and make the 'view all' link more clear, also add a view more on WordPress.com link.

cc @beaulebens

**Comment by joanrho** [comment]
**Proposed solution:**

1. Add logo to stats widget in wp-admin Dashboard to emphasize Jetpack's role in delivering the value of this feature. 
2. Update text of "View all" button to read "View all stats" and shift its location be centered at the bottom of the first section so that the functionality of it is clearer: (it directs to https://wordpress.com/stats/day/SITE_URL).
3. Adjust the two column width of the first section so that the "Top Posts" and "Top Searches" are equal, and list the Top Searches results in a vertical list format rather than in-line/comma-separated.
4. Update text of title of second section from "Most Active (the past day)" to "Most Active Pages (within the past day)" so it's clearer what is being listed and the time range covered.

BEFORE
<img width="814" alt="before" src="https://user-images.githubusercontent.com/204742/49536096-f682bc00-f882-11e8-86a3-fa72369b75e8.png">


AFTER
<img width="705" alt="after" src="https://user-images.githubusercontent.com/204742/49536705-647bb300-f884-11e8-8245-abd0389d201c.png">

**Comment by jeherve** [comment]
Patch ready in #10958.

> Update text of title of second section from "Most Active (the past day)" to "Most Active Pages (within the past day)" so it's clearer what is being listed and the time range covered.

Jetpack's Stats widget looks a bit different from the one available on WordPress.com sites, so we don't have a "Most active" section to deal with here.
