### ISSUE TITLE
Sharing / Likes: conflict with the Basic Google Maps Placemarks plugin

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#106]
Plugin:
http://wordpress.org/plugins/basic-google-maps-placemarks/

This plugin allows you to insert content from another post type (Placemarks) into an existing post or page, thanks to a shortcode.

However, it seems to create problems with Jetpack Sharing buttons.
Steps to reproduce:
1. Enable the Jetpack plugin, and insert sharing buttons at the bottom of your posts
2. Enable the Basic Google Maps Placemarks plugin
3. In Placemarks > Add new, create a new map
4. In Posts > All Posts, add that map into an existing post by adding `[bgmp-map]` to the post
5. View post
6. The sharing buttons (and Like buttons) have disappeared

cc @iandunn 

Original trac ticket:
- https://plugins.trac.wordpress.org/ticket/1868

**Comment by dereksmart** [comment]
I just looked into this briefly and Ian is right, there's some `the_content` competition going on.  

Since they are using `apply_filter('the_content')` to get their map description, our likes, shares, and even related posts are trying to load themselves onto that filter which is applied here: https://cloudup.com/cAprgqRSA27 

A simple fix would be for them to namespace their filter hook to something like `bgmp_the_content`

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
