### ISSUE TITLE
Social Icons Widget: allow for alternate feed URLs

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#10662]
Right now, Jetpack's Social Icons Widget will display an RSS icon if you insert a link that ends with `feed/`. While this works well for most people, there are situations when an RSS feed may not use that format. It may be useful to check for other potential formats, as highlighted here:
https://codex.wordpress.org/WordPress_Feeds

**Comment by rickcurran** [comment]
Hi, I've added a PR that adds approximately 20 other possible url elements that can be found in many RSS feed url structures. This improves the likelihood that RSS Feed urls that are added to the Social Icons widget are correctly recognised and displayed using the RSS feed icon rather than the default link icon. 

This PR adds in approximately 20 additional items to an array $social_links_icons which is used to match components of any url added to the Social Icons widget, the additions expand upon the existing /feed/ array item which is intended to show an RSS feed icon if matched. Whilst this works for the standard WordPress permalink feed format it doesn't work for non-permalink WordPress feed urls and also many other common RSS feed url formats. It should now support some other RSS feed url formats such as:

http://blogs.adobe.com/jkost/atom.xml
http://feeds.feedburner.com/clickontyler
http://daringfireball.net/index.xml
http://ranchero.com/xml/rss.xml
http://usefulmac.com/rss
http://rss.macworld.com/macworld/feeds/main

If these are correctly parsed then you should see an RSS feed icon instead of the default 'chain link' icon.

(I did explore the potential of doing some kind of detection on the url when it is being added to see if it was possible to detect whether it was a feed or not as this would be a 'smarter' way to do it, e.g. using SimplePie to attempt to parse it as RSS and if successful mark it as RSS, however, that would require a different process for checking. At the moment the urls are parsed as part of the process of displaying on the front end and then the correct icon shown but obviously that is the wrong place to do any parsing / lookup!)
