### ISSUE TITLE
Settings: show banner after first successful WordPress.com Secure Sign On login

### ISSUE THREAD

**Issue by joanrho** [Automattic/jetpack#10692]
After the WordPress.com Secure Sign On login module has been activated by a user, present the user with a banner in the Jetpack Dashboard view after their first time logging in with WordPress.com Secure Sign On to communicate the feature's value (that it’s a safer way to login).

ref: p6TEKc-2m8-p2 (RB / item 5.17)

**Comment by joanrho** [comment]
Proposed solution:

Banner that appears the first time (only) a user signs in using WordPress.com Secure Sign On that informs them of the successful sign on, describes the benefit, and links to our support page with more details. Banner text will read:

Title: "You've successfully signed in with WordPress.com Secure Sign On!"
Description: "Logging in with the same log-in credentials you use for WordPress.com ensures you always sign in to self-hosted WordPress.org sites quickly and securely. [Learn more](https://jetpack.com/support/sso/)"
where "Learn more" links to https://jetpack.com/support/sso/.

Mockup:
<img width="1355" alt="screen shot 2018-12-05 at 2 43 28 pm" src="https://user-images.githubusercontent.com/204742/49546272-1030fd00-f89d-11e8-9cd5-e2a2e7db145a.png">

**Comment by jeherve** [comment]
I started working on this, and I would have some questions:

- You modeled the design of the notice after the existing JITMs that can appear on all pages of the dashboard. I assume that if this SSO notice should replace any JITM displayed there?
- Since we already have a tool to display notices in the dashboard, I was wondering if we could take advantage of that tool instead of building something new, or something that would override the JITMs. We could, for example, create a new JITM that would only be displayed on that main dashboard page, and only on sites where SSO is active. We could also choose to make it disappear after you dismiss it once. Here is how that would look like: D22220-code

The inconvenient of that second approach is that we lose a bit of flexibility: we can't display it "only after a login via SSO", and we can't "display it only once". On the other hand, we leverage an existing system, with its built-in stats and design, and we don't have any overhaul in the plugin.

What do you think?

**Comment by jeherve** [comment]
#10979 introduces an approach that would work, and is Jetpack-only, while not conflicting with other JITMs (no chance of having 2 JITMs displayed at the same time).
