### ISSUE TITLE
Should we hide JITMS during a customer's first session in the Jetpack dashboard?

### ISSUE THREAD

**Issue by rickybanister** [Automattic/jetpack#10752]
@annezazu posted a long product walk through nearly two months ago now and one of her points was around upgrade banners. She had just installed and connected Jetpack and had already been shown the plans grid and had several opportunities to upgrade. She chose not to (in this particular demo), but was still shown just in time messages in the Jetpack dashboard before she saw much else. 

In this case it was a prompt to access premium themes by purchasing the professional plan.

Should we work to simplify the dashboard experience for that first session and reserve showing jitms when we have more certainty surrounding their context and relevance to the customer AND when the customer is not focused on something else (in this case trying to learn the dashboard for the first time)?

I can see the other side, where that upgrade banner could have alerted a customer to a valuable feature and resulted in a sale, but the context and likelihood in this particular scenario seem dubious. 

Let's discuss!

cc @jessefriedman @joanrho @jeffgolenski @keoshi 

p6TEKc-2m8-p2

**Comment by dereksmart** [comment]
I'm kind of torn. The example you provided makes a great case for hiding. However, a couple things came to mind: 

- We have the majority of their attention on their first visit. Other than Stats, there isn't much incentive to revisit the Dashboard after initial set up. We can collect data on how many times people visit the Jetpack admin to see how many potential views we'd miss out on. 
- Since it's only code, It doesn't have to be boolean. We can add an option to the JITM settings so that we can choose which do and do not show up on first page view. We could even make them timed (only show after X visits, etc).

**Comment by keoshi** [comment]
I really like @dereksmart's arguments here. The first one is especially valid, but I also agree that the JITMs should be throttled back (even if artificially) so that they're not overwhelmed with suggestions that don't make much sense at that particular point.

Maybe this just means the Dashboard, as it stands, it's not very helpful at all and that we should rethink that first experience holistically, even including suggestions in the form of a “welcome to your site, let's go through a quick checklist together” moreso than with JITM banners, which can lack context.

**Comment by jessefriedman** [comment]
A couple thoughts:
- JITMs should not be thought of as purely commercial. 
- Depending on the lifecycle phase that the user is in, JITMs can be highly useful
- "they're not overwhelmed with suggestions that don't make much sense at that particular point."
No JITM should exist that doesn't make sense at a particular point. If it's not highly relevant it shouldn't exist.

**Comment by keoshi** [comment]
> No JITM should exist that doesn't make sense at a particular point.

Sorry I didn't make my point clear here. I meant “at a particular point” in the customer's experience/journey, not from a technical aspect of when JITMs appear.

**Comment by rickybanister** [comment]
> Maybe this just means the Dashboard, as it stands, it's not very helpful at all and that we should rethink that first experience holistically, even including suggestions in the form of a “welcome to your site, let's go through a quick checklist together” moreso than with JITM banners, which can lack context.

@keoshi yes! that's definitely part of what I meant to imply. Anne's experience was partly because we had an over-eager jitm, and partly because our onboarding flow didn't guide her in a meaningful way. I think we need to tackle both a bit to improve the experience. 

@jessefriedman let's look at the logic behind this particular message and see if it deserves to be there.

**Comment by jeherve** [comment]
Noting that #10759 may help a bit with those issues, at least in regards to JITMs in the Jetpack dashboard, as it will give us more flexibility and granularity over what JITMs are displayed on what Jetpack dashboard page and subpage.
