### ISSUE TITLE
Subscriber Email Erroneously Says Ad Supported

### ISSUE THREAD

**Issue by peiche** [Automattic/jetpack#11025]
I am using the free tier of Jetpack, meaning I could not have Jetpack-powered ads even if I wanted to. A recent post I published triggered an email to subscribers, as it does, but this time the email also contained a "this post is ad supported" section with ads. My site is not ad supported. It's never done this before.

Screenshot of the email sent to subscribers:
![email](https://user-images.githubusercontent.com/613931/50325798-8728e100-04ac-11e9-9bf8-3a90bfcac7a4.png)

My Jetpack dashboard, showing that Ad settings is disabled:
![Jetpack dashboard settings](https://user-images.githubusercontent.com/613931/50325896-03232900-04ad-11e9-98ef-30cacde40666.png)

**Comment by andrewarthurdawson** [comment]
Jeremy, this is totally unacceptable. My readers are going to drop because of these ads showing up. I’ve already been informed of it. With sensitivity lately to stuff going on like Facebook selling info and sharing personal info, it’s triggered all sorts of fear and worry and it doesn’t take much to make people to take action. Personally, I don’t want to get an email either with garbage ads in it! This feels like a cheap money grabbing scheme by Jetpack right now and I’m thoroughly upset about this. I’ve always loved and supported Jetpack for years now and now I have to upgrade to turn this off? Come on! That is ridiculous and so I have to choose to spend money when I am currently unemployed and don’t earn a single dime because of my disabilities or I have to choose to accept it and warch as my readers unsubscribe. I sincerely hope you immediately turn this off as I can’t believe I’m the only one that’s going to be upset about this...as evident on my thread I started on the word press support for Jetpack where others have already chimed in...

**Comment by mehmednaim** [comment]
It is **not** only free version of Jetpack.

**Comment by rluechinger** [comment]
@mehmednaim so which subscription do we need to purchase in order to disable this ad? Is a personal subscription sufficient, or is premium/professional needed? or maybe we should just stop using Jetpack alltogether...

**Comment by andrewarthurdawson** [comment]
So they implemented it on the paid versions of Jetpack too? With no way to turn it off at all? This is ridiculous.

As I mentioned in my personal support email to them, I can see a company like Facebook doing something like this. But Jetpack I never saw this coming. Regardless, it isn’t fair, even for free users like me. It makes the subscription email almost unreadable. 

When it first came in last night I thought there was an error! The first thing I noticed was not the few sentences that are shown from my blog. Instead, i noticed a big square with ads that I thought looked like porn because there were some scantily clad women advertising some article to click!!!! And I’m publishing a spiritual 12 step blog about recovery from addiction!!! I am so upset at Jetpack right now and have been put in a corner. 

My readers don’t want this and I don’t want this and we have no way to turn it off? I sincerely hope Jeremy, that Jetpack will immediately turn this back off and find some other way to generate money for itself.

I have remained with Jetpack for one reason and one reason only anymore and that’s for the subscriber emails because I liked the format of them and so did my users. I don’t really use any other feature of Jetpack currently, except Akismet but that’s a different plugin anyway owned by the same company. 

Please Jetpack listen to your loyal subscribers and turn this off as I want to keep supporting you guys and not lose my own few subscribers...

**Comment by andrewarthurdawson** [comment]
For me it’s not ok. Not even if they informed us ahead of time. Most of my readers are in recovery for addiction and are now having to see ads with pictures that can potentially trigger their addictions with booze or women showing up is 100 percent unacceptable!

**Comment by potatoqualitee** [comment]
This is *terrible* and unexpected. Our whole brand is built around not spamming people, and this unexpected garbage popped up in my inbox today without obvious warning. Totally, totally uncool.

**Comment by rluechinger** [comment]
@jeherve if you could let users know which jetpack subscription is needed to hide those ads, it would be very much appreciated.

**Comment by jeherve** [comment]
@rluechinger I am waiting for details from our Ads team on this issue, and will update everyone here once I have more details!

**Comment by potatoqualitee** [comment]
I've been using WordPress since the beginning and even had Matt over for gumbo. I've always trusted the Automattic brand and this is a breach of that trust. I genuinely hope this is a mistake.

**Comment by andrewarthurdawson** [comment]
We shouldn’t have to pay to change this. I agree with @potatoqualitee. This goes against everything I signed up for. And it goes against my 12 step programs as well!

**Comment by hansfrederiks** [comment]
It's indeed terrible. On our blog we don't use advertisements at all and now, in the mails we are forced to have them. If it stays like this we have to look for another solution.

**Comment by andrewarthurdawson** [comment]
Agreed. This will probably lead many Jetpack subscribers to look for other solutions if they don’t change this. This goes against all my principles. I can’t believe the Jetpack team didn’t think this through?

**Comment by astridparamita** [comment]
Agreed. I have a personal subscription with Jetpack (which is enough for what I need. Won't it be enough to support my Jetpack use ?!?!?!). If I have to upgrade/pay even more just to get rid of the annoying and spammy ads, I would rather give my money elsewhere.

**Comment by andrewarthurdawson** [comment]
Agreed to both previous comments. I’ve loyally stayed with Jetpack for five years because they never injected me with stuff like this and prevented me from ever having to deal with it. My readers are not interested in ads and would not support me having them in there! It’s obvious Jetpack you made a serious mistake in your judgment with this and I sincerely hope you will listen to your loyal subscribers and turn this ad stuff off without having to make us pay for it.

**Comment by jeherve** [comment]
Hey everyone. I have an update. First of all, I'd like to apologize. The change has now been reverted. The Email ads were implemented for WordPress.com site owners using the free version of WordPress.com, and should not have appeared at all in emails for Jetpack sites like yours. 

**Future emails for posts from your sites will not include any ads. **

Again, sorry for all the trouble, and thank you all for reporting the problem in the first place.

**Comment by andrewarthurdawson** [comment]
Does that include my site Jeremy?

**Comment by jeherve** [comment]
@andrewarthurdawson Yes. It includes all sites.

**Comment by andrewarthurdawson** [comment]
I guess I just didn’t know what you mean by free sites. As I thought WordPress is free. So I’m not sure what users you were referring to?

**Comment by imabug** [comment]
I'm not a fan of the ads suddenly appearing in the email notifications, but what really ticks me off is the bit that says "This post is ad-supported" which implies that my posts and blog are ad supported, when they're most definitely not, never have been and never will be.

If you're going to inject ads, put in ads for Wordpress, or Jetpack.  Don't put in crap ads.  Everybody gets enough of that shit browsing the web already.

**Comment by andrewarthurdawson** [comment]
I just wanted to let everyone know that this is indeed fixed. I just posted a blog apologizing to my subscribers. I pray Jetpack doesn't do something like this again, as it's quite obvious how upset it made people, including my own subscribers. I never signed up with Wordpress/Jetpack, or anything really to do ads and never want to do ads. I'm running a blog to help people with addictions and I don't wish to profit from this and any advertising will only make me look like a hypocrite...even if it isn't being controlled by me and profiting someone else... so thank you Jetpack for fixing this... I just hope I haven't lost any subscribers from last night's mishap...

**Comment by claudiocuce** [comment]
We are a Non Profit Organization and this serious "mistake" will cause to us a lot of problems with our subscribers (supporters and volunteers). Please don't do anything similar again, if you plan to put ads to push us to subscribe paid plans it is not fair but you can do it. You only have to give us the time to find alternatives and disable your plugin.

**Comment by jeherve** [comment]
> Please don't do anything similar again, if you plan to put ads to push us to subscribe paid plans it is not fair but you can do it. You only have to give us the time to find alternatives and disable your plugin.

That is totally understandable. That was a really bad oversight, and something that should not have happened. We'll take measures to make sure this does not happen again.

In the future, if we were to implement something like this (and I am not saying we will, that is not in the cards), we would aim to communicate about it beforehand. I would recommend following [our blog](https://jetpack.com/blog/) to be sure you get updates and announcements about new features in Jetpack.

**Comment by andrewarthurdawson** [comment]
Being a free user I’m always wary of what could be done. Advertising is a deal breaker and something I couldn’t tolerate given the sensitivness of my blog. Hopefully Jetpack learned a lesson from all this and thankfully they listened to their loyal users after all this... to that which I’m very grateful ...
