### ISSUE TITLE
Upcoming Events: Add Integration for Other Calendar Types

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/jetpack#11039]
From 1669233-zen:

> But why direct people to Google 
> for an ical url ? Many other free and... open calendars exists.
> 
> Like this one for example : 
> https://openagenda.com/?lang=en
> 
> On this website, any organisation can create its own calendar, and export it in 
> ical, rss, json... you name it. 

Can we add integrations for other calendars in the Upcoming Events widget?

**Comment by Nic-Sevic** [comment]
I had a user with a possibly related issue: They were using an apple webcal link and the upcoming events kept failing to populate. When a new widget is added and the calendar is added for the first time it populates but then fails.

The calendar they were using is here: webcal://p29-caldav.icloud.com/published/2/MTM1MDc0NDg5NTEzNTA3NDqh_XbwHHuUikrYiXS6OZUykuLJXbWO6lRmrjOZ8gdn-w6uIgS14Vg_5Yr0YlwhnxBpkYxn5YE5kfe9xHSvotE

**Comment by kraftbj** [comment]
Closing this as invalid. The original user report dealt with the article, which mentioned Google Calendar, but doesn't mention that any ical URL would work too. The integration has always been present; just in marketing, we said "Google" instead of a technically diverse answer.

The URL in the last report works for me.
