### ISSUE TITLE
Photon images ugly stretch in to fit header banner container

### ISSUE THREAD

**Issue by gordo019** [Automattic/jetpack#11074]
-WP 5.0.2
-Jetpack 6.8.1 (yes: Speed up image load times, no: lazy images)
-Bootstrap 4.1.3
Chrome 71.0

http://jocelynslack.com/

As you move between site pages (only 3) the header banner (same on all pages: fish image) loads pixelated then the header image shrinks to fit it’s header container. Unwanted and unsightly fadein effect. Any ideas on getting the image to display when fully loaded and not pixelated?

The issue does not occur consistently.

**Comment by jeherve** [comment]
This is most likely caused by a conflict between Photon and how the header image and its dimensions are added and handled in your theme's header. Would you mind contacting us via [this contact form](https://jetpack.com/contact-support/?rel=support) and give us more details about your theme, so we can run more tests with you?

Thank you!
