### ISSUE TITLE
My Plan: consolidate prompts to upgrade

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#11110]
> There seems to be a repeated nudge for upgrade to Pro ( reasons to go Pro + and introducing Premium Themes):

<img width="773" alt="screenshot-2019-01-09-at-11 45 00" src="https://user-images.githubusercontent.com/426388/50902981-c186fd80-141c-11e9-9da1-ed0ae47130d4.png">

> we should remove all upgrade prompts from the main section and move those out into their own elements like the Premium Themes one, when and if relevant.

p8oabR-j3-p2

**Comment by jeherve** [comment]
We should also take the opportunity to fix Title Case on that page. A few examples:

> Monetize your site with ads
> Two great reasons to go Pro

> There’s also the reverse with the button Compare All Plans button, which does not match the Ask a question and Search our support site below it, despite using the same design style.

**Comment by AnnaMag** [comment]
To confirm, @keoshi suggested removing the card altogether.
Should we move the "Three great reasons one.." elsewhere since it is not specific to current plan's features?

**Comment by keoshi** [comment]
@AnnaMag Yep, I think we should remove this card since a) the main purpose of this page is to highlight the benefits of the _current_ plan and b) the first prompt (Premium Themes) already has a corresponding promo card underneath. The benefits of the plans you can upgrade to are already in the “Plans” tab, and we should keep these separate IMO.
