### ISSUE TITLE
Automatic update from 6.8.1 to 6.9 failed

### ISSUE THREAD

**Issue by bobbydurrett** [Automattic/jetpack#11125]
Automatic update from 6.8.1 to 6.9 failed

#### Steps to reproduce the issue

Wait for the automatic update of Jetpack 6.8.1 to 6.9 to run. It fails and the Jetpack plugin is disabled.

#### What I expected
I expected the automatic update to run without issues.

#### What happened instead
Site is now unusable.

**Screenshots**
I have the following error logged in as admin:
An automated WordPress update has failed to complete - please attempt the update again now.

![image](https://user-images.githubusercontent.com/12128590/51004424-c8cf0980-14f7-11e9-9c45-b1d78d606eb0.png)

**Comment by andrewarthurdawson** [comment]
I too had the same issue. Bobby, by some chance are you running your site on GoDaddy's Managed WordPress? I also am on Wordpress 5.0.3, and PHP 7.2. I was wondering if any of that is similar to your setup? Regardless, my site got hosed as well because of this update and I had to roll back a few days to get my site back up and running. And, I have had to leave the update plugin page still showing 6.8.1 because twice I tried it, and twice I corrupted my system. And twice I deleted the plugin altogether and twice I tried to redownload from the plugins page and twice it corrupted it in that way as well. Jetpack is DEFINITELY unusable for version 6.9 for me and it appears to be the same for a few others as well now too. Hopefully you guys can get to the root of this quickly and Bobby, if you're willing to share, what was your current configuration with versions of things?

**Comment by jeherve** [comment]
I replied with some recommendations in this forum thread:
https://wordpress.org/support/topic/fatal-error-updating-from-jetpack-6-8-1-to-jetpack-6-9/

**Comment by bobbydurrett** [comment]
I am on iPage on the latest Wordpress and I'm pretty sure it is php 7.2.

**Comment by andrewarthurdawson** [comment]
Jeremy, could you send me a screenshot of what the FileZilla files to select look like when I do the delete? I’ve never looked at the file structure and don’t want to select the wrong thing and screw up my site. Also, why doesn’t deleting the plugin from the wp-admin dashboard accomplish the same action? Does that leave one of those files out there? And lastly, how long can one safely run on Jetpack without updating usually (how far back of versions do you support)?

**Comment by jeherve** [comment]
@andrewarthurdawson I replied in the forum thread:
wordpress.org/support/topic/fatal-error-updating-from-jetpack-6-8-1-to-jetpack-6-9
