### ISSUE TITLE
Custom domain name / slug on URLs after Jetpack's CDN domain

### ISSUE THREAD

**Issue by kilinkis** [Automattic/jetpack#11140]
#### Problem
Images delivered through Jetpack show the domain of the WP installation where the image was uploaded. This is not always optimal and could represent liability.
For example: ``` https://i2.wp.com/secret-wp-install.com/wp-content/uploads/2019/01/image.png?fit=1200%2C683&ssl=1 ```

there, you can see the domain "secret-wp-install.com", which makes no sense if you're using a 3rd party software to compile WP or using the API.

I think it can be a great feature to have, specially because static WP is becoming a trend, with all the headless options and the static hostings like HardyPress and Shifter.

#### Desired solution
It would be nice if we could set the domain manually (maybe verifying we own that domain too), or maybe use a username instead of a domain. Or a unique slug.

Thank you on this great plugin!

**Comment by jeherve** [comment]
You can use the `jetpack_photon_domain` filter to specify your own domain for Photon:
https://developer.jetpack.com/hooks/jetpack_photon_domain/

You can also check those posts for more details about running your own instance of Photon, that will consequently not be blocked in your country:
https://danielbachhuber.com/tip/photon-local-development/
https://ethitter.com/2017/04/running-a-private-photon-instance/

**Comment by kilinkis** [comment]
hi @jeherve , thanks for your reply.
I checked those before opening this thread.

it's not exactly what I mean.
Those are to replace the photon domain (x.wp.com). I tried ```jetpack_photon_domain```` and that's what it does.

What I'd like to have my url to be something like:

```https://i2.wp.com/CUSTOM-NAMESPACE/wp-content/uploads/2019/01/image.png?fit=1200%2C683&ssl=1```

**Comment by jeherve** [comment]
I see. I am not sure this is something that's possible right now, as the full image path has to be publicly accessible and resolve to a real image. Such a change would require some significant changes to the Photon infrastructure, and to the way the images are served (since we currently include a link to the canonical image when serving each Photon image).

The Photon infrastructure isn't currently built to separate domains and treat them differently; it does not know or care about the site behind an image, or its settings. If you give Photon an image, it will cache and serve, regardless of where it comes from or the site settings. Here is an example:

`https://i1.wp.com/www.google.com/logos/doodles/2019/childrens-day-2019-thailand-6255707132264448-2x.png`

As a result, I am afraid we won't be able to implement something like what you have in mind. I can see how it could be useful in some cases, but that is not something you can do with Photon today, and not something that we plan on working on in the near future.

**Comment by kilinkis** [comment]
okay, I see.
As I said on the first post I think this can be really valuable when using headless WP.
Still, thank you for hearing :)

Jetpack Rocks!
