### ISSUE TITLE
Subscriptions: Confirmed subscription emails should not be sent in English, regardless of the site language

### ISSUE THREAD

**Issue by HardeepAsrani** [Automattic/jetpack#1122]
A friend of mine, who is using WordPress in French, wanted me to post it here. I never used WordPress in any other languages. According to her:

(When someone subscribes to her site using Jetpack's module): The first message to ask to confirm soubscription is in French. That's what I want.

The second message [Subscribe] Confirmed Subscription tis in English that's what I dont' want because all the people who receive these messages speak FRENCH. Do you know what can I do to resolve this ?

Don't you think all messages should be in chosen language. Thanks!

I wonder if the language pack is available? If not, I'll ask her for help :)

**Comment by richardmtl** [comment]
Another: 2136751-t

**Comment by csonnek** [comment]
Another in 2184100-t

WPLANG setting in `wp-config.php` is `define ('WPLANG', 'nl_NL');`

**Comment by mikeyarce** [comment]
Another in 2188177-t

**Comment by kraftbj** [comment]
Noting that the `WPLANG` constant is deprecated as of WP 4.0. The setting that replaced it in Settings->General should be used.

**Comment by richardmtl** [comment]
This came up in 2235365-t

**Comment by richardmtl** [comment]
2277289-t

**Comment by HardeepAsrani** [comment]
See yea at WordCamp Pune, @jeherve . :)

**Comment by csonnek** [comment]
Another in 2524746-t

**Comment by chaselivingston** [comment]
Another in 2601186-t

**Comment by jenhooks** [comment]
Reported in 2857262-t.

**Comment by lamdayap** [comment]
reported here: 2904408-t

**Comment by lamdayap** [comment]
Reported here 2912153-t

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/translation-of-subscription-molude-of-jetpack-plugin/

**Comment by lamdayap** [comment]
reported here: 2963073-t

**Comment by davidovich1** [comment]
This issue may seem minor (reported years ago), but it actually kills a lot of interest in using jet pack outside Wordpress.com. My users are seeing a geeky strange English message that probably 80% don't understand and even worse some reported to me they thought it was a bug on  MY website. Which is bad for my brand (and not for Wordpress brand)
I would be surprised that a fix would be very long to implement, so at the end, the ROI of fixing the bug seem quite high isn't it ?
Cheers
D.

**Comment by jeherve** [comment]
Also reported here:
https://www.mister-wp.com/plugin/vulgarisation-jetpack/

**Comment by richardmtl** [comment]
3073639-t

**Comment by richardmtl** [comment]
3203705-t

**Comment by gelgen** [comment]
Has this issue been priotized?  I work for a Québec government entity and this English only second email is keeping us from using the Subscriptions module entirely :(

**Comment by s2r** [comment]
This is still a issue! My site is in portuguese set on wplang and all works well with wordpress but all e-mails from subscribe are in english! not just the replies, all of them, including saying to press the button in portuguese and then the button is in english, its a mess... below is the first e-mail someone receives... and all other emails are just in english or again mixed
![screen shot 2018-03-10 at 19 25 06](https://user-images.githubusercontent.com/2265583/37245982-cb46c130-2498-11e8-9787-610191d42031.png)

**Comment by gaurav1984** [comment]
#1402747-zen

**Comment by richardmtl** [comment]
Reported again in https://wordpress.org/support/topic/untranslated-plugin-parts/

**Comment by richardmtl** [comment]
Removing Stale because this is something we should fix, even if low priority.

**Comment by s2r** [comment]
Still not fixed? 6 years to get it fixed? :/

**Comment by htdat** [comment]
I followed these steps https://github.com/Automattic/jetpack/issues/1122#issuecomment-56966828 
The only difference is that I am using Spanish instead of French. The result looks good: 

![Screen Shot on 2020-04-09 at 16:18:47](https://user-images.githubusercontent.com/10045087/78879254-d6b66600-7a7d-11ea-8a15-c2fcc62ebd99.png)

@s2r - can you try testing again and give me the specific steps to test this issue in your case?

**Comment by s2r** [comment]
@htdat is that wordpress.com or jetpack? For portuguese no need for another screenshot that i already put, because its the same as the one i posted, and before you say its that site, i have about 20 wordpress sites its all of them... but here is another one, this time is from the daily email sent... its all in english... even though the site is set to portuguese and i also changed to portuguese brazilian just to check, it comes all in english... its not even mixed portuguese and english

![Screen Shot 2020-04-10 at 08 36 38](https://user-images.githubusercontent.com/2265583/78972958-73204d00-7afe-11ea-8fd6-2e9b1bc6aa50.png)

**Comment by htdat** [comment]
> is that wordpress.com or jetpack? 

It's a Jetpack site :)

@s2r I've subscribed to your site and will check emails for your new posts (screenshots below).

### What I noticed 

- In the opt-in email, there was only one English string: `Confirm your subscription for`.
- In the confirmation email, there were a few English strings: `Confirmed subscription to posts on`, `Congratulations, you are now subscribed to the site`, etc. 

### What I found out 

- These strings are not translated into Portuguese yet. You can [check](https://translate.wordpress.com/projects/wpcom/pt/default?filters%5Bterm%5D=Click+on+the+unsubscribe+link+at+the+bottom+of+every+email&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filters%5Bview%5D=wk-emails-new&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) [on](https://translate.wordpress.com/projects/wpcom/pt/default?filters%5Bterm%5D=Confirmed+subscription+to+posts+on&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filters%5Bview%5D=wk-emails-new&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) these [links](https://translate.wordpress.com/projects/wpcom/pt/default?filters%5Bterm%5D=Congratulations%2C+you+are+now+subscribed+to+the+site&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filters%5Bview%5D=wk-emails-new&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc). 
- But they have been already translated into Portuguese (Brazil). You can [check](https://translate.wordpress.com/projects/wpcom/pt-br/default?filters%5Bterm%5D=Click+on+the+unsubscribe+link+at+the+bottom+of+every+email&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filters%5Bview%5D=wk-emails-new&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) [on](https://translate.wordpress.com/projects/wpcom/pt-br/default?filters%5Bterm%5D=Confirmed+subscription+to+posts+on&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filters%5Bview%5D=wk-emails-new&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) these [links](https://translate.wordpress.com/projects/wpcom/pt-br/default?filters%5Bterm%5D=Congratulations%2C+you+are+now+subscribed+to+the+site&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filters%5Bview%5D=wk-emails-new&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc). 

### To answer your questions: 

> but here is another one, this time is from the daily email sent... its all in english... 

It seems that the email you used here is related to a WordPress.com account and in your WordPress.com account, you're using English. 

If possible, please subscribe with a totally new email that you've never subscribed for any WordPress.com/Jetpack site, and this email should not link to any WordPress.com account. 

> even though the site is set to portuguese and i also changed to portuguese brazilian just to check, it comes all in english...

It seems that Portuguese (pt) and Portuguese Brazil (pt-br) make difference as I mentioned in `What I found out`. Going forward, I can suggest: 

1. If possible, please translate all missed translation strings for Portuguese (pt) in translate.wordpress.com (these strings are in our WordPress.com codebase so that's the only way!)
2. Otherwise, you can switch your site to Portuguese Brazil (pt-br). However, please wait until this language change is synced to our cache site, then our email system will pick up "pt-br" for emails. 

### Screenshots 

#### opt-in email 

![Screen Shot on 2020-04-13 at 21:39:29](https://user-images.githubusercontent.com/10045087/79129378-51a9b480-7dcf-11ea-8da4-1d8917ec4204.png)

#### confirmation email 

![Screen Shot on 2020-04-13 at 21:38:36](https://user-images.githubusercontent.com/10045087/79129956-5458d980-7dd0-11ea-90cf-ef8b43a452be.png)

**Comment by htdat** [comment]
@s2r: New post emails look good for me: 

- [Post 1](https://user-images.githubusercontent.com/10045087/79234986-3b662c00-7e95-11ea-9adc-54c58fc89e9c.png)
- [Post 2](https://user-images.githubusercontent.com/10045087/79235224-88e29900-7e95-11ea-8176-3bffd62bdc3c.png)

--- 

### In summary:

- I think we can close this issue here as I am not able to replicate it anymore by following these steps https://github.com/Automattic/jetpack/issues/1122#issuecomment-56966828
- If we see English strings in some emails, these strings are not yet translated for that specific language. We can check if a specific string in subscription-related emails is translated to a specific language in translate.wordpress.com

**Comment by s2r** [comment]
thanks @htdat its a bit tricky for me right now, but ill try and follow your instructions and also translate the remaining strings to portuguese, as a sidenote my wordpress account that is required to use jepack is in english because some of my sites are in english, and some of my sites are in french, spanish and portuguese, so im guessing ill have to have a different wordpress account for each language, is that correct? Thanks again.

**Comment by htdat** [comment]
@s2r: 
 
> as a sidenote my wordpress account that is required to use jepack is in english because some of my sites are in english, and some of my sites are in french, spanish and portuguese, so im guessing ill have to have a different wordpress account for each language, is that correct?

Generally, you do not need to set up different WordPress.com accounts for each language. However, if you want to get emails in the language of your site, yes, you may need to set up different WordPress.com accounts for different languages.

For followers, the logic is applied like the following: 

- If an email does not link to any WordPress.com account, we will send emails in the language of your site. 
- If an email has a WordPress.com account, we will send emails in the language of this WordPress.com account, which is set up in https://wordpress.com/me/account

I am closing this issue here. If you have any concern, feel free to reach our support team in https://jetpack.com/contact-support/

**Comment by donalirl** [comment]
> * If an email does not link to any WordPress.com account, we will send emails in the language of your site.

This does not seem to be happening, based on my recent experience with a French-language site.

**Steps to reproduce the issue**

1. Add a Subscription block to your site
2. Set your site's language to something other than English, such as French
3. Subscribe to the site using an email address not connected to a WordPress.com account
4. See the language of the subscription confirmation email is in English

**What I expected**
I expected the language of the email to be in the site's language, like French in the above example.

**What happened instead**
The email arrived in English.

As I understand it, if my WordPress.com account's interface language is set to French, I'll get the email in French. Or Russian is my account is set to Russian. That makes sense.

But for subscribers without a WordPress.com account, it makes more sense to have it in the site's language. This is because the subscriber is browsing a site in French, and subscribes to that site using a French subscription form, so it is a safe assumption that they understand French. Therefore, it's logical that they receive an email in French, not English.

**Screenshots**
Site language was set to French, yet the email arrived like this:
![Dj2CTS](https://user-images.githubusercontent.com/30727666/88354916-e2683700-cda5-11ea-9211-9937cafbe7db.png)

#22836384-hc

**Comment by chaitanyamsv** [comment]
I just had a customer report this in 25851701-hc. 

Their site language is French but the initial email subscription confirmation email is sent in English.

**Comment by ezebecke** [comment]
Another report with site language in French but confirmation email in English. 3758948-hc

**Comment by donalirl** [comment]
Encountered again in #28164615-hc, with the Chinese language.

I also recreated this again myself by:

1. Setting my site language to Spanish
2. Subscribing with a throwaway email address.

The email arrived with a Spanish subject line but English body content:
![image](https://user-images.githubusercontent.com/30727666/109891880-fa118180-7cdd-11eb-99f4-6daef8d94762.png)

**Comment by jeherve** [comment]
Also in #20374.

**Comment by blackjackkent** [comment]
I spent some time today trying to reproduce this issue, both in WPCOM and a Jetpack (JN) site, and am not able to reproduce it in either context.

Steps I followed:
- Set site on my non-A8C WPCOM account to French language.
- Subscribed to it in an incognito window with a throwaway email address.
- Result:
![image](https://user-images.githubusercontent.com/13437011/134417584-bcb13f01-1a93-44a5-be83-e121d1e74018.png)
- Opened confirmation link in same incognito tab, received confirmation email:
![image](https://user-images.githubusercontent.com/13437011/134417728-d0b65e12-c2cf-49ce-a9fa-ce3a5b7f0743.png)
- Repeated the above steps on a JN site connected to WPCOM with subscriptions enabled, using the post block widget. Same results:
![image](https://user-images.githubusercontent.com/13437011/134417867-34c970ae-327f-4361-b834-b341e46e7b75.png)
![image](https://user-images.githubusercontent.com/13437011/134417896-c6383077-32ef-466d-a09d-fa00f59ebfba.png)

@jeherve Do you know if this got resolved somewhere along the line? Or is there a reproduction step that users are following that I am missing?

**Comment by jeherve** [comment]
@blackjackkent Thanks for giving this a try! If you cannot reproduce anymore, I'd be inclined to close this issue. We can always reopen if this starts happening again in the future.

**Comment by AnjanaV93** [comment]
Another report in 7210835-zen

**Comment by the-misha** [comment]
Another user report: 7959576-zen

**Comment by pkuliga** [comment]
Contacted Team Global and it seems this email "is currently excluded from translation by our internal unused email detection system". Hope they will do sth with it 😄 

Slack link: p1714988274107409-slack-C02AED43D

**Comment by simison** [comment]
Gotcha, so a repeat of the earlier similar issue (p1706086276847489-slack-C02AED43D).

**Comment by simison** [comment]
This should be sorted:

- All notification templates are marked as active for translation in D147736-code and won't get excluded in future anymore
- Translations for welcome template are now reactivated
- Remaining translations for strings in progress https://translate.wordpress.com/projects/wpcom/-all-translated/9895/ 

Kudos @sdnunca for the work!
