### ISSUE TITLE
Image CDN: Webp on Firefox 65

### ISSUE THREAD

**Issue by dasZGFz** [Automattic/jetpack#11245]
https://hacks.mozilla.org/2019/01/firefox-65-webp-flexbox-inspector-new-tooling/

Firefox 65 now supports webp. Please include it on the auto-webp conversion. Thank you!

**Comment by jeherve** [comment]
Since Firefox followed the standards that were previously set for WebP, notably the use of the `Vary` header, it is already compatible with Jetpack's Image CDN. Nothing has to be changed: the image CDN already performs the WebP conversion today in Firefox

References:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1294490
- https://phabricator.services.mozilla.com/D8120
- https://code.trac.wordpress.org/browser/photon/class-image-processor.php

Here is an example:

![image](https://user-images.githubusercontent.com/426388/52118967-0535e700-2618-11e9-98b9-63d1a1c13bf3.png)

**Comment by dasZGFz** [comment]
Odd, it didn't seem to replicate on my computer but now it does. Thank you for your assistance.
