### ISSUE TITLE
Facebook Auto Post shows Published by WordPress

### ISSUE THREAD

**Issue by concevoir-anshul** [Automattic/jetpack#11259]
#### Steps to reproduce the issue

1.
2.
3.

**Comment by jeherve** [comment]
I believe you are referring to this message, appearing on Facebook Pages when using [Jetpack's Publicize feature](https://jetpack.com/support/publicize/facebook/):

![image](https://user-images.githubusercontent.com/426388/52213640-efcaf200-288f-11e9-8bdd-b180ff3d62b0.png)

To use your own site name or brand there, you’d have to use your own Facebook app. Since Jetpack aims to help you easily push your content to multiple Social Networks, we won’t ask you to create a Facebook developer account, create an app, change the app settings, copy app ID and secrets somewhere in your WordPress dashboard, and then monitor and update your app settings whenever Facebook's API is updated. That is not something we want you as a site owner to have to go through.

Instead of asking you to do that, we use our own app to publish to your Facebook Page. That is the app you see when you first connect your site to your Facebook, and it is the app you see here:
https://www.facebook.com/settings?tab=applications

The display of the update, and the name of the app are controlled by Facebook themselves. You would see a similar layout if you were to post with another app.

I hope this clarifies things a bit. If you have other questions, don't hesitate to reach out via [the Jetpack support forums](https://wordpress.org/support/plugin/jetpack/) or [this contact form](https://jetpack.com/contact-support/?rel=support).
