### ISSUE TITLE
Image Storage Similar To Video Storage

### ISSUE THREAD

**Issue by silentwisher** [Automattic/jetpack#11282]
I reached out to support about image hosting and they recommend me checking amazon aws, however from the research I did, it's frankly too complicated for me. It also sounds like its going to cost me more money. That said...
I was wondering if you guys could implement a future to store images uploaded to a wp-site on your servers in the same way you do for videos for the applicable account levels(example: premium accounts or professional). I think it would be a neat feature especially for sites that use lots of images.

**Comment by jeherve** [comment]
That is not something that's on our roadmap right now, but whenever we iterate on [our existing image CDN feature](https://jetpack.com/support/site-accelerator/) that may be an option we'll consider.

Until then, I would recommend using our Image CDN feature; while it won't help you save space on your server, it will help you save bandwidth as the images will copied over to our CDN and served from there instead of from your site.
