### ISSUE TITLE
Add Images Webp to CDN and Lazy Loading for images WEBP

### ISSUE THREAD

**Issue by fredroo** [Automattic/jetpack#11309]
#### Is your feature request related to a problem? Please describe.

After change, my images from JPG to WEBP lazy loading and CDN broken

Plugin **Lazy Load by WP Rocket** work very fine with webp images
You can see in: https://criativoaz.com/

please, someone, update this plugin to support WEBP images

#### Describe the solution you'd like

Add jetpack support to webp images format

**Comment by jeherve** [comment]
Looking at your site, something else appears to be causing the issue, as the image tag does not include any `src` parameter. This is not caused by Jetpack alone.

Jetpack's Lazy Images feature already supports images using this format. I was for example able to display your own image on a test site of mine with no issues:

![image](https://user-images.githubusercontent.com/426388/52504167-df947900-2be7-11e9-93f2-64a992d63c71.png)

As long as the images are added via the image inserter in your posts, you should have no issues displaying them in Jetpack.

Jetpack's Image CDN feature also supports WebP. In fact, it goes one step further. It converts jpg images to the WebP format for you, and only in the browsers that support that format. You can read more about it here:
https://jetpack.com/2015/12/04/webp-support/

You can see this in action with any image served by our CDN, if you load it in a browser that supports WebP, like Google Chrome or the latest version of Firefox. Here is an example:

https://i0.wp.com/criativoaz.com/wp-content/uploads/2018/06/modelo-de-cartao-de-visita-restaurante-e-marmitex-modelo-1-1024x819.jpg

<img width="1164" alt="screenshot 2019-02-08 at 21 36 06" src="https://user-images.githubusercontent.com/426388/52504800-d6a4a700-2be9-11e9-9f6c-236faece3927.png">

I would strongly recommend that you take this approach: instead of uploading WebP files to your site, upload jpg and let Jetpack's Image CDN take care of automatically converting those images for you. This way, if someone tries to load the image in a browser that does not support WebP, they will get a jpg image instead of a broken WebP image.

I hope this clarifies things a bit.
