### ISSUE TITLE
Related posts: Ignore category (not exclude!)

### ISSUE THREAD

**Issue by sebas77** [Automattic/jetpack#11316]
#### Is your feature request related to a problem? Please describe.
I use a special category, called featured, to show on the front page a set of features posts. However these posts may not be related at all, so it's frustrating when the related posts section show them

#### Describe the solution you'd like
If I try to exclude a category, the posts with that category are excluded even if they are actually related. Hence, I would like a solution that doesn't take the unwanted category in consideration, but won't exclude the post without considering the rest of the categories. A code snippet would be highly appreciated.

**Comment by jeherve** [comment]
I am not quite sure I understand. Is the problem that when looking at posts that belong to the "Featured" category, Jetpack's Related Posts often returns other posts from the "Featured" category, even if those posts are not really related to the original post?

If so, could you give us a few examples so we can take a closer look? Jetpack's Related Posts rely on multiple factors to choose Related Posts. One of those factors is the category, but Related Posts are also chosen based on the post content, the title, the tags, and more factors.

Thank you!

**Comment by sebas77** [comment]
I checked my website and I have to be honest, my problem is actually different. 

check this post: http://www.sebaslab.com/the-quest-for-maintainable-code-and-the-path-to-ecs/

check the related posts at the bottom.

only one has a category in common:  CODE DESIGN all the other posts do not have any category in common. You can verify it because the posts show the categories the belong to. 

so I must miss something actually.

**Comment by jeherve** [comment]
> only one has a category in common: CODE DESIGN all the other posts do not have any category in common.

Yes, that's to be expected. Jetpack's Related Posts feature doesn't just look at a post's category to determine related posts. It relies on multiple factors (post content, the title, the tags, and more). As a result, a post may belong to a different category and still be considered a related post by Jetpack.

Does that clarify things a bit?

**Comment by sebas77** [comment]
can I force to use the category then? Because there are posts much more relevant than the ones chose.

**Comment by jeherve** [comment]
> can I force to use the category then? 

I am afraid that's not really an option. Jetpack's Related Posts feature was built to rely on multiple factors, not just one, in order to provide much more relevant results.

If you find that the results are not relevant on your site, could you give me a few examples so we can take a closer look?

**Comment by sebas77** [comment]
Isn't the link I posted above a good example? 

in that article I discuss a topic that I have already discussed in the past. The first post chosen "The truth behind Inversion of Control – Part III – Entity Component System Design" is relevant for sure, actually is the best possible choice, but it should have then picked up other posts from the same series where I talk multiple times about the SOLID principles, while the posts chosen haven't much in common (except, maybe, the fact that I use the word ECS multiple times?)

**Comment by jeherve** [comment]
That's helpful, yes, thank you.

Here is a list of related posts for that specific post (ID `2096`). We display only the 3 first ones by default, but we can look at what other posts were considered relevant:

```json
{
	"total": 33,
	"max_score": 740.8667,
	"hits": [
		{
			"_score": 740.8667,
			"fields": {
				"post_id": 514,
				"blog_id": 86270956
			}
		},
		{
			"_score": 633.09204,
			"fields": {
				"post_id": 1331,
				"blog_id": 86270956
			}
		},
		{
			"_score": 613.8227,
			"fields": {
				"post_id": 1363,
				"blog_id": 86270956
			}
		},
		{
			"_score": 566.2063,
			"fields": {
				"post_id": 789,
				"blog_id": 86270956
			}
		},
		{
			"_score": 541.0816,
			"fields": {
				"post_id": 550,
				"blog_id": 86270956
			}
		},
		{
			"_score": 539.35724,
			"fields": {
				"post_id": 521,
				"blog_id": 86270956
			}
		},
		{
			"_score": 534.1886,
			"fields": {
				"post_id": 1594,
				"blog_id": 86270956
			}
		},
		{
			"_score": 517.04846,
			"fields": {
				"post_id": 1852,
				"blog_id": 86270956
			}
		},
		{
			"_score": 484.05814,
			"fields": {
				"post_id": 1495,
				"blog_id": 86270956
			}
		},
		{
			"_score": 327.00214,
			"fields": {
				"post_id": 200,
				"blog_id": 86270956
			}
		}
	]
}
```

You'll notice that some of the other articles in your series are in there, just not in 2nd or 3rd position:

http://www.sebaslab.com/ecs-design-to-achieve-true-inversion-of-flow-control/
http://www.sebaslab.com/the-truth-behind-inversion-of-control-part-iv-dependency-inversion-principle/
http://www.sebaslab.com/ioc-container-unity-part-1/

> except, maybe, the fact that I use the word ECS multiple times?

This plays a role, yes. It's mentioned within the post content, and when it is also present in the posts' title it even has a higher weigh in the algorithm. It is not the only factor, though, as we don't just pick related posts because a single word is mentioned multiple times.

Ultimately, if you wanted to change some of those related posts here, you could use some of the filters mentioned [here](https://jetpack.com/support/related-posts/customize-related-posts/) (to force-include specific posts, for example), or you could change the content of some of your posts (by modifying the title, for example).

If you are interested in this topic, and how our algorithm figures out what posts are the most relevant when calculating related posts, my colleague Xiao covered some of the inner working of Jetpack Related Posts in this video:
https://wordpress.tv/2014/10/16/xiao-yu-jetpack-related-posts-for-power-users/

I hope this clarifies things a bit.
