### ISSUE TITLE
External links impacted by Photon

### ISSUE THREAD

**Issue by RealCarFax** [Automattic/jetpack#11371]
Specifically tested this with PayPal buttons as outlined here: https://en.support.wordpress.com/paypal/

#### Steps to reproduce the issue

1. Insert this code into a page or post:
```
<a href="https://wordpress.com">
<img src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_LG.gif" alt="Buy Now Button" />
</a>
```

#### What I expected
On the backend it displays the Buy Now image properly, you can see it here: https://www.paypalobjects.com/en_US/i/btn/btn_buynow_LG.gif So I expect it to do the same on the frontend... not the case.

#### What happened instead
Broken image link on the actual site.
Here's a screenshot of how it looks for me: https://cloudup.com/cy_HtLUYQZM

If I try to open the image in a new tab I get this link: https://i0.wp.com/www.paypalobjects.com/en_US/i/btn/btn_buynow_LG.gif?w=700&ssl=1
and the error "Too many redirects".

Two examples:
WordPress.com hosted site (on Business plan): https://carissaattest.com/6891-2/
Pressable hosted site: https://carissawoo.mystagingwebsite.com/672-2/

**Comment by ash1eygrace** [comment]
Reopening this issue as I had a WordPress.com user in chat having this same issue with Photon and Dropbox images. 

#### Steps to reproduce the issue

1. Insert this Dropbox image code into a page or post:

```
<img src="https://www.dropbox.com/s/b4ezvx00mm35y7l/step29A.png?raw=1">
```

#### What I expected

On the back-end in the editor, it displays the images as expected, and I expect the images to show normally on the front-end. 

#### What happens instead

The broken image link shows instead of the images: https://cld.wthms.co/DLf9ay

If I try to open the image in a new tab I get the link https://i1.wp.com/www.dropbox.com/s/b4ezvx00mm35y7l/step29A.png?w=640&ssl=1

And the error: "We cannot complete this request, remote server returned an unexpected status code (400)" 

Screenshot for reference: https://cld.wthms.co/zvkZIb

#### Example post: 

https://happyash.co/2019/02/27/external-links-impacted-byphoton/
