### ISSUE TITLE
Publicize: Enable sharing to MeWe

### ISSUE THREAD

**Issue by gemmagarner** [Automattic/jetpack#11393]
Add support for sharing to MeWe via Publicize:

https://mewe.com/

Request in: https://wordpress.org/support/topic/mewe-support-for-sharing-and-publicize/

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Comment by DanTappan** [comment]
Why was this closed? The feature[*] is still needed. Closing due to "lack of activity" seems like a process error. How does a lower priority, but still necessary, enhancement request ever get implemented if the request gets closed just because no-one has worked on it yet. It's still something that's needed, at least if MeWe is to be a viable social media platform. Should someone mark this as high priority or what?

[*] originally requested at https://wordpress.org/support/topic/mewe-support-for-sharing-and-publicize/  and also marked closed there because the request had been entered in GitHub. Serious process failure.

**Comment by kraftbj** [comment]
Hi Dan,

Adding new social media platforms to Publicize is not something we have on the roadmap at this time. If/when we opt to explore adding platforms to Publicize, we can consider and reopen this issue.

There will always be legit enhancement requests that are out of scope or off roadmap for what an organization will explore. Publicize changes require server-side work on WordPress.com, so they are not enhancements where we can accept community contributions. Instead of leaving the issue open without updates and leaving the question without resolution to those asking, we opt to close the issue to provide some finality for the time being.

In the context of Sharing (the "share to" buttons after a post), those can be added via community contribution and we are always happy to review community-submitted PRs. I'm not opposed to having a separate issue tracking that specifically, as opposed to Publicize (where a new post is automatically shared to the social media platform).

**Comment by oaknorton** [comment]
I totally want this feature. FB has turned a lot of people off with it's heavy-handed censorship. Twitter as well. I would love the publicize feature to add a few of the other growing social media platforms like parler.com, mewe.com, and gab.com.

**Comment by meganallen208** [comment]
I really hope this is up for consideration again. There's a MASS exodus from Facebook and Twitter. Parler, MeWe, and Gab are seeing major growth.

**Comment by fresatomica** [comment]
Just noting another request here: https://twitter.com/KristinaBSc/status/1406183141522481156
