### ISSUE TITLE
[Shortcopy] Dashboard > My Plan: re-order features

### ISSUE THREAD

**Issue by folletto** [Automattic/jetpack#11533]
Refocusing Jetpack around Security and Performance.

This task is dependent on the updated Modules grid.
Design TBD

**Comment by keoshi** [comment]
This will no doubt require a much deeper content strategy work, but pointing out that we’ve started a PR for the changes on that page here:

https://github.com/Automattic/jetpack/pull/11505

This draws in cues from the changes we’ve done on the My Plan page for sites on the free plan, so we might want to update that as well in order to unify the messaging:

https://github.com/Automattic/jetpack/pull/11418
