### ISSUE TITLE
Sync is too Aggresive

### ISSUE THREAD

**Issue by bhubbard** [Automattic/jetpack#11553]
I have a site with custom syncing of users with a third party service, every time it runs it triggers new syncing in Jetpack filling up the options table. 

As a developer can I configure sync to not happen for specific items such as users?

How about settings a time window to sync specific items? Like only around midnight in my site timezone?

Is there a hook I can use to delay how often a sync runs?

**Comment by kraftbj** [comment]
Hi Brandon,

As a sludgehammer way to deactivate the users sync, you can use https://developer.jetpack.com/hooks/jetpack_sync_modules/ and unset the users module https://github.com/Automattic/jetpack/blob/7.1.1/sync/class.jetpack-sync-modules.php/#L38

Generally, sync listens for different events, so having a time to sync specific events would be problematic for you since we would store those things in the db longer until the sync process sends it up. Likewise, delaying how often sync runs is equally problematic since that would just delay how long items are stored in the queue. Right now, it sends up batches every five minutes, but it sends up stored changes from the various listeners ( https://developer.jetpack.com/hooks/jetpack_sync_incremental_sync_interval/ ).

To rephrase, when a synced event happens (`wp_insert_post` for example), we hook into that function to grab that something changed, store it in the queue, then on the next sync event (every five minutes per the above filter), send it up. So, there isn't a way to delay that without causing more issues like you're seeing.

How many users does the site have?

I'm going to mark this as closed since it isn't a bug but we can continue the conversation.

**Comment by bhubbard** [comment]
Currently the site has around 8,000 users. 

Might I suggest moving the queue to a different table. Our company uses `wp-queue` to handle these types of style syncs. 

https://github.com/wp-queue/wp-queue
