### ISSUE TITLE
i18n: Exception when calling fallback jed domain

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#11722]
`TypeError: Cannot read property 'jetpack' of undefined`

```html
<script type='text/javascript>
( function( domain, translations ) {
	var localeData = translations.locale_data[ domain ] || translations.locale_data.messages;
	localeData[""].domain = domain;
	wp.i18n.setLocaleData( localeData, domain );
} )( "jetpack", {"":{"domain":"jetpack","lang":"en"}} );
</script>
```

Possibly due to https://github.com/Automattic/jetpack/blob/cd1e9ea59c4df3f8e325661665b4aa39c18d044e/class.jetpack.php#L2606-L2612 per @sirreal 

#### Steps to reproduce the issue

1. Set up a new Jetpack site with the RC or master (cd1e9ea59c4df3f8e325661665b4aa39c18d044e): https://jurassic.ninja/create/?shortlived&jetpack-beta
1. Connect Jetpack
1. Open browser console. If you set "pause on exceptions" in the Chrome sources panel, you'll see the exact location the exception occurs.
1. Go to the new post page: /wp-admin/post-new.php
1. See the exception above that occurs in the script tag.

#### What I expected

No exceptions.

#### What happened instead

The exception happens.

**Comment by jeherve** [comment]
This also happens on WordPress.com with this patch (see my comment there):

D25726-code

The patch matches this Jetpack PR: #11603

**Comment by kraftbj** [comment]
FYI @zinigor - can you look into this?

**Comment by kraftbj** [comment]
@sirreal - Could you update this report with duplication steps?

**Comment by sirreal** [comment]
I've added steps to reproduce 👍

**Comment by kwight** [comment]
Returning `false` instead of the "valid empty JED locale" mentioned by @kraftbj allows `$json_translations` to be given a working default here: https://core.trac.wordpress.org/browser/trunk/src/wp-includes/class.wp-scripts.php#L544. This fixes the type error, but I'm not familiar enough to know if that breaks something else.

**Comment by sirreal** [comment]
- https://github.com/WordPress/WordPress/blob/ffc064d82d3f8bf7441aa7b1634ddaba9293857f/wp-includes/functions.wp-scripts.php#L226
- https://github.com/WordPress/WordPress/blob/ffc064d82d3f8bf7441aa7b1634ddaba9293857f/wp-includes/class.wp-scripts.php#L521
- https://github.com/WordPress/WordPress/blob/ffc064d82d3f8bf7441aa7b1634ddaba9293857f/wp-includes/class.wp-scripts.php#L542-L547

You can see the expected [fallback shape here](https://github.com/WordPress/WordPress/blob/ffc064d82d3f8bf7441aa7b1634ddaba9293857f/wp-includes/class.wp-scripts.php#L544-L547):

```php
		if ( ! $json_translations ) {
			// Register empty locale data object to ensure the domain still exists.
			$json_translations = '{ "locale_data": { "messages": { "": {} } } }';
		}
```

In Jetpack we're providing a fallback with a different shape:

```json
{
  "": {
    "domain": "jetpack",
    "lang": "en"
  }
}
```

That leaves me with 2 observations:
- Do we have good reason to add inline script rather than use [`wp_set_script_translations`](https://github.com/WordPress/WordPress/blob/ffc064d82d3f8bf7441aa7b1634ddaba9293857f/wp-includes/functions.wp-scripts.php#L219-L227) which will fall-back gracefully if the translation doesn't exist?
- The fallback should be updated to `'{ "locale_data": { "messages": { "": {} } } }';`

The current method for localization was added in #10362, one of the concerns is to avoid setting up the same Jetpack i18n locale data repeatedly. I don't know whether `wp_set_script_translations` will deduplicate as desired, but it's something to keep in mind.

**Comment by sirreal** [comment]
Fix for the fallback format appears to work: #11737

I think I had a bad assumption in my previous comment. I believe the erroring code is actually from a call to `wp_set_script_translations` and not the Gutenberg-specific i18n function I mentioned above.
