### ISSUE TITLE
Images in WooCommerce product short description are not cached by Photon module

### ISSUE THREAD

**Issue by leandroprz** [Automattic/jetpack#11732]
#### Steps to reproduce the issue
1. Create a new product in WooCommerce.
2. Add an image to the short description.
3. Enable Jetpack Photon module.
4. Check the product you created in step 1. The image is not served from WordPress servers.

Example: https://leandroperez.com.ar/tienda/copias-fine-art/los-seismiles-cfa/los-seismiles-12/

#### What I expected

The image to be picked up by WordPress servers.

#### What happened instead
The image is not being served by WordPress servers.

**Screenshots**

**Comment by jeherve** [comment]
This most likely happens because that short description is just plain HTML, it does not go through a filter. To solve that issue, you could use WooCommerce's `woocommerce_short_description` filter to customize the contents of the short description field. 

In this case, you would use that filter to apply Photon to the contents of that field, like so:

```php
function jeherve_photonize_woo_short_description_images( $short_description ) {
    if ( class_exists( 'Jetpack_Photon' ) ) {
        $short_description = Jetpack_Photon::filter_the_content( $short_description );
    }

    return $short_description;
}
add_filter( 'woocommerce_short_description', 'jeherve_photonize_woo_short_description_images' );
```

You can [add that code snippet to a functionality plugin](https://jetpack.com/support/adding-code-snippets/) on your site.
