### ISSUE TITLE
Ads Block: "Small Screens" instead of "Mobile"?

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#11765]
For the Ads block, would "hide on small screens" is something similar make more sense than "mobile"? For our purposes, an iPad is *not* triggering the mobile option, which has led to some confusion in beta testing.

#### Steps to reproduce the issue

1. Go to Block Editor, add Ad block (Jetpack + paid plan + ads enabled)
2. See "hide on mobile devices" toggle.

#### What I expected
Ads not to show on mobile devices, which could mean phone and tablets.

#### What happened instead
Only hidden on phones or devices of that form factor.

cc: @dbspringer @simison 

I'm adding a milestone of 7.2 so we at least consider it before release. I'm okay if we decide to delay any actual changes if so decided to make.

**Comment by dbspringer** [comment]
I'm actually not convinced this is "better" or clearer than other settings in Jetpack. For instance, what do we call Jetpack's version of Minileven? (Jetpack Mobile Theme) Does Jetpack Mobile Theme run on iPad views? (No)

If y'all are adamant about changing it them I'm fine with it, but I don't think "hide on small screens" is clearer either since if you have a small browser window they won't hide--it's only on mobile devices.

**Comment by dbspringer** [comment]
If we do want to change it perhaps something like "Small Devices" instead of "Small Screens?"

**Comment by simison** [comment]
cc @thomasguillot

**Comment by thomasguillot** [comment]
I thought about this a bit more and I agree with @dbspringer. "Hide on small screens" is not necessarily clearer than "Hide on mobile devices". In general when talking about "mobile devices" it's for smartphones, not tablets (mentioned on the [Mobile Theme](https://jetpack.com/support/mobile-theme/#how-do-i-see-the-mobile-theme-in-action-on-my-site))

**Comment by kraftbj** [comment]
Sounds good. Closing at wontfix. Thank you all!
