### ISSUE TITLE
Jetpack_Sync_Module_Users ArgumentCountError with WP Cassify

### ISSUE THREAD

**Issue by mdmuzzie** [Automattic/jetpack#11982]
#### Steps to reproduce the issue

1. On WordPress 5.1.1, install WP Cassify 2.1.8. and configure CAS as primary authentication method
2. Activate Jetpack 7.2 or 7.2.1
3. Attempt to log into /wp-admin via CAS
4. See WSOD and error 500 in logs
5. Disable Jetpack and observe normal login
6. Re-activate Jetpack and observe error upon login

Also, because CAS is our only allowed authentication source, we have disabled both "Allow users to log into this site using WordPress.com accounts" on all individual sites and "Allow individual site administrators to manage their own connections (connect and disconnect) to WordPress.com" (network)

#### What I expected
After log in through CAS, I expected to be redirected back to the WordPress dashboard.

#### What happened instead
I got a WSOD and an error 500 was logged. The URL still had the token from the CAS server.
https://example.princeton.edu/wp-admin/?ticket=ST-371779-yzh0UqS5qVGHCKwmMaQm-auth-a

Deleting the ticket parameter from the URL to reload /wp-admin allowed the page to load normally.

#### Error message
ArgumentCountError: Uncaught exception 'ArgumentCountError' with message 'Too few arguments to function Jetpack_Sync_Module_Users::wp_login_handler(), 1 passed in wp-includes/class-wp-hook.php on line 286 and exactly 2 expected' in wp-content/plugins/jetpack/sync/class.jetpack-sync-module-users.php:175

#### Stack trace
in Jetpack_Sync_Module_Users::wp_login_handler called at //wp-includes/class-wp-hook.php (286)
in WP_Hook::apply_filters called at /wp-includes/class-wp-hook.php (310)
in WP_Hook::do_action called at /wp-includes/plugin.php (465)
in do_action called at /wp-content/plugins/wp-cassify/classes/wp_cassify_utils.php (244)
in wp_cassify\WP_Cassify_Utils::wp_cassify_auth_user_wordpress called at /wp-content/plugins/wp-cassify/classes/wp_cassify_plugin.php (483)
in wp_cassify\WP_Cassify_Plugin::wp_cassify_grab_service_ticket called at /wp-includes/class-wp-hook.php (286)
in WP_Hook::apply_filters called at /wp-includes/class-wp-hook.php (310)
in WP_Hook::do_action called at /wp-includes/plugin.php (465)
in do_action called at /wp-settings.php (505)
in require_once called at /wp-config.php (268)
in require_once called at /wp-load.php (37)
in require_once called at /wp-admin/admin.php (34)
in require_once called at /wp-admin/index.php (10)

**Comment by jeherve** [comment]
I am afraid that is an issue with the WP Cassify plugin. The plugin, just like Jetpack, relies on a WordPress hook named `wp_login`. As mentioned in [the documentation](https://developer.wordpress.org/reference/hooks/wp_login/), that hook relies on 2 parameters. If you only provide one, you will cause conflicts with any other plugin that also uses the hook (like Jetpack).

WP Cassify only provides one, thus causing the issue. The problem was reported and acknowledged by the plugin author here:
https://wordpress.org/support/topic/fatal-error-uncaught-argumentcounterror-is-raised-during-login-w-wp_ver-4-9-6/

Unfortunately, it does not look like they've had the chance to fix the issue in their plugin yet. You can still see the issue on line 244 of `classes/wp_cassify_utils.php`:

`do_action( 'wp_login', $user->user_login );`

I would consequently recommend that you contact the plugin author to ask them for news; you could post in the forum thread above for example.
