### ISSUE TITLE
"Set up" link on backup & security cards send user to Calypso

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#11988]
![image](https://user-images.githubusercontent.com/1123119/55821475-dbd38480-5aba-11e9-8a3a-5ba06fdce7c0.png)

#### What happened
On a site with Jetpack Backup enabled, the "Set up" links send the user to Calypso and then installs/activates VaultPress.

#### What is expected
On sites with Jetpack Backup enabled, the links should take the user into the backup setup flow.

**Comment by eliorivero** [comment]
As discussed on Slack, this is correct because these are only shown when a site has `unavailable` as the status for their JP Backup. Such status is only caused by VP being active for that site. When VP is active, JP Backup is not.
https://github.com/Automattic/jetpack/blob/master/_inc/client/at-a-glance/backups.jsx#L216
