### ISSUE TITLE
Scrollbars in gif block

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#11995]
When adding a gif block, there are scrollbars:

![image](https://user-images.githubusercontent.com/87168/55858915-86aa7800-5b79-11e9-8ace-852ae418e990.png)

When hovering:

![image](https://user-images.githubusercontent.com/87168/55858923-8b6f2c00-5b79-11e9-8203-6e6d16486126.png)

That’s inside the Giphy `iframe` so outside our control. It may be a giphy change or regression;

it could also be that they expect us to add `scrolling="no"` and/or `iframe { overflow: hidden; }` to the iframe.

**Comment by scottsweb** [comment]
Just had a look at this, I only see the scroll bars when hovering over the GIF. This seems to be desired because it allows access to more related content below:

![Screenshot 2019-04-26 at 12 12 43](https://user-images.githubusercontent.com/411945/56804162-b49be780-681c-11e9-9686-258f44a6c415.png)

Do you happen to remember what theme this was tested on?

**Comment by simison** [comment]
This was with wpcom simple site using twenty nineteen. Seems like it was an issue at Giphy's end and they've since fixed it.

Thanks for checking!
