### ISSUE TITLE
Sharing: WhatsApp share button returned "The address wasn't understood" on Firefox

### ISSUE THREAD

**Issue by reginabally** [Automattic/jetpack#12069]
#### Steps to reproduce the issue

1. Add a WhatsApp share button to be shown on posts/pages.
2. On a Firefox browser, click on the WhatsApp share button on the post/page.
3. A new tab will be opened for the WhatsApp API page.

#### What I expected

The new tab should show the WhatsApp API page like this screenshot:

![](https://cld.wthms.co/jBNBz0+)

The correct URL should be something like this:

`https://api.whatsapp.com/send?text=Gallery%20Slideshow%20https%3A%2F%2Fpremiumplantestsite20190311.wordpress.com%2F2019%2F04%2F01%2Fgallery-slideshow%2F`

#### What happened instead

The error "The address wasn't understood" was shown on Firefox with invalid URL:

`whatsapp://send?text=Gallery%20Slideshow%20https%3A%2F%2Fpremiumplantestsite20190311.wordpress.com%2F2019%2F04%2F01%2Fgallery-slideshow%2F`

![](https://cld.wthms.co/8XBjul+)

*Note:* I can see a glimpse of the WhatsApp API page before Firefox showed me the error page.

#### Additional notes

The issue was originally reported in 1951401-zen.

**Comment by kbrown9** [comment]
I've confirmed that this bug occurs in Firefox 66.0.3.

It looks like this is caused by a Firefox bug. A [similar bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1444997) was reported for Firefox for Android.

A possible work-around is to use the "web.whatsapp.com/" URL for Firefox. This URL skips the send confirmation page shown in the screenshot provided by @reginabally . So, all other browsers should continue to use the "api.whatsapp.com/" URL.

@jeherve - what do you think of this approach? If it sounds OK, I can work on a PR.

**Comment by jeherve** [comment]
> A possible work-around is to use the "web.whatsapp.com/" URL for Firefox.

Does this work even when web.whatsapp.com is not set up in your browser (if you are not connected to Whatsapp there)?

**Comment by kbrown9** [comment]
> Does this work even when web.whatsapp.com is not set up in your browser (if you are not connected to Whatsapp there)?

Yes. My browser is not connected to Whatsapp, and the following URL displays a QR code in Firefox.

`https://web.whatsapp.com/send?text=Gallery%20Slideshow%20https%3A%2F%2Fpremiumplantestsite20190311.wordpress.com%2F2019%2F04%2F01%2Fgallery-slideshow%2F`

**Comment by jeherve** [comment]
Sounds like a good change then! 👍
