### ISSUE TITLE
Jetpack Manage: Notice has unwanted space below text and buttons lack space

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/jetpack#12103]
#### Steps to reproduce 

- Start with a Jetpack site.
- Turn off the Jetpack Manage module. _I tried to this from the `Access the full list of Jetpack modules available on your site.` section of Jetpack settings, but for some reasons I did not see Manage there. So, I ended up turning it off using CLI - `wp jetpack module deactivate manage`_
- Visit the wp-admin dashboard again.

#### What is expected 

A notice appears that suggests activating Jetpack Manage and the design looks good.

#### What happens instead 

The notice's design looks out of place. There is unwanted space below the notice text, and the buttons are placed next to each other without any space.

<img width="1746" alt="Screenshot 2019-04-20 at 19 00 01" src="https://user-images.githubusercontent.com/18581859/56457943-55168580-639f-11e9-8a1b-97bccc39ef4e.png">

**Comment by oskosk** [comment]
@arunsathiya thanks for the report. 

Context: For long now, Manage was going to be retired as a module and incorporated into Jetpack's core. This is going to happen finally with the relese of Jetpack 7.3, so this issue will no longer be relevant . Although for some versions now we had removed Manage from that listing, and that's why you couldn't find it.  Closing!

**Comment by arunsathiya** [comment]
That's very good to know, thank you! 🙌🏽
