### ISSUE TITLE
Slideshow block: Transform to slideshow removes all the images from the block

### ISSUE THREAD

**Issue by brbrr** [Automattic/jetpack#12255]
#### Steps to reproduce the issue

1. Start on `/wp-admin/post-new.php`
2. Add a gallery/tilled gallery block. Add few images to the block
3. Try to transform it to slideshow
4. See an empty slideshow block
5. Repeat steps 2-3 with Image block. See the image was persisted

#### What I expected
Image gallery copied to slideshow block

#### What happened instead
Image gallery got lost in transformation

**Screenshots**
![screencast 2019-05-03 12-35-36](https://user-images.githubusercontent.com/5654161/57130776-49fe2500-6da3-11e9-9ee7-8d5b8b13bc64.gif)

**Comment by simison** [comment]
The problem was that in the slideshow block, a "from tiled gallery to slideshow" transform passes whole `attributes` object to `getValidImages()` instead of `attributes.images` array:

https://github.com/Automattic/jetpack/blob/a4bfaa8786010fbf5bd0026bcd2a73963f8f9d52/extensions/blocks/slideshow/transforms.js#L39-L43
https://github.com/Automattic/jetpack/blob/a4bfaa8786010fbf5bd0026bcd2a73963f8f9d52/extensions/blocks/slideshow/transforms.js#L7-L15

Fixed in https://github.com/Automattic/jetpack/pull/12284
