### ISSUE TITLE
Video upload on Free plan gives wrong error message

### ISSUE THREAD

**Issue by marecar3** [Automattic/jetpack#12309]
**Describe the bug**

When I try to upload an mp4 video using Free account, it gives an wrong error message. I think that we need to change that as it is not clear for users why they can’t upload videos.

**To reproduce**
1. Download video from https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4
2. Create a new Gutenberg (Block Editor) Post
3. Add video block
4. Select Upload and pick a downloaded video from step 1.

**Expected behavior**
Wrong error message (or not clear for the real user)

**Screenshots**

<img width="1114" alt="Screen Shot 2019-05-08 at 11 17 46 AM" src="https://user-images.githubusercontent.com/28219092/57398330-b8285a80-719c-11e9-8c08-dc0721ce8691.png">

**Desktop (please complete the following information):**
 - OS **Mac OS Mojave : 10.14.3**
 - Browser **Chrome**
 - Version **73.0.3683.86 (Official Build) (64-bit)**

**Comment by jeherve** [comment]
That message comes from WordPress itself. Since your site does not use a paid Jetpack plan, the VideoPress module is inactive and the Video block is entirely managed by WordPress, with no interventions from Jetpack at all. 

If the error message does not sound right to you, and if you receive a different error message when you try to upload videos via Media > Add New, it could be an issue with the Video block, and I would then recommend that you report that issue here:
https://github.com/wordpress/gutenberg/issues/

I hope this clarifies things a bit.
