### ISSUE TITLE
SSO doesn't work on Sign-off

### ISSUE THREAD

**Issue by rosepajaroja** [Automattic/jetpack#12318]
#### Steps to reproduce the issue

User is switching between two different WordPress.com accounts on the same browser. 

1. Logs in User 1 to WordPress.com. 
2. Clicks WP Admin. 
3. Logs out user 1 from WordPress.com and close WP Admin. 
4. Logs in User 2 to WordPress.com. 
5. Clicks WP Admin, and User 1 is still logged in. 

**This causes an error "User Mismatched."

#### What I expected
If user 1 logs out from WordPress.com, it should be logged out from WP Admin, too. 

#### What happened instead
User 1 logs out from WordPress.com, but stays logged in to WP Admin. User 2 can log in to WordPress.com, but cannot be in the WP Admin with their own account. 

**Screenshots**
Issue only happens on AT site, watch here: https://www.loom.com/share/7e6f5a0949ec47ef9c41533b5be34edb

#### Actions taken
* Tested on Simple Sites, and the issue doesn't occur. 
* Disconnected and reconnected Jetpack

----------------------
Chat: HC-12633864
Follow-up Ticket: ZD-2015796
URL: https://elintransigente.com

**Comment by jeherve** [comment]
This is the expected behaviour I am afraid. When logging out of WordPress.com, you do not get logged out of services linked to your WordPress.com account.

Previous discussion on this topic:
p3btAN-LW-p2

We had somehow worked around that problem by making the Log out action in the WordPress.com toolbar sign you out of both services at once, in #6791.

However we have now removed the option to sign out via the WordPress.com toolbar (see #11766), so you can't log out of both services at once anymore.

I would recommend bringing this up at p9Jlb4-R8-p2 as one potential downside of the change in the log in flow.
