### ISSUE TITLE
Search: Support Stemming

### ISSUE THREAD

**Issue by jenkoian** [Automattic/jetpack#12333]
#### Is your feature request related to a problem? Please describe.

I want to be able to return results for the root form of the word. For example I want to be able to search for 'skate' and return content with a title of 'skateboard'.

#### Describe the solution you'd like

I would like to add some stemming analysis so we're able to return results in this manner.

#### Describe alternatives you've considered

Alternatives I have at present involve partial matching (regexp queries for example) which seems to diminish the power of elasticsearch a little from what I understand.

#### Additional context

You can read more about stemming in elasticsearch here: https://www.elastic.co/guide/en/elasticsearch/guide/master/stemming.html

**Comment by jeherve** [comment]
Related: #8895

**Comment by gibrown** [comment]
Yep, so this is more about decompounding than stemming. We do run some stemming already.

It is a good example added some detailed thoughts on https://github.com/Automattic/jetpack/issues/8895#issuecomment-491376589

I'm going to close this issue in favor of that one. I doubt we'll be working directly on decompounding this year. For your particular example though we are currently working on search as you type which would also solve this example since it would match the beginning of the word. Just getting started on it though so it will be a number of months.

**Comment by jenkoian** [comment]
> We do run some stemming already.

Are you able to elaborate or point me in the direction of some docs?

**Comment by jenkoian** [comment]
> Yep, so this is more about decompounding than stemming.

Don't get hung up on the particular I gave, other examples I'm looking to support would be:

- Searching for 'plum' brining back results for 'plumber'
- Search for 'choc' bringing back results for 'chocolate' 

I guess what I'm suggesting is not just decompounding something like 'skateboard' into 'skate' and 'board' but taking to the root form of the word. So my examples above with decompounding might not give you what I'd expect from stemming, i.e. 'plum' (stemming) over 'plumb' (decompounding) and 'choc' over 'choco'.

I probably could have chosen some better examples, but that's just off the top of my head for now.

**Comment by gibrown** [comment]
I wrote up a lot of my thoughts on stemming a while ago. Some of the details have changed, but my opinions are mostly the same: https://greg.blog/2013/05/01/three-principles-for-multilingal-indexing-in-elasticsearch/

I still wouldn't call that stemming, since "plum" isn't really the root of "plumber", the root is "plumb". https://en.wikipedia.org/wiki/Stemming

In any case we do very minimal stemming (stripping plurals only) as mentioned in that post above. Generally stripping further has been found to hurt search results and make them noisier.

It sounds a lot like you are looking for full prefix matching of the terms. We will end up there with search as you type. Right now the index isn't built to perform those searches efficiently.

The exact English analyzers we are using are here: https://github.com/Automattic/wpes-lib/blob/master/src/common/class.wpes-analyzer-builder.php#L82
