### ISSUE TITLE
An embed from videopress.com gives a mixed content warning on Firefox

### ISSUE THREAD

**Issue by enkrates** [Automattic/jetpack#124]
I run my wordpress with SSL and I got a mixed content warning while looking at the Jetpack admin page. The Firefox developer tools said - 

"Blocked loading mixed active content http://s0.videopress.com/player.swf?v=1.02"

So, I searched for that URL in my Jetpack source and found it in just one place, line 336 in module-info.php in the function sharedaddy_more_info_connected(). Normally, I could just change the url and leave out the 'http' to make it compatible with an SSL page, but in this case using the videopress url with https triggers another warning, also, as it seems to use a CDN SSL certificate which really brings us back to the original problem of broken under SSL.

So, normally I would just submit a pull request with a better url, but in this case I don't know what a more secure url would be for videopress.com. As a result, I can only submit an issue and ask the folks who know more than I do to use an SSL compatible url.

**Comment by EnigmaSolved** [comment]
@georgestephanis The `"NetworkError: 410 Gone - https://videos.files.wordpress.com/crossdomain.xml"` error via SSL seems to be fixed (ie, that NetworkError is no longer present).

Also, the thumbnail image is now properly scaled to fill the player when using SSL.

I'm also not seeing any mixed content warnings in Jetpack.

So I'm thinking maybe this issue can be closed now (unless I'm missing something)?

**Comment by tlctara** [comment]
I have inherited a site that has a bunch of videos embedded using the VideoPress plugin in this format:

[youtube id="gaxOMN3OOR8" width="620" height="360"]

I recently installed an SSL on the site, and since that time, the videos no linger show on the pages. It looks like the plugin is not forcing/allowing an https link for these shortcodes.

I have had to revoke the SSL as an immeidate solution to this, but wanted to let you know about this issue as I can't find any setting that will allow the plugin to force a redirect to https?

In case you get this before the SSL comes off you can see the empty space here:
https://travelwithagingparents.com/why-mom-likes-to-travel-with-me-video/

and the same page on the staging site which has no ssl:
http://9ca.b57.myftpupload.com/why-mom-likes-to-travel-with-me-video/

**Comment by georgestephanis** [comment]
@tlctara I'm seeing a SSL cipher suite issue when I try to pull up the link in question --

<img width="964" alt="2016-03-11 19_29_50-https___travelwithagingparents com_why-mom-likes-to-travel-with-me-video_ failed" src="https://cloud.githubusercontent.com/assets/941023/13719152/ad38140e-e7bf-11e5-9367-eb0daf4b2e49.png">

That being said, the issue you're having seems to be with the YouTube shortcode bundled in Jetpack -- nothing to do with VideoPress.

Our YouTube shortcode is mostly based off using the URL to the video -- https://en.support.wordpress.com/videos/youtube/ -- if you are using shortcodes that use that id attribute as you posted above, my guess is that they're being processed through a separate plugin -- not Jetpack -- that may be hijacking the [youtube] shortcode and taking priority over Jetpack's implementation.

**Comment by tlctara** [comment]
Thanks. Client told me she had used the plugin to insert the YouTube IDs ... I had checked it and don't see any other related plugin, saw this support thread and assumed it was related. Sorry to bother you!

**Comment by jeherve** [comment]
Closing this as `wontfix` since the legacy flash player is slowly being deprecated, and won't be worked on much in the future.

Related: #2500

**Comment by EnigmaSolved** [comment]
Well, last I checked (https://github.com/Automattic/jetpack/issues/124#issuecomment-75286236) the issue was resolved anyway. :)

**Comment by jeherve** [comment]
Even better :) 👍
