### ISSUE TITLE
Checklist: Single CTA and hide on removal

### ISSUE THREAD

**Issue by sirreal** [Automattic/jetpack#12405]
If we have time here, I think it would be prudent to build some logic in. The color is less important. What's important is that we only have one primary CTA show at any given time. 

Now that we're implementing the checklist I'd argue the only primary CTA should be the "continue jetpack setup" button. Let's make it blue for now and make all other CTAs white.

Once the jetpack checklist has been completed, that button should disappear completely. then we can make that "view settings" button the primary CTA.

_Originally posted by @jeffgolenski in https://github.com/Automattic/jetpack/pull/12277_

**Comment by sirreal** [comment]
#12430 removed all the feature primary buttons

**Comment by simison** [comment]
I think this can be closed since the 2nd competing blue CTA will go away when we remove jumpstart and feature primary buttons are now handled:

<img width="1105" alt="Screenshot 2019-06-04 at 17 24 54" src="https://user-images.githubusercontent.com/87168/58887123-b5fae280-86ed-11e9-9448-631b78750c0a.png">
