### ISSUE TITLE
When sharing content to social media with Jetpack, links are not correct with WPML

### ISSUE THREAD

**Issue by vukvukovich** [Automattic/jetpack#12437]
#### Steps to reproduce the issue

1. install WP + WPML, 2 languages
2. install Jetpack
3. activate the sharing module
4. connect a social media account
5. create a post and share it (or set the module to automatic sharing)
6. translate the post and share it
7. the link points to the original post

#### What I expected

It is expected for link to point to the translated post. `Ex. example.com/sr/clanak`

#### What happened instead
The link points to the original post `Ex. example.com/post`

**Screenshots**
Here is the Twitter account I've tested issue with. You'll see original and translated posts tweets. https://twitter.com/V02218182

**Comment by jeherve** [comment]
> translate the post and share it

Could you walk me through the steps you follow to share that post once it's been translated?

**Comment by vukvukovich** [comment]
Hi @jeherve. Translated post is same as original, before you publish it just mark checkbox to share (pubilicize) it.

**Comment by jeherve** [comment]
Thanks for the extra details. In those cases, does the original post get shared by Jetpack? That's what I would expect. However, Jetpack wasn't built to also send updates about additional content created by other plugins like WPML. Since the translated posts aren't regular posts like the ones you may find on a WordPress installation without any plugins and aren't custom post types either, Jetpack does not support them. 

Since this is not something Jetpack can support out of the box, I'm afraid I can only recommend that you share those posts manually.
