### ISSUE TITLE
Hide WooCommerce Admin Events in Activity Log

### ISSUE THREAD

**Issue by tijosh** [Automattic/jetpack#12714]
#### Steps to reproduce the issue

1. Ensure Jetpack is connected to the site
2. With WooCommerce 3.6 or higher installed, install and activate the [WooCommerce Admin plugin](https://wordpress.org/plugins/woocommerce-admin/)
3. Head to Jetpack Activity Log

#### What I expected

Expected to see nothing related to WooCommerce Admin

#### What happened instead

Multiple events are logged related to WooCommerce Admin:

![Screenshot](https://cld.wthms.co/naufhQ+)

If you click on the event, you're taken to a blank page:

![Screenshot](https://cld.wthms.co/2U1MEk+)

Context:

#13441980-hc
#2111289-zen

**Comment by timmyc** [comment]
If I had to venture a guess here, this is happening due to ActionScheduler being a custom post type and activity log is picking up on all of the post creation/modification that ActionScheduler is doing. I would imagine there is a way to filter ActivityLog events for certain custom post types to prevent this from happening...

**Comment by jeherve** [comment]
> I would imagine there is a way to filter ActivityLog events for certain custom post types to prevent this from happening...

There should be, yes. We should decide if we want that information to not be synchronized with WordPress.com at all, or if we want it synchronized but not displayed.

I am not really familiar enough with ActionScheduler to make that call though. Is that some information you would need to query from WordPress.com in places like the Woo mobile app?

**Comment by timmyc** [comment]
I don't personally see any value in synchronizing ActionScheduler posts to WordPress.com myself. Looking ahead, version 3.0 of ActionScheduler will be moving away from using CPTs and will use a custom db table to track jobs.

**Comment by jeherve** [comment]
@lezama Would adding the post type to this list be enough to solve that issue?
https://github.com/Automattic/jetpack/blob/3f5d42c4f18b1ae13651c58c9f00d05baa40a040/packages/sync/legacy/class.jetpack-sync-defaults.php#L326

**Comment by jeremyb1** [comment]
Hey @jeherve and @timmyc - the customer came back and said she was getting scared by the amount of actions being recorded in their Activity Log. I sent a response to calm them down but I was wondering if there is a way to revert the customer's view from Woo Admin to the old Woo view in the /wp-admin sidebar. If there is, let me know as that could help the customer here.

Customer response came from 2111289-zd again

**Comment by jeherve** [comment]
> I was wondering if there is a way to revert the customer's view from Woo Admin to the old Woo view in the /wp-admin sidebar.

You could do that by deactivating the Woo Admin plugin, but that won't stop all of the events they see in the activity log. Only some of them are related to the Woo Admin plugin. WooCommerce itself will trigger some of those.

As you mentioned in your last email to the customer, this is indeed nothing to be worried about. Those are routine maintenance operations performed by WooCommerce itself, or by Woocommerce Admin, to make sure the data in the dashboard stays up to date. 

I can see how this could be confusing though, since the activity log reports all those actions without really explaining what they are. We'll see about stopping displaying those.

@timmyc If you get the chance to test #12830 on a Woo site with some traffic and the Woo mobile app to make sure that does not break anything, I'd appreciate it!

Thank you!

**Comment by timmyc** [comment]
@jeremyb1 

> but I was wondering if there is a way to revert the customer's view from Woo Admin to the old Woo view in the /wp-admin sidebar. If there is, let me know as that could help the customer here.

If the user disables the WooCommerce Admin plugin the ActionScheduler activity log entries will go away.

Alternatively, if we can just explain to them that this is how WooCommerce processes data in the background to build out reporting tools, that might be the easiest way to resolve the problem.

Right now the plan is for ActionScheduler to move away from using Custom Post Types so I'd imagine this problem is just going to "fix itself" within the next few months ( sorry I don't have a firm timeline on this change being done ). Since we only have one user reporting this as a negative experience, I'm not certain if it is worth making code changes for. Just my .02 though.

**Comment by jeherve** [comment]
> If the user disables the WooCommerce Admin plugin the ActionScheduler activity log entries will go away.

I'm afraid some will stay. Things like the Marketplace suggestions also rely on ActionScheduler, afaik?

**Comment by timmyc** [comment]
> I'm afraid some will stay. Things like the Marketplace suggestions also rely on ActionScheduler, afaik?

Correct, and webhooks in Woo core too, along with other extensions like Subscriptions.
