### ISSUE TITLE
Tiled Galleries: column option not available for Thumbnail Grid Gallery types.

### ISSUE THREAD

**Issue by jenhooks** [Automattic/jetpack#1287]
In 1983051-t it was reported that the option to choose the number of columns in a Thumbnail Grid gallery was not there. 

Since column options are not available with Tiled Mosaic galleries, if the Tiled Galleries module in Jetpack is active, the ability to choose the column number for all galleries is automatically not displayed. In order for the user to be able to toggle the number of columns, they need to go to Settings > Media, and deselect "Display all your gallery pictures in a cool mosaic." Having that option "on" overwrites how gallery types work:

https://github.com/Automattic/jetpack/blob/3.2/modules/tiled-gallery/tiled-gallery.php#L163

This doesn't allow for a check of what type of gallery is being selected (and subsequently prevents the display of gallery type-specific options):

https://github.com/Automattic/jetpack/blob/3.2/_inc/gallery-settings.js#L19

I was able to reproduce in my Sandbox. This is the view when "Display all your gallery pictures in a cool mosaic." is selected on Settings > Media:

![no_column_options](https://cloud.githubusercontent.com/assets/7585054/4994600/87fa1e46-6988-11e4-8730-17186b2e4d4c.png)

Deselecting that option in Settings > Media allows the columns option to reappear: 

![columns_option_returns](https://cloud.githubusercontent.com/assets/7585054/4994613/99461466-6988-11e4-8bf5-cf80c505d10c.png)

We should allow the column option appear by default when Thumbnail Grid is the selected gallery type, even if the Tiled Mosaic option is selected in Settings > Media.

**Comment by aheckler** [comment]
IMHO, I don't think this is a bug. (Or at least, the bug is something different than what is described here.)

With the Tiled Galleries module active and the "Tiled Galleries" option in Settings > Media unchecked, I can still change the number of columns just fine.

With the Tiled Galleries module active and the "Tiled Galleries" option in Settings > Media checked, @jenhooks is correct: I do not see the option to change the number of columns if I happen to switch gallery types to, for example, thumbnail grid. 

*But that is as it should be*, since the option in Settings > Media clearly says:

> Display **all** your gallery pictures in a cool mosaic.

Not "some", not "Tiled Mosaic only", but "all". 

So in fact the bug seems to be that this option exists at all:

![screen shot 2015-02-17 at 2 33 09 pm](https://cloud.githubusercontent.com/assets/5512652/6235627/e9e6ecc6-b6b1-11e4-9732-61cb0bff3e2c.png)

That is, why even present Type dropdown to the user if they have clearly selected, under Settings > Media, that they want **all** galleries displayed as the Tiled Mosaic type?

Having said that, I don't think we should remove the Type option if the setting under Settings > Media is checked. Users expect it to be there, and hiding it based on an obscure checkbox in wp-admin isn't a good experience.

I think we should instead remove the settings here:

https://github.com/Automattic/jetpack/blob/3.3.1/modules/tiled-gallery/tiled-gallery.php#L185-206

... and make `tiles_enabled()` ([ref](https://github.com/Automattic/jetpack/blob/3.3.1/modules/tiled-gallery/tiled-gallery.php#L21-24)) simply return true if the Tiled Galleries module is active. Finally, we could stop taking over the default gallery type.

**Comment by aheckler** [comment]
Ignore my stupid comment above; I fixed this (hopefully anyway):

https://github.com/Automattic/jetpack/pull/2267
