### ISSUE TITLE
Clicking "Make your site faster" from the "My Plan" page in wp-admin unnecessarily leads to wordpress.com page

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#12899]
#### Steps to reproduce the issue

1. Go to /wp-admin/admin.php?page=jetpack#/my-plan
2. Click on 'Make your site faster' under "Optimize Performance" box
3. I am taken to https://wordpress.com/settings/performance/www.goldsounds.com
4. ... however Jetpack has all these same settings at /wp-admin/admin.php?page=jetpack#/performance, right there on my site!

#### What I expected
To go to the wp-admin settings if available

#### What happened instead
Was taken to Calypso, which is a pain to get back to my site from

**Comment by simison** [comment]
I agree, as long as the link just bluntly drops the customer to settings page without any further guidance, it's better to drop them in equivalent in Jetpack dash instead of Calypso.

In the longer term, might make sense to bring customer to onboarding checklist (`https://wordpress.com/plans/my-plan/SITE?checklist`), where they can be guided to set this stuff up and easily find their way to WP Admin.

cc @jeffgolenski
