### ISSUE TITLE
Premium block flows: ensure texts are translated

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#12966]
Since .com is lacking support for `wp.i18n` translations (https://github.com/Automattic/wp-calypso/issues/32418), we might need to pass strings for the upgrade nudge from the backend to ensure they get translated for simple sites.

See an example here:

https://github.com/Automattic/jetpack/blob/3c16fe75b1461b2370d9a2fc22e619b3af36345f/modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php#L272-L286

Alternatively, we could decide to just stick to JS since blocks aren't getting translated either.

**Comment by ockham** [comment]
@simison Is it worth working around the more general issue for the specific case of the upgrade nudge (which AFAIU we'll need to revert once the general issue is solved)? The lack of translations also affects pretty much all other Jetpack block strings on WP.com, so shouldn't we rather push for/help with getting translations to work there? (In other words -- why does the upgrade nudge deserve translations more than other UI elements? Because it can earn us money? :sweat_smile: :thinking: )

**Comment by simison** [comment]
Convo pxLjZ-5oR-p2

**Comment by simison** [comment]
I agree this should just work on .com, but meanwhile, if we can fix it for this banner with 3 lines of PHP, it might make sense. If it's more involved, prolly not.
