### ISSUE TITLE
Feature Request: Toggle Button to 'Offload' Media Library

### ISSUE THREAD

**Issue by backpackingseries** [Automattic/jetpack#12972]
#### Is your feature request related to a problem? Please describe.

Rewuest redirected from [Jetpack Support Forum](https://wordpress.org/support/topic/feature-request-a-toggle-button-to-offload-media-library/) 

In the BAU scenario, 10-11 thumbnails per image (created by theme and WorsPress) eat up resources. Operations such as backups and security scanning takes longer and, especially on shared hosting, this can impact site performance.

#### Describe the solution you'd like

Three months ago, I initiated a project to test leveraging Photon to ‘offload’ the media library to WordPress dot com servers. Jetpack support team confirmed [here](https://wordpress.org/support/topic/photon-scaled-images/)  that the approach I took is okay. The test is successful and I have rolled out the changes to production.

This approach has saved our site about 500% disk space resulting in quick backups, faster security scans, and better loading speed for site visitors.

I wonder whether this option could be included in a future release of Jetpack as a toggle button to say,

> Offload Media Library

The toggle could activate a standard WordPress filter to disable thumbnails (while retaining the original image) on the server, while Photon takes care of the rest (scaling images on-the-fly, delivering WebP images, etc.).

WordPress Filter to Disable Thumbnails (Credit: StackExchange)
add_filter( 'intermediate_image_sizes', '__return_empty_array', 999 );

#### Describe alternatives you've considered

Moving to a bigger server with more resources (more php threads) - an expensive solution for relatively small sites.

#### Additional context

Documented my experience here. 
https://www.unakriti.com/how-to-optimize-images-and-offload-media-library/

Kind regards 
Abhijeet Deshpande

**Comment by jeherve** [comment]
Thanks for the suggestion! That's a nice use-case of Jetpack's Image CDN, and it's nice of you to share your experience so others can give it a try as well.

We are not planning on adding that feature to Jetpack right now though.

Making that change has an inconvenient: once you don't generate the intermediate image sizes anymore, you are 100% relying on Jetpack's Image CDN to take care of your sites' images for you. That's fine, but that also means that you can't just deactivate the feature or the plugin anymore (you would have to use a plugin like [Regenerate Thumbnails](https://wordpress.org/plugins/regenerate-thumbnails/) to be able to get all your images back, and I assume it would take a lot of time since you already have quite a lot of images). You have lost some of the flexibility WordPress offers and are "locked in" with a plugin. This is not something we want to offer to site owners out of the box right now. We do not want to lock in anyone, you should be free to deactivate the features you don't want or even move to a different plugin without breaking anything on your site.
That does not mean you cannot do that on your own with your own plugin though; it is a great idea, and if you are okay with the inconvenient I mentioned above it's fine!

**Comment by backpackingseries** [comment]
Thank much for the consideration. 

The lockin effect is already present with Jetpack - because once you disable it, things like social share count is lost forever.

Besides, offloading media library with any other plugin (such as one made for Amazon) would have similar impact - in that removing it would necessiate regenerating thumbnails.

The benefit here (of retaining your shared host) seems to outweigh the cost (of regenerating thumbnails).

**Comment by macmanx2** [comment]
> The lockin effect is already present with Jetpack - because once you disable it, things like social share count is lost forever.

We actually pull the share counts from the social networks’ API’s and don’t store any of that data ourselves, so as long as you use a sharing plugin that uses the same API’s, you won’t lose your share counts.

**Comment by backpackingseries** [comment]
Thanks for the clarification about social share counts.

I guess then its a question of a lockin with a theme vs a plugin. 

The proposed option helps transition between themes easier (without the need to regenerate thumbnails)

Thanks again for the consideration.

Kind regards,
