### ISSUE TITLE
Premium block flows: border/spacing adjustments

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#13007]
A list of small style fixes we should do — follow up from https://github.com/Automattic/jetpack/pull/12963:

- [ ] Border/margin/padding funkiness on hover:
    <img width="558" alt="Screenshot 2019-07-05 at 15 56 01" src="https://user-images.githubusercontent.com/87168/60723836-6fdbad80-9f3d-11e9-9f1f-1fff88b69261.png">

- [ ] And the banner seems to "jump" visually ~1-2px when selecting the block so it doesn't feel as smooth as it does for "missing block" and similar core alerts. Basically, you see some movement in the block when selecting it, while you don't see this movement with other blocks.

**Comment by ockham** [comment]
Gutenberg uses selectors like
-  `.block-editor-block-list__layout .block-editor-block-list__block .block-editor-block-list__block-edit:before` 
- `.block-editor-block-list__layout .block-editor-block-list__block.has-warning .block-editor-block-list__block-edit:before`

and absolute positioning to style the thin frame around the entire block, whereas we're currently imitating that with our `.jetpack-paid-block__wrapper:not( .is-selected )` selector plus padding and negative margins to achieve the bottom and right borders in the screenshot above.

Our approach doesn't seem greatly compatible with the 'highlight/selected' border on the left-hand side.

It'd be neat to use the same kind of selector and styling as Gutenberg itself, but it might be a bit hard to select that `:before` thing, since it's wrapped _around_ our own block elements.

**Comment by ockham** [comment]
> It'd be neat to use the same kind of selector and styling as Gutenberg itself, but it might be a bit hard to select that `:before` thing, since it's wrapped around our own block elements.

This could work: https://developer.wordpress.org/block-editor/developers/filters/block-filters/#block-style-variations

> Block Style Variations allow providing alternative styles to existing blocks. They work by adding a className to the block’s wrapper.

**Comment by ockham** [comment]
Oh, those are user-selectable styles, so nothing hardwired. Not what we want then.

But maybe this: https://developer.wordpress.org/block-editor/developers/filters/block-filters/#editor-blocklistblock

**Comment by ockham** [comment]
Oh nice, that works. And we'll just inject the `has-warning` class name to automatically get Gutenberg's styling.

Spinning up a PR.
