### ISSUE TITLE
Simple payments: change X icon to star when block isn't available

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#13040]
When Simple payments block is in post content but the site doesn't have a paid plan, administrators of the site see this nudge on the frontend of the site:

<img width="696" alt="image" src="https://user-images.githubusercontent.com/87168/61116706-a4032100-a49d-11e9-919e-f1e5cc4de045.png">

This is scary and "X" can look like the message is dismissable. We should instead use the star and more soft language like in upgrade nudge banner:

<img width="849" alt="Screenshot 2019-07-12 at 12 12 18" src="https://user-images.githubusercontent.com/87168/61116973-50450780-a49e-11e9-9f35-8cf37dc2d7e8.png">

Later on, this could be extracted to generic PHP function that can be used with other premium blocks as well.

Note that this badge is visible for both Jetpack self-hosted and .com sites.

More copy ideas in https://github.com/Automattic/jetpack/issues/12946#issuecomment-508745047

We should also ensure this banner looks good on pages with dark backgrounds.

cc @fditrapani 

via p58i-7Tf-p2#comment-42407

**Comment by fditrapani** [comment]
The new banner looks much better! 

cc @shaunandrews

**Comment by ockham** [comment]
> Later on, this could be extracted to generic PHP function that can be used with other premium blocks as well.

Indeed. Note that even now, the string from the current message is already duplicated:

https://github.com/Automattic/jetpack/blob/27afef4f91df4b99bb1d05a8e3a288c4fe5bc568/modules/simple-payments/simple-payments.php#L204

https://github.com/Automattic/jetpack/blob/41924cee7d46aea5a4d3c92d7fbb91857d68dfcb/modules/widgets/simple-payments/admin-warning.php#L9

It would make a ton of sense to centralize the shared strings and messages somewhere when fixing this, and ideally to parametrize with block and plan names.

> <img width="849" alt="Screenshot 2019-07-12 at 12 12 18" src="https://user-images.githubusercontent.com/87168/61116973-50450780-a49e-11e9-9f35-8cf37dc2d7e8.png">

Note that we might not want to re-use the exact same copy, since

1. We might want to continue to re-assure the user that only _they_ (i.e. site admins) are seeing the message, but their visitors aren't
2. We might want to mention the disabled block by name in the message, since unlike in the editor, the block itself isn't visible at all.

**Comment by shaunandrews** [comment]
I'm not sure we should be using the star icon. Its associated with likes elsewhere, and doesn't really have much to do with plans. Perhaps a more generic info icon would be better.

<img width="50" alt="image" src="https://user-images.githubusercontent.com/191598/61239776-abc8fc80-a70d-11e9-86b9-ef028e1d8b0a.png">

<img width="60" alt="image" src="https://user-images.githubusercontent.com/191598/61239792-b71c2800-a70d-11e9-812b-229d62a1e59f.png">

**Comment by ockham** [comment]
FWIW, the `UpgradeNudge` component in Calypso -- after which we modeled the one seen in the block editor -- currently uses the star, see https://wpcalypso.wordpress.com/devdocs/blocks/upgrade-nudge. This issue is mostly concerned with consistency between that editor nudge, and the one in the frontend, which currently looks vastly different.
