### ISSUE TITLE
Facebook sharing is really awkward and primitive. Featured image not displayed and more

### ISSUE THREAD

**Issue by chjan** [Automattic/jetpack#13055]
#### Steps to reproduce the issue

1. go to noach.one/blog, select a blog, use the share button at bottom of blog. The awkward result will be that this plugin creates a "cutout" of the blog logo, and the text is not good. 
2.
3.

#### What I expected

What I would wish for:

1.	Feature to edit and/or format text prior to sharing 
2.	Feature to select picture, typical not the general blog logo picture, but one of the following:

a) featured image
b) any photo detected in the blog

Here in 2019, I suggest this is beyond doubt mandatory!

3.	Optionally; Feature to save a “default” for my selections.

That’s all.

#### What happened instead
Se above.

NOTE: Please let me know if you need a temporar account on this blog noach.one, in order to study possible bug. Send me an email on chj@hdsoundlab.com

**Comment by jeherve** [comment]
If you wish to get a more advanced set of options when using a Facebook Sharing button, I would recommend using Facebook Official sharing button. You can change the button style under Settings > Sharing in your dashboard.

![image](https://user-images.githubusercontent.com/426388/61365368-e5be0e00-a887-11e9-955e-599e66b819de.png)

Once you switch to that button style you will be offered the option to add custom text to the post you are sharing, and if Facebook finds multiple images on the page it will offer you the choice to select which image you can use.

I hope this helps.

**Comment by chjan** [comment]
Thanks and accepted, however I am curious why you do not per default offer these self-evident features? Or at least, why you don’t add some explanatory text to the settings gui so that we don’t need to contact you per email? You solution is not easy to guess just like that.

 

Kind regards

Carl Henrik

**Comment by chjan** [comment]
And, more info: What you claim, I cannot provoke, however the awkward cutout of the site logo is luckily gone. Here is a screendump of a blog (on our own server) containing both a featured image as well as several embedded images, noen of them showing up.

 

1.	Where is the option to choose image for sharing?
2.	Where is the option to adjust the text to something a human being can understand?

 

As you can see for yourself, the text cutout (grey field) done by Jetpack (or FB?) is in both cases completely nutty, to the extent that it disables the whole feature. Unusable.



 

So, I repeat basic requirements:

a) A need to select whatever picture is connected to the blog

b) At the minimum a proper intelligent text, for example the ingress, of course without “category”, without a lack of spaces between words, etc, or, at the maximum an option to rewrite the text based on that ingress. (Note however that the inclusion of headers like “General” is due to wordpress being too primitive on selecting an ingress, when none was written).

 

Thanks for a follow up so this problem can be solved

 

Carl

**Comment by jeherve** [comment]
> why you do not per default offer these self-evident features?

Unfortunately that is just not possible with the current implementation of the buttons. We opted to offer a "simple", light version of the buttons whenever one chooses any of the non-official implementations. This allows to display buttons without the need to load extra resources directly from Facebook. Those buttons will display faster, and will not rely on a call to the Facebook API for each post. Performance-wise, it's a better choice for your website. The downside of such a light implementation is that since it does not load the Facebook API, it does not offer the same kind of functionality.

> why you don’t add some explanatory text to the settings gui

We could indeed add an indicator for each button style, showing what options are more full-fledged and what options are lighter and more performance-oriented. I've taken note of this and we'll consider it when we next iterate on that screen.

> Here is a screendump of a blog

Could you post those images directly on the GitHub issue, so I can see them? They don't seem to be uploaded to the issue when you comment via email:
https://github.com/Automattic/jetpack/issues/13055

**Comment by chjan** [comment]
I will. I just state her that I think it is mandatory that a jetpack feature that is all about sharing is developed further and becomes superslick. To attract readers, this is necessary. A lightweight version is not that interesting. Hope you are not offended and that you agree on the principle.

 

One solution could be to add a section to the WP post editor where the editor may offer the editor/user to choose picture, i.e. that WP collects all possible pictures in a list, and that a FB excerpt is also possible to write down. And then a selector on whether you want autoshare or manual share. The current excerpt that grabs everything in a non-formatted manner, including {category, headers, author, etc} is not good. None of my FB friends is ever interested in which category I use for my post. Agree? IOW, remove redundancy and make an effective and pinpointing excerpt that will make the FB friend curious. Make it very tempting and delicate.

 

I was the inventor of FreePad, the Norwegian forerunner to iPad type of terminals, hence I am concerned about usability and GUI friendliness of software and hardware. To win, things MUST BE superslick.  On top of that, I have this uncanny ability to jump into almost any bug around. When I release my own software, there are no bugs around. I have found them all. It is very strange 😊

 

Note that I am developing currently an Android app containing both Spotify and FaceBook SDKs. They both work very well and is easy to use. So don’t be afraid of integrating them. It is easy.

 

SECONDLY:

 

Would you be in contact with some of the WP developers, and could bridge me to one of them?

 

There are a few other major, practical problems in WP that could probably be easily fixed. One of them is that the inclusion of oneDrive videos is indeed very troublesome, in that the embed option from OneDrive causes autoplay of videos, one need to change the embed string from “embed” to “download” to make things work. Another thing is that WP constantly reports “source unavailable”, and then the “next day”, it is ok again. It is something with the way WP (or possibly the browser)  interprets the embed string because if you just provide the video link, it always work.

 

The requirement is this simple one: Make software that always work without exception, and that grants you a solid error report when errors are detected. 

It is much better if WP team had a chat with OneDrive team and fix this. The OneDrive user forum needs “upvotes” before they take bug reports seriously, so that is not the way to report (have tried). 

 

(this autoplay feature was suddenly introduced a few years back, causing my posts with multivideo content to all start autoplaying. It completely destroyed by blog. What a nightmare to fix it, with a 100 videos)



There is also the autogenerated Excerpt for a post which is from the last century technological level. This is blending with your trouble with sharing. At the moment, it is mandatory to manually write an excerpt, else things go awry+



Not to mention that the editors offered by WP is – on certain matters – incredibly stupid. For example, it sometimes removes spaces and lines without asking my permission. When will I ever want an editor to overrule my choices of formatting? Never.



And some more things to fix.

 

Your problem, and these originating from WP, creates a cumbersome experience and one needs to learn to trick the software to make things work. I honestly think these types of problems should have been solved long, long time ago, and hence, it could be useful for many if I am allowed to discuss a little with WP team. Thanks for any help you can provide. 

 

All the best

Carl

**Comment by chjan** [comment]
Oh, there is one more very important thing with sharing that you need to look into: 

 

If you have written a post and like to share it, you e.g. click the sharing button, which brings up an overview of what you are about to share.

 

Then, often, you discover some blunder that you want to fix, thus, click cancel on the share, then fix the error, and then finally click share again.

 

Now the new share suggestion DOES NOT contain the changes. You get one shot only, the first. So there is a need to CLEAR FACEBOOK SHARE CACHE always when a share is commenced. Agree? I don’t know if this is WP or Jetpack. In the former case, notify WP!

 

(my trick on this is to copy post to a new draft and hit the share button, and delete the old version of the post, clearly cumbersome).

 

Carl

**Comment by chjan** [comment]
![sharingTrouble](https://user-images.githubusercontent.com/69140/61434518-7c490880-a936-11e9-85f3-b78f3f66b490.png)

**Comment by chjan** [comment]
To the picture above, please study the actual blog and how it is interpreted in a most cumbersome manner: http://www.noach.one/blog/the-secret-of-the-old-winch/

**Comment by jeherve** [comment]
> I just state her that I think it is mandatory that a jetpack feature that is all about sharing is developed further and becomes superslick. To attract readers, this is necessary. A lightweight version is not that interesting. 

If you are interested in a more advanced version of the Facebook sharing button, the official button should be just what you are looking for. We aim to keep the non-official buttons as lightweight and simple as possible so we do not plan on adding any additional dependencies to the Facebook API for those buttons. Not relying on third-party resources is also important for folks who aim to limit the amount of third-party tracking scripts available on their site.

> One solution could be to add a section to the WP post editor where the editor may offer the editor/user to choose picture, i.e. that WP collects all possible pictures in a list, and that a FB excerpt is also possible to write down. And then a selector on whether you want autoshare or manual share. 

That is not something we are planning on adding to Jetpack, but there may be other sharing plugins that offer such preview options and settings in the editor.

Jetpack instead aims to provide all the information Facebook needs automatically, via [Open Graph Meta Tags](https://developers.facebook.com/docs/sharing/webmasters/). Jetpack adds those tags to your site as soon as you activate the Sharing feature, and those tags provide the title of the post, an excerpt, the images available on the page, all so that Facebook can build a post preview when you hit the share button.

Those tags are nowhere to be found on your site though, most likely because your theme or one of your plugins disables Jetpack's Open Graph Meta Tags. Could you check your plugins and theme's settings to find out where the tags are being removed? It's likely that the plugin or theme that removes Jetpack's tags offers its own set of tags instead, but that hasn't been configured in the theme or plugin settings yet.

Once you have a proper set of Open Graph Meta Tags, your Facebook Post Previews will look a lot better.

> Would you be in contact with some of the WP developers, and could bridge me to one of them?

You can contribute to WordPress, suggest changes, and even contribute code by following the instructions here:
https://make.wordpress.org/core/handbook/

> Now the new share suggestion DOES NOT contain the changes. You get one shot only, the first. So there is a need to CLEAR FACEBOOK SHARE CACHE always when a share is commenced. Agree? I don’t know if this is WP or Jetpack. In the former case, notify WP!

As you mentioned, that data is cached on Facebook's end. There is not much that can be done on your end when that happens, short of using [Facebook Debug(https://developers.facebook.com/tools/debug/) to clear that cache. This is not something that can be done by WordPress or Jetpack.
