### ISSUE TITLE
JITM: RTL CSS file is created by build inside css folder, but not inside vendor/automattic/jetpack-jitm/assets

### ISSUE THREAD

**Issue by MDCR55** [Automattic/jetpack#13089]
When I update my plugins, I see this big JetPack logo on the Arabic RTL version

#### Steps to reproduce the issue
1. Go to Settings
2. Change language to Arabic
3. Hit back to update page

**Screenshots**
![](https://i.imgur.com/GfKcfla.png)

**Comment by jeherve** [comment]
Thanks a lot for the reports.

@gititon Do you think you could take a look at this? When we moved the JITM feature into a package in #12516, you added the main .css file to the package, but I am not clear as to how building CSS works for the JITM package now.

- If I make a change to `scss/jetpack-admin-jitm.scss` today, and then run `yarn build`, a few files are built in the `css` directory:
![image](https://user-images.githubusercontent.com/426388/61622211-a40cd900-ac74-11e9-89d5-ab57335ac665.png)

- How do we make sure those changes are made available to the package?
- Should we ship both the scss and all the built css files inside the package, instead of keeping them in the main `/scss` directory? In this case, that would mean that we would have to create a new gulp task to build css files in packages as well?

**Comment by csonnek** [comment]
Also reported in:

- 2200709-zen
- 2211075-zen

**Comment by csonnek** [comment]
Replied to both users above to let them know this will be fixed in the next update.
