### ISSUE TITLE
Regression: Publicize and Verification Tools no longer detect SEO plugins

### ISSUE THREAD

**Issue by sybrew** [Automattic/jetpack#13146]
Methods `Jetpack::check_open_graph()` and `Jetpack::check_twitter_tags()` used to check for SEO plugins, but it regressed to skip that. 

This causes the output of duplicated metatags when using SEO plugins from the `Jetpack::$conflicting_plugins['seo-tools']` list.

Moreover, `Jetpack::$conflicting_plugins['verification-tools']` isn't checked against anywhere anymore. I believe this index can be removed and replaced by checking for the `seo-tools` index solely instead.

**Comment by jeherve** [comment]
It seems to work well in my tests. Could you tell me more about what plugin you've used in your tests?

Thank you!

**Comment by sybrew** [comment]
Thanks for looking into this!

That'd be The SEO Framework. I take it you've moved forward from this check and let us set the filter, instead? As seen here:

1. https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/b07ef0b86a22450eb242fb06459d242f13c4774b/modules/aioseop_opengraph.php#L95
2. https://github.com/Yoast/wordpress-seo/blob/28f942ef35d5001aef1b7addc9d5d9de481fe272/frontend/class-opengraph.php#L38

I would not oppose to embedding the same in The SEO Framework. I was unaware that this change in behavior had been made. With that, I feel confident closing this. Cheers!

**Comment by jeherve** [comment]
> I take it you've moved forward from this check and let us set the filter, instead

Both options are valid and possible. Yoast SEO and All In One SEO used to be on our list as well.

Our list is ideal for plugins that start outputting Open Graph Meta Tags as soon as you activate the plugin. In this plugin, we want to hide Jetpack's OG Tags right away because we know that if the other plugin is active, there will be OG tags set already.
However, plugins like Yoast SEO or All In One SEO do not output OG tags right away. You have to go to the plugin's options and toggle an option to start outputting OG tags. As a result, there are times when Yoast SEO or All In One SEO are active, but do not output any OG tags yet. In this scenario, you want Jetpack to keep showing OG tags. That is why we worked with both plugin authors so they hide our OG tags from their plugin, as soon as one activates OG tags in their plugin options.

I am not too familiar with The SEO Framework, so I'll let you decide which solution would make the most sense for you. We are happy to add your plugin to our list, or you can use the filter in your own plugin and have it set as soon as one turns on OG tags in your plugin options. That's up to you!

**Comment by sybrew** [comment]
I came to the same conclusion as you have: it's optional, so I'll make the filter conditional in The SEO Framework. Cheers!

Please do relay when you change the behavior of the Twitter Card output. They now fall under the same filter `jetpack_enable_open_graph`, but the tags are not deemed mutually inclusive by Twitter.

**Comment by jeherve** [comment]
> that can still be superseded by `jetpack_enable_open_graph`.

This was done on purpose, as the Twitter Cards are built on top of the Open Graph base in Jetpack. We opted to do things that way as most plugins offering Open Graph Meta Tags now also offer Twitter Cards as a "Social tags" package.

If you think we should revisit this decision, I would recommend opening a new issue with your suggestions and take on that.

Thank you!

**Comment by sybrew** [comment]
I understand! I think Jetpack's philosophy is "set and forget" and "decisions, not options," so I don't think my contributions will live up to that. After all, I make a "competing" (or complementing 😄) product. So, I don't believe I should be the one to make suggestions outside of the structural realm--of which I think you have a firm grasp.

Cheers 😃
