### ISSUE TITLE
Video Blocks inline styles breaks existing styles

### ISSUE THREAD

**Issue by pbuzdin** [Automattic/jetpack#13187]
#### Steps to reproduce the issue

1. Create a post in Gutenberg with YouTube video block

#### What I expected
if i block https://c0.wp.com/p/jetpack/7.5.3/modules/theme-tools/responsive-videos/responsive-videos.min.js it looks fine
![image](https://user-images.githubusercontent.com/1329807/62529359-2eddfe00-b847-11e9-9174-ffc497c3dfcb.png)

#### What happened instead
![image](https://user-images.githubusercontent.com/1329807/62529290-081fc780-b847-11e9-9764-e19bb8d1d2fa.png)

https://e.iboong.com/105/

WordPress 5.2.2
Jetpack 7.5.3

**Comment by jeherve** [comment]
Could you let me know if this happens regardless of the theme you use?

**Comment by pbuzdin** [comment]
I use https://sustywp.com 1.0.0

Issue solved by adding this to functions.php via https://github.com/Automattic/jetpack/issues/10678#issuecomment-445227751
```
add_theme_support( 'responsive-embeds' );
```

**Comment by jeherve** [comment]
That's a good option. Another alternative, since you've changed your theme's content width with CSS, would be to update your theme's `$content_width` value to match the width you've set with CSS. You can do so with a code snippet like so:

```php
function jeherve_custom_width() {
	return 1100;
}
add_filter( 'susty_content_width', 'jeherve_custom_width' );
```

I've opened a PR to suggest the addition of responsive embeds support for your theme:
https://github.com/jacklenox/susty/pull/23

**Comment by pbuzdin** [comment]
Thank you @jeherve !
