### ISSUE TITLE
Markdown: some stylistic and functional issues

### ISSUE THREAD

**Issue by Ramlinbird** [Automattic/jetpack#13185]
Hi, I'm using jetpack markdown on my wordpress blog (classic editor). And had some problem after writing several posts. Here are they.

### 1. Heading styles not the same
Heading titles' font seems different with each other in different level, for example,
![image](https://user-images.githubusercontent.com/11084132/62504079-8e2d1580-b829-11e9-9272-a53a305a6782.png)
I don't know if this is caused by wordpress's font setting? If so, how can I fixed it?

### 2. Some common latex not support
Hope latex can support some common math style in many papers, for example
- `$latex ax+b=c \tag{1}$` display as `ax+b=c    (1)`
- multiple line auto-indent

### 3. The contents of table not indentation
![image](https://user-images.githubusercontent.com/11084132/62505003-78b9ea80-b82d-11e9-8d97-409bdcd815e3.png)
Some content seems strange in table, not align well.

Thanks a lot.

**Comment by jeherve** [comment]
Jetpack's Markdown feature helps you by converting Markdown into HTML whenever you save your post. It does not, however, style that HTML content. This is something that is done by your theme. If you'd like to change the display of a heading, you should be able to do so with CSS, inside your theme's `style.css` file. 

If you see some styling differences between some of the headings, it's most likely because some of them use a custom class name, that is used in CSS to style the heading differently.

> Hope latex can support some common math style in many papers, for example

To get proper LaTeX support, I would recommend that you make sure [Jetpack's Beautiful Math feature](https://jetpack.com/support/beautiful-math-with-latex/) is enabled, and then try outputting LaTeX again. If you experience issues with some of your equations, even when the formula appears to be correct, do not hesitate to open a new issue here in this repo with some examples.

Thank you!
