### ISSUE TITLE
Toggling Jetpack sidebar in Gutenberg causes jumping

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#13212]
#### Steps to reproduce the issue

1. Go to the block editor
2. Click on the Jetpack icon in the top-right
3. See things jump around a bit

#### What I expected
I'd expect the Jetpack icon to become highlighted exactly in place, without causing anything else to move (like how the core icon does).

#### What happened instead
When the Jetpack icon gets highlighted, I think it's adding/removing too much padding/margin, so the other items near it jump around.

**Video**
Here's a video showing it happening. Taken on the wordpress.com block editor, but the same thing happens in core. This is using latest Chrome on OSX
https://cloudup.com/cyMiAul7KIt

**Comment by simison** [comment]
This seems to be a core Gutenberg bug since it's also happening with other plugin sidebars:

<img width="392" alt="image" src="https://user-images.githubusercontent.com/87168/63266748-4bdbed80-c299-11e9-81a1-c920341fb8ee.png">

Tested with Gutenberg 6.2.0 and 6.3.0

Should be fixed in future versions: https://github.com/WordPress/gutenberg/issues/15608
