### ISSUE TITLE
Widget: Internet Defense League imaged served over http

### ISSUE THREAD

**Issue by jjchrisdiehl** [Automattic/jetpack#13250]
#### Steps to reproduce the issue

1. Go to 'Customize > Widgets' and add Internet Defense League widget
2. Go to live site and inspect element > security
3. Leave Inspector open and refresh page
4. See error - Non-secure Origins

#### What I expected
I expected the image to load over https

#### What happened instead
Looks like both an http and https variant of the image loads on the page, which triggers a mixed source error.

**Screenshots**

![image](https://user-images.githubusercontent.com/16580129/63218095-1c09da00-c121-11e9-9d11-9216d107db6d.png)

This may be something on the Internet Defense Leagues end with how they are serving this content, or perhaps we are pulling both versions?

**Comment by jeherve** [comment]
The widget pulls data from `members.internetdefenseleague.org` directly, so I'm afraid there isn't much we can do on our end to fix this. I would recommend reporting the issue here, while mentioning the specific campaign you had picked, as well as the exact resource that was loading via HTTP:
https://github.com/fightforthefuture/members.internetdefenseleague.org/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
