### ISSUE TITLE
Add option to disable the Jetpack dashboard for non admin users.

### ISSUE THREAD

**Issue by dericleeyy** [Automattic/jetpack#13280]
#### Is your feature request related to a problem? Please describe.

Currently, the Jetpack menu in wp-admin is displayed to all logged-in users.

#### Describe the solution you'd like

Option to only display the Jetpack wp-admin dashboard to admin users, or users with permission to view the stats.

#### Additional context

2258552-zen

**Comment by jeherve** [comment]
That's not something we plan on implementing in Jetpack, since the Jetpack menu is useful even to non-admins who would want to connect their account to their WordPress.com account, to use features like Post By Email, Notifications, Publicize, and other features that are accessible to non-admins. It is also useful, as you mentioned, for folks who have access to Stats.

Jetpack takes all that into account and only display settings that your role would allow you to access.

That said, if one wanted to hide that menu anyway, they could use a plugin like this one:
https://wordpress.org/plugins/admin-only-jetpack/

**Comment by busitech** [comment]
This is absolutely false for our use case, and this is exactly the kind of thinking that holds Wordpress back as an application platform.  

Jetpack has no use whatsoever for users who get created in order to allow them to authenticate and use functionality provided by plugins, such as a learning management system (LMS), where the users have roles for Instructor and Student, and do not even need to know the site is driven by Wordpress.  The roles held by an Instructor and a Student in this case are totally unreleated to the underlying Wordpress system, and even seeing the Jetpack menu is totally inappropriate for these users.  

The Wordpress infrastructure and platform extenstions like Jetpack that are directed towards site owners, authors and other types of site contributors need to supply site owners with an a la carte library of resuable functionality much more like an operating system does, and much less from any particular functional persepctive such as blog posts, pages, comments and pingbacks, such that each plugin can have it's own definition of who a user is, and what they need to access.

Plugin authors are trying to help Wordpress go far beyond a blogging platform, to become an application platform.  To cooperate with this, Wordpress / Jetpack needs to widen their vision of what Wordpress can become if developers are allowed to decide precisely what that application is, and precisely what functionality is presented to the user.  In many cases, that does NOT include a Jetpack menu.

Please reopen this enhancement request, and strongly consider it for a future release, so that the Wordpress platform can grow well beyond the relatively narrow scope of a blogging platform.

**Comment by jeherve** [comment]
> Jetpack has no use whatsoever for users who get created in order to allow them to authenticate and use functionality provided by plugins, such as a learning management system (LMS)

While this may not be the case on your own site, other sites may rely on Jetpack features such as [WordPress.com Secure Sign On](https://jetpack.com/support/sso/), which allows visitors to create an account on the site or log in via WordPress.com. In those cases, the Jetpack menu will be useful for folks to manage their own user connection to WordPress.com.

This is just an example though; as I pointed out earlier there are other Jetpack features that can be used by non-admins on a WordPress site.

All that said, none of this may apply on your own site. If that's the case, there are ways for you to customize the user experience of different users on your site.

> To cooperate with this, WordPress / Jetpack needs to widen their vision of what Wordpress can become if developers are allowed to decide precisely what that application is, and precisely what functionality is presented to the user. In many cases, that does NOT include a Jetpack menu.

WordPress give you different ways to control what is presented to your users. A common approach is to use plugins. I pointed out one in my comment above, but there are others. Here is one:
https://wordpress.org/plugins/admin-menu-editor/

If you'd rather not use a plugin and want to control this via a code snippet on your site, you can do that too. Something like this would help:

```php
add_action( 'admin_menu', 'busitech_no_jetpack_menu_non_admins', 999 );
function busitech_no_jetpack_menu_non_admins() {
	if (
		class_exists( 'Jetpack' )
		&& ! current_user_can( 'manage_options' )
	) {
		remove_menu_page( 'jetpack' );
	}
}
```

**Comment by busitech** [comment]
Providing examples of use cases who need Jetpack is out of scope for this discussion.  This discussion is about use cases where Jetpack, and the underlying presence of Wordpress, should both be unknown to the user of the website. 

You're suggesting I make our site more brittle, so it can break when the `remove_menu_page` API becomes `remove_menu_item` or when the `admin-menu-editor` plugin ceases to be maintained, or is updated 14 months after a Wordpress update came along to break it, because the author got too busy to maintain his free plugin.  

Plugin creep, snippet creep and incompatibility are the plague, which all lead eventually to the **WordPress white screen of death**.

Why are you against supporting an _optional_ Jetpack capability, natively in Jetpack, to control visibility of Jetpack, that I can take away from certain user roles, to achieve the goal of providing Jetpack only to the users who need it?

**Comment by jeherve** [comment]
> it can break when the remove_menu_page API becomes remove_menu_item

You can rest assured; `remove_menu_page` has been around since 2011 (it was introduced in WordPress 3.1) and is not going anywhere. If the function eventually changes, it will be deprecated without breaking your site, as per WordPress' commitment to backward compatibility. I would encourage you to use that option if you'd rather not add a new plugin to your site, or if you don't plan on using the Admin Menu Editor plugin to alter your site's dashboard menu even further, since your instructors and students don't need to see most of WordPress' underlying features as you mentioned earlier.

> Why are you against supporting an optional Jetpack capability, natively in Jetpack

I am not against adding more options to Jetpack; we do so quite often.

In general, we try to follow WordPress Core's principles whenever possible. One of those principles is "[Decisions, not Options](https://wordpress.org/about/philosophy/)". In practice, that means that whenever we discuss adding a new option to one of Jetpack's interfaces, we first stop and consider the impact such an option will have on the entirety of our user-base:

- Will the majority of our user-base need and use the option?
- Will the option create any confusion to some site owners?

Back to our present discussion, I would say that the majority of site owners currently do not need that option in the Jetpack interface. However, if we receive more requests in the future and if more and more people need that option, we won't hesitate to reopen this issue and reconsider adding the option. Since you commented on the issue, you should receive an email notification whenever this happens!

I hope this clarifies things a bit.

**Comment by ICEknigh7** [comment]
Was wondering why everyone was still using unofficial workarounds for hiding Jetpack from non-admins and just found this. Please add this requested option.

- Will the majority of our user-base need and use the option?
Don't know percentages but just doing a search on the internet shows a lot of people with the same needs.
- Will the option create any confusion to some site owners?
Not if you just set the current behavior as default.

**Comment by chatoxz-wp** [comment]
9384372-zd-a8c
