### ISSUE TITLE
Contact Info Widget: improve styles for error messages displayed for map

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#13361]
> When omitting an API key, the feedback/error is teeny tiny and could be easily missed:
> A little extra padding would certainly help. I am thinking perhaps a stronger border too – to separate the white on white problem.

![image](https://user-images.githubusercontent.com/426388/63942054-3ae76500-ca6d-11e9-8740-97a4d04f3e40.png)

cc @scottsweb

**Comment by codestor4** [comment]
I'd like to help on this one. What if instead of admin notices, we simply display the `Please enter a valid Google API key` message in red text? 

Here's an example: 

![Screen Shot on 2019-10-05 at 07:19:57](https://user-images.githubusercontent.com/20779676/66248128-a2659400-e740-11e9-9b8f-f3b25d14c53b.png)

It could be an easy fix :) 
@scottsweb what do you think? In case you haven't already started work on it, I can make a PR

**Comment by codestor4** [comment]
**Update:** I've gone ahead and created a PR anyway. We can always just close that if it's not needed :)

**Comment by scottsweb** [comment]
The delete link seems to be using the class `.button-link-delete` which is `#a00` - so I would go with that. You can probably just use the same class rather than an inline style.

**Comment by codestor4** [comment]
@scottsweb Thanks. Added these changes here https://github.com/Automattic/jetpack/pull/13676
