### ISSUE TITLE
Plans tab is empty as secondary unlinked user

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#13415]
#### Steps to reproduce the issue

The issue only appears for secondary users that are not connected to wpcom. 

0. Connect your site to wordpress.com
1. Create a secondary admin user on the site
2. Log in as secondary admin in a separate browser/incognito
3. navigate to `/wp-admin/admin.php?page=jetpack#/plans`
4. Notice there is nothing there to be displayed. 

#### What I expected

I expected to see the plans grid? 

#### What happened instead
![image](https://user-images.githubusercontent.com/7129409/64197093-35b25d80-ce53-11e9-9ad5-c6ce08a8be65.png)

**Comment by jeherve** [comment]
This seems to happen because the user is not linked to WordPress.com, so the call to get the plans from WordPress.com fails since there is no token associated with the request.

It makes me wonder if we should even show that page to non-connected admins. They won't be able to make any changes since they are connected to WordPress.com yet. The same goes with the "My Plan" page. Both pages include links to Calypso for that site, but none of those links will work for them.

I think we should only display those navigation menu items once a user has linked their account to WordPress.com.
