### ISSUE TITLE
Markdown for Comments: code stripped out when commenting as non-admin

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1365]
Steps to reproduce:

1. Enable the Markdown module
2. Enable Markdown for comments in Settings > Discussion
3. Log out of your WordPress account.
4. Try to leave a comment with the following text on any of the posts:
https://gist.githubusercontent.com/chriscoyier/215aee9a06435b3bec8f/raw/39cb53e79cd300b2b11c7a789cc43aeadcbecd88/comment.md
5. Your code will be stripped. See screenshot below for a comparison between a comment as an admin, and the same comment as a guest:

![markdown-comments](https://cloud.githubusercontent.com/assets/426388/5296500/dd89bcd0-7ba4-11e4-8950-ff12762ad447.png)

Reported here:
- https://wordpress.org/support/topic/random-markdown-code-block-results

cc @chriscoyier

**Comment by richardmtl** [comment]
@cfinke what do you or someone else on your team think of the above?

**Comment by cfinke** [comment]
I don't think it's Akismet -- I'm seeing the tags get stripped even when Akismet is disabled.

**Comment by jawittdesigns** [comment]
Well, there is the `<pre>` tag issue, but no there is something going on with Akistmet being activated. I contacted the Akismet support and Valerie tested it. She did confirm there is an issue with Akismet and Jetpack both active, but concluded that it is a Jetpack issue since there's nothing in the Akismet code to effect this. 

I'm suspecting that maybe there's something elsewhere in Jetpack tied to Akismet that may be causing this.

**Comment by cfinke** [comment]
> She did confirm there is an issue with Akismet and Jetpack both active, but concluded that it is a Jetpack issue since there's nothing in the Akismet code to effect this. 

She also confirmed that disabling Akismet doesn't change the behavior:

<blockquote>Using the multi-line code syntax worked for me when Akismet was on and when Akismet was off while being logged out of the site completely. [...]  I do see that there's a different between the logged in and logged out comments: comments made by a logged in admin have the <pre> tag in addition to the <code> tag whereas logged out comments have only the <code> tag. That doesn't seem to be different when Akismet is on or off, though.</blockquote>

Have you been able to definitively reproduce the error with Akismet enabled and have it go away when Akismet is disabled?

What version of WP and what version of Akismet are you seeing the problem with? I don't see how the current version of Akismet could be modifying comment content at all.

**Comment by jawittdesigns** [comment]
Yeah, like I said the `<pre>` tag issue. That something separate. That's happening because the `<pre>` tag isn't added to the allowed HTML list be default, so if it isn't added to the list for non-admin users it get's stripped out by kses. That's part one part of the tag stripping. 

Yes, I've been able to reproduce this on multiple clean WP installs both on local and on a live server with the only plugins active being Akismet and Jetpack/Mardown. It was also confirmed on the css-tricks.com dev and live site. 

http://hl.jawittdesigns.com/hello-world/ 

Here are test comments(the `<pre>` tag is added to allowed HTML). The first comment is from an admin account. The second one it a guest post with Akismet active. The third comment is a guest account with Akismet deactivated.

**Comment by jawittdesigns** [comment]
I just saw a Jetpack update and updated it.

Here's a new test post.

http://hl.jawittdesigns.com/new-post

**Comment by cfinke** [comment]
Thanks for the examples; after uninstalling/reinstalling the latest Jetpack, I can reproduce the issue with the `pre` tag getting stripped when Akismet is enabled. I'm looking into it.

**Comment by cfinke** [comment]
@jawittdesigns This change: https://plugins.trac.wordpress.org/changeset/1076927/akismet/trunk should fix the problem you're seeing.

**Comment by techsupport90** [comment]
The problem here arises because an HTML comment at the start of the line “taints” the whole paragraphs as HTML. As you can see, the importance (bold) and code no longer “work”. ... You signed out in another tab or window. [Web Design Malta](https://www.europewebsitedevelopment.com/web-design-malta/)
