### ISSUE TITLE
Instant Search: Improve aggregation data structure

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/jetpack#13862]
## Current State
Currently, the Instant Search API returns aggregations in the following format:
```js
{
  [ widgetId ]: {
    buckets: arrayOf(
      doc_count: Number,
      key: Number,
      key_as_string: String (only exists for Date filters),
    )
  } 
}
```

An example Month filter bucket might look like the following:
```js
{
	doc_count: 7
	key: 1191196800000
	key_as_string: "2007-10-01 00:00:00"
}
```

## Proposed Solution
I'd like to propose that we return a properly formatted `text` value within the bucket object. The above Month filter bucket might look like the following:
```js
{
	doc_count: 7,
	key: 1191196800000,
	key_as_string: "2007-10-01 00:00:00",
	text: "October 2007",
}
```

An example post type filter bucket might look like:
```js
{
	doc_count: 10783,
	key: "post",
	text: "Post",
}
```

An example taxonomy filter bucket might look like:
```js
{
	doc_count: 264,
	key: "japanese%e6%97%a5%e6%9c%ac%e8%aa%9e",
	text: "Japanese (日本語)",
}
```

This change would allow us to remove a substantial amount of code from the front-end application that currently handles normalizing the filter bucket object. Doing so will also allow us to better address filter rendering issues affecting our prototype.
  - For Date filters, we're doing custom date formatting that doesn't respect the user's site configuration (#13810).
  - For Post Type filters, we're unnecessarily propagating the site's post type configuration throughout the entire application just so we can properly render the post type names.
  - For taxonomies, we're rendering the raw taxonomy key which is currently causing encoding issues (#13812).

**Comment by gibrown** [comment]
Also related: https://github.com/Automattic/jetpack/issues/13749

**Comment by gibrown** [comment]
Also I think we should think about how to handle custom filter lists in relation to this since it is a pretty important type of aggregation: https://github.com/Automattic/jetpack/issues/9682

As well as filtering by post meta and authors.

**Comment by gibrown** [comment]
@jsnmoon @bluefuton I think we should close this now. The `slug_slash_name` takes care of all the cases for taxonomies and we should be able to do similar things in the future for other fields.

That leaves dates. I don't think we should add formatted dates to the index because anytime the end user changes that setting we would have to fully reindex the whole site before their change takes effect. Seems like a bad UX.

We could reprocess the aggs in the api, but it breaks the architecture a bit. In particular it means we would need to push blog specific DB data to edge data centers (when we get there) and I am not sure we will ever be able to do that.

**Comment by bluefuton** [comment]
Sounds good to me @gibrown 👍
