### ISSUE TITLE
Dashboard Widget: confusing UI when only one of Akismet / Protect is enabled

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#13952]
This was originally brought up here:
https://twitter.com/LaChicaGamer/status/1187212707356971009

> I have been paying for Akismet for almost 2 years.. I noticed a couple of weeks ago that on the Stats tab seems that is not active? 

![EHnTqGXW4AI7GuZ](https://user-images.githubusercontent.com/426388/68116474-39b63680-fefb-11e9-89b1-4c0929e1b0b4.jpg)

Maybe we could add headings to each column to make it clearer that each side refers to a different feature that may or may not be active?

For reference, here are some of the different states one may see in that dashboard widget:

<img width="685" alt="screenshot 2019-11-04 at 11 57 39" src="https://user-images.githubusercontent.com/426388/68116537-5eaaa980-fefb-11e9-9994-47b507b7e988.png">
<img width="682" alt="screenshot 2019-11-04 at 11 57 15" src="https://user-images.githubusercontent.com/426388/68116539-5f434000-fefb-11e9-95f4-0b28f3bd1d14.png">
<img width="720" alt="screenshot 2019-11-04 at 11 56 55" src="https://user-images.githubusercontent.com/426388/68116540-5f434000-fefb-11e9-8139-d3e64d93d74e.png">

**Comment by keoshi** [comment]
Agreed that this is not great. It's easy to read that footer as one single section when it's actually two different features; even I was confused to see that first screenshot.

I'd also agree that adding headings would make the two columns stand out more on their own, but I'm afraid our naming could make this slightly obscure — i.e.: “Protect” on its own is as much of a verb as it is our product's name.

I'd suggest a couple of changes then:

- Add `h4` headings to each column:
  - `Jetpack Protect`
  - `Akismet` (since it's a stand-alone product/plugin, unless we want to go with `Jetpack Anti-spam` right away; ref: p1HpG7-7EE-p2 & p1HpG7-76q-p2 )
- Tweak copy on buttons to make them consistent:
  - `Activate Jetpack Protect`
  - `Activate Akismet` (or `Jetpack Anti-spam`)
- Make the copy consistent across the board:
  - `Blocked malicious login attempts`
  - `Blocked spam comments`

Here's what this looks like (sans-buttons):

![image](https://user-images.githubusercontent.com/390760/68118844-f5299b80-fef8-11e9-9f78-57656b151db8.png)
