### ISSUE TITLE
SEO issue: Social sharing uses temporary/302 redirects

### ISSUE THREAD

**Issue by galbaras** [Automattic/jetpack#14016]
#### Steps to reproduce the issue

1. Go to any page with Jetpack sharing buttons
2. Hover over any sharing button - the URL is on the local domain
3. Click that button - a new window opens
4. Check the URL in the new window - it's on the social media domain

#### What I expected

Social sharing icons should be linked directly to the respective social network. If any tracking or updates are required on the local domain, it can be AJAXed on click.

#### Why this is an issue

Google considers page redirection bad user experience, particularly the temporary kind, which cannot be indexed reliably. Jetpack sharing URLs feature in all my sites' SEO audits as having 302 redirect issues, which means that using Jetpack sharing creates an SEO disadvantage for site owners.

**Comment by jeherve** [comment]
> Social sharing icons should be linked directly to the respective social network. If any tracking or updates are required on the local domain, it can be AJAXed on click.

The redirection isn't there for tracking (Jetpack doesn't do any tracking when clicking on sharing buttons), but to allow us to open a popup with all the necessary information for each Social Network. It avoids having to open social  networks in a brand new tab, and creates a unified experience when one clicks any of the sharing buttons at the bottom of a post. They all mostly behave the same way thanks to that extra step.

Moving to linking directly to each social network would make the user experience a bit worse overall.

> Google considers page redirection bad user experience, particularly the temporary kind, which cannot be indexed reliably. Jetpack sharing URLs feature in all my sites' SEO audits as having 302 redirect issues

That is not something I would worry about in this case, since each one of the sharing buttons uses a `nofollow` rel attribute to clearly indicate that the links are not meant to be followed by search engines.

That said, if that is something that worries you, I would recommend switching to the "Official" button type under Settings > Sharing in your dashboard. Once you do so, you will move away from Jetpack's implementation and its redirections, and instead rely on each Social Network's JavaScript to open the popups and handle the sharing for you.
