### ISSUE TITLE
AAG: update Backups card to take Jetpack Backup into account

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#14086]
#### Steps to reproduce the issue

1. Connect a brand new site to WordPress.com and purchase a Jetpack Backup plan.
2. Go back to wp-admin.
3. In Jetpack > Dashboard, the backups card is not updated.

![image](https://user-images.githubusercontent.com/426388/69333563-2c1de200-0c59-11ea-9346-8ae09d62348a.png)

This would be a good follow-up from #14083.

**Comment by robertf4** [comment]
@jeherve this seems to have been caused and fixed in https://github.com/Automattic/jetpack/pull/14083, as I've tested this case both in that branch and master and haven't been able to reproduce it. Could you double check and close if you can't reproduce either?

I think the Backup card should be fine, as I inspected the code and it doesn't look at the plan or purchases at all, it only looks for the presence of VaultPress or Rewind. Since that is required for Jetpack Backup to work, this card should work unless I've broken something.

**Comment by jeherve** [comment]
Yep, looks okay now. 👍 

Closing.
