### ISSUE TITLE
JSON API: Post and Comment author data should reflect wpcom info

### ISSUE THREAD

**Issue by rralian** [Automattic/jetpack#1410]
The `get_author()` method in `class.json-api-endpoints.php` is supposed to return the wpcom external info for the User, rather than the jetpack local User data. But that's not working because this line is returning false for some reason.

https://github.com/Automattic/jetpack/blob/master/class.json-api-endpoints.php#L1029

**Comment by stevector** [comment]
Is it the expected behavior that wpcom info would be returned even when the given site is hosted elsewhere?

https://github.com/Automattic/jetpack/blob/d35f362b49e392d50fe32ad8f24af05d459be61f/class.json-api-endpoints.php#L1038 The check for IS_WPCOM skips trying to load wpcom info when hosted elsewhere.

**Comment by jeherve** [comment]
> Is it the expected behavior that wpcom info would be returned even when the given site is hosted elsewhere?

It does indeed seem to be the expected behavior. Closing this issue for now. We can always reopen in the future if needed.
