### ISSUE TITLE
Markdown: Error when using Stackable - Gutenberg Blocks plugin

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#14141]
A user reported the following error which they've tested and confirmed seems to be happening only when the Stackable - Gutenberg Blocks plugin is active.

```
Cannot use a scalar value as an array in
/home/bijwerki/public_html/wp-content/plugins/jetpack/modules/markdown/easy-markdown.php
on line 437
```

**Comment by jeherve** [comment]
I think this may be caused by part of this:
https://github.com/gambitph/Stackable/commit/716eb640927f2b902d6d86b2b8121399986602de

Could they try to comment out `add_filter( 'wp_kses_allowed_html', 'stackable_allow_wp_kses_allowed_html', 10, 2 );` in `wp-content/plugins/stackable-ultimate-gutenberg-blocks/src/init.php` on their site, and see if that helps?

**Comment by htdat** [comment]
Another report 2530513-zen blog_id = 158387891, they also use `Stackable - Gutenberg Blocks` plugin and it's has been just updated. 

I am asking them to try @jeherve's suggestion above.
