### ISSUE TITLE
Warning: Invalid argument supplied for foreach() in .../wp-includes/rest-api/endpoints/class-wp-rest-controller.php on line 295

### ISSUE THREAD

**Issue by westi** [Automattic/jetpack#14232]
#### Steps to reproduce the issue

1. Install WooCommerce 3.8.1, Jetpack 8.0, and wpcli
2. Run wp plugin list
3. See warning

#### What I expected
No Warning

#### What happened instead
A Waring

This is caused by the resolve-redirect endpoint not having a `properties` array in the response to the `get_item_schema` method here: https://github.com/Automattic/jetpack/blob/branch-8.0-built/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-resolve-redirect.php#L82

**Comment by pento** [comment]
This is [a bug in Core](https://core.trac.wordpress.org/ticket/48785).

Adding a `properties` array will cause the schema to be invalid, since this endpoint returns a [string](https://json-schema.org/understanding-json-schema/reference/string.html), not an [object](https://json-schema.org/understanding-json-schema/reference/object.html).
