### ISSUE TITLE
Instant Search: multiple, duplicate filters in mobile view

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#14535]
I suspect this is caused by rendering filters from multiple different widgets.

Go to http://gibrown.wpsandbox.me/demo/?s=related%20psts&blog_id=20115252&theme=twentytwenty and compare filters for the mobile and non-mobile views. For non-mobile there are 4 sets of filters, and for mobile there are 8. I think the other ones are coming from the front end widget.

**Comment by jsnmoon** [comment]
This is caused by the fact that we show filters for all widgets inside the mobile filter popover; it's cumbersome for the client to determine whether a widget falls inside or outside the overlay. 

I recommend we update [`JetpackInstantSearchOptions.widgets`](https://github.com/Automattic/jetpack/blob/instant-search-master/modules/search/class-jetpack-instant-search.php#L124) to only return widgets inside the overlay sidebar. This will allow us to prune significant amount of code introduced with #14374 [here](https://github.com/Automattic/jetpack/pull/14374/files#diff-d0d51843579dd7b9005ae67b9ecae5fcR12).
