### ISSUE TITLE
Instant Search: getting "Invalid Date" filter text in Chrome iOS

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#14534]
This only seems to happen on Mobile Chrome on iOS.

![IMG_1D84E5D06085-1](https://user-images.githubusercontent.com/820871/73499164-900d0700-437c-11ea-92af-dda402cf5329.jpeg)

**Comment by bluefuton** [comment]
I can reproduce this for month and year filters, but also only in Chrome mobile (iOS).

I think it's happening because most browsers are more lenient when using the `new Date` constructor, and accept our date format, which looks like this:

<img width="249" alt="Screen Shot 2020-01-31 at 15 33 10" src="https://user-images.githubusercontent.com/17325/73507872-2efa3780-443f-11ea-84a1-9046e54a1fa2.png">

@gibrown is it straightforward for the API to hand us a ISO8601 compliant date/time instead in `key_as_string`, like `2014-01-01T00:00:00Z`? I think that should solve it.
