### ISSUE TITLE
Carousel: tiled gallery block images get closed immediately in Firefox

### ISSUE THREAD

**Issue by joweber123** [Automattic/jetpack#14545]
#### Site Setup
1. Create a 'Posts' page on the site and select 'Full Post' to display in Content Options. 
2. Create a post and add a tiled gallery either using the Classic or Block Editor.  Publish post.

#### Steps to reproduce
1. Open the home page of the site.  
2. View the 'Post' page.  Clicking on images within the title gallery will open the lightbox normally.  
3. Return to the homepage.  
4. Again, return to the Post page.  Clicking on images within the title gallery will open the lightbox and immediately close it.  

#### What I expected
Clicking on an image within the titled gallery would always open the lightbox normally. 

#### What happened instead
Clicking on an image within the title gallery does not consistently open the lightbox normally. 

#### Browser / OS version
Firefox 71
OS X 10.15 
Javascript enabled
Cookies enabled 

This does not occur on Chrome/Safari. 

#### Screenshot / Video
Video: https://d.pr/i/j70sT5

#### Context / Source
User Report: 2580452-zen

**Comment by samiff** [comment]
Hey James 👋 

I'm trying to reproduce this issue using Jetpack 9.9-beta (available via the Jetpack Beta Tester [plugin](https://jetpack.com/download-jetpack-beta/) "Release Candidate") but haven't had any luck with Twenty Twenty-One as the theme.

The carousel module code has been updated significantly recently, so I'm wondering if the issue is still around or maybe it has been fixed? I was testing with Firefox v80 on Mac.

If you have a moment could you check to see if you are still able to reproduce this issue and let me know which theme the site is using? Thanks!

**Comment by joweber123** [comment]
Looks like it has been fixed.  I am testing in our Varia child themes, Twenty Sixteen, Lodestar, and unable to reproduce this now.  I'll close this report now as it looks like this is no longer an issue.  Thanks for having a look @samiff
