### ISSUE TITLE
Instant Search: Open overlay after user first types a few characters in search box

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#14612]
@keoshi and I discussed the UX (and marketing) of not having the overlay open until after the user has hit enter. We think we should try out opening it after a few characters have been typed and then see whether we can make that a smooth enough experience.

**Comment by jsnmoon** [comment]
What's the cutoff? 3 characters?

**Comment by keoshi** [comment]
@gibrown Does it matter how many characters are entered before we can return a reasonable result?

I'd actually like to see the overlay show up with only 1 character. Visitors would click/tap the search input and as soon as they start typing, the overlay starts showing results.

We might have to play with the overlay reveal animation to make both of these plays harmoniously with each other. For instance, I wouldn't be opposed to just have a fade in effect instead of the slide from the side movement.

**Comment by gibrown** [comment]
Hmmm... i'm unsure. A few ideas:
1. we wait until we start getting results from the API, so fire off the request as we currently do and open the overlay once we have something to display
2. Open it after one character
3. Open it after two (this is the minimum needed to really do a search on our current api)
 
1 or 2 feel like they may be the best option and I kinda lean towards 1 being less distracting (but maybe a bigger change).

**Comment by keoshi** [comment]
Didn't know 1 was possible, but I dig that a lot.

**Comment by jsnmoon** [comment]
#14788 implements option (1) mentioned above.
