### ISSUE TITLE
Related Posts: Add Filter for Post Meta

### ISSUE THREAD

**Issue by ivannovak** [Automattic/jetpack#1471]
It'd be sweet to have a filter available for post meta for related posts.  

I work on a site site that publishes content sometimes against Google DoubleClick for Publisher's Terms of Service so we've had to work to ensure Ads only appear on pages where the content is compliant with DFP's ToS.  Our solution was to simply set a custom field value if the post is against DFP's ToS.

For the time being, I'm grabbing and excluding posts against ToS like this:

    function jetpackme_filter_exclude_youtubeTosViolations( $filters ) {
        $youtubeTosViolations = array(
            'fields'       => 'ids',
            'meta_key'     => 'youtube-tos-volation',
            'meta_value'   => '1',
            'meta_compare' => '=',
            'posts_per_page' => -1
        );
        $youtubeTosViolationsQuery = new WP_Query($youtubeTosViolations);

        return $youtubeTosViolationsQuery->posts;
    }
    add_filter( 'jetpack_relatedposts_filter_exclude_post_ids', 'jetpackme_filter_exclude_youtubeTosViolations' );

This seems to work fine, however, I'd imagine adding a couple thousand post ids to exclude is fairly inefficient.  What do you think?

**Comment by jeherve** [comment]
cc @xyu

**Comment by xyu** [comment]
Unfortunately we currently do not index post_meta because it would bloat index too much trying to parse such a free form field. Excluding by post id like this works and it actually should not be that much slower as calculating relevancy scores is a much heavier operation then filtering by id.

The other option is to tag these posts then filter by post tag however I'm not sure if that's something that you can expose via tags in this case with TOS violations.

**Comment by ivannovak** [comment]
Thank you!
