### ISSUE TITLE
Instant Search: Highlight content not returning

### ISSUE THREAD

**Issue by jakeols** [Automattic/jetpack#14741]
Hi All - 

I've been testing out the instant search plugin, and can't seem to figure out why the content array that should return search highlights is empty. Title is functioning as expected. 

I've also tried sending a query directly to the api [as described](https://wpvip.com/documentation/vip-go/elasticsearch-on-vip-go/#search-api), but receive: a `not an allowed highlighted field` error (when trying to add a wildcard or attempt to use force_source) 

#### Steps to reproduce the issue
1. Send any query with highlight_fields parameters 
2. Inspect response

Happy to provide my siteID privately if needed. Brooke (from VIP) recommended I check in here.

**Screenshots**
<img width="500" alt="Screen Shot 2020-02-19 at 3 20 09 PM" src="https://user-images.githubusercontent.com/3232346/74885887-821f2600-532b-11ea-9d48-c6fcea7c2c97.png">

**Comment by gibrown** [comment]
Hi @jakeols excited to have you trying it out!

First let me verify a few details:
- You are running the instant search prototype and enabling it based on https://jetpack.com/support/beta-instant-search-and-filtering-prototype/
- You were manually querying the api (should be the v1.3 api) to get those results (it looks like it)?
- Are you looking to build your own UI with those api results, or just use it as is?

A few pieces of background:
- The prototype has changed a lot from what we were showing in this post: https://jetpack.com/2019/11/05/79-peek-future-jetpack-search/. The big change is that we have moved to using an overlay rather than trying to integrate with the existing theme.
- Currently the new UX is not in a Jetpack release, but it will be in the release coming out next week (March 3rd), or you can run the Jetpack beta which should be available tomorrow.
- If you want to just play with UX quickly, feel free to try it on my demo site which is also configured to accept any blog_id: http://gibrown.wpsandbox.me/demo/?s=related%20psts&blog_id=9619154 This site is running our feature branch which we should be merging into master today. (This though doesn't let you play with the customization options that we have added see https://cloudup.com/cqg-dKcYH9m)
- The instant search API is not really an ES API anymore though we do a lot of things in a similar way. This lets us do multiple searches on the backend when it makes sense (e.g. spelling correction). 

On the highlight field specifically, we are no longer accepting the "real" ES field names because we are sometimes dynamically selecting which field a bit and I expect we will do more of this in the future. So the `highlight_fields` param is defined as `(array) List of fields to highlight.` with the accepted strings of: 'comments', 'content', and/or 'title'.

I think what is happening is that there is no content (or tags/categories) on that top search result and so we have nothing to return. So we end up falling back to the path for the post. This is kinda our worst case fallback right now. The code for this fallback is here: https://github.com/Automattic/jetpack/blob/master/modules/search/instant-search/components/search-result-minimal.jsx#L43

**Comment by jakeols** [comment]
> You are running the instant search prototype and enabling it based on https://jetpack.com/support/beta-instant-search-and-filtering-prototype/
You were manually querying the api (should be the v1.3 api) to get those results (it looks like it)?
Are you looking to build your own UI with those api results, or just use it as is?

Yes, the prototype is enabled and I'm using v1.3 for those results. I'm looking to build my own UI for these results. I've also tested with our `blog_id` on your sandbox (which, by the way, is extremely helpful!)

> On the highlight field specifically, we are no longer accepting the "real" ES field names

Ah, this makes a lot more sense now. Is there any way with the current api to force a return of where this search was matched? (I'm not really sure what the ES setup for this looks like under the hood for you). Currently, we just have a lot of queries where it's not obvious where the match is happening (see screenshot below). 

<img width="508" alt="Screen Shot 2020-02-24 at 2 08 32 PM" src="https://user-images.githubusercontent.com/3232346/75195798-76f33e00-570f-11ea-987d-cd56174f49cf.png">

**Comment by gibrown** [comment]
> I'm looking to build my own UI for these results.

Cool! I'd be curious to hear if you want to try and reuse our code to some extent or if there are things we could to do to make building your own integration easier. For instance, if you are just changing how the results look, I wonder if we could provide hooks for doing that in our JS. We have also considered building some form of a template language (probably based on Gutenberg formatting) that would move us in the direction of accepting a result template to display results. cc @jsnmoon 

Are you planning to integrate the search results directly into the page, or into an overlay?

I will also caution you that the reason why this API is not yet documented publicly is because I still consider it under development and we could still change some things. It is also built to do things like mix different result types. Right now it only returns posts, but we likely will add tags/categories in the future.

> Is there any way with the current api to force a return of where this search was matched?

We do matching against more than the content that we currently display in the UI. We may expand the available highlighted content in the future (or more likely we will let the end user customize it). On the back end our query matches just about every piece of text we can associate with a post, and then we use boosting to adjust the ordering.

That particular example is matching the path for the post which has the word "advocacy" in it: `/advocacy-movement-capacity-building/movement-capacity-building/`. We have considered adding the url/path to our search results to handle this type of case (and some others), but we have wanted to avoid taking up too much space. cc @keoshi

**Comment by jakeols** [comment]
> That particular example is matching the path for the post which has the word "advocacy" in it

Ah, got it - the results make a lot more sense now

>  I'd be curious to hear if you want to try and reuse our code to some extent 

Right now I'm actually re-using some of the code in `lib` (specifically `api.js` and `query-string.js`). Our design on the UI side was fairly stripped down (no filters, using a page not an overlay, etc.) Essentially all that is needed is just the post title and highlight.

**Comment by gibrown** [comment]
Very cool. I'm going to close this issue for now, but let us know if you have any more issues.

**Comment by jakeols** [comment]
Hey @gibrown , one last thing I'm looking into:

> On the back end our query matches just about every piece of text we can associate with a post, and then we use boosting to adjust the ordering.

Does this also include any whitelisted post meta that has been added? I've whitelisted and manually initiated a re-sync of the index, but don't seem to see the expected content being returned (although there may be the possibility i'm missing something from [here](https://wpvip.com/documentation/vip-go/elasticsearch-on-vip-go/#searching-through-and-indexing-post-meta)).

**Comment by gibrown** [comment]
Hi @jakeols 

Ya, so we are moving towards building a consistent set of post meta (and custom taxonomies) that we index. Right now the code only really exists on wp.com and the plan is to eventually sync that code into Jetpack to ensure that the correct post meta gets synced.

Currently that code only exists in a single branch (and doesn't at all work), but you can see what we are syncing/indexing here: https://github.com/Automattic/jetpack/blob/add/search-post-meta/packages/sync/src/modules/class-search.php

So any post meta that is currently getting synced will get indexed based on that spec (e.g. if it has the "searchable_in_all_content" param set to true then we will match against it). I want to keep the post meta keys generic, but the idea is that we can easily add more over time. If you have any more keys you want or have reasons why some of the existing ones should have "searchable_in_all_content" set to true, then let me know and I can add them on the backend and reindex your site.

**Comment by jakeols** [comment]
Thanks @gibrown!

So, let me just make sure I understand: if I have whitelisted post meta through `jetpack_sync_post_meta_whitelist` it's not going to show up with this API because it doesn't have the `searchable_in_all_content` param? 

This would make sense to me, as for our custom newsroom the blog content is saved under a post meta key called `content_body-full_content` that I have whitelisted but fail to see matches against that content.

**Comment by gibrown** [comment]
Yep that is right. This is a new site right? Is it possible to move the post meta into `content` https://github.com/Automattic/jetpack/blob/add/search-post-meta/packages/sync/src/modules/class-search.php#L213)?

I'm not against adding that post meta key I guess. Is there a reason behind the naming? Does this mean that there are also other `content_body-*` fields or `*-full_content` fields that we should add?

**Comment by jakeols** [comment]
Awesome - makes sense. This isn't a new site (and the post metas aren't something that I'm able to change). Do you think I'm better off using something like [this](https://wpvip.com/functions/es_api_search_index/)? (and just writing our own ES queries)

**Comment by gibrown** [comment]
> Do you think I'm better off using something like this?

ya that won't really work for you unless you want to add your own endpoint and then it will be slower than what we have also.

I've added the `content_body-full_content` field and reindexed your site so you should now see matches against it.

This won't help you with displaying what is matching though since we only display matches against what is in post_content, post_title, and comments. I opened https://github.com/Automattic/jetpack/issues/14911 to track that, but it is a bigger change and we won't be able to work on it for a while.

Let me know if this works for you. This is the first time I have tried adding a field like this, so I'm still trying to wrap my head around when I do it and what the process should look like which is why I asked a few questions first. After a bit of reflection I think I should almost always just add the field once someone asks.

**Comment by jakeols** [comment]
Thanks for adding that key and opening that issue (that would pretty much solve our use case). 

For this in #14911 ,
> create a separate field that combines content and specific post meta (maybe we display other matches also?)

I wonder if it makes sense for the time being to extract out the fields we want to highlight from and update them into `content` using `updated_post_meta`, `added_post_meta` and `deleted_post_meta` - that seems like the approach you're going for, correct?

**Comment by gibrown** [comment]
> I wonder if it makes sense for the time being to extract out the fields we want to highlight from and update them into content using updated_post_meta, added_post_meta and deleted_post_meta - that seems like the approach you're going for, correct?

Ya, that would take care of your use case. Mostly we expect to have the correct data in post_content and so we also will boost matches against content that is in there a lot better as well.
