### ISSUE TITLE
Carousel - Comments on the Right

### ISSUE THREAD

**Issue by hirenshah** [Automattic/jetpack#14962]
Would it be possible to have the option of moving the comments section to the right hand side (rather than the bottom)?

**Comment by jeherve** [comment]
That is not something we are likely to implement, as it would mean having smaller pictures in the Carousel view to accomodate for the comments section. Since Carousel's original goal was to put images front and center, we probably won't be implementing such a change in Jetpack.

If you are interested in such a feature, I would recommend that you try to implement the change with Custom CSS on your site, or turn to a different Carousel plugin that offers that option.

I hope this clarifies things a bit.
