### ISSUE TITLE
Stats: many transient database requests generated on each page load

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1499]
Stats use the `Jetpack_Client::remote_request` ([ref](https://github.com/Automattic/jetpack/blob/3.3/modules/stats.php#L425)), thus indirectly triggering `wp_generate_password` ([ref](https://github.com/Automattic/jetpack/blob/bdfc92311418c8dde187b5df4cd686b17d97c44a//class.jetpack-client.php#L54)). This function itself uses `wp_rand()` to generate a random number ([ref](https://core.trac.wordpress.org/browser/tags/4.1/src/wp-includes/pluggable.php#L1985)). That number is stored in a transient by WordPress ([ref](https://core.trac.wordpress.org/browser/tags/4.1/src/wp-includes/pluggable.php#L2018)).

In some cases, that transient appears to be updated up to 28 times per page load when Stats are active:
https://wordpress.org/support/topic/jetpack-statistics-causing-mysql-errors?replies=1

What could cause this issue?

**Comment by jeherve** [comment]
More details from the site owner:

> We are not running the latest version of mysql however. Could that be an issue? We are running 5.0.96-community.
>
> I didn't actually count the number of times it occurred on the second website. The 28 was the number it occurred on the first site, and once I disabled the stats, I had 0 counts. And it was 28 times on each page, whether the home page or an article.
>
> In each case, the requests overwhelm the database and then corrupts the table

**Comment by perdrix** [comment]
We are now running MySQL 5.6.22. The issue remains with the 28 updates to the transient. We were able to additionally narrow it down to a conflict between Jetpack Stats and MathCaptcha by dFactory:

https://wordpress.org/plugins/wp-math-captcha/

Disabling either their plugin or Jetpack stats stops the pages from trying to update the database 28 times. In fact, disabling either plugin stops any calls to update the _Options table.

**Comment by samhotchkiss** [comment]
Very odd-- have you reported this to them?

**Comment by perdrix** [comment]
I have now. I just discovered this today.

**Comment by samhotchkiss** [comment]
Sounds good-- we probably aren't going to be able to check it out in this release cycle, but if you can report back with what they say, we'll look at it from our end for the next cycle

**Comment by perdrix** [comment]
The following is the conversation between Bartosz Arendt of dFactory and myself. I'll let him describe how he worked around the issue... he's still not sure why there was a conflict with Jetpack stats initially.

-------

I think I have an idea of how this happens, but I don't know why.

Math Captcha is using set_transient but it's done once for a cookie lifetime. But there's also a wp_generate_password() function involved which is using wp_rand().

Turns out wp_rand() runs set_transient after each 14 uses - it generates new random string and stores it in '_transient_random_seed'.

I know what we can do on our side (switch from wp_rand() to custom helper function).

Question is what it has to do with Jetpack?

Regards,
Bartosz Arendt / dFactory


dFactory
Member
Plugin Author
Posted 19 hours ago #

Should be resolved in just released 1.2.4

But Jetpack guys should take a look at the issue independently I think.

**Comment by jeherve** [comment]
This does not seem to be an issue anymore. Closing. Let's reopen this issue if the problem pops up again.
