### ISSUE TITLE
Social Menu & Social Media Icons: RSS icon visible when URL contains `feed`

### ISSUE THREAD

**Issue by nielslange** [Automattic/jetpack#15162]
This issue had been reported by @ezebecke on https://github.com/Automattic/themes/issues/1869 as follows:

## Steps to replicate

[Please include screenshots, browser information, and anything else that can help us recreate the problem.]

Add a social menu item with a URL containing the word `feed` somewhere on the slug. Example: https://instagram.com/testfeed/ or https://twitter.com/feedtest

## Result

![Screen Shot 2020-03-26 at 22 26 43](https://user-images.githubusercontent.com/24919469/77718436-f1cea380-6fb0-11ea-930a-03a982a6013b.png)

Instead of the social network icon, the RSS feed icon appears.

## Expected

To see the social network icon. 

![Screen Shot 2020-03-26 at 22 30 19](https://user-images.githubusercontent.com/24919469/77718653-76212680-6fb1-11ea-9052-b688027348dc.png)

* User report: #19672577-hc
* Follow-up ticket: #2822148-zd

I couldn't figure out if it's a Jetpack issue. Pardon me if this needs to be reported on Jetpack.

**Comment by fresatomica** [comment]
This might be related, a user reported that when adding a link to their WordPress feed, they get two icons stacked on top of each other. The WordPress logo icon and the feed icon:

![Screen Shot on 2020-05-05 at 09-33-21](https://user-images.githubusercontent.com/40177971/81044137-048f9e80-8eb4-11ea-8cfe-8ec553764fbf.png)

I think it may be related because the link also contained the word "feed".

Reported [here](https://wordpress.org/support/topic/jetpack-social-widget-2/).

**Comment by willnorris** [comment]
@fresatomica, it's definitely related.  The problem is that both patterns match the given URL, and jetpack isn't stopping processing feed icons after it's found a match.  PR coming shortly.
