### ISSUE TITLE
Single Products: needs better/consistent copy and design work

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#15183]
Problems both in Calypso now that there is more than one plan:

<img width="1086" alt="Screen Shot 2020-03-29 at 12 36 11 PM" src="https://user-images.githubusercontent.com/820871/77857379-37aa8800-71ba-11ea-8919-5c983ac1683b.png">

and in wp-admin:

<img width="1136" alt="Screen Shot 2020-03-29 at 12 40 26 PM" src="https://user-images.githubusercontent.com/820871/77857426-9839c500-71ba-11ea-9a96-b18c2690fc37.png">

Note that you can't purchase a monthly backups plan from the UI.

@robertbpugh I think we need new and consistent copy for the various products

**Comment by robertbpugh** [comment]
Good catch. Can you just move that backup line into the backup box after
"Always-on backups..." I don't think we need to replace it with anything
else.

@keoshi can we look at these? I have lots of questions/updates.

- Do WP Admin and Calypso have different monthly/ annual toggles. Because
the copy is different in each box
- Can we also update the copy in the search box? Maybe from the LP: "Incredibly
powerful. Fully customizable. Jetpack Search helps your visitors instantly
find the right content – right when they need it."
- Also let's change to "You are saving $10 by paying annually."
- CTA: do you prefer existing or "Upgrade Your Search"

**Comment by keoshi** [comment]
Yeah @robertbpugh, let's tackle these together. Some answers below:

> - Do WP Admin and Calypso have different monthly/ annual toggles. Because
the copy is different in each box

They are different. For example: the monthly/annual toggle in wp-admin only works for plans, not for single products. For the copy specifically (I assume you're talking about “Monthly/Yearly” vs “Monthly/Yearly Billing”) there's no reason why we can't make them consistent.

> - Can we also update the copy in the search box? Maybe from the LP: "Incredibly
powerful. Fully customizable. Jetpack Search helps your visitors instantly
find the right content – right when they need it."

> - Also let's change to "You are saving $10 by paying annually."

I like that.

> - CTA: do you prefer existing or "Upgrade Your Search"

I don't know — what do you think it's better: cater each copy according to the product, or make all single products consistent between them? Upgrade currently has “Upgrade to [product name] for [price] per [billing cycle]”. I worry about this inconsistence, but purely from a copy perspective I much prefer your suggestion “Upgrade your Search” or “Upgrade your site Search”.

**Comment by keoshi** [comment]
I'm going to take a stab at this one.

**Comment by keoshi** [comment]
Jetpack PR is ready for review here: https://github.com/Automattic/jetpack/pull/15237

**Comment by keoshi** [comment]
Calypso PR is ready for review here: https://github.com/Automattic/wp-calypso/pull/40672
