### ISSUE TITLE
Subscriptions: Remove the shortcode

### ISSUE THREAD

**Issue by scruffian** [Automattic/jetpack#15227]
The Subscriptions block outputs a shortcode.

#### Describe the solution you'd like
We should remove this, and output the markup we want for the block directly [as suggested](https://github.com/Automattic/jetpack/pull/15107#discussion_r398843320) by @mtias 

#### Describe alternatives you've considered
Keeping the shortcode means that people who use the shortcode continue to be able to benefit from the additional features we add, but this results in more complex development and doesn't encourage people to move to Gutenburg.

**Comment by mmtr** [comment]
We created a separated issue for stopping using the `simple-payment` shortcode as output of the "Pay with PayPal" block: https://github.com/Automattic/jetpack/issues/17246 (fixed by https://github.com/Automattic/jetpack/pull/17256).

I've updated this issue to reflect we only need to handle the Subscriptions block now.

**Comment by simison** [comment]
Thanks for this! Leaving the shortcode in Simple payments block was one of my biggest regrests. 😅 

It came from wish to not add yet another simple payments implementation (alongside widget, classic editor block, and shortcode) but it turned out to be short-sighted and caused more trouble than it was aiming to save time.

**Comment by coreymckrill** [comment]
Noting that, at present, shortcodes included in the block templates and block template parts of FSE themes are not rendered, and that probably [won't change](https://github.com/WordPress/gutenberg/issues/23626). It seems like that might make this issue a bit more urgent.

**Comment by simison** [comment]
@jeherve 👋 this issue should be tracked for WP 5.9 readiness.

**Comment by jeherve** [comment]
> this issue should be tracked for WP 5.9 readiness.

Could you clarify a bit what you mean by that? Would 5.9 break rendering of shortcodes in some way?

**Comment by TimBroddin** [comment]
This is fixed with https://github.com/Automattic/jetpack/pull/26947
