### ISSUE TITLE
Podcast Player: Keep side-gutters clear

### ISSUE THREAD

**Issue by obenland** [Automattic/jetpack#15262]
Let's make sure everything aligns with these red vertical lines on both sides.
 Nothing (player controls or episode details) should be protruding past them:

<img width="638" alt="sides" src="https://user-images.githubusercontent.com/1398304/78305224-3c8e7500-74f5-11ea-8941-053bf1f3742a.png">

**Comment by marekhrabe** [comment]
@lessbloat this should be good to do as described, right? 

I was also thinking about a related issue. Due to those spaces left for status icons on the left side of tracks, to me this block feels strangely misaligned until at least one icons shows up. Any concern or should we just go with it as is?

**Comment by davemart-in** [comment]
> Due to those spaces left for status icons on the left side of tracks, to me this block feels strangely misaligned until at least one icons shows up. Any concern or should we just go with it as is?

Let's just make sure the "playing" icon is also aligned when it's showing and call it good. Thanks!

If we were worried about it, we could experiment with just adding an opacity to the "playing" icon (perhaps `opacity: 30%;` when the track is paused) and just leave it showing rather than hide it:

<img width="767" alt="opacity" src="https://user-images.githubusercontent.com/5634774/78375925-8af64f00-759b-11ea-91b1-3ba00b65d83f.png">

But I'm not super worried about it.

**Comment by WunderBart** [comment]
Fixed by https://github.com/Automattic/jetpack/pull/15356.
