### ISSUE TITLE
Podcast Player: Add support for Google, Apple, and Spotify subscription links

### ISSUE THREAD

**Issue by obenland** [Automattic/jetpack#15264]
Let's add a block setting to display Google, Apple, and Spotify subscription links, so visitors can subscribe to the podcast or the episode. These links could be added manually to start. We’ll want to include toggles within the right sidebar to turn them both on/off individually.

**Comment by frontdevde** [comment]
@davemart-in Would it be possible to provide us with some design guidance here? 

In wp-p7DVsv-8oS#comment-27709 it was suggested that allowing the user to add these links manually would suffice (initially).

We also discussed some concerns in Slack around adding this as a feature. Marek will chime in below.

**Comment by marekhrabe** [comment]
I have concerns this is not entirely in the scope of "Podcast Player". Adding more features like this directly in the single block will make it hard to use and even harder to maintain from the developer perspective. There is also a huge number of places where podcasts will be hosted - I think we should support linking anywhere, not just a handful of services we like.

The power of the block approach is building your things from small blocks and having the freedom to position them, align them add things in between etc…

I agree it's really useful to link to places where your podcast is available but since the RSS doesn't give use those external links, we cannot make it any more convenient to the user. 

What if we instead looked at this from the block-first perspective and came up with a way to recommend using for example Buttons block? Social Icons might also be a great match - maybe we can improve them by adding more icons for related services, if some are missing…

**Comment by davemart-in** [comment]
Valid concerns. Thanks for raising them Let's hold off on adding this to the Podcast player block for now. In the meantime, people can always manually add buttons or links below. If we hear a bunch of feedback from customers regarding providing a way to display buttons, perhaps we can create a complementary block with easy toggles for the most popular services. 

cc @amamujee
