### ISSUE TITLE
OpenTable block: Button style has built in padding

### ISSUE THREAD

**Issue by alaczek** [Automattic/jetpack#15267]
OpenTable's block button style has padding around it, which makes it impossible to properly align with text.

#### Steps to reproduce the issue

1. Add a paragraph of text, and OpenTable block below. Use the button block style.
2. Notice how the button does not align with text.
3. Preview the page. Inspect with developer tools and notice the button has built in padding around.

#### What I expected
To be able to align button with text.

**Screenshots**

![image](https://user-images.githubusercontent.com/4550351/78322531-bb011a80-75ba-11ea-9531-9ea608b56bcc.png)

**Comment by glendaviesnz** [comment]
I have had a look at this, and unfortunately this padding is set by OpenTable, and because this is within an iframe have no way of overriding this style:
<img width="901" alt="Screen Shot 2020-04-14 at 4 29 59 PM" src="https://user-images.githubusercontent.com/3629020/79186318-6177d600-7e6d-11ea-8eae-221d23afe936.png">

In theory we could set a negative margin on the parent container to pull it back 14px, but because of the strange and varied ways that themes handle the different alignment values of blocks this isn't possible in practice (and would be fragile if we could anyway as it would break if OpenTable happened to changed their padding values).

I may be missing something, so happy for others to take a look, otherwise I suggest we close this one.

**Comment by creativecoder** [comment]
@glendaviesnz 

Two work around ideas (that may be bad!) for implementing a negative margin. What do you think?

1. Add a check box for "Remove button margin" (or similar) to the block settings so user can toggle this on. ~~If~~ When it breaks, they at least have an easy way to turn it off
1. Same idea, but create a css class that does this that can be added to the block. We can add it to the documentation as a sort of "advanced level" feature, which won't pollute the settings bar for users who don't have any interest in it.
