### ISSUE TITLE
Instagram Gallery block: Improve the access token usage

### ISSUE THREAD

**Issue by Copons** [Automattic/jetpack#15276]
In #15091 I've connected the Instagram Gallery block with the Instagram Basic Display API.
Currently, the token is saved as block attribute. It's a straightforward solution, but also one that has some inherent problems.

See original discussions at https://github.com/Automattic/jetpack/pull/15091#discussion_r400587587 and https://github.com/Automattic/jetpack/pull/15091#issuecomment-608375862

- [x] Reuse token across blocks. _(Slated to future iteration)_
- [x] Improve token privacy.
- [x] Limit the block to WPCOM-connected sites.
- [x] Display error messages.
- [x] Show notice that user (not just site) needs to connect to WPCOM to connect to Instagram.
- [x] Guard against the API returning null

### The token is not reused across blocks

_This is a nice to have but can wait for a future iteration of the block._

Every time a user inserts a new Instagram Gallery block, they have to connect it to their Instagram account again.

A possible solution would be to store it as site option, and use it with `useEntityProp` (double-check if available on JP).

### The token is supposed to be personal.

Saving it as block attribute means that users with the `edit_others_posts` capability (the token is not exposed on the front end) could easily copy it and use it in ways that the token owner might not be aware of, or agree with.

Could it be possible to store it as user option?
What would happen if user X inserts the block and connects it to their Instagram account, then user Y edits the same post?

### Does the block need to be connected to WPCOM?

The block requests the access token passing through WPCOM (`wpcom_json_api_request_as_blog` and `wpcom_json_api_request_as_user`).
Is there a way to make it work without relying on being connected to WPCOM?

Note: the block is registered regardless, but we'd need to only register it if the site and user are connected to WPCOM.

Note 2: the block saves the fetched Instagram Gallery in the post content, so disconnecting the site from WPCOM would not affect the block on the front end.

### Errors handling

The Instagram widget handles API errors admirably, with several different messages in both the editor and the front end.
We should replicate them in the block as well.

Examples:

- Front end (only visible to admins):
  - Returned images is not an array:
`There was an error retrieving images from Instagram. An attempt will be remade in a few minutes.`
  - No images:
`No Instagram images were found.`
- Editor:
  - Failure to retrieve the connect URL:
`Instagram is currently experiencing connectivity issues, please try again later to connect.`
  - Generic connection troubleshooting message:
`Having trouble? Try <a href="https://instagram.com/accounts/login/" target="_blank">logging into the correct account</a> on Instagram.com first.`

### User needs to be connected to WPCOM

_Investigation required!_

I was under the impression that only the site needed to be connected to WPCOM in order for this block to work.
This is apparently not the case: the user needs to be connected to WPCOM to connect to Instagram, otherwise `GET connect-url` would return 500.

As [suggested](https://github.com/Automattic/jetpack/issues/15276#issuecomment-608408520) by @pablinos, we should show a notice on the block placeholder for users not connected to WPCOM, and prevent them from disconnecting from Instagram existing blocks.

### The API might return null

_Investigation required!_

This happened while testing with a secondary account, connected to a secondary WPCOM account (not the same used to connect JP to WPCOM).

Trying to connect to Instagram, `GET connect-url` returns 200 with no body.
I've tried to backtrack the whole stack, as when I created the `connect-url` endpoint I've only tested for `WP_Error`:

- `connect-url` calls `sites/external-services`, and returns either `WP_Error` or `$body->services->instagram->connect_URL`.
- `sites/external-services` creates the connect URL with `wpcom_keyring_get_connect_URL` from Keyring.
- Keyring uses `Keyring_Util::admin_url` which uses a filter, etc.

Somewhere this returns null, which propagates back to the `connect-url`, where it passes the `WP_Error` test and is sent back to the block.

See p1586965076081800-slack-explorers

**Comment by pablinos** [comment]
> Note: the block is registered regardless, but we'd need to only register it if the site and user are connected to WPCOM.

I'm not sure I understand this point, but we would need to access Instagram via WPCOM, because we run the approved app. If the user and/or site are not connected to WPCOM then we probably need to show a nudge when they insert the block, and prevent editing of existing blocks.

> Note 2: the block saves the fetched Instagram Gallery in the post content, so disconnecting the site from WPCOM would not affect the block on the front end.

Good point. Should we have it server side render too, so that images update dynamically? Or offer that as an option?

**Comment by pablinos** [comment]
> Saving it as block attribute means that users with the edit_others_posts capability (the token is not exposed on the front end) could easily copy it and use it in ways that the token owner might not be aware of, or agree with.

I'm wondering if we could store the ID with a signature (or as an encrypted value) made from some secret, the user ID, token ID and post ID. It would involve having to get the signature from WPCOM, but we're going back and forth there during the authorisation flow anyway. It would be a bit like a nonce to prove that the attribute value was set by that person on that block in that post.

> Every time a user inserts a new Instagram Gallery block, they have to connect it to their Instagram account again.

I like the idea of caching the token ID in a user attribute, so this reconnection doesn't need to happen each time. As the block is inserted, we could check on the server for a valid token, or if we're using the technique above, ask for the signature (or encrypted version) to store it in the block attributes.

---

All of this feels a bit like overkill and that I'm missing something simple. I'll give it some more thought and see what other solutions come to mind.

**Comment by glendaviesnz** [comment]
@pablinos, @Copons  - partly related this I had a play around with [adding a custom hook](https://github.com/Automattic/jetpack/pull/15325) so we can pull some of this business logic out of the UI component, and also to allow sharing it with other components that might need it in the future -  open to feedback on whether you think this is worth doing at this stage or not.

**Comment by scruffian** [comment]
Should we also get the block working with the token from the old widgets?

**Comment by glendaviesnz** [comment]
> I'm wondering if we could store the ID with a signature (or as an encrypted value) made from some secret, the user ID, token ID and post ID

This seems like the easiest way, as the alternative is to have to check the permissions of the current user to use the token either on post save, and on frontend parse (this is trickier as here you need to see if any of the current site admins can use that token which could be expensive)

There will be some key already on wpcom that we can use, eg. the nonce key, and if we make the signature 'secret, tokenID, siteID, pageID' then on the front end parse it is easy to validate the token signature against those values for the currently loading page, if someone tries to copy the block token to another page or site it will fail to load on the front end. 

Rather than a signature, as @pablinos mentions we could encrypt the whole lot and only store an encrypted version of those values in the block rather than the actual token and signature - not sure if there is  much performance difference between signature validation and string decyrption, but the encryption option has the advantage of other users not  seeing the actual token value.

**Comment by pablinos** [comment]
I'm not sure about the performance either, but I was thinking that we could use the same signature code we've developed to deal with the signed requests from Facebook. 

>  the encryption option has the advantage of other users not seeing the actual token value

Yes, that's the advantage, but with the other values used for the signature, the only one exposed would be the token ID, which should be pretty useless.

I don't feel strongly either way though. I wonder why Facebook favours signing? Maybe because the signed request is only a one-time thing between us and Facebook, so it's less likely to be seen by someone else.

**Comment by glendaviesnz** [comment]
I explored the signature approach and it seems like it will be pretty simple to do ... needs a bit more discussion though so will P2 it.

**Comment by Copons** [comment]
All done! ✨
