### ISSUE TITLE
Comments: Resources loaded over HTTP when using Cloudflare's Flexible SSL

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#1535]
A user is using Cloudflare's Flexible SSL to allow visits to their site over either HTTP or HTTPS. Their site and home URLs both just use HTTP, however when someone visits their HTTPS site, a Mixed Content message is seen for the resource at http://jetpack.wordpress.com/jetpack-comment since it's loaded over HTTP.

It seems that we should be able to serve that over HTTPS regardless of the user's site settings, no?

**Comment by georgestephanis** [comment]
Where it's decided: https://github.com/Automattic/jetpack/blob/3.3/modules/comments/comments.php#L244

I'd be fine switching it to HTTPS only, I think.

**Comment by georgestephanis** [comment]
That being said, I'd say there is a problem with the CloudFlare bit as it's not being picked up as SSL properly by `set_url_scheme()` or `is_ssl()`

**Comment by georgestephanis** [comment]
This may help -- unsure -- https://wordpress.org/plugins/ssl-insecure-content-fixer/

**Comment by xyu** [comment]
The problem here is CloudFlare Flexible SSL should only be used when the origin server does not support SSL. Which means the connection looks something like this:

:bust_in_silhouette: ---HTTPS---> CloudFlare ---HTTP---> Origin (WP server)

So for all intensive purposes to WP there is no SSL at all. CloudFlare does send a header which can be used but trusting this header is a bit dodgy because anyone can spoof it. Although in this case the user is using Flexible SSL anyway so it's not the most secure to begin with. To do that the user will need to do something like:

https://github.com/xyu/heroku-wp/blob/master/support/app_nginx.conf#L11-L13
https://github.com/xyu/heroku-wp/blob/master/support/app_nginx.conf#L129-L140

**Comment by bhubbard** [comment]
How about letting supporting something like `define ('JETPACK_FORCE_SSL', true);` in wp-config.php?

**Comment by kraftbj** [comment]
Specific to Cloudflare, I believe their plugin aids with much of this: https://wordpress.org/plugins/cloudflare/

I'd lean more toward https all the things than a constant. jetpack.wordpress.com specifically should work in all browsers, except IE 6 on XP (SSLv3, IIRC) under SSL.

**Comment by samhotchkiss** [comment]
I agree with @kraftbj -- if this is still a painful issue with the Cloudflare plugin, we can reassess, but I would also be happy with erring on the side of extra ssl rather than getting too much logic involved

**Comment by jeherve** [comment]
When using a setup like [this one](https://jeremy.hu/cloudflare-flexible-ssl-wordpress/), the comment form is displayed properly and doesn't generate any warnings. If they do, [send us an email](http://jetpack.me/contact-support/(!
