### ISSUE TITLE
Instant Search: immediately trigger overlay on click

### ISSUE THREAD

**Issue by aheckler** [Automattic/jetpack#15359]
As it stands now, using Instant Search, users need to start typing a search into (for example) their sidebar search field before our overlay pops up. This sort of changes the interface while I'm typing.

Some folks (me at least :P) might prefer the overlay to pop up _immediately_ when I click into a search field.

**Comment by gibrown** [comment]
I think when we tried this in the past a lot of folks didn't like how the UX felt. Do you have an example site showing where you don't like it?

cc @keoshi

**Comment by keoshi** [comment]
I wonder if this should be an option. Realistically I think we'll learn a lot about our product in the next few weeks, and hopefully that will give us good bases for the next iteration.

**Comment by aheckler** [comment]
> I think when we tried this in the past a lot of folks didn't like how the UX felt. Do you have an example site showing where you don't like it?

My first reaction to the current UX was that I'd personally prefer the overlay to appear right away, instead of waiting for me to type something. By waiting, and then changing the UI underneath me as I'm typing, it made me a bit uncertain as to what was happening, like maybe I hadn't waited long enough for the overlay to load and it was trying to "catch up." ¯\\_(ツ)_/¯ 

An option to trigger the overlay immediately would be cool, but that's just my two cents.

**Comment by keoshi** [comment]
That's great feedback. We pondered if opening the overlay immediately would create more confusion, while changing the UI while someone is typing (because ideally we wait for some results to be returned to open the overlay) would feel more natural since the search query is entirely preserved.

As an MVP we could add that as a binary option — open immediately vs wait for search results —, though I always go back to “decisions, not options”.

Have you heard this from anyone else? Would be cool to ask around and see how people feel about it. It could be a good minimal research exercise.

**Comment by aheckler** [comment]
> Have you heard this from anyone else? 

I have not.

**Comment by gibrown** [comment]
We missed closing this, but it has been live for a while, we have iterated on it, also there are some options in https://jetpack.com/support/search/install-search-on-your-site/
