### ISSUE TITLE
Stats: Modernize Stats Footer Post ID

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#15582]
The stats footer inserts the post ID if this conditional matches true:
`if ( $wp_the_query->is_single || $wp_the_query->is_page || $wp_the_query->is_posts_page ) {`
but then inserts the post ID based on:
`$post = $wp_the_query->get_queried_object_id();`

There could exist situations where something matches those conditional but the queried ID is different.

We could likely make this more error-proof.

#### Steps to reproduce the issue

1. Based on the linked JPOP Issue. I'm not terribly sure how to get a Woo Product Category to think it is a page yet. Reading through the code, though, we probably can improve.

#### What I expected
Only insert the post ID if it is a page, post, or a CPT individual item.

#### What happened instead
It inserted a term_id instead.

**Screenshots**
n/a

**Comment by anomiex** [comment]
There's really not much to go on here. In particular, there seems to be no way to actually reproduce this for testing. So let's see where static analysis takes us.

As noted, we're running into a situation where `$wp_the_query->is_single || $wp_the_query->is_page || $wp_the_query->is_posts_page` test is true, but when `$wp_the_query->get_queried_object()` is called it winds up in the code path for `$this->is_category || $this->is_tag || $this->is_tax` and so returns a WP_Term rather than a WP_Post like we're expecting.

I have no idea how that might happen. Never mind that `WP_Query` seems like a mess, but also any random plugin might be overwriting any of those properties on the `$wp_the_query` object with inconsistent state because they're all public.

`->get_queried_object()` and `->get_queried_object_id()` seem fairly straightforward in comparison. The latter just returns whatever ID gets cached by the former. Looking through all the code paths in the former (and trusting other functions' `@return` declarations) it can return an object of type WP_Term, WP_Post_Type, WP_Post, or WP_User, or null, or possibly some other things in unchecked error cases. The code paths Stats seems to be intending to use are both supposed to return a WP_Post (or null).

Since the only possibility we seem to care about is when we get a WP_Post from `->get_queried_object()`, perhaps we can fix this by looking for that class specifically rather than trying to work out where the rest of the plate of spaghetti is getting screwed up.

**Comment by leogermani** [comment]
> or a CPT individual item.

Shouldn't we use `is_singular()` here? this will return `true` for any page querying for one single post of any post type.

> $wp_the_query->is_posts_page

This will return true if the "Posts" page is set to something different in the Settings > Reading options. Meaning it's a page that exists on the DB, but that actually displays a list of posts and not the content of that page. I think we want that...

Looking at the issue, chances are that a plugin or the theme is tweaking with the wp_query object to force the load of a different template but not keeping all the query parameters consistent.
