### ISSUE TITLE
(3P) Podcast Player: White-on-white controls invisible

### ISSUE THREAD

**Issue by obenland** [Automattic/jetpack#15611]
Player controls can become invisible when paired with a white background.

#### Steps to reproduce the issue

1. Theme: Twenty Twenty
2. Insert a Podcast Player block and load a podcast. I used https://anchor.fm/s/22b6608/podcast/rss
3. Player controls are white on a white background

#### Screenshots
<img width="512" alt="screen-shot-2020-04-29-at-10 44 38-am" src="https://user-images.githubusercontent.com/1398304/80625255-cbfa4b80-8a01-11ea-90c6-6277fea910e8.png">

**Comment by marekhrabe** [comment]
I was unable to reproduce in local Jetpack env. There is not much info in this issues so I have assumed to try `master` with the latest twenty twenty. I have tried with Gutenberg plugin (7.9.1 and 8.0.0) and without it in WP 5.4.1. In no circumstance, I have seen the state pictured above.

**Comment by frontdevde** [comment]
Thanks for helping me test this, @marekhrabe. I'm having the same issue of not being able to reproduce the bug reported here. Using twenty twenty I tested both locally on master as well as on dotcom staging without the bug surfacing.

**Comment by marekhrabe** [comment]
I have also tried to reproduce in a plain WordPress with the Jetpack Beta active and I couldn't reproduce in the Release Candidate nor the Bleeding Edge release.

**Comment by retrofox** [comment]
> I was unable to reproduce in local Jetpack env. There is not much info in this issues so I have assumed to try `master` with the latest twenty twenty. I have tried with Gutenberg plugin (7.9.1 and 8.0.0) and without it in WP 5.4.1. In no circumstance, I have seen the state pictured above.

Similar tests here. I wasn't able to reproduce it.

**Comment by jeherve** [comment]
> for WordPress installations in sub-folders.

👍 Good catch! I was able to reproduce on a site where WordPress is installed in a sub-folder.

I'd be okay shipping with this bug as it will only impact a subset of Jetpack sites. 

Were you able to make progress on this, or should we punt this to 8.6?

**Comment by obenland** [comment]
I've not been able to make much progress on it unfortunately. 8.6 sounds good, I'll get it on our board for a second look

**Comment by jeherve** [comment]
This also happens when using Jetpack's Asset CDN feature, as the svg path gets updated to this:
`https://c0.wp.com/wp-includes/js/mediaelement/mejs-controls.svg`

This will consequently impact more people than I originally estimated.

**Comment by davemart-in** [comment]
Yep, let's add this bug to our next cycle.

**Comment by marekhrabe** [comment]
Possible solutions discussed: 
- copy asset into our plugin and use relative dir walking like `url('../images/mejs-controls.svg')`
- since the plugins directory is at known depth, maybe we can walk relatively until `wp-includes`? `../../../wp-includes/js/mediaele…controls.svg`
- generate inline style in PHP with CSS rule and absolute URL for the asset (least nice but 100% works)

**Comment by jeherve** [comment]
> since the plugins directory is at known depth

I'm afraid we can't count on that since plugins directories can be set in custom locations.

> copy asset into our plugin and use relative dir walking 

Given that it seems that the file was not updated once since it was added to WordPress 3 years ago, maybe we can safely copy it for now?
https://github.com/WordPress/WordPress/commits/master/wp-includes/js/mediaelement/mejs-controls.svg
