### ISSUE TITLE
Podcast player: JavaScript error when scrolling through item

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#15677]
#### Steps to reproduce the issue

1. Open a post with a Podcast player in Chrome mobile (or with Chrome Dev Tools and responsive mode)
2. Click play to start playing
3. Click on the progress bar to move forward in the podcast that is being played. 

`Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().`
-- https://developers.google.com/web/updates/2017/06/play-request-was-interrupted

**Comment by mreishus** [comment]
I'm able to reproduce the issue. As noted, google[ documents how to fix the bug](https://developers.google.com/web/updates/2017/06/play-request-was-interrupted) by using the promise object returned by `.play()` before using `.pause()`.

### Not happening in Jetpack

* The [`<PodcastPlayer>`](https://github.com/Automattic/jetpack/blob/ef20dcfb96ff4ffdc179edd72847bf52a0855312/extensions/blocks/podcast-player/components/podcast-player.js#L25) and [`<AudioPlayer>`](https://github.com/Automattic/jetpack/blob/ef20dcfb96ff4ffdc179edd72847bf52a0855312/extensions/blocks/podcast-player/components/audio-player.js#L19) belong to Jetpack and do have calls to `.play()` and `.pause()`.  However, none of these calls are being used when the bug is triggered.

### Happening in external library mediaelement.js

* When triggering the bug by clicking on the progress bar to move forward, code within [mediaelement.js](https://github.com/mediaelement/mediaelement) calls in rapid succession: `.pause()`, `.play()`, `.pause()`, `.play()`.  This is an external library which we've included in the `wp-includes` directory of `wpcom`.
* Our version of mediaelement.js is slightly outdated, but upgrading it does not fix the issue.  We have 4.2.12 but the latest is 4.2.16.

### Cause: Touch events cause both "touch" and "mouse" events, and event handlers are firing twice

* The issue seems to be caused by mediaelement.js not handling touch events properly.  [A touch event on a mobile device generates both "touch" and "mouse" events.](https://www.html5rocks.com/en/mobile/touchandmouse/).  Generating a touch event on the progress bar causes both two fire, and the event handlers in mediaelement.js fire twice.  While `.pause()`, `.play()`, is likely intended, the library runs `.pause()`, `.play()`, `.pause()`, `.play()`, as both "touch" and "mouse" events are triggering the "pause, play" sequence.  The second pause interrupts the first play, causing the warning. See screenshot:

![2020-07-16_14-14](https://user-images.githubusercontent.com/937354/87713717-49676980-c770-11ea-9c04-9f92ceb6a200.png)

### Next steps

I don't think there is anything we can do here. I see the issue is already reported on the [mediaelement github](https://github.com/mediaelement/mediaelement/issues/2795).  I will update that issue with my specific findings.

**Comment by obenland** [comment]
Fantastic documentation of your research, thanks so much!

@jeherve How would you feel about closing this in favor of https://github.com/mediaelement/mediaelement/issues/2795?

**Comment by jeherve** [comment]
Nice sleuthing! I think we can close this issue indeed. 👍
