### ISSUE TITLE
Prevent loading unused code from jetpack.css

### ISSUE THREAD

**Issue by Mic2005** [Automattic/jetpack#15734]
#### Is your feature request related to a problem? 
We use Jetpack only for the Woocommerce mobile app so I switched all modules in Jetpack off. But I see that my site is serve full jetpack.css and nobody use it. Unused code slow down the site.[...] 

#### Describe the solution you'd like
Less modules, Less code. Not include unnecessary resources. 

#### Describe alternatives you've considered
Option to prevent loading jetpack.css.

#### Additional context
This optimalisation speedup all Wordpress websites with Jetpack so I think it's just a good idea to implement this feature.

**Comment by jeherve** [comment]
Instead of including a separate CSS file for each Jetpack feature, Jetpack enqueues only one file, built by concatenating all CSS from all Jetpack features. This limit the number of requests made when loading a site.

To deactivate this, you can use the `jetpack_implode_frontend_css` filter as explained here:
http://developer.jetpack.com/hooks/jetpack_implode_frontend_css/

When doing so, you'll ask Jetpack to only load individual stylesheets, for each  feature you may have activated on your site.

> Less modules, Less code. Not include unnecessary resources.

That's an alternative we've discussed as well, in #1258; it would be nice if one could customize the way `jetpack.css` is built so only active features would get concatenated.
