### ISSUE TITLE
Publicize to more than one Path account

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#1577]
(Note: I didn't create a new Path account to test if this is actually valid, as I don't have another mobile number I can give for verification purposes when creating the account).

The user in 2077049-t asks if it could be possible to add more than one Path account to Publicize.

**Comment by jkudish** [comment]
It is already possible. However not immediately straightforward.

So if you connect a Path account, and then try to it again, you are presented with this:

![screen shot 2015-05-02 at 1 33 59 pm](https://cloud.githubusercontent.com/assets/260253/7439805/ebcda356-f0cf-11e4-93f0-85485356f5a6.png)

This is because Path stored a cookie with the `partner.path.com` domain in your browser. In order to connect to a different account, you have 3 options:

* The simplest, is to press the `not you?` button and login again into the different account.
* Use a different browser or incognito mode.
* Manually remove the `partner.path.com` cookie.

![screen shot 2015-05-02 at 1 32 54 pm](https://cloud.githubusercontent.com/assets/260253/7439801/d49c7248-f0cf-11e4-973b-87f8dce67ccf.png)

Note: screenshots from WP.com but this would equally work from a Jetpack's site wp-admin.
