### ISSUE TITLE
Tiled Galleries: Color Value Error in CSS

### ISSUE THREAD

**Issue by emiluzelac** [Automattic/jetpack#1579]
Hi guys,

In https://github.com/Automattic/jetpack/blob/master/css/jetpack.css there is a small bug:

```
.tiled-gallery .tiled-gallery-item a {
    color: none;
}
```

There is no color value none.

**Comment by emiluzelac** [comment]
Thanks bud :)

**Comment by aheckler** [comment]
I'm no CSS expert, but I think `color: initial;` is what should be used?

**Comment by emiluzelac** [comment]
I don't believe that initial exist, maybe inherit.

**Comment by aheckler** [comment]
`initial` exists in CSS 3:

https://developer.mozilla.org/en-US/docs/Web/CSS/initial

It basically resets the property to the browser default, if I understand it correctly. Not supported in IE though.

**Comment by emiluzelac** [comment]
Never seen it before, cool I learned something new today 😀

**Comment by aheckler** [comment]
After some more poking around, I think `inherit` is the way to go here. `initial` [shouldn't be used on inherited properties](https://developer.mozilla.org/en-US/docs/Web/CSS/initial) (of which color is one). Working on a patch now.

**Comment by aheckler** [comment]
I tried to fix this in https://github.com/Automattic/jetpack/tree/fix/1579 but NPM was erroring out trying to install dependencies. Changing the version number to `3.6.0` (as a test) in `package.json` instead of `3.6-beta1` seemed to overcome that, but it still wouldn't install the dependencies.

@jeffgolenski -- does running Grunt work for you to update the concat'ed CSS? cc @kraftbj
