### ISSUE TITLE
(2P) Podcast Player: Don't render list for one episode only

### ISSUE THREAD

**Issue by WunderBart** [Automattic/jetpack#15803]
#### Is your feature request related to a problem? Please describe.
The Podcast Player block looks awkward with just one episode:

<img width="748" alt="Screenshot 2020-05-15 11 51 22" src="https://user-images.githubusercontent.com/1451471/82037476-7af58300-96a2-11ea-8ea4-31cb20f4494e.png">

The title is already in the heading and the media controls are already bound to that single episode - no need to click it first.

#### Describe the solution you'd like

Turn the heading into a link as a fallback and not render the list at all:

<img width="772" alt="Screenshot 2020-05-15 11 51 43" src="https://user-images.githubusercontent.com/1451471/82037597-a7110400-96a2-11ea-9ce5-c6ede140880d.png">

**Comment by frontdevde** [comment]
Just noting that we'll loose the only place where we're linking out to the episode if we remove it.
Related, should the current title at the top maybe become a link in general?

**Comment by jancavan** [comment]
> Just noting that we'll loose the only place where we're linking out to the episode if we remove it.

@frontdevde Just to clarify, do you mean clicking on in to play the episode?

**Comment by frontdevde** [comment]
@jancavan If you hover over the list item you'll see in the bottom left of the browser that it links to the episode. You can command + click it to go to the episode in a new window.

**Comment by jancavan** [comment]
Oh I see, thanks. It's not even obvious that it actually does that.

**Comment by jancavan** [comment]
Just to expand on the above ^:

- Add a link icon next to the episode title, this will link to out to the episode in a new tab.
- Episode title remains as is (ie: we don't turn it into a link to prevent users from inadvertently clicking on it due to size, only for it to link to the same episode)
- Apply the same behavior to each episode. This way, we attain consistency regardless of how many episodes are listed in the track list.
- In the mockup, I'm using `gridicons-link.svg` from Gridicons, but we also have `link` icons in Material and `@wordpress/icons` which look pretty much the same. Let me ask what we should be using because we don't have clear guidelines. I'll get back to you. @frontdevde

**Comment by jancavan** [comment]
@frontdevde Let's just use `link` from `@wordpress/icons` since this is a block within Gutenberg.
