### ISSUE TITLE
Modules: Option to disable Jetpack Blocks

### ISSUE THREAD

**Issue by supernovia** [Automattic/jetpack#16111]
#### Is your feature request related to a problem? Please describe.
This user feels like the Jetpack blocks are overtaking the edit screen:
https://wordpress.org/support/topic/disable-gutenberg-blocks/

#### Describe the solution you'd like
Offer an option in Modules and on the Writing page to disable Jetpack Blocks if wanted

#### Describe alternatives you've considered
There may be some custom code way of doing it, but giving folks an option could be better.

#### Additional context
Found while working in the forums at WordPress.org.

**Comment by jeherve** [comment]
You should be able to disable all Jetpack blocks at once by [adding the following code snippet](https://jetpack.com/support/adding-code-snippets/) to your site:

```php
add_filter( 'jetpack_gutenberg', '__return_false' );
```

Alternatively, you can the block manager that is available in WordPress itself to disable all blocks you don't need:

![Screen Recording 2020-06-10 at 10 30 AM](https://user-images.githubusercontent.com/426388/84245539-7d15fa80-ab05-11ea-89cc-540950473770.gif)

For this reason, we most likely won't implement a global toggle in Jetpack settings.

**Comment by matthewmcvickar** [comment]
> Alternatively, you can the block manager that is available in WordPress itself to disable all blocks you don't need.

Please note that the block manager only disables blocks for the user that's managing them. If you want these blocks disabled for all users, you should add the code snippet to your theme code.

**Comment by snow1776** [comment]
> Alternatively, you can the block manager that is available in WordPress itself to disable all blocks you don't need:

@jeherve  For me, I'm not seeing the jetpack blocks in the deactivate dialogue. For that reason, I'd ask that you consider opening this again. Even in your screen shot, the jetpack blocks are not shown.

**Comment by jeherve** [comment]
> I'm not seeing the jetpack blocks in the deactivate dialogue. For that reason, I'd ask that you consider opening this again. Even in your screen shot, the jetpack blocks are not shown.

If you do not see the Jetpack blocks in the dialogue, that should mean that the blocks are already not available for your user on your site.

My screenshot showed how things looked like with an older version of Jetpack. Since then we've made some changes to the way our blocks are categorized; you'll find some of the Jetpack blocks in the categories at the top of the manager (Markdown in the Text category, Tiled Gallery in Media for example), and you'll find other Jetpack blocks in their own categories at the bottom of the manager (Earn and Grow):

![Screen Recording 2020-11-12 at 09 00 AM](https://user-images.githubusercontent.com/426388/98911905-a88e7e00-24c5-11eb-9cbe-b129eb523275.gif)

**Comment by snow1776** [comment]
> you'll find some of the Jetpack blocks in the categories at the top of the manager (Markdown in the Text category, Tiled Gallery in Media for example), and you'll find other Jetpack blocks in their own categories at the bottom of the manager (Earn and Grow):

Thanks for such a quick and detailed reply. I see my mistake. 

I have the Stackable blocks installed and they appear in the block library (?) as well as the block manager as multi-coloured icons. I wrongly assumed that since the jetpack icons were green in the block they would also appear green in the block manager. For me, they are black like the built in blocks. Maybe that could change so things were more consistent and it would be easier to deactivate them.

I guess I was also looking for a section called Jetpack in the manager as there is in the library.

Thanks again!

**Comment by jeherve** [comment]
> I wrongly assumed that since the jetpack icons were green in the block library they would also appear green in the block manager. For me, they are black like the built in blocks. Maybe that could change so things were more consistent and it would be easier to deactivate them as a group.

That's a good point. I created #17789 to track this. 

> I guess I was also looking for a section called Jetpack in the manager as there is in the library.

That's a good point. I think it would make for a good improvement to the block manager as a whole; as we all install more and more blocks on our sites, the full list becomes harder and harder to quickly parse and some filtering options would be useful I think.

I commented here to bring that piece of feedback to the contributors working on the block editor:
https://github.com/WordPress/gutenberg/issues/15121

Thanks for your feedback!
