### ISSUE TITLE
Better handle odd connection cases.

### ISSUE THREAD

**Issue by georgestephanis** [Automattic/jetpack#1611]
Currently there are a number of ways that a connection can get out of sync.  Some are more innocuous -- the url on a site changes, and doesn't get updated in the wpcom dataset for the site.  This we can easily detect using `Jetpack::check_identity_crisis()` https://github.com/Automattic/jetpack/blob/3.4-beta1/class.jetpack.php#L4910-L4956

More complicated issues arise when the .org site believes it's connected to wpcom servers -- but wpcom doesn't believe it is.  .org site has the shared secret tokens, but the .com site doesn't!

There's a couple ways that this could come to pass:

- The user disconnected Jetpack from wpcom (deleting remote and local tokens) but then restored the .org site's database from a prior sql dump, restoring the local tokens and making it believe that it's still connected.
- The user duplicated their .org site into a staging site, fully cloning its database, and then disconnected the staging version of the site.  This disconnection would also delete the remote keys, leaving the real .org site believing itself to be connected, but the remote keys would have been wiped, making wpcom think it was no longer connected.

We should make sure we're passing back a sane error message when this is the case, and testing for that error message in the plugin to display a good, understandable error to the user.

**Comment by georgestephanis** [comment]
Should we be deleting the wpcom keys on a disconnect?  Maybe just purge them on a successful reconnect instead?

**Comment by enejb** [comment]
Another way to replicate this error if you disconnect the site in Calypso but .com can't reach the site for some reason. ( I move the site to a different folder on the server ). 

The Jetpack site still thinks it is connected. There is nothing in the UI that tells me that the site doesn't know better. I think doing some sort of check on the Jetpack admin page of the sites status on wp.com would work. And since we sync the data daily I am guessing it would return an error on .com that the site is not connected properly. We could catch that on the Jetpack side and try to inform the user that the connection is broken.

**Comment by kraftbj** [comment]
I think both of George's original use cases was resolved by the IDC fixer via https://github.com/Automattic/jetpack/blob/3.8.0/class.jetpack.php#L6023

If the tokens aren't valid, WP.com returns a 401, which we use to prompt the user to cycle the connection.

@georgestephanis as always, please reopen if this either isn't sufficient.
