### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by Vermakirti2** [Automattic/jetpack#16183]

**Comment by jeherve** [comment]
I'll close this issue as it doesn't contain any information.

If you experience issues with Jetpack, I would recommend that you reach out to our support team here:
https://jetpack.com/contact-support/?rel=support

If you're seeing Fatal errors on your site that you think may be caused by Jetpack, could you enable `WP_DEBUG` on your site as explained [here](https://gist.github.com/jeherve/e6acfc973c07cb500836804e1044d12a), and then send out the details you have about the error to our support team?

Thank you.
