### ISSUE TITLE
Send a Message Block: Broken on some themes on mobile devices

### ISSUE THREAD

**Issue by apeatling** [Automattic/jetpack#16341]
Twenty Twenty seems to be broken on mobile views, the styles for the button are not being applied:

![screenshot_20200629-170429](https://user-images.githubusercontent.com/1464705/86159717-93d5be80-babf-11ea-97a1-7a3b9f043faa.png)

**Comment by apeatling** [comment]
This seems to only be broken on WordPress.com sites, not on Jetpack or local installs.

**Comment by apeatling** [comment]
Oddly things work just fine in the iOS simulator, but not on an actual device.

<img width="372" alt="Screen Shot 2020-06-30 at 3 24 28 PM" src="https://user-images.githubusercontent.com/1464705/86182958-ceeae880-bae5-11ea-8d7d-e8719cad8f6b.png">

**Comment by aaronrobertshaw** [comment]
@apeatling Is this due to it still being a beta block. Accessing the site via the iOS simulator would still be using your proxied connection? 

I added the `jetpack-beta-blocks` sticker to a test blog of mine and refreshing the page on my iPhone now gets the CSS.

<img width="372" alt="Whatsapp button with styles" src="https://user-images.githubusercontent.com/60436221/86196573-db7b4980-bb96-11ea-9c14-d46e8547a3b9.jpeg">

**Comment by apeatling** [comment]
@aaronrobertshaw Yes! That's exactly what it is. Good sleuthing!

**Comment by apeatling** [comment]
Closing this because it will be fixed once this launches fully.
