### ISSUE TITLE
Sharing: ThickBox doesn't close after creating custom button 

### ISSUE THREAD

**Issue by elliott-stocks** [Automattic/jetpack#1645]
A quick fix would be to force a page refresh, which is required at the moment to show the newly created button.

**Comment by dereksmart** [comment]
I've failed to reproduce this.  As you see <a href="https://github.com/Automattic/jetpack/blob/master/modules/sharedaddy/admin-sharing.js#L400">here</a>, we are refreshing the page on a successful submit, and throwing an error otherwise.  

Could you tell me more about your setup?  Any console errors?

**Comment by elliott-stocks** [comment]
Tested on two different sites with the latest stable release and I see the following error in console -

`Uncaught ReferenceError: sharing_js_options is not defined`

Though it looks to be fixed in beta - https://github.com/Automattic/jetpack/commit/783ec263305303bd8c4e26f30cea49bda00878d3

**Comment by dereksmart** [comment]
Ah yup, it's in our <a href="https://github.com/Automattic/jetpack/blob/master/modules/sharedaddy/sharing.js#L1">master branch</a> as well but hasn't made its way into a stable release.  I will make sure it gets in the next one.  Thanks for the report!

**Comment by jeherve** [comment]
@elliott-stocks Could you try to install the Beta and let us know if that commit fixes things for you?

**Comment by elliott-stocks** [comment]
Confirmed as fixed in the beta!
