### ISSUE TITLE
Unable to create file /tmp/jetpack.tmp

### ISSUE THREAD

**Issue by miservice99** [Automattic/jetpack#1658]
Installing Plugin: Jetpack by WordPress.com 3.3.2

Downloading install package from https://downloads.wordpress.org/plugin/jetpack.3.3.2.zip…

Warning: touch(): Unable to create file /tmp/jetpack.tmp because No such file or directory in /home/website/public_html/wp-admin/includes/file.php on line 153

Warning: unlink(/tmp/jetpack.tmp): Operation not permitted in /home/website/public_html/wp-admin/includes/file.php on line 453

Download failed. Could not open handle for fopen() to /tmp/jetpack.tmp

**Comment by jeherve** [comment]
I'm afraid that problem is not linked to Jetpack, but to your WordPress installation settings. Take a look at these posts, they should help you solve these issues:
- http://wordpress.stackexchange.com/a/95278/27574
- https://wordpress.org/support/topic/wp-and-plugin-updates-cant-create-tmp-file?replies=6&view=all
