### ISSUE TITLE
(3P) Social Previews: Add scaffolding for the feature

### ISSUE THREAD

**Issue by marekhrabe** [Automattic/jetpack#16594]
This tasks is to make a scaffolding in the `extensions` directory for our Social Previews feature. Nothing more than a placeholder file where we will later add code and get our dependencies ready. 

TODO:
- [x] install `@automattic/social-previews` into Jetpack
- [x] find a place for social previews feature and create a scaffolding
- [x] mark extension as beta

Requires https://github.com/Automattic/wp-calypso/pull/44385 to be merged and published

**Comment by jeherve** [comment]
> find a place for social previews feature and create a scaffolding

Since the feature will not rely on the SEO Tools module, I would recommend relying on [our existing block scaffolding](https://github.com/Automattic/jetpack/blob/5a4ec0da4f32874708b4f7014690aa458ceca883/extensions/README.md#L70) to have this feature be like another block, relying on `JetpackPluginSidebar` a bit like Shortlinks do?
https://github.com/Automattic/jetpack/blob/4c63a49fc0139c3296248e09ee69dedb537e024f/extensions/blocks/shortlinks/index.js#L31-L35

**Comment by marekhrabe** [comment]
Awesome, let's follow that path then
