### ISSUE TITLE
Sharing: jetpack_static_url staticize_subdomain serve non-existing loading.gif on SSL sites

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1663]
On a site using SSL, you'll run into the following issue when using the Email sharing button:

`Failed to load resource: the server responded with a status of 404 (Not Found) https://s-ssl.wordpress.com/wp-content/plugins/jetpack/modules/sharedaddy/images/loading.gif`

https://github.com/Automattic/jetpack/blob/febfeece3968559062bbe0fd9e9465c128debdbf/modules/sharedaddy/sharing-sources.php#L329

Reported here:
https://twitter.com/Josh412/status/568844340853747713

**Comment by aheckler** [comment]
This should just be loading from the user's site, correct? Not sure what that filter does, but the image is present in the plugin itself.

**Comment by jeherve** [comment]
> This should just be loading from the user's site, correct?

I'd think so, yeah.

**Comment by aheckler** [comment]
The problem here stems from `staticize_subdomain()`:

https://github.com/Automattic/jetpack/blob/3.3.2/class.jetpack.php#L4422-4437

This regex `/.?(?:wordpress|wp)\.com$/` will match any domain that ends in "wp":

http://regexr.com/3agd1

Thus the issue with this user's site: `calderawp.com` I don't have an SSL handy for testing, but I would bet this issue only affects SSL domains that end with `wp.com`.

After some regex experimentation, I believe a better pattern to match might be this:

`\b(?:wordpress|wp)\.com$`

You can see what it matches here:

http://regexr.com/3agd4

That said, regex is hard and we could probably use some sort of `in_array` check instead if we can extract only the TLD from `$host = parse_url( $url, PHP_URL_HOST );`.
