### ISSUE TITLE
How to Fix it?

### ISSUE THREAD

**Issue by anmol257** [Automattic/jetpack#16776]
The following file of Jetpack plugin is affecting the site page speed - 
![image](https://user-images.githubusercontent.com/45257813/89720655-2ee08300-d9f2-11ea-9381-9d923e0bb1e5.png)
Kindly guide me
(PS: I'm using Pique theme)

Thnks in advance

**Comment by jeherve** [comment]
This font is used by your theme to display icons in different places around your site. If you'd rather not use the font, I would recommend picking a different theme.

**Comment by anmol257** [comment]
@jeherve 
Kindly refer to the updated title.
The following is the latest page test result
![image](https://user-images.githubusercontent.com/45257813/89765306-aeb23e80-db13-11ea-802b-7d2c9df9e71b.png)

The current theme is perfect for my website so it would be great if you could assist me in it. (I'm scoring 97-99 for desktop but for mobile, it is lagging because of this issue at 88-90 approx)
![image](https://user-images.githubusercontent.com/45257813/89765586-3bf59300-db14-11ea-9af7-313a9e56122b.png)
![image](https://user-images.githubusercontent.com/45257813/89765413-e5885480-db13-11ea-8e58-4a1b37493d73.png)

Thanks
Anmol

**Comment by jeherve** [comment]
Since the Genericons are controlled by your theme, there is not much I can do to help you I'm afraid. If you'd rather not use Genericons, you can switch to a different theme or set up a child theme and dequeue the Genericons from your site. You'll find them enqueued in your theme's `functions.php` file.

Looking at your site, I can see the font being used to display the social media icons in the footer:
![image](https://user-images.githubusercontent.com/426388/89766576-a993c600-daf8-11ea-93a8-760b87dcccad.png)

**Comment by anmol257** [comment]
Ohh
Social Media icons are very critical for my site.
I definitely need em.
