### ISSUE TITLE
(3P) Social Previews: Set upgrade button link location

### ISSUE THREAD

**Issue by marekhrabe** [Automattic/jetpack#16781]
We need to figure out where to link the user when they click the upgrade button. Button introduced in #16744

Do we need to use the redirect library, as other links in Jetpack dashboard do? cc: @jeherve

**Comment by jeherve** [comment]
> Do we need to use the redirect library, as other links in Jetpack dashboard do?

We do not have the necessary npm lib yet, so that won't be possible:
- https://github.com/Automattic/jetpack/issues/15403
- https://github.com/Automattic/wp-calypso/pull/41497

Ideally you'd be able to leverage the existing `UpgradeNudge` component and , or extract the link building part of it and build something new for inside your modal?
