### ISSUE TITLE
(0P) Social Previews: Mark as non-beta

### ISSUE THREAD

**Issue by marekhrabe** [Automattic/jetpack#16783]
This is an effective feature launch so let's make sure all other issues are addressed first. 

Do we wait for Jetpack release on Sep 1st or launch wpcom sooner? Do we first mark it as experimental or go straight to production? cc: @jeherve

**Comment by jeherve** [comment]
We usually switch to production on Jetpack's `master` before the code freeze, but wait until release day, a couple of hours before the release, to commit the matching WordPress.com Fusion-generated diff. 

This way no one will start using the feature on WordPress.com, and then move to Atomic and lose access to the feature because it's not yet available there.

> Do we first mark it as experimental or go straight to production?

We can go straight to production.
