### ISSUE TITLE
Photon/Image Accelerator breaks animated gifs 

### ISSUE THREAD

**Issue by wmodes** [Automattic/jetpack#16798]
Related to issue [4528](https://github.com/Automattic/jetpack/issues/4528) which was reported fixed.

#### Steps to reproduce the issue

1. Look at [animated gif hosted directly on site](https://unavoidabledisaster.com/wp-content/uploads/2020/08/TECHNICS-SL-1200-anim-10.gif?fit=450%2C291&ssl=1).
2. Compare to [same resized animated gif hosted on photon](https://i2.wp.com/unavoidabledisaster.com/wp-content/uploads/2020/08/TECHNICS-SL-1200-anim-10.gif?fit=450%2C291&ssl=1).

#### What I expected
I expect the photon hosted image to perform similarly.

#### What happened instead
Notice that the last few frames of the animation are partially blanked.

This was an animation created in photoshop. The same thing happens at different sizes and whether I optimize or flatten the frames or not. The original animated gif looks correct in every other way of viewing it I can think of, browser, preview, etc. It is only when it is resized by photon that it breaks.

Please note that if you [view the UNresized animated gif on photon](https://i2.wp.com/unavoidabledisaster.com/wp-content/uploads/2020/08/TECHNICS-SL-1200-anim-10.gif) it does not break.

**Comment by jeherve** [comment]
Thanks for the report. This issue is currently tracked here:
https://code.trac.wordpress.org/ticket/92

It seems to impact some animated GIFs, but not all of them. Do you think you could comment on the issue with more details about how you created that GIF? That may help us narrow down things and reproduce.

If you do not have a WordPress.org account and cannot comment there, do not hesitate to comment here and I'll copy your comment into the original issue. 

Thank you!
