### ISSUE TITLE
Donations: Stripe modal does not display currect currency after changing a block's currency.

### ISSUE THREAD

**Issue by kwight** [Automattic/jetpack#16977]
If, I change an existing block's currency and leave the values as the defaults, the updated front-end view will display the old currency in the Stripe modal (in the example below, a block in Euro was changed to a block in Yen).

<img width="1444" alt="Screen Shot 2020-08-25 at 12 53 45 PM" src="https://user-images.githubusercontent.com/349751/91222094-8c075480-e6d3-11ea-9a3b-bb06054691ee.png">

Changing the values to anything else and updating the post again will result in the correct currency displayed from then on.

**Comment by mmtr** [comment]
I cannot reproduce this one @kwight. I made sure to leave the block with the default values after changing the currency, but the payment dialog displays the new currency:

![Aug-27-2020 12-36-42](https://user-images.githubusercontent.com/1233880/91432486-1087dd80-e862-11ea-9821-8c36843639fd.gif)

@blackjackkent recently fixed a similar issue in https://github.com/Automattic/jetpack/pull/16844, so maybe the environment you used for testing has not been updated so the fix is missing?

**Comment by kwight** [comment]
Aaaaand I can't replicate today. We'll blame the singularity.
