### ISSUE TITLE
Why is 'My Tweet' in twitter timeline widget

### ISSUE THREAD

**Issue by FellowTuts** [Automattic/jetpack#1698]
I don't understand what is purpose behind placing 'My Tweets' in line number 93 

`echo '>' . esc_html__( 'My Tweets', 'jetpack' ) . '</a>';`

in file <blockquote>modules/widgets/twitter-timeline.php</blockquote> 
Won't it be better to ask for username inside widget form in dashboard and update 'My Tweets' with user handler (Tweets by @User) accordingly.

**Comment by jeherve** [comment]
The Twitter Timeline widget allows you to create timelines that are not linked to a specific Twitter user. You can for example create a timeline that will list tweets including a hasthtag:

![screen shot 2015-03-02 at 2 03 14 pm](https://cloud.githubusercontent.com/assets/426388/6441130/f41a5d4e-c0e4-11e4-9f32-0d0e659ce1d1.png)

It could also be used to display a list:

![screen shot 2015-03-02 at 2 04 09 pm](https://cloud.githubusercontent.com/assets/426388/6441133/089562b4-c0e5-11e4-820e-f7410f312618.png)

That's why we can't require a Twitter username in the widget settings.

No worries though, "My Tweets" is only a placeholder that disappears as soon as the timeline is fully loaded. Your readers consequently won't see it, unless Javascript is disabled in their browser.

**Comment by FellowTuts** [comment]
The Embedding with a shortcode `[twitter-timeline id=1234 username=jeherve]` offered by Jetpack gives users the facility to provide username while embedding shortcode in a page or post and widget appears as 'Tweets by @jeherve' 

So there should be no different in appearance since both are used for same purpose.

Furthermore as you said:
> The Twitter Timeline widget allows you to create timelines that are not linked to a specific Twitter user. 

Then as tweets are not related to a particular user so the word 'My' shouldn't be at least there.

I agree that 'My Tweets' is just a placeholder still it's visible to visitors for a countable amount of time.

So just modifying my previous post, I vote to let user choose a custom text to appear until timeline appears.

**Comment by jeherve** [comment]
> I vote to let user choose a custom text to appear until timeline appears.

I just submitted #1710 to add a new filter, `jetpack_twitter_timeline_placeholder`, that will allow you to customize that title with something like this:

```php
function jeherve_custom_placeholder() {
        return 'Tweets by @jeherve';
}
add_filter( 'jetpack_twitter_timeline_placeholder', 'jeherve_custom_placeholder' );
```

**Comment by FellowTuts** [comment]
Thank You.
