### ISSUE TITLE
Google Analytics - Honor Do not Track

### ISSUE THREAD

**Issue by rmuthukrishnan** [Automattic/jetpack#17176]
#### Is your feature request related to a problem? Please describe.
Just like Wordpress.com stats, we would like to have honoring of Do not Track for Google Analytics. 

#### Describe the solution you'd like

Similar to Wordpress.com Stats

#### Describe alternatives you've considered

Google analytics has an option for user opt-out: https://developers.google.com/analytics/devguides/collection/analyticsjs/user-opt-out

**Comment by jeherve** [comment]
For reference, here is the approach we took for the Stats module: #8075 

We could rely on a filter as well for Google Analytics. That filter could could tie in to an option that would be defined in `modules/google-analytics/classes/wp-google-analytics-options.php`. That option would then be used in both legacy and universal analytics. Here is an example:
https://github.com/Automattic/jetpack/blob/cdff225c5b5159c23a51bd0e6c63e2c486b0b98b/modules/google-analytics/classes/wp-google-analytics-legacy.php#L131-L143
https://github.com/Automattic/jetpack/blob/cdff225c5b5159c23a51bd0e6c63e2c486b0b98b/modules/google-analytics/classes/wp-google-analytics-universal.php#L88-L94

**Comment by chrisbliss18** [comment]
r250559-wpcom

**Comment by chrisbliss18** [comment]
An update with a rudimentary implementation of this feature is scheduled to go out in the next release (expected version 11.3). You can find the details for the implementation in PR #25423.

The implementation does not have a user interface. To enable honoring the DNT header, you must manually set the `jetpack_honor_dnt_header_for_wga` filter to `true`. This should be done in a custom plugin rather than modifying an existing plugin.
