### ISSUE TITLE
Premium blocks: Upgrade button is broken in Safari.

### ISSUE THREAD

**Issue by kwight** [Automattic/jetpack#17181]
_Reported by @donlair in 227-gh-dotcom-manage_

### Expected behavior
Clicking the Upgrade button on premium blocks should redirect people to the checkout page.

### Actual behavior
In Safari, clicking the upgrade button hides the upgrade banner without loading the checkout page

### To Reproduce
1. Use Safari, go to WPcom and select a Free plan user, then go to the Gutenberg page editor.
2. Add a premium block, such as Payments
3. Click the upgrade button
4. See that the upgrade banner disappears without redirecting the user.

**Comment by blackjackkent** [comment]
Tested this in safari on my machine and am not able to reproduce it. @donlair / @kwight can you confirm when you have a chance?

![upgrade-banner](https://user-images.githubusercontent.com/13437011/93639256-539b2380-f9be-11ea-8bed-73d711ce79e0.gif)

**Comment by sixhours** [comment]
Ahh, I'm seeing two upgrade calls to action; it's the black one with the pink button that isn't working as expected @blackjackkent: 

<img width="845" alt="Screen Shot 2020-09-18 at 4 04 57 PM" src="https://user-images.githubusercontent.com/2124984/93640694-007a9e00-f9c9-11ea-9235-d592a8e1b88f.png">

**Comment by blackjackkent** [comment]
Aha, thanks @sixhours . I see it now; investigating!

**Comment by blackjackkent** [comment]
This issue appears to have something to do with event bubbling on the button click event being handled differently between Safari and (for instance) Chrome. The banner isn't disappearing so much as it is being hidden in the normal way that it otherwise would when clicking away from the block, and when it is hidden, the event doesn't seem to be making its way to the button to actually perform the link navigation.

Still looking into the best solution.

**Comment by mmtr** [comment]
I wonder if this check is the culprit:

https://github.com/Automattic/jetpack/blob/bfdc141d859118c099450f3673682db49fd83021/extensions/shared/use-upgrade-flow/index.js#L48

If I go to wordpress.com/block-editor and run `window.top` in the browser console I get different outputs depending on the browser (it's important to select the `post-new.php` context, since the check above runs in a JS that is loaded in an iframe).
- Chrome:
<img width="707" alt="Screen Shot 2020-09-21 at 16 26 23" src="https://user-images.githubusercontent.com/1233880/93779513-63697080-fc27-11ea-87d8-656ead16e167.png">

- Safari:
<img width="696" alt="Screen Shot 2020-09-21 at 16 26 34" src="https://user-images.githubusercontent.com/1233880/93779533-68c6bb00-fc27-11ea-8459-fbc7bb67102b.png">

As you can see, `window.top` returns an empty object in Safari.

**Comment by blackjackkent** [comment]
I've confirmed that the issue is not related to the `window.top` reference (although thank you, @mmtr , for the suggestion -- it was a good idea). Adding a console.log to that `if` statement does nothing, and the button *does* work if the logic to remove the banner is removed:

```js
const UpgradePlanBanner = ( {
	...
} ) => {
	...
	// if ( ! visible ) {
	// 	return null;
	// }
```

This seems to indicate to me that the problem is due to a race condition or oddity in event bubbling wherein the banner is removed from the DOM before the click handler on the button can be activated.

This seems to beg the question - does that banner have to be hidden? It's always going to be right next to the block it refers to anyway; if we just leave it visible all the time it would alleviate this issue more rapidly (not to mention being a more obvious call to action for upgrades).

**Comment by kwight** [comment]
> does that banner have to be hidden?

Hm, which hide do you mean? It's not hidden on initial render, only after clicking out of the block, from what I can tell (in which case, the button should work if clicked immediately).

Oh, erm, uh – now it works for me. Which a race condition could explain. 🙃  If you can get a PR consistently working with that direction, let's give it a shot.

**Comment by kwight** [comment]
Oh jeez – is it the `savePost` call before it? If there's nothing to save, the promise doesn't resolve properly to trigger the redirect?

**Comment by blackjackkent** [comment]
I don't think so, if I'm understanding you right -- `goToCheckoutPage` isn't being called at all in Safari.

**Comment by blackjackkent** [comment]
@kwight , @krymson24 , and I put our heads together on this for a little this afternoon and it seems (cautiously) as if this might be manifesting only in dev. We've put out a ping to support folks to see if it's manifesting among actual users which may affect our approaching going forward with this issue.

**Comment by krymson24** [comment]
I also noted that this behavior can be reproduced for already-existing premium blocks. See GIF.
![2020-09-22 00 30 48](https://user-images.githubusercontent.com/66652282/93844383-fa0b5100-fc6a-11ea-90b3-e95cfddddf57.gif)

**Comment by kwight** [comment]
#17233 , which fixes this issue, will be part of the Jetpack 9.0 release, scheduled for October 6, 2020.

**Comment by mmtr** [comment]
I deployed the changes to WP.com in r214163-wpcom, so the issue shouldn't be replicable anymore (upsell nudges for blocks are disabled in Jetpack, so v9.0 won't bring any noticeable change to Jetpack users).
