### ISSUE TITLE
Calendly Block: Link style does not work when used inside another block

### ISSUE THREAD

**Issue by sstabrizi** [Automattic/jetpack#17425]
When adding the Calendly block inside of a Cover block and using the Link style the button does not work properly. When a user clicks the button on the published page they see the Cover block image in a popup window instead of the Calendly page added in the settings.

#### Steps to reproduce the issue

1. Create a new page or post.
2. Add a Cover block.
3. Add Calendly block inside the Cover block.
4. Add a valid Calendly web address and click Embed.
5. Choose the "Link" style from the block Style settings.
6. Publish the page or post.
7. Click the Calendly button and see that it does not work correctly.

#### What I expected

When Calendly is used outside of a Cover block this is how it looks: 

![Markup 2020-10-08 at 17 19 18](https://user-images.githubusercontent.com/25855381/95522832-6d5ed380-098a-11eb-844c-8ba6c2067a20.png)

This is what should happen: 

![Markup 2020-10-08 at 17 20 15](https://user-images.githubusercontent.com/25855381/95523213-4bb21c00-098b-11eb-9e00-3dc0b6d6d030.png)

#### What happened instead

Instead of showing the scheduling page, as shown above, the Cover block background image is shown instead:

![Annotation on 2020-10-08 at 17-23-42 (1)](https://user-images.githubusercontent.com/25855381/95523127-1279ac00-098b-11eb-9d27-ec2bdbd59a06.png)

**Comment by Matthewnie** [comment]
I am having a similar issue when trying to use the link style inside a column. 

**Steps to reproduce the issue**

1. Create a new page or post.
2. Add a Columns block.
3. Add Calendly block inside the column block.
4. Add a valid Calendly web address and click Embed.
5. Choose the "Link" style from the block Style settings.
6. Publish the page or post.
7. Click the Calendly button and see that it does not work correctly. (The HREF for the button is not getting populated with the Calendly URL instead it is saving as "#" so the javascript is trying to load the current page within the popup.)

**Expected HTML (this does work properly outside of the columns block)**
`<a class="wp-block-button__link" style="" data-id-attr="calendly-block-4" id="calendly-block-4" href="https://calendly.com/username?hide_event_type_details=0&amp;background_color=ffffff&amp;text_color=4D5055&amp;primary_color=00A2FF" target="_blank" role="button" rel="noopener noreferrer">Schedule time with me</a>`

**Actual HTML (when inside a columns block)**
`<a class="wp-block-button__link" style="" data-id-attr="calendly-block-3" id="calendly-block-3" href="#" target="_blank" role="button" rel="noopener noreferrer">Schedule time with me</a>`

**Comment by stumax** [comment]
This has also been raised in - 

3446596-zd

**Comment by katiebethbrown** [comment]
Another report in 26633754-hc.

Moving the block out of the columns block it was inside resolved the issue.

**Comment by annbingle** [comment]
Another user reported the same issue here in 26874854-hc.

Had them use the inline embed for now as it works.

**Comment by brookewp** [comment]
Another one 27098226-hc
This was in the columns block

**Comment by MaxPhilip** [comment]
Another one with columns block: 3780746-ZD

**Comment by marcuswisecaesar** [comment]
Cover Block: 3843036-ZD

Pulling the Calendly Block out of the Cover Block resolved the issue.

**Comment by ramonjd** [comment]
There are a couple of issues here I think:

1. For the button text color, the attribute name of `textColor` isn't passed through to the child Button block. E.g., `passthroughAttributes: { url: 'url', textColor: 'textColor' },` I think it should happen [here](https://github.com/Automattic/jetpack/blob/ef9c697baa076d31ee829e6c46ac31c6bac3c9c4/projects/plugins/jetpack/extensions/blocks/calendly/edit.js#L192).
2. The url isn't being correctly applied to the button when the Calendly block is nested. It's something to do with the way we [pass down attributes and check the block's parent](https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/extensions/blocks/button/use-passthrough-attributes.js#L20). It's possible that, if the Calendly block is inside a column block, we're looking too far up and checking to see if the column block has a `url` attribute and not the Calendly block. Will keep checking.

The fix for 1 might depends on the fix for 2.
