### ISSUE TITLE
Payment Blocks: Blocks are not available in the WordPress.com widgets block screen.

### ISSUE THREAD

**Issue by kwight** [Automattic/jetpack#17481]
With Gutenberg 9.1, we're able to start testing blocks on the WordPress.com admin widgets page (with the appropriate test flags). However, our payments blocks (Payments, Donations) are not accessible in the inserters.

Once that is solved, we can follow up with individual issues for verifying each block. This should all be done by October 16th. See the internal call for testing.

**Comment by kwight** [comment]
Hm, looks like Pay With PayPal is available, just not the others.

**Comment by jeherve** [comment]
> looks like Pay With PayPal is available, just not the others.

Could that be because it's registered as a regular old widget in addition to being a block?
https://github.com/Automattic/jetpack/blob/4e8c7e73cb4e6660132deb3698d972fddd32af45/modules/widgets/simple-payments.php#L556

**Comment by mmtr** [comment]
> Could that be because it's registered as a regular old widget in addition to being a block?
> https://github.com/Automattic/jetpack/blob/4e8c7e73cb4e6660132deb3698d972fddd32af45/modules/widgets/simple-payments.php#L556

Yes, that's the reason. I don't think we can register 3rd party blocks as widgets yet, since the Gutenberg widgets page doesn't offer any way of registering additional blocks at the moment.

The post block editor allows to register 3rd party blocks by [hooking into `enqueue_block_editor_assets`](https://core.trac.wordpress.org/browser/trunk/src/wp-admin/edit-form-blocks.php?rev=49040#L395) and enqueuing our scripts there.

But there isn't a similar hook in the widgets block editor, so only the [core `wp-edit-widgets` script is enqueued](https://github.com/WordPress/gutenberg/blob/0bf25d76e09ec9e595b215d56c240ab857991b37/lib/widgets-page.php#L121) (which only registers [the Core blocks and the legacy widgets](https://github.com/WordPress/gutenberg/blob/0bf25d76e09ec9e595b215d56c240ab857991b37/lib/widgets-page.php#L121)).

**Comment by kwight** [comment]
Sorry yes, this was basically me misreading what we were trying to test – closing! 😅

**Comment by draganescu** [comment]
3rd party block work as normal, without any further changes needed. This was added by:

https://github.com/WordPress/gutenberg/pull/25826
https://core.trac.wordpress.org/ticket/51330

All registered blocks should load and work in the new widgets editor. Nevertheless, there is no concept of "registering 3rd party blocks as widgets" - the "as widgets" part - but what we do have is:

1. register a block which replaces a widget
2. hide the replaced-by-block-widget by using the `widgets_to_exclude_from_legacy_widget_block` hook

This way, the block-that-replaces-a-widget is by default usable in any block editor (including post) and:

1. If the user has the block based widgets editor enabled they can use the new block in sidebars
2. If the user doesn't have the block based widgets editor they can use the old widget in sidebars, and the new block in other places.
