### ISSUE TITLE
Photon changes colors when resizing images that include color profile metadata

### ISSUE THREAD

**Issue by szczys** [Automattic/jetpack#17541]
#### Steps to reproduce the issue

1. Upload an image with color profile metadata ([example file](https://hackaday.com/wp-content/uploads/2020/10/Lewis-Latimer-filament-patent-rethemed.png)) to a site using Jetpack Photon
2. Use a URL with query string to view a different size of the file ([example file at 966px width](https://hackaday.com/wp-content/uploads/2020/10/Lewis-Latimer-filament-patent-rethemed.png?resize=966,1536))
3. In this example, background color of original file is #1a1a1a but has changed to #181818 in resized file

#### What I expected
Original image has the same background color as our site CSS, resized version of this file should also have the same color

#### What happened instead
Background color of the file has changed and now stands out from the page background

#### Workaround
When saving photos in Gimp image editor (v2.10.*) , de-select the "Save Color Profile" box when saving

**Screenshot showing background color standing out on a resized image**
![image](https://user-images.githubusercontent.com/367685/96604165-6739f280-12ba-11eb-9231-ff83f6e9010f.png)

**Comment by jeherve** [comment]
Thanks for the report. I think you may be running into the same issue that is currently logged here:
https://code.trac.wordpress.org/ticket/94

I'll consequently close this issue as duplicate.

On your end, since your site uses the VIP Go Hosting solution it uses a custom implementation of the image CDN offered in Jetpack. I would consequently recommend that you contact VIP support about this, they may be in a better position to help.

**Comment by gift610** [comment]
![Uploading IMG_20200923_164801_354.jpg…]()

**Comment by gift610** [comment]
#17760
