### ISSUE TITLE
Star rating module - generate stars on Google search

### ISSUE THREAD

**Issue by klinge** [Automattic/jetpack#17579]
#### Is your feature request related to a problem? Please describe.
I have a site that does software reviews of guitar amp simulator software (www.honestampsimreviews.com). I've been using the star rating block since it was released. I had hoped that using the star rating block would result in our reviews being shown on Google search with the associated star rating. But it does not. Adding this would be a great feature. 

Also looking at the original issue #14139 where rich content tags was introduced the goal of adding schema.org markup was just for the purpose of Google and likes to be able to pick it up. In that respect this is more of a bug than an enhancement.. 

#### Describe the solution you'd like
As of now the star rating module includes the following schema.org tags as microdata: 
- type = "Rating"
- worstRating
- bestRating
- ratingValue

Google only shows star ratings for certain product types, listed in this post: 
https://developers.google.com/search/docs/data-types/review-snippet

This simplest possible solution would be to add a schema.org/Product tag to the data on the page. 

So my suggestion is to include the following schema.org tags in the output from the star rating block (example below in ld-json for simplicity):
```
<script type="application/ld+json">
{
	"@context":"http:\/\/schema.org\/",
	"@type":"Product",
	"name":"<post title OR set via property in right side property panel",
  	"image":"<url of post featured image>",
	"review":
	{
		"@type":"Review",
		"reviewRating":
		{
			"@type":"Rating",
			"bestRating":"<total number of stars>",
			"worstRating":"<lowest number of stars>",
			"ratingValue":"<selected number of stars>"
		},
		"author":
		{
			"@type":"Person","name":"<post author>"
		},
		"datePublished":"<date of post on format YYYY-MM-DD>"
	}
}</script>
```
This code is validated with the Google rich-text verifier and should contain all tags to generate star ratings on google search. 
https://search.google.com/test/rich-results

#### Describe alternatives you've considered
- Schema.org tags could be added kept as microdata or changed to ld+json whichever is most convenient
- An alternative to always setting "@type":"Product" would be to have a dropdown list in the right side property panel to choose between different types of products that can be reviewed. However this introduces more complexity since some of the other types have more required attributes. For example if you set type to "SoftwareApplication" you also have to set the properties "applicationCategory" and "operatingSystem". This could easily get too complicated. 

#### Additional context
-

**Comment by jeherve** [comment]
As you discovered with the #14139 issue, we've added schema.org metadata to the star rating markup. It relies on the `http://schema.org/Rating` type and ratings are set depending on the amount of stars you add to the page.

Here is an example output from the Rich Snippets tool when on a page with a Star Rating block:
- https://honestampsimreviews.com/2020/07/03/brainworx-rockergain/
- https://search.google.com/test/rich-results?id=CYcorDi3SNSbNvN0n0TkUQ

![image](https://user-images.githubusercontent.com/426388/96873537-5e415080-1475-11eb-9461-bad70fe00579.png)

The stars don't show up in search results though:
![image](https://user-images.githubusercontent.com/426388/96873758-a2ccec00-1475-11eb-8bd4-8c834cee6af7.png)

As you discovered, this is because Google would expect to see content type schema.org metadata as well. In your case, a "Product" type would probably be the best fit.

This is not something we can decide or create for you with the Star Rating block, though. As you can imagine, other sites may need different product types.

Instead, I would recommend that you use a different plugin to add the blocks you need on your site. [This plugin](https://wordpress.org/plugins/schema-google-blocks/), for example, seems to add a product type block that you could use alongside Jetpack's Star Rating block.

I hope this clarifies things a bit.

**Comment by klinge** [comment]
I see your point. But this is not a problem that is unique to my site. Since there are tags missing star ratings won't be shown for any users using the star rating block. Doesn't this sort of defeat the purpose of #14139? 

If setting type=Product is too limited to fit everyone's needs wouldn't having an option of setting type as a property of the block sort of fix that issue?

**Comment by jeherve** [comment]
> Since there are tags missing star ratings won't be shown for any users using the star rating block. Doesn't this sort of defeat the purpose of #14139?

I'd say the Star Rating block and its Schema.org implementation is really just one piece of the puzzle. 

- If you aim to display stars in search result pages, it is most useful when used alongside other blocks that add more Schema.org metadata.
- Similarly, using a Product Schema block would be most useful when used alongside a rating block if your aim is to display star ratings in search result pages.

Both blocks can be used separately, and when used together they have an additional benefit.

> wouldn't having an option of setting type as a property of the block sort of fix that issue?

Right, that is what the plugin I mentioned above seems to do, alongside organizing the markup to fit the needs of the schema.org requirements.

The Star Rating block cannot do that though, since it only displays stars; it doesn't display content. 

We could expand the block and add extra fields to add information for different content types, but I think that kind of information is a better fit for a block that will also display information about that content on the site.

**Comment by klinge** [comment]
> Both blocks can be used separately, and when used together they have an additional benefit.

My understanding of the schema is that on the top level you have a "Thing" (that is of type Product, CreativeWork or a number of other categories) that has one or many "Review" that each has a "Rating". Putting this together piecemeal with several plugins could work - but I think it would need to be tested before you could be certain. I'll look into that and report the results I get. 

> We could expand the block and add extra fields to add information for different content types, but I think that kind of information is a better fit for a block that will also display information about that content on the site.

This is more on a personal level, but we're on a wordpress plan that don't allow running plugins. Upgrading the plan would increase cost almost 4 times. So because of this I was hoping to see native Wordpress support for getting star ratings on search engines. 

Thinking about this - a more general question is if and how Wordpress wants to support rich content and schema.org markup. Has there been any discussion on that?

**Comment by jeherve** [comment]
> Putting this together piecemeal with several plugins could work - but I think it would need to be tested before you could be certain. I'll look into that and report the results I get.

Right. That's where blocks and block groups can be powerful.

> This is more on a personal level, but we're on a wordpress.com plan that don't allow running plugins. Upgrading the plan would increase cost almost 4 times. So because of this I was hoping to see native Wordpress support for getting star ratings on search engines.

That makes sense.

> a more general question is if and how Wordpress wants to support rich content and schema.org markup. Has there been any discussion on that?

That's not something we've discussed in the past, and I cannot say that we've had many requests for such a feature, but that doesn't mean we shouldn't consider it! I'll keep this in mind and will open an issue if this comes up again in the future.
