### ISSUE TITLE
Introduce Support for Mailerlite Embedded Forms

### ISSUE THREAD

**Issue by donalirl** [Automattic/jetpack#17721]
#### Is your feature request related to a problem? Please describe.
We introduced a Mailerlite (https://www.mailerlite.com/) popup integration in https://github.com/Automattic/jetpack/pull/15878 that is becoming popular. However, for people who wish to use Mailerlite to manage their email list, a popup is the only integration we offer. Many site owners do not like popups, and wish to use a static embedded form instead.

#### Describe the solution you'd like
I'd like to see us support a Mailerlite form integration, via a block or whitelisting the embed code. Mailerlite provides Javascript and HTML options, which are not supported on WordPress.com sites.

As a side note, Mailerlite have a plugin that includes both a widget and block: https://wordpress.org/plugins/official-mailerlite-sign-up-forms/

#### Describe alternatives you've considered
Mailerlite provides a third option: a URL for the form. This can be added to the site but it is not an embed. It takes visitors off of the user's site to Mailerlite's site to subscribe. Embeds directly on the site are more attractive to site owners.

#### Additional context
#user-report #25414796-hc

cc @artpi

**Comment by artpi** [comment]
YES PLEASE!

There is another solution that will be way easier. The same script that I introduced in #15878 will also load the inline form.

Here is a screenshot from my ML account:

![Zrzut ekranu 2020-11-5 o 11 38 57](https://user-images.githubusercontent.com/3775068/98230539-9196db80-1f5b-11eb-9b2c-b65874a55892.png)


If I am thinking correct, we can introduce a Gutenber block that loads the script introduced in #15878

And generates the code:

```
<div class="ml-form-embed"
  data-account="1726876:o6h6c1w0c9"
  data-form="2302393:s7q2f2">
</div>
```

**Comment by jeherve** [comment]
Since the Mailerlite popup was added to the Editing Toolkit plugin and not to Jetpack, any changes to the existing integration may be a better fit to that plugin (currently developed in the wp-calypso repo). I'll consequently close this issue since that may not be the best fit for the Jetpack repo right now (see p1HpG7-9kd-p2 for more discussion around this).

That said, we do have an existing form block in Jetpack. That block also happens to includes a Newsletter sign-up form variation:

![image](https://user-images.githubusercontent.com/426388/98232720-4d590a80-1f5e-11eb-8fe1-fca42a6af92c.png)

That variation allows you to insert a block where one is able to collect emails, names, and consent to subscribe to a newsletter.

![image](https://user-images.githubusercontent.com/426388/98232874-80030300-1f5e-11eb-9cff-86820664d10a.png)

One could use this block to collect email addresses from visitors.

The question then becomes how you automatically add those collected email addresses to your Mailerlite list. If you can use an external, official Mailerlite plugin, that plugin can take care of that for you by developing an integration that will pull that data from the saved feedback forms.
If you cannot use any additional plugin, things are obviously more complicated; this is why the newsletter sign-up form variation is currently not available on WordPress.com simple sites.

As it stands, I would recommend the following:

- If an integration can be developed from within the Editing Toolkit plugin, we could then enable that form variation on WordPress.com Simple sites.
- If not, maybe we could reach out to the Mailerlite team and see if they'd be interested in developing such an integration in their official plugin.
