### ISSUE TITLE
List Jetpack Blocks after Core blocks when searching blocks in "Add Block" sidebar or Slash Inserter popup menu

### ISSUE THREAD

**Issue by mrwweb** [Automattic/jetpack#17732]
#### Is your feature request related to a problem? Please describe.
When searching for blocks using the "Add Block" sidebar or slash inserter, Jetpack blocks are listed before core blocks.

This is extremely annoying for common blocks like "Image". It's not that the Jetpack blocks aren't useful, but they are so clearly _not_ the most likely block needed for a search like that. I've personally found that this behavior is making me wish I just didn't have Jetpack blocks at all.

#### Describe the solution you'd like
List Jetpack blocks second in the slash inserter and "Add Block" sidebar with a possible exception for exact matches on the block name. (I imagine that the Jetpack block would be the only block for exact name matches in most cases.)

#### Additional context
Slash Inserter search for "image":
![image](https://user-images.githubusercontent.com/1238696/98401266-41328300-201a-11eb-820c-9292fc50e003.png)

Add Block sidebar search for "image":
![image](https://user-images.githubusercontent.com/1238696/98401341-5effe800-201a-11eb-93ba-0346eeb7b4fc.png)

Interestingly, the contextual add block button search for "image" does not display this behavior:
![image](https://user-images.githubusercontent.com/1238696/98401302-4f809f00-201a-11eb-9576-6636b301f0e0.png)

**Comment by jeherve** [comment]
Yeah, I agree this is frustrating. Unfortunately, that's not something we can fix from within the Jetpack plugin. We do not control the order of the blocks in the inserter. This is done by the block editor, and right now it seems to place blocks created by third-parties above core blocks for some reason. This is true with any plugin. I'm not sure if this is done on purpose, or if that is a bug.

I see it's been reported in the Gutenberg repo here:
https://github.com/WordPress/gutenberg/issues/26651

I'll add a comment about your report to that issue. I would recommend subscribing to that issue to see where things go from here.

I'll be closing this issue, since that's not something we can fix in Jetpack.
