### ISSUE TITLE
Open Graph Tags: single posts don't show tags when using Timber

### ISSUE THREAD

**Issue by vvvctr** [Automattic/jetpack#17753]
After [this update](https://github.com/Automattic/jetpack/commit/d6dfd9c34b18c5e378b9ed2a2674bc2212b289df?branch=d6dfd9c34b18c5e378b9ed2a2674bc2212b289df&diff=unified#diff-eecd73fcf91b3d96b843061abb7caa6d473c7e385562c056b24a5494a56687e4R119), **Open Graph Tags** are not showing in single posts of any post type when using the [plugin Timber](https://wordpress.org/plugins/timber-library/).

This is because while using Timber, the post object is usually of class `Timber\Post` instead of `WP_Post`:

> This is the object you use to access or extend WordPress posts. Think of it as Timber's (more accessible) version of WP_Post. This is used throughout Timber to represent posts retrieved from WordPress making them available to Twig templates. See the PHP and Twig examples for an example of what it's like to work with this object in your code.

https://timber.github.io/docs/reference/timber-post/

#### What I expected
To see <head> Open Graph Tags in single posts when using the plugin Timber.

#### What happened instead
The <head> Open Graph Tags have disappeared after a recent update of Jetpack.

**Comment by jeherve** [comment]
This was introduced in #17423. 

Were the tags previously all displayed properly? I'm asking because `Timber\Post` seems to be a bit different from `WP_Post`. Looking at the documentation, I do not see the `post_title` property for example, while we do rely on that property to display Open Graph tags in Jetpack:
https://github.com/Automattic/jetpack/blob/3dfc97c0d9e26dcfb96899e0175f85c56b827a48/functions.opengraph.php#L121

I suppose we could switch from checking for `WP_Post` to checking if each property exists, individually. That would make things a bit less clean though. 

Do you happen to know what Timber recommends in these scenarios? It would seem that such issues would come up with a lot of plugins that rely on the `WP_Post` object.

**Comment by vvvctr** [comment]
Hi @jeherve!

It did work before, indeed. Even though it is not documented there, the `post_title` property and other `WP_Post` properties are actually available in the `Timber\Post` object.

In any case, I just checked [their starter theme code](https://github.com/timber/starter-theme/blob/1.x/page.php#L27) and it shows that while retrieving the post, the developer should not override the global variable $post before assigning it to the $context. So doing something like this just works and won't interfere with any plugins which rely on the `WP_Post` object, as you previously noted.

```
$timber_post     = new Timber\Post();
$context['post'] = $timber_post;
```

Thanks!
