### ISSUE TITLE
Gathering Tweetstorms: automatically add tags to post based off hashtags

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#17817]
When creating Twitter Threads, one can add hashtags to their tweets to specify a topic. It would be nice if, when importing a Twitter thread into a post, one could automatically fetch those hashtags and add them as tags to the post.

**Comment by jeherve** [comment]
cc @pento, in case this came up in the past.

**Comment by pento** [comment]
It's been mentioned in the other direction (automatically adding hashtags based on the post tags when publishing a Twitter thread), but I don't recall mention of it in the import direction.

I'm not convinced the former can be done without being super spammy, but I think the enhancement in this issue would be quite reasonable.

Here are my suggested implementation notes, if someone wants to tackle this:

- In `lib/gather-tweetstorm.php` on WPCOM, `::gather()` returns an array of blocks, I don't think it's necessary to change the function signature to include the tags (avoiding the change management that involves). Instead, `::convert_tweet_to_blocks()` could add an array of tags to any block that contains hashtags.
- Since the the data structure will stay as an array of blocks, no changes are needed to `Jetpack_Tweetstorm_Helper` or `WPCOM_REST_API_V2_Endpoint_Tweetstorm_Gather`.
- In the `gathering-tweetstorms` block, `useGatherTweetstorm()` would need to be modified to go over the blocks, grab all the tags, de-dupe and clean them up, then apply them to the post.

**Comment by jeherve** [comment]
Closing since the feature is no longer available.
