### ISSUE TITLE
Widgets: Contact_Info_Widget conflicts with other themes

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#1813]
We should namespace this better.

**Comment by kraftbj** [comment]
Reported in 2131614-t

**Comment by kraftbj** [comment]
Also in https://wordpress.org/support/topic/jetpack-34-breaks-site?replies=11#post-6707927

**Comment by jeherve** [comment]
Could we revert to a unique namespace instead of [looking for a theme name](https://github.com/Automattic/jetpack/blob/master/modules/widgets/contact-info.php#L9)? Many themes are based off Avada, and we won't be able to check for each theme name in Jetpack.

Reported here with a theme named `jwe`, for example:
https://wordpress.org/support/topic/help-just-updated-now-cant-get-in-admin-panel-500-server-error

**Comment by kraftbj** [comment]
The solution in #1814 is still valid.

The item we cannot change is https://github.com/Automattic/jetpack/blob/e47fb86d08d5c153398c521211ce66afeb58bb26/modules/widgets/contact-info.php#L49 . That instance of `widget_contact_info` is what WP is using to link the widget to the db.

The PHP class and related functions can be changed without impacting existing instances of the widget from the testing I did with @jeherve.

**Comment by jeherve** [comment]
Also reported here with a theme named `archerindustries`.
https://wordpress.org/support/topic/fatal-error-cannot-redeclare-class-contact_info_widget

**Comment by jeherve** [comment]
Same issue with the [Terra theme](http://themeforest.net/item/terra-responsive-multipurpose-wordpress-templete/4396320).

**Comment by jeherve** [comment]
Same issue [on that thread](https://wordpress.org/support/topic/broken-403?replies=3&view=all#post-6748999) with a theme named `Avada 2`.

**Comment by jeherve** [comment]
Also reported with the [nimva theme](http://www.rockythemes.com/nimva/).

**Comment by richardmtl** [comment]
Also reported with  [creativo theme](http://rockythemes.com/creativo/) (same author as in Jeremy's comment right above mine).
