### ISSUE TITLE
Conversation/dialog blocks: edit participants from toolbar

### ISSUE THREAD

**Issue by creativecoder** [Automattic/jetpack#18283]
A conversation block contains several dialogue blocks, and you can set the participants list from either place.

In testing we've seen some bugs, seemingly caused when the participants lists are out of sync.

- Move participant UI to toolbar
- Always keep participants list in sync between dialog and parent conversation block
- This means that any "custom participant" for an individual dialog block will be added to the list of participants in the paret conversation

**Comment by retrofox** [comment]
I'd like to know the opinion of @sfougnier here. Basically, the idea is to be able to edit the participant names from the dialogue block:

replace this...
<img src="https://user-images.githubusercontent.com/77539/104586034-aff81200-5643-11eb-8d75-f5607cf09fb6.png" width="400px" />

whit something like this:
<img src="https://user-images.githubusercontent.com/77539/104586081-bd150100-5643-11eb-81c9-65bb04857656.png" width="400px" />

**Comment by sfougnier** [comment]
Let me make sure I'm understanding, I think I might be confused.

Do we need to make the ability to add/edit names within the toolbar consistent across the conversation and dialogue blocks? Does this impact the selection dropdown within the dialogue block? The screenshots shared above show 2 separate user actions, selection vs add/edit.

>Move participant UI to toolbar
> Always keep participants list in sync between dialog and parent conversation block

Is this what you're referring to, moving the ability to add/edit names to the dialogue block in the toolbar? Would the name in the canvas still be clickable to select the names? 

<img width="702" alt="Screen Shot 2021-01-15 at 10 03 52 AM" src="https://user-images.githubusercontent.com/67021691/104742992-27e43c00-5719-11eb-8313-a8d40297c736.png">
<img width="678" alt="Screen Shot 2021-01-15 at 10 04 53 AM" src="https://user-images.githubusercontent.com/67021691/104743013-30d50d80-5719-11eb-843b-969313829966.png">
<img width="776" alt="Screen Shot 2021-01-15 at 10 06 12 AM" src="https://user-images.githubusercontent.com/67021691/104743455-b8bb1780-5719-11eb-8bea-851c2482e837.png">

Or are you merely saying that the selection needs to happen within the toolbar vs in the canvas?

<img width="766" alt="Screen Shot 2021-01-15 at 10 09 35 AM" src="https://user-images.githubusercontent.com/67021691/104743510-c6709d00-5719-11eb-9977-3eaa4330cdda.png">

Or that a user should be able to add/edit and select all within the same dropdown?

<img width="806" alt="Screen Shot 2021-01-15 at 10 20 36 AM" src="https://user-images.githubusercontent.com/67021691/104744807-5105cc00-571b-11eb-91e5-4fd1d90d2ac7.png">


> This means that any "custom participant" for an individual dialog block will be added to the list of participants in the parent conversation

So, we'd remove the ability to add one-off overrides, correct? I think depending on what we do with the rest of this, perhaps it doesn't make sense to even include this as an option anymore.

**Comment by retrofox** [comment]
> Do we need to make the ability to add/edit names within the toolbar consistent across the conversation and dialogue blocks?

Yes. Currently, to edit the participant's name I have to switch to the conversation block in order to be able to edit their names. I can get annoying IMO. And it gets worse when editing a transcription with a bunch of dialogue blocks.
So considering we've already have connected both blocks, there is not a technical reason why do not edit the participant names from the Dialogue block. It will impact straight in the UX.

> Does this impact the selection dropdown within the dialogue block?

Yes, but something that we can deal with. We can change the `remove` button by an icon, and add another `select` button? or maybe add a radio button next to each input field.

> The screenshots shared above show 2 separate user actions, selection vs add/edit.
 
Yes.

> > Move participant UI to toolbar
> > Always keep participants list in sync between dialog and parent conversation block
> 

> Is this what you're referring to, moving the ability to add/edit names to the dialogue block in the toolbar?

I wouldn't say **moving** but **adding**, in the sense that the `conversation` block will still able to edit the participants.

> Would the name in the canvas still be clickable to select the names?

Yes, but also to add/edit/remove participants from it.

> Or are you merely saying that the selection needs to happen within the toolbar vs in the canvas?

Nop. I strongly encourage us to try to keep the toolbar as clean as possible. 

> Or that a user should be able to add/edit and select all within the same dropdown?

That's the idea. :100:


> > This means that any "custom participant" for an individual dialog block will be added to the list of participants in the parent conversation

Yes, but something that we can ignore for now.


> So, we'd remove the ability to add one-off overrides, correct? I think depending on what we do with the rest of this, perhaps it doesn't make sense to even include this as an option anymore.

Yes, something that we should consider. We added the `custom` participant because sometimes the transcription has a unique name when is introduced in the transcription, but then it changes to another name, but globally.  https://distributed.blog/2020/10/15/episode-25-davit-baghdasaryan-on-the-science-of-sound-in-a-distributed-work-world/ is a good example of this. In the beginning, the participants have full names, but then it applies the first name.


> Do we need to make the ability to add/edit names within the toolbar consistent across the conversation and dialogue blocks?

Yes. Currently, to edit the participant's name I have to switch to the conversation block in order to be able to edit their names. I can get annoying IMO. And it gets worse when editing a transcription with a bunch of dialogue blocks.
So considering we've already have connected both blocks, there is not a technical reason why do not edit the participant names from the Dialogue block. It will impact straight in the UX.

> Does this impact the selection dropdown within the dialogue block?

Yes, but something that we can deal with. We can change the `remove` button by an icon, and add another `select` button? or maybe add a radio button next to each input field.

> The screenshots shared above show 2 separate user actions, selection vs add/edit.
 
Yes.

> > Move participant UI to toolbar
> > Always keep participants list in sync between dialog and parent conversation block
> 

> Is this what you're referring to, moving the ability to add/edit names to the dialogue block in the toolbar?

I wouldn't say **moving** but **adding**, in the sense that the `conversation` block will still able to edit the participants.

> Would the name in the canvas still be clickable to select the names?

Yes, but also to add/edit/remove participants from it.

> Or are you merely saying that the selection needs to happen within the toolbar vs in the canvas?

Nop. I strongly encourage us to try to keep the toolbar as clean as possible. 

> Or that a user should be able to add/edit and select all within the same dropdown?

That's the idea. :100:


> > This means that any "custom participant" for an individual dialog block will be added to the list of participants in the parent conversation

Yes, but something that we can ignore for now.


> So, we'd remove the ability to add one-off overrides, correct? I think depending on what we do with the rest of this, perhaps it doesn't make sense to even include this as an option anymore.

Yes, something that we should consider. We added the `custom` participant because sometimes the transcription has a unique name when is introduced in the transcription, but then it changes to another name, but globally.  https://distributed.blog/2020/10/15/episode-25-davit-baghdasaryan-on-the-science-of-sound-in-a-distributed-work-world/ is a good example of this. In the beginning, the participants have full names, but then it applies the first name.

**Comment by sfougnier** [comment]
> Yes. Currently, to edit the participant's name I have to switch to the conversation block in order to be able to edit their names. I can get annoying IMO. And it gets worse when editing a transcription with a bunch of dialogue blocks.

I'm curious how often adding/editing names will be a common occurrence for podcasters who are in the process of transcribing. I agree that it could get frustrating if it is a common scenario. Something to test, I suppose.

>Yes, but something that we can deal with. We can change the remove button by an icon, and add another select button? or maybe add a radio button next to each input field.

Do you have an example of another block that does this? This doesn't really follow any existing patterns that I am aware of. I think this will warrant a mini-exploration, I think we should try some options out in design before making a decision.

> We added the custom participant because sometimes the transcription has a unique name when is introduced in the transcription, but then it changes to another name, but globally.

Yeah, for sure! I definitely see the use case for having the override, but I'm also not sure if it will further complicate things with the other changes. I'll explore it 😄 

I can timebox some exploration next week for this, I'd like to look into this further before making a decision.

**Comment by retrofox** [comment]
> > Yes. Currently, to edit the participant's name I have to switch to the conversation block in order to be able to edit their names. I can get annoying IMO. And it gets worse when editing a transcription with a bunch of dialogue blocks.
> 
> I'm curious how often adding/editing names will be a common occurrence for podcasters who are in the process of transcribing. I agree that it could get frustrating if it is a common scenario. Something to test, I suppose.

To me, it's enough if it happens once. 

> 
> > Yes, but something that we can deal with. We can change the remove button by an icon, and add another select button? or maybe add a radio button next to each input field.
> 
> Do you have an example of another block that does this? This doesn't really follow any existing patterns that I am aware of. I think this will warrant a mini-exploration, I think we should try some options out in design before making a decision.

Fair enough.

> > We added the custom participant because sometimes the transcription has a unique name when is introduced in the transcription, but then it changes to another name, but globally.
> 
> Yeah, for sure! I definitely see the use case for having the override, but I'm also not sure if it will further complicate things with the other changes. I'll explore it 😄

just in case, the custom participant option is already implemented.

> 
> I can timebox some exploration next week for this, I'd like to look into this further before making a decision.

Nice, just keep in mind we have one-week before code freezing :-D

**Comment by sfougnier** [comment]
Based on some exploration and review, I propose the following updates to participant selection:

- Move participant dropdown to the toolbar within Conversation + Dialogue blocks.
- Remove the custom participant override in the Dialogue block.
- Maintain the existing separation of actions across the Conversation (Add/edit/remove across all blocks) and Dialogue (Select for single block). Merging these actions into the same dropdown becomes confusing for a few reasons, but generally, it's clearer that making a parent block change will impact all child blocks rather than applying the same parent block functionality across all child blocks. 
- Add a link to 'edit participants' in the Dialogue block dropdown to make editing the participant list more accessible. Clicking this would take the user to the parent block participant dropdown.

<img width="1472" alt="Screen Shot 2021-01-19 at 10 50 28 AM" src="https://user-images.githubusercontent.com/67021691/105058381-2631b580-5a44-11eb-8039-0c0ee79564cd.png">

**Comment by creativecoder** [comment]
Thanks @sfougnier ! I've removed the "Needs Design Review" label, as it looks like your last comment covers that.

**Comment by retrofox** [comment]
> Add a link to 'edit participants' in the Dialogue block dropdown to make editing the participant list more accessible. Clicking this would take the user to the parent block participant dropdown.

This is not something that we can do easily, since it will require:

1) Select the `Conversation` block form the `Dialogue` block
2) Open the participants dropdown once the `Conversation` block is focused.

Even being doable (probably in a hacky way), it can get super confusing in terms of the user experience. Consider the following example, when the conversation block has a bunch of Dialogue blocks into it.

It will change the interface from this state (lets image the participants dropdown is right there):

![image](https://user-images.githubusercontent.com/77539/105078947-72ddb680-5a6d-11eb-96e2-f854eded651f.png)

To this:

![image](https://user-images.githubusercontent.com/77539/105078978-7d984b80-5a6d-11eb-81f0-4104c318c9d8.png)

It changes the context of the application. The sidebar changes considerably.

**Comment by retrofox** [comment]
If we remove the participants dropdown to the toolbar, how we are going to show the participant styles?

<img src="https://user-images.githubusercontent.com/77539/105083822-3bbed380-5a74-11eb-8124-3299875fac16.png" width="500px" />

Right now, when the user opens the participants dropdown, the styles are shown in the toolbar:

<img src="https://user-images.githubusercontent.com/77539/105083940-66a92780-5a74-11eb-8325-62fc0d02844d.png" width="300px" />

When the Dialogue content focuses, the toolbar changes showing the default toolbar for text editing, the same one shown for paragraph blocks, for instance.

<img src="https://user-images.githubusercontent.com/77539/105084794-a290bc80-5a75-11eb-9f15-d2331a00e7f3.png" width="400px" />



We can still activate the participant styles in the block toolbar when the user focuses on the participant label, tough. Also, maybe we can print the participant as a button? Or... keep both the dropdown in the editor canvas and also the menu in the toolbar ¯\_(ツ)_/¯

**Comment by retrofox** [comment]
<img src="https://user-images.githubusercontent.com/77539/105085290-4d08df80-5a76-11eb-9674-77c1cf6e6c36.png" width="400px" />

The `Timestamps` button there will be used to show/hide the Timestamps option?
If so, should we replace it by an icon?

**Comment by sfougnier** [comment]
> This is not something that we can do easily, since it will require:

Ah, I see. Is there a way to, rather than add the 'edit participants' in the canvas toolbar dropdowns, place it in the sidebar within the participants section? On click, it could just select the parent block, rather than needing to toggle any dropdowns open.

Otherwise, let's just remove the 'edit participants' link and move forward with the rest of the changes / keep things as reflected in the [designs](https://www.figma.com/file/T9w8JpWJP4wmsWgvczyCyG/Anchor-Partnership?node-id=2777%3A61217).

> If we remove the participants dropdown to the toolbar, how we are going to show the participant styles?

I was under the impression we had removed the ability to edit participant name styling from the v1. It was removed from the design, as it adds an extra layer of complexity that starts to get confusing pretty quickly.

**Comment by retrofox** [comment]
> We can still activate the participant styles in the block toolbar when the user focuses on the participant label, tough. Also, maybe we can print the participant as a button? Or... keep both the dropdown in the editor canvas and also the menu in the toolbar ¯_(ツ)_/¯

Replacing the Dropdown with a Button looks good.
<img src="https://user-images.githubusercontent.com/77539/105085940-40d15200-5a77-11eb-9e10-78b0fdd76abc.png" width="400px" />

**Comment by retrofox** [comment]
> > This is not something that we can do easily, since it will require:
> 
> Ah, I see. Is there a way to, rather than add the 'edit participants' in the canvas toolbar dropdowns, place it in the sidebar within the participants section?

Yes, it's doable.

> On click, it could just select the parent block, rather than needing to toggle any dropdowns open.

Correct. Switching between blocks to edit the participant name doesn't look good to me, though.
What do you think about being able to edit the participant name, from the Dialogue block but only in the sidebar?
<img src="https://user-images.githubusercontent.com/77539/105087144-d0c3cb80-5a78-11eb-92b2-e46455ebf64d.png" width="400px" />

> Otherwise, let's just remove the 'edit participants' link and move forward with the rest of the changes / keep things as reflected in the [designs](T9w8JpWJP4wmsWgvczyCyG-fi-2777%3A61217).

You have the last word :-)
 
> > If we remove the participants dropdown to the toolbar, how we are going to show the participant styles?
> 
> I was under the impression we had removed the ability to edit participant name styling from the v1.

Basic styles for participants have been there from a long time ago. Bold, Italic, and Uppercase. What we didn't do because decided it wasn't going to be part of v1 was setting participant colors.

> It was removed from the design, ...

Sorry I wasn't aware of this change.

> ... as it adds an extra layer of complexity that starts to get confusing pretty quickly.

Sorry, I don't get how it could get confusing. Removing the capability to format the participant label will be a pretty basic tool that could impact negatively the users. Can we try to keep it and improve the experience, even if it's done after v1?

**Comment by retrofox** [comment]
Took this one:

> Otherwise, let's just remove the 'edit participants' link and move forward with the rest of the changes / keep things as reflected in the designs.

btw I can't see the design from that link

**Comment by retrofox** [comment]
Almost all issues addressed here https://github.com/Automattic/jetpack/pull/18438
