### ISSUE TITLE
Protect: Ensure Math_Autentication class is loaded

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#1841]
Quick read of the code suggests that the `Jetpack_Protect_Math_Authenticate` class is only defined via `include ... /protect/math-fallback.php` which is called in `check_use_math`, which is fired on `add_action( 'login_head', ..) L50 or `check_login_ability`

In `check_preauth` (fired as a filter on `authenticate`), the `Jetpack_Protect_Math_Authenticate::math_authenticate();` function is fired only with a check of a transient. 

It may be possible for this filter to fire without loading `math-fallback.php` resulting in a fatal reported by an user:
`[Sat Mar 21 22:57:01 2015] [error] [client xxx ] PHP Fatal error:
Class 'Jetpack_Protect_Math_Authenticate' not found in
/var/www/wp-content/plugins/jetpack/modules/protect.php on line
221`

User noted seeing math human check on the wp-login.php screen with an occasional white screen: "Not every time.... but anoyingly often."

I haven't duplicated, so investigating further with user as well. 2135605-t

**Comment by arkonlabs** [comment]
If it helps at all, i'm also experiencing this issue. None of my users are able to log into their own website.
![screen shot 2015-03-23 at 1 09 04 pm](https://cloud.githubusercontent.com/assets/5146215/6787021/d84a3dda-d15d-11e4-9f74-abd4074ba4f0.png)

**Comment by samhotchkiss** [comment]
Hey @arkonlabs -- I've got a fix for this ready to go here: https://github.com/Automattic/jetpack/pull/1857/files

Can you try manually applying this and let us know if it clears things up?

**Comment by Konceptuel** [comment]
Hi @arkonlabs 
this is what we experience as well:
>The issue only seems to arise when they try logging in from /wp-admin and not when they log in from /wp-login.php

**Comment by lumpysimon** [comment]
I'm seeing this too since the Protect module was added, it's happening on every login attempt (blank white screen, fatal error in the PHP error log).

@samhotchkiss's fix works for me.

**Comment by JayHoltslander** [comment]
@samhotchkiss Thank you.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/jetpack-with-protect-breaks-all-my-websites?replies=6&view=all

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/php-fatal-error-in-protect-math-authenticate?replies=1&view=all

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/fatal-error-1569?replies=1&view=all

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/jetpack-protect-is-locking-me-out?replies=4&view=all

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/jetpack_protect_math_authenticate

**Comment by glyndavidson** [comment]
Same here, although no error message is displayed, just a white screen. 
Note, Protect has been active for some time, but today is the first time the maths question appeared.
Deactivating, and then Reactivating Protect removes the maths question.
I've tried repeating the steps that might have made the maths question appear but haven't yet been able to do so.

**Comment by jsmcgraw** [comment]
@samhotchkiss 

Fix works for me, though I'm still prompted with the math challenge every time on IP addresses that are on the Protect whitelist.

**Comment by Ipstenu** [comment]
Of note, this just happened to me in a very specific way.

1. Using Multisite, the per-site login did not have a problem.
2. Saw I had a plugin upgrade pending, went to run it, was prompted to log in again (this is expected, mapped domains etc). 
3. Logged in, got a MATH problem I had never seen before.
4. Filled in deets, got that error message

While the fix DOES correct it, this is a serious bug if you're havign BP Math show up like that. Also I did whitelist my IP, but only on the main site. There's no place I can see to do it on the Network admin, which is a serious issue if you're checking it on network admin. I would have expected it to draw from the main site whitelist.

Jetpack is network activated, BTW.

**Comment by jeherve** [comment]
> There's no place I can see to do it on the Network admin, which is a serious issue if you're checking it on network admin. I would have expected it to draw from the main site whitelist.

+1. Related: #1861 and #1842

**Comment by ahogen** [comment]
I just dealt with this today. Same symptoms described [here](https://wordpress.org/support/topic/jetpack-protect-is-locking-me-out). I have no choice but to disable Protect entirely, which really sucks, but I hate getting locked out of my own site.

My Wordpress site in question: [http://redambassadormusic.com/](http://redambassadormusic.com/)

**Comment by jeherve** [comment]
@ahogen The  Fatal error reported above was fixed last year. You mentioned you were getting locked out of your own site; did you get the error message mentioned on the thread you linked to?

`Fatal error: Class 'Jetpack_Protect_Math_Authenticate' not found in .../wpcontent/plugins/jetpack/modules/protect.php on line 221`

Or did you get a different error message? If so, which one?

**Comment by ahogen** [comment]
My fault. Sorry. I didn't read the error details correctly. I didn't meant to bring up an old issue.

Here (were) my symptoms. Let me know if I should post this as a new issue or not....

- Went to my `wp-login.php` page to log in
- Entered my username and password
- The page refreshed, no error message, same login screen only now there is the math challange
- I enter the same username and password. Enter the correct sum into the challenge field. 
- Page loads as if it's going to log me in and then without any error message, displays the same login form with the math challenge.

I tried this many times. Finally I went to Wordpress.com and disabled Jetpack and was able to log in to my site successfully. No issues since I have re-enabled Jetpack and disabled "Protect."

Again, apologies for posting this on an reliant issue. I will gladly post this wherever you suggest.

**Comment by jeherve** [comment]
@ahogen That makes sense. The issue you ran into is a conflict with the W3 Total Cache, and we'll get this fixed in the next Jetpack update, scheduled to happen in the next couple of days. If you'd like, you can apply the patch to your own Jetpack installation. The changes are outlined in #4746.

Another alternative would be to install Jetpack 4.2.1 Release Candidate 1 on your site; it's available here:
https://github.com/Automattic/jetpack/releases/tag/4.2.1-rc1
