### ISSUE TITLE
Nav Unification: Sharing options are duplicated

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/jetpack#18427]
Sharing options are duplicated and appear on both `Tools > Marketing > Sharing Buttons` (Calypso) and on `Settings > Sharing (WP Admin)`. We should keep a single one and move relevant tools (like adding a new service) to Calypso.

#### What I expected

To find all the Sharing Options on a single location.

#### What happened instead
We have two ways to get to the (almost identical pages):

1. https://wordpress.com/marketing/sharing-buttons/SITEURL.wordpress.com
2. https://SITEURL.wordpress.com/wp-admin/options-general.php?page=sharing

#### Browser / OS version

Chrome 87 / Mac Catalina 10.15.7

#### Context / Source

#manual-testing

**Comment by sfougnier** [comment]
I prefer keeping sharing options in https://wordpress.com/marketing/sharing-buttons/SITEURL.wordpress.com for now since it aligns with the current structure on WordPress.com and would be one less change for users with the new nav.

I agree having sharing options in Settings is much more intuitive, so I also vote for a reorg in a follow-up project.
