### ISSUE TITLE
Jetpack Dashboard hidden by "WP Hide Plugin Updates & Notifications"

### ISSUE THREAD

**Issue by mzakariya** [Automattic/jetpack#18439]
#### Steps to reproduce the issue

1. Activate _[WP Hide Plugin Updates & Notifications](https://wordpress.org/plugins/wp-hide-updates-notifications-and-warnings/)_ on a Jetpack site
2. Our dashboard page is hidden

Disabling the _Hide Warnings_ feature of the above plugin allows our Dashboard to appear, but also largely defeats the purpose of the plugin.

![](https://d.pr/i/GnwZDn+)
Image Link: https://d.pr/i/GnwZDn

This seems like relatively new behavior, and we've started getting reports from affected users.

**Comment by dereksmart** [comment]
This plugin works by unsetting the global $wp_filter like so `unset($wp_filter['admin_notices']);` ([among others](https://plugins.trac.wordpress.org/browser/wp-hide-updates-notifications-and-warnings/tags/1.1.0/1.0/wphdpuw.php#L225)). It's bound to cause some functionality issues. Jetpack attaches not only the full-screen connection prompt (the one you are viewing), but all connection, info, warning, error, and success notices onto that filter.

Attached is a full dump of all of the functionality (Jetpack and otherwise) they are suppressing with the code on the Jetpack page alone: 

[scratch_22.txt](https://github.com/Automattic/jetpack/files/5839103/scratch_22.txt)

Since the Jetpack dashboard itself not attached to any admin notices, it appears just fine after connected. 

Somewhat ironically, this plugin does not suppress their own PHP notices and warnings, as I was greeted with this upon activation: 
![image](https://user-images.githubusercontent.com/7129409/105104888-1c7a7300-5a81-11eb-9d98-66e89713131c.png)

`admin_notices` are a healthy, normal part of WordPress functionality and I would personally recommend that no one who wishes to keep their site healthy to suppress them globally as such. There looks to be a sea of other plugins that provide this functionality, so I would recommend finding one that allows you to pick and choose which specific notices to hide. 

In any case, we will not be building a workaround for this issue.
