### ISSUE TITLE
Anchor.fm: Default to latest episode if episode not provided

### ISSUE THREAD

**Issue by creativecoder** [Automattic/jetpack#18514]
#### Is your feature request related to a problem? Please describe.

It's possible that users could come from Anchor.fm without an episode specified, particularly from the Dashboard link

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/1699996/105610859-88a5f100-5d77-11eb-9c81-f0d85f5bf632.png">

When that happens, you end up with an empty post, rather than having the podcast episode starter content.

![image (1)](https://user-images.githubusercontent.com/1699996/105610876-a2473880-5d77-11eb-8588-f5685cbbdf2c.png)

#### Describe the solution you'd like

Fallback to the most recent episode in the RSS feed for the episode post content.

**Comment by kwight** [comment]
Hm, I like this idea. Honestly, I hope we can instead all commit to the `episode` query param being required – it seems this is the only way to ensure that a just-published post is the one used to populate our editor (the RSS feeds are cached, so we can't rely on them). That said, having _something_ load rather than nothing is always good. 🙃

**Comment by creativecoder** [comment]
> Honestly, I hope we can instead all commit to the episode query param being required

Agreed, that's the happy path 😀!

But, in the case where the episode id gets lost, for whatever reason, staring at a blank post is an awful first experience with the editor.

It's a small change to fix, so we went ahead with this in https://github.com/Automattic/jetpack/pull/18531 to get it into the upcoming release.
