### ISSUE TITLE
Add Custom Colors from wp.com

### ISSUE THREAD

**Issue by BinaryMoon** [Automattic/jetpack#1854]
I make premium themes for wp.com and so it would be great if I could set up the custom colours through the customizer on my dev environment.

Currently the colour annotations are controlled by wordpress.com theme team. Moving it to Jetpack would mean I can control the colours - this would mean better coverage (since I know the theme better than anyone) and I can update the annotations when new colours are added or when bugs are found.

I would like to see it working something like this:

```
add_theme_support( 'custom_colours', array(
    'colours' => array(
        'name 1',
        'name 2',
        'name 3',
    ),
    'colour_schemes' => array(
        array( '#f00', '#0f0', '#00f' ),
        array( '#f00', '#0f0', '#00f' ),
        array( '#f00', '#0f0', '#00f' ),
    ),
    'callback_fn' => 'css_output_function',
));
```

This would allow me to set named colours, specify a few default colour schemes (which are offered for free on wp.com), and specify a callback function that decides what rules to output.

**Comment by kraftbj** [comment]
cc: @ianstewart

**Comment by brbrr** [comment]
I don't think this will ever happen. WP.COM themes team works only with WP.COM, and there are no plans to change that, unfortunately.

I'm going to close this issue. If you still think this is something that should be done on Jetpack site, feel free to reopen it and please update the issue so that it follows our [guidelines](https://github.com/Automattic/jetpack/blob/master/.github/CONTRIBUTING.md#create-bug-reports).
