### ISSUE TITLE
Instant Search: standard sidebar widgets can end up in the search modal sidebar when switching themes

### ISSUE THREAD

**Issue by bluefuton** [Automattic/jetpack#18556]
#### Steps to reproduce the issue

1. Set up a new WordPress site with the Twenty Twenty One theme. This theme has no sidebar area.
2. Switch to a theme that does have a sidebar of sorts, like Twenty Twenty (footer sidebar)
3. Note that the Jetpack Search sidebar now has a bunch of unwanted widgets in it, like 'Archives', 'Categories' and 'Meta'

#### What I expected

Switching themes does not add a bunch of widgets to my nice search modal.

#### What happened instead
I got some bonus sidebar widgets I didn't ask for. My guess is that WordPress looks for a widget area with 'sidebar' in the name to add the widgets to, and Twenty Twenty One doesn't create one (it just has "Footer #1" and "Footer #2").

**Screenshots**

<img width="1076" alt="Screen Shot 2021-01-27 at 14 16 29" src="https://user-images.githubusercontent.com/17325/105928147-44ce2700-60aa-11eb-99b1-b4aef93430a6.png">

**Comment by kangzj** [comment]
Had an investigation yesterday and found out that when switching themes, WordPress would try to migrate sidebar widgets to new sidebars. And if the new theme has less sidebars than the old theme, *WordPress would chuck the not-belonging-to-any-sidebar widgets in existing sidebars rather than moving them to unused widgets*, which is what is happening in the issue. 
I'm looking at relevant filters and see if we can deal with it.

Related WordPress functions: [wp_map_sidebars_widgets](https://github.com/WordPress/WordPress/blob/b8487747b8eba2562ab05db3cff2440a22761e94/wp-includes/widgets.php#L1320)

**Comment by bluefuton** [comment]
> WordPress would chuck the not-belonging-to-any-sidebar widgets in existing sidebars rather than moving them to unused widgets, which is what is happening in the issue.

Excellent sleuthing @kangzj! 🕵️
