### ISSUE TITLE
Onboarding / Recommendations: optimize images

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#18587]
> I took a good two seconds for the image to show up on the initial step (site-type-illustration.png). Running the foreground image through Optimage saved 92 KB (148 KB – 56KB).
>
> All subsequent images also took some milliseconds to show up. At the very least we should ensure all the added images are compressed as much as possible; for example, 148 KB seems like a lot for such a small image.

-----

p8oabR-BT-p2#comment-4905

**Comment by jeffgolenski** [comment]
@robertf4 @jeherve I've optimized the images a bit more by converting them from png to jpg. Not an issue since we really don't need the transparency. 

Total file size went from 528kb (pngs) > **down to 143kb** (jpgs). I think that should be good. 

[jetpack-assistant-imgs-jpg.zip](https://github.com/Automattic/jetpack/files/5889556/jetpack-assistant-imgs-jpg.zip)

If we're finding that's still too large, we have designed fallback svgs to use instead of raster images.
