### ISSUE TITLE
Podcast Player Block: Issues with AMP + other iframes in the Customizer

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/jetpack#18714]
Disclaimer: This seems like an issue related to the Podcast block, but this might not be the correct spot (I'm not sure, for example, that the MediaElement.js isn't the cause). Please let me know if I should file this somewhere else!

#### Steps to reproduce the issue

1. Set up a test site using a default theme. 
2. Install Jetpack and the [official AMP plugin](https://en-ca.wordpress.org/plugins/amp/); set AMP to Standard mode under WP Admin > AMP. 
3. Add the podcast block, and another block that inserts an iframe to a page or post (a Custom HTML block with a regular iframe will work, or an embed like YouTube).
4. When viewing that post, open the Customizer by clicking the button in the admin toolbar, so the Customizer previews this page. 

#### What I expected
A regular preview of the page. 

#### What happened instead
The preview starts with an exploded version of the Podcast Player CSS. When I inspect it, it looks like a partial SVG element is inserted right after the body tag, replacing the opening `<style>` tag. 

**Screenshots**
With the Twenty Twenty One theme:

![image](https://user-images.githubusercontent.com/177561/106945160-5338c600-66dc-11eb-9cd9-34352a63e2e6.png)

Scrolling down will eventually reach the normal page preview...

![image](https://user-images.githubusercontent.com/177561/106945202-6055b500-66dc-11eb-8d63-673e25e4bcfa.png)

... but the podcast player is not styled correctly, because its styles are messed up:

![image](https://user-images.githubusercontent.com/177561/106945277-76637580-66dc-11eb-8f34-b3ca7bb2458d.png)

What I see when I inspect the Customizer preview's iframe -- after the closing `<body>` tag, there is an opening `<g>` tag (like it's midway through an `<svg>` tag). The [audio player styles in Jetpack include SVGs](https://github.com/Automattic/jetpack/blob/763703ec4974dc1017c2d1a5648d1fa0e3e1ffd0/projects/plugins/jetpack/extensions/shared/components/audio-player/style.scss#L136), so it could just be something else is cutting off the styles, and this just happens to be where it is:

![image](https://user-images.githubusercontent.com/177561/106945456-a7dc4100-66dc-11eb-9b6f-036817a10a23.png)

**Comment by westonruter** [comment]
Looks like this is a bug with the AMP plugin. The issue is that in the Customizer, tree shaking is disabled which then allows for this CSS rule to be added to `style[amp-custom]` from `podcast-player/view.css:

https://github.com/Automattic/jetpack/blob/763703ec4974dc1017c2d1a5648d1fa0e3e1ffd0/projects/plugins/jetpack/extensions/shared/components/audio-player/style.scss#L140-L143

Note the `</style>` embedded inside the SVG `data:` URL. This is causing the stylesheet to prematurely close. 

The quick fix in Jetpack would be to make sure the SVG data: URLs get URL-encoded like elsewhere in the stylesheet:

https://github.com/Automattic/jetpack/blob/763703ec4974dc1017c2d1a5648d1fa0e3e1ffd0/projects/plugins/jetpack/extensions/shared/components/audio-player/style.scss#L136-L138

Or else use a base64 encoding. 

The AMP plugin needs to do this URL encoding to prevent this from happening.

**Comment by westonruter** [comment]
This regression appears to have been introduced in #18501 via 763703ec4974dc1017c2d1a5648d1fa0e3e1ffd0.

**Comment by westonruter** [comment]
> The AMP plugin needs to do this URL encoding to prevent this from happening.

I opened a fix for that as well: https://github.com/ampproject/amp-wp/pull/5937.
