### ISSUE TITLE
Sharing: Twitter share button opens popup and new tab in Firefox

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#18760]
#### Steps to reproduce the issue

1. Go to https://uneven-chinstrap.jurassic.ninja/2021/02/09/hello-world/ (or any site with sharing enabled) in Firefox.
2. Click on the Twitter share button.
3. See Twitter open in a new tab and in a popup window.

Note: This doesn't happen every time, it seems almost random, but if you keep trying you should see the issue.

Reported in https://wordpress.org/support/topic/sharing-buttons-open-two-windows-on-firefox-since-jepack-9-4/ - although I couldn't reproduce on the site mentioned there. That user also mentioned it happening with Facebook, but I could only reproduce with Twitter.

**Screenshots**

![image](https://user-images.githubusercontent.com/1990037/107354466-18f96b00-6ac6-11eb-9709-ec335eba80df.png)

- Jetpack 9.4
- Firefox 85.0 on Mac

**Comment by jeherve** [comment]
This may be caused by our move away from jQuery, and the caching service in use on the site. Let's try to investigate on the thread.

**Comment by jeherve** [comment]
@sgomes Could you take a look at this? I assume it's a byproduct of #17864.

**Comment by sgomes** [comment]
That's odd. The apparent randomness makes me think this is a race condition inside Firefox, but that doesn't mean we can't do anything about it.

Perhaps an explicit `event.preventDefault()` could fix things?

**Comment by Salubritas** [comment]
I am the original reporter on Wordpress.org. I have re-tested this on my staging site with default theme and minimal plugins.

It is completely consistent on my system (Windows 10, FF 85.0.1). Not intermittent at all.

Test page: https://staging-webretailer.kinsta.cloud/b/selling-branded-products-on-amazon-nnnnn/

Loom video: https://www.loom.com/share/327b4b4ca5e74d15a2c1a6a3b6dd548f

I realized after recording the video that I was logged in as admin so I repeated this logged out and got the same behavior.

I will leave the staging site as-is as long as I can.

**Comment by sgomes** [comment]
Thank you, @Salubritas! I t may well be that the issue manifests itself differently based on the specifics of each system.

What I've found after some further testing is that in the situations where this fails, it's because Firefox fires the default action on the button before the event listener is called. `preventDefault` and `stopImmediatePropagation` don't work to prevent this.

This appears to be because we're setting the event handler on the document body rather than the element, but we need to do this in order to account for new Twitter buttons making their way into the page when e.g. infinite scroll is enabled.

The reason why this used to work with `jQuery` is because it implements its own event system, presumably during the capture phase, so the event never even got to the bubbling phase on the DOM. This sort of inconsistency between browsers is why `jQuery` was created in the first place, and while I thought those days were behind us, it seems there are still edge cases like this where some browsers sometimes do the wrong thing.

The only strategy I can think of is to add the event listener directly to every button that's already present on the page, thus solving the problem for the vast majority of cases. Buttons loaded by infinite scroll will still show the incorrect behaviour, however, unless Firefox changes their event handling.

**Comment by Salubritas** [comment]
Could you move the URL to open from the href attribute to a data attribute (and remove the target attribute as well), and change the href to blank or "#/" so the default action effectively does nothing? That should work fine except for if JS is disabled.

Apologies if I am being naive here.

**Comment by sgomes** [comment]
> Could you move the URL to open from the href attribute to a data attribute (and remove the target attribute as well), and change the href to blank or "#/" so the default action effectively does nothing? That should work fine except for if JS is disabled.
> 
> Apologies if I am being naive here.

You're not at all being naive, that is definitely a valid suggestion 🙂 

That said, I'm reluctant to drop the progressive enhancement approach in this case. It's best if the links have a meaningful destination, both for the use-case of users with disabled JS, which you mention, but also for providing more semantic information to e.g. any robots that are parsing and indexing the page. Also, the link provides browsers with more context of what will happen if the button gets clicked, as well (e.g. the destination showing up in the status bar).

It may well be that we'll end up taking that approach regardless, if the other options prove too cumbersome. I'll try a few of them out and keep this thread posted.

**Comment by sgomes** [comment]
After some further investigation, the problem turns out to not be Firefox-specific at all, and the reason behind the randomness is made clear: it all depends whether you're clicking the button or the `<span>` inside of it. This is a much easier fix, which I've taken care of in #18776

**Comment by sgomes** [comment]
To be clear, there was probably a bit of Firefox quirkness somewhere, since it was the only browser to both open a popup and a new tab, but the behaviour wasn't correct on other browsers either.

**Comment by Salubritas** [comment]
FWIW, I have tested this fix on Firefox and it looks good to me. Also tested on Edge and Chrome and saw no regression. Thanks for working on this so quickly.

**Comment by sgomes** [comment]
Thank you for taking the time to confirm that the fix works on your site, @Salubritas! 👍
