### ISSUE TITLE
Nav Unification - Missing Plugin Submenu

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#18831]
#### Steps to reproduce the issue

When activating 9.4.1, on a site with nav unification enabled, the submenu for the plugin page is missing in Calypso:

**Screenshots**

![Screen Capture on 2021-02-15 at 15-39-54](https://user-images.githubusercontent.com/33553323/107991268-418cd380-6fa4-11eb-8323-653000eaeedd.gif)

**Expected**

![Screen Capture on 2021-02-15 at 15-41-58](https://user-images.githubusercontent.com/33553323/107991337-66814680-6fa4-11eb-837b-87ff0dc1f3f0.gif)

**Comment by jeherve** [comment]
This is related to https://github.com/Automattic/wp-calypso/issues/49120

cc @mmtr who works on this.

**Comment by mmtr** [comment]
Thanks for flagging this, @sdixon194. This is an edge case when the "dashboard appearance" toggle is enabled on https://wordpress.com/me/account.

If that toggle is disabled, the "Plugins" menu links to Calypso as done in the existing Calypso menu (currently visible to all non-a12s). We intentionally remove all the submenu items in order to replicate the existing Calypso menu:

<img width="287" alt="Screen Shot 2021-02-16 at 15 59 28" src="https://user-images.githubusercontent.com/1233880/108080280-f8a25100-706f-11eb-9d72-91f368d125d7.png">

However, when the toggle is enabled, we simply change the link destination to WP Admin but the submenu items remain removed.

At this point, I'm not sure if we should add back the submenu, since the purpose of the toggle is to simply change the destination and not the menu items that are displayed. cc @obenland @lessbloat

**Comment by obenland** [comment]
I think it would make sense to not remove the submenu items when the toggle points to wp-admin
