### ISSUE TITLE
Publicize option or filter to make default view open

### ISSUE THREAD

**Issue by mowse-ink** [Automattic/jetpack#1891]
Hi, gang...

Would you please add an option (or a filter) to make the default view open instead of having to click "Edit Details" every time?

We have set the Publicize to uncheck the boxes by default so that users publicize intentionally. It would be really handy to be able to have the details open by default so that users don't forget to publicize when they're publishing.

Thanks for listening...
—jonathan

**Comment by samhotchkiss** [comment]
Hi @mowse-ink -- we'll definitely look at this in the future-- in the interim, you could create a solution with a little bit of JS that fires on the post edit screen.  Obviously, not as ideal of a solution, but one you could use today rather than waiting until this makes it into a release.

Alternately (and preferably), we'd encourage you to write your own solution and submit a pull request.

Thanks!

**Comment by jkudish** [comment]
At this point, I am inclined to mark this as wontfix. It's pretty edge case and as @samhotchkiss mentions this is is easy to do with Javascript as a custom solution.

**Comment by jenhooks** [comment]
Also requested in 2988996-t 

Reopening to revisit this, if it is (relatively) easy to implement.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
