### ISSUE TITLE
Search: Clicking outside the overlay should close the modal

### ISSUE THREAD

**Issue by mirka** [Automattic/jetpack#18937]
#### Is your feature request related to a problem? Please describe.
With the change in design of the search modal in Jetpack 9.5, there's now a clear visible area outside the modal. A Jetpack Search user reported that they expected the modal to close when clicking outside the modal.

#### Describe the solution you'd like
Clicking outside the modal area closes the modal.

<img width="1436" alt="Screen Shot 2021-03-03 at 11 47 06" src="https://user-images.githubusercontent.com/17325/109725579-3679aa80-7c16-11eb-80fe-fd41404aa3a5.png">

Related: #17554

**Comment by jsnmoon** [comment]
@jeffgolenski: The implementation for this would be straightforward, but I remember that we intentionally omitted this feature during the modal implementation. What are your thoughts? Also, cc'ing @evilluendas, who proposed this originally in the P2 repo.

**Comment by jeffgolenski** [comment]
Let's try it out for sure. Is there anyway we can track this so measure how many people click outside of the modal? @jsnmoon

**Comment by jsnmoon** [comment]
Got it. I'll be sure to implement this with analytics events so that we can keep track of users clicking outside of the modal.

**Comment by bluefuton** [comment]
Good implementation here: https://kittygiraudel.com/2021/03/18/close-on-outside-click/

Could be complicated by our use of a React portal to render the overlay.

**Comment by alinclamba** [comment]
It's been a while since this request was added, but I want to add a little note here. I think it would improve, albeit to a _small extent_, the user experience. Moreover, it would make things **more consistent** (just a small example where the module closes when clicked out):

![close_click-out-of-module](https://user-images.githubusercontent.com/6790170/151942660-c233203c-99e8-4cab-a8fd-67ba6d2aa458.gif)
