### ISSUE TITLE
Form block: submit button alignment options do not work

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#18933]
> Aligning the button doesn’t seem to work as intended. Left and center alignment appear to do nothing, and the right alignment just moves the button a bit towards the right side, when I would expect that it would align to the right side of the form input field.
-- p8oabR-Co-p2#comment-4999

#### Steps to reproduce the issue

1. Go to Posts > Add New
2. Add a new Form block
3. Edit the submit button and change its alignment
4. The different alignment options do not work.

![image](https://user-images.githubusercontent.com/426388/109130183-b94fc080-7751-11eb-95b0-505e9d70b71a.png)

**Comment by calvinmorett** [comment]
Able to replicate the issue, but for me Left and Center alignment worked while using the editor to align a form block button.

**Note**: Although the editor for alignment may be off, on the live site is was working to align the button. 

------------
### Solution (Editor)

![align-editor](https://user-images.githubusercontent.com/11654917/126931832-c2c6e5c2-8a89-4c2e-a15a-ae24480d51b4.gif)

To fix the issue within the editor, with alignment of buttons, we need to set a width for Jetpacks `data-align` class.

- **Add** `width` and set to `100%`

```
div[data-type="jetpack/button"][data-align] {
    z-index: 1;
    width: 100%;
}
```

------------

### Solution (Live Site)

This issue doesn't just effect the above `data-align` class. If a form button is set to right, it will overflow the form, too far to the right.

- **Edit** `margin-left:` and set it to negative value to shift the button back into the form. (-.9em)

**Note**: you technically don't need a display: inline-block on this alignright CSS class, because you're applying a float.

/* Theme: Storefront, button align right */
.alignright {
    display: inline-block;
    float: right;
    margin-left: -.9em;
}
