### ISSUE TITLE
[audio] & [playlist] shortcodes and Infinite Scroll don't work together

### ISSUE THREAD

**Issue by tsiger** [Automattic/jetpack#1893]
If [audio] & [playlist] content isn't visible on page load (loaded using infinite scroll afterwards) the player doesn't get initialised. 

Tested on various themes including TwentyFifteen

**Comment by andreg** [comment]
+1

Also, the same seems to be happening to the [video] content, since it uses Media Element as well; on a related note, some embeds do not work as well, when loaded through infinite scrolling.

**Comment by richardmtl** [comment]
related to https://github.com/Automattic/jetpack/issues/1439 ?

**Comment by andreg** [comment]
Not exactly sure, but it might be.

**Comment by chrisdc** [comment]
I think I see the problem (for playlists at least), but I'm not sure of the best solution yet. Normally if you load a playlist [this code](https://github.com/WordPress/WordPress/blob/5294e0e655a2aa44b402014121771dc73d446392/wp-includes/media.php#L1144) in core adds a couple of underscore js templates to the DOM as script tags. As these scripts are constructed, rather than enqueued the normal way infinity.php doesn't load them and so the playlist doesn't render.

**Comment by jeherve** [comment]
#5518

**Comment by jeherve** [comment]
Closing as wontfix, as `audio` and `playlist` are now provided by WordPress Core and should be handled by Infinite Scroll.
