### ISSUE TITLE
WhatsApp Block: Styling and Alignment Inconsistencies 

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#18940]
Lots of styling issues with the WhatsApp block. This might be related to the state the block in is now - being a child of "send a message" while somehow also being named as its own parent block. 

> “Chat on WhatsApp” doesn’t appear to be correctly styled on the published post:

![image-5-15](https://user-images.githubusercontent.com/33553323/109175812-2d8b6380-7754-11eb-9c84-397bf25c3dbd.png)

> Once aligned to the left, it’s harder to select the button again for the controls to show up. You have to click on the lower part of the button to make the selection again.

> Alignment issues as mentioned elsewhere. This Block frequently collapses behind other Blocks that end up wrapping entirely around it and making it difficult to click again. Some Blocks collapse around it and some don’t. Behavior is inconsistent.

> When center aligned, the Block has additional space on the bottom compared to when it it Left or Right aligned.

Related:

> The Block is named “Send a Message” in the overall List View, but only “WhatsApp Button” in the Block browser (although it is still searchable by either term). It’s somewhat confusing.

If these are separate issues, happy to break this down into multiple distinct bug reports instead. 

**Additional Context**
p8oabR-Co-p2#comment-5013
p8oabR-Co-p2#comment-5050

**Comment by jeherve** [comment]
This was most likely introduced in #18487, since we ran into the same problem when testing this PR.

@stacimc @apeatling Do you think you could take a look at this so we can fix this before the 9.5 release on Tuesday? I wonder if it may be related to the changed block name (`send-a-message/whatsapp-button` vs. just `whatsapp-button` now) and how we try to enqueue styles for the block:
https://github.com/Automattic/jetpack/blob/96c05f153090eb012a38078002f2e811dd36eb7f/projects/plugins/jetpack/extensions/blocks/send-a-message/whatsapp-button/whatsapp-button.php#L42

Thank you!
