### ISSUE TITLE
Photon: disable intermediate image sizes not working

### ISSUE THREAD

**Issue by eduardogoncalves** [Automattic/jetpack#18956]
As we're using Photon to optimize and serve our images, we don't need to have intermediate image sizes generated.

![image](https://user-images.githubusercontent.com/4308648/109419734-4fc7f000-79a5-11eb-80e2-49af8021f288.png)

I filled an issue at https://github.com/Automattic/newspack-theme/issues/1262 and @laurelfulford  pointed that Jetpack had this feature https://github.com/Automattic/jetpack/pull/11287

#### Steps to reproduce the issue

1. To enable the noresize, add this filter to Twenty Twenty-One's functions.php: `add_filter( 'jetpack_photon_noresize_mode', '__return_true' );`

![image](https://user-images.githubusercontent.com/4308648/109419761-70904580-79a5-11eb-9254-9ecb4d5b8b97.png)

2. Enable the Twenty Twenty-One theme
![image](https://user-images.githubusercontent.com/4308648/109419787-8c93e700-79a5-11eb-8368-02f8035fc131.png)

3. Upload a sample image
4. Go to upload's folder on file explorer, it's generating intermediate image sizes.

#### What I expected
I expected to see only the uploaded file.

#### What happened instead
It still generates all intermediate image sizes
![image](https://user-images.githubusercontent.com/4308648/109419941-55720580-79a6-11eb-8a78-eff2ff065f4c.png)

**Comment by jeherve** [comment]
cc @zinigor, who may be familiar with the filter and its current implementation on WoA.

**Comment by zinigor** [comment]
I have tried reproducing the problem on my test site just now, and I don't see any additional sizes generated. The image gets uploaded, appears once in the uploads folder, and correctly uses srcset URLs with Photon arguments. Are you sure this is caused by the theme? Maybe this is something related to other plugins? I'm happy to help debug this if needed.

**Comment by eduardogoncalves** [comment]
I disabled all plugins, except Jetpack, LiteSpeed Cache and Regenerate Thumbnails, than the thumbnail sizes registered drop to 7
![image](https://user-images.githubusercontent.com/4308648/109843117-1e5b5880-7c21-11eb-84d6-d375e536db25.png)

But when I upload some imagem, it's generating intermediate sizes
![image](https://user-images.githubusercontent.com/4308648/109842385-675edd00-7c20-11eb-9f98-2959ab611279.png)

**Comment by zinigor** [comment]
Thanks for the extra details! I was able to reproduce the problem - at first it wasn't working for me in the same setup, but then I decided to try to place the `add_filter` statement to the same position in the code where you had it. Bingo, it turns out that having it in the `functions.php` file of the theme is either too late in the execution, or is entirely off the path of the upload. I don't know which reason it is, but it makes sense to avoid loading themes when all you need is to upload an image. Do you have another place where you can put the `add_filter` snippet?

**Comment by eduardogoncalves** [comment]
Hello @zinigor where is the recommend place to have this filter enabled?

Btw, is it possible to add a toggle under 'speed up image load times' to 'disable intermediate image sizes generation'?

Thanks a million!

**Comment by zinigor** [comment]
Whoops, sorry it took me a while to get back to you! As for a recommended place, I would say any plugin code that you have access to will do, maybe even an mu-plugin that you have installed somewhere. I wouldn't recommend editing WordPress code though, so it's either some plugin code that you have control over, or any "WordPress Code Snippet" plugin out there that can do it for you.

As for the toggle - it's a good idea, thank you! I don't know when we'll be able to do it though, no one is currently working on the Accelerator UI.

**Comment by eduardogoncalves** [comment]
Thanks @zinigor 
It worked adding the filter to a plugin
