### ISSUE TITLE
perform_security_reporting() writes to db even if Protect module is disabled

### ISSUE THREAD

**Issue by borekb** [Automattic/jetpack#1898]
With the new 3.4 release, JetPack now writes to its options storage every 15 minutes even if the *Protect* module is disabled, see https://github.com/Automattic/jetpack/blob/5bd1b10a5dba2570d962091c7f62be3b9796040c/class.jetpack.php#L1270. This is a problem for VersionPress or any other plugin that tries to do database change tracking as a new change is generated every 15 minutes when it shouldn't.

**Comment by samhotchkiss** [comment]
Hi there @borekb-- 

This is unrelated to Protect, but is laying the groundwork so that third party plugins can report what steps they're taking to help secure your site so that we can help users understand their security.

If we were to move storage to a transient, would that alleviate the VersionPress issues?  I'm not familiar, as I haven't used it.

**Comment by borekb** [comment]
@samhotchkiss Thanks for the explanation, Sam. Transients would greatly help as VersionPress ignores them by default.
