### ISSUE TITLE
CI: Check for an outdated yarn.lock

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#19027]
We already check for an outdated composer.lock file. We should check for an outdated yarn.lock file at least in the monorepo root.

@anomiex - would you be game to expand the composer.json check?

**Comment by anomiex** [comment]
I have no objection in principle.

The main purpose of the composer.lock check is to make sure that dependencies within the monorepo are updated, e.g. if jetpack-autoloader changes then Jetpack's composer.lock gets updated to include it.

We specifically avoid detecting a situation like how changelogger depends on symfony/console "^3.4 | ^5.2", Jetpack's composer.lock locks to 5.2.3, but 5.2.4 is available. That's something that should be done occasionally by something like renovate rather than being a random requirement on whichever PR of ours happens to be created just after Symfony pushes that new version.

The composer command we use handles this by only trying to update direct dependencies while leaving indirect dependencies alone, combined with the fact that we only check in composer.lock in cases where all external direct dependencies are using a specific version (e.g. Jetpack, but not changelogger).

I'm not too familiar with how yarn works, and perhaps others are. Before I start trying to figure it out for myself, does anyone already know of a yarn command that would do an equivalent check?
