### ISSUE TITLE
Twitter meta: remove the @jetpack default value for twitter:site

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#1908]
Twitter is now automatically whitelisting sites for most Twitter cards: https://href.li/?https://twittercommunity.com/t/automatic-cards-whitelisting/34207

We should remove the default value of @jetpack for the twitter:site meta tag, as it now shows up for every tweet that links to a site that has Jetpack activated, unless they changed the value in Settings -> Sharing. It's not a required value, as far as I can tell.

**Comment by jeherve** [comment]
It seems to be confusing for a lot of people, and even spammy since Jetpack appears in tweets that aren't related to Jetpack at all. Here are a few examples of the feedback we go in the past few days:

https://twitter.com/rhettsoveran/status/583667097550487552
https://twitter.com/bovibe/status/583529054671896576
https://twitter.com/coreyholms/status/583294444985683968
https://twitter.com/splorp/status/583311095110057984
https://twitter.com/SupportPets/status/583024804120436736
https://twitter.com/sydneypadua/status/582225500933885952
https://twitter.com/sydneypadua/status/582557212977004545

**Comment by jkudish** [comment]
Patch looks good @jeherve
