### ISSUE TITLE
Actions: avoid duplicate Gardening comments 

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#19099]
When creating a new PR, you often end up triggering [the Gardening task that check the PR description twice](https://github.com/Automattic/jetpack/blob/12a6d0d94eed577940707653ecd3b74f898c028c/.github/actions/repo-gardening/src/index.js#L33-L37):
- Once when the `pull_request` is opened.
- Once when the `pull_request` is labeled (even though you most likely added the labels as you created the PR).

As a result, the 2 actions run concurrently, and 2 comments are created because when each task checks for an existing comment, they do not find one yet.
See the example below, triggered when I created a Pull Request (I had added some labels before I submitted my pull request):

- Pull request opened: `Tue, 09 Mar 2021 13:29:02 GMT main: Received event = 'pull_request', action = 'opened'` -- https://github.com/Automattic/jetpack/runs/2066899454?check_suite_focus=true
- Pull request labeled: `Tue, 09 Mar 2021 13:29:02 GMT
main: Received event = 'pull_request', action = 'labeled'` -- https://github.com/Automattic/jetpack/runs/2066899578?check_suite_focus=true

We need the task to be triggered when we open PRs, and we also need it to be triggered when we label PRs, so we can't get rid of one of the triggers.

But somehow, we should be able to either:
1. Check for existing runs of the same action and wait until they complete.
2. Cancel duplicate runs. I don't think this would be a good option here as we don't want to accidentally cancel a run that's checking something else in the Gardening action:
https://github.com/Automattic/jetpack/blob/12a6d0d94eed577940707653ecd3b74f898c028c/.github/actions/repo-gardening/src/index.js#L19-L37

I'm not quite sure how to go about that yet. I wonder if I would be able to rely on https://github.com/actions/toolkit/pull/149.

**Comment by anomiex** [comment]
In case it helps, we already have [cancel-dups.yml](https://github.com/Automattic/jetpack/blob/master/.github/workflows/cancel-dups.yml) that cancels duplicate runs of some other workflows, and [this bit in build.yml](https://github.com/Automattic/jetpack/blob/3e7719770c8cbe053c8728f00b830bff5d4343f3/.github/workflows/build.yml#L188-L191) that tries to avoid concurrent runs of a critical section.

I don't think the saveState/getState will help here, as those share information between an action's "pre", "main", and "post" steps within in a job run, rather than across workflow runs.
