### ISSUE TITLE
Publicize: Fallback to excerpt and feature image for Tumblr

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#19107]
#### Is your feature request related to a problem? Please describe.
When the post content is empty, but there is a featured image and/or an excerpt, the published post on Tumblr is virtually empty.

#### Describe the solution you'd like
If there is no post content, but alternative sources (excerpt, featured image), use them.

#### Describe alternatives you've considered
Not using Publicize+Tumblr.

#### Additional context
Requested as part of https://wordpress.org/support/topic/publicize-not-posting-image-to-tumblr-2/

@zinigor @fgiannar - I know y'all looked at this back in November when moving to the Neue Post Format. I don't think it would be terribly hard to implement but would appreciate your thoughts.

**Comment by fgiannar** [comment]
Did an initial investigation and it seems that the issue lies in the "Advanced Custom Fields" plugin used to create the posts.

Without using it, posts without post content, but alternative sources (excerpt, feature image) are successfully posted in Tumblr.

I'll dig a bit more to try and fix this, aiming for consistency since the same posts are successfully published in Facebook and Twitter.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
