### ISSUE TITLE
Repo Gardening: Help incomplete PRs become compliant

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#19127]
#### Steps to reproduce the issue

1. See https://github.com/Automattic/jetpack/pull/19119
2. I presume if the PR is lacking a proper template, it'll change the label to "Needs Author Reply".
3. Change it to "Needs Review"

#### What I expected

A manual "override" back to Needs Review should stick.

#### What happened instead
No way to mark it ready for review.

I'll note that github action comment says that if the things I'm lacking aren't needed, I can explain why. From that, I would think that we expected to be able to override it in some way.

If our intent is to force these fields to be filled out without exception, what's the workflow for a PR like above to get into compliance? Start a new PR and copy/paste the template items we're missing?

**Screenshots**

**Comment by jeherve** [comment]
I think it would be nice if we could indeed help folks fix the issue, rather than offering them an override. I suppose we could offer both, but I would rather have folks fill in the missing data. How can we make that easier, short of copying and pasting? Do you have any ideas? Should we include the missing sections in the comment, in a code snippet?

**Comment by kraftbj** [comment]
I think adding what is needed for compliance in the comment would be a nice touch. I'm not sure how else to do it that would be as/more elegant. 

Maybe we should edit the comment on the template that all sections are required to be there?

I was a bit... bossy... with the fusion PR, chopping off good chunks of what `build-pr.php` gave me since I didn't think it relevant. 😬
