### ISSUE TITLE
Changelogger: add to jetpack cli

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#19120]
#### Steps to reproduce the issue

1. From the repo root, run `projects/plugins/jetpack/vendor/bin/changelogger add`
2. Follow the prompts.

#### What I expected

A changelog file is added to `projects/plugins/jetpack/changelog/`

#### What happened instead
A changelog file is added to `changelog/` instead.

**Screenshots**

**Comment by anomiex** [comment]
That's a feature, not a bug. 😉 Particularly with the possibility of global installs, and things getting symlinked all over the place within the monorepo, it'd be somewhat difficult to always do the right thing if we tried to run relative to changelogger's path rather than the current directory.

And we also specifically take advantage of `/path/to/jetpack-monorepo/projects/packages/changelogger/bin/changelogger add` working with the current directory instead of `/path/to/jetpack-monorepo/projects/packages/changelogger/` in a lot of the CI and build scripts to avoid having to do a relatively slow `composer install` everywhere.

Best thing to do would be to just cd into the right directory, e.g. `(cd projects/plugins/jetpack && vendor/bin/changelogger add)` if nothing else.

You can also do `COMPOSER=projects/plugins/jetpack/composer.json projects/plugins/jetpack/vendor/bin/changelogger add`, since all the paths are defined as being relative to the used `composer.json`.

Or I suppose we could copy composer's `--working-dir` option if neither of those workarounds are sufficient.

**Comment by kraftbj** [comment]
That makes sense. I'm thinking by using the monorepo CLI as a front, we could resolve my "issue", making it easier IMO to use, while still totally respecting the need for how it is currently written.
