### ISSUE TITLE
Improving Twitter Widget conformance to W3C's HTML definitions 

### ISSUE THREAD

**Issue by AntonioGiovanniSchiavone** [Automattic/jetpack#1917]
Hello,

I was validating my web site with the official W3C's Markup Validation Service  (http://validator.w3.org/) and i noticed a that a couple of errors are generated by your Twitter Widget. 

In particular, the html code generated by the widget is something similar to:

            <li id="twitter_timeline-2" class="widget widget_twitter_timeline">
            <h3 class="widgettitle">Twitter:</h3>
            <a class="twitter-timeline" data-widget-id="519280815012737025" data-theme="light" data-link-color="#f96e5b" data-border-color="#e8e8e8" data-tweet-limit="4" width="325" height="400" lang="EN">My Tweet</a></li>

The <a> tag is subsequently transformed into a <iframe> section. The errors stems from the fact that, according to the HTML specifications , the <a> tag  should not have the attributes width and height (http://www.w3schools.com/tags/tag_a.asp). 

Since all the "data-* Attributes" are freely customizable and legal (http://www.w3schools.com/tags/att_global_data.asp) I suggest to change those attributes into "data-twitter-timeline-width" and "data-twitter-timeline-height".

**Comment by jeherve** [comment]
> according to the HTML specifications , the tag should not have the attributes width and height 

We've had to use these attributes because that's what Twitter requires when building an embedded Twitter Timeline:
https://dev.twitter.com/web/embedded-timelines#dimensions

If we were to use data attributes instead, Twitter wouldn't recognize these attributes and ignore them.

Other developers have already reported the issue to Twitter, but you could add your vote to [this thread](https://twittercommunity.com/t/embedded-timeline-attribute-not-html5-compliant/19756) to let Twitter developers know this is still an issue.
