### ISSUE TITLE
Sharing: add Reddit sharing counts

### ISSUE THREAD

**Issue by jenhooks** [Automattic/jetpack#1932]
If possible, add share counts to the Reddit icon in Sharedaddy. 

Facebook, Twitter, and LinkedIn have their own custom sharing counts:

https://github.com/Automattic/Jetpack/blob/master/modules/sharedaddy/sharing.js#L7

Requested in 2153079-t

**Comment by jkudish** [comment]
So reddit doesn't really have a concept of share counts, it has "points" which are up/down votes. The "official" button already supports that. 

We won't add support for the other button styles, chiefly because it'd be a complex integration both from a technical point of view and a user point of view because of how reddit works... Anyone can create a new thread to share a URL and there's no way to combine those. Additionally it's not really a share count but rather an up/down vote.

Leaving this as-is.
