### ISSUE TITLE
Payments / Mailchimp block: improve loading state

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#19390]
Both blocks currently display a simple loading spinner when data is loading. This could be improved so the spinner is better centered.

![screenshot-2021-04-01-at-19 36 05](https://user-images.githubusercontent.com/426388/113412597-fe9e8800-93b8-11eb-9fea-3c5ddd454ff5.png)

Original report:
p8oabR-DS-p2#comment-5130

**Comment by rcrdortiz** [comment]
Note: These blocks don't share a common component that displays the Spinner. Each of these blocks uses a composition of the Placeholder and Spinner components. 
Maybe we could also add the name of the Block beside the icon, for example:
````
<Placeholder icon={ icon } label={ __( 'Payments', 'jetpack' ) } notices={ notices }>
	<div class="class that centers content">
            <Spinner />
        </div>
</Placeholder>
````
Ideally, we should create a new component for this instead of copying and pasting the solution to N blocks.

**Comment by lukaszwilczakwilnet** [comment]
PR: https://github.com/Automattic/jetpack/pull/24694
