### ISSUE TITLE
Site Editor Compatibility: Podcast Player block issues in editor and front end views

### ISSUE THREAD

**Issue by andrewserong** [Automattic/jetpack#19483]
In the new site editor in Gutenberg (`/wp-admin/admin.php?page=gutenberg-edit-site`), there are some issues with the Podcast Player block within the editor and on the front end of the site. The issues include:

* Within the editor, the styling and behaviour for the player doesn't appear to be rendering (perhaps an issue with how the block works with the site editor iframe?)
* On the front end of the site, the player itself isn't being rendered / loaded

#### Steps to reproduce the issue

1. Grab an RSS feed from your favourite podcast (here's one for Distributed.blog: https://distributed.blog/category/podcast/feed/)
2. With the Gutenberg plugin active (>=10.4.0-rc1), activate a block-ready theme (like tt1-blocks)
3. In the site editor, insert a Podcast Player block into the Footer template part
4. Add the feed URL from your favourite podcast and click embed
5. Observe that the player isn't rendered correctly.
6. Save the template part and view the front end of your site
7. Observe that the podcast player interface isn't loaded / rendered

#### What I expected
* The player to be available within the editor canvas and to be styled correctly.
* The player to be available on the front end of the site

| Editor view | Front end view |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/14988353/114123496-c1e10c80-9935-11eb-83cf-28cd6272797e.png) | ![image](https://user-images.githubusercontent.com/14988353/114123537-d7563680-9935-11eb-95ef-d0f1eced88c5.png) |

#### What happened instead
* The player is not available within the editor canvas
* The player was not rendered on the front end of the site

| Editor view | Front end view (note missing player) |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/14988353/114123398-90684100-9935-11eb-8695-3003c997b53e.png) | ![image](https://user-images.githubusercontent.com/14988353/114123416-9b22d600-9935-11eb-8ee6-664c78938bc9.png) |

**Comment by ramonjd** [comment]
It looks like [podcast player enqueues assets](https://github.com/Automattic/jetpack/blob/26db3e436ccca3e16a62d02d95e792a81f38a1e4/projects/plugins/jetpack/extensions/blocks/podcast-player/podcast-player.php#L209) from the mediaelement core lib: https://github.com/WordPress/WordPress/tree/master/wp-includes/js/mediaelement

So we're going to need a way to ensure all block dependencies can be copied into the site editor context. 

I'm starting to think core should be offering a solution to this.

**Comment by sdixon194** [comment]
I just did some more testing in preparation for the 9.9 release, but it looks like this issue is happening for me again 🤔 @ramonjd would you be able to take another look?

**Comment by ramonjd** [comment]
> I just did some more testing in preparation for the 9.9 release, but it looks like this issue is happening for me again 🤔 @ramonjd would you be able to take another look?

Thanks for the ping @sdixon194 

Could you fill me in on how you tested this?

I just checked with release candidate (9.8.1-918672803-g67226f6) and bleeding edge (9.9-alpha-974918035-gf25064c), and embedding the podcast player block works as expected on the site editor and frontend end (using Gutenberg 10.9.1)

<img width="1526" alt="Screen Shot 2021-06-28 at 12 42 37 pm" src="https://user-images.githubusercontent.com/6458278/123571792-5577fa00-d80e-11eb-87ee-aaa16aa8fb70.png">

**Comment by ramonjd** [comment]
As far as I can tell, the Site Editor in WPCOM is no longer loading `mediaelement-css` and `wp-mediaelement-css`, which are required for the podcast player to function correctly. I'm not yet sure when or how this changed as we tested in WPCOM at the time and it was working. 

My only guess is that it's due to a Gutenberg change, but I can't be sure. Still looking...

**Comment by ramonjd** [comment]
Okay, I think it's because we haven't implemented the changes required by https://github.com/WordPress/gutenberg/pull/31873, which was merged after our changes.


We need to add `'style'           => 'wp-mediaelement',` to the [register_block](https://github.com/Automattic/jetpack/blob/26db3e436ccca3e16a62d02d95e792a81f38a1e4/projects/plugins/jetpack/extensions/blocks/podcast-player/podcast-player.php#L27) function.

Now it works

<img width="568" alt="Screen Shot 2021-06-28 at 2 43 16 pm" src="https://user-images.githubusercontent.com/6458278/123581400-2e75f400-d81f-11eb-9fc9-9e0abfc8040f.png">

cc @glendaviesnz for sanity check

**Comment by sdixon194** [comment]
Brilliant, nice sleuthing and thanks for the quick fix!
