### ISSUE TITLE
Media placeholder interfering with alignment in gutenberg `cover` block

### ISSUE THREAD

**Issue by roo2** [Automattic/jetpack#19488]
### Interaction with the cover block's drag and drop zone
The `paid-block-media-placeholder` element in [paid-blocks](https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/extensions/extended-blocks/paid-blocks/media-placeholder.js#L56) automatically wraps the `components-drop-zone` drag and drop zone.

see the [original bug report in calypso](https://github.com/Automattic/wp-calypso/issues/51670)

see also slack discussion p1617898513140100-slack-CBTN58FTJ

### Should the placeholder even be added?
I'm not sure if it's correct for the the paid block placeholder to even be added to the DOM in this case? It isn't visible to the user.

### the width of the placeholder is interfering with alignment of the cover block's contents
In this image, the paragraph should be center aligned. See [original issue](https://github.com/Automattic/wp-calypso/issues/51670)
![113503749-65987a00-953c-11eb-9f50-e2434e608399](https://user-images.githubusercontent.com/22446385/114147207-d2a47900-995b-11eb-8e56-6ddac306978d.png)

The paid block placeholder [uses width: 100%](https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/extensions/extended-blocks/paid-blocks/media-placeholder.js#L56) which causes other contents of the cover block to be misaligned
Might in be appropriate to change this css?

**Comment by ciampo** [comment]
The issue seems to be caused by the fact that the `paid-block-media-placeholder` element becomes an unexpected flex-child of its parent — without it, the `components-drop-zone` element would not be a flex-child since it has `position: absolute` set on it.

To make matters complicated, it looks like the `paid-block-media-placeholder`  needs to be at 100% width and with a implicit value of `display: block` in order for the cover block to be displayed properly when an image hasn't been picked yet:


https://user-images.githubusercontent.com/1083581/114154610-e088d880-9920-11eb-859b-6275b5bca51d.mp4


One potential solution that comes to mind is to use `display: contents`, but the browser support isn't great (see [MDN page](https://developer.mozilla.org/en-US/docs/Web/CSS/display))

This will require more investigation into all the places/cases this element is used, in order to find a good solution while avoiding regressions

**Comment by ciampo** [comment]
Tentative hotfix: https://github.com/Automattic/jetpack/pull/19489

This should still require investigation to find out what's the best way to deal with this bug
