### ISSUE TITLE
Markdown should set wpautop() second parameter to false for documented behavior

### ISSUE THREAD

**Issue by benyakov** [Automattic/jetpack#1965]
(Originally posted on WordPress Jetpack forum)

When writing in Markdown, it is expected that the writer may
use the -nix line convention, breaking lines manually within
paragraphs. This is supported and facilitated by browser
add-ons like Vimperator, which can take a textbox and link
it to an instance of Vim, where the editing can take place
more naturally than in a web browser, and with the full
convenience of a text editor. This paragraph is an example.

Markdown writers may also use the old word processing convention of extending lines to the end of the paragraph (as I'm doing here), but this is undesirable in a line-based environment like a traditional text editor, and less than optimal if the content will be managed in a system that uses line-based change tracking, like Git.

Jetpack's Markdown plugin makes use of the wpautop()
function, which makes sense for paragraph breaks. But that
function also inserts HTML line breaks within paragraphs
when it encounters a line break character. Providentially,
wpautop also allows a second parameter for disabling the
insertion of &lt;br&gt; where there are not two line
breaks in a row. As far as I can tell, WordPress is not
making use of this anywhere, but it makes perfect sense for
Markdown. Writers using the -nix convention would avoid
having to tinker in the source of WordPress, and writers
using the word processor convention would find that their
Markdown code is behaving as the documentation says it
should. Markdown should be the flavor specified in the
documentation anyway, without special undocumented
additions.

Jeremy Herve wondered about existing Markdown already
published with Jetpack Markdown. I can think of two ways to
handle it. There may be others.

1. The easier and maybe preferable way would be to simply
   make the change. Existing Markdown will very likely not
   be making any intentional use of this "undocumented
   feature" of Markdown found only in WordPress Jetpack,
   because the authors have intentionally chosen to write in
   Markdown *instead of* any kind of WordPress native
   system. The documented Markdown behavior makes a
   difference only for those who use the -nix line
   convention and expect Markdown support for it.

2. A configuration option could be added to the post edit
   page for enabling or disabling "Jetpack-enhanced"
   Markdown on a post-by-post basis.

3. I suppose a third option would be to write a filter that
   could be used to transform existing Markdown as needed,
   removing in-paragraph line breaks automatically. This
   would be for those (hopefully rare) cases where the
   change makes any difference to existing Markdown.

**Comment by mattwiebe** [comment]
Thanks for the report! The default, expected behaviour for WP (newline = linebreak) and Markdown (newline ≠ linebreak except with a trailing space) are indeed different.

It's unlikely that I want to change this, for the simple fact that `wpautop` is applied as a filter on `the_content`, which is applied to all posts and pages in WP at runtime. Changing the default behaviour would change the display of some existing content, which would be a rude surprise for many of our users and basically a non-starter.

And, even if we remove the filter and put in a new filter to leverage `wpautop` with the 2nd param as `false`, we also don't solve the issue of the Markdown spec allowing for a newline with a trailing period. And making it an option is interface bloat for something that almost nobody cares about.

So, we're now outside of the territory where this can be good for Jetpack. But, if you want to put in a small bit of code on your own site, and you don't really care about linebreaks on a trailing space, you could do something like:

```php
remove_filter( 'the_content', 'wpautop' );
function wpautop_no_linebreaks( $content ) {
  $content = wpautop( $content, false );
  // maybe try to deal with trailing spaced newlines?
  return $content;
}
```

**Comment by snarfed** [comment]
i wanted to migrate from Michel Fortin's unmaintained markdown plugin to Jetpack Markdown, and meaningful newlines in a somewhat big collection of existing posts was the biggest stumbling block. i got much of the way through converting the post content itself before i found this, but i like the convenience of non-meaningful newlines for editing enough that i'm switching to this tweak and dropping the conversion. thanks @mattwiebe!

also, fwiw, Jetpack Markdown evidently handles trailing space newlines now, so the snippet above is enough!
