### ISSUE TITLE
"Found n Results" only counts first page of results

### ISSUE THREAD

**Issue by iandunn** [Automattic/jetpack#19656]
#### Steps to reproduce the issue

1. Start a search, e.g., https://jetpack.com/?s=backup
2. At first `jetpack-instant-search__search-results-title` will say `Found 10 results`
3. Scroll down to infinitely load the next page of results, and it will update to say `Found 20 results`

#### What I expected

The total number of results, regardless of how many are displayed on the current page. 

#### What happened instead

The count only includes results that have been loaded onto the page.

In my experience, that's not consistent w/ what search engines typically do. Seeing `10` made me think that there were _only_ 10 results.

In some cases, that could be confusing or misleading. e.g., if someone expects to see a couple dozen results, they may think that they searched for the wrong term and start trying others instead of scrolling to see all the results.

**Comment by robfelty** [comment]
This looks to be a front-end issue. The API returns a "total" key, which should probably used to show the number of results.

**Comment by keoshi** [comment]
I'm on support rotation this week and have been seeing this issue on a few sites (including my own, which I've only noticed now).

**Comment by tiagonoronha** [comment]
One of our partners on 51 reported this as well.

It looks like this issue was introduced on this PR: https://github.com/Automattic/jetpack/pull/19428

Relevant code: https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/modules/search/instant-search/store/reducer/api.js#L71-L76

Removing that conditional statement fixes the issue, but probably it breaks what the PR above tried to fix.

cc @jsnmoon

**Comment by jsnmoon** [comment]
The original rationale for the fix was to temporarily handle an API bug where paginating to the next page could return a completely empty API response when the site is configured to [exclude post types](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/modules/search/instant-search/lib/api.js#L160) (initial report: p8oabR-DS-p2#comment-5144).

I'm no longer able to reproduce the API bug, so I'll go ahead and prioritize spinning up a small revert for this.

@robfelty: Have there been any changes to the pagination code in the API since early April?

**Comment by robfelty** [comment]
> @robfelty: Have there been any changes to the pagination code in the API since early April? Also, I noticed search API requests return smaller `total` values upon each page advancement (e.g. page 1 response has `total` of 18, page 2 response has a `total` of 8). If this is intentional, would it be possible to alter the total value to always return the correct total result count (e.g. both page 1 and 2 responses would have a `total` of 18)?

Yes, we deployed a change on May 3rd to prevent duplicate results during pagination in some cases. I will look into the decreasing total issue, to see if that stems from that change.

**Comment by jsnmoon** [comment]
This has now been fixed! It's live for WPCOM and will be live for Jetpack with the 9.9 release.
