### ISSUE TITLE
Instant Search: remove or reduce modal animation

### ISSUE THREAD

**Issue by bluefuton** [Automattic/jetpack#19836]
#### Is your feature request related to a problem? Please describe.
@pablohoneyhoney reports in https://github.com/Automattic/jetpack/pull/19251#issuecomment-838645044:

> 
> It would be neat if we enhance the animation that happens currently with the Search modal (sliding up from the bottom) to be simpler as a quick fade or even remove it all together. The animation itself delays the action (it’s fairly slow), and it doesn’t look good either. There are other particular cases like this P2 on a non P2020 5dIxE-p2 with an open field where the Search behavior (when you start typing) and the look (styles on the close ad clear UI) aren’t ideal. While this case is running on an older theme, Lighthouse is considering the open field as a resting search UI that would likely create a similar fractured flow.

#### Describe the solution you'd like
The modal animation should be a quick fade or even removed all together.

#### Additional context
@pablohoneyhoney started a Slack conversation about this in p1620744989134600-slack-jetpack-search-team. @p3ob7o  added: "I agree on the animation, it’s quite jarring. I’d love a quick fade as Pablo suggested."

**Comment by evilluendas** [comment]
In case it's useful, we use a quick "bounce" animation for some modals in P2: 

https://user-images.githubusercontent.com/820374/118655826-d2f92500-b7e1-11eb-831d-e59822a5afde.mov

This is the animation:

https://github.com/Automattic/p2/blob/master/plugins/p2/src/client/shared/components/p2-modal/style.scss#L63

And these are the parameters:

https://github.com/Automattic/p2/blob/master/plugins/p2/src/client/shared/components/p2-modal/style.scss#L9

Since the search modal is quite big, it may still feel a bit jarring. If that's the case I recommend we just remove the animation altogether and let it open instantly — it may feel a bit less refined than an animated fade, but definitely snappier!

**Comment by evilluendas** [comment]
In case it's useful, we use a quick "bounce" animation for some modals in P2: 

https://user-images.githubusercontent.com/820374/118655826-d2f92500-b7e1-11eb-831d-e59822a5afde.mov

This is the animation:

```
@keyframes dialog-pop {	
	0% {
		opacity: 0;
		transform: scale(0.9);	}
	50% {
		opacity: 1;
		transform: scale(1.01);
	}
	100% {
		opacity: 1;
		transform: scale(1);
	}
}
```

And these are the parameters:

```
transition: opacity 0.2s ease-in;
animation-name: dialog-pop;
animation-duration: 0.3s;
animation-timing-function: cubic-bezier(0.455, 0.03, 0.515, 0.955);
transform-origin: center center;
```

Since the search modal is quite big, it may still feel a bit jarring. If that's the case I recommend we just remove the animation altogether and let it open instantly — it may feel a bit less refined than an animated fade, but definitely snappier!

**Comment by bluefuton** [comment]
Thanks for taking the time to provide those details @evilluendas! We'll give the fade a try and see how it feels 👍

**Comment by pablohoneyhoney** [comment]
Nice! 

I'd try even faster, less obvious of a bounce. It's ok in a single use, but any animation can become distracting in repetitive tasks.

**Comment by bluefuton** [comment]
I've done some experimenting and I think I'm in favour of dropping the animation and using a simple, short opacity transition (like the `transition: opacity 0.2s ease-in;` @evilluendas mentions above). I'll spin up a PR so we can try it out.
