### ISSUE TITLE
Story Block: navigation feedback

### ISSUE THREAD

**Issue by samiff** [Automattic/jetpack#19949]
This is some feedback from testing of the Story Block on web.

**On keyboard navigation:**

> I expected “Enter” to open the story, but Just “Spacebar” did.

> when I had tabbed to the story I naturally pressed “Enter” instead of “space”. The space bar is normally the way to start/stop media players

**On mobile navigation patterns/expectations:**

> on iOS works well, but when I try to “hold the screen to pause” (the most common pattern on mobile to pause stories) it instead selects everything and doesn’t pause.

> When using it on the desktop and you’re viewing the last portion on the story you can press the right button and skip it and mark the story as viewed. On mobile you can’t tap the right of the screen to skip the last item, this is particularly annoying if the last item is a long video.

#### Additional context

* Internal: p8oabR-FS-p2
* cc: @Tug

**Comment by kallehauge** [comment]
>when I had tabbed to the story I naturally pressed “Enter” instead of “space”. The space bar is normally the way to start/stop media players

I think it's because I normally tap to an element and then press "Enter" to interact with it (submit buttons or similar) but when I play/pause videos on YouTube or elsewhere I am never in doubt about using space. So in isolation it seems a bit weird using "Enter" to play but in the context as a normal "power user" of browser it just had to pause a think for a second because Enter didn't work.

**Comment by Tug** [comment]
Thanks @samiff that's great feedback. I'll do both of the mobile patterns/expectations as they impact all mobile users.

Concerning keyboard navigation, I guess we could use both enter and space to play (and go fullscreen) since this is an action that does 2 things. This is less of a priority imo.
