### ISSUE TITLE
Related Posts: cannot dequeue script and style anymore

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#20039]
This issue was introduced in #19615. 

It was previously possible for one to dequeue both the JavaScript and the CSS files from Related Posts, to load your own instead, using both the `jetpack_implode_frontend_css` filter as well as `wp_dequeue_style`.

It doesn't appear to be possible anymore, as reported in https://github.com/Automattic/jetpack/issues/18736#issuecomment-856451444

> It is no longer working.
> 
> `wp_dequeue_script( 'jetpack_related-posts' );`
>
> I can still enqueue my own script, but the default script is also getting added, no matter what priority I use. Any idea why?
-- @MuhammedSwalihct

**Comment by MuhammedSwalihct** [comment]
@jeherve The issue is still not fixed if I am correct. There have been multiple releases recently and I am stuck with using 9.7.1 because of this issue. If I update, I will lose the customizations. So, can you please add this issue to the next milestone? Being not able to dequeue scripts is a pretty serious bug that denies one of the core features of WordPress.

**Comment by jeherve** [comment]
> The issue is still not fixed if I am correct.

That's correct, we haven't looked at it yet. We'll update this issue as soon as we make progress with this.

@stacimc Do you think you could take a look when you get the chance? The change was introduced in #19615.

Thank you!
