### ISSUE TITLE
Carousel: caption is not displayed in modal anymore

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#20295]
In Jetpack 9.8.1, when using the Carousel feature, the Carousel view displayed 3 different types of information:
- The image title
- The image description
- The image's description

![image](https://user-images.githubusercontent.com/426388/124767947-88ba3780-df38-11eb-9f28-095a8285ca79.png)

In Jetpack 9.9, following the changes in #20107, only 2 types of information are displayed:

- The image title
- The image description

<img width="751" alt="Screenshot 2021-07-07 at 15 29 58" src="https://user-images.githubusercontent.com/426388/124767976-8f48af00-df38-11eb-9197-68ff3df491f3.png">

That's problematic for the folks who were previously using captions to display important information. Since we're also displaying the same info twice, we should be able to revert to the previous behaviour.

********

Internal references:
- p1625660123167900-slack-C0CMN0V97
- 4122177-zen

**Comment by antermoia** [comment]
On the sites that I manage, the caption is always the place where I put extra information, in particular because it is also used and shown in the thumbnail grid and the various other gallery formats (example: [https://sdphotoclub.com/gallery/gallery-waves-photo-quest-june-2021/](https://sdphotoclub.com/gallery/gallery-waves-photo-quest-june-2021/)) so I would have a strong preference for the caption in the new Carousel.

**Comment by jeherve** [comment]
> I would have a strong preference for the caption in the new Carousel.

@antermoia We'll make that happen. We're working on a fix that we'll included in the next Jetpack release.

If you'd like, you could test the fix already, like so:

1. Upload, install, and activate [the Jetpack Beta plugin](https://jetpack.com/download-jetpack-beta/).
2. Go to Jetpack > Beta
3. There, search for the `fix/caption-in-carousel` branch and activate that.

The only thing to keep in mind is to revert to using Jetpack Stable later. :)

**Comment by antermoia** [comment]
Thank you @jeherve I've installed the Beta plugin and activated that particular fix.

It's a little better, but the captions are getting truncated and never seem to utilize the full width of the screen. What's more, I can't seem to see them in full anywhere either.

Example: [https://www.alex-kunz.com/water-light-texture-reflection/](https://www.alex-kunz.com/water-light-texture-reflection/)

**Comment by jeherve** [comment]
Thanks for giving it a try and giving us feedback. I see you've even commented on the PR already, that's perfect!
https://github.com/Automattic/jetpack/pull/20300#issuecomment-876652945

**Comment by separatelyunited** [comment]
From #20300 it appears captions should show below the image in the carousel instead of the image title; however, today I was able to replicate an issue from a user who reported that no caption shows when using the gallery block (either below the image or in the information section). 
<img width="707" alt="Gallery" src="https://user-images.githubusercontent.com/30807174/126108276-1255c10a-bce4-485b-9ac9-f7da03ad6ffa.png">
<img width="1500" alt="Carousel no caption" src="https://user-images.githubusercontent.com/30807174/126108285-63acc5a6-2f6a-47d4-a9d3-3d043b5d90ad.png">

This user reported previously using classic block with a gallery so I test that as well and found that images in the carousel show image title and in the information section repeat title, then the description, then caption.

Example on my own test site here: https://premiumgetittested.wordpress.com/
https://premiumgetittested.wordpress.com/#jp-carousel-2305

**Comment by apeatling** [comment]
This hasn't yet merged on WordPress.com, it should happen sometime today.

**Comment by sdixon194** [comment]
Shipped to wpcom and outstanding issues should be resolved. Can re-open or open a new issue if something occurs again.

**Comment by DanFeather** [comment]
As of December 20, 2023, the caption is not displaying by default and the custom code provided (here and at Jetpack's support Happy Bot) does nothing to change that. AND instead of the Title being displayed in the preview (before clicking the "i-in-a-circle" icon), the first line of the caption is displayed.
![danfeather-jp-carousel-caption-in-title](https://github.com/Automattic/jetpack/assets/16339251/c2778066-fcdf-4808-85f6-a52fe745a27a)
![danfeather-jp-carousel-caption-provided-code](https://github.com/Automattic/jetpack/assets/16339251/58df8c84-f20a-42bc-ad22-4771bb944b3a)
