### ISSUE TITLE
Boost: Refactor Critical CSS Generation logic in the dependent outside library

### ISSUE THREAD

**Issue by davidlonjon** [Automattic/jetpack#20586]
**NOTE:** This issue does not really belong here but after a discussion with @thingalon, we decided to log it here rather than in the [Automattic/jetpack-boost-critical-css-gen](https://github.com/Automattic/jetpack-boost-critical-css-gen) so it does not get lost there (as there are no many activities in there and devs might not think to look there).

Critical CSS generation on the Jetpack Boost plugin depends solely on the [Automattic/jetpack-boost-critical-css-gen](https://github.com/Automattic/jetpack-boost-critical-css-gen) repository. 

In that repository the `lib/generate-critical-css.js` [module](https://github.com/Automattic/jetpack-boost-critical-css-gen/blob/trunk/lib/generate-critical-css.js) module has the core logic for the Critical CSS generation. However @thingalon and I have identified some areas of improvement particularly in the logic that capture errors.

If it does not feel right to have this issue here, we can port it back into its original repo.

**Comment by thingalon** [comment]
Adding some guidance for any developer who wants to tackle this:

The core of the problem is that the `generateCriticalCss` is doing too much in one place, and is confusing and difficult to follow as a result. It needs to be broken down into smaller pieces, each of which are clear, straightforward functions which deal with a smaller set of things.
