### ISSUE TITLE
Map: Block broken on live page

### ISSUE THREAD

**Issue by onny** [Automattic/jetpack#20591]
#### Steps to reproduce the issue

1. Creating a new page and insert a map block
![image](https://user-images.githubusercontent.com/757752/128541679-e57ac8ae-f6a4-4dbc-aa1b-891320a3c05d.png)
Displays and works fine. But unable to insert, remove or update token. Something is wrong :O
2. Preview page, map block is working fine
![image](https://user-images.githubusercontent.com/757752/128541858-47eadf3d-40d4-45c2-ac44-c12552d65680.png)
3. On the live published page the map block is missing:
![image](https://user-images.githubusercontent.com/757752/128541538-a57c4838-3a99-4f2e-acdc-f60d92630313.png)

We are using a hosted Wordpress.com instance with premium plan. We already contacted support and they said they were aware of the problem. So I opened this ticket to keep track on the issue.

Tested with:

- Jetpack 10.0
- Wordpress 5.8
- Latest Firefox / Chrome browsers.

Since it is a hosted Wordpress instance, I'm unable to dig deeper into this issue, for example purging jetpack database tables etc. There is no error in the JS console. 

#### What I expected
Map block should be rendered fine. I was able to enter api token in the first place but now it's not working anymore

#### What happened instead
Map block broken on live page, unable to insert access api token

**Comment by jeherve** [comment]
> But unable to insert, remove or update token. Something is wrong :O

That's indeed expected on your site. Since your site is hosted on the WordPress.com platform, you do not have to worry about an access token. WordPress.com provides one for you. I agree the UI is confusing though; we'll see about improving that.

> On the live published page the map block is missing:

That is a problem, and should not happen. Could you check for Javascript errors on the page, as explained here:
https://wordpress.org/support/article/using-your-browser-to-diagnose-javascript-errors/

Let me know what you find!

Alternatively, could you let me know the page URL or contact our support team again to ask them to add a private reference to this GitHub issue for you, so we can follow up on this?

Thank you!

**Comment by jeherve** [comment]
> I agree the UI is confusing though; we'll see about improving that.

I opened this issue to track that: #20593

**Comment by onny** [comment]
Thank you @jeherve. Unfortunately I didn't got a response yet from the support team. But I take a look again with Jetpack version 10.0.

Our site is not live yet but maybe you have access. I created a test page, added a map block and set the marker to a specific street. After publishing, when I open the site I see nothing :( https://zhochzwei.wpcomstaging.com/test/

I enabled script debugging an get this:
```
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <n>. See https://fb.me/react-warning-keys for more information.
    in ul react.js:401:32
Uncaught TypeError: a is null
    value https://c0.wp.com/p/jetpack/10.0/_inc/blocks/map/view.js:1
    React 19
    js https://c0.wp.com/p/jetpack/10.0/_inc/blocks/map/view.js:1
view.js:1:10854
The above error occurred in the <n> component:
    in n

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries. react-dom.js:19662:15
Uncaught (in promise) Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information.
    React 16
    js https://c0.wp.com/p/jetpack/10.0/_inc/blocks/map/view.js:1
react-dom.js:242:21
```
Fortunately this script error only appears if I have this block on this page, otherwise the output for "errors" is empty.

I couldn't find any Mysql entries related to the Jetpack map block because I thought I could maybe reset it somehow.
The map block already worked some time ago so it might be a regression or an other plugin interfering?

**Comment by jeherve** [comment]
> Our site is not live yet but maybe you have access.

I do not, I'm afraid. Though the errors you pasted above is helpful.

Do you happen to have other blocks on that page at the moment? I wonder if another element on the page would introduce a custom version of the React library that would conflict with Jetpack's Map block.

If you do not have any other blocks on the page, what happens when you switch to a different theme for a few minutes? If that fixes the issue, it may mean that the theme itself loads a custom version of that library.

Let me know what you find!

**Comment by onny** [comment]
Thank you @jeherve for the response.
It is only this single block and I tried to switch the theme, same issue :(

**Comment by onny** [comment]
Oh looks like it depends on WP Multilang. As soon as I disable it, the map block works again :O
