### ISSUE TITLE
Redirect old Jetpack Boost proxy Pagespeed requests to new codepath

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#20933]
Jetpack Boost originally backed onto a Google Cloud Functions Microservice to handle RUM gathering, Critical CSS generation and collecting Speed Scores. We proxied all requests via the WordPress.com API to keep it private and reuse the Jetpack API authentication system.

However, when we shipped Boost 1.0.0, we only included one feature which uses the Microservice - the Speed Scores.

So the Microservice was a glorified proxy for the PageSpeed API, and was extra bulk for us to maintain - and the extra steps in generating a PageSpeed score were giving users headaches.

So we simplified it. Now the WPCOM API triggers a Jetpack Job directly to run the PageSpeed API from WordPress.com, cutting out the Microservice.

But old versions of Jetpack Boost are still requesting PageSpeed scores via the Microservice, costing us a small amount of monthly fees - but worse than that - requiring us to maintain the PageSpeed API in the Microservice for as long as we support these users.

We need to do one of two things:

1. Decide to cut these users off and require them to upgrade Jetpack Boost, or
2. Update the old Jetpack Boost Microservice Proxy in the WPCOM API to redirect requests to the more modern codepath - generating PageSpeed scores without the Microservice.

We also need to:

1. Review what versions of Boost are installed in the wild, and
2. See which API-wrapper methods they use.

**Comment by eAdnan007** [comment]
Going through the old APIs, it seems like the older APIs are using a webhook strategy instead of polling for request completion. So, I don't think we can simply redirect to the newer APIs. So the new options are:
1. Decide to cut these users off and require them to upgrade Jetpack Boost (still viable).
2. Add support for the webhooks in jobs. 

I don't think we should go with the second option. This will require us to complicate the existing job implementation to support a very small user base. The plugin will not break the site if speed scores are not working, it just won't show the speed scores, and users can just update to get it working again. Furthermore, the old endpoint provides more information with scores. I don't think they are used anywhere, but I think it's still worth mentioning just in case.

**Comment by eAdnan007** [comment]
Diff created: D69849-code?id=283369
![image](https://user-images.githubusercontent.com/3737780/141067673-41f3fafe-f1ae-4587-bdcd-09e5a8af5d77.png)
