### ISSUE TITLE
Monitor should allow more specific testing to determine if site is correct site.

### ISSUE THREAD

**Issue by ambroseya** [Automattic/jetpack#2096]
It would be really nice to see if the monitor could search the page for a specific string, such as copyright text, to assure that the "correct" site is live on the URL.

**Comment by kraftbj** [comment]
Monitor is purposely a very simple system. It requests a HTTP HEAD request so it grabs the minimal amount of data from your site and checks the status code. 

If it is 400 or more, which indicates either a permissions issue or an error code, it declares the site down (after checking against two other servers making the check from separate networks and locations). If it is in the 300 range (a redirect), it'll follow a few redirects before declaring it down (as that many redirects likely indicates a redirect loop or something else gnarly). Lastly if it is a 200, all okay.

The other situation is if the site takes longer than 20 seconds to respond, then it is declared down.

Since it's meant to be a lightweight solution (for both our servers and your server), adding full-page scraping and detection is not something currently on the radar.

Thanks for the suggestion!
