### ISSUE TITLE
Widget Blocks: test/remove widgets in Legacy Widget block

### ISSUE THREAD

**Issue by arcangelini** [Automattic/jetpack#21069]
### Impacted plugin

Jetpack

### What

Test and remove Jetpack widgets that are not working inside the Legacy Widget block

### How

With the recent release of the new widget block editor came a new block that displays legacy widgets within a block. This allows users to continue using the original Jetpack widgets even after converting to the new block editor.

The problem is that many of the widgets do not work properly inside the legacy block. We need to test all of the current widgets inside the legacy block and remove the ones that already have viable block replacements. [Legacy Widget block documentation](https://developer.wordpress.org/block-editor/how-to-guides/widgets/legacy-widget-block/)

This issue is only addressing the availability of the widget inside the Legacy Widget block. I will create another GH issue to tackle the transform. I think these should be separate because they vary in importance.

## Widgets

- [x] Instagram 
- [x] Twitter timeline
- [x] Social Icons
- [x] Authors
- [x] Blog Stats
- [x] Blog Subscriptions
- [x] Contact Info & Map
- [x] Cookies and Consent
- [x] Display WordPress Posts
- [x] Facebook Page
- [x] Flickr
- [x] Goodreads
- [x] Google Translate
- [x] Gravatar
- [ ] Internet Defense Leage
- [ ] Mailchimp Subscription Popup
- [x] Milestone
- [x] Music Player 
- [ ] My Community
- [x] Pay with PayPal
- [ ] Blogs I Follow
- [x] RSS links
- [ ] Top Posts & Pages
- [x] Upcoming Events

**Comment by simison** [comment]
Nice, thanks! I appreciate the organization here.

_Milestone_ seems a8c only?

Let's also review if there's a (close enough) block equivalent and deprecate widget if there is. I'd also be curious for insights that would help improve blocks or block patterns, so that we could deprecate some more widgets.

Search, RSS links, mailchimp, Instagram, etc

**Comment by jeherve** [comment]
> Milestone seems a8c only?

No, it's available for everyone.

**Comment by simison** [comment]
How would transforms change the experience around deprecations? Deprecating would mean that new customers can't insert deprecated widgets anymore, and those don't need transforms obviously. Previously inserted widgets would continue functioning in editors, but for those transforms seem more like a "really nice have", but not critical? 

I could very well miss something so curious for your thoughts!

**Comment by jeherve** [comment]
I may be wrong with my expectations, but since their legacy widgets would be transformed into blocks, folks would learn to use the block directly the next time around, instead of trying to insert a legacy widget that would get transformed later?

It's definitely not critical, but I see it as a way to help people discover those new blocks.

**Comment by arcangelini** [comment]
## Instagram widget - [PR](https://github.com/Automattic/jetpack/pull/21050) r231968-wpcom

**Comment by arcangelini** [comment]
## Authors widget

This widget is working well in the Legacy Block and we do not have a block to replace it with just yet. Checking it off the list, for now, we may want to look at building a viable replacement block.

**Comment by arcangelini** [comment]
## Goodreads

This widget is working well in the Legacy Block and we do not have a block to replace it with just yet. Checking it off the list, for now, we may want to look at building a viable replacement block.

**Comment by aisajib** [comment]
This is almost certainly not the right place to bring it up, but I really wanted to note this somewhere and perhaps one of you can point me in the right direction. :) 

In the original list of legacy widgets to be removed, I noticed that "Text" and "Images" are not there. I was looking for them because I've been trying to look for a solution to this [forum post](https://wordpress.com/forums/topic/how-to-photo-widgets-with-controlled-visibility-on-block-editor/).

They basically want to show an image with text below, and control the visibility of that widget. We know that the visibility option is only available on legacy blocks. So our suggestion of using the Image + Paragraph block isn't useful as the user can't control the visibility. Would one of you know if it's a sad Christmas here or if there is another way to achieve this that I haven't thought of yet? 

We already suggested inserting the "widget" (using Image and Paragraph blocks) into the actual page content instead of at the sidebar, but the user doesn't like how it looks, so they want it on the actual sidebar. 

Thank you and apologies for bringing this here. :disappear:

**Comment by arcangelini** [comment]
Hey @aisajib thanks for pointing this out. I am going to make a P2 post this week summarizing what we have done so far with the Jetpack widget ⇢ block transforms and hopefully, that will offer a place to discuss some of the particulars that people are running into.

As for the visibility button, I think the best way to respond at this point is with CSS. All blocks should have the CSS Class option under `Show More Settings` ⇢ `Advanced` with the exception of the Legacy Widget block. Moving forward, I am not sure if there is a plan to incorporate the Visibility option into the blocks I think that would be something Gutenberg would be working on?

I do know there is a new Widget Group block that has been released (only on WPCOM right now, but should be public with the next major release). If visibility was something that would be incorporated, I would imagine it to fit into this block? Just a thought though... https://github.com/WordPress/gutenberg/pull/33881

**Comment by simison** [comment]
@aisajib @arcangelini visibility feature is almost done for the blocks, so they should be able to use image+text blocks soon. Just a couple small issues to sort out, listed at https://github.com/Automattic/jetpack/pull/20731#issuecomment-926682417

**Comment by arcangelini** [comment]
## Social Icons - [PR](https://github.com/Automattic/jetpack/pull/21146)

**Comment by arcangelini** [comment]
Total list of ALL WordPress.com widgets investigations - p1633288426167100-slack-C029HCKPXP0

**Comment by arcangelini** [comment]
## Cookies & Consent Banner - working with no exact block to replace with yet
## Facebook Page - working with no exact block to replace with yet
## Flickr Photos - working with no exact block to replace with yet
## Google Translate - working with no exact block to replace with yet
## Gravatar - working with no exact block to replace with yet
## Gravatar Profile - working with no exact block to replace with yet
## Internet Defense League - working with no exact block to replace with yet

**Comment by arcangelini** [comment]
Apex team is now responsible for widgets. I believe most of these are taken care of but I could be wrong. I will let @yansern and @ivan-ottinger decide what to do with this from here.

**Comment by ivan-ottinger** [comment]
Thanks for the ping, Tony.

Below is the summary of the remaining widgets and our plans with them. The project spreadsheet with details can be found over here: p1633288426167100-slack-C029HCKPXP0.

Of course, if anyone of you have any comments / suggestions / other opinion on what should happen with specific widgets, feel free to let us know. We will be glad to discuss further. :)

---

### Widgets we plan to keep for the time being

The following widgets don't have an equivalent block available and provide unique feature.

* **Display WordPress Posts**: There's a similar Query Loop block available, but the Display WordPress Posts widget allows users to display a list of posts _from other WordPress sites_ as well.
* **RSS Links**: There's the RSS block available, but it displays the actual links to blog posts coming from the selected RSS feed. On the other hand, the RSS Links widget displays links _to the blog's RSS feeds_.
* **Upcoming Events**: The widget allows users do display a list of events from chosen calendar. We don't have a similar block available.
* **Blog Stats**: We don't have a similar block available. It can be built in the future (panfyZ-8L-p2#comment-504).
* **Top Posts & Pages**: We don't have a similar block available. It can be built in the future (panfyZ-8L-p2#comment-504).

### Widgets we plan to deprecate (details are in pdf5j4-7f-p2)

* **Mailchimp Subscription Popup**
* **My Community**
* **Posts I Like**
* **Blogs I Follow**
* **Internet Defense League**

---

I am also updating the description of this issue so it is in sync with the project spreadsheet.
