### ISSUE TITLE
Boost: Disable critical css until regeneration on theme switch

### ISSUE THREAD

**Issue by eAdnan007** [Automattic/jetpack#21068]
When a site has Critical CSS enabled and they change the theme, Boost will ask them to regenerate CSS. Sometimes the user may not notice it and leave the site. Critical CSS still continues to serve on the site increasing CLS.

https://user-images.githubusercontent.com/3737780/133209224-4743ee35-6583-4f1f-9ff0-e90a3114469d.mp4

**Suggested solution:** Disable serving critical CSS until it is regenerated.

**Comment by amustaque97** [comment]
Hi @eAdnan007, I was going through the recording. I noticed at `0.07` second it is showing a message. 
![image](https://user-images.githubusercontent.com/21127788/133310950-b3ff60ca-e5e1-4392-9264-c596d2dfb716.png)

Not only that on the dashboard page it shows the same message block.
![image](https://user-images.githubusercontent.com/21127788/133311231-ab62c1be-c7de-48da-a205-83277024411f.png)


Checked in the codebase, we have logic in place :)
https://github.com/Automattic/jetpack/blob/9f865ae6a997e3c42b99637bd1800cf0a9b74c33/projects/plugins/boost/app/class-jetpack-boost.php#L517-L526

CC @gravityrail, If I misunderstood or I missed something here!

**Comment by amustaque97** [comment]
Hi @eAdnan007, I would love to work on this issue. In my opinion, we should not disable the module itself because doing so it will not show any notice to the user. Here is my proposed solution video... It will clear CSS and notify the user at the same time. Proposed solution will be more user-centric rather than just disabling the plugin without telling it to the user.
Please share your thoughts. Thanks 

Video Recording: https://youtu.be/OznLHatwz-4
