### ISSUE TITLE
Tiled Galleries work with no connection to WordPress.com 

### ISSUE THREAD

**Issue by robertdall** [Automattic/jetpack#2112]
When you turn on Tiled Galleries while in Development Mode you are told that Titled Galleries only work with the WordPress CDN. See quote docs.

> Note: Images in tiled galleries require extra-special processing, so they will be served from WordPress.com's CDN even if the Photon module is disabled.

Or screenshot: 

![screen shot 2015-05-11 at 2 35 21 pm](https://cloud.githubusercontent.com/assets/1909677/7575637/23e229e8-f7eb-11e4-83c9-160dcc1e7626.png)

But if you are able to activate the module without the connected to WordPress.com then you don't need the notice in the plugin set up. 

Either the docs aren't correct or the functionality of the plugin isn't correct. But something doesn't add up here.

**Comment by kraftbj** [comment]
It's not perfect, but we try to provide a dev mode fallback. Since WP doesn't naturally provide dynamic imaging sizes, Tiled Galleries use the Photon CDN to provide dynamic image sizes back.

IIRC, in Development Mode, we provide a work-ish option that resizes the container for the images so it has a good-faith representation for development purposes, but aren't actually resized.

Overall, our goal is to have faithful fallbacks in development mode so developers have the least amount of things possible that appear differently on the front end of sites that are connected and in production and sites that are in dev mode.
