### ISSUE TITLE
Main Jetpack Screen: Inconsistent styles

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/jetpack#2120]
The buttons on the main Jetpack screen obey the 'Admin Color Scheme' setting, but the rest of the styles do not. Either the buttons should be consistent with the rest of the screen, or the rest of the screen should obey the the 'Admin Color Scheme'.

![screen shot 2015-05-13 at 2 16 31 pm](https://cloud.githubusercontent.com/assets/2694219/7617673/b842beaa-f97a-11e4-9d44-d99699f578a5.png)

**Comment by jeffgolenski** [comment]
@roccotripaldi could you be a little more specific? When you say "the rest of the styles" do not? Are you referring to the 'configure' buttons or literally the rest of the colors? ie. the blue borders, title colors, etc?

Thanks!

**Comment by roccotripaldi** [comment]
Exactly Jeff. Sorry for being vague.

"Rest of the styles" = blue borders on the cards and the card headers.

**Comment by jeffgolenski** [comment]
@roccotripaldi No worries – I'll dig around and see what core has to offer for styles regarding boxed borders + headline colors. Perhaps I can add this to a mild redesign of the Jetpack dash as we move to be less obtrusive to the user. 

I'm going to remove the 3.6 milestones, simply because we're working on a new jetpack.me design. Would like to keep everything consistent – modules on jetpack.me and in /wp-admin/ are similar. Would like to roll out new styles simultaneously if possible. 

![screen shot 2015-05-13 at 5 17 11 pm](https://cloud.githubusercontent.com/assets/214813/7621330/02c361aa-f994-11e4-9bfb-fccfece3ff96.png)


Thanks for bringing this up!

**Comment by dereksmart** [comment]
moot since #2549
