### ISSUE TITLE
404 on an RTL CSS file

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#2125]
A user reported that he is getting a 404 result for this RTL CSS file while logged in with the Contributor role:

jetpack-banners.min-rtl.css

Reported in 2129869-t

**Comment by jessefriedman** [comment]
@richardmtl I logged in as a contributor and wasn't able to duplicate the problem. Do you know specifically what they were doing or seeing when it occured?

Also I don't see that the file jetpack-banners.min-rtl.css exists anywhere in Jetpack. I also don't see a single reference to a file of that name. 

This is what we have that is close: https://cloudup.com/c3U2uxIzsL2

**Comment by bStyler** [comment]
Hey there,

I  was the one to original report this issue, allow me to provide more some screenshots please:
http://gyazo.com/72de9b3232cc46339a037d0fe0b5c595
http://gyazo.com/54d5b27a9667e1b11495b67af46507c5

That's the css link that can't be found:
<link rel='stylesheet' id='jetpack-rtl-css'  href='http://www.nusic.co.il/wp-content/plugins/jetpack/css/jetpack-banners.min-rtl.css?ver=3.5.3-20121016' type='text/css' media='all' />

I'm using the latest Jatpack version with the latest Wordpress version.
Since my WP is RTL, it's trying to grab the RTL css file.

Question is, why is it trying to reach to this one?

I'm happy to provide you with credentials to my WP if required, just let me know to which e-mail to sent it to.

Many thanks!
