### ISSUE TITLE
Jetpack Search: Does not work when the site language is Arabic

### ISSUE THREAD

**Issue by mrsjaved** [Automattic/jetpack#21349]
### Quick summary

Jetpack search does not work when the site language is set to Arabic. 

### Steps to reproduce

1. Make sure JP search is eanbled from JP settings -> Performance -> Search
2. Change site language to Arabic (no need to change it for the user interface) from site settings -> general.
3. Add JP search widget in the sidebar and try to search.

### What you expected to happen

It should display results in popup

### What actually happened

Does nothing.

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

Ticket: 4357314-zd-woothemes

**Comment by anomiex** [comment]
Trying it locally, I see this in my browser console:
```
Uncaught (in promise) Error: Loading CSS chunk main-payload failed.
(https://REDACTED/wp-content/plugins/jetpack/_inc/build/instant-search/jp-search.chunk-main-payload.min.rtl.css?ver=f33ebf8feb95ae7fc64a)
```
Looks like the problem is that [@automattic/webpack-rtl-plugin](https://www.npmjs.com/package/@automattic/webpack-rtl-plugin) expects the CSS asset's name to end in `.css`, while since #20926 it's ending in something like `.css?var=f33ebf8feb95ae7fc64a`. So it never produces the `.rtl.css` file, which makes Instant Search fail to load for RTL languages.

**Comment by kangzj** [comment]
thanks @anomiex I'm onto it.
