### ISSUE TITLE
No obvious way to deactivate a module from the main Jetpack settings

### ISSUE THREAD

**Issue by pbaylies** [Automattic/jetpack#2140]
This is a general UI issue I ran into regarding module activation that I mentioned to @georgestephanis -- I'm going to pick on the Related Posts module by way of example:

![related_posts_activate](https://cloud.githubusercontent.com/assets/3865161/7659389/8a95ea90-fb0f-11e4-9399-0ad3de63ac55.png)

Initial state, Related Posts is deactivated, so it has an Activate button; clicking this appears to work fine, and also yields this helpful message, which appears briefly:

![related_posts_activation](https://cloud.githubusercontent.com/assets/3865161/7659415/bbc7c890-fb0f-11e4-91a5-440b610589b4.png)

However, on the subsequent screen, you'll notice that there is no Deactivate link next to the module, as was mentioned above:

![related posts no deactivate](https://cloud.githubusercontent.com/assets/3865161/7659573/e7b16cb2-fb10-11e4-9ab5-7b2edc70e099.png)

There is, however, a Configure button, but this goes to a different settings screen, where there also is no Deactivate link or button.

If you click at random on the rest of the Related Posts section, you will find that nothing happens if you click the description or the white space, but clicking the header itself will reveal more hidden information that includes a Deactivate button. However, there is no visual cue to indicate that this exists at all.

I am by no means a UI expert, but I would suggest adding either a Deactivate button next to the Configure button if possible, or perhaps an X in the corner (with a tooltip that says "Deactivate"), and/or some sort of button or icon for more information on a module (perhaps a stylized letter i in a box), and include instructions that do not quickly vanish that mention how to Deactivate modules if it isn't made plain (or even if it is).

**Comment by jessefriedman** [comment]
Hi @pbaylies 

Thanks for the feedback. Right now this screen is designed to help users easily activate and configure their favorite Jetpack tools. We are always improving it, which is why getting feedback like this is great. 

In addition to clicking the "Related Posts" title and clicking the deactivate button in the modal you can also go to the main settings page. There you can activate and deactivate each tool and even bulk activate and deactivate them as well. 

I'm going to take this feedback and evaluate what to do next.  Thank you for taking the time to write it all up. If you have any further questions or concerns don't hesitate to get in touch. I'll keep this ticket up to date if we decide to move forward with changes. 

Jesse

**Comment by jeherve** [comment]
Related: #661

I think it'd be nice to get rid of that screen and direct to the Settings screen once the user is connected to WordPress.com.

**Comment by dereksmart** [comment]
Closing, as 3.7's new layout makes toggling these obvious
