### ISSUE TITLE
Packagist

### ISSUE THREAD

**Issue by peterhough** [Automattic/jetpack#2150]
Could Jetpack be submitted to http://packagist.org?

I am using the Bedrock to develop Wordpress installations, this uses Composer to manage dependencies. I can see Jetpack already has a composer.json file but it is not listed in Packagist: https://packagist.org/packages/automattic

This would avoid the need to manually add the repository:

```
"repositories": [
    {
      "type": "git",
      "url": "https://github.com/Automattic/jetpack"
    }
]
```

**Comment by kraftbj** [comment]
I don't have an immediate answer re packagist, but have you seen http://wpackagist.org/ ? It is a mirror of the w.org plugins repo as Composer packages.

**Comment by kraftbj** [comment]
@xyu - the only Automattic package appears to have been added by you. Do you have access to add JP?

**Comment by xyu** [comment]
I've just added [Jetpack to Packagist](https://packagist.org/packages/automattic/jetpack), I don't believe there is any sort of "authentication" per say so anyone could have added Jetpack. However before it's actually useful we will need to include a `composer.json` file in this repo to define maintainers and prerequisites.

As a sidenote, personally I use http://wpackagist.org for WordPress plugins as they crawl the .org repo and automagically exposes all of the plugins available to composer.

E.g.: https://github.com/xyu/heroku-wp/blob/master/composer.json

**Comment by peterhough** [comment]
Thanks for adding Jetpack to Packagist and thanks for the tip about http://wpackagist.org I wasn't aware of that :+1:

**Comment by kraftbj** [comment]
FYI - on Packagist, it blocked me from adding Jetpack since there was already a package listed with the same vendor ("Automattic"), so there is some type of authentication check.

**Comment by sirbrillig** [comment]
Thanks for the heads-up! I pressed "Update" on the Packagist page, which seems to have updated it for now.

Github is disabling their "services" hooks, so we need to configure the new Packagist auto-updater so it will work in the future. One of the requirements is for Packagist to be granted access to the Automattic repo, and that permission reads

> Access request pending. 

I have a feeling that whoever runs the Automattic Github organization does not usually approve access requests. We should probably try to figure out who that is and see if we can grant it in this case, otherwise I don't think we can get auto-updates to work properly.

In the mean time I tried setting up a manual webhook with my key, but I'm not sure if it worked or not. The Packagist repo still shows the same warning, but I guess we'll find out when the next release happens.

**Comment by jeherve** [comment]
> We should probably try to figure out who that is and see if we can grant it in this case, otherwise I don't think we can get auto-updates to work properly.

Paging @mdawaffe, who should be able to help us here I think.

**Comment by mdawaffe** [comment]
> jeherve commented on Nov 27, 2018

Huh. I forgot all about this, obviously. Do we still need to do anything here?

**Comment by jeherve** [comment]
The webhook appears to work well now, our plugin updates are published properly:

https://packagist.org/packages/automattic/jetpack

Closing this.
