### ISSUE TITLE
Boost: Fix an issue with inconsistent Lazy Load toggle and state on a fresh boost install with Jetpack installed

### ISSUE THREAD

**Issue by davidlonjon** [Automattic/jetpack#21585]
It seems there is some inconsistency in the state of the Lazy Load module on a fresh install if Jetpack is also activated.

see 

https://user-images.githubusercontent.com/927932/139411310-30253daf-e978-4a1c-8e69-90914901bb97.mp4

By default, the Lazy Load module from Boost should be disabled. However on a fresh install, after the user press the getting started, it also connects the Jetpack plugin which seems to have the Lazy Load module enabled by default. After a refresh of the Jetpack Boost admin page just after pressing the 'Getting Starting" button, the Lazy load module is showing as enabled. This is inconsistent and should be fixed.

**Comment by eAdnan007** [comment]
I am currently looking into this. Seems like this is what happens:
- Boost and jetpack are both freshly installed and not set up.
- User opens Boost page, the inline config json while the page has lazy loading disabled.  Boost shows connect to WP.com prompt.
- User clicks connect to WP.com. This also connects jetpack in the backend and enables lazy loading.
- Boost main UI is shown but lazy loading is still showing from the old inline config that was available.

Now, I am thinking about what should be the consistent default config. If we disable Lazy Loading by default, things change depending on Jetpack is present or not(as jetpack considers this as enabled by default). The simplest solution seems to be to follow Jetpack and keep Lazy Loading enabled by default for Boost as well.

Your thoughts?

cc: @thingalon

**Comment by thingalon** [comment]
🤔

I'm on the fence about this. On the one hand, Jetpack Boost usually starts with all of its features off by default, and invites users to turn them on one-by-one. I wonder if starting with some on and some off will discourage users from exploring the features (?)

On the other hand, consistency across plugins is good and lazy loading is a very safe module to have enabled.

I think we may need to run this one by design. Can you pls P2 it, cross-post to jpopdesign and we'll have a discussion about it.

I don't want to make this change in response to a bug - but it may be the right choice to make from a user-friendliness perspective. I'm just not sure.
