### ISSUE TITLE
Jetpack sharing buttons causing Google Search Console warnings

### ISSUE THREAD

**Issue by lakellie** [Automattic/jetpack#21836]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Enable sharing buttons
2. Set up Google Search Console
3. Google Search Console attempts to index the URLs linked on each sharing button (which is the post URL appended with ex.  `?share=facebook`, `?share=reddit`, and `?share=email`)

### A clear and concise description of what you expected to happen.

I wouldn't expect GSC to attempt to index these URLs, as they all link to outside the site (for example, the URL with `?share=facebook` opens a Facebook share panel from Facebook).

### What actually happened

GSC attempts to index the URLs, and it reports a warning: `indexed, though blocked by robots.txt`. This results in users receiving a warning/notice email, and they don't seem to be able to dismiss the warnings. 

### Other information

Opening an issue here as we've received at least three separate user reports about this over the past month or so.

Looking at the source code for the sharing buttons, I can see these URLs are added to the buttons with `rel="nofollow noopener noreferrer"` 

Have there been any changes made to this recently? Is this an issue on the GSC side, or is there a way we can change the way these URLs are linked to prevent the errors from occuring? 

### Browser

Chrome/Chromium

**Comment by jeherve** [comment]
> Have there been any changes made to this recently?

No, we've made no changes to this in the past few years.

> I can see these URLs are added to the buttons with rel="nofollow noopener noreferrer"

Right, this is how we've informed search engines that the links should not be followed until now. Apparently it doesn't always work though.

I think it would be worth reaching out to Google to ask them what the preferred method is for situations like this one, if not using  the `nofollow` `rel` attribute like we've been doing since we first introduced the buttons 10 years ago. Maybe there is a better way.

Until then, I think we could try something more, like #21843.

**Comment by anomiex** [comment]
Based on some testing with Google's Search Console, it looks like the "though blocked by robots.txt" bit is because the Twitter page that's the target of the redirect is listed in Twitter's robots.txt. Which makes sense, Twitter wouldn't want that crawled.

Based on some text at https://developers.google.com/search/docs/advanced/guidelines/qualify-outbound-links, the problem may be that Google ignores `nofollow` entirely when the link points to your own site.

> If you need to prevent Google from following a link to a page on your own site, use the robots.txt disallow rule.
>
> To prevent Google from indexing a page, allow crawling and use the noindex robots rule.

Or it may just be that some link somewhere else (possibly not even on your site) points to these URLs without using `rel=nofollow`.

Either way, the solution is probably to have the redirect itself specify "noindex" via `header( 'X-Robots-Tag: nofollow' )` somewhere in there before the `die()`.
