### ISSUE TITLE
Malformed img src when lazy-loaded is active

### ISSUE THREAD

**Issue by bmarotta** [Automattic/jetpack#22003]
### Impacted plugin

Boost

### Steps to Reproduce

1. Enable lazy loading
2. Check the generated HTML page source

### A clear and concise description of what you expected to happen.

The source should contain the data prefix

src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"

### What actually happened

The image source is mal-formed generating a potential 404 error

src="image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"

### Other information

For more information see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs

### Operating System

Any

### OS Version

Any

### Browser

Any

### Browser Version(s)

Any

**Comment by jeherve** [comment]
Thanks for the report. Does this happen on a specific site, or do you experience this on multiple sites? If you experience this on a specific site, could you post its URL here so we can take a closer look?
Could you also try deactivating any other plugins that may impact with the Lazy Loading feature, such as caching plugins, and let us know if you find that the problem is caused by a conflict between Jetpack Boost and a specific plugin?

Thank you.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
