### ISSUE TITLE
OpenTable Block 403 network errors

### ISSUE THREAD

**Issue by AnthonyLedesma** [Automattic/jetpack#22006]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Go to the editor. 
2. Insert OpenTable block.
3. Type anything into the field.
4. Notice 403 response from API under inspector controls.

### A clear and concise description of what you expected to happen.

Expect block to be resilient to API changes.

### What actually happened

Block seems unusable at the moment.

### Other information

This is also happening on the CoBlocks implementation of OpenTable so I thought to test it here as well.

### Operating System

macOS

### Browser

Chrome/Chromium, Firefox

**Comment by jeherve** [comment]
Thanks for the report. The issue seems to be with the Restaurant Search API from OpenTable:
https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/extensions/blocks/opentable/use-restaurant-search.js#L16-L18

[Their API status page](https://status-api.opentable.com/) doesn't report any outages at the moment, so we'll need to investigate some more to find out what's happening.

**Comment by jeherve** [comment]
Internal reference: p1638807404196300-slack-C0299DMPG

**Comment by olafleur-godaddy** [comment]
It does not seem to be an outage, but more likely that they stopped allowing cross origin requests somewhere last week.

**Comment by jeherve** [comment]
I've emailed them to find out more. I'll update this issue once I have more information.

> This is also happening on the CoBlocks implementation of OpenTable so I thought to test it here as well.

Cross-posting here for reference: 
https://github.com/godaddy-wordpress/coblocks/issues/2188

I'll update you there as well if this gets fixed on their end. 👍

**Comment by olafleur-godaddy** [comment]
FYI, one of our devs wrote a workaround that should be merged today : https://github.com/godaddy-wordpress/coblocks/pull/2204

Basically it's creating a REST endpoint to proxy the call to the API.

**Comment by jeherve** [comment]
Closing as duplicate of #39410.
