### ISSUE TITLE
Disable Lazy load for above the fold critical images

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/jetpack#22020]
### Impacted plugin

Jetpack, Boost

### Steps to Reproduce

1. Enable Jetpack and Jetpack Boost
2. Enable Lazy Image Loading in Boost
3. Visit a page and search for loading="lazy". You will find loading="lazy" attribute added to post-thumbnail.

### A clear and concise description of what you expected to happen.

Above the fold images are critical for Largest Contentful Paint measurement in Core Web vitals. At least site logo and featured image should be excluded from Lazy load to not affect LCP in negative way.

### Browser

Chrome/Chromium

**Comment by jeherve** [comment]
The `loading="lazy"` attribute is not added by Jetpack's Lazy Load feature, it is added by WordPress itself, since [version 5.5](https://make.wordpress.org/core/2020/07/14/lazy-loading-images-in-5-5/). Jetpack's feature is built on top of core's lazy loading feature, and is implemented in JavaScript so it can work with browsers that do not support the `loading` attribute yet.

As you can read in the post above introducing the `loading` attribute to WordPress, they have considered the performance impact of that attribute:

> Images that are marked as candidates for lazy-loading require the browser to resolve where the image is positioned on the page, [which relies on the IntersectionObserver to be available](https://web.dev/native-lazy-loading/#is-there-a-downside-to-lazy-loading-images-or-iframes-that-are-within-the-device-viewport) and thus as of today slightly delays their fetching. Experiments using Chrome for Android have shown that the impact of such loading=”lazy” images in the initial viewport on the [Largest Contentful Paint](https://web.dev/lcp/) metric is fairly small, with a regression of <1% at the 75th and 99th percentiles compared to non lazy-loaded images – yet it is a consideration to make where theme developers can apply some fine tuning for even better user experience.
> 
> See [#50425)(https://core.trac.wordpress.org/ticket/50425) for further background information on this change.

In that linked ticket, you'll find that following investigations, the contributors who worked on the Lazy Loading feature in WordPress have made some changes a few weeks ago, as outlined in [this ticket](https://core.trac.wordpress.org/ticket/53675) and [this post explaining the changes](https://make.wordpress.org/core/2021/07/15/refining-wordpress-cores-lazy-loading-implementation/). Those changes should address your concerns, and will be included in the upcoming version of WordPress, 5.9, scheduled to be released in January 2022.

I hope this clarifies things a bit.

**Comment by yogeshbeniwal** [comment]
@jeherve Thank you for clarification.

In that case it it right to say that, Lazy load feature in jetpack is same as in built in WordPress for browser supporting lazy load by default?

**Comment by vini123** [comment]
虚幻之物对应着冥冥之路！：《羽》

**Comment by jeherve** [comment]
> In that case it it right to say that, Lazy load feature in jetpack is same as in built in WordPress for browser supporting lazy load by default?

They work a bit differently:
- the WordPress implementation does not enqueue any JavaScript; it fully relies on support provided by the browser.
- the Jetpack implementation relies on JavaScript, so it is compatible with all browsers by default.
