### ISSUE TITLE
Broken image

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/jetpack#2203]
I have Jetpack installed as an MU plugin (i.e. in `wp-content/mu-plugins/`). On `/wp-admin/admin.php?page=jetpack_modules`, when I click on "VaultPress", I see a broken image:

![screen shot 2015-06-01 at 20 22 51](https://cloud.githubusercontent.com/assets/233434/7921255/2c5cd926-089c-11e5-8e48-329ad58d014f.png)

The image is referencing Jetpack as a sub-directory of the `wp-content/mu-plugins/` folder, rather than working out it's actually an MU plugin.

**Comment by kraftbj** [comment]
@simonwheatley To confirm, you're probably also seeing this on all modules, right? Gravatar Hovercards, etc?

**Comment by lancewillett** [comment]
In testing a website on a WordPress host I saw broken Jetpack file paths for settings screenshot images just like this report — in my case it was the Related Posts module. (But after looking, it's all the modules settings screenshots are returning 404.)

In the settings UI for each Jetpack module the screen images are missing probably because `basename` isn't always reliable depending on where Jetpack plugin is loaded (symlink, for example).

Code ref: https://github.com/Automattic/jetpack/blob/8d13e90a72b1afad48a6d3c380019c4834c922f3/modules/module-info.php#L789

That file call results in a 404:

[code]Failed to load resource: the server responded with a status of 404() wp-content/plugins/4.0.2/images/screenshots/related-posts.jpg 
[/code]

**Comment by lancewillett** [comment]
Could the simplest solution be using `plugins_url()` without the `basename` references?

**Comment by jeherve** [comment]
Related: #1991

**Comment by dereksmart** [comment]
We no longer show VaultPress in this list
