### ISSUE TITLE
Assets: Unable to enqueue CSS files from Jetpack Search package

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/jetpack#22043]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Apply [this diff](https://gist.github.com/jsnmoon/74f0f901ddcdc4ffef8310e89fa5f681) to the Search package, which adds a `css_path` parameter (`search/build/customberg/jp-search-configure.css`) to the `Assets::register_script` invocation.
2. Ensure that the production build has been run for the Search package. 
3. On a site with a Jetpack Search subscription, navigate to `/wp-admin/admin.php?page=jetpack-search-configure`.

### A clear and concise description of what you expected to happen.

The appropriate stylesheet should have been enqueued and applied to the page.

### What actually happened

The stylesheet is enqueued, but throws a 404 since its path is:
`/wp-content/plugins/jetpack/vendor/automattic/jetpack-search/build/customberg/` instead of
`/wp-content/plugins/jetpack/vendor/automattic/search/build/customberg/`.

Using `search/build/customberg/jp-search-configure.css` as the `css_path` also fails, since it refuses to enqueue the stylesheet due to failing the `file_exists( "$dir/{$options['css_path']}" )` check within the `register_script` function.

### Browser

Chrome/Chromium

**Comment by anomiex** [comment]
Your steps to reproduce don't really work. It seems the patch needs to be applied to some version of #21637.

It looks like your problem is that you're passing wrong paths. In the code in your diff, you have `$plugin_base_path` as the base directory of the plugin, but `Assets::register_script()` (like WordPress core's `plugins_url()`) wants to be passed a file within that directory. You're then trying to correct for this by including "jetpack-search/" in your `$path_prefix`, which is not correct in all contexts.

As for `css_path`, you're making much the same mistake except this time you're including "search/" in the path which again is not correct in all contexts. You shouldn't need to use `css_path` at all since the CSS filename is the same as the JS with the extension changed, which is what `Assets::register_script()` looks for as the default.
