### ISSUE TITLE
Beta Plugin: Link to Beta Plugin README and testing tips not working from within 'To Test' box

### ISSUE THREAD

**Issue by coder-karen** [Automattic/jetpack#22104]
### Impacted plugin

Beta

### Steps to Reproduce

1. From the Jetpack Beta Tester Home, click on the button to manage the Jetpack Beta Tester
2. Make sure the 'existing version' is active (3.1.0)
3. In the 'To Test' box, the link to the Jetpack Live Branches README leads to a 404 page. It will send you to `https://currentsiteurl.com/tools/jetpack-live-branches/README.md`
4. Additionally this is also broken in the current 'bleeding edge' version (3.1.0-1583136679-g85df5bd) - the link in the 'To Test' box here is also broken. It goes to `https://currentsiteurl.com/projects/plugins/beta/docs/testing/testing-tips.md` which leads to a 404 page.

### A clear and concise description of what you expected to happen.

I'd expect those links to lead to non-broken pages.

### What actually happened

Clicking on both of the mentioned buttons lead to 404 pages (see above for the URLs).

### Other information

The Jetpack Live Branches README link appears to be broken in every 'To Test' box, not just when managing the Beta Tester

### Operating System

macOS

### OS Version

11.6

### Browser

Chrome/Chromium

### Browser Version(s)

96.0.4664.110

**Comment by anomiex** [comment]
If you'd like to take this on, that comes from [projects/plugins/beta/docs/testing/testing-tips.md](https://github.com/Automattic/jetpack/blob/master/projects/plugins/beta/docs/testing/testing-tips.md). The link should probably be adjusted to point to https://github.com/Automattic/jetpack/blob/master/tools/jetpack-live-branches/README.md#readme instead of being a relative link to `../../tools/jetpack-live-branches/README.md`.

I note that the link for "Jetpack Beta Tester plugin" there is broken too, pointing to something like `https://currentsiteurl.com/wp-admin/github.com/Automattic/jetpack-beta`. That one is missing the "https://" at the beginning of the URL.
