### ISSUE TITLE
Instant Search: search for default results should not always happen on page load

### ISSUE THREAD

**Issue by bluefuton** [Automattic/jetpack#22231]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Go to https://meyerbees.com/product/honey-bee-advent-calendar-12-day-sampler/
2. Inspect the API requests in your browser console. Note that the Jetpack search endpoint has been requested.
3. Inspect the HTML markup and look for `jetpack-instant-search__overlay`. Note that search results have been fetched. If there are images present they may have been loaded (see https://github.com/Automattic/jpop-issues/issues/7204).

### A clear and concise description of what you expected to happen.

Instant Search does not make any API requests or load any images before the overlay is in use.

### What actually happened

Instant Search makes an API request (and potentially some image requests) on every page load.

### Other information

<img width="1591" alt="Screen Shot 2022-01-06 at 09 59 42" src="https://user-images.githubusercontent.com/17325/148288722-e49cbdc7-1cf8-4f7d-8c44-09be4f125927.png">
<img width="854" alt="Screen Shot 2022-01-06 at 09 59 26" src="https://user-images.githubusercontent.com/17325/148288731-9aca3064-1006-4ae9-865e-cfee1b342407.png">

### Browser

Firefox

**Comment by bluefuton** [comment]
@gibrown notes that we may need to perform the API request when there is a faceted sidebar, but we shouldn't need to load any images in this case.

**Comment by kangzj** [comment]
Probably is not worth another issue - in additional to the front end, the back end queries instant search index on every load too. Code could be found here: 

https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/modules/search/class-jetpack-instant-search.php#L82

I guess we could load it when needed instead of request it without testing whether we'd need it. A possible solution could be:

1. Remove the code above
2. Add search request before we show the search widget, somewhere in: https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/modules/widgets/search.php#L445

IMO, it's not an urgent issue, so I guess we could fix it after we finish the search package, otherwise there will be additional work.

Discussion: `p1641409510448600-slack-opers`

**Comment by bluefuton** [comment]
Can we test if this solved the customer image issue in https://github.com/Automattic/jpop-issues/issues/7204?

**Comment by kangzj** [comment]
@bluefuton The bug should be kept open as PR #22312 only fixed the issue from the backend.

**Comment by robfelty** [comment]
@jsnmoon  - I see this has been moved to done, but I still see API requests being sent on every page load on several test sites running Jetpack 10.9. Has this been shipped yet? Or did it regress perhaps?

**Comment by jsnmoon** [comment]
> I see this has been moved to done, but I still see API requests being sent on every page load on several test sites running Jetpack 10.9. Has this been shipped yet? Or did it regress perhaps? (@robfelty)

Yes, it might be a regression... I'll move it back into the maintenance backlog.

**Comment by katiebethbrown** [comment]
Adding a +1 as we're seeing this happen on a Team51 partner site. The API call is present across all pages of the site, even those that don't have any search functionality.

When testing performance on the homepage we noticed several extremely large images (15+ MB) loading that were not present in the page content. They were featured images and product images loading as part of search. The unoptimized images were obviously the larger issue for us, and the load times improved once they were optimized.

Because we're loading in the full-size featured image we could be unintentionally slowing down pages that don't even use search if the site has even one featured image that hasn't been optimized.

Slack thread:
p1652832201933599-slack-C0CMN0V97
