### ISSUE TITLE
Enhancement: replace is_ajax with wp_doing_ajax

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#22350]
### Impacted plugin

Jetpack

### What

Replace all instances of `is_ajax` with `wp_doing_ajax`

### How

Since [WooCommerce 6.1](https://developer.woocommerce.com/2022/01/11/woocommerce-6-1-released/), `is_ajax` is deprecated and should be replaced with `wp_doing_ajax`.

Reported in https://wordpress.org/support/topic/deprecated-function-text-getting-printed-in-error_log/

**Comment by amustaque97** [comment]
Hi I would like to take this up. It would be  better if someone from the team triage it and can point some relevant files/docs (if knows)

**Comment by jeherve** [comment]
I'm not quite sure what this is referring to, to be honest. The message is outputted by WooCommerce, since the function is from there and was deprecated there:
https://github.com/woocommerce/woocommerce/blob/acbe200c79815deda60e9fd5cc1aa63fccdda070/plugins/woocommerce/includes/wc-deprecated-functions.php#L1135

The current stable Jetpack plugin is not using that old WooCommerce function anywhere at the moment, so the deprecation message is not caused by Jetpack. 

There are a few WooCommerce extensions that do use that old function though, and that will need to be updated accordingly. I'd consequently recommend that on sites where you get that error, you deactivate all plugins but WooCommerce, one at a time, until you find the extension that's causing the issue.

**Comment by danjjohnson** [comment]
Sorry @jeherve - I may have wrongly assumed the messages were coming from Jetpack, although I did find a few instances in https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/modules/custom-post-types/nova.php

Could that we generating the deprecated notices?

**Comment by jeherve** [comment]
> I did find a few instances

Those are variables, not functions (i.e. `$is_ajax` and not `is_ajax()`), so that's not causing to cause any issues here.

**Comment by amustaque97** [comment]
Even I was confused for sometime. Thought of asking about the files/code here! 😆
