### ISSUE TITLE
All Themes: Turning on AMP page in Jetpack hides the mobile menu from the theme

### ISSUE THREAD

**Issue by mapk** [Automattic/jetpack#22351]
## Steps to replicate

1. Install Dara on a test site
2. Go to the Jetpack > Settings. Turn on AMP and view on a mobile device (or by appending `?amp` to the URL of an AMP-compatible page, like a single post). 

## Expected behaviour:

The menu will still be available.

## Actual behaviour: 

The menu is not available.

Reported in Zendesk: Incident #1323696-zen

**Comment by jeherve** [comment]
As mentioned above, I believe this is the expected behaviour with the AMP plugin. Here is an example with a site using the Dara theme. No other plugin is active (not even Jetpack)

<img width="211" alt="Screenshot 2022-01-14 at 15 11 51" src="https://user-images.githubusercontent.com/426388/149529583-a10e4f0c-5c77-4073-9e70-aa8ae049fd21.png">

And when I activate the AMP plugin:

<img width="200" alt="Screenshot 2022-01-14 at 15 11 07" src="https://user-images.githubusercontent.com/426388/149529863-f588f273-a515-4b08-9e0d-9f7b2e6a41c0.png">

The Reader Mode for AMP is meant to be simple, and uses its own theme.

If you'd like AMP mode to use the theme's features and colors, the theme would have to be made AMP compatible. Here are a few examples:
https://amp-wp.org/ecosystem/themes/
