### ISSUE TITLE
Widget Visibility: Show Front Page/ Posts Page for secondary pages

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#224]
Currently, if a widget is set to show/hide on "Front Page" or "Posts Page", the condition will only apply on the "first" page. If visiting ?paged=2, etc, the condition is not respected.

Suggest enhancement that this option include paged.

**Comment by SN0WKRASH** [comment]
Hi, any solution for this? I'm about to have to pay someone to hack the plugin (something I don't want to do since we want to be able to update easily).  Please add is_paged condition for home (front page).  We use this for ads, and the money we make depends on which pages they show up on.  We are currently unable to make any money for the paged front page, even though they get lots of traffic.  To make matters worse, those ad spaces are conspicuously empty and it looks amateurish.  Thanks for considering this.

**Comment by jeherve** [comment]
@SN0WKRASH We haven't made any progress on this yet, but feel free to add the option on your site and submit a Pull Request so others can benefit from your change. You can follow the instructions here to submit a Pull Request:
https://github.com/Automattic/jetpack/blob/master/CONTRIBUTING.md

**Comment by samhotchkiss** [comment]
This should probably be a filter, not a front-end option, IMO

**Comment by jeherve** [comment]
Also requested here:
https://wordpress.org/support/topic/widget-visibility-home-page?replies=1&view=all

**Comment by jeherve** [comment]
Also requested on Slack FR.

**Comment by scottsweb** [comment]
I am not seeing this issue in my testing. 

Widget settings:

![Screenshot 2019-05-01 at 16 13 41](https://user-images.githubusercontent.com/411945/57024279-1a78dc80-6c2c-11e9-816b-523df675c957.png)

The widget is visible on the front page + page 2/3/4 etc Hide has the exact reverse effect, as expected. 

Possibly one to close?

**Comment by jeherve** [comment]
If you can't reproduce anymore, and since we haven't had any new reports in a long time, I think it's time to close that issue indeed. Thanks for giving it a try!
