### ISSUE TITLE
Blocks: potential conflict with WP Super Cache

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#22410]
Jetpack includes a `jetpack_is_frontend()` function that is used across blocks to display a fallback message on non-frontend requests, where the block's resources are not available:
https://github.com/Automattic/jetpack/blob/590d930bd476bef1f01aa2904a4b3d9adea58a5b/projects/plugins/jetpack/functions.global.php#L458-L463

It would seem that in some scenarios, folks get the fallback messages when on the frontend of the site, when using the WP Super Cache plugin:
![jetpack-error](https://user-images.githubusercontent.com/426388/150177456-c02271e3-4ffe-46e0-80cf-893e7b71ced0.jpg)

We may have to adjust some of the conditions here to better accomodate caching plugins:
https://github.com/Automattic/jetpack/blob/590d930bd476bef1f01aa2904a4b3d9adea58a5b/projects/plugins/jetpack/functions.global.php#L467-L476

******

Reported here:
https://wordpress.slack.com/archives/C08M59V3P/p1642609182048900

**Comment by ryelle** [comment]
The config file for WP Super Cache on WordCamp.org can be found here: [wp-cache-config.php](https://github.com/WordPress/wordcamp.org/blob/production/public_html/wp-content/wp-cache-config.php)

**Comment by jeherve** [comment]
Looking at the file, 2 things seem to jump at me:

`$wp_cache_pages["feed"]      = 0;`

Meaning that Feed pages are cached; that would create an issue here.

`$wp_cache_cron_check         = 1`

This one I'm not as sure, but it does seem to be caching cron requests (where only a fallback message is shown instead of the form), and then some folks would get served that cached page later on.

Would it be an option to change those settings?

**Comment by ryelle** [comment]
> Meaning that Feed pages are cached; that would create an issue here.

I don't think the feed pages would be served up as regular content though, I don't think that's the problem here.

> This one I'm not as sure, but it does seem to be caching cron requests 

I think that one is a debugging property, from what I can tell. But I think you're on the right track with cron - it looks like we [preload the cache,](https://github.com/WordPress/wordcamp.org/blob/2b8cf32f0b1f2fa8a6b0bed05eaaf4c6ac60a86a/public_html/wp-content/wp-cache-config.php#L34) which is an action that runs in cron… though it seems to fetch the pages using `wp_remote_get`, so I would think it's not `wp_doing_cron` in the request.

**Comment by jeherve** [comment]
@mmtr I'll rope you in since you worked on #17256. Maybe we could try to remove the `wp_doing_cron()` condition in there? Do you recall the type of use-case this was built for?
