### ISSUE TITLE
Contact Form: Allow for different/multiple CPTs

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2244]
For users that either need to use a different CPT or would like multiple forms that deposit to different CPTs, the Contact Form could include a filter to change the CPT and add a shortcode argument to the shortcode processor.

Suggested in 2222558-t

**Comment by strix-technica** [comment]
Example use case:

Standard "contact us" type forms go to the default Feedback taxon;

Customer questionnaire type forms (of which there may potentially be more than one) get filed in their own respective taxa, however those taxa are created.  

Jetpack need not be responsible for registering those additional taxa; it could, but there are many ways to do this so it would be hugely useful if, as a first step, the option to specify a destination post_type were available in the form shortcodes (because doing the UI for creating and managing such taxa is time consuming) and it's the ability to specify the target post_type that would be most useful at this point.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
