### ISSUE TITLE
Tiled Galllery Block: update Platform implementation to avoid pulling too many dependencies

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#22445]
This is a follow-up from #21849. 

The block update pulls `Platform`, from `@wordpress/element`. That is problematic as the whole package (and its dependencies, React, React Dom, and lodash) is then added as a dependency and then enqueued in the editor as well as on the frontend to render the gallery.

It would be nice to refactor this so we only add what we need. While we do try to use WordPress packages whenever possible, we aim to be as frugal as possible for frontend dependencies.

*******

cc @illusaen, @guarani, and @SiobhyB who worked on the original PR. Do you think you could take a look?

Thank you!

**Comment by guarani** [comment]
Hi @jeherve, thanks for reporting this, I'll take a look.

**Comment by sgomes** [comment]
Hey @guarani, please let me know if you need any help looking into this!

**Comment by sgomes** [comment]
Hey @guarani! I'm currently AFK but I'd be happy to help out on Monday, yes!

 > My understanding of the issue is that #21849 (the port of Tiled Gallery to native mobile) imported Platform from @wordpress/element and this caused performance issues on the web. These performance issues are present in both the editor (via edit.js) and on the frontend (via the serialized output of save.js).
>
> Could you please confirm if this is your understanding as well?

Yes, that's the issue I able to identify, although it only applies to the frontend; the editor is able to make use of `@wordpress/element` without any performance concerns, since it's part of the core Gutenberg functionality.

Not the frontend, though. Loading `@wordpress/element` (and consequently, `lodash` and `react`) is a large performance regression that's currently affecting all page views that use the tiled gallery.

**Comment by guarani** [comment]
> Loading @wordpress/element (and consequently, lodash and react) is a large performance regression that's currently affecting all page views that use the tiled gallery.

I'll go ahead and create a PR to split `mosaic/resize.js` into a `resize.js` file and `resize.native.js` file, and removing the import of `Platform` from the former. I'll submit that PR for review from Jetpack Crew even if I can't test the change myself (since I don't want to delay this further due to any issues with my local Jetpack development setup.)

**Comment by guarani** [comment]
I've created https://github.com/Automattic/jetpack/pull/22547 to fix this by reverting the changes to `resize.js`. If this is urgent and someone else can test the PR and approve it, I'd be grateful! I'm having a few issues with the local environment that I'll summarize below.

---



I think I've been able to reproduce the original issue on Jetpack `master`:
<img width="1910" alt="Screen Shot 2022-01-28 at 14 11 11" src="https://user-images.githubusercontent.com/1898325/151597833-c5315a45-a403-43f4-8c0a-efcf9dad827a.png">

When testing the PR locally, Jetpack seems to install fine (`jetpack install plugins/jetpack`) and the plugin appears activated, but I don't see the Tiled Gallery in the block picker. Other times I get the "Your installation of Jetpack is incomplete." error in the WordPress dashboard. I won't be able to continue looking into this today, but will be back Monday to continue testing.
