### ISSUE TITLE
Stats module: add secret JS key to reduce referrer spam

### ISSUE THREAD

**Issue by peterwilsoncc** [Automattic/jetpack#2248]
As many referrer spammers run the JavaScript by iterating blog ids without hitting the site, adding a secret key to the data sent to wp.com would help reduce referrer spam.

``` js
_stq.push(['view' {
  v:'ext',
  j:'1:3.5.3',
  blog:'123456',
  post:'0',
  tz:'10',
  srv:'example.com',
  secret:'4IAoQUvgCzEtML0X'}
]);
```

I've halved GA referrer spam with a similar technique using custom dimensions.

To prevent referrer spammers collecting an archive of secrets, the secret would ideally be a time based nonce - possibly with a longer life span the the WP default to account for page caching.

**Comment by georgestephanis** [comment]
Then it's just a question of them firing off a curl request to get it and inject it to the response, plus it would destroy stats working for anyone not currently on the most up to date version of the plugin.

It also may not be compatible with our aggregation system that pulls the data out of the requests -- the requested stats gif isn't actually a script that outputs the gif, stats are aggregated batched based on access logs of requests to an actual gif file.  Parsing secret keys would be a significant additional process to look up per site as opposed to just aggregating and saving.

Tagging Data Team for input (and to make sure I'm not completely in the wrong) (which could be)

**Comment by skeltoac** [comment]
I can see how this could work. Each site would have a unique secret shared with the Jetpack servers. It could be as simple as a random integer chosen during activation or upgrade. Each time the site generated a page it would use the secret to produce a unique nonce, valid for the next H hours, for the js client to sign its gif requests. No additional HTTP requests are used. Visitors won't notice any difference.

Then the nonces would have to be validated. Gifs from older versions of Jetpack would not be subject to this validation. We would not want to accept old-version gifs from spammers after the site had been upgraded, so we'd have to look up both the secret and the site's Jetpack version to validate every gif.

It is a trivial task to design such a system as a rough sketch. The actual code wouldn't be too hard, either. The up-front engineering costs are manageable. The ongoing costs of this gif validation scheme are much more significant. They include the cost to sites of generating nonces (no problem; it's fairly distributed across self-hosted sites) and the cost to wpcom of checking versions and validating nonces with very high throughput.

We have gone almost 10 years without adding per-site lookups to the stats parsers. It would be folly to imagine that we haven't seriously discussed this exact anti-spam idea at least three times in that interval.

We consistently reject this strategy because low barriers to spam only work at a small scale. When one or a handful of sites put up a low barrier, spammers don't care enough to bother updating their bots to step over the low barrier. They keep spamming the millions and their costs stay low. When the same low barrier suddenly appears on million of sites, spammers take notice because it affects their business. They have kids to feed. So they improve their scripts and raise their rates. Also, because of the design of the barrier, everyone using Jetpack now bears the extra load of spammer bots requesting pages just for the nonces they need.

So if you have a low barrier that works for you 50% of the time, you're better off keeping that barrier to yourself. Soon after you altruistically share your barrier with everyone, it becomes useful to no-one.

That's just my opinion. I could be wrong. The decision isn't mine to make. Ultimately we won't know if we don't try it. I hope that's enough disclaimers to encourage someone to seriously try it out.

**Comment by peterwilsoncc** [comment]
Thanks for such detailed feedback and insight, Automatticians, it's appreciated.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
