### ISSUE TITLE
Premium Content Block: Free Simple Sites display a "0" character after the upgrade nudge

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/jetpack#22636]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Go to a free Simple Site
2. Add a Premium content block
3. Notice that we display a "0" character above the Upgrade nudge.

### A clear and concise description of what you expected to happen.

There shouldn't be anything there.

### What actually happened

There's a "0" string displayed.

### Other information

![Screenshot 2022-02-03 at 10 54 37](https://user-images.githubusercontent.com/995955/152311368-47c2ec03-1337-43d6-9b01-2b0f9905560d.png)
![Screenshot 2022-02-03 at 10 54 43](https://user-images.githubusercontent.com/995955/152311380-839ed93c-2b18-4b24-b531-fc7a364cb915.png)

### Browser

Chrome/Chromium

**Comment by Copons** [comment]
@BogdanUngureanu I think this is caused by this check:

https://github.com/Automattic/jetpack/blob/5cecab97547246e8526b5d99fcdb663d7e0313c8/projects/plugins/jetpack/extensions/blocks/premium-content/edit.js#L367

If `selectedPlanId` is falsy, the second condition is not tested.
The expression returns `selectedPlanId`, which is `0`, which React can — and does 😄 — render.

In these cases, we should cast to boolean.
E.g. `!! props.attributes.selectedPlanId`
