### ISSUE TITLE
Form block inside FSE "On Submission" actions not working

### ISSUE THREAD

**Issue by ezebecke** [Automattic/jetpack#22696]
### Quick summary

Forms have three optional actions "on submission"

- Show summary of submitted fields
- Show a custom text message
- Redirect to another page

None of them seem to work when adding this block inside an FSE template. 

### Steps to reproduce

1- Add Form block to template
2- Test live form with any selection "on submission" option

### What you expected to happen

The form should display a custom message, redirect, or show submitted fields after submitting.

### What actually happened

Page refreshes and email is sent, but the "on submission" action doesn't happen. 

### Context

Tested on my own Atomic site. 

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Workaround details

Adding the Form block on a page.

**Comment by Greatdane** [comment]
Another report here; 36093109-hc

Looks like only certain templates. (I could reproduce on Single Item templates)

**Comment by jeherve** [comment]
cc @danielbachhuber who worked on #24727.

**Comment by danielbachhuber** [comment]
@Greatdane Would you be able to provide full reproduction steps? Thanks!

**Comment by Greatdane** [comment]
Sure @danielbachhuber 

1. Create a new template in FSE
2. Add a form block
3. On the form settings, choose redirect on submission and choose a URL
4. Save!

When you visit the page and submit the form, it does not redirect

Here is a video of it in action; 

https://user-images.githubusercontent.com/5075840/180941658-8527cbf1-a056-48d3-91d8-a6499068fcd3.mp4

**Comment by danielbachhuber** [comment]
@Greatdane Thanks! Your additional details are very helpful — I didn't even know that feature existed 😅 

Interestingly, this works in my local environment with the latest version of Jetpack and Gutenberg:

<img width="1593" alt="image" src="https://user-images.githubusercontent.com/36432/181028900-38fed2b8-fb9b-4f53-ba49-854b21198304.png">

https://user-images.githubusercontent.com/36432/181029063-1a681836-b886-49e4-bc77-a768b4f5cd06.mp4

However, I can reproduce the bug in the Atomic environment I created for the occasion:

https://user-images.githubusercontent.com/36432/181035710-2126874c-5a80-49ed-a190-5bb443217813.mp4

The underlying issue is that Atomic is using a `gutenberg/lib/compat/wordpress-5.9/template-canvas.php` fallback template. Here's a fix for it #25278

**Comment by Greatdane** [comment]
Awesome, thanks for the quick fix @danielbachhuber! ABSPATH strikes again.
