### ISSUE TITLE
Social Media Widget: pre-fill fields with values saved for each Publicize connection

### ISSUE THREAD

**Issue by bhubbard** [Automattic/jetpack#2272]
http://jetpack.me/support/social-links/

It would be really great when social links support is added to the theme, that we have a widget users can use to display the links for any widget area.

**Comment by kraftbj** [comment]
We have a widget going into the next release: https://github.com/Automattic/jetpack/pull/2230

At this time, it's a pretty simple widget—site admin would manually add the social network handles in the widget settings.

To make sure we're on the same page, would you like the widget values to be (pre-)populated with the values from Publicize, noting that we don't have to depend on theme support for social links to do that.

**Comment by bhubbard** [comment]
@kraftbj Glad to see this its already going into the next release. I think (pre-)populate it with the values from Publicize makes sense. I assume by (pre-)populating the user could still override and use a different profile url when they want.

**Comment by hannahwarmbier** [comment]
Is this widget going to replace social links? I would like to be able to add social icons to a theme without adding a widget area. I personally don't use Publicize so custom links would be great.

**Comment by jeherve** [comment]
@hannahwarmbier [Social Links](http://jetpack.me/support/social-links/) aren't going to be replaced by the new Social Media Widget, as they are quite different:
- Social Links are a theme feature, something you need to code into your theme or into a plugin.
- The Widget is there for all users, and you don't need to declare support in your theme.

However, what @bhubbard and @kraftbj suggested is to pre-fill the Social Media Widget whenever a Publicize connection exists for a Social Network.

**Comment by hannahwarmbier** [comment]
What I really want to know is can I or will I be able to include the social icons without adding a widget area? I'm developing a very minimal theme and I want to be able to include social icons in my sidebar without hardcoding the HTML/etc. Since Jetpack is widely used and I already have coded in support for some Jetpack modules, this would be the easiest way. I'm going to have a look at the source for the new widget and see if I can come up with a way to hack this but it would be nice if there could be a way to implement it, whether through add_theme_support or a shortcode.

**Comment by jeherve** [comment]
Yes, you can, thanks to the Social Links theme feature I linked to earlier. The support doc should help you understand how to add this to your theme.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
