### ISSUE TITLE
Calypso: Akismet Anti-Spam missing from Jetpack menu on Jetpack sites

### ISSUE THREAD

**Issue by kbrown9** [Automattic/jetpack#22967]
### Quick summary

When the Akismet plugin is active on a Jetpack site, the Akismet Anti-Spam submenu item is displayed under the Jetpack menu:

<img width="166" alt="Screen%20Shot%20on%202022-01-28%20at%2010-29-24" src="https://user-images.githubusercontent.com/50059399/151576586-7aa77b97-240b-457e-b0e9-10f1c0654596.png">

In Calypso, the Akismet Anti-Spam submenu item is not displayed:

<img width="274" alt="Screen%20Shot%20on%202022-01-28%20at%2010-30-01" src="https://user-images.githubusercontent.com/50059399/151576661-c575ebe0-3b7b-4e18-a591-2e711a1d105a.png">

This doesn’t affect Simple or WoA sites.

### Steps to reproduce

1. Create a Jetpack site and connect it to WordPress.com.
2. Install and activate the Akismet plugin on the site.
3. In wp-admin, notice the Akismet Anti-Spam submenu item under the Jetpack menu.
4. In Calypso, notice that there is not an Akismet Anti-Spam submenu item under the Jetpack menu.

### What you expected to happen

The Akismet Anti-Spam submenu item should be displayed in Calypso for Jetpack sites when the Akismet plugin is active.

### What actually happened

As shown in the screenshots, the Akismet Anti-Spam submenu item was not displayed in Calypso.

### Reproducibility

Consistent

**Comment by jeherve** [comment]
I believe this was done on purpose. You'll note that other submenu items are missing when in the Calypso view.

cc @mmtr and @cpapazoglou, who may know more about this since they worked on the nav-unification project.

**Comment by mmtr** [comment]
Correct, this is the intended behavior, since Nav Unification has never been enabled for Jetpack sites (p1HpG7-bjx-p2). That's also aligned with the Jetpack green-blue strategy (p6TEKc-4ar-p2), so we really don't want to send users from Calypso to WP Admin or vice versa.

Note that Jetpack users are able to manage the Akismet API key within Calypso from "Settings > Security":
<img width="1196" alt="Screen Shot 2022-02-18 at 11 51 50" src="https://user-images.githubusercontent.com/1233880/154669438-f3b707c2-1e13-420f-b9c9-2fd4f105acaa.png">
