### ISSUE TITLE
Pexels Featured Images do not Display Credits on Full Site Editing (FSE) Themes

### ISSUE THREAD

**Issue by macmanx2** [Automattic/jetpack#23408]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Add a featured image via Pexels.
2. Save
3. View the post.

### A clear and concise description of what you expected to happen.

I expected a credit to be displayed below the featured image, like in these screenshots from non-FSE themes:

Twenty Twenty:
<img width="712" alt="Screen Shot 2022-03-13 at 4 59 28 PM" src="https://user-images.githubusercontent.com/4856235/158085177-7842fc10-4faa-4804-8c51-79d882e967b1.png">

Twenty Twenty One:
<img width="734" alt="Screen Shot 2022-03-13 at 4 57 41 PM" src="https://user-images.githubusercontent.com/4856235/158085184-edde7931-17f6-4cc4-ab4f-58bbb27ed838.png">

### What actually happened

No credit is displayed, as you can see in these screenshots from FSE themes:

Twenty Twenty Two:
<img width="772" alt="Screen Shot 2022-03-13 at 4 56 10 PM" src="https://user-images.githubusercontent.com/4856235/158085208-b7653e91-bd43-4c30-a695-df74022147b2.png">

Stewart:
<img width="811" alt="Screen Shot 2022-03-13 at 4 56 49 PM" src="https://user-images.githubusercontent.com/4856235/158085223-767295ef-9b7e-48a0-bde4-6f2930874f36.png">

### Other information

Self-reported and reproduced on a simple WordPress.com site and a WordPress.org 5.9.2 site running Jetpack 10.7.

### Operating System

macOS

### OS Version

12.2.1

### Browser

Firefox

### Browser Version(s)

98

**Comment by samiff** [comment]
@macmanx2 Hey 👋 

It doesn't look like this issue is particularly related to Jetpack or the Pexels integration. The featured image metadata is persisted as expected, but the theme would be responsible for the display of the image caption.

Looks like the block themes rely on [wp:post-featured-image](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-library/src/post-featured-image) to show the featured image, which is a decent compromise when moving from an older theme to a new block theme. This block does not have an option to render the caption (credit) however.

For reference, it seems like there is some ongoing discussion around "featured images + blocks": https://github.com/WordPress/gutenberg/issues/27617

I've surfaced your concern in: https://github.com/WordPress/gutenberg/issues/40946
