### ISSUE TITLE
Subscription Block: Style switching not working on Site Editor.

### ISSUE THREAD

**Issue by yansern** [Automattic/jetpack#23481]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Go to the site editor.
2. Insert a Subscription Block.
3. Go to inspector sidebar, and change the style between Split & Compact.
4. It doesn't update the block on the editor.

### A clear and concise description of what you expected to happen.

It should update the block on the editor.

### What actually happened

Nothing happened.

### Browser

Chrome/Chromium

**Comment by mashikag** [comment]
What I can see so far is that the correct classes are being applied to the correct elements, i.e. `is-style-compact` and `is-style-split`. However it is as if the styles for those classes were not present in FSE mode, i.e. despite the class applied there is no styles applied.

Another observation I made that when I try the block in Gutenberg editor via local jetpack build it works as expected.

I need to drop off for a while, but I will do more investigation later.

**Comment by mashikag** [comment]
See the for a detailed investigation that was done on the issue.

Finally the issue was caused by stale wpcom cache of  the file at the following url `https://s0.wp.com/wp-content/mu-plugins/jetpack/_inc/blocks/editor-beta.css?minify=false`.

The fix was to invalidate the wpcom cache for the path. It was done via running the following command in my (no special permissions required) sandbox:
`echo '/wp-content/mu-plugins/jetpack/_inc/blocks/editor-beta.css?minify=false' | php ~/public_html/bin/invalidate-static-uris.php`
