### ISSUE TITLE
Subscriptions: Cannot see site followers when Site Stats is disabled.

### ISSUE THREAD

**Issue by RCowles** [Automattic/jetpack#237]
If subscriptions are enabled in Jetpack, but site stats are disabled, there appears to be no way to view that follower data. Attempts to visit the URL at `http://example.com/wp-admin/admin.php?page=stats&blog_subscribers` or to view the followers dashboard at `http://example.com/wp-admin/admin.php?page=stats` are met with:

> You do not have sufficient permissions to access this page.

It would be nice if Site Stats specific data was conditionally removed from that admin page and the requested follower data was displayed.

Original Trac ticket:
https://plugins.trac.wordpress.org/ticket/2076

**Comment by kraftbj** [comment]
This will be/has been added via People Management on WP.com.

**Comment by jeherve** [comment]
Reopening this as People Management is only available if you use the Manage Module. One should be able to use the Subscriptions module, and only that module, and still be able to access their subscriber list imo.

**Comment by kraftbj** [comment]
What about having a link available to the wp.com/my-stats page for subscribers to the blog? Realistically, that is more likely to happen anytime soon (and could be a community contribution). Would that be suitable?

**Comment by jeherve** [comment]
Where would you add that link? As a Jetpack sub-menu, in the description modal, or in Jetpack > Settings somewhere?

**Comment by kraftbj** [comment]
Open to ideas. My first IANADesigner spitball thought is in Settings->Discussions under 'Jetpack Subscriptions Settings'.

Perhaps with links to: 
```
if manage && connected account with access -> wp.com people management
elseif stats -> wp-admin stats 
else wp.com/my-stats or a new abstracted page based on /admin.php?page=stats&blog_subscribers
```
flow since people management has the most features (remove follower), but still providing the same access for non-connected accounts that can't view via wp.com as it stands now (e.g. with stats active), then provide something for admins with only subs.

Stretch goal would be to figure out how /admin.php?page=stats&blog_subscribers works and extract that out. It might mean, tbh, abstracting the stats.php to something like class.photon.php can can be used by multiple modules since I assume the stats API code would need to be used, or something that could leverage the JSON API, etc.

**Comment by jeherve** [comment]
This was recently fixed in Calypso:
https://github.com/Automattic/wp-calypso/issues/11308

**Comment by kraftbj** [comment]
If it's fixed in Calypso, I'm game to close the issue out.
