### ISSUE TITLE
Carousel: An underscore in the Image Description prevents the Description from being displayed

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#2401]
If your image has a description that has an underscore, the description will not be displayed. Note, however, that the description and underscore has to be in this format:

`description_here`

or 

`description_` (underscore at the end with no characters afterwards).

Something like this works with no problem:

`description _ here`

as does this:

`description_` (note the extra space after the underscore).

**Comment by richardmtl** [comment]
reported in 2247960-t

**Comment by osiux** [comment]
I traced this to https://github.com/Automattic/jetpack/blob/master/modules/carousel/jetpack-carousel.js#L1027-L1029, that's why it works if you have spaces in the description.

It seems that is there since the introduction of Carousel in Jetpack in 976c5a7 3 years ago.

Removing those lines fixes this issue, but I'm not entirely sure why is that there. If it's only to check if it's an empty value, it can be replaced by something else. Does anyone know?

**Comment by kraftbj** [comment]
I traced it back to r52467 in the wpcom codeback with the commit message: `adding parseTitleDesc() to define if/when we should show a title or description based on having no spaces but underscores, as well as based on common default image naming by cameras, scanners, mobile p\`

My assumption is it was added so when someone upload an image from a camera like `IMG_20150718_174348.jpg`, the title would automatically be set to `IMG_20150718_174348`, which is pretty ugly to display in a carousel.

But that accounts for the title, not the description. In short, not sure and open to change here.

**Comment by osiux** [comment]
I was thinking on maybe separate the `parseTitleDesc()` method in two, one for title and another one for description (or none). The title can stay the same as of now and throw something else for description, not sure how bad is to display something like IMG_20150718_174348 in the description.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
