### ISSUE TITLE
Enhancement: Fallback to Jetpack Search When Instant Search Fails

### ISSUE THREAD

**Issue by PlayaGroupLtd** [Automattic/jetpack#24019]
### Impacted plugin

Search

### What

Fallback to basis Jetpack search when Jetpack Instant Search Fails

### How

Jetpack Instant search stops working a lot i.e. it fails and in spite of my having Jetpack basic searched enabled concurrently basic search doesn't kick in and takeover search when Instant search fails (which happens a lot!) so my website ends up with no search.  This really should be setup this way so you don't render search completely dead at Wordpress websites running Jetpack Enhanced Instant Search.  Instant Search has failed several times at my website this year already and it's on the third week of April.  Unacceptable to be left with no active search at all.  Come on!

**Comment by jsnmoon** [comment]
Hi, could you describe how Instant Search is failing on your site? Do you see anything in the browser console or in your server error logs?

**Comment by PlayaGroupLtd** [comment]
You need to setup Basic Search to kick in automatically when Jetpack Instant Search fails which happens frequently in my experience.  That’s what I’m asking you to add to the mix.

Jetpack Instant Search just stops working and since Jetpack basic search, even though it’s also enabled doesn’t takeover when instant search stops working my website is left with no search at all and that’s unacceptable.


Michael
Luxe-Edit.com <http://luxe-edit.com/>


PS — as far as your two questions NO, and NO — no idea how to even access those things.

**Comment by bobmatyas** [comment]
You can find console errors using this guide: 

https://wordpress.com/support/browser-issues/advanced-browser-troubleshooting/#java-script-errors

For server logs, you can reach out to your hosting provider to see if any error logs were generated at the time Jetpack Instant Search failed and the standard search failed to render.

**Comment by PlayaGroupLtd** [comment]
How about you actually address the subject of my post to GitHub.
I’ve wasted enough time on this useless crap. I have a business to run.

I DON’T CARE ABOUT THIS DAMN LOGS —

**Comment by jsnmoon** [comment]
Hi Michael, 

Unfortunately, we are unable to investigate a fallback implementation without a better understanding of the failure mechanism causing Instant Search to malfunction on your site. Please provide us with additional details on how Instant Search is failing on your site if you'd like for us to continue looking into this.

Also, interacting on this repository requires adhering to the [code of conduct laid out here](https://github.com/Automattic/jetpack/blob/master/CODE-OF-CONDUCT.md#contributor-code-of-conduct) which ensures a harassment-free experience for all participants involved. I understand your frustration, but please refrain from adversarial behavior.

**Comment by PlayaGroupLtd** [comment]
My suggestion is PURE LOGIC your lame response below is an absurd ducking of the situation. Look into all of the Jetpack support tickets on this failure
for a product you charge $$$ for.  More often then not your Jetpack support staff had to conduct a hard reset to re-sync my website and then JP Instant Search would work again.  That’s on your, on your end.

What a waste of time!  This duck & dodge is insulting.  Granted I’m not one of your Wordpress VIP customers but I’m a Wordpress customer nonetheless.

**Comment by sdixon194** [comment]
Doing some further research, a fall back to classic search wouldn't be possible as a catch-all solution for instant search failing. It works quite differently, relies on different data for its index, and if the issue is with the API for example, search would break for both instant search and the fallback. I think it was definitely worth ruling that out as an option for fixing potential failures with Instant Search, so thanks for suggesting that. 

That said, if you're having an issue with Instant Search failing, that's definitely something we'd like to look into further! We'd need some more information to find out what the exact problem is. I believe you have opened tickets with our support team already, [but here is the contact form ](P1moTy-pc-p2?rel=support)in case you need it again.

I'm going to close out this issue as this particular suggestion won't be something we'll be able to implement, but I encourage you to reach out to support for further help troubleshooting your issue.
