### ISSUE TITLE
Payments: Add visual clues for donation products

### ISSUE THREAD

**Issue by Copons** [Automattic/jetpack#24074]
Users now have the ability to manually create products of type donations both in the editor and in the Calypso Earn section.

Donation products don't have any visual clue to distinguish them from regular products.

We should add some visual indications (label, icon, etc.) in the Product Management selector component in the editor, and in the Calypso Earn section.

| Editor | Calypso |
| - | - |
| <img width="466" alt="Screenshot 2022-04-25 at 15 31 18" src="https://user-images.githubusercontent.com/2070010/165110803-e062b46a-a0f3-4aa6-a1df-0df252dc03b8.png"> |  <img width="848" alt="Screenshot 2022-04-25 at 15 31 41" src="https://user-images.githubusercontent.com/2070010/165110827-7c0528f2-919b-41c1-9d00-4d3343ad8b68.png"> |

**Comment by BogdanUngureanu** [comment]
In Calypso I think adding a label after the name of the subscription would be similar to what we do in Calypso Pages with the "homepage" tag.
![Screenshot 2022-04-29 at 17 04 28](https://user-images.githubusercontent.com/995955/165960723-4ee72d37-789b-4c5c-bf7c-d50c6b364886.png)
![Screenshot 2022-04-29 at 17 03 27](https://user-images.githubusercontent.com/995955/165960671-13daa856-bbaa-40f6-b5b7-09f94a96859c.png)

We could also add an icon with a heart, since we already use one for the Donations block, so the label would look like ":heart: Donation"

As for the Editor, not sure. We don't have  enough real estate in that menu, so an icon would be ideal. However, not sure if it has enough context, since users might assume it's some kind of bookmarking button if we opt for the :heart: icon.

**Comment by Copons** [comment]
cc @SaxonF

**Comment by SaxonF** [comment]
I wonder if we need to differentiate as whether something is a donation or could we just rely on the name added by the customer? If a payment plan is marked as a donation, could we update the name of the plan to be something like "Monthly donation" if the plan name wasn't already changed? The same could be done for one-off payments.

This might be a silly question but can you mark a plan as a donation if added from Earn?

![image](https://user-images.githubusercontent.com/1072756/168206432-623bce03-bea3-4b80-aba7-5366755284df.png)

**Comment by Copons** [comment]
> This might be a silly question but can you mark a plan as a donation if added from Earn?

Not yet!
We have a PR ready to go, but were waiting for a JP release — which has happened now (cc @BogdanUngureanu): https://github.com/Automattic/wp-calypso/pull/62208

> I wonder if we need to differentiate as whether something is a donation or could we just rely on the name added by the customer? If a payment plan is marked as a donation, could we update the name of the plan to be something like "Monthly donation" if the plan name wasn't already changed? The same could be done for one-off payments.

Ah, something like this?
Normally the default product name is "Monthly subscription", but if the user flips some toggles, it could automatically be updated to something else, provided it hasn't been manually updated already.

E.g.
| Frequency | Type | Default Name |
| - | - | - |
| one-time | default | Payment |
| one-time | donation | Donation |
| monthly | default | Monthly Subscription |
| monthly | donation | Monthly Donation |
| yearly | default | Yearly Subscription |
| yearly | donation | Yearly Donation |

In the editor, we have used a fairly custom approach for the strings, which are controlled by the block, but it should be doable. 🤔

**Comment by SaxonF** [comment]
@Copons yep exactly!

**Comment by dsas** [comment]
#25397 fixes this for Jetpack, but the same change needs making in Calypso :)

**Comment by dsas** [comment]
Calypso change is at https://github.com/Automattic/wp-calypso/pull/66338
