### ISSUE TITLE
General: Mixed-case domain names cause connection issues?

### ISSUE THREAD

**Issue by aheckler** [Automattic/jetpack#2419]
I have a test site with settings like so:

![screen shot 2015-07-19 at 8 34 06 am](https://cloud.githubusercontent.com/assets/5512652/8765889/f59e2334-2df0-11e5-95bc-f7027342af0b.png)

Note the capital letters in the domain. When I connect that to WP.com, our debugger returns an unknown error:

http://jetpack.me/support/debug/?url=http%3A%2F%2Ftestingcapdomain.nfshost.com%2F

... and I can't update plugins from WP.com:

![screen shot 2015-07-19 at 8 37 33 am](https://cloud.githubusercontent.com/assets/5512652/8765905/7b1cd76c-2df1-11e5-9d82-32e3ac14eb59.png)

My in-dash debug links says everything is OK though:

![screen shot 2015-07-19 at 8 36 11 am](https://cloud.githubusercontent.com/assets/5512652/8765895/3a46e00c-2df1-11e5-92fa-673fede3a2c1.png)

The old debugger returns: `"-10520: Jetpack: [invalid_signature] The required "url" parameter is malformed."`

To repro, just connect a site to JP with the Site and Home URL as mixed case.

**Comment by dereksmart** [comment]
I can't reproduce.  Did you try this on any other hosts?

**Comment by aheckler** [comment]
Happened for me on NearlyFreeSpeech.NET and the user who brought this to my attention (in 2200215-t) is on BlueHost. I can maybe screenshare with you at some point and walk you through it if you want.

**Comment by dereksmart** [comment]
After extensive debugging and testing, we've learned a few things: 

- The debugger had a minor glitch (fixed dotcom side)
- update failures from dotcom were because FTP creds were required (fix is to <a href="https://codex.wordpress.org/Editing_wp-config.php#WordPress_Upgrade_Constants">set the creds in wp-config</a>)
- mixed case domains inherently don't cause any problems.
