### ISSUE TITLE
Subscription form widget and shortcode not working

### ISSUE THREAD

**Issue by rilwis** [Automattic/jetpack#24612]
### Impacted plugin

Jetpack

### Steps to Reproduce

Hi, I'm using the subscription widget and it doesn't work. Here are the steps:

1. Go to https://metabox.io/blog/
2. Enter email to the subscription form on the sidebar
3. Click Subscribe button

It happens for the subscription shortcode, too:

1. Go to https://metabox.io/newsletter/
2. Enter email to the subscription form on the sidebar
3. Click Subscribe button

### A clear and concise description of what you expected to happen.

A new email should be subscribed to the newsletter. But it shows an error while subscribing.

### What actually happened

An error message is shown.

### Operating System

Windows, macOS

### Browser

Chrome/Chromium, Firefox, Safari

**Comment by jeherve** [comment]
Your site doesn't seem to be properly connected to WordPress.com at the moment, which is why you're not able to use features that rely on a WordPress.com connection, like Subscriptions.

Could you try to go to the Jetpack menu in your dashboard, scroll down to the connections area, click on the link to manage your connection, and then disconnect from WordPress.com? You will then be able to reconnect, and things should work better after that.

Let me know how that goes!

**Comment by rilwis** [comment]
Hi @jeherve , you're right! I've reconnected with WordPress.com and the problem is solved!

Thank you very much!
