### ISSUE TITLE
Social sharing: Use incorrect post url

### ISSUE THREAD

**Issue by ferllings** [Automattic/jetpack#24693]
### Impacted plugin

Social

### Steps to Reproduce

1. Enable the sharing button
2. Go on any page
3. Click on Share with Twitter

### A clear and concise description of what you expected to happen.

Twitter should open with the correct link embedded

### What actually happened

The link, in the tweet, incorrectly matches a random, old post

### Other information

Can be tested here: https://www.ejiltalk.org/the-far-reaching-us-proposals-to-amend-the-international-health-regulations-at-the-upcoming-75th-world-health-assembly-a-call-for-attention/

### Browser

Other / Not applicable

**Comment by jeherve** [comment]
I can see the issue on your site, and I see that it doesn't happen for all posts, but only for some of them. I wonder if this may be caused by a code snippet or another plugin that would impact permalinks (post URLs) for specific categories or posts.

Could you try to deactivate each one of your plugins, one at a time, and let me know if you find that the problem disappears after deactivating a specific plugin?

Thank you.

**Comment by ferllings** [comment]
I figured out the plugin: co-author plus

https://wordpress.org/plugins/co-authors-plus/

**Comment by jeherve** [comment]
Did you find out why the plugin changes the permalink on those specific posts?

**Comment by ferllings** [comment]
Not yet: I've posted a message on the support page.

**Comment by ferllings** [comment]
With the help of the CoAuthorsPlus devs, I was able to find the problem in a loop, that was missing wp_reset_postdata()
Problem solved.
Thanks!
