### ISSUE TITLE
Sharing: Reddit: official button should open Reddit in a new window

### ISSUE THREAD

**Issue by c3zh** [Automattic/jetpack#2481]
While Twitter and Facebook open a pop-up window for sharing, the user notes that the official Reddit button takes people off the page. She requests that people can share while staying on the same page.

Suggested in 2284907-t

**Comment by jeherve** [comment]
The problem is that Reddit doesn't offer an interface that would allow you to share a post from a small pop-up window.

The login form itself is responsive, so having it in a pop up would work, but the link submission form isn't really designed to live in a small window. Here is how it would look in a small pop up:

![screen shot 2015-08-05 at 6 58 27 pm](https://cloud.githubusercontent.com/assets/426388/9092068/187be2f4-3ba4-11e5-9b29-7200e62ea321.png)

Until Reddit improves the link submission form and makes it responsive, I'm afraid we will have to open the Reddit sharing window in a full window.

**Comment by aheckler** [comment]
Going to reopen this since, as it stands now, when a user is using the official buttons the Reddit iframe opens the link in the existing tab. It does have a parameter to open in a new tab though.

You can see it on line 86 here: https://www.reddit.com/static/button/button-embed.js
