### ISSUE TITLE
WordPress.com notifications and comments not working with Firefox cookie isolation

### ISSUE THREAD

**Issue by muffinpeace** [Automattic/jetpack#24832]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Spin up a new WordPress website with the latest WP version (v6.0).
2. Install Jetpack and connect it using a WordPress.com account.
3. On the WP-Admin dashboard or the website front-end, select the comments option from the admin toolbar:

![Annotation on 2022-06-23 at 16-47-25](https://user-images.githubusercontent.com/426388/175342444-29dc6686-9c9a-46f0-a4ec-267b65262bd5.png)

### A clear and concise description of what you expected to happen.

WordPress.com notifications and comments being shown.

### What actually happened

The loading animations keeps on spinning.

### Operating System

macOS

### Browser

Chrome/Chromium, Firefox

**Comment by jeherve** [comment]
I cannot seem to reproduce on my end, in Chrome and in Firefox. Could you tell me more about your setup?

- When seeing this, are you logged in to WordPress.com?
- Do you use any privacy / anti-tracking browser extensions or services, that may block some of the calls in your browser?
- Do you see any errors in your browser's JavaScript console?

********

**Note**: I updated your comment to upload the screenshot to GitHub directly instead of using Droplr. See this post for more info: pbg9X-fWF-p2

**Comment by hahntech** [comment]
> I cannot seem to reproduce on my end, in Chrome and in Firefox. Could you tell me more about your setup?
> 
>     * When seeing this, are you logged in to WordPress.com?
> 
>     * Do you use any privacy / anti-tracking browser extensions or services, that may block some of the calls in your browser?
> 
>     * Do you see any errors in your browser's JavaScript console?
> 
> 
> **Note**: I updated your comment to upload the screenshot to GitHub directly instead of using Droplr. See this post for more info: pbg9X-fWF-p2

1. Yes, I am logged into Wordpress.com when this problem occurs. I have tried it both ways, while logged into Wordpress.com and while logged out. There is no change for either method
2. I am using Firefox for Mac version 101.0.1 using default settings and no extensions. Even tried it using the Private browse window to make sure cookies were not causing the issue. I also tried it using Safari for Mac version 15.5 and the same exact issue occurs. I also tried this from a Windows device using MS Edge version 103.0.1264.37. I also tried this using an iPad. Safe to say this issue is somehow tied to my website configuration rather than any devices I am using. 
3. Yes, there are several errors being generated and I am not sure which ones are relevant. I am happy to provide a list of the errors. Just let me know which error messages I should provide. However the following error message seems to most likely tied to this current issue: **"Firefox can’t establish a connection to the server at wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data."**

I appreciate you taking the time to examine this. Please let me know if I can provide any other details to assist in the resolution.

**Comment by jeherve** [comment]
Thank you for the extra details.

> However the following error message seems to most likely tied to this current issue: "Firefox can’t establish a connection to the server at wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data."

That's helpful. I believe you're running into the same error that was discussed in #9170.

However, since logging into your WordPress.com account didn't help, it would seem, as you mentioned , that the issue may be tied to something tied to your site setup.

Would you mind pasting the other errors in a new comment? They may tell us more about the problem.

Could you also let me know if you use any caching or performance plugin that may impact the way JavaScript is loaded on your site?

Thank you.

**Comment by hahntech** [comment]
Here are the other errors which appear to be related to the issue. There is a Jscript error being triggered from a plugin I use for the Q&A Forum but I don't think it's impacting the Jetpack comments panel. 

These errors show up in red. There are many errors marked in yellow but none of them seem to have anything to do with Jetpack. But I have very little experience with this stuff. I can open the website inspection panel and read errors. I have no idea what they mean or how to fix them. 

GETwss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data
[HTTP/1.1 403 Forbidden 178ms]

Firefox can’t establish a connection to the server at wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data. [rest-proxy:16:5479](https://public-api.wordpress.com/wp-admin/rest-proxy/?v=2.0#https://widgets.wp.com)
GETwss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data
[HTTP/1.1 403 Forbidden 184ms]

Firefox can’t establish a connection to the server at wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data. [rest-proxy:16:5479](https://public-api.wordpress.com/wp-admin/rest-proxy/?v=2.0#https://widgets.wp.com)
GETwss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data
[HTTP/1.1 403 Forbidden 178ms]

Firefox can’t establish a connection to the server at wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data.

If needed, I can create an admin user on my staging site and let you log in and dig deeper. Just let me know how to pass along those credentials if you need them. 

Thanks again for your time on this.

**Comment by jeherve** [comment]
> If needed, I can create an admin user on my staging site and let you log in and dig deeper. Just let me know how to pass along those credentials if you need them.

That may indeed be helpful. Could you contact us via [this form](https://jetpack.com/contact-support/?rel=support&hpi=1) and mention this issue? We'll then send you a secure form where you'll be able to share credentials with us.

Thank you!

**Comment by hahntech** [comment]
Just a quick update. My schedule has been completely full and I will have time to perform these next steps on Monday July 4th.

**Comment by hahntech** [comment]
Thanks. I have submitted the support ticket as instructed.

**Comment by sdixon194** [comment]
Just noting I'm able to reproduce this consistently on Firefox with both my test site and brand new sites, on multiple versions of Jetpack and WordPress.

**Comment by brucea8c** [comment]
Hi @hahntech 

Would you be able to check if it works with third-party cookies enabled? or alternatively, logging out and logging in to wordpress.com after connecting the Jetpack site?

**Comment by hahntech** [comment]
> Hi @hahntech
> 
> Would you be able to check if it works with third-party cookies enabled? or alternatively, logging out and logging in to wordpress.com after connecting the Jetpack site?

Well we've already tried logging out and back into wordpress.com and that did not work. But I tried it again at your request and there is no change. The issue remains. I am using Firefox and there is no setting I can find for blocking or allowing third party cookies. The current version of Firefox only provides three options (standard, strict and custom). Main is set to default settings (standard) and none of those options indicates whether third party cookies are allowed or blocked. 

The issue is also present when I log into my website from Safari. There again, there is nothing in the settings for Safari that specifically states third party cookies are allowed or blocked. The only setting that looks like it may impact this issue is one to prevent cross-site tracking. However the issue is present regardless whether that setting is turned on or off. 

I have also tested this on other devices, including a Window 11 PC as well as an iPad. The issue is present everywhere I log into the admin panel of my website.

**Comment by lsl** [comment]
Thanks for ruling out other cookie problems with the re-login attempt @hahntech. 

I did a little digging and think this is likely due to Firefox's new [cross-site cookie isolation](https://blog.mozilla.org/security/2021/02/23/total-cookie-protection/). This was rolled out as [the default setting last month](https://blog.mozilla.org/products/firefox/firefox-rolls-out-total-cookie-protection-by-default-to-all-users-worldwide/). The notifications feature leverages cross site cookies for authentication with WordPress.com (where the notifications panel loads from). I'm guessing these cookies are now being isolated similar to how Safari [sandboxes cookie domains with ITP](https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/).

We'll need to look at a real fix for this but as a temporary workaround you can switch to less strict cookie blocking behavior in the privacy settings page: `about:preferences#privacy`.

Choose to only block "Cross-site tracking cookies". Clicking "Reload All Tabs" after was enough to bypass the restriction and load notifications for my test site.

![Screenshot_2022-07-13_13-33-28](https://user-images.githubusercontent.com/811776/178644930-37dc713d-a146-4a12-8d98-c92a7e482745.png)

You can access this page through browser settings or the shield icon in the URL bar:

![Screenshot_2022-07-13_13-39-43](https://user-images.githubusercontent.com/811776/178645543-df3bde17-ccb9-4dab-b4d6-85dd2ca4f6e9.png)

**Comment by hahntech** [comment]
> Thanks for ruling out other cookie problems with the re-login attempt @hahntech.
> 
> I did a little digging and think this is likely due to Firefox's new [cross-site cookie isolation](https://blog.mozilla.org/security/2021/02/23/total-cookie-protection/). This was rolled out as [the default setting last month](https://blog.mozilla.org/products/firefox/firefox-rolls-out-total-cookie-protection-by-default-to-all-users-worldwide/). The notifications feature leverages cross site cookies for authentication with WordPress.com (where the notifications panel loads from). I'm guessing these cookies are now being isolated similar to how Safari [sandboxes cookie domains with ITP](https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/).
> 
> We'll need to look at a real fix for this but as a temporary workaround you can switch to less strict cookie blocking behavior in the privacy settings page: `about:preferences#privacy`.
> 
> Choose to only block "Cross-site tracking cookies". Clicking "Reload All Tabs" after was enough to bypass the restriction and load notifications for my test site.

Thanks for those instructions. I tested this out for my site and the Jetpack comments panel immediately began working. You mentioned this issue is similar to the way Safari sandboxes cookie domains. I hope that whatever solution Jetpack developers are working on will be applicable to all web browsers and not just Firefox. For now I have restored my default privacy settings on Firefox and will just have to live with this limitation until a solution is published.
