### ISSUE TITLE
Form block: checkbox group doesn't display item with option set to 0

### ISSUE THREAD

**Issue by bindlegirl** [Automattic/jetpack#24885]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Create a new post and add a form to it.
2. Add a checkbox group with several options.
3. View the post. 

### A clear and concise description of what you expected to happen.

Option with value 0 should show up.

### What actually happened

The option is missing.

### Other information

When adding the single checkbox, the problem doesn't appear.
<img width="560" alt="Screen Shot on 2022-06-29 at 14-06-52" src="https://user-images.githubusercontent.com/1242807/176432432-02d76bd8-cc4f-4cdd-abd9-e25a33bd7b7b.png">
<img width="291" alt="Screen Shot on 2022-06-29 at 14-01-11" src="https://user-images.githubusercontent.com/1242807/176432443-04b1b87f-17db-40af-8a8d-3fa20006eb59.png">

### Reproducibility

Consistent

### Browser

Firefox

**Comment by anomiex** [comment]
Probably it's a use of an implicit boolean cast somewhere in `projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php`. PHP treats `0` and `'0'` as falsey.

The `if ( $option )` in this function looks suspicious: https://github.com/Automattic/jetpack/blob/f55374155b9a558f1c1c35e96d81b6f9a15def7b/projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php#L4370-L4383

If that turns out to be it, I see similar code in `render_radio_field()` and `render_select_field()`. I'd check if those have the same bug.

**Comment by coder-karen** [comment]
Related: #17866
