### ISSUE TITLE
Form block: inconsistent text colors between editor and frontend

### ISSUE THREAD

**Issue by bindlegirl** [Automattic/jetpack#24928]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Add a form block to the post and add some multiple checkbox and radio buttons to it.
2. Change text color.

### A clear and concise description of what you expected to happen.

Colors should change in the editor as well to be consistent with the actual change.

### What actually happened

Colors will be changed on the frontend but options will still have unchanged color in the editor.

### Other information

<img width="753" alt="Screen Shot on 2022-07-01 at 12-00-21" src="https://user-images.githubusercontent.com/1242807/176873167-ee62433a-559d-4a62-81d9-d06f992ac79e.png">

### Reproducibility

Consistent

### Browser

Firefox

**Comment by bindlegirl** [comment]
@ivan-ottinger I noticed you worked on form block colors here: #22465
Is this issue something you can check out?

**Comment by ivan-ottinger** [comment]
Thanks for the ping @bindlegirl!

The issue seems to come from the fact that a couple of styles (including the user agent stylesheet) are overriding the color selected in the editor:
![Markup on 2022-07-01 at 13:34:53](https://user-images.githubusercontent.com/25105483/176887044-60e25c88-aad8-4d30-b00d-eb4c3f3f3ec5.png)

I am looking at how to best fix the issue. Probably applying `color: inherit;` on the checkbox `<input>` element will work, but I need to test it.

**Comment by samiff** [comment]
Another report from internal testing for differences of style between editor & frontend: p8oabR-T0-p2#comment-6463

**Comment by ivan-ottinger** [comment]
> Another report from internal testing for differences of style between editor & frontend: p8oabR-T0-p2#comment-6463

Thanks for the report @samiff. This one looks to be related to the issue reported in https://github.com/Automattic/jetpack/issues/23114 (@mashikag - thanks for highlighting the issue) - which is also in our team backlog and we will get to it.

I have added your report as a comment to that second issue thread.
