### ISSUE TITLE
Blocks: make design tools panel open by default

### ISSUE THREAD

**Issue by mashikag** [Automattic/jetpack#24957]
> it’s bit strange that the color/padding/etc areas have to be selected first and don’t just appear when that section is opened in the block settings.

### Internal references
- p8oabR-Oy-p2#comment-6044
- pdDOJh-6-p2

Related: #23110

**Comment by JuanLucha** [comment]
Hi!
@ivan-ottinger and myself where triaging this and these are some conclusions:

a) the request seems to be to apply this behavior to all the jetpack blocks. In order to do that, the change has to be applied to each block individually, there is no way to make this a general way as each block manages these options in its own way
b) even when this is something that would benefit our users as a quality of life enhancement, we are not sure this is something we get a lot of feedback about from them at the moment.

Based on those conclusions, I wonder if we should do this now or de-prioritize it.
Any thoughts on this, @Automattic/apex

**Comment by yansern** [comment]
Deprioritize it.

Thanks for triaging, now we know what amount of effort it'll take. :)
