### ISSUE TITLE
get_term_by() test logic can return null.

### ISSUE THREAD

**Issue by charlestonsoftware** [Automattic/jetpack#2497]
See https://core.trac.wordpress.org/attachment/ticket/33281/

You are likely being bitten by the same logic bug that I've been chasing in my Store Locator Plus code by testing the "falseness" of get_term_by().     See class.wpcom-json-api-list-posts-v1-1-endpoint.php for example:
            $category = get_term_by( 'slug', $args['category'], 'category' );
            if ( $category === false) {
                $query['category_name'] = $args['category'];
            } else {
                $query['cat'] = $category->term_id;
            }

get_term_by() can return null, not just false or WP_Error.

It may help to test for this instead:
if ( ( $category === false ) || is_null ( $category ) ) {

Not a specific bug/issue but something to be aware of since you are testing for false in some of your get_term_by() calls.

**Comment by kraftbj** [comment]
For easy reference to the specific mention: https://github.com/Automattic/jetpack/blob/master/json-endpoints/class.wpcom-json-api-list-posts-v1-1-endpoint.php#L174-L181

`get_term_by` used in:
/class.json-api-endpoints.php
/json-endpoints/class.wpcom-json-api-list-posts-endpoint.php
/json-endpoints/class.wpcom-json-api-list-posts-v1-1-endpoint.php
/json-endpoints/class.wpcom-json-api-update-post-v1-2-endpoint.php
/json-endpoints/class.wpcom-json-api-update-taxonomy-endpoint.php
/modules/theme-tools/featured-content.php

cc: @justinshreve since most of the instances are within the API.

**Comment by jeherve** [comment]
I believe this was fixed in Core in https://core.trac.wordpress.org/ticket/21760

Let's reopen if this becomes an issue again.
