### ISSUE TITLE
Slideshow Block not visible when added inside Row block

### ISSUE THREAD

**Issue by devNigel** [Automattic/jetpack#25101]
### Quick summary

Slideshow Block is not visible when added inside Row block. I was able to reproduce the issue on Simple and Atomic sites.

1. With FSE theme, the Slideshow block images are not visible on editor or live page.
2. With Classic theme,  the Slideshow block images are visible on editor or but not on live page.

### Steps to reproduce

1. In an Atomic or Simple site, open page eidtor.
2. Add Row block.
3. Add Slidehsow block inside the row block and add images.
4. You will notice that the images are not showing up on the editor or live page in the case of FSE theme. In case of Classic theme, the slideshow images are visible only in the editor, but not in the live page.

Screenshot ( FSE theme ):

Editor:

<img width="1316" alt="Screenshot on 2022-07-15 at 14-48-53" src="https://user-images.githubusercontent.com/426388/179194817-f53504b3-d0c8-4572-957d-3f2d8ff83850.png">

Live page:

<img width="1129" alt="Screenshot on 2022-07-15 at 14-50-06" src="https://user-images.githubusercontent.com/426388/179194842-5664190b-3735-454d-97f3-15187af10b82.png">

Screenshot ( Classic theme ):

Editor: 

<img width="1435" alt="Screenshot on 2022-07-15 at 14-44-13" src="https://user-images.githubusercontent.com/426388/179194859-2611fc18-4ef8-4c29-a0fc-4b0de0f79166.png">

Live page:

<img width="1139" alt="Screenshot on 2022-07-15 at 14-37-32" src="https://user-images.githubusercontent.com/426388/179194891-434ce125-f231-4413-ac6e-f437dd883b2f.png">

### What you expected to happen

Slideshow image to be visible on editor and live page.

### What actually happened

Slideshow images were not visible.

### Context

User report: 35867969-hc

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

Was able to reproduce on FSE and Classic theme.s

### Reproducibility

Consistent

### Severity

All

**Comment by devNigel** [comment]
Not able to upload screenshots to github. Please try adding screenshots. Thanks.

**Comment by jeherve** [comment]
> Not able to upload screenshots to github. Please try adding screenshots

I took care of that for you.

Since the slideshow block is developed in the Jetpack repository, I"ll move your issue there.

**Comment by jeherve** [comment]
Somewhat related: #22834

**Comment by cuemarie** [comment]
📌 SCRUBBING
- Tested on P2 ✅ 
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 
- Replicable on Core - Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
- I'm able to replicate this issue consistently across Simple, AT, and Self-Hosted sites, as well as P2. 
- As described above, Classic Themes could display the Slideshow in the Editor, but it was still missing on the live site. FSE themes (and P2) did not display the slideshow in the editor or the live site.

### P2 Site:

![Screen Capture on 2022-07-28 at 10-58-11](https://user-images.githubusercontent.com/27249804/181606156-dbbf38c3-b2f3-4d6c-ae44-f6fe76fc1d30.gif)

### Self-Hosted Site:

**Editor**
<img width="1370" alt="Screen Shot 2022-07-28 at 11 07 00 AM" src="https://user-images.githubusercontent.com/27249804/181607100-12560e1f-546b-4bd2-a2e2-c1f806c81be6.png">

**Live Site**

![Screen Capture on 2022-07-28 at 11-07-46](https://user-images.githubusercontent.com/27249804/181607381-952d5308-ff5b-42a8-b3a4-537130c37f58.gif)

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by dsas** [comment]
I'm not sure if this is a symptom or a cause but when the slideshow is contained by a row block something is setting a really big width style on the swiper wrapper:

`<ul class="wp-block-jetpack-slideshow_swiper-wrapper swiper-wrapper" style="width: 71582800px; transition-duration: 0ms; transform: translate3d(-17895700px, 0px, 0px); height: 951px;" id="swiper-wrapper-04f0905eaa699738" aria-live="polite">`

and similarly for its children.

When the slideshow is not contained by a row block, it gets set to something more sensible sounding.

I think [this is because a flex-item will use `min-width:auto` by default](https://stackoverflow.com/questions/36247140/why-dont-flex-items-shrink-past-content-size), which means the content is as wide as the space necessary. Setting a `min-width:0` on the flex-item element, will fix that.

Unsure how to usefully make that happen from within this block 🤔 recurse upwards through the parents before setting a `min-width:0` if it is set to `min-width:auto`. Seems risky.
