### ISSUE TITLE
Payment Button: Impossible to read upgrade banner

### ISSUE THREAD

**Issue by ianstewart** [Automattic/jetpack#25102]
Example:

![image](https://user-images.githubusercontent.com/545779/178289443-e9d620c4-e478-4a15-8a82-c2e5adb195fc.png)

In context, in case it's theme related:

![image](https://user-images.githubusercontent.com/545779/178289545-8f96b5ba-b6ea-4b09-a2c6-d54083ed28c8.png)

**Comment by coder-karen** [comment]
I can replicate this - only on a WordPress.com simple site (both in Calypso and wp-admin), and when adding any Payments block within a Column block (minimum number of columns is 3, of equal size):

<img width="932" alt="Screenshot 2022-07-15 at 15 40 07" src="https://user-images.githubusercontent.com/16754605/179246574-c66e5cc2-fd1a-413c-921a-a8339e75c265.png">

Same result (text cut-off) in any theme I've tested.

**Comment by dsas** [comment]
Looks like there are two issues with this upgrade nudge: 
 1. The div with the black background sometimes has a too small height. This can make it look cut-off or otherwise tricky to read.
 2. The block toolbar menu hovers over the top of the nudge obscuring it. i.e. it's a recurrence of #23248

The small height could be fixed by removing the fixed `height`s from paid-blocks/editor.scss + maybe some other css tweaks to keep it looking good

The block toolbar position looks like it could be resolved by moving the nudge in the HTML so that it is inside the block is nudge is for (but not inside it's inner div). This would mean the toolbar position is calculated correctly. Unfortunately that looks like a pain due to the way this is implemented. I'll see if I can do something with CSS first.

**Comment by dsas** [comment]
The way that the CSS avoids the block toolbar menu from covering the nudge + content is by setting the nudge to display the nudge height + half the height of the toolbar away from the top and then make the actual block have a padding-top equal to the height of the nudge so that the toolbar leaves that much space when calculating it's position.

In order to know the height of the nudge it hardcodes it to 48px. Where the content is narrow the height of 48px is insufficient and the content bursts the nudge box.

The toolbar is positioned relative to the content - the actual block with the clientId

I think the CSS might be slightly overcomplicated and could be simplified (but I could be missing something). We'll always be left with one element (the content) needing to know the height of another (nudge) in order to leave space for the block toolbar.

If the nudge was inside the actual block with the clientId, we'd get this free, but so far as I understand it this can't really work with the nudge being a HOC that wraps the given blocks. Instead we'll have to make [`with-upgrade-banner`](https://github.com/Automattic/jetpack//blob/a99e0ccac5aeb9092b5c01d75af6846386182738/projects/plugins/jetpack/extensions/extended-blocks/paid-blocks/with-upgrade-banner.jsx) communicate the computed height of [`upgrade-nudge`](https://github.com/Automattic/jetpack//blob/a99e0ccac5aeb9092b5c01d75af6846386182738/projects/plugins/jetpack/extensions/shared/components/upgrade-nudge/index.jsx) to it's `BlockListBlock`

**Comment by mmtr** [comment]
> If the nudge was inside the actual block with the clientId, we'd get this free, but so far as I understand it this can't really work with the nudge being a HOC that wraps the given blocks.

Could we achieve that if the nudge is rendered via [the `editor.BlockEdit` filter](https://github.com/WordPress/gutenberg/blob/6ecb4c7740c3767f30878a3c639367a290dbbfba/docs/reference-guides/filters/block-filters.md) instead of using the `editor.BlockListBlock` filter?

https://github.com/Automattic/jetpack/blob/5e97040ad217da10434cbe6f0ba31b0b499388a6/projects/plugins/jetpack/extensions/extended-blocks/paid-blocks/index.js#L49

**Comment by dsas** [comment]
Unfortunately no, that doesn't seem to work either. The `editor.BlockEdit` filter has the same problem. The editor.BlockEdit filter gives you the block with the clientId, but you can't put the `UpgradePlanBanner` inside that.


In both cases, even though the HOC gets different components (BlockEdit is a component wrapped with InspectorControls, ToolbarControls etc, BlockList is a component wrapped with FontSizeInlineStyles) I get the same HTML in the editor:

![image](https://user-images.githubusercontent.com/93301/183674191-663c9830-90eb-4a45-a5ea-34e02030eddb.png)

 * The bare div is a wrapper div I added for testing
 * div.is-jetpack-reccuring-payments-paid-block is the upgrade nudge
 * div#block-f1c606b3-etcetc is the given component to be wrapped.

**Comment by mmtr** [comment]
> The `editor.BlockEdit` filter gives you the block with the clientId, but you can't put the UpgradePlanBanner inside that.

Would [the `blocks.registerBlockType` filter](https://github.com/WordPress/gutenberg/blob/c4bdc602cce6b885eca90a538a412d7175039689/packages/blocks/src/store/actions.js#L60) allow that? That's what we use for changing the `edit` component of the `core/video` block to support VideoPress:

https://github.com/Automattic/jetpack/blob/f5f70bf4c2bdbe07ce9188945c0235870d084bb1/projects/plugins/jetpack/extensions/blocks/videopress/editor.js#L389

**Comment by mmtr** [comment]
Probably not, I guess the `settings.edit` component available in that filter would be the same one that is provided by the `editor.BlockEdit` filter.

Looks like our only option left is to compute the height with JS and use it in the nudge styles.

**Comment by dsas** [comment]
@SaxonF, wondering if you can give some design input on this?

For premium blocks we prompt the user to upgrade their plan to get access. This is done by displaying a pink dot on the block in the inserter, and once inserted by showing an upgrade nudge when the block is selected 

Block list | Nudge
-------|------
 ![image](https://user-images.githubusercontent.com/93301/186149488-123c6bf4-2793-44c1-8ebd-e276aa148d08.png) | ![Woav99.png](https://user-images.githubusercontent.com/93301/186149608-6d4fdedb-c8ce-4c9c-8921-2525f1cc9a3c.png)

When the block is inside a narrow width, such as when inside a gutenberg column block, the nudge doesn't display correctly - the text overflows the container and additionally is obscured by the gutenberg toolbar. You can see this in various screenshots above. For various technical reasons (see above & linked pr), this is difficult to fix with the current design. 

Another flaw with the current design, is that selecting the content bumps it down so that it can fit the nudge inside the canvas, which is a bit jarring at best:

https://user-images.githubusercontent.com/93301/186151266-b28e9cac-ca50-4207-a2b1-07940193da88.mp4

Have you got any other design proposals that take the nudge out of the canvas? Perhaps we can attach something to the Gutenberg toolbar which floats above the content, fix something to the top of the viewport, or something completely different?

**Comment by SaxonF** [comment]
> Have you got any other design proposals that take the nudge out of the canvas? Perhaps we can attach something to the Gutenberg toolbar which floats above the content, fix something to the top of the viewport, or something completely different?

The canvas definitely doesn't feel like the right place for this. Could we move into the sidebar inspector which may be a more appropriate place?

**Comment by dsas** [comment]
I wondered about that too @SaxonF , I _think_ that's actually one of the easier options technically, but I had two main concerns:

 1. Will that work well on mobile? The sidebar inspector is full screen there. It might be confusing if after the block is inserted the sidebar just takes over the screen. If you don't show the sidebar then the nudge will be missed. If you don't show the sidebar when the block is selected then the nudge could be forgotten.
 2. Is it noticeable enough on desktop?

**Comment by mmtr** [comment]
> Will that work well on mobile? [...] If you don't show the sidebar then the nudge will be missed

This is also a concern for desktop, since users have the ability to hide the sidebar.

**Comment by mmtr** [comment]
If we decide to stick with the current placement, I opened https://github.com/Automattic/jetpack/pull/25812 (still WIP) to move the upgrade banner inside the block markup which has the nice side effect of allowing us to remove the fixed height that was causing the issue.

<img width="748" alt="Screen Shot 2022-08-24 at 17 51 28" src="https://user-images.githubusercontent.com/1233880/186464924-a58bcfb2-e99b-4ca6-85d3-a895ece829e5.png">

**Comment by mmtr** [comment]
> Could we move into the sidebar inspector which may be a more appropriate place?

FWIW, we had the banner there as well. It was introduced by https://github.com/Automattic/jetpack/pull/16603 and removed by https://github.com/Automattic/jetpack/pull/18604. The reasoning behind the removal is noted in https://github.com/Automattic/jetpack/pull/18604#issuecomment-777837757:

> 1. Their click through rate is low compared to the canvas banners. See tracks event jetpack_editor_block_upgrade_click on property context.
> 2. They are superfluous with the canvas banner, there is no way to miss that banner so seeing them in the sidebar is unnecessary.

**Comment by mmtr** [comment]
Reading through the early exploration of the premium blocks work, looks like it was considered to have the nudge only in the sidebar (plus a small indicator in the block icon): pbAPfg-Bm-p2#comment-1247

It was later discarded because we cannot guarantee that the sidebar would be always visible: pbAPfg-Bm-p2#comment-1248

Another alternative that was considered was to display an action button in the block toolbar: pbAPfg-DS-p2#comment-1334

![image](https://user-images.githubusercontent.com/1233880/186622108-3f472106-6275-4492-ba2e-2a841bca87a7.png)

Which again was discarded because it could be easily missed: pbAPfg-EE-p2#comment-1389

So I think we should keep the current placement, at least for now.
