### ISSUE TITLE
De-Fusion: Custom CSS

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25182]
### Impacted plugin

Jetpack

### What

Custom CSS

### How

```
"$plugin_root/modules/custom-css/custom-css.php"                    => "$wpcom_root/wp-content/mu-plugins/custom-css.php",
"$plugin_root/modules/custom-css/custom-css/js/codemirror.min.js"   => "$wpcom_root/wp-content/mu-plugins/custom-css/js/codemirror.min.js",
"$plugin_root/modules/custom-css/custom-css/js/css-editor.js"       => "$wpcom_root/wp-content/mu-plugins/custom-css/js/css-editor.js",
"$plugin_root/modules/custom-css/custom-css/js/use-codemirror.js"   => "$wpcom_root/wp-content/mu-plugins/custom-css/js/use-codemirror.js",
"$plugin_root/modules/custom-css/custom-css/css/codemirror.css"     => "$wpcom_root/wp-content/mu-plugins/custom-css/css/codemirror.css",
"$plugin_root/modules/custom-css/custom-css/css/css-editor.css"     => "$wpcom_root/wp-content/mu-plugins/custom-css/css/css-editor.css",
"$plugin_root/modules/custom-css/custom-css/css/use-codemirror.css" => "$wpcom_root/wp-content/mu-plugins/custom-css/css/use-codemirror.css",
"$plugin_root/modules/custom-css/custom-css/preprocessors.php"      => "$wpcom_root/wp-content/mu-plugins/custom-css/preprocessors.php",
"$plugin_root/modules/custom-css/custom-css/preprocessors/"         => "$wpcom_root/wp-content/mu-plugins/custom-css/preprocessors/",
"$plugin_root/modules/custom-css/csstidy/"                          => "$wpcom_root/wp-content/mu-plugins/csstidy/",
```

**Comment by coder-karen** [comment]
Noting that I moved this to 'Handle Last' (or Later) because of the number of discrepancies between files (having only looked at `custom-css.php` so far).

**Comment by anomiex** [comment]
Looking at desyncs in custom-css.php, looks like wpcom is missing these (and then some phpcsing in followups):

* d95d3009d6bc566dc5bad3ad07d33ef3ebe149d6
* 7b1cccd0c6ef11dffbbbdc2e8ea6e8932cb24fce
* #1592
* 898f543a00f6aafdc8c08171beadc092125a2663
* #2893
* #2955
* #4281 and #4316
* #5804
* #6775
* #8329
* #15140
* #16129

Also of note is that wpcom did r138518-wpcom instead of #2324 and #4525.

I didn't see anything on the wpcom side missing in Jetpack in that file, unless it's that one of those was indeed applied and then reverted only on wpcom.

----

As for the rest of the Fusioned files, the only other desync of note is that Jetpack never got D86305-code for some reason. The rest are just phpcs stuff.

**Comment by anomiex** [comment]
- Sync changes: D90582-code
- De-Fusion: D90583-code
- Clean up: D90585-code

Note the De-Fusion needs to wait until the weekly deploy this week so #26961 is included.

Also we could skip D90582-code if we want to, the de-Fusioning will do effectively the same thing. In that case we should probably copy all the info from its description into D90583-code 's description for the record.

**Comment by coder-karen** [comment]
Makes sense and tests well for me (minus the addition of the Jetpack CSS Tidy PR) - with all diffs applied. Just pending that weekly deploy.
