### ISSUE TITLE
De-Fusion: Grunion (Jetpack Contact Forms)

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25189]
### Impacted plugin

Jetpack

### What

Grunion (Jetpack Contact Forms)

### How

```
"$plugin_root/modules/contact-form/" => "$wpcom_root/wp-content/mu-plugins/grunion-contact-form/",
```

**Comment by coder-karen** [comment]
Defusioning diff (all in one): D90043-code

---

To test, apply this diff and sandbox a WPcom site. Add a contact form and test the functionality - test the form entries on the backend too. Since all the WPcom files are being deleted, simply testing the functionality here will be enough. You can also add an error_log to a modules/grunion-contact-form PHP file to confirm everything is being served from Jetpack.

**Comment by coder-karen** [comment]
I've now split the diff into two diffs. New instructions here:

Update diff: D90232-code

Cleanup (deletions inc tests) diff: D90043-code

---

Testing: To test, apply both diffs (check out both diffs, then check out the first and git merge the second from there) and sandbox a WPcom site. Add a contact form and test the functionality - test the form entries on the backend too. Since all the WPcom files are being deleted, simply testing the functionality here will be enough. You can also add an error_log to a modules/grunion-contact-form PHP file to confirm everything is being served from Jetpack.

**Comment by coder-karen** [comment]
Update: r254726-wpcom

Cleanup: r254731-wpcom

**Comment by sdixon194** [comment]
Removed some lingering JS files here: r254928-wpcom
