### ISSUE TITLE
De-Fusion: Site Abstraction Layer (SAL)

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25202]
### Impacted plugin

Jetpack

### What

SAL

### How

```
"$plugin_root/sal/class.json-api-platform.php"          => "$wpcom_root/public.api/rest/sal/class.json-api-platform.php",
"$plugin_root/sal/class.json-api-site-base.php"         => "$wpcom_root/public.api/rest/sal/class.json-api-site-base.php",
"$plugin_root/sal/class.json-api-site-jetpack-base.php" => "$wpcom_root/public.api/rest/sal/class.json-api-site-jetpack-base.php",
"$plugin_root/sal/class.json-api-post-base.php"         => "$wpcom_root/public.api/rest/sal/class.json-api-post-base.php",
"$plugin_root/sal/class.json-api-metadata.php"          => "$wpcom_root/public.api/rest/sal/class.json-api-metadata.php",
"$plugin_root/sal/class.json-api-links.php"             => "$wpcom_root/public.api/rest/sal/class.json-api-links.php",
"$plugin_root/sal/class.json-api-date.php"              => "$wpcom_root/public.api/rest/sal/class.json-api-date.php",
"$plugin_root/sal/class.json-api-token.php"             => "$wpcom_root/public.api/rest/sal/class.json-api-token.php",
```

**Comment by coder-karen** [comment]
After working on this a bit, I've come to a point where the errors when testing are getting a little complex and difficult to parse for me.
I'll leave this for now but here is a diff with all the SAL file references having been changed: D86582-code

At least one other change that would be needed in the Jetpack plugin version of `/sal/class.json-api-platform.php`: the path needs to change where `class.json-api-platform-wpcom.php` is being required.

**Comment by samiff** [comment]
Started working on this since there is overlap with #25198 

- [x] Jetpack PR (wait for wpcom deploy before landing D89982): #26861
- [x] Update diff: D89982-code
  - Testing: lots of things rely on these files, so make sure tests are passing then will require some attentive post-deploy observation including watching internal support channels.
- [x] Cleanup diff: I'm thinking it's okay to leave the stubs for now since a few wpcom files make references to them.

**Comment by samiff** [comment]
r255122-wpcom
