### ISSUE TITLE
De-Fusion: Jetpack User Agent

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25213]
### Impacted plugin

Jetpack

### What

Jetpack User Agent

### How

```
"$plugin_root/class.jetpack-user-agent.php" => "$wpcom_root/.config/is-mobile.php",
```

**Comment by anomiex** [comment]
Looks like the main thing going on here is that D45478-code never happened. In turn, that stalled out because `.config/batcache-config.php` calls the `jetpack_is_mobile()` function that was moved from `class.jetpack-user-agent.php` to `functions.global.php` so it's not defined in time.

It would also block de-Fusioning, since the `.config/is-mobile.php` is also happening before the `JETPACK_PLUGIN_LOADER_DIR` constant is defined. I think to unblock all this, we'd have to do the following:

* Move the definition of `JETPACK_PLUGIN_LOADER_DIR` from `wp-content/mu-plugins/0-wpcom-jetpack-loader.php` into something in `.config/` where it can be loaded early.
* Move the `jetpack_is_mobile()` function from `functions.global.php` to something like `functions.is_mobile.php`, that defines only that function. That file can be required from `functions.global.php` if we want.
* Jetpack's `class.jetpack-user-agent.php` should require `functions.is_mobile.php` and, if the class doesn't already exist, `jetpack_vendor/automattic/jetpack-device-detection/src/class-user-agent-info.php` manually (because on wpcom the autoloader won't be set up to load it).
* Then `.config/is-mobile.php` can be de-Fusioned to require Jetpack's `class.jetpack-user-agent.php`.
  * Also we'll probably want to take care of anything in wpcom calling `Jetpack_User_Agent_Info` to avoid logging tons of deprecation warnings.
  * Or maybe just avoid the deprecation calls on wpcom, since wpcom-premium-themes, wpcom-pub-themes, wpcom-a8c-themes, and wpcomsh all call the class too.

**Comment by anomiex** [comment]
* [x] First bullet: D90366-code, D90367-code, and D90369-code
* [x] Next two bullets: #26971
* [ ] Last bullet: D90372-code
* Left over: Cleaning up uses of `Jetpack_User_Agent_Info` and restoring the deprecation warnings on wpcom.

**Comment by anomiex** [comment]
Turns out we missed something in D90369-code, so we'll need D91112-code before D90372-code is good to go. Other than that, though, it's ready for review.
