### ISSUE TITLE
Description not shown in Classic Gallery Carousel when EXIF data is not shown

### ISSUE THREAD

**Issue by bsanevans** [Automattic/jetpack#25363]
### Steps to reproduce the behavior

1. Create a new page/post in the Classic Editor
2. Add a Gallery, with images. Choose images with a description
3. Publish the content, and on the front end, click on an image to open the carousel
4. If `Metadata | Show photo metadata (Exif) in carousel, when available.` is enabled in Media settings, then there will be an "i" to press, which will show image description.
5. If `Show photo metadata (Exif) in carousel` is turned off, then there will be no "i", making it impossible to see the image description too.

#### What I expected to happen

"i" should exist in all cases, brining up the image caption and descriptions, regardless of whether the `Show photo metadata (Exif) in carousel` setting is on or not.

#### What actually happened

The setting regarding EXIF data determines whether other info about the image (caption, description) are visible, too.

### Context

* User reported their image descriptions disappeared from all gallery carousels recently. 4180402-zd-woothemes
* I've confirmed on my test site with multiple themes, and found the visibility is determined by the EXIF setting.

#### Does this happen on simple or atomic sites or both?

Confirmed on Simple. (Haven't tested on Atomic)

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

Consistent

**Comment by cometgrrl** [comment]
I am not able to reproduce this. However, I am not able to see the Exif of my photo, even when `Show photo metadata ([Exif](https://en.wikipedia.org/wiki/Exchangeable_image_file_format)) in carousel, when available`. is on.

**Comment by jeherve** [comment]
This is a duplicate of #20470, which was fixed in #20747. Things work well now, both on WordPress.com simple or in Jetpack.

- Here is the Carousel modal when the exif option is on:

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/426388/182559731-d67bafbc-d3b3-414e-a800-0e031d4c7c18.png">


- Here is the same image when the exif option is off:

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/426388/182559828-bcef4fc3-35e4-48d8-a7ef-48f23aa87a98.png">
