### ISSUE TITLE
Slideshow block: block converted to HTML

### ISSUE THREAD

**Issue by rafaelmpx1** [Automattic/jetpack#25629]
### Impacted plugin

Jetpack

### Steps to Reproduce

The block containing the jetpack slideshow has been converted to HTML and the slide does not work.

I noticed that if I add a new slide block below, it starts to work.

I would like to know a solution so I don't have to go through all my more than two thousand posts to perform this procedure.

Is there a way, a css or js call that makes this HTML work?

<img src="https://marciatravessoni.com.br/wp-content/uploads/2022/08/Capturar.png">

### Reproducibility

Consistent

**Comment by jeherve** [comment]
> The block containing the jetpack slideshow has been converted to HTML and the slide does not work.
> I noticed that if I add a new slide block below, it starts to work.

Could you tell us a bit more about the steps you followed to get to that point?

- Is this when opening an existing, already published post in the block editor, to make some changes?
- Does this happen only with the Slideshow block?
- Does this happen with all your posts that have slideshow blocks in them, or only some relatively old posts?
- What happens if you publish a new post with a slideshow block, and then edit it right away? Do you see this behaviour as well?
- Do you see an error before you see that HTML block?

Thank you!

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
