### ISSUE TITLE
Subscriptions: Blog Subscription Widget errors out with dash in email address

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#2583]
When a user tries to subscribe using the Blog Subscription Widget and has a dash in their email address, the widget errors out with /?subscribe=error and doesn't subscribe the email address to the blog. 

Example email address: foo-7@example.com

2310427-t

**Comment by kraftbj** [comment]
@chaselivingston I couldn't duplicate this. My junk address is web-comments@ and it worked.

**Comment by dereksmart** [comment]
The reason the email address in your ticket is failing is because that email has blocked subscriptions.  I am getting error message `The email address has opted out of subscription emails.` from wpcom's response when trying to subscribe that specific email. 

Nothing wrong with the syntax, so closing the issue.

**Comment by dereksmart** [comment]
opened #2599 to provide a better error message next time :)
