### ISSUE TITLE
NUX landing page: third column isn't aligned with the 2 first columns

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2593]
For some reason, each row of the third column is a bit taller than the rows in the first and second column. It causes a little gap, seen in Firefox and Chrome:

![screen shot 2015-08-23 at 12 45 07 pm](https://cloud.githubusercontent.com/assets/426388/9427900/d1b938b8-4994-11e5-9dc9-317cc345beed.png)

@jeffgolenski Is that a problem?

**Comment by jeffgolenski** [comment]
Yeah, that's expected in some browsers at this point. I have an idea for a fix... @dereksmart can you implement the same JS that gives each model box a fixed height, based on the tallest box, to our nux page?

example: there's some JS that finds which module box is the tallest, and applies that height, inline to each module box:

<img width="1170" alt="screen shot 2015-08-29 at 10 39 30 am" src="https://cloud.githubusercontent.com/assets/214813/9562431/540a78a0-4e3a-11e5-8409-8135d247204f.png">

Ideally, if we can apply it to this j-row class, it would work best:

<img width="1246" alt="screen shot 2015-08-29 at 10 41 16 am" src="https://cloud.githubusercontent.com/assets/214813/9562442/8931ca10-4e3a-11e5-87f3-5cbf6f292236.png">

@jeremy you're missing a lot of elements within that screenshot though. all the toggles / wordpress.com CTA is missing. is that intentional?

**Comment by jeherve** [comment]
> you're missing a lot of elements within that screenshot though. all the toggles / wordpress.com CTA is missing. is that intentional?

Yes, my user didn't have the permissions to configure Jetpack modules.

**Comment by jeffgolenski** [comment]
fixed in: https://github.com/Automattic/jetpack/commit/b79dde2ce7060db8191a77dfecae25b870fdfe01
