### ISSUE TITLE
VideoPress: VideoPress Video block outputs `null`

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#25950]
The VideoPress Video block outputs `null` in the front end when the block doesn't have a defined video.

Block editor | Front-end
------|------
![Image](https://user-images.githubusercontent.com/77539/187665400-6049a2a6-222f-41da-9e00-8c345aa2f956.png) | ![Image](https://user-images.githubusercontent.com/77539/187665329-bc3aa2e1-653e-4ffc-b2eb-a5e27b6106a9.png)

**Comment by dhasilva** [comment]
The `null` output happens here, when `videoPressUrl` is null: https://github.com/Automattic/jetpack/blob/trunk/projects/packages/videopress/src/client/block-editor/blocks/video/save.js#L67

```js
<div className="jetpack-videopress-player__wrapper">
	{ `\n${ videoPressUrl }\n` /* URL needs to be on its own line. */ }
</div>
```

A simple check fixes this:
```js
{ videoPressUrl && (
	<div className="jetpack-videopress-player__wrapper">
		{ `\n${ videoPressUrl }\n` /* URL needs to be on its own line. */ }
	</div>
) }
```

The problem is that this triggers the block's [validation](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-edit-save/#validation), as the `save` content is different from what was previously saved to the database:

![Screenshot_2022-09-20_16-35-50](https://user-images.githubusercontent.com/8486249/191538954-22f7da3c-6a15-4f12-a7fb-5131bb714301.png)

The block user would need to manually update the offending block instances which, to be fair, I think should not be a problem as we are talking about a specific case that should not be common.

There is an issue about this, for reference: https://github.com/WordPress/gutenberg/issues/7604
