### ISSUE TITLE
Tiled Gallery: Issue with images resizing dynamically.

### ISSUE THREAD

**Issue by gabrieino2** [Automattic/jetpack#26088]
### Impacted plugin

Jetpack

### Steps to Reproduce

On https://harberphotography.com/joella-and-drews-non-traditional-geyserville-wedding/ , at least one of the blocks shrinks.  I have tried it on my phone, on Chrome, and on Safari, and the result is the same.  I also have a shrinking block on this blog post - https://harberphotography.com/sarah-and-mike-healdsburg-wedding-at-rus-farm/ .  On Safari, this block post has some blocks that have gone tiny - https://harberphotography.com/a-colorful-rancho-nicasio-wedding-in-west-marin/.  It looks fine in Chrome, though kind of bounces a little when looking at some of the text.  This post also has the shrinking block issue - https://harberphotography.com/a-magical-san-francisco-botanical-garden-wedding/.  I haven't checked all my posts, but the issue seems to be with the Jetpack tiled block.  I have tried deactivating all the plugins except for jetpack and running a default theme, and the problem persists.

### A clear and concise description of what you expected to happen.

Please refer to https://wordpress.org/support/topic/jetpack-tiled-gallery-issue-2/#post-15987309

### What actually happened

Please refer to https://wordpress.org/support/topic/jetpack-tiled-gallery-issue-2/#post-15987309

### Browser

Google Chrome/Chromium, Apple Safari

### Other information

Please refer to https://wordpress.org/support/topic/jetpack-tiled-gallery-issue-2/#post-15987309

### Reproducibility

Consistent

### Workaround details

I am not sure how many users are being affected.  I have not tried it on other computers outside of my home, but I have reproduced the issue on multiple devices in my home.  I have has limited success in mitigating, but not eliminating the issue by merging blocks together.  I should mention, that I used to be able to import a bunch of images into a native Wordpress gallery block and convert it into an image block so that I could have a bunch of images show up as images instead of importing them one at a time.  The native gallery block doesn't seem to be working correctly, and I can no longer do this.  I am not sure if it is connected with the Jetpack issue.

**Comment by coder-karen** [comment]
That's quite interesting - I can definitely spot the tiny images when looking at [this post](https://harberphotography.com/a-colorful-rancho-nicasio-wedding-in-west-marin/) in Safari, vs Chrome (just above the 'A colorful ceremony' heading). Those images appear to be in a WordPress Gallery block.

I couldn't replicate the shrinking images on Tiled Galleries but I did notice a Tiled Gallery image attempting to dynamically resize - resulting in flickering.

There are a few things going on within the pages that may need more investigation. One has to do with the deep nesting of Group blocks. You mentioned you've tried to solve problems by merging blocks together - is that what you mean here?

If not - do you still notice the issue (with both the shrinking images and the flickering images) if you 'un-nest' the group blocks? They can be manually moved from the lists view in the post editor, you may currently see something similar to this:

<img width="345" alt="Screenshot 2022-09-08 at 11 36 13" src="https://user-images.githubusercontent.com/16754605/189124639-1d419d52-491b-4478-b288-0ef707033c5e.png">

The tiny image issue and Jetpack Tiled Gallery resizing issue may not necessarily be related, but I'd explore the deep nesting first here. Do you have any other links to pages / posts on the site that also have a lot of images but don't appear to have any issues from what you've observed over time? 

Lastly, I notice the forum post is from a few weeks ago - is that roughly when you noticed the issue for the first time?

**Comment by gabrieino2** [comment]
In June I contacted my theme developer, because I noticed that the spacing between my blocks was funky.  My blog posts from the beginning of the year still have funky spacing.  Some with big gaps between blocks and some with no gap at all.  I seemed to solve the spacing issue to a certain extent by stacking the blocks together.  Not sure how I came up with that solution, but it seemed to fix the spacing issue.  Stacking the block made rearranging blocks very difficult, but as long as my layout was good, it evened out all the weird spacing.  I think I first noticed the weird resizing thing and flickering in June or July.

I just tried to “ungroup” several of the stacked blocks from https://harberphotography.com/joella-and-drews-non-traditional-geyserville-wedding/ .  It fixed the shrinking block issue, but the spacing between the blocks is all over the place again.  In posts not using the tiled blocks, I don’t have any issues with spacing or shrinking blocks.  

I tried changing the tiny blocks to tiled blocks, but then they disappeared from my blog post.  On the https://harberphotography.com/a-colorful-rancho-nicasio-wedding-in-west-marin/ post, I also unstacked some of the blocks at the top of the post to see if that would help with the tiny block issue.  

This is all pretty frustrating.  Any guidance would be appreciate.

Thanks,

Gabriel

**Comment by coder-karen** [comment]
Thank you for digging in even more here. I can definitely see that it would be frustrating not knowing what the specific cause is in order to fix it.

Hopefully a fix for [the issue reported here](https://github.com/Automattic/jetpack/issues/9548) will resolve spacing issues, though there is no time frame on that at the moment.

With the shrinking, I can now see the actual shrinking as well as the dynamically changing height and width variables for the images in some of the Tiled Gallery blocks. For anyone else attempting to replicate, there are a few resizing blocks on the page - the first are toward the bottom of the section 'Getting Ready at Home on Haight Street' (on both Chrome and Safari) on this page: https://harberphotography.com/a-magical-san-francisco-botanical-garden-wedding/ . 

By setting a breakpoint in the Chrome browser inspector tools on one of the lines where the image height and width are dynamically changing, it looked like an Autoptimize file was responsible for the resizing. However adding '?ao_noptimize=1' to the URL as suggested in the forum thread it now looks like the resizing is taking place in the 'tiled-gallery/view.js' file.

On Firefox I didn't see shrinking but in their place a couple of those same images were so small they were barely noticeable. As soon as I removed the 'ls-is-cached' class from those images they increased in size - that class (related to the Lazy Loading cache) is added by Autoptimize. I suspect that may be related to the tiny images issue elsewhere as well.

I do notice there is another optimization plugin active on your site - EWWW Image Optimization - so it isn't clear if there is a conflict with that plugin as well (it looks like it may have an image resize option). Deactivating that plugin from the plugins page rather than via troubleshooting mode and then clearing any site caches could help rule a conflict out there as well.

That said, I cannot replicate any of this on a test site just now though, so that would be something we'd need to do from our end too - specifically with regard to the resizing. We'll mark this for further investigation.

**Comment by gabrieino2** [comment]
Karen

I deactivated Autopitmize and EWWW Image Optimization and reloaded the post with the tiny images.  The images were back to normal size.  I then activated each plugin individually, and found that when EWWW was deactivated, the images were the correct size.  So there must be some sort of issue with EWWW and something else causing that issue.  

One thing that I have noticed with the tiled gallery, is that when I am building my blog posts, the tiled gallery is a little bit smaller in width than the other blocks.  I wonder if that matters.  

Thanks,

Gabriel

**Comment by coder-karen** [comment]
Ok that's good to know. In terms of the image resizing issue, I can see EWWW Image Optimizer appears to be de-activated just now, yet those particular images continue to be resized.

As a note to anyone who continues the debugging - could the ResizeObserver in 'tiled-gallery/view.js' have a part to play with this issue?

> One thing that I have noticed with the tiled gallery, is that when I am building my blog posts, the tiled gallery is a little bit smaller in width than the other blocks.  I wonder if that matters.

I notice the same in the post editor but not on the live site, I suspect that isn't an issue in this case as I can see there is a little bit of padding added to the block there.

**Comment by gabrieino2** [comment]
Karen

Yes, I de-activated EWWW and contacted their tech support to see if they had any insight into what was causing the images to be resized.  On Safari, the images that were appearing tiny before, are now showing displaying at their regular size.  I don’t know why they would be appearing small for you still.  

I have been going through and un-grouping blocks whenever I see that one of the tiled galleries in the stacked block is shrinking.  But now the spacing between the blocks is back to being funky… which I suppose is better than shrinking blocks, but still not great.  Hoping for a fix sometime soon.

Thanks for your help with this.

Gabriel

**Comment by gabrieino2** [comment]
Karen

It looks like tiled galleries and wordpress galleries do not play well together.  

In the blog post below, in ever instance where there was a gallery butting up against a wordpress gallery, the space between the blocks went to zero.  I went through the post and converted all those galleries to tiled galleries and the spacing was fixed.  Before that I tried disabling every plugin that I thought might be causing the issue, with no change.


 

Gabriel

**Comment by gabrieino2** [comment]
Karen

I am losing my mind.  I thought I had fixed the issue by changing most of the gallery blocks to tiled gallery blocks.  The site looked good at the end of the day yesterday.  Now the spacing between many of the blocks is gone.  I am talking with EWWW about this issue as well.  Any insight would be appreciated.

Thanks

Gabriel

**Comment by coder-karen** [comment]
Hi Gabriel,

The image resizing (where the images start normal sized and slowly start shrinking) isn't happening at my end either now - I suspect it was just browser caching that I hadn't cleared. Tiny images aren't there either. So just to recap where I understand we're currently at:

**Images resizing:**

That issue appears to have been resolved on your end by ungrouping nested Tiled Gallery blocks. Not an issue at my end either anymore.
Cause: Unclear at this stage but the issue was specific to Tiled Galleries that were nested.


**Tiny images:**

This was resolved when deactivating EWWW Image Optimizer (also not an issue for me anymore).
Cause: Likely a conflict between Jetpack and EIO, unclear exactly what at this stage.

**Spacing between blocks:**

This appears to be the current main issue, and more specifically there is no spacing when a WordPress Gallery block is up against a Tiled Gallery block. In each of those instances the spacing between the blocks completely disappeared. 
You've converted all WordPress Gallery blocks to Tiled Gallery blocks and the issue appeared to be fixed initially, but has reappeared.

You mentioned going through a post to change those WordPress Gallery blocks to Tiled Galleries but I'm not sure which post you're referring to as any links added aren't showing up here in GitHub. I can see the issue myself between those two blocks, but since the issue has reappeared for you I'd like to look more closely at the post in question.

Generally though, fixing the spacing between blocks is likely best done with CSS at this stage. Unless each block used has its own settings to adjust padding or margins (which Tiled Galleries do not have yet), then that is a good interim solution.

Below are a couple of snippets that could be of help.

To add some spacing underneath a WordPress Gallery block:
```
.wp-block-gallery {
    margin-bottom: 4px;
}
```
Changing the margin underneath each Tiled Gallery block (this snippet is to match the spacing between rows in the block):
```
.wp-block-jetpack-tiled-gallery {
	margin: 0 auto 4px !important;
}
```
Changing the spacing underneath a regular image block:

```
.wp-block-image {
	margin-bottom: 4px;
}
```

Only the Tiled Gallery example is Jetpack specific, and different themes or plugins could override added CSS styles, but testing with the GeneratePress theme on a test site those above examples worked for me. You can change the numbers to match the spacing levels that you'd prefer.

This can all be copied directly into the Additional CSS section in the Customizer, and then published with the Publish button:
https://harberphotography.com/wp-admin/customize.php?autofocus%5Bsection%5D=custom_css

If I've misunderstood and there was something else happening here that was Tiled Gallery specific, do let us know the specific post / page and we can take a look.

**Comment by gabrieino2** [comment]
Karen

Great recap.  

Thank you!

Gabriel

**Comment by coder-karen** [comment]
Thanks Gabriel, hopefully the CSS does the job here.

What I'll do is close this specific issue out because I've now done the following:

* I've created a separate issue for the image resizing issue: https://github.com/Automattic/jetpack/issues/26309
* As there is an [issue open](https://github.com/Automattic/jetpack/issues/9548) to add border width options the spacing issue would be covered there.
* That leaves the tiny images issue which appears to be a conflict with EWWW Image Optimizer at this stage and most likely because the two plugins have conflicting features. Possibly changing settings within EIO could help if you wanted to re-activate that plugin. Since it doesn't appear specifically Jetpack related I've not created an issue for that just now.
