### ISSUE TITLE
Setting "fallback_to_avatars" for top-posts widget results in type error 

### ISSUE THREAD

**Issue by sagarnasit** [Automattic/jetpack#26106]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Install jetpack plugin running on WordPress site with PHP version >= 8.0.
2. Set top-posts widget or shortcode on the page.
3. Go to theme's functions.php or a plugin.
4. use a filter hook `jetpack_top_posts_widget_image_options` to disable fallback gravatar option.
5. Try to open the top posts page.

### A clear and concise description of what you expected to happen.

By default, top posts set the fallback gravatar for the posts that do not have a featured image. There is filter hook `jetpack_top_posts_widget_image_options` that can be used to disable the fallback image. Disabling fallback images using the above hook should not display fallback images for the posts without featured images.

### What actually happened

Disabling the default fallback image using filter hook results in a type error with PHP 8.0 or higher.

For PHP versions lower than 8.0,  Instead of hiding the image tag, there is a broken image tag without a src value.

### Browser

Google Chrome/Chromium

### Other information

Error message:
```
Uncaught TypeError: Cannot access offset of type string on string in /wordpress/plugins/jetpack/11.3/modules/widgets/top-posts.php:422
```

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Workaround details

- Add a check for array index/key before accessing the value.
- Remove broken image tag when image fallback is disabled and post does not have featured image set.

**Comment by anomiex** [comment]
Looks like there are a few problems going on here:

* Most directly, code in [modules/widgets/top-posts.php](https://github.com/Automattic/jetpack/blob/d232df23bca4c637fe124d2aa489adf0789c8426/projects/plugins/jetpack/modules/widgets/top-posts.php#L413-L425) doesn't check for a failure return value.
* The code its calling [doesn't document](https://github.com/Automattic/jetpack/blob/d232df23bca4c637fe124d2aa489adf0789c8426/projects/plugins/jetpack/class.jetpack-post-images.php#L596) what it returns on failure. And for some strange reason it returns an empty string rather than say null.
* And the code that that calls [implies that it returns an empty array if there are no images](https://github.com/Automattic/jetpack/blob/d232df23bca4c637fe124d2aa489adf0789c8426/projects/plugins/jetpack/class.jetpack-post-images.php#L638), but actually may return false. Which would be another PHP warning.
