### ISSUE TITLE
Social Auto Share post.

### ISSUE THREAD

**Issue by bunchhuon** [Automattic/jetpack#26275]
Hi,

I have trouble with Jetpack which was double (Facebook and Tweeter) shown on my blog post screen.

**Comment by coder-karen** [comment]
Hi @bunchhuon 

Could you explain a bit more about what is happening on your site? You mention your blog post screen - is that your post editor or live post? Is it the Facebook and Twitter icons that are appearing twice underneath your posts? The issue title seems to indicate that something is being shared twice though. If you are happy to share a screenshot here that would be helpful too. Thank you!

**Comment by bunchhuon** [comment]
Dear Automattic/jetpack,

Sorry late reply, please see the attachment captured image.

Best regards,

**Comment by coder-karen** [comment]
It doesn't look like any attachments came through - the best way to add a screenshot to a GitHub issue comment is to upload the screenshot to GitHub directly (using the attach an image or video icon in the comment toolbar). It looks like you are responding to the comment directly from email so that's likely why any attachments aren't coming through.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
