### ISSUE TITLE
Akismet: Menu conflict with Standalones

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#26315]
### Impacted plugin

Backup, Boost, Protect, Search, Social

### Steps to Reproduce

1. Activate any standalone, without Jetpack proper, and activate Akismet

### A clear and concise description of what you expected to happen.

1. Akismet listed in either the Jetpack menu or its original top-level menu.
2. Settings link from the Plugins list table lead to the Akismet config page.

### What actually happened

1. Neither happens.
2. Link leads to a "Sorry, you are not allowed to access this page"

### Other information

My guess is Akismet has special provisions for loading under the Jetpack menu when the Jetpack class is present and something there is mucking it up.

https://user-images.githubusercontent.com/88897/191498911-5b9bc24a-4922-4306-8b1e-3184a0e36503.mov

Reported by @bizanimesh 

### Platform (Simple, Atomic, or both?)

Self-hosted

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes

### Workaround details

The Settings link for Akismet on the Plugins page doesn't work when a standalone plugin is active. The Akismet Settings page can still be accessed via the wp-admin menu, Jetpack -> Anti-Spam. Saving changes to the Akismet settings will cause the error message to be displayed. The changes are actually saved.
(props @kbrown9)

**Comment by anomiex** [comment]
> Akismet listed in either the Jetpack menu or its original top-level menu.

I see the menu item when Jetpack Boost or Jetpack Protect is installed (didn't check the rest). I see it in your video too at about 0:34, "Anti-Spam" is present under the Jetpack menu.

Looks like both [Akismet](https://plugins.trac.wordpress.org/browser/akismet/trunk/class.akismet-admin.php?rev=2753903#L110) and [the standalone plugins](https://github.com/Automattic/jetpack/blob/21e2b2e0c9b1ca93a5bdb4cda927d88478dbfc88/projects/packages/admin-ui/src/class-admin-menu.php#L51-L66) have logic trying to move it under the Jetpack menu, although Akismet's only looks for Jetpack-the-plugin. The standalone plugins' logic will win.

> Settings link from the Plugins list table lead to the Akismet config page.

I note that that Settings link goes to `/wp-admin/options-general.php?page=akismet-key-config` while the one in the Jetpack menu goes to `/wp-admin/admin.php?page=akismet-key-config`.

It looks like Akismet will produce the admin.php link for its settings page instead when the Jetpack class exists, which is why it works with Jetpack-the-plugin itself.

I see that WordPress Core has a `menu_page_url()` function since 3.0, perhaps Akismet should use that to produce its links instead of doing like `class_exists( 'Jetpack' ) ? admin_url( 'admin.php' ) : admin_url( 'options-general.php' )`?

**Comment by kraftbj** [comment]
Assigning @sdixon194 as the Jetpack monorepo point-of-contact and @kbrown9 as the Akismet POC.

**Comment by kbrown9** [comment]
We're pushed a fix for this to the dev version of Akismet, and we're expecting to release a new version next week.

**Comment by kbrown9** [comment]
We fixed this bug in version 5.0.1 of the Akismet plugin, which was released on September 28.
