### ISSUE TITLE
Search: Clicking on JetpackColophon behaves differently than before, inconsistently across browsers

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#26334]
The colophon link does not seem to behave seamlessly as with the old version. 

Follow-up to #26320 

An adblocker is blocking the new window in Chrome.

### Chrome with uBlock running this branch

https://user-images.githubusercontent.com/746152/191612269-39a61d3d-868d-42ab-bc8d-e6c77894edd4.mov

### Chrome with uBlock running trunk

https://user-images.githubusercontent.com/746152/191612241-08b847c2-c401-4941-81ba-fd03ceb6d9bf.mov

### Safari running this branch

https://user-images.githubusercontent.com/746152/191612276-fdd48412-542d-4c8c-9f7d-173d192e7169.mov

**Comment by jsnmoon** [comment]
This occurs because we're now incorrectly targeting the overlay in [this file](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/search/src/instant-search/components/overlay.jsx#L50) ([original review](https://github.com/Automattic/jetpack/pull/26320#pullrequestreview-1116104516)).

We'll want to resolve this issue before the scheduled code freeze on September 26, 2022. cc @dognose24
