### ISSUE TITLE
VideoPress: video Caption value

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#26341]
The caption value provided by the backend is an object that needs to be adjusted to make its usage easier.

![Image](https://user-images.githubusercontent.com/77539/191725455-7ad18f9a-ea47-46a7-864f-8160d889e48a.png)

**Comment by lhkowalski** [comment]
We currently have the data being returned as an object containing the `.rendered` property:

![videopress-caption-field-on-api-response](https://user-images.githubusercontent.com/6760046/192026491-0f5e2530-7f7a-4ff5-9a7a-d8cf26aabedd.png)

I am looking for a way to fetch the plain text value, and then include it on the `jetpack_videopress` fields from the `media` endpoint response, [the same way we did with the title and description](https://href.li/?https://github.com/Automattic/jetpack/pull/26228/files#diff-805985ee677f743d3659341c3a3f05713127bf9dde9f3aa9f8c0e23f9afadac2).

Kernel Team help as been requested on pe4Cmx-fL-p2#comment-152.

**Comment by lhkowalski** [comment]
Steps for solving this:

* [x] add `caption` to `jetpack_videopress` object, [here](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/videopress/src/class-wpcom-rest-api-v2-attachment-videopress-data.php#L121-L141)
   * PR: #26409
* [x] use `jetpackVideoPress` instead of `video` to set the `caption` const on the function that maps the response to the state object used on the client, [here](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/videopress/src/client/state/utils/map-videos.ts#L33-L39)
   * PR: #26440
