### ISSUE TITLE
Feature Request: Customizations in Post By Email

### ISSUE THREAD

**Issue by brucea8c** [Automattic/jetpack#26442]
### What

Customizations Ideas for Post By Email 

A [user in the forums](https://wordpress.org/support/topic/post-by-mail-issue-jetpack/) asked the following: 

>I am Jetpack – Post by Mail option. Everything is fine but i have 2 issues to put forward. 1. Can we make a custom email (not Jetpack provided). 2. Mine is a Job site. When my users post their Jobs – they put their email ids at the bottom of the post. Everything get posted but half of the mail is erased (like [@gmail](https://wordpress.org/support/users/gmail/).com is erased).

>I know that emails will be erased due to Jetpack default setting. But i want posted emails not to be erased.

**Comment by jeherve** [comment]
I'm afraid this is unlikely to change.

> Can we make a custom email (not Jetpack provided)

Since the emails are processed by WordPress.com, we must use a WordPress.com email address. You would have to use a different service to use a different email address.

> I know that emails will be erased due to Jetpack default setting. But i want posted emails not to be erased.

Jetpack's Post by Email service does indeed clean things up to avoid abuse of the service. This is unlikely to change.

I'll consequently close this issue as wontfix.
