### ISSUE TITLE
Post by Email doesn't work after upgrading to https

### ISSUE THREAD

**Issue by nickyfoto** [Automattic/jetpack#2646]
I have updated the Setting>>General for sites for the URL.
Also regenerate a new email address.
Does jetpack support Post by Email for sites use https?

**Comment by nickyfoto** [comment]
http://jetpack.me/support/getting-started-with-jetpack/troubleshooting-tips/
added following code to wp-config.php and reconnect with Wordpress.com
```
$_SERVER['SERVER_PORT'] = 443;
```
Problem solved

**Comment by kraftbj** [comment]
Likely, what happened, is that you're running something in front of your site—Varnish, CloudFlare, etc—and the SSL terminates there. Internal to your box, the actual PHP server is listening on port 80. Since the site is HTTP, Jetpack expects port 443 as part of the communication verification process.

Since the server reported 80 and we were expected 443, the verification fails (there's a number of pieces all used together that all must match what's expected on both sides). By setting the variable, the expected value matches what PHP is reporting.

Cheers!

**Comment by kraftbj** [comment]
Likely, what happened, is that you're running something in front of your site—Varnish, CloudFlare, etc—and the SSL terminates there. Internal to your box, the actual PHP server is listening on port 80. Since the site is HTTP, Jetpack expects port 443 as part of the communication verification process.

Since the server reported 80 and we were expected 443, the verification fails (there's a number of pieces all used together that all must match what's expected on both sides). By setting the variable, the expected value matches what PHP is reporting.

Cheers!
