### ISSUE TITLE
VideoPress: it is not possible to pull storage used when Jetpack plugin is not active

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#26511]
The endpoint that provides the storage used is registered by Jetpack plugin, meaning that is not accessible from VideoPress standalone plugin:

![Image](https://user-images.githubusercontent.com/77539/192830203-4f65571b-2a54-4d03-8a43-1b1273d34eb9.png)

Let;s figure out how to fix it. Probably registering a new endpoint in the VideoPress env.

**Comment by lhkowalski** [comment]
This is hard to replicate right now, because we are setting the initialState from the backend and are telling the client to rely on it, so the request to the Jetpack endpoint is not happening on the frontend (and not being performed on the backend).

To replicate it, I disabled the backend initial state by setting it's `_meta.relyOnInitialState` to false.

I think what we need to do here is:

* [x] move (copy) the endpoint to the Videopress namespace
   * #26652 
* [x] provide this data on the backend initialState
   * #26672
* [x] update the client to use the new endpoint
   * #26677

This will solve the issue from both sides.

**Comment by lhkowalski** [comment]
It's possible to get this info by requesting the site information on the WPCOM sites endpoint: `https://public-api.wordpress.com/rest/v1.1/sites/{ $site_id }`.

EDIT: actually, it will not work if the site does not have the Jetpack plugin enabled.

**Comment by retrofox** [comment]
exactly, that's explained in the issue description.

**Comment by lhkowalski** [comment]
Now that we shipped these [3 changes](https://github.com/Automattic/jetpack/issues/26511#issuecomment-1268524488), the issue is solved.
