### ISSUE TITLE
VideoPress: quick actions popover doesn't look very well

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#26549]
![Image](https://user-images.githubusercontent.com/77539/193262611-c56d5164-bfc3-4722-9697-0f64fe234b56.png)

**Comment by dhasilva** [comment]
It seems we have leaking styles here.
After many reloads I found out that `packages/videopress/src/client/admin/components/pricing-section/index.tsx` uses `PricingTableItem` that uses `IconToolTip` from the RNA library that [uses raw css](https://github.com/Automattic/jetpack/blob/trunk/projects/js-packages/components/components/icon-tooltip/index.tsx#L8) instead of scoped `style.module.scss`.
Scoping the CSS there fixes the padding here, but removing [this import](https://github.com/Automattic/jetpack/blob/trunk/projects/js-packages/components/components/icon-tooltip/style.scss#L1) breaks the search input in the VideoPress dashboard.

We need to ensure that every RNA component uses scoped css modules to avoid this type of issues.
