### ISSUE TITLE
Tiled Galleries: Odd number of circle items result in poor display

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2660]
Example: https://kraftbj.wpsandbox.me/2015/09/02/test-7/
![screen shot 2015-09-02 at 12 37 29](https://cloud.githubusercontent.com/assets/88897/9641510/b4e6a4ce-517c-11e5-82ea-13c83e4ccd3c.png)

The first image is the "odd duck out" of the grid of circles. The large size is unexpected, to me. I'd expect an odd image to be the same size as the rest at the end of the grid.

**Comment by dereksmart** [comment]
I'm pretty sure this was designed like this intentionally.  Can we get some designers to chime in? @jeffgolenski @justinkropp

**Comment by kraftbj** [comment]
The reported use case was as a simple "team" gallery. The user wanted to display a grid of headshots of their employees/teammates, but the actual result ended up being quite odd. http://mologic.co.uk/demo/

**Comment by jeffgolenski** [comment]
I agree with derek, it appears as that was designed intentionally. But I understand where you're coming from @kraftbj, especially with the example you provided. 

All images should be the same size with the same alignment. If a user(s) wants to feature an image within a tiled gallery so that it displays above the gallery, at a larger size, we should offer an option to do so: "featured gallery image" or something. 

The markup is pretty strange in the example:
![screen shot 2015-09-02 at 3 41 13 pm](https://cloud.githubusercontent.com/assets/214813/9642265/339531da-5189-11e5-9bef-9f40d665bd7c.png)


Truth be told I've never really investigated the Tiled Gallery feature that much, but I'll add it to my list of #trash-pickup

**Comment by dereksmart** [comment]
> offer an option to do so 
I don't think we should be adding more options.  Although I understand the use-case for this, IMO it does not appeal to the general masses.  

FWIW, it's possible to accomplish this with overriding CSS https://cloudup.com/cgqRBLC8ZTc

I think we should stick with the design we have.

**Comment by kraftbj** [comment]
> All images should be the same size with the same alignment.

My point is that's not happening. The user's example has something else going on (perhaps trying to fix it). Out of the box, if you have a row that will end up with one or two items, it'll display larger than the rest to have an even row.

Personally, it looks odd to me with the Circles layout in particular, perhaps because of the unexpected-to-me result along with the impact of #1526 .

If it's intended, we can close it as wontfix.

**Comment by dereksmart** [comment]
the user's site is already overriding our css with some of theirs, which is why it shows so much whitespace.  

Here's the css that will align it like my screenshot: 

```css
.gallery-row:first-child, .gallery-row:first-child img {
	max-width: 313px;
	max-height: 313px;
	float: left;
}

.tiled-gallery .gallery-row {
	display: inline;
}
```

Note that the above CSS is quick n' dirty, and doesn't fully account for mobile, but shows that it's possible.  

Also note that if we do decide to change the design, it will also change the design on all wpcom sites. 

I'll leave it up to @jeffgolenski to make the call

**Comment by jeffgolenski** [comment]
@kraftbj 

> My point is that's not happening.

Yes, I know. I was simply adding clarity to the issue. I think whoever originally did that intended for the image to stick out and be larger, above the rest of the gallery. It shouldn't do that. 

They should all be uniform images. If a particular person / user / company wants to tweak it so a featured image sticks out, they can mod the CSS to do so. 

@dereksmart 
> I don't think we should be adding more options. Although I understand the use-case for this, IMO it 
> does not appeal to the general masses.

I agree. So we'll leave that option out.

**Comment by dereksmart** [comment]
cc @rase- you've done a lot of work on tiled galleries.  what do you think?

**Comment by s-a-s-k-i-a** [comment]
@kraftbj  @jeherve 

Reported here as well. fixed it using a "walkaround". Read in other issue: https://github.com/Automattic/jetpack/issues/320#issuecomment-134123086

**Comment by c9dd** [comment]
Hi Guys any update on this?

**Comment by MichaelArestad** [comment]
No longer seems to be an issue with the latest tiled gallery. Closing for now.
