### ISSUE TITLE
Jetpack: Subscriptions - Decouple shortcode from Block rendering

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#26866]
The Subscribe block currently saves a shortcode block in the post HTML, and the relies on the shortcode frontend code for rendering it.

This has become inconvenient, and we should detach the block from the shortcode.

![Image](https://user-images.githubusercontent.com/746152/196157135-36c2b108-c08e-4502-854c-13a1e2796067.png)

**Comment by ice9js** [comment]
I just want to make sure we're on the same page before I start updating the code:

The submission logic looks like it can be left as is, as it really only depends on the [right request being sent for it to trigger](https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/modules/subscriptions.php#L101).  

As for the block itself, I see two ways to go about it, in order to be able to display the success message:
- Make the block fully dynamic, removing `save()` altogether and doing all the rendering in `render_block()`
- Make `save()` return the _form part_ of the block and treat it as a static block. In case of a submission just suplement it with an appropriate success/error message above/instead of the form.

~I think the second approach makes sense as we're not breaking up the form which could cause some issues with proper error message placement. Either way we're not doing that yet so even more reason to start with the static form/dynamic message approach.~
Actually, having gone through all the block options thoroughly now, having a fully dynamic block makes the most sense to me, rather than attempting to inject additional HTML into it.

**Comment by oskosk** [comment]
Reopening. @ice9js this doesn't seem to have been addressed by #26947

I still see the block generating shortcode in the editor	

To reproduce:

- Launch a JN site on trunk
- Connect Jetpack
- enable subscriptions from Jetpack -> Settings -> Discussion (at the bottom)
- Create a post 
- Add a subscription block
- Switch to code editor view

**Comment by ice9js** [comment]
As already mentioned in the conversation on the old PR, this was intentional to preserve compatibility during testing or in case anything goes wrong: the shortcode was saved but it wasn't actually used to generate the output when the post is rendered.

Now that the initial PR is merged, I opened up another one to completely remove the old `save()` implementation and prevent any future confusion regarding that.
