### ISSUE TITLE
Search: Removing plan still makes it look like you have it.

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#26965]
### Impacted plugin

Jetpack, Search

### Steps to Reproduce

1. Install the standalone plugin.
2. Buy a plan for it (store sandbox, etc)
3. See that it is all configured and working
4. Remove your plan using https://wordpress.com/plans/my-plan/...
5. Go back to your site, and see on the Jetpack Search page that you have not returned to the upsell page, even though everything is deactivated.

### A clear and concise description of what you expected to happen.

I haven't tested many variations of this, it looks like there is some cleanup in the DB for the plugin that we need to do. Even just installing the main plugin it shows "Customize Search" button, but when you click on it you just get an error saying you don't have permission.

<img width="535" alt="Screen Shot 2022-10-20 at 10 51 33" src="https://user-images.githubusercontent.com/820871/197011256-7e9cea9f-bae5-4c2d-aa28-d61cf6bda12a.png">

### What actually happened

I actually have no idea how to get out of this state without spinning up a whole new site.

### Reproducibility

Consistent

**Comment by gibrown** [comment]
Retested this on bleeding edge and I can no longer reproduce it so guessing it is fixed. cc @Automattic/red @trakos @robfelty

**Comment by trakos** [comment]
I managed to get it only once before, but it was a backend issue in that case. The response from API indicated that there's a plan, even after I've removed it in store admin. It was still listed in https://wordpress.com/purchases/subscriptions/<my-site>, it got fixed once I removed it there. It looks like a backend bug, but it could just be some store sandboxing weirdness.

Because it's in backend, we should be able to tackle it later if someone manages to reproduce it again.
