### ISSUE TITLE
WSoD when using WAF

### ISSUE THREAD

**Issue by withinboredom** [Automattic/jetpack#27220]
### Impacted plugin

None / Other

### Steps to Reproduce

If a WAF isn't bootstrapped (i.e., migrating hosts), the entire site dies.

### A clear and concise description of what you expected to happen.

Detection of a non-bootstrapped host should result in automatic re-bootstrapping or providing a better error message.

### What actually happened

PHP Fatal error:  Uncaught Error: Failed opening required '..../jetpack/jetpack_vendor/automattic/jetpack-waf/src/../rules/allow-ip.php

### Platform (Simple, Atomic, or both?)

Self-hosted

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

No but the platform is still usable

### Workaround details

Delete Jetpack.

Then reinstall and reconfigure.

**Comment by Dinsmoor** [comment]
I had this issue with an automatic upgrade to 11.5 as well, the steps of first deleting the jetpack plugin folder then reinstalling worked to continue site operation.

Error message: An error of type E_COMPILE_ERROR was caused in line 2 of the file /var/www/wordpress/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-waf/rules/rules.php. Error message: require(): Failed opening required '/var/www/wordpress/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-waf/src/../rules/allow-ip.php' (include_path='.:/usr/share/php')

**Comment by VR51** [comment]
This fault must have taken down half the internet. As stated above, removal of the Jetpack files and the WAF prepend rules in the htaccess and/or userini file(s) revives broken sites. Thankfully Jetpack can now be re-installation and activated without going through the auth process.

I have noticed that with versiion 11.5, Jetpack needs to be network activated in WP multisites or else multisites die again.

Also, it appears that not all my sites went down at the same time although I updated Jetpack in them all at around the same time. Maybe the fault's expression is triggered by a Jetpack cron task.

**Comment by withinboredom** [comment]
Ah good to know that it probably wasn't due to a server migration but more likely, a badly timed auto-update of the plugin.

**Comment by VR51** [comment]
This issue is urgent. Sites that were fixed yesterday by removing then reinstalling Jetpack have broken again. This time only the multisites were affected.

Another site broke in the early hours of this morning after I last posted here. This site worked ok with Jetpack 11.5 until it didn't. Leads me to believe the issue is being triggered by a cron task.

**Comment by anomiex** [comment]
Hi, thanks for reporting this!

We've already been tracking the issue as #27209, and as you can see there we've already fixed the bug in our development trunk. We plan to release 11.5.1 today to get the fix out to everyone.

You're right that it does seem to be related to a cron task. The upgrade deletes all three "rules" files, which does not happen to break the site. But when the cron task runs, it re-creates only one of those, then since the one exists it blows up trying to load the others.

As a workaround until 11.5.1 comes out, you can disable and re-enable the WAF module. This triggers re-creation of all three files.

**Comment by anomiex** [comment]
FYI, 11.5.1 is now out.
