### ISSUE TITLE
VideoPress Block: Update Captions Icon

### ISSUE THREAD

**Issue by roundhill** [Automattic/jetpack#27400]
The chapters icon sticks out because it has too much weight when compared to the other icons in the toolbar:

<img width="389" alt="Screenshot 2022-11-14 at 1 13 22 PM" src="https://user-images.githubusercontent.com/789137/201756677-9ab9889c-c869-4b81-b996-7d63154f1483.png">

**To Reproduce**
 * Activate Jetpack VideoPress
 * Go to the post editor, and add a video block.
 * Observe the out-of-place captions icon.

@evilluendas can you please provide a new SVG? 🙇

**Comment by evilluendas** [comment]
How about something like this? 

<img width="503" alt="image" src="https://user-images.githubusercontent.com/820374/203655443-fbb96065-971a-46bb-ab50-2d2bebc3f1c4.png">

One caveat: it's based on the new "Add caption" icon from the image block:

<img width="545" alt="image" src="https://user-images.githubusercontent.com/820374/203655534-12a409e0-0283-4bfa-8f6c-d871f785c7d2.png">

We should add a similar feature to toggle the caption on and off (don't confuse it with video captions though), so it'll eventually look something like this:

<img width="764" alt="image" src="https://user-images.githubusercontent.com/820374/203655755-d2c1a197-c0c9-45af-8495-e2d0e1785e24.png">

Which may be confusing. What other icon could be used for "text tracks"? 

An alternative would be to focus the feature on subtitles (instead of generic "text tracks", even though you'd be able to upload a vtt with info beyond subtitles), showing the standard "Closed Captions" CC label:

<img width="765" alt="image" src="https://user-images.githubusercontent.com/820374/203656454-c4674797-8c06-4435-8b9b-6d107d7ee962.png">

Or even better, like this — without a border:

<img width="765" alt="image" src="https://user-images.githubusercontent.com/820374/203656726-8a04e8ed-2970-48dd-a9d4-30acb7d0f417.png">

What do you think? @roundhill @retrofox and pinging @mtias and @pablohoneyhoney for input.

**Comment by mtias** [comment]
I think we should use the same icon we have on the player.

**Comment by evilluendas** [comment]
We don't have an equivalent icon in the player anymore, because the functionality is spread out in different places (the subs are managed from the settings menu, the chapters live in the seekbar+their own menu, etc).

Text tracks are quite messy because they agglutinate multiple things in a very generic and unspecific way, so they aren't intuitive at all. I think we should create specific ways of managing the different aspects, so you can define chapters, manage subtitles, different languages, etc. in contextualized ways, instead of a single "upload a file here, good luck learning the correct formatting" interface. So eventually we could have an icon to upload and manage the subs, another one for an evolved UI for chapters, etc.

But for the time being we can start swapping the icon. The original "subtitles" icon was the rectangle with two lines, so let's replace the current one with the first alternative so it doesn't feel strangely broken and out of place. I'll share the svg right away!

**Comment by evilluendas** [comment]
Here's the svg:

```svg
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M8 14.5H16V16H8V14.5Z" fill="black"/>
<path d="M16 12H8V13.5H16V12Z" fill="black"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M4 6C4 5.46957 4.21071 4.96086 4.58579 4.58579C4.96086 4.21071 5.46957 4 6 4H18C18.5304 4 19.0391 4.21071 19.4142 4.58579C19.7893 4.96086 20 5.46957 20 6V18C20 18.5304 19.7893 19.0391 19.4142 19.4142C19.0391 19.7893 18.5304 20 18 20H6C5.46957 20 4.96086 19.7893 4.58579 19.4142C4.21071 19.0391 4 18.5304 4 18V6ZM6 5.5H18C18.1326 5.5 18.2598 5.55268 18.3536 5.64645C18.4473 5.74021 18.5 5.86739 18.5 6V18C18.5 18.1326 18.4473 18.2598 18.3536 18.3536C18.2598 18.4473 18.1326 18.5 18 18.5H6C5.86739 18.5 5.74021 18.4473 5.64645 18.3536C5.55268 18.2598 5.5 18.1326 5.5 18V6C5.5 5.86739 5.55268 5.74021 5.64645 5.64645C5.74021 5.55268 5.86739 5.5 6 5.5Z" fill="black"/>
</svg>
```

It may need some cleanup, I'm not sure if the `fill="black"` is normally used in the Gutenberg icons.

**Comment by retrofox** [comment]
it looks tinier than the other ones ([PR](https://github.com/Automattic/jetpack/pull/27619)):

<img width="513" alt="image" src="https://user-images.githubusercontent.com/77539/204057715-5ddabdde-2a30-4845-bd4a-09e095275520.png">

Poster | Tracks
------|------
<img width="188" alt="image" src="https://user-images.githubusercontent.com/77539/204057745-f5a09e25-336a-4ec4-99db-331c14c218df.png"> | <img width="200" alt="image" src="https://user-images.githubusercontent.com/77539/204057732-cc040c57-870e-4436-a335-8fcd412d8369.png">

**Comment by evilluendas** [comment]
Yep! It's based on the caption on/off button in the image block, which is slightly smaller for some reason. 

![image](https://user-images.githubusercontent.com/820374/204310010-87d77b3a-8ebf-4b9d-868c-980c01fa30b0.png)

We should eventually add that functionality to the VP block too (to avoid layout shifts when selecting it, and to be consistent with other default behaviors) so we can either make the tracks icon bigger now, but then the caption one will be awkwardly small later on, or eventually make the Poster icon smaller so they're all smaller.

In any case, since the Poster icon is already there I've adapted the tracks one it so they're the same size, at least for now:

```svg
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M7 15.5H17V17H7V15.5Z" fill="black"/>
<path d="M17 12.5H7V14H17V12.5Z" fill="black"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M18.7 3H5.3C4 3 3 4 3 5.3V18.7C3 20 4 21 5.3 21H18.7C20 21 21 20 21 18.7V5.3C21 4 20 3 18.7 3ZM19.5 18.7C19.5 19.1 19.1 19.5 18.7 19.5H5.3C4.9 19.5 4.5 19.1 4.5 18.7V5.3C4.5 4.9 4.9 4.5 5.3 4.5H18.7C19.1 4.5 19.5 4.9 19.5 5.3V18.7Z" fill="black"/>
</svg>
```

This is how it'll look:
<img width="579" alt="image" src="https://user-images.githubusercontent.com/820374/204321344-88312468-30ed-4ab0-9873-70fc2d97b8aa.png">

**Comment by retrofox** [comment]
> We should eventually add that functionality to the VP block too (to avoid layout shifts when selecting it, and to be consistent with other default behaviors)

Sorry, could you explain a little bit about this behavior? I'm not following you 🤦 

> so we can either make the tracks icon bigger now, but then the caption one will be awkwardly small later on, or eventually make the Poster icon smaller so they're all smaller.

It's up to you, honestly. We can do whatever we consider more appropriate.

Thanks, Edu.

**Comment by evilluendas** [comment]
> Sorry, could you explain a little bit about this behavior? I'm not following you 🤦

Of course! This is how captions work on both the VideoPress and Video blocks:

https://user-images.githubusercontent.com/820374/204351960-fad46476-3405-4559-affe-749afc194043.mp4

It creates the space for a caption under the video when you select the block, so it pushes all the content under it. Images worked the same until very recently, but they now behave like this:

https://user-images.githubusercontent.com/820374/204337990-7b73f42d-64af-41dd-a628-ad4a0fb6d3c2.mov

The caption space is only added on demand, by enabling it from the toolbar. That way the page's content doesn't shift constantly, just because you've selected a block.

It'd be great if the VP block (and the default video one, if we're to keep both) behaves the same way, so it feels consistent with other media formats. The way the resizing handles appear (only when selected in the image block, always present in the VP and video blocks) or even their position (right and bottom in images, both sides on VP/video) could also be copied, so these manipulation mechanics are the same. 🙌

**Comment by retrofox** [comment]
> Of course! This is how captions work on both the VideoPress and Video blocks:

The video doesn't work, at least for me :-). Anyway, I got it 🙇‍♂️

**Comment by evilluendas** [comment]
For some reason the original .mov was corrupted, I've just updated the first video!
