### ISSUE TITLE
Form Block - Bug: Multi-line text block without label in editor, shows "message" as label in published view.

### ISSUE THREAD

**Issue by digitalwaveride** [Automattic/jetpack#27429]
If a user chooses not to fill the label, we shouldn't show a label in the published view.

![Image](https://user-images.githubusercontent.com/5120357/202032745-690665e9-9d67-445b-8385-6c29410b60ef.png)

**Comment by jcheringer** [comment]
So, this is not as simple as it seems.
When a field has a default label value and this value isn't changed by the user, Gutenberg doesn't store the label value with the other blocks' attributes.
Since it's the default value, the label would be shown anyway.
The Contact Form has the [fields render logic on the backend](https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php#L2931) and, because of that, it has a logic to [show the default label values](https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php#L3001).
If we remove the 'textarea' from the switch condition, we will affect old forms that don't have a value stored for the label attribute.
To achieve the desired effect, I changed the default multi-line text field label to 'Message'.
If the user explicitly removes the label, that means they don't want it.
The label value will be saved as an empty string, and it'll have the desired effect on the rendered view.

C.C. @digitalwaveride
