### ISSUE TITLE
Remove Tweet count parameters from Tweet button

### ISSUE THREAD

**Issue by niallkennedy** [Automattic/jetpack#2747]
[Twitter announced a new design for the Tweet button](https://twittercommunity.com/t/a-new-design-for-tweet-and-follow-buttons/52791) and plans to drop Tweet count. This issue tracks an announced change not yet reflected in live code.

The new Tweet button dimensions for Sharedaddy smart buttons will be similar to an existing button configured with the `count=none` display option. The `count` and `counturl` query parameters in the iframe will have no effect once the new design is live.

The `cdn.api.twitter.com/1/urls/count.json` endpoint used by Twitter's widgets JavaScript will no longer function as part of this change, causing `WPCOMSharing.update_twitter_count` to never update.

**Comment by kraftbj** [comment]
Thanks @niallkennedy!

Per original post, "next month" so something we can account for in 3.8 hopefully and start setting user expectations in support documentation.

cc @aduth / IO

**Comment by bobbingwide** [comment]
This problem is happening already. I am getting "waiting for cdn.api.twitter.com"
This appears to be preventing other jQuery from running. 
For example the jQuery for my nivo slider.

### Workaround
Disable Sharing

**Comment by jeherve** [comment]
@bobbingwide Here is another workaround:
http://jeremy.hu/jetpack-remove-the-share-counts-from-the-sharing-buttons/

**Comment by jeherve** [comment]
> I also see Failed to load resource: the server responded with a status of 404 (Not Found)
> https://widgets.wp.com/languages/notifications/en_US.json

That's a different issue. It will be fixed in 3.7.1. See #2698 for more details

**Comment by bobbingwide** [comment]
Hi Jeremy, I like the alternative workaround and thanks for the info on the widgets issue

**Comment by paulschreiber** [comment]
I'm seeing this problem as well (on WordPress VIP). Just deployed the filter workaround.

**Comment by kraftbj** [comment]
@niallkennedy - Do y'all have a firm date for killing the API?

**Comment by aduth** [comment]
It's not obvious to me that the problems noted in this thread are related to the original issue. I'd expect that once the API is removed, it would still return a response promptly (even a 404) and not hang. From what I can tell, the logic that exists currently in Jetpack and WordPress.com will continue to work as expected even after the API is dropped, though we should certainly do our due diligence to remove the unnecessary requests and button query parameters.

@paulschreiber, can you provide more detail about the problem you were observing?

**Comment by paulschreiber** [comment]
Here's the JS in question:

```php
jQuery.each([ https_url, http_url ], function( i, urlVariant ) {
    requests.twitter.push({
        dataType: 'jsonp',
        data: { url: urlVariant },
        url: 'https://cdn.api.twitter.com/1/urls/count.json';,
        success: jQuery.proxy( WPCOMSharing.update_twitter_count, null, urlVariant )
    });
} );
```

It tries to load:
https://cdn.api.twitter.com/1/urls/count.json?callback=jQuery11130011356212897226214_1443649675853&xhr=1&url=http%3A%2F%2Ffivethirtyeight.com%2Fdatalab%2Fsteelers-cowboys-romo-roethlisberger%2F

This URL only loads only intermittently. It likely depends on which CDN POP you hit.

When it didn't load cleanly, the browser would hang (presumably until the 300sec TCP timeout), which would block the loading of other scripts/execution of other activities.

Twitter is removing this API endpoint. As this endpoint was never officially supported, unlike a regular API removal, it might not behave nicely (i.e. 404, 403 error). In this case, it's failing to load entirely, as `cdn.api.twitter.com` is not a hostname they intended the public to use and may be going away. The `cdn.api.twitter.com` timeouts may also be entirely unrelated to the API deprecation, but since that's not a supported endpoint, Twitter's probably not going to fix it for you.

Jetpack should remove this code ASAP before you get flooded with complaints.

**Comment by aduth** [comment]
See #2787 for removal of share count requests.

**Comment by kraftbj** [comment]
Reopening b/c #2787 only removed the counts from unofficial buttons. Still need to remove the counturl param (at least) from the official button to fully clean up.

**Comment by dereksmart** [comment]
done in #2979

**Comment by niallkennedy** [comment]
The Tweet button's new visual design is now deployed. The new design removes the share count component. Sites with an older version of Sharedaddy code using the official buttons may see what appears to be extra padding due to the previous iframe dimensions.
