### ISSUE TITLE
Sharing: add option to enable sharing on front page, but not on archive and search pages

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2749]
Right now, the sharing options group the front page, archive page, and search pages under one option:

![screen shot 2015-09-23 at 4 53 21 pm](https://cloud.githubusercontent.com/assets/426388/10048527/9ee22570-6213-11e5-9e05-58f198136fed.png)

It'd be nice if Front Page was a separate element, so folks can enable sharing buttons on the front page, but not on other pages.

Suggested here:
https://wordpress.org/support/topic/sharing-buttons-showing-up-on-every-element-after-updating-to-37

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Comment by jnschrag** [comment]
I'd like to request that this functionality be reconsidered. I have a situation where I need to include the sharing functionality on archive pages, but not on the homepage or the search page, and doing so is not as straight forward as it should be. Since the front page, archive pages, and search pages are fundamentally different, it doesn't make sense to continue to group them together in this option.

Thanks for considering!

**Comment by annezazu** [comment]
Requested in #2623951-zd
