### ISSUE TITLE
Jetpack Search menu not visible on Atomic without plan

### ISSUE THREAD

**Issue by trakos** [Automattic/jetpack#27512]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Create a site with Jetpack plugin on Atomic platform, for example using JN.
2. Connect Jetpack
3. Notice that there's no Search submenu in Jetpack menu

### A clear and concise description of what you expected to happen.

I expected Search to be in the menu.

### What actually happened

Search wasn't in the menu.

### Other information

![image](https://user-images.githubusercontent.com/6437642/202834653-6e8cf56a-8a5a-41a8-9f2c-b72e10b9434c.png)

Looks like Pressable sites are also affected:

![image](https://user-images.githubusercontent.com/6437642/202834756-e4c2fb93-c256-4404-a813-d767c2774b22.png)

I put it as a bug, but let me know if that's intended.

Normally, most Atomic sites already have Business plan on wpcom, and in that case, Search menu is visible. It becomes visible once any Search plan is activated, and that includes classic search. However, for example JN and pressable sites initially don't have the menu.

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

It's still possible to purchase a Jetpack Search plan using cloud.jetpack.com or My Jetpack, so this is only about decreased discoverability.

**Comment by kangzj** [comment]
Hi @trakos, this is an intended behaviour.

If the site only has Jetpack the plugin, the logic is [here](https://github.com/Automattic/jetpack/blob/8c2d347d85ed13d5145177f0014e91b4c23a68b9/projects/packages/search/compatibility/jetpack.php), meaning if user has ever used search before or has a valid plan then we show the Search submenu. The reason was we didn't want too many menu items for users.

If the Search plugin is installed, we always show the Search menu and the logic is [here](https://github.com/Automattic/jetpack/blob/8c2d347d85ed13d5145177f0014e91b4c23a68b9/projects/plugins/search/compatibility/jetpack.php).

To always show the menu regardless of context, tweak the filter to always return true [here](https://github.com/Automattic/jetpack/blob/8c2d347d85ed13d5145177f0014e91b4c23a68b9/projects/packages/search/compatibility/jetpack.php).

**Comment by trakos** [comment]
Thanks for the explanation, @kangzj!

If that's the intended behavior, then I think I'll just close this. Cc @gibrown since we've discussed this issue.

**Comment by gibrown** [comment]
Every atomic site has Classic search so I think we should always show it. So let's just return true.
