### ISSUE TITLE
VideoPress: filter by privacy doesn't work as expected

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#27558]
The app doesn't handle the filtered list properly when filtering by privacy. We must research and test the implementation, supporting the `site default` privacy value.

**Comment by lhkowalski** [comment]
I think the best thing to do initially is to map which videos we should show on each filter.

Currently, when we select one of the filters, only videos with the specific selected privacy will show up. This is OK for private and public videos, but may not be for the "Site Default" one that you mentioned.

**Comment by lhkowalski** [comment]
Thinking about what to show, does the following tables make sense? Is this the expected behavior for the filters?

*When the site is public ("Video Privacy: Restrict views to members of this site" unchecked)*

| Filter checked | Videos to show |
| --- | --- |
| Public | Public + Site Default |
| Private | Private |
| Site Default | Public + Site Default |

*When the site is private ("Video Privacy: Restrict views to members of this site" checked)*

| Filter checked | Videos to show |
| --- | --- |
| Public | Public |
| Private | Private + Site Default |
| Site Default | Private + Site Default |

**Comment by lhkowalski** [comment]
I was checking the UI and it only shows "Public" and "Private" checkboxes, my bad. In this scenario, the filtering could look like this:

*When the site is public ("Video Privacy: Restrict views to members of this site" unchecked)*

| Filter checked | Videos to show |
| --- | --- |
| Public | Public + Site Default |
| Private | Private |

*When the site is private ("Video Privacy: Restrict views to members of this site" checked)*

| Filter checked | Videos to show |
| --- | --- |
| Public | Public |
| Private | Private + Site Default |

**Comment by lhkowalski** [comment]
I am working on the PR for the second proposal, and then we can build upon it.
