### ISSUE TITLE
My Jetpack: improve wording for primary account switch

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2760]
From @bjornjohansen [in Slack](https://wordpress.slack.com/archives/polyglots/p1443211372001704):

> Regarding this string in Jetpack: “Set the primary account holder”
> Does anyone know if it is the the holder of the primary account, or is it the primary holder of the account?

- [String](https://github.com/Automattic/jetpack/blob/master/views/admin/my-jetpack-page.php#L125)

Maybe we could update that string to make things clearer?

@bjornjohansen If you have any suggestions, do not hesitate to let us know!

**Comment by bhubbard** [comment]
Maybe it should state "Primary User" instead of "Primary Account Holder", and I would suggest it link to the article about the primary user.

http://jetpack.me/support/primary-user/

I would also like to see some more information in this article, as the full details of the differences between a primary user and non primary user still seem a bit unclear. How does this relationship affect certain modules, such as "Publicize", Jetpack Manage features, disconnecting or connecting jetpack as each user type.

**Comment by jeherve** [comment]
Closing this for now, as "My Jetpack" was removed in 4.3.
