### ISSUE TITLE
Slideshow Block: replace pencil icon in editing controls

### ISSUE THREAD

**Issue by ilonagl** [Automattic/jetpack#27711]
### Impacted plugin

None / Other

### What

Swap the old pencil icon for Replace, for alignment.

### How

Swap the old pencil icon for Replace, for alignment.

Main change: 
Swap the pencil icon for text ‘Replace’.

Point of contact: @ilonagl
![Designs-4](https://user-images.githubusercontent.com/100145243/205079790-64c37bab-d555-4679-af4b-b5dd0af5d745.png)

**Comment by jeherve** [comment]
The Core Gallery block works a bit differently, in that it is a parent block, containing multiple single image blocks. In this scenario, the "Replace" word makes sense because when clicking on "Replace", one can replace that specific image in the gallery.

The Slideshow block, however, is one single big block. When clicking on the pencil, one can:
- change the order of the images in the slideshow
- add or remove images
- change image titles / captions

With that in mind, do you think it makes sense to use "Replace" for this button?

**Comment by renatoagds** [comment]
@jeherve Good point on this one.

I use the `Edit` word instead of `Replace` since it makes more sense with everything the user can do in Slideshow.

It makes sense for you @ilonagl 

You can see it in action at #28004
