### ISSUE TITLE
Infinite-scroll shows load more button even if there are no more posts

### ISSUE THREAD

**Issue by kategee** [Automattic/jetpack#282]
Load more button should not be there unless there are actual posts to load. You have to click the button, it attempts to load more posts, there isn't any, then it disappears.

**Comment by kevinbreed** [comment]
I'm having the same issue on a custom theme. Though I'm using a standalone version of infinite scroll through the [infinite-scroll-from-jetpack plugin](https://wordpress.org/plugins/infinite-scroll-from-jetpack/), the code causing this behaviour is the same as in the latest Jetpack version.

The function [is_last_batch() in modules/infinite-scroll/infinity.php](https://github.com/Automattic/jetpack/blob/master/modules/infinite-scroll/infinity.php#L256-L258) checks if the number of fetched posts on a page is smaller than the number of posts to display on a page. So with the example of @kategee, when there are 10 posts in total, and the last page is fetched, the number of fetched posts is 5, just as the number of posts to display on a page. This makes the is_last_batch function return false, while it should return true. 

It seems to me that the right way to check for the last 'batch' is to multiply the current page (2 for the last page) with number of posts per page (5) and compare this with the total number of posts for the query (10). To check for the last batch, test whether the current_page*posts_per_page is equal to or greater than the total number of posts.

After some fiddling around with the code, I came to the following solution:

```php
static function is_last_batch() {
    $current_page = self::wp_query()->query_vars['paged']+1;
    $posts_per_page = self::get_settings()->posts_per_page;
    $displayed_posts = $current_page*$posts_per_page;
    $total_posts = intval(self::wp_query()->found_posts)+$posts_per_page;

    return ($displayed_posts >= $total_posts);
}
```
The only strange thing I encountered is that 'self::wp_query()->found_posts' returns the total number of posts minus the number of posts per page. That's why I've added them again to determine the total number of posts.

**Comment by koscoder** [comment]
Obviously, the function [ is_last_batch() in modules/infinite-scroll/infinity.php](https://github.com/Automattic/jetpack/blob/master/modules/infinite-scroll/infinity.php#L256-L258) is totaly wrong. To temporary fix it in a theme I used filter 'infinite_scroll_results'.
`add_filter('infinite_scroll_results', function($results, $query_args, $wp_query) {
    if ($wp_query->get('paged') == $wp_query->max_num_pages) {
        $results['lastbatch'] = true;
    }
    return $results;
}, 10, 3);`

**Comment by innominat3** [comment]
@koscoder same here
A temporary fix was to comment out Lines 384-386 in my infinity.php
`if ( self::is_last_batch() ) {return;}`

**Comment by anastis** [comment]
Not sure what this status of this ticket is (or should be), but as of 4.4.2 the issue is pretty-much fixed, and `is_last_batch()` function looks like this:
```
	static function is_last_batch() {
		$post_type = get_post_type();
		$entries = wp_count_posts( empty( $post_type ) ? 'post' : $post_type )->publish;
		if ( self::wp_query()->get( 'paged' ) && self::wp_query()->get( 'paged' ) > 1 ) {
			$entries -= self::get_settings()->posts_per_page * self::wp_query()->get( 'paged' );
		}
		return $entries <= self::get_settings()->posts_per_page;
	}
```

Now, as I said, it's pretty much fixed. While generally it works ok, the Load More Posts button still appears on the second page, when there are exactly two pages.
It seems that `self::wp_query()->get( 'paged' )` returns 0-based page numbers, so `1` is the **second** page, so `> 1` only kicks from the third page and after.
Changing `> 1` to `>= 1` should fix the problem.
