### ISSUE TITLE
New 11.7-beta release plug-in update issue

### ISSUE THREAD

**Issue by shahabmohi** [Automattic/jetpack#28201]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Go to Jetpack activity log.
2.  Look at activity timeline.
3. Plugins update regardless of status.

### A clear and concise description of what you expected to happen.

Jetpack updates plug-ins that have specifically been designated to "Not update automatically" despite their status. Jetpack keeps updating Elementor despite the auto update option being disabled and causes fatal errors for the site.

### Browser

Google Chrome/Chromium

### Other information

![Screenshot 2023-01-05 192323](https://user-images.githubusercontent.com/66645514/210923798-55e4162a-d9ca-42c7-ac5b-ba2dd2e9cdf9.jpg)

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No and the platform is unusable

**Comment by jeherve** [comment]
Thanks for reaching out! Do you think you could give us more details about the problem, either here or by reaching out [via email](https://jetpack.com/contact-support/?rel=support&hpi=1)?

Specifically, I think it would be interesting to know:

- Where your site is hosted, as some hosting providers will purposefully automatically update some plugins, sometimes because a plugin has a known security vulnerability for example.
- What version of Elementor you currently use. This is important as WordPress itself will force auto-updates for some versions of some plugins when a security vulnerability is publicly disclosed.
- How did you disable automatic updates for that plugin on your site?

I should also note that Jetpack itself does not automatically update your plugins. Jetpack's Activity Log will show you that a plugin was updated, but that doesn't mean the plugin was updated by Jetpack. [Plugin and theme auto-updates are entirely managed by WordPress itself since version 5.5.](https://wordpress.org/support/article/plugins-themes-auto-updates/).

Thank you!

**Comment by shahabmohi** [comment]
Thank you for the response. Here are the facts of the issue I have been dealing with:

- The site is hosted on wordpress.com.
- I am currently using the 3.2.3 version of Elementor, as any other version after that seems to be incompatible with the dynamic elements in Crocoblock Jetengine plugins.
- Automatic updates are enabled only if the "Enable Automatic Updates" button on the plugins page is checked.
- Every update to Elementor happens a few minutes after Jetpack does an automatic backup. I have included a screenshot for reference.

![Screenshot 2023-01-11 181444](https://user-images.githubusercontent.com/66645514/211969375-46e03037-906a-4859-9465-62a15f59b541.jpg)

Thank you for your time.

**Comment by jeherve** [comment]
@shahabmohi Since your site is hosted on WordPress.com, I would invite you to contact the support team via this page:
https://wordpress.com/help/contact

They should be able to look at your site's activity and help you understand what is happening.

> I am currently using the 3.2.3 version of Elementor

This may be the source of the problem. This is a very old version of the plugin, that was released more than a year ago. Since then, multiple security issues were found and fixed in the plugin. By running such an old version of the plugin, you're exposed to all the security issues that were found and published in the past year. You can find all the security issues your version is impacted with here:
https://www.cvedetails.com/vulnerability-list/vendor_id-20517/Elementor.html

Before you do anything, it may be worth updating to the most recent version of the Crocoblock Jetengine plugins you have. That should allow you to then update Elementor as well.
