### ISSUE TITLE
VideoPress: Video edit page stuck loading when opened directly

### ISSUE THREAD

**Issue by dhasilva** [Automattic/jetpack#28593]
When opening the video edit page directly in a new browser tab, the page is stuck in the loading state:

![Image](https://user-images.githubusercontent.com/8486249/214870042-86fcd730-4485-4498-8897-9a5a368158dd.png)

Introduced [in this PR](https://github.com/Automattic/jetpack/pull/28528/files#diff-f99fabf88a61de93b1b08e9c50f0c84344d71032c2539c0bdeb6febf16227f8dR27) where `isFetching` is set to `true` manually. It is necessary to check if the page is not the edit page before doing so.

**Comment by lhkowalski** [comment]
I spent this afternoon was looking for some way to do this without expanding the code inside the `state/index.js`file because looking now it seems like an odd place for this rule, but whenever a try to do it I got a weird bug on the video library itself (videos from other pages showing up).

I will proceed with the simple solution inside the current file and then we can start exploring better ways to do this, as well as handling search parameter changes, for example, and everything else related to the routing of search parameters.

**Comment by lhkowalski** [comment]
I have a working concept for the simple fix. I will clean it and prepare the PR.

**Comment by lhkowalski** [comment]
I will reopen this so we can handle the edge case of someone typing `page=1` as the search parameter, what makes the library page hang on the loading status (thanks @dhasilva):

<img width="800" alt="Screen Shot 2023-01-27 at 12 20 00" src="https://user-images.githubusercontent.com/6760046/215122101-f3e60314-2d3c-4496-bc8a-fdebc9b13c56.png">
