### ISSUE TITLE
VideoPress: get 404 error on Dynamic colors example

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#28779]
I get 404 error on Dynamic colors example from Block settings > Color

Simple | Jetpack
-----|-----
![Image](https://user-images.githubusercontent.com/77539/217045611-0e9ee8ef-7a8b-4999-acd2-07b470850814.png)| ![Image](https://user-images.githubusercontent.com/77539/217046169-94f683ff-0fdb-40be-be61-52ddba042cd2.png)

**Comment by dhasilva** [comment]
Can't reproduce. Tried locally, on JN, simple and WoA, all working fine 🤔

**Comment by dhasilva** [comment]
I can reproduce it in a new Premium site, without sandboxing.

**Comment by ebinnion** [comment]
Question - Disregarding the broken image, what should be showing there?

Because, I can reproduce on a test site. But, when I add `concat_js=no` to the URL, then I get something that looks different. Notice how it's different panels in general.

**With Concat**
<img width="1281" alt="Screen Shot 2023-02-07 at 12 14 44 PM" src="https://user-images.githubusercontent.com/1126811/217331214-f7ad18d5-be10-42ee-b626-690e78043744.png">

**No Concat**
<img width="1417" alt="Screen Shot 2023-02-07 at 12 15 20 PM" src="https://user-images.githubusercontent.com/1126811/217331247-d664565d-03f9-49ee-9e99-16ae298c8017.png">

**Comment by dhasilva** [comment]
> Notice how it's different panels in general

The first screenshot uses the VideoPress block (v6), while the second uses the Video block (v5).
On simple sites, as of now, the Video block gets converted to the VideoPress block automatically, so my guess is that you added a Video block and it got converted normally in the first case, but when adding `concat_js=no` to the URL the conversion does not happen. Maybe the VideoPress block gets broken in that case?

**Comment by dhasilva** [comment]
The issue also happens to the `videopress-block-example-image.jpg` file.

JN:
![2023-02-07_17-08-18](https://user-images.githubusercontent.com/8486249/217355701-98130de7-e6d9-49d8-b419-f51ea2bcb3ad.png)

Simple site:
![2023-02-07_17-07-05](https://user-images.githubusercontent.com/8486249/217355706-aee77f81-6659-4c85-b5cf-7b4218672091.png)
