### ISSUE TITLE
About widget: Allow custom url in Read More... link

### ISSUE THREAD

**Issue by rothschild86** [Automattic/jetpack#2894]
Pretty straightforward. At the moment, one must choose one of the wp pages for the link. The lack of custom url option is preventing me from using the widget at the moment. Cheers!

**Comment by jeherve** [comment]
Could you give me more details about that widget? What's the exact title you see at the top of the widget options under Appearance > Widgets in your dashboard?

**Comment by rothschild86** [comment]
Jetpack > Extra Sidebar Widgets > The Gravatar Widget :)

**Comment by jeherve** [comment]
By the "Read More" link, I assume you mean the "View Full Profile →" link appearing at the bottom of the widget? Is that correct?

**Comment by rothschild86** [comment]
Ah, yes, I guess I renamed mine. That's the name :)

**Comment by jeherve** [comment]
Thanks!

Your version of the Gravatar Profile widget must indeed be quite different, because it's currently not possible to choose one of the wp pages for the link, as you mentioned it. That link is hardcoded, and points to your Gravatar Profile page.

Since you seem to be building a custom Profile widget, it might be best to actually start from scratch and use a Text widget where you'll paste the HTML you need and the elements you need. Jetpack's Gravatar Profile widget offers some customization options, but you won't be able to change that link.

**Comment by rothschild86** [comment]
Ahhhh.... Very sorry man! The widget was coming from the Genesis. And the whole time I though I was using the jetpack one. My bad :/
