### ISSUE TITLE
Subscriptions: allow site owners to customize the "Confirmed subscription" email

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2911]
Site owners can already customize the emails sent to subscribers before they can confirm their subscription. They can't, however, customize the final email sent after confirmation. It'd be nice if this were possible.

Suggested here:
https://wordpress.org/support/topic/content-for-jetpack-subscribers-only?replies=3&view=all

**Comment by osiux** [comment]
Seems easy to add an extra setting to allow for a customized text for the confirmation email, but I couldn't find where the email is sended. It makes a xmlrpc call and syncs `subscription_options` (where the emails contents are stored), so I suppose there are some changes needed in the jetpack/wp.com servers?

**Comment by jeherve** [comment]
> I suppose there are some changes needed in the jetpack/wp.com servers?

Correct, yeah.

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/editing-the-confirmed-subscription-to-posts-email?replies=1

**Comment by espspare** [comment]
I've been looking for a way to edit this as well in order to give confirmed subscribers a free download as a thank-you. At the moment I've compromized by putting it into the confirmation link but that means they get the download even if they don't confirm. Please make this more customizable if possible. Otherwise it might make more sense to turn Jetpack subscriptions off and go to a different autoresponder. Thanks

**Comment by jeherve** [comment]
Closing as duplicate of #152
