### ISSUE TITLE
Blaze showing up by default on all my sites with Jetpack

### ISSUE THREAD

**Issue by mrkshrt** [Automattic/jetpack#29294]
### Impacted plugin

Jetpack

### Quick summary

Blaze is now a default and showing up in Posts

### Steps to reproduce

1. Show all posts
2. Mouse over posts to Edit, View, etc and now new option Blaze

### A clear and concise description of what you expected to happen.

This should not be turned on by default, it should have to be selected by Admin

### Impact

All

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

It is simple to disable but must be done on every site with a filter

**Comment by jeherve** [comment]
Thanks for the feedback.

Since the feature does not make any changes to your site's frontend, and only appears for site admins connected to WordPress.com, it has a very limited impact on your site. This is why we decided to enable the feature by default.

Also for this reason, we're not currently planning on adding a toggle or a setting to allow one to disable the feature from the Jetpack Settings.

> It is simple to disable but must be done on every site with a filter

You can indeed disable the feature with a filter, and that's currently the only way to remove the additional links added to the Post List menu:

```php
add_filter( 'jetpack_blaze_enabled', '__return_false' );
```

**Comment by mrkshrt** [comment]
Thanks for the response.

I have already found and tried the filter, I just think it should be the
default.

Can I CC you on the responses I send to the site administrators on the many
sites I host? Just kidding.

I get you want to promote it, just don’t see why it is on by default. I
mean I see.

Thanks,



Mark Short - Transparent Solutions - 913-897-5019

**Comment by jeherve** [comment]
Also suggested in #30163.

**Comment by jeherve** [comment]
I'm reopening this issue. Following your feedback and others', we'll most likely add a toggle in a future version of Jetpack, as we continue to iterate on the Blaze feature.
