### ISSUE TITLE
Mastodon Sharing Button Is Missing the Logo

### ISSUE THREAD

**Issue by pollyplummer** [Automattic/jetpack#29362]
### Impacted plugin

Social

### Quick summary

I have tested this on a few sites. When adding the Mastodon sharing button to a site, it appears in the lineup of other sharing options without the logo. The button works, it just isn't displaying the logo.

<img width="315" alt="Screen Shot 2023-03-08 at 11 11 22 AM" src="https://user-images.githubusercontent.com/343280/223766999-98b1a502-64c7-4b54-9550-476584ff77ea.png">

### Steps to reproduce

1. Enable Mastodon sharing button to Jetpack sharing options
2. View the buttons on the frontend

### A clear and concise description of what you expected to happen.

Logo should appear inside the button

### What actually happened

Button appears to be empty

### Impact

One

### Available workarounds?

There is no user impact

**Comment by jeherve** [comment]
Thanks for the report! Do you happen to use a caching plugin on some of those sites? What happens when you flush your cache?

I do see the button on WPTavern.com right now when using Chrome, Firefox, Safari, and Edge, so I'm wondering if maybe you're seeing this in a specific browser?

<img width="817" alt="image" src="https://user-images.githubusercontent.com/426388/223769807-9ca21f5a-72e5-4d43-a4b5-a679961e2342.png">

(Example with [this post](https://wptavern.com/wordpress-legacy-default-themes-updated-to-bundle-google-fonts-locally))

Thank you!

**Comment by jeherve** [comment]
After discussing this in Slack, it seems that your site is still using an older version of the Jetpack plugin, with older versions of the button's assets (icon font, css) cached by your site's CDN. Once your site's Jetpack version is updated (most likely tonight or tomorrow), you'll start seeing the button properly!
