### ISSUE TITLE
Twitter Cards: use fallback images from Blavatar, Site Logo, and Site Icon when possible

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#2947]
The `twitter:card` type defaults to `summary` but if the user wants to verify another card type, they have to manually change that to something else. It seems we should either do a better job of picking the correct card type, or allow users to choose which card type they'd like to use.

2402779-t

**Comment by kraftbj** [comment]
There is a bit of logic already wrt card type: https://github.com/Automattic/jetpack/blob/master/class.jetpack-twitter-cards.php#L48=L84

Basically, default is `summary` with checks to use `summary_large_image`, neither requiring whitelisting anymore. The `app` type would be hard to check the need for. The `player` card could be useful, but the requirements, IMO, are beyond what JP can do by itself, though can be done with the following filter.

Lastly, the [jetpack_open_graph_tags](https://github.com/Automattic/jetpack/blob/1824cf7e3bdb18998f13c5654c91707e36a08192/functions.opengraph.php#L206) filter should be sufficient. To ensure the twitter tags are already present, ideally set to a priority of 11+.

Any suggestions on how to improve this?

**Comment by chaselivingston** [comment]
In the case of the user I was working with, they wanted to be validated for `summary_large_image` but apparently our logic wasn't loading that for them, so that's why they had to manually change it in this case.

**Comment by jeherve** [comment]
@chaselivingston It'd be useful to get an example of a post where they expected to see the `summary_large_image` type, but got `summary` instead.

**Comment by chaselivingston** [comment]
@jeherve I believe this happened on their homepage actually, not an individual post.

**Comment by jeherve** [comment]
That would explain things. `Jetpack_Media_Summary` wasn't built to get content from the home page, only from posts and pages. So we never look for an image big enough to build a `summary_large_image` card on the home page.

That issue should probably be renamed into "Twitter Cards: use fallback images from Blavatar, Site Logo, and Site Icon when possible", and then extend `class.jetpack-twitter-cards.php` to behave much like `functions.opengraph.php`:
https://github.com/Automattic/jetpack/blob/master/functions.opengraph.php#L310-L340

We'll just need to check for the image size before to use it, since Twitter requires images that are quite large:
> Images for this Card should be at least 280px in width, and at least 150px in height. Image must be less than 1MB in size.
https://dev.twitter.com/cards/types/summary-large-image

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/twitter-cardsummary-is-this-something-jetpack-creates/

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
