### ISSUE TITLE
Carousel: Display additional metadata

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#295]
Add hooks to allow for the display of additional pieces of metadata for the image (year photograph taken, etc or whatever else).

Originally suggested in 1772224-t.

**Comment by kristarella** [comment]
Reinstating that filter would be appreciated.

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/how-to-enable-map-showing-geocoords-in-carousel?replies=1

**Comment by paolofid** [comment]
Is there any chance to add geo location information on carousel and link to google maps with pin on the photo geo location?

**Comment by lschuyler** [comment]
Also requested in 2497155-t.

**Comment by paolofid** [comment]
Thank you to jeherveand and lschuyler 
I undertand it is something planned to be added but it's not clear to me if it is something that will happen soon.
You are really making a wonderful work with updates and maintenance of jetpack and carousel.

however it seems that this issue is on hold since long time and this is making me somehow sad... :(

do you have any forecast for that? I think this would make many people so happy! there is no valid alternative around and the way carousel show photos and pieces of exif is simply wonderful!
The further step should be very simple, isn't it?

thank you again, I look forward to receiving your answer

**Comment by jeherve** [comment]
@paolofid We don't have any ETA to add this feature back to Jetpack's Carousel module, but we've discussed some possible ways to add the feature back above. If you'd like, you can contribute to the plugin by [proposing a Pull Request](https://github.com/Automattic/jetpack/blob/master/CONTRIBUTING.md) adding the options we mentioned above.

**Comment by paolofid** [comment]
Hello

What should I do once in the page linked by you? (proposing a pull request)?

I land in https://github.com/Automattic/jetpack/pulls but when I click on “New Pull Request” i go to to a page with forks comparison and I’m not sure what to click.

 

On a slightly different subject, can I make a donation to have the the feature working again on Jetpack with geo locations and google maps?

 

 

Da: Jeremy Herve [mailto:notifications@github.com] 
Inviato: giovedì 21 gennaio 2016 07:42
A: Automattic/jetpack <jetpack@noreply.github.com>
Cc: paolofid <pf@paolofidanzati.it>
Oggetto: Re: [jetpack] Carousel: Display additional metadata (#295)

 

@paolofid <https://github.com/paolofid>  We don't have any ETA to add this feature back to Jetpack's Carousel module, but we've discussed some possible ways to add the feature back above. If you'd like, you can contribute to the plugin by proposing a Pull Request <https://github.com/Automattic/jetpack/blob/master/CONTRIBUTING.md>  adding the options we mentioned above.

**Comment by jeherve** [comment]
> What should I do once in the page linked by you? (proposing a pull request)?

If you're not familiar with Pull Requests, you can read more about it here:
https://help.github.com/articles/using-pull-requests/

They're a way for you to propose code changes you wrote to the Jetpack plugin. If you don't feel comfortable editing PHP and JS code, I'm afraid you wont' be able to use that feature.

> On a slightly different subject, can I make a donation to have the the feature working again on Jetpack with geo locations and google maps?

That's exactly what this issue is about: bring back the option to add additional metadata like geolocation to the Carousel. We do not, however, accept donations.

**Comment by ethansmith** [comment]
+1 for bringing this feature back.

**Comment by eliorivero** [comment]
Closing since this is now fixed in https://github.com/Automattic/jetpack/pull/6352. There's one example showing how to add new tags to be displayed and another showing how to rewrite the list including only what you want to display.
