### ISSUE TITLE
Custom CSS: Quick Export Option

### ISSUE THREAD

**Issue by bhubbard** [Automattic/jetpack#2951]
We use jetpack on a lot of sites, and the custom css gets used regularly on each for quick css changes. It would be great if there was a quick export button. This would offer a quick backup solution, or make it easier for devs to take that css and then merge into a theme or child theme.

Bonus: If it has the option to choose to backup as a minified file.

**Comment by jeherve** [comment]
Since Custom CSS is stored in a Custom Post Type, you should be able to pull it directly from the database, or using WordPress' export tools and only pulling posts belonging to the `safecss` post type. That's probably the fastest way to move Custom CSS from site to site, and it doesn't need any additional code in Jetpack.

I hope this helps.
