### ISSUE TITLE
Fatal error: Cannot declare class Instant_Articles_Jetpack plugins/fb-instant-articles/src/compat/class-instant-articles-jetpack.php on line 9

### ISSUE THREAD

**Issue by sandeepavasthi01** [Automattic/jetpack#29556]
Hi,

When we trying to update the FBIA plugin. Then this error is coming.
What can i do ? Please help me as soon as possible.

Thanks

**Comment by jeherve** [comment]
I'm afraid we will not be able to help. The error is caused by the Instant Articles for WP plugin, and the Jetpack plugin cannot control how the FBIA plugin behaves.

I would normally recommend that you contact the team working on the Instant Articles for WP plugin to let them know about the issue; they would be able to help you fix this. However, the Instant Articles for WP plugin is now deprecated:

> At this point in the product lifecycle, publishers should be advised to stop using this plugin, and instead, use direct site traffic for Facebook content. Meta have announced that Instant Articles will have all support dropped at April 2023.
-- [https://wordpress.org/plugins/fb-instant-articles/](https://wordpress.org/plugins/fb-instant-articles/)

I would consequently recommend that you deactivate the plugin to solve this issue.
