### ISSUE TITLE
CPTs: Shortcode markup issue

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/jetpack#2958]
We have the following issue in both Portfolio and Testimonial shortcodes.

With <a href="https://github.com/Automattic/jetpack/commit/529cecb63e57a7aa7077ee39fda0ec313019a5d0#diff-2da4a1879ab00cd88d001db523ff3ed2R568">this changeset</a> in 3.8.0, the content is outside of `xxx-entry-content` `div`. See the screenshot below.

![screen shot 2015-11-05 at 04 02 28](https://cloud.githubusercontent.com/assets/908665/10959702/9ba17d4e-8373-11e5-8f30-f9c73dc7917d.png)

**Comment by jeherve** [comment]
cc @chaselivingston @dereksmart

**Comment by michaeldcain** [comment]
`the_content()` and `the_excerpt()` echo the results of `get_the_content()` and `get_the_excerpt()` after passing them through their respective filters. Using them inside another `echo` is causing the wonky output.

We should keep `the_{content/excerpt}()` instead of `get_the_{content/excerpt}()` for the filtering though.
