### ISSUE TITLE
Twitter Share button counter 

### ISSUE THREAD

**Issue by sunipeyk** [Automattic/jetpack#2959]
After the last upgrade of jetpack, Twitter share button couldn't fetch the shared number any more. Not new also the old posts too.

**Comment by jeherve** [comment]
This is actually due to a change on Twitter's end. We will no longer be able to display counts on the Twitter button due to <a href="https://blog.twitter.com/2015/hard-decisions-for-a-sustainable-platform">their upcoming API changes</a>. I hope that helps to clear things up!

You can read more about it in #2747 and #2787.
