### ISSUE TITLE
Jetpack Plugin Visual Refresh: At A Glance Dashboard

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#29832]
Visual refresh for the Jetpack Plugin At a Glance dashboard. 

- Most borders removed to reduce business of page. Padding, type size, color, and buttons adjusted.
- Main navigation & footer updated to match all our other products.
- All cards styled to resemble cards in My Jetpack and inactive cards are easier to identify.
- Mini notices at the top of Dashboard and Settings cards now consistent with Emerald.
- Security upsell gets a special highlight

For more images and details: p1HpG7-lx8-p2#dashboard

![Image](https://user-images.githubusercontent.com/7129409/229134128-df24b70f-e970-4a15-9cb2-c55a6c8858e6.png)

**Comment by sergeymitr** [comment]
The PR is in progress: https://github.com/Automattic/jetpack/pull/30210

**Comment by jeffgolenski** [comment]
Just gave this a test in `bleeding edge` and it's looking amazing. I tested 4 different product / feature states and I'll drop each one as a comment with a screenshot here. Changes are mostly minor! Great work.

Please see the dev specs in Figma or the **JP Core Emerald page** in the Jetpack Library in Figma to see all component variations, if you need to check for examples. 

- [x] Need 32px padding between header and content (JITMs / Notices / Stats)
- [x] "Action needed" labels need to be `yellow 30` and include the dot
- [x] All circular info icons should be `gray 30`
- [x] All close icons should be `black`
- [x] Toggles and card titles should be vertically aligned
- [x] Ensure all links are `black` + underlined (see "Customize your search experience)
- [x] Boost card header isn't as tall as the VideoPress header (probably because of the toggle). Can we ensure the header is the same height as the most tall header in the row?


![At a Glance 01](https://user-images.githubusercontent.com/214813/234353916-e6b87c8f-5a57-4242-8a3e-a3b3f4b77b45.png)

**Comment by jeffgolenski** [comment]
- [x] Ensure the bottom padding of all card (including inactive features) is at least 16px. A few of them appear to be less
- [x] Right align all toggles with the content of the cards and other head status labels (should be flush 16px right padding)
- [x] Some cards don't include the proper shadow (see CRM, Boost, and mobile card)

![At a Glance 02](https://user-images.githubusercontent.com/214813/234354613-84e81c53-9562-491f-bf03-91ada3dd3fb4.png)

**Comment by jeffgolenski** [comment]
- [x] Empty state illustration should be replaced with a large Jetpack Logomark (64 x 64 px)
- [x] Empty state text should be `gray 80` ("Hello there! Jetpack Stats has been activated...")
- [x] Akismet card: "Already have an API Key? Activate Akismet Anti-spam" - Button should be a simple text link, and the text should align left with the text above it
- [x] Akismet card: The "A" Akismet icon can be removed in this card to save space.
- [x] Support card: A `Gray 5` border is needed between the 2 support buttons and the upsell line below them (see the VP Backup Card in the same screenshot)
- [x] Mobile card: Shadow needed


![At a Glance 03](https://user-images.githubusercontent.com/214813/234355119-ddec30fc-c57a-407b-870c-afbd7dd304c2.png)

**Comment by jeffgolenski** [comment]
- [x] Scan card: Remove background color from the threat number. Make the number itself red 50
- [x] Scan card: Ensure all links are `Black` + underlined

![At a Glance 04](https://user-images.githubusercontent.com/214813/234356378-fb23e4a3-cb53-4b3d-ae2c-709f8ef51a8d.png)
