### ISSUE TITLE
Check backward-compatibility if paid-newsletters are disabled

### ISSUE THREAD

**Issue by millerf** [Automattic/jetpack#29878]
If a blog with paid-newsletter enabled is somehow disabled (Stripe account unlinked, or any other way...), the posts that are gated seem to be in a strange way: paid-gated post would still display

<img width="200" alt="Screenshot 2023-04-03 at 11 44 42" src="https://user-images.githubusercontent.com/790558/229560638-7c5c5910-46f4-4acf-9a4a-773919d8c944.png">

But will not be gated anymore if the Stripe account is removed.

### What to do in this task
Those should behave as a "subscribers"-gated post.

- [x] Test that this is the actual behaviour
- [x] Fix the displayed text
- [x] Fix the behaviour
- [x] Check that a  "subscribers"-gated post still behaves properly

### Hint

Switching from test store to production store "should" make a site behave as if the Stripe account was removed.

**Comment by romarioraffington** [comment]
What I've observed:

1. When Stripe is disconnected, the post is still gated
2. The gated post returns to the defaulted behavior of the Subscribe block ( i.e Users can subscribe without paying )
3. "This post is for paid subscribers"  is displayed as the gated text even though the post is no longer a paid subscribers post since Stripe was disconnected. Fixed in https://github.com/Automattic/jetpack/pull/29880


I believe step 1 and 2 is the correct behavior
