### ISSUE TITLE
Stats: Jetpack stats widget not loading on /wp-admin/ dashboard for AT and Self-Hosted

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/jetpack#30407]
### Quick summary

Jetpack stats widget loads never loads on the `/wp-admin` dashboard (`SITE_ADDRESS/wp-admin/`)

Stats load as expected in these other locations:

https://wordpress.com/stats/
/wp-admin/admin.php?page=jetpack#/dashboard
/wp-admin/admin.php?page=stats

I was able to recreate this on a test Atomic site and a self-hosted site. 

### Steps to reproduce

1. Go to an Atomic test site using Jetpack stats.
2. Visit the site address, for example: testsite.com/wp-admin/index.php
3. Check Stats section.

### What you expected to happen

Stats should load.

### What actually happened

There is a loading icon and the stats do not load.

Screenshot: 
<img width="501" alt="Stats not loading on WP Admin" src="https://user-images.githubusercontent.com/30788962/235304672-5d3bb2a1-3a05-4efb-95b0-e38e039ca92d.png">

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic, Self-hosted

### Logs or notes

User report: 39268511-hc
The user requested a follow-up if there is any update: 6246637-zd-woothemes

A workaround is to use any other working stats dashboard.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Could Not Replicate
- Tested on Atomic – **Replicated**
- Replicable outside of Dotcom – **Yes** on Jetpack Connected Site

📌 FINDINGS/SCREENSHOTS/VIDEO
- On my Atomic and Jetpack-Connected Self-Hosted site, the Jetpack Stats module on the WP Admin dashbaord are indefinitely loading.

#### Screenshots/Recordings

**Self-Hosted**

https://user-images.githubusercontent.com/27249804/235746306-dacd9086-bd7b-4d16-8d0f-9d079d85dea7.mp4

Console Log shows:

```
Uncaught (in promise) Error: Loading CSS chunk 8009 failed.
(https://widgets.wp.com/odyssey-stats/v1/c24139c3a772a351942a.css)
    onload https://widgets.wp.com/odyssey-stats/v1/widget-loader.min.js?minify=false&ver=calypso-4917-11903-gb5a8f64874:1
```

📌 ACTIONS
- Assigned to Other
- CC @Automattic/jetpack  
- Transferred to `/jetpack` repo because this issue does not appear in Calypso, only the wp-admin dashboard.
- Possibly related to this recent issue? https://github.com/Automattic/jpop-issues/issues/8254

**Comment by jsnmoon** [comment]
I believe https://github.com/Automattic/jetpack/pull/30374 should resolve the issue. Could you give it a try reproducing the issue on [Jetpack 12.1](https://jetpack.com/2023/05/02/jetpack-12-1-under-the-hood-improvements-for-your-site/), which should include this fix?

**Comment by cuemarie** [comment]
Thanks @jsnmoon ! My WPcom sites are still on 12.1-beta for the moment, but I spun up a Jurassic Ninja site on 12.1, and the stats widget look great!

![8sR1Fa.png](https://user-images.githubusercontent.com/27249804/235795352-c876c362-c9c5-4c6a-8ff1-b69c9fbc1cc2.png)

**Comment by jeherve** [comment]
Fixed in #30374

**Comment by ithubeg** [comment]
i'm still having this issue

**Comment by jeherve** [comment]
@ithubeg Could you contact us via [this contact form](https://jetpack.com/contact-support/?rel=support&hpi=1), and give us more details about your site there? It could be that some connection issues are stopping the widget from loading properly.
Thank you!

**Comment by c266** [comment]
I have the same problem. Everything up to date.

404 error on
https://widgets.wp.com/odyssey-stats/v1/aa2a31994871f2e04373.css

**Comment by jeherve** [comment]
@crmb Could you attempt to update to the most recent version of the Jetpack plugin? If that doesn't help, could you contact us via [this form](https://jetpack.com/contact-support/?rel=support&hpi=1) and give us more details about your site there, so we can take a closer look?

Thank you.
