### ISSUE TITLE
Single Sign On configurations need more information

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#3042]
Setting up single sign on, on a few of my sites I realized...

To a non-technical user these two things would leave me very confused if I didn't already know what they were. We should provide more information so they don't have to go digging for it. At the very least ? icons to get them to the right place. 

![screen shot 2015-11-18 at 7 50 18 pm](https://cloud.githubusercontent.com/assets/214813/11259182/95759e90-8e2d-11e5-92d2-3edaacc8048c.png)

**Comment by kraftbj** [comment]
For a bit of back history, there were/are more options there that were commented out with "hide in 2.9" notes :) ( https://github.com/Automattic/jetpack/blob/master/modules/sso.php#L159-L176 )

Personally, I'd like to see this in 3.9 along with reviewing the Hidden Options and seeing if whatever rationale for hiding them still applies and since I know @dereksmart is chopping on the bit to get 3.8.1 out to beta.

**Comment by jeffgolenski** [comment]
@kraftbj Awesome. Thanks for being on top of things man!

**Comment by v18** [comment]
@ebinnion - I don't think we'll be adding any more settings to that page, and we removed the 'match by email' option since that's the default. Should we close this issue or leave open so we can take another look in the future?

**Comment by ebinnion** [comment]
We can probably close this. As @kraft pointed out, we intentionally removed some options (though, I'm not too sure why). And since we're moving to the React admin, we can handle it there.
