### ISSUE TITLE
Custom Content Types: Testimonial Post type available even if module is deactivated

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#3044]
1. Install Jetpack.
2. Do not turn on the Custom Content Type Module
3. Install a theme that supports the Testimonials post type (User was using
Sequential and someone else saw the same thing with Sela and Twenty
Fifteen.)
4. The testimonial post type is available even though the module is
turned off.
5. Toggling the module on and off again does not solve the problem.

https://wordpress.org/support/topic/testimonials-active-regardless-of-jetpack-custom-content-types-module?replies=1#post-7675546

2425723-t

**Comment by mrwweb** [comment]
I think this is a duplicate of this: https://github.com/Automattic/jetpack/issues/2890

**Comment by chaselivingston** [comment]
Indeed, closing as duplicate of #2890

**Comment by mrwweb** [comment]
I've read both your replies twice and will try to respond.

I didn't realize that `add_theme_support ( 'jetpack-testimonial' );` was intended to override all settings. I figured it was intended to indicate that the CPT would be available when the module was turned on.

The settings on Settings > Writing are new to me. I didn't even know they were there. It also seems a little odd that `add_theme_support ( 'jetpack-testimonial' );` prevents you from disabling the post type. Is it a good assumption that if a theme supports something a person must use it?

I *love* the idea of standardized CPTs, but as more are added that only will increase the times when a theme supports a CPT but the user doesn't want to use it.

**Comment by jeherve** [comment]
> It also seems a little odd that add_theme_support ( 'jetpack-testimonial' ); prevents you from disabling the post type. Is it a good assumption that if a theme supports something a person must use it?

That's where we have a bug. You should be able to disable the post type by deactivating the Custom Content Types module. Unfortunately, deactivating the module doesn't deactivate the post types right now. That's what we need to fix!

**Comment by mrwweb** [comment]
> You should be able to disable the post type by deactivating the Custom Content Types module

That I understand and I'm glad you'll fix it. I was more referring to this though:

![image](https://cloud.githubusercontent.com/assets/1238696/11306871/691c3b14-8f69-11e5-962a-e62765cd6876.png)

If there are plans to add more post types to the Custom Content Types Module in the future, I think it's more likely that you'll have people who want one theme-supported post type or another but not all. My expected behavior of all of this was:

- Disabling Custom Content Types Module unregisters all CPTs.
- Settings > Writing allows for granular control of each CPTs, `add_theme_support()` or no.
- `add_theme_support( 'jetpack-{cpt}' )` *defaults a CPT to checked on Settings > Writing* the first time the module is enabled or Jetpack is installed.

Maybe that's wrong, but it's what makes sense to me when looking at everything.

**Comment by jeherve** [comment]
I see what you mean. That's certainly an option worth considering. We might want to do more than just checking the box, to let site owners know that the box was checked by default because of their theme. Maybe we could leave that "Your theme supports testimonials" message there, in addition to the checkbox.

Would you mind creating a new issue with that suggestion?

**Comment by jeherve** [comment]
@mrwweb Thank you! :)

**Comment by cliffordp** [comment]
Just chiming in to say this is still happening on WP 4.4 and Jetpack 3.8.2.

Thanks for working on it.
