### ISSUE TITLE
Get rid of css and jquery being loaded while no module active

### ISSUE THREAD

**Issue by KienTrong** [Automattic/jetpack#3057]
As the title above, just try Jetpack and no module active but on the front-end the devicepx-jetpack.js and jetpack.css are being loaded. is it a bug or jetpack enable it by default?

Thanks.

**Comment by kraftbj** [comment]
That is by design. The CSS, specifically, we load all front-end into one file to reduce http requests (can be disabled via `add_filter( 'jetpack_implode_frontend_css', '__return_false' );` to return to the older way of each module enqueing separate CSS files.

devicepx-jetpack.js is loaded by default when Jetpack is active (e.g. a token is present indicating a valid connection to WordPress.com) It supports enhanced Photon, Gravatar, etc imaging when using HiDPI devices.
