### ISSUE TITLE
AI Assistant: Change previous content detection to include blocks like the list block

### ISSUE THREAD

**Issue by dhasilva** [Automattic/jetpack#30619]
When detecting content above the AI Assistant block, it checks for `content` block attribute, which does not work for lists or images with captions.

To reproduce:
- Add a list
- Add an AI Assistant block
- Add a paragraph
- Check that the AI Assistant block does not detect previous content
- Move the AI Assistant block below the paragraph
- Check that the AI Assistant block now detects the paragraph content

**Comment by lhkowalski** [comment]
I am playing with this locally, exploring which methods do we have to get the content from a block and what we can do with them.

**Comment by lhkowalski** [comment]
I did some tests using the HTML content from the blocks (using [`getBlockContent`](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-blocks/#getblockcontent)). Since ChatGPT can understand HTML, it does a decent job on some operations. The simplify action, for example:

<img width="692" alt="Screen Shot 2023-05-10 at 18 55 52" src="https://github.com/Automattic/jetpack/assets/6760046/088b7d14-828a-4820-b68e-226c671689e0">

In the example above, the table was the existing content and the text below it was the result of the simplify action. It worked on lists as well.

---

Tested it using the "Correct spelling and grammar..." action and it worked better than I expected.

The original table, with some typos and errors:

<img width="688" alt="Screen Shot 2023-05-10 at 19 01 15" src="https://github.com/Automattic/jetpack/assets/6760046/6b19632c-6c8c-4934-a3cd-4c31911e364c">

The result:

<img width="693" alt="Screen Shot 2023-05-10 at 19 01 28" src="https://github.com/Automattic/jetpack/assets/6760046/cf992eb8-2fd0-47e0-b487-74fbd42a4c49">

The table is there and the errors got fixed, but it expanded a lot the content and also changed the column ordering of the table. This probably could be fixed using some strict rules on the prompt.

---

There is a lot of things to test yet, but this seems promising.
