### ISSUE TITLE
AI Assistant: Change the cooldown logic to avoid cached responses when the request is not a retry

### ISSUE THREAD

**Issue by dhasilva** [Automattic/jetpack#30649]
Currently we have a request cooldown of 15 seconds when a cached response is given. This causes some problems when unrelated requests are done in quick succession.
We should check if the request is a `retry` before sending the cached response, otherwise respond with a `429 Too Many Requests` status to let the frontend know that it should wait.

ref p1683749397068959/1683747782.692629-slack-C054LN8RNVA

**Comment by lhkowalski** [comment]
I am reviewing the logic for the cooldown time and checking what we can do to improve while still protecting the API from abuse.

**Comment by lhkowalski** [comment]
It now came to my mind that this is not an issue since we moved to the streaming of completions for text.

The old endpoints, that are throttled, are still in use for image generation. The caching period for images os a full month, so the same images are generated for the same prompt on this 1-month window, regardless of the user that tried it.

**Comment by lhkowalski** [comment]
Since the cooldown time for text is not affecting the block anymore, I will close this as not needed anymore.

I also created a new issue to track the image caching thing, so we can get to it when the time comes: #30740
