### ISSUE TITLE
Ai Assistant: revisit spinner and double check with dark backgrounds

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#30716]
![Image](https://github.com/Automattic/jetpack/assets/16329583/048c961f-8d9c-4a3e-a6b5-03a66472643a)

**Comment by nunyvega** [comment]
Maybe we can use the default WordPress spinner component:
https://wordpress.github.io/gutenberg/?path=/story/components-spinner--default

**Comment by nunyvega** [comment]
Current spinner on dark backgrounds:

https://github.com/Automattic/jetpack/assets/16329583/27785562-cc48-4194-b6da-62c267b97821

**Comment by dhasilva** [comment]
I fixed the loader on dark themes in this PR (not yet merged):
https://github.com/Automattic/jetpack/pull/30873

I did not mark myself in this issue as the design can change. Just linking it here because the PR may be enough for this issue as well.

**Comment by keoshi** [comment]
> Maybe we can use the default WordPress spinner component:

Couldn't agree more, @nunyvega. Especially since we're dealing in the context of Gutenberg, we should be reusing the spinner component.

In the mock below we replaced the blue color with the `Jetpack Green 50`. In terms of light/dark theme, not sure if the existing spinner offers any automatic fallbacks?

![image](https://github.com/Automattic/jetpack/assets/390760/ccf6dd63-7afb-487a-9cb0-cbed98a93ed7)

**Comment by retrofox** [comment]
~I think we should set the background color white in the whole component, in the same way that the Placeholder component does in core.~
