### ISSUE TITLE
Jetpack AI: create My Jetpack card

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#30728]
We need a way to upgrade to Jetpack AI.
Possible proposal from My Jetpack (replace Extras card):
![Image](https://user-images.githubusercontent.com/16329583/238385105-6d8575b9-8dd1-4f9d-ab1c-db03f846fa74.png)

Which then takes to the interstitial of Jetpack AI introduced in [#30543](https://github.com/Automattic/jetpack/pull/30543)

**Comment by oskosk** [comment]
I like the idea of replacing the Extras card with the Jetpack AI one, as it doesn't offer much value currently. Let's go this way for now

**Comment by keoshi** [comment]
If we have appetite for more, here's a mock of a banner highlighting the product at the top of the My Jetpack page:

![image](https://github.com/Automattic/jetpack/assets/390760/9a9987ab-f843-4834-a657-37ec208fc293)

gG1smMHbNGas0qwP9y6RwK-fi-3669_13106

**Comment by ederrengifo** [comment]
Just to add more ideas, here are ideas for the three states this card should have:

- When it is not installed (do users need to do this, or does it come already installed with the update?)
- When it is installed but for free, in which case it would be good if we use an Upgrade CTA (can we include the remaining free prompts here?)
- When it is upgraded. Since there is nothing to manage, maybe we can point to the Support documentation.

 
![ai-myjetpack-1](https://github.com/Automattic/jetpack/assets/10525007/e51b6f0e-1d87-4030-a31d-43be26d65b49)

**Comment by nunyvega** [comment]
Thanks folks for the designs. 
Let's go with the card for this week and present that banner to @robertbpugh and @augurlu so we can use it as part of our feature communication campaign.

**Comment by ederrengifo** [comment]
btw, I noticed here (and in the original designs for the latest version of My Jetpack) we switched to "Get" instead of "Install". Maybe we can use that word? (Related to the other card for the interstitial)

**Comment by renatoagds** [comment]
> btw, I noticed here (and in the original designs for the latest version of My Jetpack) we switched to "Get" instead of "Install". Maybe we can use that word? (Related to the other card for the interstitial)

It is being used, since it's the default for all plugins.

**Comment by renatoagds** [comment]
While coding this one I saw that we don't have a `Manage` place to redirect the user in `Jetpack Ai`. Some thoughts about what we could do @ederrengifo @nunyvega ?

Initially I just disabled it.

**Comment by renatoagds** [comment]
Closing since it was merged and we can open a new one to improve the card.
