### ISSUE TITLE
Photon isn't working in 4.3.1 after latest update

### ISSUE THREAD

**Issue by ChrisBegley** [Automattic/jetpack#3087]
I just upgraded to Jetpack  3.8.1 on my WordPress 4.3.1 sites, and noticed some issues with Photon. It's no longer resizing my images to the sizes defined in my themes. On one of my sites it's now loading in the full sized images (with the resize query). On another site that's using the Twenty Fifteen theme, it's loading in small 80x80 featured image sizes instead of 825x510.

**Comment by kraftbj** [comment]
Thanks @ChrisBegley. Can you contact us at https://jetpack.me/contact-support/ . We'd like to dig in with your specific setup a bit more to see what made it past us in testing so we can correct it.

**Comment by ChrisBegley** [comment]
Thanks @kraftbj, I just sent an email with more info.

**Comment by kraftbj** [comment]
@ChrisBegley's issue is due to Photon now supporting post_thumbnails and srcset, and srcset relying on the sizes contained within the metadata for an attachment. On his site, he unset the larger sizes since Photon, strictly speaking, doesn't need those files, but Core's srcset does. The result is Core thinks the 80x80 is as best as it can get, at least is my understanding.

To resolve, we need to improve Photon to create our own srcset and use that instead of relying on Core. Related #2918.

**Comment by ChrisBegley** [comment]
I just thought of another example where some users may run into this problem. 

One of the benefits of Photon was that when you switched themes, it automatically generated the new post thumbnail sizes for you, eliminating the need for plugins like Regenerate Thumbnails. I don't think that will happen anymore.

**Comment by kraftbj** [comment]
Indeed. We didn't regen thumbnails, but basically didn't care about the sizes that already existed. As of now, since we use Core's srcset support, which does care, situations like that may appear.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/freaky-size-of-some-thumbnails-since-the-update
