### ISSUE TITLE
AI Assistant: improve error message when user is disconnected

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#30934]
Whenever a user is disconnected from Jetpack, we show this error message:

![Image](https://user-images.githubusercontent.com/16329583/240886908-da2670c3-dbd4-4dfd-a7b7-977c13b2b13a.png)

Update this to an error that explains what needs to be done or a CTA

**Comment by keoshi** [comment]
Would we be able to do something like this:

- Change the styling of the notice above the prompt.
- Add copy explaining the error, and give users a CTA to fix the issue.
- Lower the opacity of the input box until the problem is solved and disable any clicks on it.

![image](https://github.com/Automattic/jetpack/assets/390760/7b1eb392-2c5c-4936-83aa-a35ba23e411a)
