### ISSUE TITLE
Carousel: Master kill switch for comments

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#3101]
The Carousel window allows comments, that are associated with the attachment post, based on each media item's Discussion settings.

Individual attachments will have comments enabled based on Core's generic option for opening comments on new articles. To disable for an individual media item, users need to visit the Media Library, choose a particular image, click the "Edit More Details" link, (enable the Discussions metabox via Screen Options), uncheck Comments and Save.

Idea: Should we add an option that will kill the comment form on all carousel modals? Or is there a better way to handle this ourselves? Or a Core problem?

ref: 2443324-t

**Comment by jeherve** [comment]
Related:
http://jetpack.me/2013/05/01/remove-comments-carousel/

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Comment by jeherve** [comment]
> It dosn't work in the most cases.

I assume this is the issue reported in #11148; it will be fixed in the next release.

> Ugly and disturbing

It would be good to find out more here; the comment feature is not displayed in the modal by default, you have to scroll down to see it. Are they referring to the same comment feature?

> Pics would be more centered.

The comment form does not have an impact on the alignment of the images in the Carousel modal.

Could you ask them for more details about this?

**Comment by htdat** [comment]
Thanks Jeremy. I am asking this user in 1744463-zen.

**Comment by tbradsha** [comment]
Requested here: 11166400-hc.

**Comment by zdenys** [comment]
Another where it would have been helpful to avoid the CSS solution 16997128-hc

**Comment by jeherve** [comment]
This was implemented in #15436.
