### ISSUE TITLE
Sharing: Email button -- wp_mail_from_name & wp_mail_from should not overwrite wp_mail headers

### ISSUE THREAD

**Issue by stl99** [Automattic/jetpack#3119]
When you use the wp_mail_from_name & wp_mail_from filters to implement a custom from name and email address, replying to an email sent via "Jetpack share via email feature" uses the wp_mail_from email address instead of the address the user added as email address to the Jetpack share via email form.

It would be great if replying to an email shared via Jetpack would actually use the sender's email address, not the one set with wp_mail_from (which is the administrator's email address).

**Comment by jeherve** [comment]
`wp_mail_from_name` & `wp_mail_from` indeed work as expected here: they overwrite the data Jetpack's Email sharing button sets for the sender name and sender email address, before to send out the email with `wp_mail`.

Unfortunately, the email sharing button is the one case where the 2 filters should **NOT** be able to overwrite the default `wp_mail` settings.

This issue seems like a good idea!

**Comment by galbaras** [comment]
@jeherve Looks like this one has been fixed. From what I can see, replying uses the "reply-to" header, which contains the sender details. Close?

**Comment by jeherve** [comment]
@galbaras Yep you're right, it was fixed in #3504.
