### ISSUE TITLE
Query Loop block displays all posts as accessible for "Paid subscribers" when the latest post is marked for "Paid subscribers".

### ISSUE THREAD

**Issue by danielk-am** [Automattic/jetpack#31237]
### Quick summary

When the latest post is marked for "Paid subscribers", all posts in the Index template display as accessible for paid subscribers.

When the latest post is marked for "Everybody", all posts in the Index template display the content as though it is open to everybody, even when specific posts are meant for "Paid subscribers".

https://github.com/Automattic/wp-calypso/assets/92185881/62fa8362-9c80-4a7e-928e-a2942c08c5d6

### Steps to reproduce

1. Assign the latest post accessible for "Paid subscriber".
2. All posts on the homepage (latest posts; Index template) display all posts as accessible for "paid subscribers".
3. Assign the latest post accessible for "Everyone".
4. All posts display the content even when specific posts are meant for "paid subscribers".

### What you expected to happen

1. Posts are meant for "paid subscribers", not to display the content when the site displays the latest posts.
2. Posts meant for everyone to display to everyone, and not for "paid subscribers".

### What actually happened

Incorrectly displaying the content meant for everyone as paid subscribers when the latest post is marked for paid subscribers, while the latest post is marked for everyone, resulted in all content displaying to everyone even when specific posts are meant for paid subscribers.

### Impact

All

### Available workarounds?

Not tested.

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by danielk-am** [comment]
A possible workaround is to assign posts meant for paid subscribers with a different category, and use the Query Loop block to display specific categories excluding the ones for paid subscribers.

**Comment by worldomonation** [comment]
I tried to reproduce this issue but could not do so due to confusion around setting up a Stripe connection that appears to be required in order to test.

That said, I think this is a high priority issue since the workaround is troublesome for sites with a large backlog of paid subscriber contents.

Pinging @cuemarie for assistance with Stripe connections.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated as described - the Query Loop block hides/shows the Post Excerpt or Post Content of each post based on the subscriber access of the most recent post. 
- Note - clicking on the post itself, the post is either hidden or shown correctly based on subscriber access - so the issue is just within the QL block.


#### Screenshots/Recordings

**Latest Post = Paid Subscribers Only**

![Markup on 2023-06-06 at 10:38:00](https://github.com/Automattic/wp-calypso/assets/27249804/b9872922-1a0c-466e-ab65-0e36a54197e2)

_Logged Out View:_
![Markup on 2023-06-06 at 10:38:47](https://github.com/Automattic/wp-calypso/assets/27249804/e15ed809-645f-403f-a181-06297b5d3540)

**Latest Post = Everyone, 2nd Latest Post = Paid Subscribers Only**

![Markup on 2023-06-06 at 10:44:10](https://github.com/Automattic/wp-calypso/assets/27249804/7178cf26-1c90-4855-9472-6b0c8df2e600)

_Logged Out View:_
![Markup on 2023-06-06 at 10:44:32](https://github.com/Automattic/wp-calypso/assets/27249804/9dedd740-a9bd-4029-b66b-92a915a454b0)

📌 ACTIONS
- Scrubbed, awaiting assignment
- @jeherve as Newsletter access is powered by Jetpack, is this something JP Crew could weigh in on?

**Comment by jeherve** [comment]
@millerf Could your team take a look at this?

Thank you!

**Comment by millerf** [comment]
@1dr0 Thanks for spotting that issue! It should be fixed now, both on Atomic and WPCOM...
