### ISSUE TITLE
Comments: Page reloading instead of moving comment form on reply

### ISSUE THREAD

**Issue by yj-soh** [Automattic/jetpack#3133]
Tested on a fresh installation of WordPress 4.4, latest Firefox & Chrome.
Jetpack 3.8.1 with only Comments activated, no other plugins.

`addComment.moveForm`, called on reply links for comments, should move the comment form to below the comment it's replying to.
It's just falling back by reloading the page with an appended query string (`[post-url]/?replytocom=[comment-id]#respond`) now, though.
To reproduce, add a post, at least two comments, and reply to the higher one.

This appears related to ticket [#29974 on Wordpress Core](https://core.trac.wordpress.org/ticket/29974).
Specifically, the declaration of a `commentForm` variable and the addition of a check for it (29974.5) that caused the function return an `undefined` (w/ Jetpack Comments) may be breaking the functionality due to Jetpack using an iframe for the comment form.
Not entirely sure since I don't know what was the previous expected return value, though.

**Comment by kraftbj** [comment]
Duplicated this on my production site. It creates a really janky experience that we should fix. Thanks for the report!

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/jetpack-comments-do-not-work-1?replies=2&view=all

**Comment by eliorivero** [comment]
I tracked down the bug to `addComment.moveForm` in `comment-reply.js` where it expects to find a `form` tag inside the `#respond` element
```js
commentForm = respond.getElementsByTagName( 'form' )[0];
```
it later checks for it returns if it doesn't exist. The `undefined` value returned causes:
- element is not moved to the proper comment
- since `false` is not returned, the element default behaviour is triggered, leading to the page reload

I did a quick test wrapping the comments `iframe` with a `form` and it did the trick: form was moved and page didn't reload.

However, the iframe did reload but it's unavoidable due to the DOM move. This is important to considerate because users might type a response to reply, and then notice they were replying to the wrong reply and when they click the correct reply, their reply will be gone. We should save the reply in the top frame so we can reload it in the iframe when it's repositioned.

Perhaps we should completely overwrite `addComment.moveForm` with our own method? would be good if core had the `'form'` parameter passed to `getElementsByTagName` as a variable.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/comments-reply-stoped-working?replies=5&view=all#post-7917755

**Comment by diggisaur** [comment]
This patch fixed my issue that I mentioned here. You can close that support case.
https://wordpress.org/support/topic/jetpack-comments-do-not-work-1?replies=2&view=all

Any idea when this will be rolled into a JetPack update?

**Comment by jonnyjain** [comment]
when your printer is unable to print and unable to perform there task and show a message [printer is in an error state](http://printertechsupportnumbers.com/blog/fix-hp-printer-error-state-windows-10/) after makes some changes in software after happening this error, uninstalling and reinstalling the device doesn't work. Best solution visit them
