### ISSUE TITLE
AI Extension: improve upgrade message when requests are used

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#31588]
Currently we show this message:

![Image](https://user-images.githubusercontent.com/16329583/248932402-08ad8a4c-1deb-4dd4-bade-3097e2aa1ae5.png)

Let's iterate on the current message to make clear how to keep using the feature, with a message in the lines of:

`“You have used all your free prompts. [Upgrade] to get unlimited prompts or [learn more] about Jetpack AI Assistant”

More context here:
p1687806318857109-slack-C054LN8RNVA
pe4Cmx-1p7-p2#comment-661

**Comment by ederrengifo** [comment]
To keep consistency with the existing message we already show for the Jetpack AI block, this is my recommendation:

> You have reached the limit of free requests. [Upgrade now] to keep using Jetpack AI. [Learn more] 

The first link should lead users to the checkout and the second one to our support documentation

**Comment by keoshi** [comment]
Since this is a global message that will be visible outside of the content of Jetpack AI Assistant (meaning when the block is not selected), I'd be tempted to lead with the scope of the message and say it's coming from the AI Assistant as early as possible.

Tweaking the language around "limit" a bit as well to make it more natural.

For example:
> **Jetpack AI Assistant**
> You have used all your free requests. [Upgrade now] to keep using the AI Assistant.

If a double-liner is not possible then:
> **Jetpack AI Assistant**: you have used all your free requests. [Upgrade now] to keep using the AI Assistant.

**Comment by retrofox** [comment]
Let's close it since we will be transforming the extended blocks into AI Assistant instances. The block will take care of the upgrading process.
