### ISSUE TITLE
Sharing Buttons: Skype sharing button not working due to expired SSL cert

### ISSUE THREAD

**Issue by samiff** [Automattic/jetpack#31624]
**To Reproduce:** 

- On a Jetpack connected site, enable sharing buttons in `Jetpack > Settings > Sharing` then click on the "Configure your sharing buttons" link.
- Add the Skype sharing button.
- On the frontend, try sharing a post with the Skype sharing button.

**Result:**

- The popup loads but several resources on the Skype side of things are failing due to an expired SSL cert such as `https://sdk.cdn.skype.com/0-1-12/js/share.js`

Reported via internal testing: p8oabR-1eP-p2#comment-7390

Skype sharing button originally requested in #3170

**Comment by jeherve** [comment]
It may be worth reaching out to the Skype team about this, since that's not something we'll be able to fix on our own.

I posted in the Skype forums here about the issue:
https://answers.microsoft.com/en-us/skype/forum/sk_dev-sk_web/issues-with-the-sharing-sdk-ssl-certificate/67e46fd2-4079-4677-9896-d2d156cfbe04

**Comment by anomiex** [comment]
Looks like they've responded:

> I'm afraid that this cannot be fixed because Skype Buttons are no longer supported.
>
> Also, Skype Web Control was disabled 2 years ago.
