### ISSUE TITLE
Could you provide a detailed security report?

### ISSUE THREAD

**Issue by sweigand** [Automattic/jetpack#3180]
This is more of a feature request: Could JetPack provide a sort-of Security Analytics report on the Blocked malicious login attempts? I would be curious to see the ways/methods. I'm running Sucuri Security in-addition, so I do get a bit of a view into the attempts.

JetPack does a GREAT job of protecting my WordPress sites, definitely carrying on from BruteProtect which saved my bacon many many times!

**Comment by kraftbj** [comment]
Generally, we don't comment on specific ways and methods as that would give those looking to bypass our methods more information to work with.

Protect works through cloud-sourced brute force data. When we see a particular actor perform what appears to be a brute force attack—either isolated to one site or a number of sites within the Protect family—all sites are able to use that information to preempt an attack from that actor. In other words, instead of waiting until an attack is specifically attacking your site to trigger protection for you, you'll already be guarded because the actor first attempted any other site(s) that are part of Jetpack Protect.

**Comment by sweigand** [comment]
Could Protect maybe provide a list of IPs and/or Usernames attempted on a particular site? Protect already provides a nice count of attempts blocked, but Management/C-Level love details.

**Comment by samhotchkiss** [comment]
Hey @sweigand, part of the ways that protect protects your site is by limiting database interactions which are a major contributor to the denial-of-service component of a brute force attack.  As a result, we don't track which particular IPs are trying to get into your site, as that would reintroduce one of the problems we were trying to solve.

There is, however, a hook that we added if you'd like to do your own logging (either to your DB or, preferably, to a file for parsing later): `jpp_kill_login`

You can see this hook here:
https://github.com/Automattic/jetpack/blob/master/modules/protect.php#L524

Let us know if there's anything else we can do to assist!
