### ISSUE TITLE
Paid newsletter subscription issue - Subscriber can't access the content

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/jetpack#31903]
A paid newsletters subscriber on the site cannot read a paid newsletters post. They received the email notification with the post, but can't read the post on the site.

Site/Subscriber info:
- Site is `https://criticaltherapyantidote.org`, on WPcom Business plan.
- The user `valthomas777` is the only "paid newsletters subscriber" on the site.
- There are multiple other subscribers that have sent donations before on this site.
- The post https://criticaltherapyantidote.org/2021/07/13/one-dimensional-intersectional-psychobabble/ is the only post set to "paid subscribers only".

Troubleshooting done:
- ✔️ The post settings show that the post is set to be viewed by "Paid subscribers only": https://criticaltherapyantidote.org/wp-admin/post.php?post=1287&action=edit
- ✔️ Checked the support guide here for paid newsletters and it looks like the site owner did everything right: https://wordpress.com/support/paid-newsletters/. It doesn’t seem like the site owner needs to add their content in the post inside a Paid Content block: https://wordpress.com/support/paid-newsletters/ so they did the right things so far.
- ✔️ The user who's subscribed, "valthomas777", has the site listed as a paid subscription here: https://wordpress.com/read/subscriptions/. They subscribed on Jul 10 2023.
- ✔️ Tested setting the latest post https://criticaltherapyantidote.org/2023/07/13/the-black-african-and-asian-therapy-network-baatn-launches-a-misconceived-training-initiative/ as "paid subscribers only" as well, and I can replicate the problem.
- ✔️ I noticed that the user "valthomas777" had a one-time donation done on the site at one point. I wonder if it has anything to do with that - you can check at https://wordpress.com/subscribers/criticaltherapyantidote.org/230439413?page=1

**Comment by millerf** [comment]
We have some known issues with the Reader's cache: pMz3w-hVN-p2
Can you confirm that this issue is happening when seing the post on the website and not on the Reader?

> Tested setting the latest post https://criticaltherapyantidote.org/2023/07/13/the-black-african-and-asian-therapy-network-baatn-launches-a-misconceived-training-initiative/ as "paid subscribers only" as well, and I can replicate the problem.

This test makes me think you are seing the issue on the Reader...

**Comment by davipontesblog** [comment]
> We have some known issues with the Reader's cache: pMz3w-hVN-p2 Can you confirm that this issue is happening when seing the post on the website and not on the Reader?
> 
> > Tested setting the latest post https://criticaltherapyantidote.org/2023/07/13/the-black-african-and-asian-therapy-network-baatn-launches-a-misconceived-training-initiative/ as "paid subscribers only" as well, and I can replicate the problem.
> 
> This test makes me think you are seing the issue on the Reader...

Hi @millerf , they cannot see the post on the website, or the reader. None work.

**Comment by cuemarie** [comment]
Gave this a look during triage to see if I can help spot anything.

📌 FINDINGS/SCREENSHOTS/VIDEO
- When I SU/SSP in as the site _owner_, I also cannot view the content of the post in question:

<img width="1108" alt="Screenshot 2023-07-17 at 2 18 13 PM" src="https://github.com/Automattic/jetpack/assets/27249804/aefd047a-c261-456d-9a93-08ea5d075e50">

Additionally, under Tools > Earn, I see that while the Premium Content plans are set up, the section **Send paid email newsletters** is showing `Learn how to get started`; this strikes me as incorrect:

![Markup on 2023-07-17 at 14:24:08](https://github.com/Automattic/jetpack/assets/27249804/d812cdff-4bc9-4057-81d0-ab93a649dec4)

Perhaps it's possible something is not working properly with the Newsletter set up on this site in general, rather than just for that one user? I'm sure @millerf will get this sorted from here :) Hope this helps at all

📌 ACTIONS
- Assigned to @Automattic/gold

**Comment by millerf** [comment]
Thanks for looking into this @cuemarie 

> When I SU/SSP in as the site owner, I also cannot view the content of the post in question:

I am a bit skeptical SU is working in that particular use-case. But I might be wrong.

> newsletters is showing Learn how to get started; this strikes me as incorrect:

This is "correct", however unintuitive. We will be redesigning the whole Earn dashboard pretty soon :)

But if the user was actually subscribed, reentering his email address would trigger the "2 FA-code login" , and it clearly does not...

https://github.com/Automattic/jetpack/assets/790558/20ba5873-b30e-4f8a-9b80-f12d9625bf35

I am digging a little bit more into this now...

**Comment by millerf** [comment]
Further findings on Slack: p1689633375955289/1689430191.794019-slack-C02FMH4G8

**Comment by cuemarie** [comment]
> I am a bit skeptical SU is working in that particular use-case. But I might be wrong.

I thought the same! I did also test with SSP and saw the same result, but perhaps both tests are unreliable there 👍

**Comment by millerf** [comment]
>  I did also test with SSP

What is SSP? 

I am setting a new site to be able to test freely, so we can test SU and know for sure...

**Comment by millerf** [comment]
We have a fix for a side of the issue D116327-code

However we identified some issues in p1689695694844569/1689430191.794019-slack-C02FMH4G8 that seem to point toward a problem with Jetpack not syncing properly some data to WPCOM. CC @Automattic/jetpack-crew

**Comment by cuemarie** [comment]
> What is SSP?

This is the predecessor to SU, but can still be used and sometimes helps bypass issues/quirks with SU (for example, occasionally it's needed to help reconnect Jetpack as there's a bug that can happen with SU).

Internal info: P9HQHe-P1-p2

**Comment by millerf** [comment]
@davipontesblog After investigation, I believe this was a mix of small issues:
- There might have been an issue with Jetpack sync on WPCOM so the content was not unlocked properly. It has been fixed: p1689708070760839/1689701094.306599-slack-CBG1CP4EN
- I also believe the user was not loggued in with the right user when checking access, so he could not see the unlocked content, however we have a way to log the user if they enter their email again in the subscribe block, however:
- There was an issue that would prevent retrieving the user subscriptions on WPCOM, now fixed in D116327-code

I would consider this solved. Please let me know if the user encounters further issues,..

**Comment by millerf** [comment]
I have been able to test and now everything works as expected. (once I'll have deployed the patch)

See: p1689790699198329/1689430191.794019-slack-C02FMH4G8

**Comment by millerf** [comment]
We found another issue where some data is not synced to WPCOm preventing for some functionalities (email sent, being a major one). 

> They received the email notification with the post, but can't read the post on the site.

I am not sure how that happened...

**Comment by millerf** [comment]
Considering this as closed. It will properly work on the next JP release, once https://github.com/Automattic/jetpack-production/commit/daa64236b3ba55d3db4d07b8b26ecb626268ebb8 is out.
