### ISSUE TITLE
Portfolios don't consistently display when set as the default homepage content.

### ISSUE THREAD

**Issue by arinoch** [Automattic/jetpack#32141]
Notably on themes with a template to display portfolio content (see 6547697-zd-woothemes), the display of portfolio content on the homepage is inconsistent.

Steps to reproduce:

1. Set up a test site with a portfolio theme (the user is using, and I tested with, Illustratr).
2. Remove post content from the site, and create a test portfolio.
3. Insure that a static homepage is not set in the customizer, or that a homepage template (in the case of an FSE theme) is not in use.
Expected:

When visiting a site, and posts do not exist but portfolio content does, the portfolio content should be displayed where latest posts would go.

What Happened:

On the user's site, portfolio projects display as expected when logged in, but a 404 page is displayed when logged out. On my test site, a 404 page was displayed both when logged in and logged out.

**Comment by jeherve** [comment]
The display of posts and / or portfolio content is entirely controlled by the theme, so this should be fixed in the theme itself. I'll close this issue as invalid. I would recommend opening an issue for the Illustratr theme instead (although I am not sure we should expect the theme to automatically display content from the CPT).
