### ISSUE TITLE
Sharing / Social: update Twitter logo

### ISSUE THREAD

**Issue by rw-ye** [Automattic/jetpack#32178]
### What

Update the logo for Twitter to the new logo

Feature request from user: 6586135-zd-woothemes

### Why

Twitter has recently updated its logo: https://techcrunch.com/2023/07/24/twitter-has-officially-changed-its-logo-to-x/

---

_Just adding a couple places where this appears; feel free to update with more (-cuemarie)_:

- [ ] Social Icons block
- [ ] Sharing Buttons

**Comment by cuemarie** [comment]
📌 ACTIONS
- Feature request kept
- CC @jeherve

**Comment by cuemarie** [comment]
Noted on this internal discussion: p1690826399037819/1690812959.552119-slack-C029KQRGV

**Comment by jeherve** [comment]
As far as I know, the new X logo is currently an interim logo, so we may want to wait until the final logo is revealed, maybe.

When that happens, we'll need to make changes to https://github.com/Automattic/social-logos first, then propagate those changes / update the package's version in the Calypso repo and the Jetpack repo.

This will also need to be updated in Core. I created an issue to keep track of it here:
https://github.com/WordPress/gutenberg/issues/53223

**Comment by bobmatyas** [comment]
Also requested on: https://wordpress.org/support/topic/replace-twitter-sharing-button-with-x

**Comment by syhussaini** [comment]
7140561-zen

I confirmed that he the Plan to update the logo is on hold as the new X logo is currently an interim logo.

**Comment by staproehl** [comment]
7368162-zen

Let user know the plan to update the logo is on hold as the new X logo is currently an interim logo.

**Comment by rakshitwesley** [comment]
Requested here: 7394377-zd-a8c

**Comment by laurelfulford** [comment]
Hi @syhussaini @staproehl @rakshitwesley! The X logo is available in Jetpack and on WP.com as of early-ish Oct (added in #33134). Instead of replacing the bird icon, it's a separate option under the share options (similar to how core handled it in the social icons block, with the two different icons available). Anyone who wants to use it will need to update their share buttons to add the X option:

![image](https://github.com/Automattic/jetpack/assets/177561/c9698748-e8e6-4429-afd9-0f2d67baac1c)
