### ISSUE TITLE
Contact Form: color contrast ratio accessibility issue with "required" text

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#3228]
The "required" label appearing next to contact form fields does not pass the color contrast ratio with most light themes, like Twenty Fifteen.

The color contrast ratio between for the text (#aaaaaa) and its background (#F8F8F8 for Twenty Fifteen) is not at least 4.5 to 1.

**Comment by TechThomas** [comment]
Hello, this issue is not stale it is still an issue on our site https://equalentry.com

An example page when adding a comment that shows the issue
https://equalentry.com/the-vessel-is-nycs-newest-landmark-accessible-for-all/

![Screenshot of color contrast analyzer showing issue](https://user-images.githubusercontent.com/991176/67745920-badb7c80-fa68-11e9-96a9-daa973bd062d.jpg)

**Comment by crunnells** [comment]
Hey @TechThomas, the screenshot in your comment is part of WordPress core, and issues are tracked on [WordPress Trac](https://core.trac.wordpress.org/). I did a quick search but couldn't find a report on the specific issue you referenced, but [reporting accessibility issues](https://make.wordpress.org/accessibility/handbook/reporting-issues/) is highly encouraged.
