### ISSUE TITLE
Repeat Visitor Block: languages that do not use multiplicative numbers to count show a %d when counter is set to 1.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/jetpack#32361]
### Impacted plugin

Jetpack

### Quick summary

Languages that do not use the "once, twice" system for counting (known as "multiplicative numbers") have issues when the value for Repeat Visitor block is set to 1. 

### Steps to reproduce

1. set language to Japanese/Chinese/Korean.
2. open the editor.
3. insert the Repeat Visitor block.
4. set the counter to 1.

### A clear and concise description of what you expected to happen.

Text below the counter should show the equivalent of "...1 time".

eg. 只有访问该页面的次数多于 1 次的访客才能看到该区块。

![image](https://github.com/Automattic/jetpack/assets/6549265/3600470d-9312-47b0-803d-308b2d055bd9)

### What actually happened

Text below the counter shows %d, because the equivalent text in English does not use the arabic numeral 1 but instead the multiplicative number "once".

![image](https://github.com/Automattic/jetpack/assets/6549265/d2fd72ac-2ac4-4b7e-94e9-65b7b73cd576)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

**Comment by jeherve** [comment]
For reference, this is controlled here:
https://github.com/Automattic/jetpack/blob/3a3c4adc1c0913bac224ddb832713bd6101fe1ab/projects/plugins/jetpack/extensions/blocks/repeat-visitor/components/edit.js#L36-L74

We should probably remove the special scenarios when `this.props.attributes.threshold` is `1`.

```diff
diff --git a/projects/plugins/jetpack/extensions/blocks/repeat-visitor/components/edit.js b/projects/plugins/jetpack/extensions/blocks/repeat-visitor/components/edit.js
index 129c926cc4..5f5ab2cf32 100644
--- a/projects/plugins/jetpack/extensions/blocks/repeat-visitor/components/edit.js
+++ b/projects/plugins/jetpack/extensions/blocks/repeat-visitor/components/edit.js
@@ -35,13 +35,6 @@ export class RepeatVisitorEdit extends Component {
 
 	getNoticeLabel() {
 		if ( this.props.attributes.criteria === CRITERIA_AFTER ) {
-			if ( 1 === this.props.attributes.threshold ) {
-				return __(
-					'This block will only appear to people who have visited this page more than once.',
-					'jetpack'
-				);
-			}
-
 			return sprintf(
 				/* translators: placeholder is a number. */
 				_n(
@@ -54,13 +47,6 @@ export class RepeatVisitorEdit extends Component {
 			);
 		}
 
-		if ( 1 === this.props.attributes.threshold ) {
-			return __(
-				'This block will only appear to people who are visiting this page for the first time.',
-				'jetpack'
-			);
-		}
-
 		return sprintf(
 			/* translators: placeholder is a number. */
 			_n(

```

I think this would solve the problem for some languages, but in English we would end up with "1 time" instead of "once". Is that acceptable? Is there a better option here? I'm never exactly sure how to handle this.

 cc @Automattic/i18n Would you have any recommendations here?

**Comment by yuliyan** [comment]
@jeherve, the problem here seems to be with the [translation itself](https://translate.wordpress.org/projects/wp-plugins/jetpack/stable/ja/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=7726341&filters%5Btranslation_id%5D=69298837), rather than the strings in the code. The current translation contains an unexpected %d placeholder, but instead it should use the number 1, as the suggested example in the issue description.

The code itself looks perfectly fine to me and it corresponds with the suggested approach from the [I18n for WordPress Developers Guide](https://codex.wordpress.org/I18n_for_WordPress_Developers#Plurals).

**Comment by jeherve** [comment]
@yuliyan Thank you!

Since that translation was contributed by our paid translators, would there be a way to ask them to correct that translation?

**Comment by yuliyan** [comment]
> Since that translation was contributed by our paid translators, would there be a way to ask them to correct that translation?

Yeah, I'll ask them 👍

**Comment by worldomonation** [comment]
Thanks for the heads up @yuliyan, I went to translate.wordpress.com and looked for the string "this block will only appear to people" but I couldn't find any.

**Comment by yuliyan** [comment]
@jeherve @worldomonation We've received the retranslated string from the translation vendor and deployed it to translate.wordpress.org - https://translate.wordpress.org/projects/wp-plugins/jetpack/stable/ja/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=7726341&filters%5Btranslation_id%5D=69298837.
