### ISSUE TITLE
Option to regenerate WooCommerce image thumbnails disappears when Jetpack is active

### ISSUE THREAD

**Issue by rbgly** [Automattic/jetpack#32392]
### Impacted plugin

Jetpack

### Quick summary

As the title says, when Jetpack is active, the `Regenerate product thumbnails` option cannot be found under `WooCommerce > Status > Tools`.

### Steps to reproduce

1. Deactivate all plugins on the site except for `WooCommerce`:

![1-only-woocommerce-active](https://github.com/Automattic/jetpack/assets/107065508/42f686dc-9793-4bb7-8d1a-b63a407cdc34)

2. Check `WooCommerce > Status > Tools`.
3. The `Regenerate product thumbnails` option should be listed (usually under `Delete WooCommerce tax rates`):

![2-regenerate-shop-thumbnails-showing](https://github.com/Automattic/jetpack/assets/107065508/0cd6df4b-b804-40f4-82de-b1f9924563ce)

4. Now, activate `Jetpack`:

![3-only-woocommerce-and-jetpack-active](https://github.com/Automattic/jetpack/assets/107065508/91065390-7aca-4eff-8ad7-bcf5f4ed2526)

5. The `Regenerate product thumbnails` option no longer shows in the list:

![4-regenerate-shop-thumbnails-disappears](https://github.com/Automattic/jetpack/assets/107065508/a0b3b464-4d89-4b3b-879a-970da4389da7)

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic, Self-hosted

### Logs or notes

This was tested with the theme `Storefront` but also seems to happen for a third-party theme such as `Astra`.

6645263-zen

**Comment by jeherve** [comment]
This seems to be done on purpose in WooCommerce when Jetpack and its Image CDN feature are active, since the image CDN feature negates the need for several different thumbnail sizes:
https://github.com/woocommerce/woocommerce/blob/b2c9373b1919af2b6e3c6217f24ede2c55eed4d6/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-tools-v2-controller.php#L223

If you think this should be better specified, I would recommend opening an issue in the WooCommerce repo about this.
