### ISSUE TITLE
Jetpack Comments: Different user ids in the environment when creating and verifying the nonce

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#32552]
### Impacted plugin

Jetpack

### Quick summary

In #23439 we added nonces to the comments system, which are not being verified properly, If you're signed in to the site.

The nonce is generated with the idea of the user visiting the site, but the validation happens under `id: 0` (anonymous) `wp_verify_nonce` fails.

https://github.com/Automattic/jetpack/assets/746152/7944b4f0-e9b0-4a00-aef1-75d1adffd689

### Steps to reproduce

1. Activate Jetpack comments under Jetpack -> Settings -> Discussion
2. On a post, while signed in to the site, try to leave a comment
3. Expect to get a `Nonce verification failed` message.

### A clear and concise description of what you expected to happen.

I expected to be able to write a comment being signed in. 

### What actually happened

I can't write a comment

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate
- Tested on Self-Hosted site with Jetpack Connected - Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was unable to replicate the issue on any test sites.  On my self-hosted site, I tested commenting with both the owner/admin of the site, and an Editor, and both could comment as expected. 

#### Screenshots/Recordings

https://github.com/Automattic/jetpack/assets/27249804/b34ac006-6a96-4dc4-8648-f5f82560b357

📌 ACTIONS
- Requested author feedback

📌 Message to Author
- @oskosk are there more detailed steps to replicate this problem that you can share?

**Comment by oskosk** [comment]
@cuemarie Have you tried with this setup?

* Logged in to .com
* Logged in to the site with a user whose Jetpack connection matches the .com account you're signed with to .com
* Commenting


For example. This is in an incognito window. on a Jurassic Ninja site.


* If I'm signed into the self-hosted site, but not to WordPress.com, I can comment.
<img width="314" alt="image" src="https://github.com/Automattic/jetpack/assets/746152/61897e7b-06c0-4ff3-8910-93f0a52c7038">


* In the same incognito window, I sign in to .com with the user that connected the Jetpack site and I can't comment

<img width="733" alt="image" src="https://github.com/Automattic/jetpack/assets/746152/31cd8981-bdcb-448d-ba24-54f1c69b969b">

**Comment by oskosk** [comment]
The diagnosis here, matches mine

>Upon further digging, the nonce is different because wp_get_current_user fails upon submission, and returns 0 as the user_id when it is typically something else at page load (in my case, 2).
> I’m not sure why the wp_get_current_user fails upon submission. Hopefully, the developers can figure it out. Fort posterity, I checked this not only with my theme but also twenty-twenty-two. Both produced the same error for the same reasons.

https://wordpress.org/support/topic/jetpack-comment-error-nonce-verification-failed/#post-16276738

**Comment by cuemarie** [comment]
Thanks @oskosk for the added details! It seems the issue was my Discussion Settings.  Updated notes below:

📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Could Not Replicate**
- Tested on Atomic – **Replicated** 
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
-  I was able to repro on Atomic and self-hosted site with the following steps:

- Settings > Discussion, enable `Users must be registered and logged in to comment`
- Refreshed post, and clicked "log in" under comment thread
- Log in to the WordPress.com account that the site is connected to via Jetpack
- Leave a comment.

#### Screenshots/Recordings

**Atomic**

https://github.com/Automattic/jetpack/assets/27249804/ada06f27-b1fc-4e72-a641-2619b4fa3d45

**Self-Hosted**
![Markup on 2023-08-17 at 13:53:09](https://github.com/Automattic/jetpack/assets/27249804/88b4df63-082c-4070-aadc-8961369bd6b7)

https://github.com/Automattic/jetpack/assets/27249804/46a8798e-0f59-49de-8f5a-baa85e7431b4

**Simple** site did not reproduce the same error, and commenting worked as expected.

📌 ACTIONS
- Assigned to Other

**Comment by cuemarie** [comment]
🔔Just a heads up FYI to @Automattic/loop  as this impacts commenting/engagement.

**Comment by oskosk** [comment]
Thanks @cuemarie. 

Noting here that in the Jetpack Admin page settings we don't have that setting as it comes from core. In calypso both sets of settings are merged 

### Jetpack -> Settings -> Discussion
![image](https://github.com/Automattic/jetpack/assets/746152/b6c5620b-7a07-42d0-80d0-78a92897c441)

### Settings -> Discussion

![image](https://github.com/Automattic/jetpack/assets/746152/63e25ff6-813e-404c-8e5f-4a98e9c1ca78)


### Calypso

![image](https://github.com/Automattic/jetpack/assets/746152/a1df9520-909e-4320-8d98-0840d95edb91)

**Comment by jeherve** [comment]
Related:

- p1690992899536269-slack-CA17PSW87
- 7666-gh-jpop-issues

**Comment by jeherve** [comment]
I looked into this a bit. I was able to reproduce on one site (a brand new JN site, freshly connected to my a11n acount), but not on others. I was not able to figure out what was different about the site where I could reproduce.

A few things to note:

1. You do not need to enable the user login requirement (as shown on the screenshots above) to be able to reproduce the issue. 
2. You do need to be logged in with both the local admin account and the linked WordPress.com user.
3. When the problem happens, there is indeed no user info available when Jetpack's `pre_comment_on_post` runs, so the nonce check logically fails.

The Verbum comment UI is slowly getting activated for more and more folks, and it does complicate testing in some scenarios since it does not always seem to reflect the current user situation on the site. In the example below, I was logged in as an admin on the site:

<img width="776" alt="image" src="https://github.com/Automattic/jetpack/assets/426388/7dd82d21-deaa-434c-a4b2-2ac0291e357a">

In this scenario, I should be logged in in the comment form as well. I cannot seem to be able comment as a logged in user at the moment.

In fact, one could argue that when you are locally logged in as admin, you may not need any type of Jetpack Comment UI; you are already logged in, you do not need any kind of social login option at this point.
Looking at the codebase, it looks like logged in users should be allowed to post with other options so the codebase disagrees with my statement above:
https://github.com/Automattic/jetpack/blob/24b4c87ebc8e497f57c524e72ff0d50d8c576327/projects/plugins/jetpack/modules/comments/base.php#L218-L227

 If we removed the Jetpack Comment UI when you're logged in, it would solve this issue. I think it may also avoid some confusion around Jetpack Comments and social login. It would, however, change the way Jetpack Comments have worked until today, and may potentially cause more confusion.

At this point, I'm not sure how to move forward with this. @Automattic/vertex Since you've been working on Verbum, you're most likely the most familiar with this at the moment. Do you have any ideas?

**Comment by heavyweight** [comment]
> I looked into this a bit. I was able to reproduce on one site (a brand new JN site, freshly connected to my a11n acount), but not on others. I was not able to figure out what was different about the site where I could reproduce.
> 
> A few things to note:
> 
> 1. You do not need to enable the user login requirement (as shown on the screenshots above) to be able to reproduce the issue.
> 2. You do need to be logged in with both the local admin account and the linked WordPress.com user.
> 3. When the problem happens, there is indeed no user info available when Jetpack's `pre_comment_on_post` runs, so the nonce check logically fails.
> 
> The Verbum comment UI is slowly getting activated for more and more folks, and it does complicate testing in some scenarios since it does not always seem to reflect the current user situation on the site. In the example below, I was logged in as an admin on the site:
> 
> <img alt="image" width="776" src="https://user-images.githubusercontent.com/426388/272240489-7dd82d21-deaa-434c-a4b2-2ac0291e357a.png">
> In this scenario, I should be logged in in the comment form as well. I cannot seem to be able comment as a logged in user at the moment.
> 
> In fact, one could argue that when you are locally logged in as admin, you may not need any type of Jetpack Comment UI; you are already logged in, you do not need any kind of social login option at this point. Looking at the codebase, it looks like logged in users should be allowed to post with other options so the codebase disagrees with my statement above:
> 
> https://github.com/Automattic/jetpack/blob/24b4c87ebc8e497f57c524e72ff0d50d8c576327/projects/plugins/jetpack/modules/comments/base.php#L218-L227
> 
> If we removed the Jetpack Comment UI when you're logged in, it would solve this issue. I think it may also avoid some confusion around Jetpack Comments and social login. It would, however, change the way Jetpack Comments have worked until today, and may potentially cause more confusion.
> 
> At this point, I'm not sure how to move forward with this. @Automattic/vertex Since you've been working on Verbum, you're most likely the most familiar with this at the moment. Do you have any ideas?

Our efforts are scattered across multiple places ATM, but we have this patch D123363-code. We need to address the issues there.

**Comment by heavyweight** [comment]
We were fixing a related issue and to me it seems that this got fixed as well.
Can someone try to reproduce this? No need for any testing setup except a sandbox pull.

**Comment by jeherve** [comment]
@heavyweight This is still happening I'm afraid.

**Comment by heavyweight** [comment]
https://github.com/Automattic/jetpack/assets/7000684/3a20b10b-1881-4615-9e88-9db68a51bcdb

Not sure what I'm doing wrong.
I logged in to the site with email password. The same email from my wp account.
Later I logged in into wordpress.com.
When posting the comment I don't see the error.

**Comment by jeherve** [comment]
I was having trouble reproducing as well; it happens on some of my sites, but not others. I haven't been able to understand why sometimes it works and sometimes it doesn't.

**Comment by danjjohnson** [comment]
A few users affected by this:

8481771-zen
8495110-zen

https://wordpress.org/support/topic/chrome-jetpack-gives-nonce-errors-firefox-jetpack-is-completely-fine/

**Comment by StefMattana** [comment]
Another user reporting it on this forum thread: https://wordpress.org/support/topic/chrome-jetpack-gives-nonce-errors-firefox-jetpack-is-completely-fine/#post-17920955

**Comment by heavyweight** [comment]
The PR got merged https://github.com/Automattic/jetpack/pull/38554
It will be fixed once jetpack is deployed to atomic sites

**Comment by jenhooks** [comment]
@heavyweight - is there any chance that this could still be a problem? I'll refrain from reopening this, but we have a Jetpack user in 8669002-zen reporting this problem, and we're able to reproduce the `Nonce verification failed.` error when trying a test comment on their site.

**Comment by heavyweight** [comment]
After the merged PR I didn't expect to see this again.
I tried to reproduce on my atomic site and couldn't. 
I tried on the customer site and the comment went through. 

<img width="936" alt="Screenshot 2024-09-02 at 14 18 54" src="https://github.com/user-attachments/assets/09433d00-246f-47d2-8ede-143d038cb1a6">

I suspect that this could be an old or cached nonce that got sent.
I see on the ticket that @lschuyler managed to reproduce this. Could you share replication steps?

**Comment by lschuyler** [comment]
I simply loaded the site and attempted to leave a comment on the latest post and got the `Nonce verification failed.` message. I then checked the Jetpack connection, and saw a bit of a sync discrepancy in the Sync Validation. I clicked the Schedule a Fix button. I came back later in the hour to confirm that was fixed. I did a hard refresh of the blog and attempted to comment again, but got the same `Nonce verification failed.` when I tried. I checked the comments page on her dashboard just to see if the comment went through anyway, but it did not. Hope that helps!

**Comment by escapemanuele** [comment]
@heavyweight are you able to give it a test following @lschuyler steps?

**Comment by heavyweight** [comment]
I wasn't able to reproduce this issue unfortunately.

**Comment by lrtottenham** [comment]
@heavyweight are you able to offer some guidance on how to reply to the customer, if we aren't able to reproduce the issue? I tried and was also able to comment on one of their posts.

thanks!

**Comment by heavyweight** [comment]
It's always tricky with issues that we can't reproduce.
I don't have any meaningful ideas on how to follow up on this unfortunately.

We could ask again if the issue persist for the user in question and what authentication method was used for commenting: email or social login.

**Comment by dmsnell** [comment]
On November 17 I experienced what appears to be a similar issue, if not the same issue, as I was unable to post a comment on my own site due to an invalid nonce error.  The comment form showed that I was logged in.

Given that we don’t seem to have any evidence collected for how frequently this impacts Jetpack customers’ ability to leave comments, I’m concerned that we could be overlooking something wider spread.

Would it be possible to recognize these failures inside Jetpack so that we could have some idea of the incidence rate and any apparent patterns?

My mind immediately jumps to long-running sessions as a suspect (without any other evidence) if we’ve been unable to resolve it. This because weird authentication issues can happen once tokens of various kinds expire.

If this is related in any way to old browser sessions, the impact could be hitting hardest on those who are most prolific in engaging in online discussion — or at least those who are trying.

**Comment by lschuyler** [comment]
I've hit this again when trying to leave a comment on an Atomic hosted site. It happened in Chrome and in Firefox, and continued after I logged out of WPCOM and back in again. It happened for the site owner at the same time for the same site.

**Comment by jeherve** [comment]
@lschuyler I wasn't able to reproduce the issue in Firefox when trying to leave a comment via my WordPress.com account. 

Did you get the same error message mentioned in this post, or something more generic? I'm asking because there are currently issues with comments highlighted in https://github.com/Automattic/wp-calypso/issues/99436

Also, did you run into the issue when commenting with an email address, via your WordPress.com account, or via your Facebook account?

**Comment by lschuyler** [comment]
> Also, did you run into the issue when commenting with an email address, via your WordPress.com account, or via your Facebook account?

I was commenting with my WordPress.com account. I got the "Nonce verification failed." error many times in a row, not the "Sorry, this comment cannot be posted" mentioned in the other issue.

It is still happening for me right now - is there any useful troubleshooting information I can grab to help narrow this down?

**Comment by jeherve** [comment]
It may be interesting to save the form data for the 2 comment requests (to `jetpack.wordpress.com/jetpack-comment` and `allmyfriendsarejpegs.com/wp-comments-post.php`) to see if something is off there.

Out of curiosity, you're not currently logged into the site, are you? I don't think you are, but just wanted to be sure.

**Comment by lschuyler** [comment]
> Out of curiosity, you're not currently logged into the site, are you? I don't think you are, but just wanted to be sure.

No, I'm not logged into the site.

**Comment by jeherve** [comment]
Internal reference for more investigation: 9596-gh-jpop-issues
