### ISSUE TITLE
Post Sync should happen whenever any part of a post changes

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#3267]
Posts currently only seem to be synced on the transition_post_status and delete_post actions: https://github.com/Automattic/jetpack/blob/master/class.jetpack-sync.php#L343

This leaves out a number of other ways that a post's data can change. Here is the list of actions we hook into for reindexing posts to Elasticsearch on wp.com:
- transition_post_status
- publish_post
- save_post
- delete_post
- set_object_terms
- add_attachment
- edit_attachment
- delete_attachment
- update_attached_file
- edit_term - resync all posts with that term!

This originally was found while investigating why a user was not able to filter their related posts by a custom taxonomy term. But inspecting the code the problem looks significantly deeper than that and probably also affects Manage.

**Comment by enejb** [comment]
In the new sync implementation we listen to a lot more actions and sync more data but we only send the data that changed. So for example when a term changed. We don't sync all the posts data again but just the term that has changed. Since we would have the up to date post data on .com already. 

I am don't know how the data is stored in elastic search but in theory we should be able to tell elastic search that something is out of data and rebuild the index with the data that we are sending and have stored on .com.

**Comment by gibrown** [comment]
Ya, we may need to adjust our actions on the .com side, but it sounds like the new syncing catches all of these cases.

**Comment by gravityrail** [comment]
This is addressed by new sync. We can open new tickets for specific bugs with new sync if some changes are being missed now.
