### ISSUE TITLE
Carousel: PHP warning when used with the WPML plugin

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#32718]
This was first reported here:
https://wpml.org/errata/jetpack-gutenberg-gallery-images-do-not-open-on-click-zoom-in-jp-carousel/

> If you create a Gutenberg Gallery with the Jetpack plugin, you will see this error on the translation:
> 
> Warning: Invalid argument supplied for foreach() in …/wp-content/plugins/jetpack/modules/carousel/jetpack-carousel.php on line 738

### Workaround

1. Open the wp-content/plugins/jetpack/modules/carousel/jetpack-carousel.php file.
2. Look for line 786.
3. Change: `$attachment_id = absint( $class_id[2] );`
4. with `$attachment_id = apply_filters( 'wpml_object_id', absint( $class_id[2] ), 'attachment' );`

******

We should be able to better handle situations where we receive a non-standard media ID.

**Comment by anomiex** [comment]
The line number in the warning apparently refers to [a version of the file from over a year ago](https://github.com/Automattic/jetpack/blob/ad9dfcb258/projects/plugins/jetpack/modules/carousel/jetpack-carousel.php). There have been several PRs fixing errors in this file since, and in particular #28388 from January 2023 seems likely to have already fixed this.

**Comment by jeherve** [comment]
That's a good point. I wonder if it would still be worth adding the WPML filter in there (most likely via the existing third-party compat file). I'm not sure if that's needed here.

@Partners-OTGS Would you be able to chime in on this one?

Thank you!

**Comment by anomiex** [comment]
I don't know, because I don't know what's going on here. We have no reproduction instructions.

Here's what I see Jetpack doing in the relevant code:

1. Extract all `<img>` tags from the HTML.
2. In each one, find the first string like `wp-image-###` or `data-id=###`. If found, save the `<img>` tag keyed under the `###` which is assumed to be the attachment ID for the image.
3. Fetch the "posts" for those attachment IDs.
4. For each "post" we get back, make sure it's really an image attachment and make sure something didn't give us back an attachment we didn't ask for.
5. Assuming it's good, extract some stuff from the attachment "post" and inject a bunch of data attributes into the corresponding `<img>` tags.

As far as I can tell, the `wpml_object_id` filter is going to map the attachment ID to a different attachment ID in step 2. Presumably WPML also hooks into `get_posts()` to return the mapped attachment "posts" if passed the unmapped IDs, although how that doesn't break a lot of other things I don't know.

**Comment by diiegopereira** [comment]
Hi there, this is Diego from the WPML Compatibility team.

**About the wpml_object_id filter**
This is the documentation about wpml_object_id: https://wpml.org/wpml-hook/wpml_object_id/ - in short, it converts the ID of a post to the corresponding language (it loads the post which is the translation of the original post). If you use it, I recommend setting the third argument ($return_original_if_missing) as TRUE, so it returns the original ID if the translation does not exist.

In the case of media (attachments), this filter is generally used to add compatibility with the WPML Media Translator.

**About the issue**
This issue was originally reported by a user in 2019, and then we had a new report in May 2022. We have had no new reports since then (more than 1 year). As #28388 fixes the same PHP warning we had, I assume the error is already solved.

So IMHO, there is no need to add the wpml_object_id filter directly in the Jetpack code, **but it would be great to have another filter/hook available there**. If needed, then we could use it to hook the wpml_object_id filter in the future without having to modify the Jetpack code.

**Comment by dgwatkins** [comment]
> Presumably WPML also hooks into `get_posts()`

It is worth noting that WPML only hooks into `get_posts()` if you pass the `suppress_filters` argument set to `false` (it is `true` by default). 

`WP_Query` on the other hand, sets the `suppress_filters` default to `false` and needs no adjustments for WPML to run its hooks.

**Comment by jeherve** [comment]
Thanks for jumping in!

> As https://github.com/Automattic/jetpack/pull/28388 fixes the same PHP warning we had, I assume the error is already solved.

👍

> it would be great to have another filter/hook available there

That's definitely something we can do. I created #32749 to do just that.
