### ISSUE TITLE
[Jetpack CRM + WPML] Compatibility issues found in internal testing

### ISSUE THREAD

**Issue by diiegopereira** [Automattic/jetpack#32812]
### Impacted plugin

CRM

### Quick summary

Hi there, this is Diego from the WPML Compatibility team.

Some time ago we did some tests of how Jetpack CRM works with WPML and found some issues. I will add the details in this ticket.

PS: We haven't had any customer reports for these issues yet.

### Steps to reproduce

**Issue 1: Custom field placeholder is not translatable**
* Setup WPML, WCML and WooCommerce
* Set up Jetpack CRM
* Go to Jetpack CRM \> Woo sync \> Finish wizard
* Go to Pages \> All and translate the *Client Portal* page
* Go to Jetpack CRM \> Settings \> Custom Fields
* Go to the bottom,  Address Custom Fields
* Add a new text field and label and placeholder
* Go to ST and search for strings
* Enable the "Look for strings while pages are rendered" option
* Search for label and placeholder
* Label there and translated fine
* The placeholder can not be found

**Issue 2: Quotes are not translatable**
* Setup WPML, WCML and WooCommerce
* Set up Jetpack CRM
* Go to Pages \> All and translate the *Client Portal* page
* Go to Jetpack CRM \> Quotes \> Add new
* Add some content and text
* Go to the Client Portal and switch language (/clients/quotes/)
* Quote content is displayed in the default language

**Issue 3:  Forms are not translatable**
* Setup WPML, WCML, and WC
* Install Jetpack CRM and finish the wizard
* Go to Jetpack CRM \> Forms \> Add New
* Add some content to title and fields and save
* At the bottom, there is a shortcode you can use to add the form to a page
* Create a new page and add code inside the shortcode block
* Translate the page
* Go to WPML ST and check for fields placeholder via "Translate texts in admin screens"
* Try the "Look for strings while pages are rendered" option

**Issue 4: 2nd currency value is applied to order instead of the default currency value**
* Setup WPML, WCML and WooCommerce
* Setup multicurrency. USD is the default currency and 2nd currency is EUR (1:2)
* Set currency to show only per language. ENG/USD and ESP/EUR
* Set up Jetpack CRM
* Go to Jetpack CRM \> Woo sync \> Finish wizard
* Create new product and translate
* Order product in EN/USD
* Order product in ESP/EUR
* Go to Jetpack CRM \> Transactions or via client portal (/clients/transactions/)
* It shows 20 USD for an ESP order, while it should be 10 USD or 20 EUR. It gives wrong calculation/price in general for clients and CRM.

**Issue 5: Mix languages for order status**
* Setup WPML, WCML and WooCommerce
* Set up Jetpack CRM
* Go to Jetpack CRM \> Woo sync \> Finish wizard
* Create new product and translate
* Order product in EN
* Order product in ESP
* Go to Jetpack CRM \> Invoices from admin dashboard or via client portal (/clients/invoices/)
* Says status `sin pagar` it should show status in ENG `unpaid`

### A clear and concise description of what you expected to happen.

- **Issue 1**: Placeholder available for translation
- **Issue 2:** Quote content to be translatable
- **Issue 3:** Forms to be translatable
- **Issue 4:** The correct default currency value is calculated (10USD)
- **Issue 5:** Not showing a mix of languages for order status

### Impact

One

### Available workarounds?

No and the platform is unusable

**Comment by tbradsha** [comment]
Thanks for filing this! I'd not used WPML before, and it's quite the interesting product!

Below are our preliminary findings:

### Issue 1: Placeholder available for translation

Custom field placeholders are user-defined. I do see both sets of strings are picked up when rendering, and can be translated in WPML. That said, translation by normal means (e.g. wrapping variables with WP translation functions) violates WPCS, which is something we try to avoid.

I'm not familiar with the internal mechanisms of WPML and how it handles strings not wrapped for translation. What solutions have other plugins used here?

### Issue 2: Quote content to be translatable

Quote content is intended to be personalised content written for each user. As with issue 1, it's user-defined, and also contains HTML tags, internal placeholders, etc., so this is working as expected.

We do recommend taking a look at quote templates, which would allow you to write up predefined quote text in the language of your choice.

### Issue 3: Forms to be translatable

This is roughly the same issue as the first; we're open to solutions if you have one!

As a workaround, you could do either of the following:

1. Avoid using user-defined placeholders. The default placeholders are translated as expected, as they use hard-coded strings.
2. Create two forms (one for English and one for Spanish).

### Issue 4: 2nd currency value is applied to order instead of the default currency value

We do not support any multi-currency setups at this time.

That said, it's important to avoid tying currency to language (as opposed to location); English speakers might need to pay in Euros, and Spanish speakers might need to pay in USD.

### Issue 5: Not showing a mix of languages for order status

There are some current shortcomings with object statuses and translations, which is partly why we haven't expanded customisable statuses to all objects. We don't have an ETA on a fix for this, but we've noted your report for future reference.

**Comment by diiegopereira** [comment]
Hello @tbradsha, thanks for checking it! :) 

About dynamic strings, or strings that are not wrapped for translation, it depends on how these strings are stored in database.

If these strings are stored in the wp_options table, it would be possible to register these strings for translation using our configuration file (wpml-config.xml): https://wpml.org/documentation/support/language-configuration-files/#admin-texts

If it's just a custom field from a post type, we just need to set the post type as translatable, and then register the fields for translation: https://wpml.org/documentation/support/language-configuration-files/#custom-fields

If that's not possible, we would need to use the wpml_register_single_string and wpml_translate_single_string filters in order to register and then translate the strings. Please check these links for more details:
- https://wpml.org/documentation/support/translation-for-texts-by-other-plugins-and-themes/
- https://wpml.org/wpml-hook/wpml_register_single_string/
- https://wpml.org/wpml-hook/wpml_translate_single_string/

For forms, we recommend to use String Package Translation instead: https://wpml.org/documentation/support/string-package-translation/

**Comment by tbradsha** [comment]
> If these strings are stored in the wp_options table
> If it's just a custom field from a post type

In our case, the strings are in custom tables, so neither of these appear to apply.

> If that's not possible, we would need to use the wpml_register_single_string and wpml_translate_single_string filters in order to register and then translate the strings.

While this isn't something we'd implement directly in our plugin so as to prevent one-off third-party references, this is good for future reference should we have anyone ask about it.

Thanks again for the analysis and details. I'll go ahead and close this issue for now, but do feel free to open a new issue should you need!

**Comment by diiegopereira** [comment]
> While this isn't something we'd implement directly in our plugin so as to prevent one-off third-party references, this is good for future reference should we have anyone ask about it.

In this case, my suggestion would be to add a filter that allows to filter/modify these strings. This would be very useful as we (and other plugins as well) could use this hook to register and translate these strings without implementing it directly in the Jetpack code.

Anyway, these issues were found during internal testing and we haven't had any customer reports about these features yet, so it's nothing urgent.

Thanks! :)
