### ISSUE TITLE
Photon: Add ssl=1 when source image is HTTPS

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#3298]
Photon now will convert HTTPS images by default, as of 3.9. To save the Photon server extra work, we need to add `ssl=1` to the those URLs so Photon will directly request the HTTPS images.

Current behavior has it request the HTTP version, which typically redirects to HTTPS. This not only adds the extra request but may not work depending on server config.

**Comment by janwessling** [comment]
Not sure this is the correct place to write a comment, but I will try anyway. 
Since this update, our users are no longer able to pin the pictures from our blog. (without Photon is works). We do not have a valid SSL certificate, and all our posts and pages are served over http, but the ssl=1 is still added to the query string. All our urls are http in the settings dialogue, and we use a https plug-in to tell wordpress to serve every post over http. Is this a bug?

**Comment by janwessling** [comment]
the blog in question is www.littlehouseonthecorner.com, but Photon is turned off at the moment. Happy to turn it back on if you want to see the results.

**Comment by jeherve** [comment]
@janwessling Your issue is probably not related to this GitHub issue.

Could you contact us via [this contact form](http://jetpack.com/contact-support/), and give us as much information as possible about your setup, and the errors you're experiencing?

Thanks!
