### ISSUE TITLE
Shortlinks: make plugin available in editor, even when the module is not active yet

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#33164]
See Primary issue: #32401

**Comment by andrii-lysenko** [comment]
Ok, so this one seems a bit tricky. This is a very simple module, that generates `shortlink` on request. As with previous blocks, we have a problem with Post types, basically, we need to register an API endpoint alongside Frontend part, so that it will work after module is activated. The problem is making this endpoint functioning will simply mean keeping this module always active. I think we should put this one to `Blocked` and try to find a solution so we can keep Frontend element separate from Post Types, in the same time have them reactive. @jeherve what do you think?

**Comment by jeherve** [comment]
That's a good point. Given that shortlinks are not a popular module anymore, and not one that's really of much use to most people nowadays, I'd be tempted to close this as won't fix.

We'll still need to address that question for other, more popular modules though.
