### ISSUE TITLE
Subscriptions Block: custom rounded borders and compact settings interacts poorly.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/jetpack#33198]
### Impacted plugin

Jetpack

### Quick summary

The input textarea and the subscribe button doe not interact well if the compact + custom rounded border is selected.

Version: Version 12.6-6240849897-g0eae74ad

<img width="1251" alt="Screenshot 2023-09-19 at 5 06 58 PM" src="https://github.com/Automattic/jetpack/assets/6549265/970f5472-e956-4dca-873a-77a8f9930236">

### Steps to reproduce

1. start a new post.
2. insert a Subscriptions block.
3. open the editor settings pane.
4. select the Block tab.
5. expand the Border pane and set it to some value.
6. click on the Style sub-tab.
7. click on the Compact style.

### A clear and concise description of what you expected to happen.

The right hand side of the textarea and the left hand side of the button remain rounded.

### What actually happened

The right hand side of the textarea and the left hand side of the button get squared off.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by monsieur-z** [comment]
Here's what I'm seeing:

_Compact_ style
<img width="500" alt="Screenshot 2024-05-08 at 3 42 06 PM" src="https://github.com/Automattic/jetpack/assets/1620183/3f8c0078-61bf-41f2-a73f-09b91729be9d">

_Split_ style
<img width="500" alt="Screenshot 2024-05-08 at 3 42 09 PM" src="https://github.com/Automattic/jetpack/assets/1620183/ee37f6aa-8e08-44ab-b1eb-94d6b66e122e">

It seems there's some unexpected wrapping in the description screenshot, which I haven't been able to see at any viewport width. I reckon it might be why the issue was originally created. The current behaviour seems on point to me. I disagree with the following statement:

> **A clear and concise description of what you expected to happen.**
> The right hand side of the textarea and the left hand side of the button remain rounded.

This should be handled by the _Split_ style.

Closing, but feel free to reopen with more details if I got something wrong.
