### ISSUE TITLE
No "search terms" data available despite site having search referrals

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/jetpack#33273]
### Impacted plugin

Jetpack

### Quick summary

A customer's stats don't display any "search terms" data despite the site having search referral traffic to the site. When clicking to see details of search terms used to reach the site in the site's Stats page, we see no search terms:

![CleanShot 2023-09-24 at 12 25 21@2x](https://github.com/Automattic/jetpack/assets/2912202/1e17d956-da19-42e8-b57f-5b68c904d349)

This is despite the site having search referrals:

![CleanShot 2023-09-24 at 12 25 02@2x](https://github.com/Automattic/jetpack/assets/2912202/2337156f-2bfb-4ddd-a956-f68ee651ac61)

### Steps to reproduce

1. Open the Stats page in the site dashboard
2. Click on **View details** in the "Search terms" panel, here:

![CleanShot 2023-09-24 at 12 26 50@2x](https://github.com/Automattic/jetpack/assets/2912202/14c30c86-c25a-46eb-9090-d79e949379af)

### A clear and concise description of what you expected to happen.

I'd expect to see a list of search terms that were used to locate the site by the visitors directed to the site through search engines.

### What actually happened

There are no search terms data.

I'm curious what could result in there being no "search terms" or, put another way, under which conditions there _would_ be search terms.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

The customer's report is in 6767085-zen

The customer's site has both Rank Math SEO and Yoast SEO installed on the site. Yoast seems to be managing the site's SEO settings, currently.

I have also asked the user if they see search terms data in their linked Google Analytics dashboard?

**Comment by jeherve** [comment]
I'm afraid that's expected. Although some of their traffic comes from search engines, the search terms are not made available to the site because search engines do not pass that information by default. You may still see some terms sometimes, but mostly only when the search is made through HTTP instead of HTTPS.

Search terms are generally a lot less available nowadays; they are sometimes available in Google Search Console or in other Google services such as Google Ads, but they're not often passed along with referral info in general stats.

**Comment by pauljacobson** [comment]
Thank you for clarifying this @jeherve
