### ISSUE TITLE
Stats: Views log in stats while checking Facebook

### ISSUE THREAD

**Issue by Robertght** [Automattic/jetpack#33460]
### Impacted plugin

Jetpack

### Quick summary

If the user goes to their FB page and brings any shared post in their viewport (not clicking though), the WordPress.com stats counts it as view on that post.

### Steps to reproduce

As we're unable to replicate this in detail, I'll add the user's video recording here

https://videopress.com/v/7La3MEBy

### A clear and concise description of what you expected to happen.

Visiting Facebook should not increase the views stats.

### What actually happened

The views stats increasesd.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Asked in Slack: p1696326645526799-slack-C04UE0ANHDY

Another report from @pauloeaquino: p1696381285254679/1695999379.202639-slack-C0334JNQD

7080160-zen

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
So far, I haven't been able to replicate this.  I connected both an Atomic and Simple site to a Facebook Page, published posts on both sites to that page, and then viewed the Facebook Page in multiple browsers; I also tried vieweing the FB Page from multiple logged in FB accounts. 

The only views registered on my test sites > Stats page so far are the homepage and any posts I viewed in my actual browser. 

I can check back in on this in a little bit to see if those stats take a little time to appear 🤔 . That said, it's pretty clear from the multiple videos provided that this is happening in some cases.

📌 ACTIONS
- Triaged

**Comment by kangzj** [comment]
Hi @Robertght  @cuemarie,

Thanks for reporting.

I inspected their Facebook page, and I don't see any tracking requests sent to us. I believe the reason behind this is that, FB generate those good-looking cover pic and nice excerpt by actually accessing the page from their back end, which in turn bumped the Stats.

But I think FB would maintain a snapshot at their side, meaning, the stats wouldn't be bumped every time the FB page is accessed. Could we ask user to confirm, whether scrolling down the FB page for later wouldn't bump the stats any longer or not?

Either way tho, I think this is expected, because FB actually accessed those pages behind the scene if that makes sense.

**Comment by jeherve** [comment]
> FB actually accessed those pages behind the scene 

Shouldn't we be able to exclude those visits from stats, since they were not triggered by human visits, but by a bot? As a site owner I wouldn't expect such visits to be included in my stats.

**Comment by sudeepbaral** [comment]
>Could we ask user to confirm, whether scrolling down the FB page for later wouldn't bump the stats any longer or not?

This is what the user shared when I asked them about it:

> It doesn't happen every time. 
> 
> My wife visited the FB page three times. The first time worked like on the video, then one hour later she repeated the same process but the count didn't go up as much as the first time, and then one hour later she did the third try and that time the view count on her Wordpress stats didn't go up at all even though she scrolled through the same posts on her Facebook page.

@kangzj 

User would like to be notified when this gets resolved.

**Comment by pauloeaquino** [comment]
I can still replicate the issue consistently on my own personal blog (see Slack details mentioned in p1696381285254679/1695999379.202639-slack-C0334JNQD ) . Tested on Atomic. For added context, the countries that are registering hits seem to be oddly consistent too: United States, Ireland, Sweden

**Comment by kangzj** [comment]
Hi all, We’ll take a look during the next couple of weeks, because  this doesn’t look like an urgent issue. We probably just exclude the bot traffic, but we need to find the pattern or up ranges first. Will keep you folks updated. In the meantime, could we please let the user know we are working on this. Thanks folks 👍

**Comment by kangzj** [comment]
The fix will land on wpcom in ~1 day, so we could ask user to test whether this fixes it by then. Thanks folks. @sudeepbaral @pauloeaquino
