### ISSUE TITLE
Akismet reports "Sorry, you are not allowed to access this page" during setup with bundle plan on Jetpack 12.6+

### ISSUE THREAD

**Issue by bluefuton** [Automattic/jetpack#33550]
### Impacted plugin

Jetpack

### Quick summary

@foleynotrose noticed an influx of tickets from users purchasing Jetpack bundles (e.g. Security, Complete) who are unable to activate Akismet - see pZbK5-7Ja-p2.

When attempting to reach the Akismet config page (/wp-admin/admin.php?page=akismet-key-config), they see the following:

<img width="848" alt="Screenshot 2023-10-11 at 14 16 20" src="https://github.com/Automattic/jetpack/assets/17325/5aa7aebf-331f-473c-b155-ea5f42ccec6c">

On further investigation, it looks like this behavior started with Jetpack v12.6, and Jetpack v12.5 works as expected.

### Steps to reproduce

1. Create a new Jetpack test site (with jurassic.ninja or similar).
2. Connect Jetpack and purchase a bundled plan, like Security or Complete.
3. Visit My Jetpack and click 'Activate' on the Akismet card.
4. When the page refreshes, click 'Manage' on the Akismet card.

<img width="384" alt="Screenshot 2023-10-11 at 14 18 24" src="https://github.com/Automattic/jetpack/assets/17325/93a96529-e4fd-477b-b438-45d0134b7237">

If you're on Jetpack v12.6+, you should see the "Sorry, you are not allowed to access this page." error.

### A clear and concise description of what you expected to happen.

After purchasing a Jetpack bundle, I should be able to visit the Akismet config page to set it up.

### What actually happened

After purchasing a Jetpack bundle while running JP v12.6.2, I am not able to visit the Akismet config page and see the message "Sorry, you are not allowed to access this page."

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by bluefuton** [comment]
I think the cause might be https://github.com/Automattic/jetpack/pull/32911 (cc @kraftbj). [Reverting it](https://github.com/Automattic/jetpack/pull/33551) seems to do the trick.

**Comment by foleynotrose** [comment]
Another report: 7144956-zd-a8c

**Comment by anomiex** [comment]
It looks like https://github.com/Automattic/jetpack/pull/32911 didn't entirely understand what was happening.

If you have Akismet, Jetpack Backups, and Jetpack all active, the Admin_Menu class gets initialized by Jetpack Backups before Jetpack is loaded, so [the `! class_exists( 'Jetpack' )` check in Admin_Menu](https://github.com/Automattic/jetpack/blob/7a0dcc49eab6477f301d105a1e5ceb468798263f/projects/packages/admin-ui/src/class-admin-menu.php#L52) passes and the Akismet page is registered.

Prior to #32911, when Jetpack did get loaded then it added its own copy of the menu item, causing the duplicate menu entries noted by #32893. After #32911, it just tries to re-init Admin_Menu which does nothing, apparently fixing the bug.

The problem comes when Jetpack itself is the first to initialize the Admin_Menu class, which unfortunately wasn't tested during #32911. In that case the `! class_exists( 'Jetpack' )` check stops Admin_Menu from adding a menu for Akismet, and since Jetpack no longer adds it either, it never gets registered and so we get this error.

So one fix might be to remove that `! class_exists( 'Jetpack' )` check, letting Admin_Menu register things for Jetpack too. Alternatively, in addition to reverting #32911 we should also add something similar to [this bit](https://github.com/Automattic/jetpack/blob/7a0dcc49eab6477f301d105a1e5ceb468798263f/projects/plugins/jetpack/class.jetpack-admin.php#L86-L93) to additionally remove the menu item added by Admin_Menu to avoid re-opening https://github.com/Automattic/jetpack/issues/32893.

**Comment by anomiex** [comment]
Looks like the decision was that, since 12.7 is so close to release (it was supposed to be yesterday, but was delayed until tomorrow due to other bugs), we'll do the following:

* Revert #32911 for 12.7, which may cause duplicate "Anti-Spam" items in the sidebar menu for sites with Jetpack and standalone plugins (e.g. Jetpack Backup) and Jetpack plans that include Akismet.
* For 12.8, restore #32911 and merge #33559 to fix both issues.

p1697032616912459/1697028510.290769-slack-C01U2KGS2PQ

**Comment by bluefuton** [comment]
The revert (https://github.com/Automattic/jetpack/pull/33551) has been released as part of Jetpack 12.7. This fixes the issue.

@anomiex shall I leave this open until we've done the followup 12.8 bits you [mention above](https://github.com/Automattic/jetpack/issues/33550#issuecomment-1757967011)?

**Comment by anomiex** [comment]
Yeah, probably.
