### ISSUE TITLE
Block Performance tests: broken since August 18

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#33626]
We track the impact of Jetpack on the block editor's peformance by running tests every 12 hours:

https://github.com/Automattic/jetpack/blob/94cb7246636e7056ce30ab2a46116d1afccebd5f/.github/workflows/block-performance.yml
https://github.com/Automattic/jetpack/actions/workflows/block-performance.yml

Unfortunately, those tests broke on August 18, following changes in Gutenberg:
https://github.com/WordPress/gutenberg/pull/53768/

We would need to update our tests accordingly.

Previous art on this: #30128

**Comment by jeherve** [comment]
@WunderBart Can I bug you about this? I'm not sure I understand the new test structure now, and where I should go look for the tests' output files.

Thank you!

**Comment by WunderBart** [comment]
👋 Thanks for the ping, @jeherve.

>  I'm not sure I understand the new test structure now, and where I should go look for the tests' output files.

Every test migrated to Playwright is removed from the `e2e-tests` package until [the migration](https://github.com/WordPress/gutenberg/issues/38851) is complete. The migrated e2e tests are saved to the [`/test/e2e/`](https://github.com/WordPress/gutenberg/tree/trunk/test/e2e) folder, and performance ones to [`/test/performance/`](https://github.com/WordPress/gutenberg/tree/trunk/test/performance). The good thing about Playwright Test Runner is that we don't need to know the exact location of the test, so updating [the current command](https://github.com/Automattic/jetpack/blob/94cb7246636e7056ce30ab2a46116d1afccebd5f/tools/e2e-commons/bin/performance.js#L32) to `npm run test:performance -- post-editor` should do the trick.

Additionally, instead of [moving the results](https://github.com/Automattic/jetpack/blob/94cb7246636e7056ce30ab2a46116d1afccebd5f/tools/e2e-commons/bin/performance.js#L37), you can define the [`WP_ARTIFACTS_PATH`](https://github.com/WordPress/gutenberg/blob/46603dc7ec3846a53ae2b8b642f9c7bdf0970271/.github/workflows/performance.yml#L32) env variable (`/artifacts` [by default](https://github.com/WordPress/gutenberg/blob/46603dc7ec3846a53ae2b8b642f9c7bdf0970271/packages/scripts/config/playwright.config.js#L8)), which should point to the folder where the results JSON will be saved. I also don't think that folder needs to be [explicitly created](https://github.com/Automattic/jetpack/blob/94cb7246636e7056ce30ab2a46116d1afccebd5f/tools/e2e-commons/bin/performance.js#L31).

I hope it helps! 🙌
