### ISSUE TITLE
JetPack Subscriptions Widget disappears when JETPACK_DEV_DEBUG mode is on

### ISSUE THREAD

**Issue by jb510** [Automattic/jetpack#3380]
Just noticed that the widget I'm trying to re-style disappears when JETPACK_DEV_DEBUG mode is turned on.  That makes it hard to work with.  Isn't there a way these widgets could continue to display in non-functional form with JETPACK_DEV_DEBUG was enabled?

I suspect it's not just that widget, but that's the one I'm looking at that is disappearing without reason.

**Comment by kraftbj** [comment]
That's intentional, as `JETPACK_DEV_DEBUG` enables only features of Jetpack that can function without a connection to WordPress.com.

We're in the process of [fleshing out a "staging mode"](https://github.com/Automattic/jetpack/blob/fe964d0da38b8f679628d6b6d0378c6db8d6e74f/class.jetpack.php#L6017) that would bridge that gap a bit (a site, more or less, functions as a connected site without actually communicating with WordPress.com).

**Comment by jb510** [comment]
I know this is closed... but this has long been a great frustration.  We, developers, _need_ front end elements to show up in dev mode whether they are fully functional or not.  Outright hiding things just confuses and frustrates people.

**Comment by kraftbj** [comment]
@jb510 Agreed. We haven't touched it in awhile, but tracking this in #385.
