### ISSUE TITLE
VideoPress: Private videos showing as ‘loading’ then timed out with error

### ISSUE THREAD

**Issue by CGastrell** [Automattic/jetpack#33975]
Forum entry: https://wordpress.org/support/topic/private-videos-showing-as-loading-then-timed-out-with-error/

**Comment by tiniacoleyba** [comment]
I found a strange behavior that seems buggy and might be related to video privacy configurations. [I documented it on this issue](https://github.com/Automattic/wp-calypso/issues/84141), and I am commenting since I think the bugs could be associated. In summary, some videos marked as private on the Calypso media tab are still playable for logged-out users on an automatically created page on {yoursite}.com/{video-file-name}-mp4 but once you install the VideoPress plugin (not installed by default), the videos are not playable anymore on those pages (as they should be).
