### ISSUE TITLE
Sharing block: enhance block view

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#34116]
Improve the display of the sharing buttons added via the block.

Here is a quick video about the current implementation, and potential directions:

https://github.com/Automattic/jetpack/assets/426388/b597b909-5833-4b32-87af-8df17f9f561f

If we were to go in the direction of the existing Core Social Icons block, we could have a parent block where we would define style (icon only, icon+text, text), and then child blocks for each one of the sharing buttons the site owner wishes the enable on their site.

********

<img width="1206" alt="image" src="https://github.com/Automattic/jetpack/assets/426388/14449af8-31ae-4857-adaa-383233e21f86">

<img width="953" alt="Screenshot 2023-11-14 at 18 14 05" src="https://github.com/Automattic/jetpack/assets/426388/02ddbdb2-d456-497e-a55c-e65f274a0da6">
<img width="637" alt="Screenshot 2023-11-14 at 18 13 47" src="https://github.com/Automattic/jetpack/assets/426388/80b314bc-3aa2-4335-81ec-89c67ceaa3ae">

*******

Epic: #19694

**Comment by chrisbliss18** [comment]
Could you contact the Design team and ask for feedback on how they see improving the design and interaction?

**Comment by andrii-lysenko** [comment]
I was thinking to utilize the current approach from calypso, where we can add/remove and drag'n'drop items for the order, but in a bit more compact way.
But I could definitely check with Design team.

![Image](https://github.com/Automattic/jetpack/assets/60262784/520bd81f-5f40-417f-858c-a3fffe8e493a)

**Comment by keoshi** [comment]
> If we were to go in the direction of the existing Core Social Icons block

Essentially this. I'd strongly suggest we follow the same pattern and reuse the additive logic that people are used to by now with the Social Icons block.

The UX of the Social Icons block is slightly flawed right now if you want to add a few networks at once though. In this scenario, it keeps selecting the latest added child component, making you click on the parent block over and over to add new networks. But that's also how blocks work, so hopefully it's a friction that users only feel once when they're initially setting up the block.

This model also has a huge advantage over showing all networks regardless of active/inactive state, since it follows the WYSIWYG model of Gutenberg. There's no room for ambiguity so if you see certain buttons in the editor, it means they'll also be visible in the site.

**Comment by andrii-lysenko** [comment]
@keoshi Thanks for the comment. Will go this way then.

**Comment by andrii-lysenko** [comment]
> This model also has a huge advantage over showing all networks regardless of active/inactive state, since it follows the WYSIWYG model of Gutenberg. There's no room for ambiguity so if you see certain buttons in the editor, it means they'll also be visible in the site.

As a side note, in the Core Block we are able to add social icons in edit, but, if URL is not specified for them, they won't show up causing ambiguity. However, in our case it shouldn't be the problem.
