### ISSUE TITLE
Boost: Concatenate JS/CSS is skipping some files

### ISSUE THREAD

**Issue by haqadn** [Automattic/jetpack#34201]
### Impacted plugin

Boost

### Quick summary

Concatenation is not minifying parts of the files and leaving some CSS/JS comments in the files. See screenshots:

<details>
<summary>See screenshots</summary>
<img src="https://github.com/Automattic/jetpack/assets/3737780/b7f4d595-7d7d-4814-ac93-21423a57b319">
<img src="https://github.com/Automattic/jetpack/assets/3737780/148c2f82-3239-448b-93c2-fc7fcb04dbf5">
<img src="https://github.com/Automattic/jetpack/assets/3737780/6662be86-66ce-497e-8851-0c23fc10c8ed">
<img src="https://github.com/Automattic/jetpack/assets/3737780/f24cd457-51e7-43e5-a7d0-ac54fb886bad">
</details>

### Steps to reproduce

1. Create a new site with Boost.
2. Enable concatenate JS and CSS.
3. Notice that the script with `[data-handles="hoverintent-js,admin-bar"]` has comments left in it.

See screenshot for more possibilities.

### A clear and concise description of what you expected to happen.

The files should be fully minified with no comments in the minified code.

### What actually happened

Parts of the concatenated files aren't minified and contain comments.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic, Self-hosted

### Logs or notes

Support thread this was discovered through: https://wordpress.org/support/topic/jetpack-and-js-and-css-minification/#post-17214305

**Comment by Purrington1949** [comment]
Please notify me when this issue is resolved.

Thank you

**Comment by Purrington1949** [comment]
it has been over two months since this problem was found but it does not yet seem to have been repaired.

would somebody kindly post what the status of this is.

thank yu

**Comment by thingalon** [comment]
Hi @Purrington1949. There is a fix in the pipeline for this issue, I expect it will be in the next Boost release.

**Comment by Purrington1949** [comment]
It is good that there is a fix in the pipeline.

When might the next Boost release be expected to go into effect with the fix in place.

It has now been over 2 months since the issue was reported.

Thank you.

**Comment by thingalon** [comment]
The next Boost release is currently scheduled for late Feb; in a few weeks' time. I'm happy to notify you when it goes out.

In the meantime if you would like to test the fix out on a test site, the Jetpack Beta plugin allows you to install pre-release / bleeding edge versions of Jetpack plugins like Boost: https://jetpack.com/download-jetpack-beta/

However, as this allows you to install software that has not undergone our internal testing process, we do not recommend it for production websites.

**Comment by Purrington1949** [comment]
I appreciate your update. Do please let me know once the next Boost release goes into effect.

I hope this thread remains open until the issue is fullly resolved.

thank you.

**Comment by Purrington1949** [comment]
It has been weeks since this issue first reared its ugly head.
Has this been repaired yet.  If not when will it be repaired.
Thank you.
    On Wednesday, February 7, 2024 at 11:45:49 PM EST, thingalon ***@***.***> wrote:  
 
 


The next Boost release is currently scheduled for late Feb; in a few weeks' time. I'm happy to notify you when it goes out.

In the meantime if you would like to test the fix out on a test site, the Jetpack Beta plugin allows you to install pre-release / bleeding edge versions of Jetpack plugins like Boost: https://jetpack.com/download-jetpack-beta/

However, as this allows you to install software that has not undergone our internal testing process, we do not recommend it for production websites.

**Comment by thingalon** [comment]
Hi @Purrington1949

I have some good news for you. Jetpack Boost 3.1.1 (released within the past couple of days) now includes the CSS/JS minification fix.

You should now find that your CSS and JS are properly minified.

**Comment by Purrington1949** [comment]
Thank you so much.

**Comment by Purrington1949** [comment]
Oops, I just checked my WordPress site and it appears the issue remains.  See image attached.
Could you kindly investigate this.
Thank you
    On Tuesday, March 12, 2024 at 07:56:30 PM EDT, thingalon ***@***.***> wrote:  
 
 


Hi @Purrington1949

I have some good news for you. Jetpack Boost 3.1.1 (released within the past couple of days) now includes the CSS/JS minification fix.

You should now find that your CSS and JS are properly minified.

**Comment by thingalon** [comment]
Hi again @Purrington1949.

I'm afraid that your image did not come through. It looks like you're replying to this GitHub thread via email. Can I recommend visiting the thread directly at https://github.com/Automattic/jetpack/issues/34201 to post your reply. But please bear in mind that any images you post here will be publicly visible, so don't include any sensitive information.

I see that this GitHub ticket was created in response to a WordPress.org Support Forum thread here: https://wordpress.org/support/topic/jetpack-and-js-and-css-minification/#post-17214305

I've examined the CSS and JavaScript being served on the site mentioned in the original Forum thread, and it appears to be minified when I view it. Here is a sample:

![image](https://github.com/Automattic/jetpack/assets/1369626/3ec6536e-a779-413b-aa7d-688981ddaf7e)

I do still see there are comments in there which begin with `/*!` at the beginning, but it is common practise to keep comments with that marker on them when minifying content, as they often denote important meta-information or licensing information that is not allowed to be stripped.

**Comment by Purrington1949** [comment]
The original issue 'Boost: Concatenate JS/CSS is skipping some files' does not appear to be resolved.

![minify](https://github.com/Automattic/jetpack/assets/151528519/c71d3d6e-acec-4777-a029-4296478e9c41)

Kindly open up this thread until the issue is repaired.

Thank you.

**Comment by thingalon** [comment]
Hi again @Purrington1949.

I have inspected the two Boost URLs you included in your screenshot:

The [CSS URL](https://carljungdepthpsychologysite.blog/_jb_static/??-eJydks9SAyEMxt/GkxS3HnrqeOmMD+ATsBC3tECYTXDdtzd0W22r/TPeEsjvy0fCkJXFxJBY51A6n0gHM2Jh1fXeaeIxwMwSPQ5Z+WRDcUB6QzqC8wYCxEoeJ1lw6FWAzthxFn26ScvdcX7MnFuz2Aa0W9LOE0/m1OFMNf+i4FNqyWOif+Em+WhY8HM6FnUQGLLFSGv9Aclhr01hFIa91Szdp8erwbsOWO3kpScJNp3Uml8zrPc7O6KcMUlD2u/qnul9y6wgiydI1kvyiivj3KjfJgtt8cHJZ2AgvqS4Ac7GbnVEVyoT/Bbo9NMcEF7Ldkn3OASfOv0ux8oMQBjhJLnB/al9yQ6Vlmzvc93PWXavxLSEOjJi0/Um/kR3S2DvjJt2dtW+TF8xypcaa8gowbV1HvpU3X1cS1/islk0T/NFM2+eH2y7bL4Ah59+eQ==) looks like this:

![image](https://github.com/Automattic/jetpack/assets/1369626/c12868d4-ce63-4214-8b07-2b94f9e5c7da)

The [JS URL](https://carljungdepthpsychologysite.blog/_jb_static/??-eJyVzc0KwjAMB/C38WRXhh9sh+Gz1DbOzjapaerY21thh51EIZA/5JdkTsqjDcVB1lOtZwFe1qaiH9kINNFjM+X9nJQlFEDRKZTRY9bGOSWkDC6fKFTDRm8vO59FvwAdsa6jRGG5+RCqAZYfdhhGqNQIseKC4iP89+mbvhM98goucWjPfXfoTseu39nr0L4BlB9skA==) looks like this:

![image](https://github.com/Automattic/jetpack/assets/1369626/8879c10d-2558-42d2-aa4f-c43ee3220b5c)

I cannot see anything at either URL which does not look appropriately minified. Can you please look at these two URLs and let me know if you see anything that is not minified as it should be?

I cannot comment on why SEO Analyzer is returning this result, as what I see at both URLs looks minified.

**Comment by Purrington1949** [comment]
I am sorry but I do not possess the competence to read the URL’s which you
have kindly provided.



This issue originally arose around 4 months ago on the SEO Analyzer.



Being a novice in such matters, I reported the issue to the wizards at
WordPress Support.



It was WordPress Support, not I, who acknowledged a legitimate problem and
ultimately referred the issue to ‘Boost.’


I do not know the specifics on how WP Support made this determination but
insofar as the SEO Analyzer still indicated a failure related to
minification it does not yet to be resolved.



I am not certain where to go from here.



Thank you

**Comment by alinclamba** [comment]
Hi @Purrington1949,

Thanks for hanging in there with us on this. I totally get how diving into URLs and tech jargon can feel like decoding alien script, especially when you’re just starting to get your feet wet with all this SEO and minification stuff.

After giving those URLs a good look-over, as previously mentioned, everything on our end seems to be minified just right, which should be what SEO Analyzer is looking for. But hey, I understand that this might not be your cup of tea to sift through, and that’s perfectly okay.

So, here’s what we can do next:

1. **Touch base with SEO Analyzer Support**: It seems the ball might be in their court to clarify why they’re flagging an issue. If you’re using their free service, maybe dropping a question in[ their public forum](https://wordpress.org/support/plugin/all-in-one-seo-pack/) could shed some light. Got a paid plan? Reaching out to [their support directly](https://aioseo.com/contact/) might get you some quicker, tailored advice.

2. **Need a hand drafting your message?** If you’re not sure how to kick off that conversation or what to include, we’ve got your back. We can help draft that message or offer some pointers on what to mention, especially highlighting that everything looks minified from here.

We know it feels like you’re being ping-ponged around, and we really want to cut through that frustration for you.

I hope this helps.

**Comment by Purrington1949** [comment]
Thank you for your gracious response.

I will get back to you this weekend.

-Lewis

**Comment by Purrington1949** [comment]
Ido not even know what ‘minification’ is. I am only aware of it because it appearedas an error on the SEO analyzer.

I donot know how to read the URL’s anymore than I can read my physician’s most recentMRI results.


ButI do possess the humility to confess my ignorance and to seek advice from thosemore capable than myself. I am more of a Dunkin Coffee boy than a Tetley Teaboy.


I haveRank Math ‘PRO Plan.’ At this point my blood pressure shall rise.


Byin large they are unresponsive and I am a tad surprised that WordPress is affiliatedwith them.

Originally,I did contact RM support. They were unhelpful though quite adept at wordsophistry and linguistic acrobatics which is what led me to WordPress Supportand ultimately to you.


WordPressSupport has always helped me and on more than one occasion helped me solve a RankMathissue.


Formonths the SEO Analyzer has shown a Page Object error and after months of askingRM Support for instructions how to ‘fix’ it, I gave up asking.


Next,I asked RM support for help fixing all the ‘Orphan Posts’ they were showing. Theygave no help.


So,I asked WP Support for help.  WPS offeredthe opinion that the RM method of diagnosing their ‘Orphan Posts’ waserroneously helped me set up the means for redirecting the ‘Orphan Posts.’ WPS dida great job.


Itold RMS that WPS helped me resolve this issue.


Theirresponse you wonder?  Miguel at RMaccused WPS of not engaging in ‘good practices’ and he was endorsed in this byhis colleague Jeremy.


Thiswas stunning. WPS helped the customer and RM. WPS never asserts they areall-knowing but WPS is not immoral or unethical.


Doyou know that the Rank Math Plugin is broken. Their ‘re-indexing’ feature doesnot work properly. It erroneously reset thousands of my SEO post scores lowernot once but twice.


I havebeen in the process of manually resetting my SEO scores taking several hundredhours with around 1000 more posts to fix.


Ittook some doing to get RM to admit their plugin is broken.  I am doubtful that they are making eithercurrent or potential customers aware of this.


Theplugin has been broken for weeks now but the only RM reply is firstly verbalcircumambulation of the issue followed by avoidance and more recentlydismissiveness.


Isuggested to RM that WPS be contacted to assist in repairing their plugin butthey simply refused.


Happily,I possess the chat transcripts to prove this. I am doubtful this plugin will berepaired anytime soon which has damaged my SEO score and my income from AdSense.


Inany event, I share this will you so you will know that I have contacted RM SEOsupport on this issue and others and what the likelihood of substantive assistancefrom them is likely to be.


Thatsaid your support in drafting a message will be of enormous assistance forwhich I will be most grateful.


Iwill keep you updated on the results.


Ifyou wish, I would be happy to give to temporary access to my site in the eventyou wish to investigate any of the issues mentioned above.


Thankyou and best regards,

Lewis
 

 

 

 

 

Needa hand drafting your message? If you’re not sure how to kick off thatconversation or what to include, we’ve got your back. We can help draft thatmessage or offer some pointers on what to mention, especially highlighting thateverything looks minified from here.

 

Weknow it feels like you’re being ping-ponged around, and we really want to cutthrough that frustration for you.

 

Ihope this helps.


    On Sunday, March 17, 2024 at 10:38:39 PM EDT, thingalon ***@***.***> wrote:  
 
 


Hi again @Purrington1949.

I have inspected the two Boost URLs you included in your screenshot:

The CSS URL looks like this:

image.png (view on web)

The JS URL looks like this:

image.png (view on web)

I cannot see anything at either URL which does not look appropriate minified. Can you please look at these two URLs and let me know if you see anything that is not minified as it should be?

I cannot comment on why SEO Analyzer is returning this result, as what I see at both URLs looks minified.

**Comment by alinclamba** [comment]
Hey Lewis,

Thank you so much for your detailed message and for sharing your experience with us. It really helps us understand the full picture of what you’ve been going through with the SEO tool issues. Your Dunkin Coffee boy analogy definitely keeps things in perspective, and it’s clear you’ve been navigating a challenging situation with grace and patience.

From our side at Jetpack, after thoroughly reviewing the information you provided and the technical aspects on our end, we’re confident that the issue lies outside of our scope, specifically with the SEO Analyzer tool you're using. While we strive to support our users as comprehensively as possible, our ability to intervene directly with third-party tools, like the SEO Analyzer, is limited.

However, we're not just going to leave you hanging. To help move things forward with the Rank Math team, here’s a draft message you can use or modify to contact their support. This message aims to clearly articulate the issues you’ve encountered, emphasizing the need for their direct assistance:

>  I am reaching out for urgent support regarding ongoing issues with the SEO Analyzer tool, specifically related to minification errors and the malfunctioning of the re-indexing feature. These problems have persistently impacted my website's SEO performance and, consequently, my AdSense revenue.
> 
> After a thorough review and dialogue with Jetpack support, it has been conclusively determined that the issues are not originating from Jetpack's services. This has led us to understand that the resolution needs to come from adjustments or fixes to the Rank Math SEO Analyzer tool.
> 
> The specific issues I am facing are as follows:
> 
> 1. Minification Errors: Despite Jetpack confirming that the resources (CSS/JS files) on my site are correctly minified, the SEO Analyzer continues to flag these as errors. This discrepancy has left me at a standstill, unable to progress in optimizing my site’s SEO performance.
> 2. Re-indexing Feature Malfunction: The re-indexing feature within the Rank Math plugin has erroneously reset thousands of my SEO post scores to lower values, not once but twice. This has necessitated several hundred hours of manual correction, with approximately 1000 more posts to address.
>
> The direct impact of these issues on my site's performance and my livelihood compels me to seek your immediate and focused assistance. A detailed examination and prompt resolution of these specific problems from your team would be greatly appreciated.

After providing you with this draft, it’s important to note that we've reached a juncture where, unfortunately, our ability to assist further is limited since the issue originates beyond our services. We’re confident, however, that by bringing this matter directly to Rank Math's attention with the specifics outlined, you're taking a positive step towards resolving these challenges. We sincerely hope this draft facilitates a productive conversation with Rank Math and leads to a swift resolution for you.

Best of luck!

**Comment by Purrington1949** [comment]
Anit-
I greatly appreciate your reply.
I did as you suggested and sent the draft of your letter to RankMath.
I received a reply which I will provide a copy of below and attached you will find a minification image sent to me.
In essence, 'Great' at RankMath tells me that JetPack is wrong and told me to check with you again.
Great- 'Based on your previous ticket, I assume the website you’re having issues with is carljungdepthpsychologysite.blog. I ran a test on your website using the public version of the SEO Analyzer tool, and the results also flagged some files as not minified. You may want to share this information with the Jetpark team again.
Regarding the SEO Analyzer Great basically tells me that if I disagree with the SEO results I can just 'ignore' them.
'Regarding your query about the SEO Analyzer results, if you have already cleared the data from Rank Math > Status & Tools > Database Tools > Flush SEO Analyzer Data, and you are still getting the same results, then it is likely that the result is correct. However, if you disagree with the result, you may ignore it.
This ignores the fact that RankMath has acknowledge that their Plugin is 'broken' and has told me relentlessly for weeks now that their 'development team is working on it.'
I am not certain where to go from here.
I understand WP would like to refrain from involvement with '3rd Party Apps' but in a very real sense involved insofar as WP essentailly endorsed these Apps by offering these 3rd Party Apps to their subscribers.
Concern by WP regarding RankMath is justifiable for a few reasons-
1. RankMath has told me that WP does not engage in 'good practices.' Accusing WP of being immoral in their business conduct is quite erroneous and untoward.
2. RankMath outright disputes the competence of JetPack in analyzing the minification and re-indexing issues.
3. RankMath has a 'broken' Plugin but to my knowledge has not made this fact known to their subscribers nor to potential subscribers.
In the state of New York, it is illegal to sell a product [including Plugins] which the seller knows to be broken and/or defective.
Certainly, this is nothing that WP/JetPack/Automatic would wish to be either direcdtly or indirectly associated with.
It would be so much easier if subscribers did not need to utilize 3rd Party Apps such as RankMath and if Automatic/JetPack could offer the same service[s] directly to subscribers including their fine Customer Support.
This would be a great advantage as then subscribers would be treated as valued customers and not relegated to the life of a ping-pong ball.
Any assistance would be greatly appreciated.  Your are the only remaining beacon of hope in this entire affair.
Thank you
Lewis
Thank you


Theres is something fundamentally flawed 


    On Wednesday, March 27, 2024 at 05:59:35 AM EDT, Alin Clamba ***@***.***> wrote:  
 
 


Hey Lewis,

Thank you so much for your detailed message and for sharing your experience with us. It really helps us understand the full picture of what you’ve been going through with the SEO tool issues. Your Dunkin Coffee boy analogy definitely keeps things in perspective, and it’s clear you’ve been navigating a challenging situation with grace and patience.

From our side at Jetpack, after thoroughly reviewing the information you provided and the technical aspects on our end, we’re confident that the issue lies outside of our scope, specifically with the SEO Analyzer tool you're using. While we strive to support our users as comprehensively as possible, our ability to intervene directly with third-party tools, like the SEO Analyzer, is limited.

However, we're not just going to leave you hanging. To help move things forward with the Rank Math team, here’s a draft message you can use or modify to contact their support. This message aims to clearly articulate the issues you’ve encountered, emphasizing the need for their direct assistance:


I am reaching out for urgent support regarding ongoing issues with the SEO Analyzer tool, specifically related to minification errors and the malfunctioning of the re-indexing feature. These problems have persistently impacted my website's SEO performance and, consequently, my AdSense revenue.

After a thorough review and dialogue with Jetpack support, it has been conclusively determined that the issues are not originating from Jetpack's services. This has led us to understand that the resolution needs to come from adjustments or fixes to the Rank Math SEO Analyzer tool.

The specific issues I am facing are as follows:
   
   - Minification Errors: Despite Jetpack confirming that the resources (CSS/JS files) on my site are correctly minified, the SEO Analyzer continues to flag these as errors. This discrepancy has left me at a standstill, unable to progress in optimizing my site’s SEO performance.
   - Re-indexing Feature Malfunction: The re-indexing feature within the Rank Math plugin has erroneously reset thousands of my SEO post scores to lower values, not once but twice. This has necessitated several hundred hours of manual correction, with approximately 1000 more posts to address.

The direct impact of these issues on my site's performance and my livelihood compels me to seek your immediate and focused assistance. A detailed examination and prompt resolution of these specific problems from your team would be greatly appreciated.


After providing you with this draft, it’s important to note that we've reached a juncture where, unfortunately, our ability to assist further is limited since the issue originates beyond our services. We’re confident, however, that by bringing this matter directly to Rank Math's attention with the specifics outlined, you're taking a positive step towards resolving these challenges. We sincerely hope this draft facilitates a productive conversation with Rank Math and leads to a swift resolution for you.

Best of luck!

**Comment by Purrington1949** [comment]
Alinclamba

I did as you suggested and sent the draft of your letter to RankMath.

 'Great' at RankMath sent me the following message and referred me back to JetPack.

Great- 'Based on your previous ticket, I assume the website you’re having issues with is carljungdepthpsychologysite.blog. I ran a test on your website using the public version of the SEO Analyzer tool , and the results also flagged some files as not minified. You may want to share this information with the Jetpark team again.

How to proceed.

Thank you,

Lewis

Image sent to me by 'Great' RankMath

![miification](https://github.com/Automattic/jetpack/assets/151528519/f62a87ac-7de4-4561-a5c6-6592a4e1935f)

**Comment by Purrington1949** [comment]
Unfortunately, it appears that ticket 34201 has recently been prematurely closed.
If you will take moment to review the thread you will find that some of your colleagues offered valuable assistance.
Among them was Alimclamba who assisted me in preparing a draft letter to RankMath regarding this issue.
In reply, 'Great' at RankMath refered me back to JetPack.
I have posted his reply on the thread earlier today but noticed the thread said 'closed' so I do not know if it will be seen by you or Alinclamba.
Could you look into this.
Thank you 
Lewis
    On Wednesday, March 13, 2024 at 09:08:13 PM EDT, thingalon ***@***.***> wrote:  
 
 


Hi again @Purrington1949.

I'm afraid that your image did not come through. It looks like you're replying to this GitHub thread via email. Can I recommend visiting the thread directly at #34201 to post your reply. But please bear in mind that any images you post here will be publicly visible, so don't include any sensitive information.

I see that this GitHub ticket was created in response to a WordPress.org Support Forum thread here: https://wordpress.org/support/topic/jetpack-and-js-and-css-minification/#post-17214305

I've examined the CSS and JavaScript being served on the site mentioned in the original Forum thread, and it appears to be minified when I view it. Here is a sample:

image.png (view on web)

I do still see there are comments in there which begin with /*! at the beginning, but it is common practise to keep comments with that marker on them when minifying content, as they often denote important meta-information or licensing information that is not allowed to be stripped.
