### ISSUE TITLE
Sharing: add notice in wp-admin Sharing settings to explain that this doesn't impact the sharing block

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#34326]
In WP-admin > Settings > Sharing, when the sharing module is active and the site uses a block-based theme, we should gray out sharing settings and display a notice inviting folks to go to the site editor to configure sharing on their site using the new sharing block.

<img width="1290" alt="image" src="https://github.com/Automattic/jetpack/assets/426388/1abbb6f8-a4c1-4951-9534-3c13c9c2b804">

Related: #34327

Epic: #19694

**Comment by keoshi** [comment]
Hey @jeherve. While going through this, I thought why not simply hide the legacy options since they're not applicable in case a block theme is being used? Essentially following the logic of the designs in https://github.com/Automattic/jetpack/issues/34325

This would keep the UI highly relevant and clean in both scenarios.

My concern is simply linking users to the block editor and expecting them to know what to do and where to do it. With this in mind, documentation on how to add and use the block will be crucial for user success, so I also added a secondary CTA that would link people to our docs.

![image](https://github.com/Automattic/jetpack/assets/390760/f4116180-c143-4120-aeca-e55b40589dec)

Let me know what you think about this. Don't mind going with a greyed-out section; I'm mostly concerned about presenting this consistently throughout our various interfaces.

**Comment by jeherve** [comment]
> While going through this, I thought why not simply hide the legacy options since they're not applicable in case a block theme is being used? 

That sounds good to me. I like replacing it with links (including links to the docs)!
