### ISSUE TITLE
Sharing Block: update messaging in Jetpack Dashboard > Settings > Sharing to mention new block

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#34325]
When a site owner uses a block-based theme, they should not be offered an option to turn on the sharing module. Instead, we should suggest they go to the site editor and add the new sharing block to their site templates.

<img width="1109" alt="image" src="https://github.com/Automattic/jetpack/assets/426388/a4829e6e-8bf1-4896-bfce-9e0419886c69">

*****

Epic: #19694

**Comment by keoshi** [comment]
Agreed! I think the UI should be dynamic here, showing only the relevant information depending on the type of theme is active at a given time.

#### Legacy theme

![image](https://github.com/Automattic/jetpack/assets/390760/aaa7d185-e188-4247-855f-851f4a9fa031)


#### Block theme

![image](https://github.com/Automattic/jetpack/assets/390760/9f8ff48b-c437-408f-8c03-d6c70cb8ee1c)

Changes:
- Removes toggle since it's not needed.
- Gets rid of the external icon because the user stays in the site.

The settings UI starts to fall apart a little bit with all the dividers, but let's worry about that later.

**Comment by jeherve** [comment]
This sounds good to me for a start. Later on, maybe we could explore automatically adding the buttons to single posts templates with a toggle there (or in wp-admin sharing settings, or in both places?). We're having a conversation about that here:
pdDOJh-2JP-p2#comment-2093

**Comment by simison** [comment]
> Instead, we should suggest they go to the site editor and add the new sharing block to their site templates.

I think the toggle was still helpful; site editor and fiddling with templates feels a bit more advanced.

Can we inject the block into post templates with the toggle turned on, instead of removing this as "legacy"? Block Hooks API I think is the way to go.
