### ISSUE TITLE
Sharing: trigger buttons do not work with Ajax Load More

### ISSUE THREAD

**Issue by zinigor** [Automattic/jetpack#3439]
With Infinite Scroll disabled and Ajax Load More enabled:
## What I expected

The MORE button drawer should open for posts that are loaded with Ajax Load More. 
## What happened

Drawers do not open neither by hovering, nor by clicking on them.
## Steps to reproduce the issue
- Install and activate [Ajax Load More](https://wordpress.org/plugins/ajax-load-more/);
- add some sharing buttons to the sharing button drawer in the Sharing settings;
- disable Jetpack IS;
- add the shortcode into for example archives page footer: `<?php echo do_shortcode('[ajax_load_more]');    ?>`
- load new posts using the control;
- observe that the drawer doesn't open.

I initially thought that it would suffice to just change the way we handle mouse events in the Sharing module code (i.e. use a global event listener), but the fact that the drawers work with Infinite Scroll puzzles me. Does anyone have any ideas how it works?

cc @ethitter

**Comment by ethitter** [comment]
Sharing buttons works in IS due to https://github.com/Automattic/jetpack/blob/d03bb2ed717bcdac7438d078a29b156cd560d492/modules/infinite-scroll/infinity.php#L1233 and https://github.com/Automattic/jetpack/blob/5892b19e02c8e91283aef7a78877ddf9e0ec3522/modules/infinite-scroll/infinity.js#L327. Hope this helps, as I don't recall much about what led to those changes. Blaming the corresponding lines in wpcom SVN may reveal Trac tickets or a P2 link with additional details about what led to those additions.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
