### ISSUE TITLE
Sharing button: add official X button

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#34459]
### Steps to reproduce

1. sharing
2. have X button
3. Turn on "official buttons" style

### What you expected to happen

Official looking Twitter/X button.

### What actually happened

<img width="1151" alt="Screenshot 2023-12-05 at 19 37 02" src="https://github.com/Automattic/wp-calypso/assets/87168/18845659-43de-470d-8f24-f5c3a90e3e9a">

Note "X" next to Facebook not rendering well.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

cc @pablinos @jeherve since you've been working on this stuff recently

**Comment by jeherve** [comment]
> Note "X" next to Facebook not rendering well.

I'm afraid there is no official X button yet. There is an official Twitter button still, but X hasn't released any update of that button with X branding yet as far as I know. When that happens, we'll be able to add an official X sharing button to our list of supported services.

For reference, here is the current documentation on that button:
https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview

**Comment by simison** [comment]
Should we just render official Tweet button meanwhile? Now it just looks broken.

Or I guess it's functional, we just use the "text only" version? 🤔 Would the logo version look more native in this case?

**Comment by pablinos** [comment]
What do we do for other networks that don't have an 'official' button?

**Comment by anomiex** [comment]
It appears that on the front end and in `/wp-admin/options-general.php?page=sharing` it falls back to the Icon + Text style.

![Front end](https://github.com/Automattic/jetpack/assets/1030580/01609a8e-93ba-4c46-8f54-4ddaa46a4ed3)
![Settings](https://github.com/Automattic/jetpack/assets/1030580/bdba99b1-b7a2-494c-87b2-122022b6bfdf)

The screenshots in the original report here appear to be about the UI in Calypso, which appears to show the Text style instead of Icon + Text. Here's the Calypso screenshot corresponding to the above two:

![Calypso](https://github.com/Automattic/jetpack/assets/1030580/4b66aa55-aa37-4b21-9413-5baf8df354f6)

P.S. Looks like the official Pocket button is broken, the service's iframe has an error page rather than the expected button.

**Comment by jeherve** [comment]
> Should we just render official Tweet button meanwhile?

But then it would be a Twitter button, not an X button. If folks want a Twitter button, we have the Twitter button for that imo.

> What do we do for other networks that don't have an 'official' button?

We fall back to a text version wth an icon. However, the X button currently doesn't show an icon because of a cache bug. I would appreciate a review for a fix, in D131104-code.

| **Before** | **After** |
|--------|--------|
| <img width="557" alt="Screenshot 2023-12-06 at 15 30 35" src="https://github.com/Automattic/jetpack/assets/426388/d9ea73c7-fefc-446e-994b-f3be073aab46"> |  <img width="644" alt="Screenshot 2023-12-06 at 15 30 19" src="https://github.com/Automattic/jetpack/assets/426388/dc0d5ffe-4e20-4da8-8744-62c93c38348d"> |

**Comment by jeherve** [comment]
Marking this as closed as I committed the diff above.
