### ISSUE TITLE
Images not visible on new post email

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#34850]
### Impacted plugin

Jetpack

### Quick summary

When posting an image, they aren't visible on the post email anymore.

### Steps to reproduce

Create a post with image, and publish it. You can try also enable "lightbox" feature.

<img width="1527" alt="Screenshot 2024-01-04 at 12 30 52" src="https://github.com/Automattic/jetpack/assets/87168/de373cd9-98c2-4956-8b1e-504b32097933">

See the email:

<img width="826" alt="Screenshot 2024-01-04 at 12 30 34" src="https://github.com/Automattic/jetpack/assets/87168/fba823fb-0717-4435-9793-8108a5cb5efc">

- No images visible
- Lightbox one has extra button that shouldn't be visible in emails.

See the post:

<img width="1035" alt="Screenshot 2024-01-04 at 12 31 25" src="https://github.com/Automattic/jetpack/assets/87168/693398f1-338c-4a6f-805c-e857f54fe38a">

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by edanzer** [comment]
I've started looking at this. I initially thought I could duplicate, but the issue was that the setting to show excerpt vs full content that lives on the Settings > Newsletter page. As long as that is set to show all content, images and other media are showing fine for me. 

<img width="933" alt="images-in-emails" src="https://github.com/Automattic/jetpack/assets/21228350/2686d890-3a49-4fc7-b3c3-4655f3c195b8">

**Comment by simison** [comment]
Thanks! I'll try see again also with the posts I noticed this with, because I received one post that now worked from a blog that didn't work before.

I still saw the "lightbox button" appear in emails which would be good to clean out for emails.

**Comment by jeherve** [comment]
cc @Automattic/apex who made some changes to subscription settings in the past few weeks, and who may have more info.

**Comment by TimBroddin** [comment]
This should be fixed now with: D135301-code
