### ISSUE TITLE
Conflict Between Jetpack Stats and Cocoon Theme

### ISSUE THREAD

**Issue by bizanimesh** [Automattic/jetpack#34877]
### Impacted plugin

Jetpack

### Quick summary

The Jetpack stats feature is not behaving properly at **Jetpack » Stats** when Cocoon Theme is installed on the site.

### Steps to reproduce

1. [Download](https://wp-cocoon.com/downloads/) + install the Cocoon Theme and Jetpack plugin on the Site.

2. Go to **Jetpack » Stats**, and as you will hover the mouse cursor over the stats, it will redirect you to the bottom of the same page.

https://github.com/Automattic/jetpack/assets/52444539/673fb07a-ebd4-4e1f-8dd0-12b13e62c4c8

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by jeherve** [comment]
I was able to reproduce the issue in Chrome, but not in Firefox.
Given that the problem is specific to this theme, and since the theme enqueues CSS and JS files on all pages of the wp-admin dashboard, I would recommend getting in touch with them to let them know about the issue. They should be able to make changes to the theme so its resources are only enqueued on pages where they're needed.
