### ISSUE TITLE
Multisite: Fatal error from AtD when bulk-connecting sites

### ISSUE THREAD

**Issue by iandunn** [Automattic/jetpack#3506]
1) Browse to `wp-admin/network/admin.php?page=jetpack`
2) Select 3+ sites
3) Select `Bulk Actions > Connect`
4) Select `Apply`

The sites will be connected until the fatal occurs, and the ones after that won't be.

> [04-Mar-2016 00:56:20 UTC] PHP Fatal error:  Cannot redeclare AtD_config() (previously declared in wp-content/plugins/jetpack/modules/after-the-deadline.php:74) in wp-content/plugins/jetpack/modules/after-the-deadline.php on line 74

**Comment by kraftbj** [comment]
@iandunn Were any of the sites already connected from the individual site's wp-admin?

I couldn't duplicate, but I did get of `PHP Warning:  Cannot modify header information - headers already sent by (output started at /srv/www/master/html/wp-includes/script-loader.php:1184) in /srv/www/html/wp-content/plugins/jetpack/class.jetpack.php on line 5475` style messages after one of the subsites had issues.

Notably, multisite registration just registers each site one-by-one, so in my case, one of the site threw unrelated notices which tripped up everything after it. In either case, seems broken.

@roccotripaldi Since you're working on the site registration bits right now, just in case there's any connection.

**Comment by roccotripaldi** [comment]
@kraftbj - I was able to reproduce your errors, but not able to reproduce @iandunn 's errors.

I do not think this is related to my recent changes to the connection process, but I'll do some digging.

**Comment by iandunn** [comment]
> Were any of the sites already connected from the individual site's wp-admin?

Nope, all off them had `Connect` in the Connected column of the Sites screen.

I tried reproducing this on my sandbox and didn't get the fatal -- _just got the same `headers already output` errors that you did_ -- so I'm not sure what was different on production. I'll keep an eye out for more instances.

`load_modules` uses `require` instead of `require_once`<sup>[1]</sup>, but I don't see anything (in Jetpack or my custom code) that's calling it multiple times.

I can't think of any reason why it needs `require` instead of `require_once`, but there definitely could be ones that I'm not aware of, and changing that would warrant significant testing, so I'm guessing it's not worth it unless other people start reporting this too.

[1] - It's switching from `require` to `include` in 3.9.3, see #3334

**Comment by roccotripaldi** [comment]
i think i know why it is happening. i think we need to check that `$jetpack_unique_connection['connected'] ` is set before we attempt to use it. 

https://github.com/Automattic/jetpack/blob/master/class.jetpack-client-server.php#L33
