### ISSUE TITLE
Newsletter/Pop-up template not working with Blockbase themes

### ISSUE THREAD

**Issue by Robertght** [Automattic/jetpack#35259]
### Quick summary

I encountered someone who cannot edit the template of the newsletter pop-up when using the Kerr theme.

### Steps to reproduce

1. Activate Kerr
2. Go to Settings > Newsletter 
3. Activate the Newsletter pop-up option and click on "Preview and edit the popup(opens in a new tab)"

### What you expected to happen

To be able to modify the Jetpack subscription modal.

### What actually happened

I got an empty template with "null" in the title of the page(browser tab).

![image](https://github.com/Automattic/themes/assets/6737345/677f141f-b4c4-461b-aa8b-02efaa1ed23d)

### Context

7355315-zen

### Platform (Simple, Atomic, or both?)

Simple

### Other notes

This happens with Blockbase&Blockbase Premium themes.

Tested with Videomaker, Russell, Arbutus, etc. 

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

Switch to another theme like Blank Canvas if the theme is simpler or find a replacement theme.

**Comment by cat-og** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated 
- Tested on Atomic – Replicated

📌 ACTIONS
- Triaged

**Comment by devNigel** [comment]
Another report: 7527596-zd-a8c

I was able to reproduce the issue with Varese theme as well.

**Comment by AnjanaV93** [comment]
Another report in 7541242-zen

The Subscriber pop-up is blank in Videomaker theme:

<img width="1031" alt="image" src="https://github.com/Automattic/themes/assets/129587477/2037e9a8-3d38-478f-bae5-f6e8d8367373">

As a temporary workaround, I suggested this CSS:

```
.jetpack-subscribe-modal__modal-content, .jetpack-subscribe-modal__modal-content button {
    color: #000 !important;
    background: Automattic/themes#999;
}
```

<img width="857" alt="image" src="https://github.com/Automattic/themes/assets/129587477/d1d554c3-9dff-4960-87d2-454b89a9fa2f">

**Comment by sashastone** [comment]
I'm experiencing the same issue on my own site, using the Zoologist theme. When I click "Preview and Edit Popup" it opens a blank page with no ability to add blocks or edit. 

<img width="1637" alt="newsletterpopup" src="https://github.com/Automattic/themes/assets/34173117/323742db-6ae4-4e0d-a1e8-ed177d239012">

**Comment by hideandgeek404** [comment]
This has also been reported again at p9F6qB-e7K-p2

However, through some investigation I have found both the issue and a workaround.

This issue is not restricted to Blockbase themes, unfortunately. Instead, it is applicable to any theme using a child theme. The reason for this is that the link in `https://wordpress.com/settings/newsletter/{site_url}` points to https://{site_url}/wp-admin/site-editor.php?postType=wp_template_part&postId=**{PARENT_THEME_SLUG}**%2F%2Fjetpack-subscribe-modal&canvas=edit but it should point to https://{site_url}/wp-admin/site-editor.php?postType=wp_template_part&postId=**{CHILD_THEME_SLUG}**%2F%2Fjetpack-subscribe-modal&canvas=edit

Interestingly, this only seems to affect Calypso, as the workaround is to access `Jetpack > Settings > Newsletter` which also gives a link to preview the pop up but has the correct child theme slug in the URL. 

**Confirmation of the issue**
Visiting `WordPress.com > Settings > Newsletter` and clicking the `Preview and edit the popup` link opens a page where the URL includes the parent theme slug instead of the active child theme slug. This in turn means that the template cannot be loaded. If the correct child theme slug is replaced in the URL the preview loads. A more user friendly workaround is shown below.

**Workaround**

1. Click `Jetpack`
2. Click `Settings` in the top right
3. Click `Newsletter` in the tabs
4. Click the `Preview and edit the popup` link (this should include the correct child theme slug in the URL)

**Comment by simison** [comment]
We have the code in two places, in Jetpack and Calypso:

- https://github.com/Automattic/jetpack/blob/2f48ff68f3ade46e250800a313d40ef507ffd70e/projects/plugins/jetpack/_inc/client/newsletter/subscriptions-settings.jsx#L53
- https://github.com/Automattic/wp-calypso/blob/18fbf112a978dd5eea2564d85d9aedf956170ac8/client/my-sites/site-settings/settings-newsletter/SubscribeModalSetting.tsx#L31

Slack p1706208764513469-slack-C052XEUUBL4 and p2  p7DVsv-jNo-p2

**Comment by pkuliga** [comment]
Potential fix:
https://github.com/Automattic/wp-calypso/pull/86904
~~Needs a review and some testing.~~
