### ISSUE TITLE
Verbum: Where to add issues

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/jetpack#35314]
We archived the Verbum repo, so we need a new place where to see the issues.

I created https://github.com/orgs/Automattic/projects/908

Let's specify in the Verbum readme where to add issues and also that it is possible to add the `Verbum` flag.

**Comment by jeherve** [comment]
I would recommend a few things that may make triage easier:

1. Use an organization-wide project board instead of a Jetpack project board: https://github.com/orgs/Automattic/projects/908/views/1 This way we'll be able to add to the board from other repos as well, and the board will be more visible.
2. Get rid of the general "Verbum" label, and use the automated "[mu wpcom Feature] Verbum Comments" that gets added to all PRs touching the feature already.
3. Automate issues getting added to the board, and your team getting pinged in Slack when high or blocker issues are added to the board.
    - This PR will take care of that: https://github.com/Automattic/jetpack/pull/35326
    - This diff will help HEs get to the right place: D136363-code
