### ISSUE TITLE
Pause method for Infinite Scroll

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/jetpack#3536]
It would be useful to provide a pause method for infinite scroll.

Example use case:

Query Monitor is a debugging plugin which appends it's information to the end of the page. With sites where Infinite Scroll is active, you scroll to see the Query Monitor information at the bottom, then the page loads some more posts, and so you scroll to the bottom again, and the page loads more posts… repeat, ad infinitum.

Query Monitor already [uses](https://github.com/johnbillion/query-monitor/blob/c97268a695afc5f5b49d328ae12b13e7e66670d1/assets/query-monitor.js#L97-L105) the pause method from another Infinite Scroll implementation to stop more posts loading when debugging information is being viewed. If Jetpack's Infinite Scroll implemented a pause method, QM could do the same.

See: https://github.com/johnbillion/query-monitor/issues/172

**Comment by eliorivero** [comment]
I've introduced two methods to pause and resume infinite scrolling. Seems like John [opted for overwriting](https://github.com/johnbillion/query-monitor/commit/135325d843a9f59d6a0017c225777e6c9038e626#diff-3d6c2bbc39189753b08f7a0fb0b37138R109) the `check()` method. If this PR is merged, we should suggest him to use the pause method here since it's easy to resume infinite scrolling.
