### ISSUE TITLE
[Boost] Make sure WP Super Cache and Boost Cache do not fight

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#35497]
Test how WP Super Cache and Boost Cache behave in each other's presence. If one is already installed and running, it should not be interrupted by installing the other.

Both Boost Cache and WP Super Cache should be able to detect each other's advanced-cache.php files and show a custom message indicating that the other is enabled.

**Comment by simison** [comment]
I'd also expect both follow the same "do not cache" constant https://jetpack.com/support/wp-super-cache/wp-super-cache-faq/

Edit: checked that this is already the case, nice!

https://github.com/Automattic/jetpack/blob/09b9352c2ad2aab983ba5aca7600e941fbd23c15/projects/plugins/boost/app/modules/cache/Boost_Cache.php#L80-L82

**Comment by donnchawp** [comment]
The code that generates advanced-cache.php in both plugins won't overwrite an existing wp-content/advanced-cache.php if the one that is there doesn't belong to it. WP Super Cache does report this error, but doesn't mention Boost specifically.

The setup function in Page_Cache returns a WP_Error if it fails to create an advanced-cache.php

**Comment by thingalon** [comment]
For the purposes of our MVP release, it is enough to ensure (test) that these plugins do not interact with each other badly in any way.

We can have a followup release which offers specific messaging about each plugin seeing each other's advanced-cache files to give more details to users.

**Comment by donnchawp** [comment]
**WP Super Cache** will show a warning with a heading saying "Warning! You may not be allowed to use this plugin on your site." with details about the existing advanced-cache.php:

"The file /var/www/..../wp-content/advanced-cache.php was created by another plugin or by your system administrator. Please examine the file carefully by FTP or SSH and consult your hosting documentation.

If it was created by another caching plugin please uninstall that plugin first before activating WP Super Cache. If the file is not removed by that action you should delete the file manually.

If you need support for this problem contact your hosting provider."

**Jetpack Boost** shows this error when WP Super Cache has created the advanced-cache.php:

"Cache loader file already exists

This feature cannot be enabled because wp-content/advanced-cache.php was found on your site. It was created by another plugin, or your hosting provider. Please remove it to use this module. [Learn more.](TBD)
[Try again button]"

**Comment by haqadn** [comment]
Seems like we can close this issue for now?

**Comment by thingalon** [comment]
Not quite. I think that WPSC and Boost should detect each other and give a more specific message.
