### ISSUE TITLE
Jetpack_PostImages::from_gallery() Function: Should detect images from slideshow galleries

### ISSUE THREAD

**Issue by davidakennedy** [Automattic/jetpack#3572]
Reproduced on a WordPress.com site.

Using the Boardwalk theme, a post does not display an image on the index page when a post contains only a slideshow, returning a green colored block instead. Boardwalk displays an image on the index page from a post that contains a gallery.

#### What I expected

Expected to see images on the index page for both posts.

#### What happened instead

The image was missing on the index page when a post contains only a slideshow. 

#### Steps to reproduce the issue

* Use Boardwalk theme.
* Upload 4 images directly to the Media Library.
* Add new post.
* Select Add Media, choose Create Gallery, and select Media Library.
* Select 2 of the images and press the Create a new gallery button.
* Use default settings and Press Insert Gallery button to add gallery to post.
* Publish. Resulting post: ​https://darrellschulte092115.wordpress.com/2015/09/28/test-gallery-post/
* Add new post
* Select Add Media, choose Create Gallery, and select Media Library.
* Select 2 of the images and press the Create a new gallery button.
* Change Type to Slideshow without changing the other settings.
* Press Insert Gallery button to add gallery (slideshow) to post.
* Publish. Resulting post: ​https://darrellschulte092115.wordpress.com/2015/09/28/test-slideshow-post/
* The only discernible difference are the image ids and the addition of the slideshow type:

`[gallery ids="1723,1720"]`

`[gallery type="slideshow" ids="1722,1721"]`

After some digging, @mendezcode suggested that in order to fix this issue, the `Jetpack_PostImages::from_gallery()` function should be patched/refactored to properly detect images from slideshow galleries.

**Comment by jeherve** [comment]
Since ae784dcd6e25cfd86faa7a96a1598dfab901781e, we use core's `get_post_galleries_images()` function to retrieve images from galleries. It's useful when looking for images in a gallery, but slideshows work a bit differently: the gallery HTML isn't built the same way ([reference](https://github.com/Automattic/jetpack/blob/3.9.4/modules/shortcodes/slideshow.php#L187)), so Core's `get_post_galleries()` ([reference](https://github.com/WordPress/WordPress/blob/4.4.2/wp-includes/media.php#L3586)) can't get the image sources from the galleries.

On the other hand, we also have `Jetpack_PostImages::from_slideshow()` ([reference](https://github.com/Automattic/jetpack/blob/3.9.4/class.jetpack-post-images.php#L14-L79)) that was built to retrieve images from the old `[slideshow]` shortcode. Maybe we should refactor that to grab slideshow images.

**Comment by eliorivero** [comment]
Closing in favor of #4069.

**Comment by eliorivero** [comment]
@davidakennedy there's a patch now for this at #4083 in case you want to test it.
