### ISSUE TITLE
Feature Request: Songkick Integration 

### ISSUE THREAD

**Issue by Aurorum** [Automattic/jetpack#35835]
### Impacted plugin

Jetpack

### What

A WordPress.com user was very keen on embedding Songkick on their site. They felt that needing to upgrade to the Creator plan to do so was a deal-breaker for them.

I wonder if folks might feel that this integration would be something that fits in within the Jetpack plugin?

### How

We already have an Eventbrite block, but Songkick seems increasingly popular too:

> Right now, more than 15 million music fans across the globe use Songkick to track their favorite artists, discover concerts and buy tickets with confidence.

Songkick has a widget that would be very easy to embed, but I'm unsure if Jetpack would be an appropriate place for it. My guess based on the Eventbrite block is that it might be, and I promised the user I'd pass on the idea.

cc @jeherve - would appreciate some thoughts on this as I'm always happy to try spin up new blocks. :) 

7764803-zen

**Comment by jeherve** [comment]
Since the service is popular, I think it would be even better to add the provider to WordPress itself, following the guidelines here:
https://make.wordpress.org/core/handbook/contribute/design-decisions/#adding-new-oembed-providers

I would recommend [opening a Trac ticket](https://login.wordpress.org/?redirect_to=https://core.trac.wordpress.org/newticket) and providing the answers to the questions in the guidelines.
