### ISSUE TITLE
[Boost] Re-add score increase popout

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#36052]
Jetpack Boost used to have a nice stream of reviews, which has tapered off since we released Boost 3.0.0. Ref: p1708932630630129/1708726302.002779-slack-C01264051NE

This coincides with when we removed the score increase/decrease pop-outs, because we found the decrease pop-out triggered in a heap of situations it shouldn't, leading users to get upset and confused.

We should start by re-adding the "Your score got better" version of the dialog with a reminder for users to review the plugin. :)

**Comment by dilirity** [comment]
@haqadn and I discussed a solution over Slack.

### The solution

If the request for speed scores doesn't have any modules enabled, don't include the "no boost" scores in the response. We don't need to compare against the same thing.

As it turns out, we already do this 🤦🏻 

https://github.com/Automattic/jetpack/blob/996ae2bc757a70b3f1d6f4c1b78aea1cef1a431a/projects/packages/boost-speed-score/src/class-speed-score.php#L322-L325

### The problem with the solution

I tried moving forward, but realized that since the information about the active modules is stored in a transient, this only works until the transient expires. When it expires, there's no way to know what modules were active when the speed score was generated.

### What now?

Does it make sense to update the options that include the score, to include the active modules at the time of recording?

They look like this at the moment:

```
Array
(
    [0] => Array
        (
            [timestamp] => 1710238629
            [scores] => Array
                (
                    [mobile] => 88
                    [desktop] => 99
                )

            [theme] => Twenty Twenty-Four
        )

)
```

We could update them to include the modules in there like this:

```
Array
(
    [0] => Array
        (
            [timestamp] => 1710238629
            [modules] => Array
                (
                    critical-css
                    ...
                )
            [scores] => Array
                (
                    [mobile] => 88
                    [desktop] => 99
                )

            [theme] => Twenty Twenty-Four
        )

)
```

I've been going back and forth with this for a few days now and I think I need some help moving forward.

**Comment by thingalon** [comment]
@dilirity - Yes, I think it makes sense to include the active modules with the scores - because they can be thought of as metadata about the scores themselves. :)

**Comment by dilirity** [comment]
Turns out, we don't need the modules stored, as we already have info about which modules are active at the time the request completes.

https://github.com/Automattic/jetpack/blob/d4561132a5249dafb3a1296f4aa3248b4be8be1a/projects/packages/boost-speed-score/src/class-speed-score.php#L323
