### ISSUE TITLE
Site Logo: compatibility for old themes after migration to WP Core

### ISSUE THREAD

**Issue by mtomas7** [Automattic/jetpack#3622]
Hello, I have question about compatibility for old (child) themes after Site Logo will be migrated to WP Core.

Site Logo was using classes .has-site-logo for BODY, .site-logo-link for anchor that wraps the logo image and .site-logo for image itself. In WP 4.5 these classes will be changed to .wp-custom-logo for BODY, .custom-logo-link for anchor and .custom-logo for image.

We can imagine, there are many themes in the wild that are using these classes, especially .site-logo-link class for the logo positioning and other CSS styles. What will happen after Site Logo will be handed over to the Core functions? Will those themes suddenly break?

In current Jetpack [Site Logo migration](https://github.com/Automattic/jetpack/pull/3494/files) I didn't see option to deal with this issue.

First question: should this compatibility issue be implemented via Jetpack or Core, or it will be left for individual theme owners (some people might not have skills to deal withy it).

Plan B: if it is left for the theme owners to deal with it.

Currently for my theme I'm using this function to deal with BODY class:

```
function tinyframework_body_class( $classes ) {
	if ( function_exists( 'the_custom_logo' ) && has_custom_logo() ) {
        $classes[] = 'has-site-logo';
	}

	return $classes;
}
add_filter( 'body_class', 'tinyframework_body_class' );
```

But the real issue is with the .site-logo-link class. As it looks there is no good way to change it. Currently I'm using this function to filter final HTML output, but I'm not sure it is the best approach:

https://stackoverflow.com/a/22818089

```
if ( function_exists( 'the_custom_logo' ) && has_custom_logo() ) {
	/**
	 * Output Buffering
	 *
	 * Buffers the entire WP process, capturing the final output for manipulation.
	 */

	ob_start();

	add_action('shutdown', function() {
		$final = '';

		// We'll need to get the number of ob levels we're in, so that we can iterate over each, collecting
		// that buffer's output into the final output.
		$levels = ob_get_level();

		for ($i = 0; $i < $levels; $i++) {
			$final .= ob_get_clean();
		}

		// Apply any filters to the final output
		echo apply_filters('final_output', $final);
	}, 0);

	add_filter('final_output', function($output) {
	    return str_replace('custom-logo-link', 'custom-logo-link site-logo-link', $output);
	});
}
```

Thank you for your time!

**Comment by jeherve** [comment]
cc @dereksmart, who worked on the migration.

**Comment by dereksmart** [comment]
Hi @mtomas7

The main intent behind our custom_logo compat patch [you linked to](https://github.com/Automattic/jetpack/pull/3494/files) is to get out of the way (and not break the customizer) if the theme for some reason provides support for both `site_logo` and `custom_logo`.  It is not meant to migrate the logo automatically.  We are leaving this up to the theme developers.  

A theme that updates to use `custom_logo` should also update the theme to use core's render methods like `the_custom_logo()`, rather than Jetpack's output render methods such as `jetpack_the_site_logo()`.  Doing this will automatically output the logo wrapped in the [new class name](https://github.com/WordPress/WordPress/blob/a311bea6d11bceabfff96ed03a9908ff7ba10505/wp-includes/general-template.php#L882).  

In the (hopefully rare) case where a theme chooses to support `custom_logo` rather than `site_logo` **but does not change the output method or class names**, we simply grab the ID saved in `custom_logo` and continue rendering the logo the Jetpack way, using the same class names and render methods as we've always done.  

Hopefully this explanation helps!
