### ISSUE TITLE
Improve design of VideoPress view for Editor

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#3636]
Some good points made by Matt about the dialog for VideoPress introduced in https://github.com/Automattic/jetpack/pull/3556

<img width="910" alt="videopress-view" src="https://cloud.githubusercontent.com/assets/1041600/14365808/01f6a312-fce6-11e5-8cf5-b7f3576ab5ed.png">

- [x] put checkboxes to the left of the text, rather than floating all the way over to the right
- [x] we probably don't need a question mark on everything?
- [x] if something isn't editable, like the GUID, maybe don't put it in a form field. also "GUID" is pretty wonky
- [x] language on all of them can be made more intuitive or apparent

Other personal observations:
- [x] the word `flash` should be capitalized
- [x] the checkboxes should have the same style than other dialogs, like the link dialog
<img width="225" alt="checkboxes" src="https://cloud.githubusercontent.com/assets/1041600/14501826/b5f21332-017e-11e6-8196-d99dd3cd9063.png">

- [x] the embedded video should adjust to the width of the Editor. Right now is cropped as shown below.

<img width="620" alt="responsive" src="https://cloud.githubusercontent.com/assets/1041600/14368215/d7a7c76e-fcf2-11e5-8888-b4f88a49086f.png">

**Comment by samhotchkiss** [comment]
Thanks for your quick attention, @jeffgolenski

**Comment by georgestephanis** [comment]
> put checkboxes to the left of the text, rather than floating all the way over to the right

This isn't something we control directly, it's how TinyMCE formats modals, given the data we're prompting for.

> if something isn't editable, like the GUID, maybe don't put it in a form field. also "GUID" is pretty wonky

I'll see if we can change it to hidden or the like.

> language on all of them can be made more intuitive or apparent

Suggestions welcome.

**Comment by georgestephanis** [comment]
cc: @michelleweber -- can we get your editorial input on phrasing for the prompts?

**Comment by michelleweber** [comment]
I agree with making them statements, rather than questions. With the caveat that there might be (ha, *are*) technical things I don't know that might inadvertently introduce an inaccuracy, I'd suggest something like:

- Use High Definition video whenever possible
- Link video title to the original video on VideoPress.com
- Autoplay video when page is loaded
- Loop video playback indefinitely
- Only use open source codecs (note: this may harm performance)
- Use the legacy flash player (not recommended)

A little bit clearer, a little bit more natural-speech-y sounding.

For the "how many seconds?" question -- is that how many second after page load the video starts, or how many seconds into the video playing begins? You can read it either way.

At the risk of introducing too much/needless complexity, I wonder if an "advanced" subheading would be useful, for the open source, legacy player, and GUID items that non-technical users (like me!) won't really get/use.

**Comment by jeffgolenski** [comment]
I made a couple of verbiage changes in this branch: https://github.com/Automattic/jetpack/tree/enhance/videopress-dialog-interface

But as you said @georgestephanis, I see how TinyMCE has their dialog formatted. Is there anyway we can build this to use a different modal? One we can alter to our needs better and specifically set a VideoPress ID on the modal container so we can do some specific CSS work easy?

**Comment by georgestephanis** [comment]
@jeffgolenski I'm sure it's possible, but I have no idea how to do it, so I'd be starting from scratch.

I'm looking into something now to see if it's possible to just use the stock one, then add an extra class to it that we can work off of or the like.

**Comment by eliorivero** [comment]
@georgestephanis can we close the modal when the overlay is clicked? Just like it happens with the Media dialog and its overlay. People is used to it. I just tried clicking it to avoid reaching to the ⨉ and when it didn't close it was confusing.

**Comment by georgestephanis** [comment]
@eliorivero We /could/, and it wouldn't be difficult --

Just something like:

```js
$( document.body ).on( 'click', '#mce-modal-block', function(e){
	$('.mce-close').click();
});
```

However, it's intentionally breaking core paradigms, and with the old media modal in Core (pre ... 4.0?) there had been a lot of issues where someone is changing things, and accidentally clicks on the background (or touches) and closes it out, losing their work.

So I hesitate to override that default.
