### ISSUE TITLE
Allow Related Posts to show dummy data when using JETPACK_DEV_DEBUG

### ISSUE THREAD

**Issue by BinaryMoon** [Automattic/jetpack#3673]
I develop themes for sale - and support all of Jetpacks functionality. I like to be able to style things so they don't look stock - but it's really hard to style related posts locally since it doesn't work when running on my machine.

I have JETPACK_DEV_DEBUG enabled which allows me to test things like infinite scroll.

My suggestion is that if JETPACK_DEV_DEBUG is enabled then related posts can be enabled also. Instead of using the wordpress.com search api you would select X latest posts. This means the content won't actually be related - but I don't think that's an issue when developing.

I have spent this afternoon working on a small plugin which does this for me - but it's not ideal since thumbnails don't work. Plus I think it would be nice for other developers to be able to use this too.

You can see the code I am using here: https://gist.github.com/BinaryMoon/cca23cdb72a9ce42a0460e8d881ff021

**Comment by jeherve** [comment]
That's a good proof of concept, thank you!

I'll close this issue as a duplicate of #385, but will mention your issue there, because I think that's a good way to solve that issue.

> it's not ideal since thumbnails don't work. 

Is that only because Photon tries to resize the image ([1](https://github.com/Automattic/jetpack/blob/3.9.6/modules/related-posts/jetpack-related-posts.php#L920), [2](https://github.com/Automattic/jetpack/blob/3.9.6/class.jetpack-post-images.php#L536)), when that image isn't publicly accessible in your local environment?

We should be able to work around that issue.

**Comment by kraftbj** [comment]
I like that approach. Instead of hard-coding, Jetpack could pick the, say, three most recent posts or something to that effect.

**Comment by BinaryMoon** [comment]
Sorry - should have searched before posting this. The thumbnails don't work because of Photon - yeah. It's probably filterable as well, but I didn't look into that :)

**Comment by jeherve** [comment]
@BinaryMoon @kraftbj took care of that for us: #3674
