### ISSUE TITLE
[Super Cache] Add compat functions for sites running old version of PHP and WordPress

### ISSUE THREAD

**Issue by donnchawp** [Automattic/jetpack#36782]
WP Super Cache now uses str_contains, str_starts_with, and str_ends_with as of version 1.12.0 which are PHP8.x functions. WordPress has a polyfill in wp-includes/compat.php for those, but before WordPress 6.3, that file isn't loaded early enough and results in fatal errors. That file is loaded in [wp-settings.php](http://develop.svn.wordpress.org/tags/6.3/src/wp-settings.php).

We should provide our own copies of those functions, copying from compat.php for sites running PHP7.4 and older versions of WordPress.

Only one report so far: https://wordpress.org/support/topic/str_contains-etc-only-in-php8-2/

**Comment by donnchawp** [comment]
WP Super Cache now requires WordPress 6.3, which is why there has only been one report about this, but it does stop sites running older versions of WordPress from upgrading the plugin. Something we'll have to address if there's a security or major bug release.

**Comment by jeherve** [comment]
> WordPress has a polyfill in wp-includes/compat.php for those, but before WordPress 6.3, that file isn't loaded early enough and results in fatal errors.

I should note that the polyfills for`str_contains`, `str_starts_with`, and `str_ends_with` were added to WordPress in version 5.9.0, which was released on 25 January 2022.

However, and as mentioned in the WordPress.org forum thread:

> there is a polyfill in compat.php but that loads after advanced-cache.php in the wp-settings.php file pre 6.3, so doesn’t kick in.

This change was made in https://core.trac.wordpress.org/changeset/56007

WP Super Cache currently requires WordPress 6.3:

https://github.com/Automattic/jetpack/blob/ec74c238b56b4b5794fb3d79f9c0694f141f8838/projects/plugins/super-cache/readme.txt#L4

With that in mind, I would expect this to not be an issue anymore, since there cannot be sites running an up-to-date version of WP Super Cache on WordPress 6.2 and below.

**Comment by donnchawp** [comment]
Yep. The problem being, if we fix any long-standing bugs or security issues in the plugin. Those sites won't get those fixes.

The latest version of the plugin had a fix for a bug in the preload page that probably goes back years. Luckily, it's an obscure one that only happens on multisites, but it means that preload will only preload a portion of the posts on a site.

**Comment by donnchawp** [comment]
I don't think it's a huge problem, as sites will naturally upgrade over time if they are still maintained, which is why I set the priority to low.

**Comment by haqadn** [comment]
Closing because: 

> After thinking about this some more I'm going to close this PR without merging.
> 
> 1. The only [officially supported version of WordPress](https://wordpress.org/documentation/article/supported-versions/) is now the latest version.
> 2. Even last August, the required version was WP 5.9, so not far off WP 6.3.

https://github.com/Automattic/jetpack/pull/36853#issuecomment-2056458342
