### ISSUE TITLE
Dips in subscriber stats graph

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#36878]
We're seeing dips in subscription stats for some sites, e.g. [cicerosletters.wordpress.com](http://cicerosletters.wordpress.com/)

![image](https://github.com/Automattic/jetpack/assets/87168/7b7a1d1f-fad0-413f-b69c-a8c6b61cf385)
<img width="2267" alt="image" src="https://github.com/Automattic/jetpack/assets/87168/6d184e65-f83c-4915-8bf5-0e5bd17342d2">

Sometimes, it's multiple drops:

![image](https://github.com/Automattic/jetpack/assets/87168/578bf30d-55f5-465c-84bf-da0aa3d25ce1)

Slack thread p1712652329448609-slack-C82FZ5T4G

Customer 8000626-zd-a8c

All graphs seem to show first time this happen around March 21st

**Comment by filipanoscampos** [comment]
7900839-zd-a8c

**Comment by nicolynramos** [comment]
Another report: 8030858-zen

**Comment by kangzj** [comment]
I’ll prioritise it this week

**Comment by kangzj** [comment]
@Automattic/gold team recently refactored the cache clearing from different places to a single function called `clear_subscriptions_cache` - https://github.com/Automattic/gold/issues/338. The issue is not directly caused by that, but the change leads to much more frequent deletion of the subscriber counts in `subscription_counts`, so we are seeing more cases where the number suddenly drops and then comes direct back again right after.

To fix this, I've spun up a diff D145418-code that queues the subscriber recording job directly after the updates of the `subscription_counts` table, when the numbers have been updated. Theoretically tho there is still a loophole - if multiple jobs are running in parallel, this might still happen, but it'll be pretty rare.

To fully resolve this, I wonder if we could update table `subscription_counts` only, rather than deleting and then inserting. By doing that, we could make the counts more or less accurate at all times, rather than not having any records often. What do you think @Automattic/gold? Thanks.

cc @dognose24 @filipanoscampos @mikestottuk @Robertght

**Comment by chrismccluskey** [comment]
> To fully resolve this, I wonder if we could update table subscription_counts only, rather than deleting and then inserting.

I think this is entirely possible. I've created a task for this here: 385-gh-automattic/gold

**Comment by millerf** [comment]
@kangzj We'll tackle this as soon as possible (we are on a meetup right now) , and I believee this will indded fix your issue....

**Comment by millerf** [comment]
This should fix it: D145613-code 
I also added a parameter to retrigger the counts directly @kangzj

**Comment by kangzj** [comment]
Thanks for doing that @millerf 👍

**Comment by kangzj** [comment]
🚢  `D145418-code`
