### ISSUE TITLE
Malicious File Detected: jetpack/modules/theme-tools/responsive-videos/responsive-videos.min.js 

### ISSUE THREAD

**Issue by viraljetani** [Automattic/jetpack#3691]
My network solutions hosting provider is sending me emails for each of my wordpress install:

Below is the text on what I am getting..:
"
_As part of our routine monitoring, we have observed that some of the files hosted on this server belonging to [domain.com] hosted under your account, has some malicious files hosted.
In order to prevent blacklisting of our service with various service providers, we have blocked outbound port 80, 443, 587 and 465 for this domain name as a precautionary measure. Here are the details of the files that were detected to be malicious.

/home/userpublic_html/wp-content/plugins/jetpack/modules/theme-tools/responsive-videos/responsive-videos.min.js

We strongly suggest you to scan all the above listed files for any vulnerabilities. If the files are part of some plugins of your CMS, then we suggest you to update the plugin to the latest version or contact the plugin developer directly.
_"

**Comment by jeherve** [comment]
We’re looking into this now and believe it to be a false-positive from ClamAV.

The virus described is a system level trojan which tricks you into manually downloading malware, which really isn’t possible from plugin on a site (it would have to exist and run on your local PC), and the file has not been changed since 3.9.6 was released (at which time it was clean). Meanwhile, the file itself is simply a display fix for responsive videos on a few select themes.

In addition, responsive-videos.js (the source from which responsive-videos.min.js is minified) is not listed as infected.

The false-positive has been reported to ClamAV, and we’re hoping for a quick resolution.

From what we can tell so far, there is no cause for concern.

**Comment by jeherve** [comment]
To wrap this up, we haven't heard back from ClamAV yet, but we did notice that today's ClamAV virus definitions are no longer reporting against the responsive-videos.min.js file in Jetpack 3.9.6: https://virusscan.jotti.org/en-US/filescanjob/3toaljmv99

You should be all set!
