### ISSUE TITLE
[action-required-reviewers] Unable to request reviews if one of the reviewers is a bot

### ISSUE THREAD

**Issue by wagenet** [Automattic/jetpack#37058]
### Impacted plugin

None / Other

### Quick summary

When using action-required-reviewers a bot can be specified as a reviewer (e.g. `@renovate-approve[bot]`). However, this won't work with `request-reviews: true`. This is because the bot is not a repository collaborator and review cannot be requested from collaborators. Ideally, we'd be able to still request reviews from the other non-bot users.

### Steps to reproduce

```
Run Automattic/action-required-review
  with:
    token: ***
    requirements:
       - name: Dependencies
    paths:
      - '**/*'
    teams: [{"all-of":["web-frameworks"]},"@renovate-approve[bot]"]
    status: Require Approvals
    request-reviews: true
    fail: false
```

### What actually happened

```
Error: Unable to request review.
  Error: HttpError: Reviews may only be requested from collaborators. One or more of the users or teams you specified is not a collaborator of the soxhub/auditboard-frontend repository.
Error: Unable to request review.
  Error: HttpError: Reviews may only be requested from collaborators. One or more of the users or teams you specified is not a collaborator of the [SNIP] repository.
    at requestReviewer (/home/runner/_work/_actions/Automattic/action-required-review/93a995cac9308b74ef0c91c0d3ee8ded6bb9c2fe/webpack:/required-review/src/request-review.js:36:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at main (/home/runner/_work/_actions/Automattic/action-required-review/93a995cac9308b74ef0c91c0d3ee8ded6bb9c2fe/webpack:/required-review/src/main.js:101:1)
```

### Impact

One

### Available workarounds?

There is no user impact

**Comment by anomiex** [comment]
At a quick glance, probably the simplest thing would be to skip entries that both start with `@` and end with `[bot]` in this loop
https://github.com/Automattic/jetpack/blob/44111097987a4947975c7209e7ba03df6f8d1eee/projects/github-actions/required-review/src/request-review.js#L18-L24

There's [an API endpoint to directly check if a user is a collaborator](https://docs.github.com/en/rest/collaborators/collaborators?apiVersion=2022-11-28#check-if-a-user-is-a-repository-collaborator), but my first impression is that that's probably overkill unless the suffix check turns out to be insufficient. API calls are rate limited, after all.

If you want to make a PR I'll review it, otherwise I'll try to find a chance to do that myself later.
