### ISSUE TITLE
Tools: Jetpack Install fails with cryptic message when PHP version is wrong

### ISSUE THREAD

**Issue by gogdzl** [Automattic/jetpack#37524]
When PHP's version is incompatible with `jetpack install` we get the following message:
```
 pnpm jetpack install
✔ What type of project are you working on today? · plugins
✔ Please choose which project · crm
  ⠹ Installing pnpm dependencies
  ✖ Installing composer dependencies for plugins/crm
    → Command failed with exit code 2: composer install
Error: Command failed with exit code 2: composer install
    at makeError (file:///home/gogdzl/dsk/git/avengers/jetpack/node_modules/.pnpm/execa@7.0.0/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///home/gogdzl/dsk/git/avengers/jetpack/node_modules/.pnpm/execa@7.0.0/node_modules/execa/index.js:119:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  shortMessage: 'Command failed with exit code 2: composer install',
  command: 'composer install',
  escapedCommand: 'composer install',
  exitCode: 2,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  context: [Object: null prototype] {}
}
```

Environment:

```
 composer --version
Composer version 2.7.6 2024-05-04 23:03:15
PHP version 8.3.7 (/usr/bin/php)
Run the "diagnose" command to get more detailed diagnostics output.
```

By downgrading PHP everything runs smoothly.

**Comment by anomiex** [comment]
I was not able to reproduce this following the instructions provided.

Unfortunately a side effect of the usually user-friendly listr output is that if something goes wrong then the error message is not terribly helpful. Try running it with the `-v` option to get more helpful output.

I'll look into whether there's a good way to have the CLI suggest that in error cases like this.

**Comment by tbradsha** [comment]
I suppose doing a quick tool version check initially might make it less frustrating, at least? Same with #37523.

**Comment by anomiex** [comment]
I doubt the error here really is just about the PHP version, since I couldn't reproduce. More likely gogdzl's local copy somehow got into a state where `composer install` complained about some locked package version not being compatible with PHP 8.3.

And anyway we do already have a check during startup of the Jetpack CLI for versions. But it doesn't complain about PHP 8.3 since that satisfies the `^8.2` constraint.

As for #37523, the hard part there is that pnpm is bailing before ever running the Jetpack CLI, and the first call in that particular script pipes the output (which unfortunately pnpm prints to stdout rather than stderr) into jq which chokes on it. The solution to that seems simple enough, add another pnpm call of some sort earlier in the script to cleanly bail. The slightly tricky part is having a command that won't print something useless or confusing to stdout on success; I have a plan for that, I just haven't had a chance to implement it yet.
