### ISSUE TITLE
Slideshow block in a template is not available in a blog post that uses this template

### ISSUE THREAD

**Issue by Atalanttore** [Automattic/jetpack#37568]
### Impacted plugin

Jetpack

### Quick summary

In the WordPress forum, I was [advised](https://wordpress.org/support/topic/why-does-a-slideshow-block-in-a-template-not-appear-in-a-blog-post-2/#post-17777748) to create a GitHub report about this issue.

The `Slideshow` block is used in a template. On a blog post that use this template, the `Slideshow` does not appear as content, nor as an option in the right-hand settings menu of the Gutenberg block editor.

### Steps to reproduce

The Gutenberg block editor is used to carry out the following steps.

1. Install the Jetpack plugin to have a [Slideshow](https://jetpack.com/support/jetpack-blocks/slideshow-block/) block.
2. Create a new template with the name `Single posts with slideshow` or any other name you like. To avoid mistakes, you should use the suggested name.
3.
    - Copy the HTML code of the `Single Posts` template and
    - paste it into your newly created `Single Posts with Slideshow` template.
4. In the `Single Posts with Slideshow` template,
    - delete the `Featured Image` block and
    - add a `Slideshow` block instead.
5. Create a new blog post and select `Single Posts with Slideshow` as its template.

### A clear and concise description of what you expected to happen.

I expected the `Slideshow` block to appear as content and as an option in the right settings menu of the Gutenberg block editor.

### What actually happened

In the right-hand settings menu of the Gutenberg block editor, there is still an option to select a _Featured image_, although the `Featured Image` block has been replaced by a `Slideshow` block.

`Featured Image` block has been replaced by a `Slideshow` block:
![Edit-template](https://github.com/Automattic/jetpack/assets/628474/48ff035c-b782-433e-b15d-fd2d50c8f9ff)

There is still an option to select a _Featured image_:
![Edit-blog-post](https://github.com/Automattic/jetpack/assets/628474/3c917df2-21c5-4a26-a177-946cc521682b)

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by jeherve** [comment]
Somewhat related: #30891, #22748

**Comment by jeherve** [comment]
I reviewed your suggestion, and I'm afraid that's not something we'll be able to achieve in Jetpack today.

> I expected the Slideshow block to appear as content and as an option in the right settings menu of the Gutenberg block editor.

I'm afraid the block editor doesn't offer that option right now.

> In the right-hand settings menu of the Gutenberg block editor, there is still an option to select a Featured image, although the Featured Image block has been replaced by a Slideshow block.

That's indeed expected. Removing the Featured Image block from a template will not remove that element from the post editor sidebar. Similarly, removing the display of tags in the single posts template wouldn't remove the tags section in the post editor's sidebar.

You would always want those areas to be displayed in the post editor, because even though the featured image block isn't part of that specific custom template we created, it may still be part of other templates in use on the site (for example we may be displaying featured images in the post list on the home page).

I'm assuming you would be interested in adding multiple featured images in your post, and display those featured images in a slideshow block. I'm afraid that's not something that's possible with WordPress today. You have 2 potential work-arounds:

- You could manually add the slideshow block to each post where you want to use it.
- You could change the default block added to the beginning of each post in the editor, like so:

```php
add_action(
	'init',
	function () {
		$post_type_object = get_post_type_object( 'post' );
		$post_type_object->template = array(
			array( 'jetpack/slideshow' ),
		);
	}
);
```

This is possible thanks to [the Block templates API](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-templates/).
You can add that code to your site using a functionality plugin, as explained [https://jetpack.com/support/adding-code-snippets/](here).

**Comment by Atalanttore** [comment]
As a workaround, I add the `Slideshow` block manually to each post.
