### ISSUE TITLE
Comments: HTML appearing in comment body

### ISSUE THREAD

**Issue by sajmes** [Automattic/jetpack#37588]
Done means:
- [ ] "Sent from my iPhone" and associated html is stripped from comment bodies when replying by email

### Impacted plugin

Jetpack

### Quick summary

Comments submitted on user's site are including plain text HTML. This is happening across multiple commenters so does not appear to be user error.

We cannot find instances beyond this one site, and cannot replicate outside of this site. 

Example post: https://roseandtedsexcellentadventure.com/2024/05/26/episode-524-packing-for-italy-in-june/

```
 <

div dir=”ltr”>

<

blockquote type=”cite”>
```

Slack discussion: p1716841339271349-slack-C02T4NVL4JJ
Interaction: 8235598-zd-a8c

### Steps to reproduce

Not replicable. 

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by jeherve** [comment]
@Automattic/vertex Could you take a look at this? Thank you!

**Comment by jamiepalatnik** [comment]
Came across this and remembered a site with the same issue: 8224385-zd-a8c

I was not able to replicate in my own tests though.

**Comment by lsl** [comment]
New to this feature but I think it's this async job: fbhepr%2Skers%2Sjcpbz%2Snflap%2Qwbof%2Svapyhqrf%2Srznvy%2Qpbzzrag%2Qercyl.cuc%3Se%3Q4374ppo4%23285-og

I'm not sure how to replicate this yet, I'm guessing there is something somewhere to enable this feature?

Going by the stats linked here p76FSM-27-p2#comment-124 I suspect it's the right one.

Bit of a guess but I'm wondering if the mime type detection is failing for these messages so we're skipping the strip tags call and only escaping?

We may want to update `strip_email_signature` to work on "Sent from my iPhone" ([example from google](https://mtl.mit.edu/pipermail/labnetwork/attachments/20201205/cd19e0bc/attachment.html))

```
<div><br>
<div dir="ltr">Sent from my iPhone</div>
<div dir="ltr"><br> 
```

Looking at the code it might be best if our next steps are to move the offending code out of the job and get it under a unit test or two before moving ahead with any fixes.

Looking at google search results https://www.google.com/search?q=Sent+from+my+iPhone+%3C+div+dir%253D%22ltr%22%3E+%3C+blockquote+type%253D%22cite%22%3E tells me this is worth fixing.

**Comment by arcangelini** [comment]
We investigated this issue previously and ended up in the same spot. p1716841339271349-slack-C02T4NVL4JJ I guess we didn't close the loop here. The only way we were able to replicate this issue was by using third-party email apps like Mail or Outlook.

We were not familiar with the feature as well so we asked @Automattic/zap and @Automattic/apex to see if they could take a look at it.

**Comment by lsl** [comment]
Thanks for the background.

Where are the emails coming in? Are we able to pull a couple of the offending emails to create some tests around this?

Much appreciation if zap or apex can pick this up but otherwise I think we'll need to solve this.

**Comment by yansern** [comment]
Quickly looked into this and I could say that @Automattic/apex has never worked on `email-comment-reply.php` file before so we are unfamiliar with this area technically.

Just out of curiousity I was hoping the original email content was still retrievable to know what was the source content that transformed into this. Initially the `email_content` is kept in the database, but it is later removed after a period of time (likely through a clean up job). So it is best to debug this fast when the iron is hot.

Tip for future debuggers: You can look for the `comment_by_email` entry on the database by filtering by blog_id & comment_id to go faster.

**Comment by simison** [comment]
I don't think there's anyone really at Dotcom or Jetpack very familiar with email-to-comments feature technically; it's really old feature from decade ago. 🙃

**Comment by dsas** [comment]
I __think__ I've found out what the problem is. Firstly, it's not possible at present to get the email content of a successfully commented email - we blank it to save space (fbhepr%2Skers%2Sjcpbz%2Snflap%2Qwbof%2Svapyhqrf%2Srznvy%2Qpbzzrag%2Qercyl.cuc%3Se%3Q4374ppo4%23609-og)

However I've got what I assume is a potentially bad email decoded at this pb: 353f7-pb/#plain. It didn't post successfully because inserting the comment failed but for our purposes I think it's fine to use to help figure out what's going on.

If we look at how we get the `$mime_type` (fbhepr%2Skers%2Sjcpbz%2Snflap%2Qwbof%2Svapyhqrf%2Srznvy%2Qpbzzrag%2Qercyl.cuc%3Se%3Q4374ppo4%23243-og) we initially use `$email->ctype_secondary`, which in this case is `alternative`, we then check the different parts of the email to see if their `ctype_secondary` is set and then rather than using the `ctype_secondary` of that part if it set, we just keep on using the same value we had before.

Then because the $mime_type is `alternative` rather than `html`, we skip the strip tags call as @lsl suggested.

**Comment by dsas** [comment]
Filed D157315-code but haven't tested it myself yet.

I am surprised though, that this issue wasn't noisier. We do get quite a lot of emailed comment replies (see `comment_reply_via_email` MC stat)

**Comment by Robertght** [comment]
I encountered another case here and I wonder if there's any ETA for a fix yet. :)

**Comment by arcangelini** [comment]
Amazing find @dsas 

Thanks!

**Comment by dsas** [comment]
> I encountered another case here and I wonder if there's any ETA for a fix yet. :)

Fix deployed @Robertght
