### ISSUE TITLE
Edit CSS pulls entire Page content (with a custom image class) and saves over it

### ISSUE THREAD

**Issue by jekkilekki** [Automattic/jetpack#3784]
`Version 4.0.2`

#### What I expected

1. I added an image to a Page, giving it a custom CSS class of `circle`.
2. I enabled JetPack's Custom CSS and wanted to go in to create `.circle { border-radius: 50%; }`

#### What happened instead

1. When opening the custom CSS editor, JetPack pulled the entire Page's content (including HTML tags) from the Page with the image with the Custom CSS class.
2. Thinking that strange, I deleted all that code in the Custom CSS editor, and added in my custom CSS:  `.circle { border-radius: 50%; }`
3. I saved the stylesheet, and went to view the Page
4. The only thing now saved in the Page is the custom CSS as plaintext:  `.circle { border-radius: 50%; }`

#### Thoughts

It seems like a JetPack was trying to identify my custom classes from within my Page and load those into the custom editor for me to style. But, it loaded the entire Page content itself and replaced the Page content when I saved the stylesheet.

This is easy to fix - I just restore the backup of the Page, but this isn't the behavior I'm expecting (or used to) from this feature.

**Comment by jeherve** [comment]
> When opening the custom CSS editor, JetPack pulled the entire Page's content (including HTML tags) from the Page with the image with the Custom CSS class.

I'm not sure how that could happen, and I wasn't able to reproduce. Custom CSS and Pages are 2 different post types, and aren't related in any way. I've tried multiple ways to go from the page editor to the custom CSS editor, either before publishing my page or after publishing the page, and I could never get the Custom CSS editor to load content from a page or a post.

Could you walk me through the exact steps you follow to reproduce the problem?
Could you also let me know what other plugins are currently active on your site? What happens when you deactivate all plugins but Jetpack? Do you still experience the issue?

Thanks!

**Comment by jekkilekki** [comment]
Aha. Found the issue.

I also have WP VIP's Babble Plugin installed. THAT'S what was pulling the Post into the Custom CSS editor. When I Deactivated that, everything was fine. Sorry for the false alarm. But it looks like the Babble plugin could use some love. I'll report this issue over there.

**Comment by jeherve** [comment]
That's interesting!

You can open a new issue [here](https://github.com/Automattic/babble/issues/new), the Babble devs will take a look!

Thank you!
