### ISSUE TITLE
Enhancement: JetPack Portfolio Clients taxonomy (or second author?) to enable an Archive Page for that Client

### ISSUE THREAD

**Issue by jekkilekki** [Automattic/jetpack#3792]
It would be nice to add either a custom taxonomy or something like a new (second) author box to JetPack Portfolios that could be used to specify the Client who commissioned the project.

I would love to be able to have an archive page for Projects that would behave similarly to the author archive and display all Projects with that Client's name and some information about that client (either in the form of a taxonomy description - with optional image, or with a kind of "author box" but for a Client).

**Comment by jeherve** [comment]
Thanks for the feedback!

While I like the idea, I'm not sure it applies to most Jetpack users. That might be something that is best implemented in a custom plugin for your own needs, instead of implementing this in Jetpack itself. You can create your own custom taxonomy and assign it to the `jetpack-portfolio` post type.

I'll close this issue as `wontfix`, but we can consider opening it again if the feature is requested by other Jetpack users, and if that seems like something that would benefit everyone.

**Comment by jekkilekki** [comment]
Yes, I guess you're right. Thanks for the consideration though!~ Will work on my own customization then.
