### ISSUE TITLE
Remove SiteEditorSnackbars

### ISSUE THREAD

**Issue by richtabor** [Automattic/jetpack#38442]
It's confusing that these come from Jetpack, and also these snackbars do not offer any additional benefit from what core does in the editor header( defining what template is currently being edited, when you're editing a template). 

It's just additional UI without any benefit (something WordPress as a whole needs to level-up on). 

On top of that, the snackbar is inaccurate: rendering "Editing the Pages template" when editing a page's content in the Site Editor, and a few other inconsistencies that aid in making navigating the Site Editor more confusing (with Jetpack active). 

I propose we remove these snackbars. One less thing to maintain, and a bit clearer experience for users. 

### Visual 

https://github.com/user-attachments/assets/af3a0e8f-7fe2-42ec-aac0-c532b23de8be

### Code 

https://github.com/Automattic/jetpack/blob/a87dd0c93706d06f0caecea521642dfffa77b56a/projects/plugins/jetpack/extensions/plugins/site-editor-snackbars/index.js#L5

**Comment by jeherve** [comment]
cc @mmtr  who added those in #28810. Is that snackbar still relevant today?

**Comment by mmtr** [comment]
> Is that snackbar still relevant today?

Probably not.

IIRC, they were only needed for the Link in Bio flow in WordPress.com because users trying to complete the "Add links" task from launchpad were not aware that they were actually editing a site template.
- The task sent users to the site editor directly with the "edit" mode active (i.e. they didn't select any template to edit)
- There was a "Customize your domain" nudge hiding the template title that appears at the top of editor.

With the snackbar, they had some context about what they were editing. The video below was recorded in Feb 2023:

https://user-images.githubusercontent.com/1233880/217796242-e222da7a-9cf2-4dba-9137-b1596db2498e.mov

Said that, it seems that the Link in Bio flow is quite differently today (July 2024):

- We no longer send users to the site editor in "edit" mode. We load the default "view" mode instead which requires users to explicitly select a template to edit first.
- The template title is no longer hidden by the "Customize your domain" nudge.

https://github.com/user-attachments/assets/6c890f13-689e-4efa-99b7-e2525675bf53

So I think it's fine if we remove these snackbars.

**Comment by richtabor** [comment]
Thanks for jumping on this. 🚀
