### ISSUE TITLE
Blog icon not used for LinkedIn sharing when Jetpack Daily Writing Prompt block is present in post

### ISSUE THREAD

**Issue by andreabadgley** [Automattic/jetpack#38501]
### Impacted plugin

Jetpack

### Quick summary

When I respond to the WordPress.com Daily Writing prompt at https://wordpress.com/home/andreabadgley.blog, and I do not add a featured image to my post, the OG Image that is shared on LinkedIn via publicize/sharing is a Gravatar from the Jetpack blogging prompt box that appears on my post. The consequence is that on LinkedIn, where I share my blog posts upon publication, random Gravatars of other people show up as the image for my post instead of my blog icon. I'm using the Resonar theme.

### Steps to reproduce

1. Start at https://wordpress.com/home/[blog address].
2. Click Post Answer in Daily Writing Prompt card.
3. Publish a blog post. Do not remove the Daily Writing Prompt block from the post. Do not include a featured image.
4. Share to LinkedIn.
5. Check LinkedIn post for image shared. 

### A clear and concise description of what you expected to happen.

I expected my blog icon to be shared on the LinkedIn post.

### What actually happened

A Gravatar from someone else who responded to the Daily Writing Prompt appears.

Sample blog post: https://andreabadgley.blog/2024/07/24/mortality-motivation/
Associated LinkedIn post: https://www.linkedin.com/feed/update/urn:li:activity:7221842995543744512/

<img width="555" alt="Gravatar from someone else; not my blog icon" src="https://github.com/user-attachments/assets/eb5e103a-f457-403f-b479-ecfab96d4e9e">

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to replicate it on a **Simple site**, and I'm seeing the following as the `og:image`: 
```
<meta property="og:image" content="https://2.gravatar.com/avatar/5847502f81991519065956177aa6b714e2aacb12c49993c933cddfab2529a676?s=96&#038;d=identicon&#038;r=G" />
```
And this Gravatar image is also displayed on Twitter: 

![Markup on 2024-07-24 at 17:14:00](https://github.com/user-attachments/assets/3b1f66b8-ca4a-4770-ba7e-0aac28ff180c)

I'm not able to reproduce it on **Atomic**, where the `og:image` tag has the following: 
```
<meta property="og:image" content="https://s0.wp.com/i/blank.jpg" />
```

📌 ACTIONS
- Triaged

@jeherve can you please take a look at this one? Thanks 🙇🏻

**Comment by jeherve** [comment]
This is happening because when looking for relevant images in a post, we also look for any images that can be found in the body of the post when no other image can be found as the featured image, or as an attachment. Those gravatars are consequently the only images found for that post. 

On self-hosted sites, we choose to ignore those images because they are too small to be used as image previews on other platforms. On WordPress.com sites, however, we do keep those images so they can be used by some legacy themes to display post thumbnails in post grid views.

Relevant code:
https://github.com/Automattic/jetpack/blob/1e225a3927c8a2b2aea73d69dc403bd86a67ca77/projects/plugins/jetpack/class.jetpack-post-images.php#L558-L562
fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Sjcpbz%2Qzrqvn.cuc%3Se%3Q66s14s2s%231084-og

Relevant issue: 8081-wpcom

I'm not immediately sure how to proceed on this issue. We must continue to take small images into account on WordPress.com Simple. I'm thinking we may be able to add an exception so small images are acceptable, but small images that are gravatars are not.

**Comment by jeherve** [comment]
@spsiddarthan What do you think about this, and about my proposed solution?

**Comment by kriskarkoski** [comment]
Could we have a default or fallback such as the site logo or header image rather than considering Gravatars at all?

**Comment by spsiddarthan** [comment]
>We must continue to take small images into account on WordPress.com Simple. I'm thinking we may be able to add an exception so small images are acceptable, but small images that are gravatars are not.


Thanks for the ping, Jeremy!  That seems to be the way to go to address gravatars appearing as the og:image. 

>Could we have a default or fallback such as the site logo or header image rather than considering Gravatars at all?

This would also be good to do, if there is no other image found.

**Comment by jeherve** [comment]
> Could we have a default or fallback such as the site logo or header image

We have that set up already, but it only happens if no images can be found in the post content.

> That seems to be the way to go to address gravatars appearing as the og:image.

@spsiddarthan I created #38692 for that, if you want to take a look. Thank you!

**Comment by spsiddarthan** [comment]
Thanks @jeherve! I just tested and approved your PR.
