### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by anton06712345** [Automattic/jetpack#38543]
### Impacted plugin

Super Cache

### Quick summary

I'm reading an error message
![error](https://github.com/user-attachments/assets/d42e2c25-ce27-45b4-8f50-d0c5d4289a05)

### Steps to reproduce

I click on the plugin settings

### A clear and concise description of what you expected to happen.

I hope you can fix the problem

### What actually happened

I enter in the plugin setting page and I get this message.

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by bizanimesh** [comment]
Hello there — it appears this is not an issue with the plugin. From the error message, it appears we can't find the `wp-content` directory. Could you please reach out to your hosting provider? They should be able to help you with this and find the root cause of the issue. Please ask them to make sure that read and write access permission is available for the `wp-content` directory.

Also, for further help, you can [open a topic here in the forum »](https://wordpress.org/support/plugin/wp-super-cache/#new-topic-0). :)
