### ISSUE TITLE
Jetpack Seo: doesn't support custom post types

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#38597]
### Impacted plugin

Jetpack

### Quick summary

Currently if you have a custom post type you can't use Jetpack SEO to save/update the post meta that need to show up the correct SEO data. 

This is due to the meta data now showing up in the editor after you save it. 

### Steps to reproduce

1.Activate jetpack seo. 

2. install a plugin that adds a new custom post type such as https://nl.wordpress.org/plugins/ultimate-faqs/ 
on the new FAQ post type editor. Notice that you are able to see the SEO settings but once you set them and save the document. they are removed. 

### A clear and concise description of what you expected to happen.

The seo setting for the custom post type should be persistant across saves. 

### What actually happened

The settings disapear after you save them as if you haven't saved them at all. 

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic, Self-hosted

### Logs or notes

This happends on the latest build of WP and Jetpack. 
Reported in https://wordpress.org/support/topic/seo-title-and-description-are-empty-but-are-active-on-the-page/

**Comment by chatoxz-wp** [comment]
I was able to replicate this on self-hosted ([Pressable site](https://jetpack-test-sc.mystagingwebsite.com/wp-admin/edit.php?post_type=ufaq)) and on Atomic  (https://testsitechatoxzbusiness.wpcomstaging.com/). The "SEO Description" and "SEO Title" are not saving their content when you publish or try to update.

**Comment by monsieur-z** [comment]
I haven't been able to figure this out yet. Here's what I've found while trying to troubleshoot it.

- I could confirm the issue happened with various custom post types (CPT) and not only the FAQ type (I wanted to double-check since the logs showed warnings related to the FAQ).
- The root of the issue is that the post meta is not saved for the custom post type. In my tests, the SEO title was not saved in the database.
- The API call to update the post is made. However, I noticed two differences between the custom post type and regular post type.
  - In the case of the CPT, the payload only contains the updated field
  - In the case of the CPT, two other HTTP calls to the post endpoint follows the initial API call

| Regular Post | Custom Post |
|-|-|
|<img width="400" src="https://github.com/user-attachments/assets/4fb5c2c2-0fe4-4567-87c3-a28e75226f10" alt="" />|<img  width="400" src="https://github.com/user-attachments/assets/b60c6ede-45a2-48b8-b72a-1b79eac859c8" alt="" />|

I don't know what to do with that information, though. Looking at the code of the SEO module, I didn't notice anything that might indicate an issue.

Pinging @Automattic/jetpack-vulcan in case someone has an idea.

**Comment by jeherve** [comment]
I wonder if it may be worth testing using `register_rest_field` instead of `register_meta` to save those values:
https://github.com/Automattic/jetpack/blob/77cb43ad1d0042d49b793b4298297e9dd674a484/projects/plugins/jetpack/modules/seo-tools/class-jetpack-seo-posts.php#L177-L179

Reference: https://developer.wordpress.org/rest-api/extending-the-rest-api/modifying-responses/#using-register_rest_field-vs-register_meta

**Comment by monsieur-z** [comment]
Thanks for the advice @jeherve. It didn't seem to make any difference, though.
