### ISSUE TITLE
Super Cache PHP error

### ISSUE THREAD

**Issue by johns260p** [Automattic/jetpack#38797]
### Impacted plugin

Super Cache

### Quick summary

Installed WP Super Cache 1.12.4 on a server running PHP 7.4.33
Once activated loading the settings page causes a PHP error for using an undefined function str_contains() in line 2333 of the file wp-cache.php
It seems that function was introduced in PHP 8
Since the requirements for the Super Cache plugin 1.12 still state compatibility with PHP 7.0 or higher I expected the plugin to run fine on this server.  I had been running V 1.11 with no problem until now.

### Steps to reproduce

1. Activate WP Super Cache on server running PHP 7
2. load WP Super Cache settings page

### A clear and concise description of what you expected to happen.

The cache settings page should have loaded

### What actually happened

PHP error was generated and page does not load

### Impact

All

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by BogdanUngureanu** [comment]
Hi @johns260p! Which version of WordPress are you running? As of WordPress 5.9, the core comes bundled with polyfills for PHP 8 functions.

**Comment by johns260p** [comment]
The site is running an older version of WordPress - 5.7.9

However, even the latest v6.6.1 release of WordPress only requires PHP v7.4
or later (actually just recommends that but the requirements page states
that it will work on PHP 7.2.24 even though that is EOL)

Given that WordPress is fine with PHP 7.4 I think the plugins should work
with that as well.

Jeff

**Comment by jeherve** [comment]
> The site is running an older version of WordPress - 5.7.9

That seems to be the problem here. WP Super Cache requires version 6.5 or higher, as you can see on the plugin's page:
https://wordpress.org/plugins/wp-super-cache/

If you were to update to a more recent version of WordPress, you would be able to use WP Super Cache, even if you use an older version of PHP. As @BogdanUngureanu mentioned above, as of WordPress 5.9 WordPress itself comes bundled with polyfills for functions that were introduced in PHP 8, and that consequently would not be immediately available on your server running PHP 7.4.

Could you try updating to WordPress version 6.5 or higher, and let us know how that goes?

**Comment by johns260p** [comment]
I understand.

Unfortunately the site where I got this issue is an old site that is stuck
at the current version of WP. I was just hoping to use the SuperCache to
make the site mostly static until it is decommissioned. I hadn’t noticed
the requirement for WP 6.5 and had used a recent version (1.11) on another
site without issue and when the PHP error popped up with v1.12 I just went
down the PHP path without considering the WP version.

I think that there would be no issue on a site with the required WordPress
version so I think you can just close this bug report.

Thanks, and sorry for the trouble,
Jeff
