### ISSUE TITLE
VideoPress: Update notice for disabled VideoPress module to show Enable instead of Connect

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#39066]
In the main Jetpack plugin, when the module is disabled, we shoow a prompt to enable the module, but the button reads Connect

<img width="705" alt="image" src="https://github.com/user-attachments/assets/51baaea2-7cd7-4a94-bfdf-231ebe23eeab">

Example showing an attempt to transform a VideoPress embed, to a VideoPress block

https://github.com/user-attachments/assets/885a1e6e-3b49-4c5e-8cc2-a3671e1583f2

**Comment by phcp** [comment]
I was working on a quick fix for this, but I noticed that this issue is being addressed by [this PR](https://github.com/Automattic/jetpack/pull/39628). I'll close this as duplicate since the [original issue](https://github.com/Automattic/jetpack-marketing/issues/1025) related to this PR already covers it.

**Comment by CodeyGuyDylan** [comment]
@phcp FYI I also wrote about improving the flow of this connect/activation banner [here](https://jetpackmarketingp2.wordpress.com/2024/09/20/ux-audit-improved-nudges-for-features-requiring-user-connection/#comment-23858) 😄

**Comment by CodeyGuyDylan** [comment]
@phcp FYI I also wrote about some ways the connection/activation flow could be improved here (pbNhbs-bHl-p2#comment-23858) 😄
