### ISSUE TITLE
Contact Form makes "Block Inserter" disappear in Firefox

### ISSUE THREAD

**Issue by sergeymitr** [Automattic/jetpack#39144]
### Impacted plugin

Jetpack

### Quick summary

When you search for the "Contact Form" block in the "Block Inserter" while editing a post, "Block Inserter" disappears.

### Steps to reproduce

1. Create new JN site
2. Connect Jetpack
3. Use Firefox to create new post.
4. Try to use the "Block insterter" (the "+" icon) to add Contact Form block.
5. The block inserter will disappear as soon as that block's icon shows up.

### A clear and concise description of what you expected to happen.

Block Inserter stays open and allows for Contact Form to be added to the post.

### What actually happened

Block Inserter disappears.

### Impact

All

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

Typing `/contact` in the post content allows adding the Contact Form block without using the Block Inserter.

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

Browser: Only fresh versions of Firefox are affected (~128.0.3 and above).
Jetpack version: 13.6 and above.

https://github.com/user-attachments/assets/2f81aa70-ee08-4ad8-8337-932d7bfab235

**Comment by monsieur-z** [comment]
@dhasilva, pinging you because the root of the issue seems to be [this line of code](https://github.com/Automattic/jetpack/pull/37386/files#diff-75e6a34584392dbce5186fb1b565b3bc098000fe9c8f44afc583daf3a682dd40R40) in the `ai-assistant` extension.

To add to the description, I've been able to reproduce the issue either by typing something in the block inserter search input or hovering a _Forms_ related block (_Form_, _Contact Form_, _Name Field_, etc.) with the mouse cursor. The exact trigger may vary depending on the browser version, but we've been able to replicate the issue with Firefox versions at least back to 127. We didn't notice any issues with the block inserter on Chrome, though.

The last Jetpack version in which the block inserter was stable in FF was 13.5, so the issue was introduced in 13.6. Locally, both with the `plugins/jetpack@13.6` tag and `trunk` branch, commenting the line mentioned above fixes the issue. Do you have any takes on why that might be the case?

**Comment by dhasilva** [comment]
> Do you have any takes on why that might be the case?

Not yet. IIRC the block inserter does not throw any error, so it will require some trial and error to identify exactly what the issue is with the block extension. I'll do that soon and post an update here when I find out what is happening.

**Comment by dhasilva** [comment]
I was able to reproduce it. My guess at this moment is that we are auto-focusing on the AI input, and when that happens inside the preview block it causes this unexpected behavior most times.

**Comment by dhasilva** [comment]
Should be fixed by the PR above. My guess was right there, it was an autofocus issue.
