### ISSUE TITLE
Newsletter "Welcome email settings" are not displaying in welcome emails

### ISSUE THREAD

**Issue by ClassicRKR27** [Automattic/jetpack#39232]
### Impacted plugin

Jetpack

### Quick summary

When setting up a custom welcome message for the newsletter, the default message is sent instead with no customizations.

### Steps to reproduce

1. Set up the newsletter form
2. Go to `Jetpack > Settings > Newsletter` and set up a `Welcome email message`
3. Try to sign up with any email

### A clear and concise description of what you expected to happen.

I expected to see the welcome message either immediately or in the email that I received to confirm my subscription.

### What actually happened

The custom message does not appear anywhere.

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

This is the ticket where I discovered the issue: 8689059-zd-a8c

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated (settings are located on `Settings > Newsletter`
- Tested on Atomic – Replicated 

📌 FINDINGS/SCREENSHOTS/VIDEO
This is the email content received when subscribing to a simple and atomic site: 

![Markup on 2024-09-04 at 16:35:25](https://github.com/user-attachments/assets/da2c3be5-b086-4721-aa54-8f142c3645fc)


📌 ACTIONS
- Triaged

**Comment by heavyweight** [comment]
@ClassicRKR27 and @jartes I tested this on my atomic site and its working as expected.
I think there is a misunderstanding on how this functionality works.
The welcome email is a different email sent out once the subscription is confirmed.
Once I confirmed the subscription email I received the welcome email.

I tested there both cases with and without having welcome message set. If the welcome message is set that will be part of the welcome email otherwise it will be the default welcome message. Can you confirm this?

**Comment by obenland** [comment]
Closing as not planned for now. 

@ClassicRKR27 @jartes Could you double check that the custom welcome message gets send once the subscription is confirmed? Feel free to re-open if that is not the case, ideally with a screen recording of what's going on.

@heavyweight In the future, feel free to close an issue when it can't be reproduced, we can always re-open.
