### ISSUE TITLE
Boost: Fix cache e2e test

### ISSUE THREAD

**Issue by haqadn** [Automattic/jetpack#39348]
The cache e2e test is failing because the wp-config.php file is not writable.

http://a8c-jetpack-e2e-reports.s3-website-us-east-1.amazonaws.com/reports/38585/report/#testresult/af8af1c2597d1b87

p1726003003837479-slack-C016BBAFHHS

**Comment by oskosk** [comment]
@ice9js mind checking this?

**Comment by anomiex** [comment]
It's not clear to me why it sometimes passes in this situation, e.g. in http://a8c-jetpack-e2e-reports.s3-website-us-east-1.amazonaws.com/reports/39332/report/#suites/2808bc793c74415478163cb4efdcb2f4/fb9937a80b7d10a2/ it failed on one run but passed on others.

In my local dev env I was able to reproduce a similar failure to enable the feature. Turns out that the wp-config file itself was writable, but the directory it's in was not so Boost's code was unable to write a temporary file to rename over wp-config. The error messaging and documentation don't seem to have considered this failure mode. I don't know for sure whether the E2E environment is running into this same thing though.

I also noted that Boost here isn't using WP_Filesystem, which would probably make it more reliable in general (although I don't know if it would actually help for the E2E environment).

**Comment by donnchawp** [comment]
Thanks @anomiex. We didn't use WP_Filesystem for the caching part of the plugin, but perhaps we should use it for wp-config.php because we're not depending on it to be fast. The public_html directory is probably owned by the account that set up the server too.

On my local dev system I noticed that cache files were sometimes created by root, sometimes by the webserver. I wonder if something similar is happening here when it passes? Using WP_Filesystem might make this more predictable.

I couldn't figure out why the web server was running as root, creating cache files, but only sometimes.

**Comment by anomiex** [comment]
I'd think the root-owned files are created by something running wp-cli while webserver-owned files are created by things run by the webserver.

That doesn't help with explaining how it sometimes passes though. 🤔
