### ISSUE TITLE
Slideshow block has duplicated caption in the Editor for sites with FSE themes.

### ISSUE THREAD

**Issue by nazilya06** [Automattic/jetpack#39459]
### Impacted plugin

Jetpack

### Quick summary

When the Slideshow block images include captions, they appear duplicated in the Editor. However, they display correctly in the preview. 

**Editor:**
<img width="1049" alt="Screenshot 2024-09-19 at 3 00 53 PM" src="https://github.com/user-attachments/assets/9afdb07d-bcf4-4b1e-8abd-c33d1951f70e">

**Preview:**
<img width="1151" alt="Screenshot 2024-09-19 at 3 02 29 PM" src="https://github.com/user-attachments/assets/f9416e39-5132-4626-a801-289f8366da8f"> 

### Steps to reproduce

1. Make sure your site is using the FSE theme. 
2. Add a Slideshow block
3. Add captions to the image

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### If the above answer is "Yes...", outline the workaround.

For atomic sites, I found that deactivating the Gutenberg plugin fixes it.

### Logs or notes

8751655-zd-a8c

**Comment by anomiex** [comment]
Looks like what's going on here is that the `swiper` library [is loaded asynchronously](https://github.com/Automattic/jetpack/blob/202fec8cce3bc6533d99c502e6721ab9eef7d4d1/projects/plugins/jetpack/extensions/blocks/slideshow/create-swiper.js#L38-L41). Webpack's async loader doesn't know anything about Gutenberg's iframe editor, so `swiper.css` is only async-loaded at the top level, not in the iframe.

Disabling the Gutenberg plugin seems to also turn off the iframe editor, so the top-level-loaded `swiper.css` takes effect there.

Looks like the Map block has a hack to work around this (see #19552). Podcast Player is doing something seemingly similar (see #19578), but I think that one is more along the lines of needing to use the 'enqueue_block_assets' hook (now that it exists) rather than async loading from webpack.

**Comment by anomiex** [comment]
Looking at options, I wonder if we could make use of [mini-css-extract-plugin's `import` option](https://github.com/webpack-contrib/mini-css-extract-plugin?tab=readme-ov-file#insert) to have it automatically load the styles inside Gutenberg's iframe when the iframe is present.

**Comment by jartes** [comment]
📌 ACTIONS
- Triaged
