### ISSUE TITLE
Blocks: Related Posts block displayed wrong on Page templates

### ISSUE THREAD

**Issue by alinclamba** [Automattic/jetpack#39720]
### Impacted plugin

Jetpack

### Quick summary

The Related Posts block is missing styles on Page templates after the latest Jetpack update. It still works as expected on Single post templates. On Pages, the Related Posts are displayed as a simple vertical list, while on Posts, they are correctly shown in a three-column layout, as intended. 
This was reported by a user here: https://wordpress.org/support/topic/related-posts-block-on-page-template-broken-style-since-last-update/

### Steps to reproduce

1. Add a Related Posts block to both a Single post template and a Page template.
2. Publish the templates and view them on the front end.
3. Notice that the block is styled correctly in a three-column layout on Single posts, but displays as a simple list on Pages.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by anomiex** [comment]
Looks like it accidentally worked before due to the style imploding, and broke when #39486 turned it off. cc @kraftbj @sergeymitr 

The real problem is that the styles and scripts only get enqueued on posts, specifically
https://github.com/Automattic/jetpack/blob/702274e92c58cef8ccbc4996044be3bbc0a25f2d/projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php#L1889-L1906
while the block itself gets rendered regardless.

Something like this might work for a fix:
* Change `Jetpack_RelatedPosts::render_block()` to return empty-string when that `::enabled_for_request()` returns false, so the block doesn't render when the scripts aren't enqueued.
* Expand the check in `::enabled_for_request()` to allow pages and whatever else the block should work on.

Looks like the 'jetpack_relatedposts_filter_enabled_for_request' filter could be used as a workaround.

**Comment by kraftbj** [comment]
I'll put in a patch to allow it to be enqueued on pages as well. My understanding is the RP system will still kick out related posts on pages so let's continue to support that.
