### ISSUE TITLE
Top posts limited to 10 days

### ISSUE THREAD

**Issue by ryanhellyer** [Automattic/jetpack#3977]
I expected the top posts to be able to pull in data from the past week, month and year.

But instead there is a block in place which prevents it going past 10 days
https://github.com/Automattic/jetpack/blob/master/modules/widgets/top-posts.php#L467

Interestingly, the API is able to access the extended data. I tested this by simply removing line 467 from the modules/widgets/top-posts.php file.

If there is no reason for this to be the case, then I'll happily submit a pull request to remove this limitation or a filter to modify the maximum number of days.

**Comment by jeherve** [comment]
We indeed added this in to avoid performance issues when querying for a really long time frame.

Instead of removing this limitation, it might be best to move the existing filter, `jetpack_top_posts_days`, after we set a maximum number of days. However, if we do so, we'll also need to edit the filter description to mention that one needs to be mindful of the impact the number of days can have on the speed of the query.
We could also add that querying for `-1` days runs a query for an unlimited number of days.

**Comment by ryanhellyer** [comment]
I'm not sure that makes much sense unfortunately, as the number of days are actually set via the filter. So moving the limitation before that would just make the limitation redundant.

Perhaps the limitation should be removed, and we just add documentation outlining that it is important not to go above 10 unless it's absolutely necessary?

We could also provide advice in the inline doc on caching the results due to queries taking too long.

**Comment by jeherve** [comment]
Yeah, you're probably right. Might as well remove it altogether.

> we just add documentation outlining that it is important not to go above 10 unless it's absolutely necessary?

Yes, that's what I had in mind as well.

> We could also provide advice in the inline doc on caching the results due to queries taking too long.

👍
