### ISSUE TITLE
My Jetpack / Manage: upsell banner is displayed even for sites connected to an agency

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#40226]
### Impacted plugin

Jetpack

### Quick summary

This banner (displayed in My Jetpack) should not be displayed when a site is connected to an agency:

![Image](https://github.com/user-attachments/assets/19c41a03-7d3d-4f04-b024-cb905ec94304)

### Steps to reproduce

1. Start with a WordPress.com account set up as an agency partner
2. Connect your test site to your WordPress.com account
3. Go to Jetpack > My Jetpack and scroll to the bottom of the page.

-> You'll see the banner above ; you shouldn't see that.

### Impact

Some (< 50%)

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

Internal reference: p1HpG7-uVU-p2

**Comment by jeherve** [comment]
Upon looking a bit more, I see that we recently updated the banner in #37248. It previously displayed different CTAs when you were registered as an agency:

![Image](https://github.com/user-attachments/assets/cac59c18-7ea8-4a52-ad1f-e30e3d30f7ed)

@jeffgolenski @elliottprogrammer Should we bring this back, or completely hide the banner instead?

**Comment by keoshi** [comment]
@jeherve My two cents is that the banner can be removed because:

- Chances are agencies already know where they're supposed to manage sites. For A4A that's agencies.automattic.com, for Jetpack it's cloud.jetpack.com.
- As highlighted by Ryan, agencies don't want their customers to see this banner and be confused about the verbiage or the actions.

**Comment by jeherve** [comment]
👍 I removed the banner for agency customers in #40251.
