### ISSUE TITLE
Form Block: AI input field appears when Contact Form module is inactive

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#40332]
### Impacted plugin

Jetpack

### Quick summary

When the Contact Form module is not active, we display a placeholder instead of the block controls in the block editor. Jetpack's AI Assistant input field is displayed below that placeholder, even though the AI Assistant cannot help you with the feature when the module is not active.

### Steps to reproduce

1. Go to Jetpack > Settings > Modules
2. Deactivate the Contact Form feature
3. Go to Posts > Add New
4. Type `/contact` and insert a contact form block

### A clear and concise description of what you expected to happen.

At this point I would expect to see the invitation to activate the form feature, and nothing else.

### What actually happened

Instead I see the placeholder, as well as the AI assistant input field:

![Image](https://github.com/user-attachments/assets/343071cf-cc91-4e7a-961e-9bd87091377e)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

You can solve the issue by activating the contact form module.

### Platform (Simple and/or Atomic)

Atomic, Self-hosted

**Comment by jeherve** [comment]
I'm not quite sure what should be the best way to work around that problem. Should we introduce the concept of module status (as made available in `@automattic/jetpack-shared-extension-utils`) to the `blockEditWithAiComponents` HOC?

@Automattic/jetpack-agora What would be your take on this?

**Comment by CGastrell** [comment]
> I'm not quite sure what should be the best way to work around that problem. Should we introduce the concept of module status (as made available in `@automattic/jetpack-shared-extension-utils`) to the `blockEditWithAiComponents` HOC?
> 
> [@Automattic/jetpack-agora](https://github.com/orgs/Automattic/teams/jetpack-agora) What would be your take on this?

I'd say that would be the way. Let me give it a try and I'll get back to you.

**Comment by CGastrell** [comment]
@jeherve for what I see shared-extension-utils can grab a module status and we could introduce that through a mapper of module => blocks somewhere in `extensions/blocks/ai-assistant/extensions/lib/is-possible-to-extend-block.ts`.

That said, we've always used the initial state as a source of truth for what is enabled and what's not. I wonder if the above solution should be impacting on `available_blocks` on our initial state instead of an _ad hoc_ solution for the AI extensions.

I mean, the true contradiction here is that `available_blocks['contact-form'].available` is `true` while the module is disabled, isn't it? Or am I misunderstanding the relation between module and available blocks?

EDIT: if we're happy with the check, I prepared #40336 so we can have a closer look at it

**Comment by jeherve** [comment]
> the true contradiction here is that `available_blocks['contact-form'].available` is `true` while the module is disabled, isn't it?

Yeah, this is because we want the block to be available, but in practice it will only be a placeholder with an invitation to turn on the module.
