### ISSUE TITLE
Admin Page: Sidebar nav changes

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/jetpack#4049]
In @jeffgolenski's original designs we had proposed removing all sidebar nav items. 

We need to decide whether we're making any changes there, in particular:
- Do we keep/remove stats, settings, and omnisearch?
- Do we keep akismet and vaultpress?
- Do we add anything? (eg links to manage, pro, tabs?)

**Comment by jeffgolenski** [comment]
* My original mockups had an empty sidebar area, but I didn't actively propose eliminating everything. 

I think we'll need to keep Akismet because we aren't currently actively linking to it in the jetpack dashboard UI. But for things like "manage, pro, etc" those are all a part of the main UI navigation, so having them as sidebar items is pretty redundant.

**Comment by MichaelArestad** [comment]
Let's remove everything from the subnav.
I would like to keep VP and Akismet top level. They will be easier to find and also be a couple more A8c brands hanging out.

**Comment by richardmuscat** [comment]
So we're saying that the side nav will have:
- akismet (if installed)
- vaultpress (if installed)

And the side nav will lose:
- omnisearch
- stats
- settings

**Comment by MichaelArestad** [comment]
Well, kind of. I was proposing Akismet and VP be moved to top level items and not JP subnav items.

**Comment by richardmuscat** [comment]
Closing this as being tackled here: https://github.com/Automattic/jetpack/issues/4019#issuecomment-226249448
