### ISSUE TITLE
Admin page: New Support Docs

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/jetpack#4050]
New Jetpack will require a significant update of many of our support pages. Because of the massive UI changes pretty much all UI-related instructions as well as screenshots will quickly become outdated.

A few decisions need to be taken and a lot of work needs to be done, including:
- [ ] Decide whether we're _replacing_ support content or _adding_ to it (ie: have instructions for old and new versions) 
- [ ] Create a hit list of all pages that will require updating and break down by content as well as screens
- [ ] Create a list of new pages that may need to be created
- [ ] Do it :-)

**Comment by jeherve** [comment]
> Decide whether we're replacing support content or adding to it (ie: have instructions for old and new versions)

I think we should replace support content. We encourage all users to use the latest version of Jetpack, and I think our support docs should do the same.

> pretty much all UI-related instructions as well as screenshots will quickly become outdated.

I don't think we'll actually need to update that many pages right away, since very few pages include screenshots or even mention the current Jetpack menu right now.

Since the current individual module settings remain available, nothing will change for the users. We can of course slowly update all docs and start referring to the settings under the Jetpack menu instead of in other dashboard pages, but none of this is a blocker for 4.1 I think. We only have a few pages that actually *have to* be updated before 4.1 hits the shelves.

**Comment by RCowles** [comment]
> I think we should replace support content. We encourage all users to use the latest version of Jetpack, and I think our support docs should do the same.

Agreed. In addition to that, if we _add_ instead of _replace_, that means we'll have similar/duplicate content that will need to be kept up to date in multiple places. Let's be deliberate and keep it simple.

> I don't think we'll actually need to update that many pages right away, since very few pages include screenshots or even mention the current Jetpack menu right now.

Agreed here as well. Step one would be compiling a list of documents that will need to be updated prior to release. Once we have the list, we can see just how much work will be required, and then divide-and-conquer if deemed necessary.

@jeherve I believe we briefly discussed this before - do you have bandwidth available to start compiling a list?

**Comment by jeherve** [comment]
> do you have bandwidth available to start compiling a list?

Yep, I already started working on that.

**Comment by richardmuscat** [comment]
> Since the current individual module settings remain available, nothing will change for the users.

I'm not sure you're correct there @jeherve . The settings for the majority of the features will be directly embedded in the cards and will look very different to how they look now.

**Comment by jeherve** [comment]
> The settings for the majority of the features will be directly embedded in the cards

That's true, but I don't think we'll remove the older settings from each individual page.

If we do, I didn't know about it, and it doesn't seem like anyone has worked on that yet. That would also make things quite messy for WordPress.com merges. Last but not least, I don't think that'd be a great idea for a lot of our users:
- Existing users who learnt about specific settings will lose them from one day to the next;
- Some of these users might not know that the settings are actually added by Jetpack; they have always sen that option there, because they've always used Jetpack, and assume it's a core WP feature. Once we remove it, they will never know where to look for its new location.
- WordPress.com users used to the old wp-admin on WordPress.com will also be confused.

**Comment by richardmuscat** [comment]
> That's true, but I don't think we'll remove the older settings from each individual page.

@jeherve we won't remove them but in many cases they won't be accessible unless the user has already a direct link to the settings page. For example, where previously a user would configure Protect settings by visiting a URL of the form `my-site.com/wp-admin/admin.php?page=jetpack&configure=protect, in the new version these settings will be embedded in the foldable card and there will _not_ be a link to this old page.

The notable exceptions are:
- Publicize and Sharing Tools (we will link to old wp-admin settings)
- Custom CSS (and a couple others which escape me right now) where we link them to the specific wp-admin UI to actually use the feature

**Comment by jeherve** [comment]
Sure. We'll definitely update those screenshots in 4.1. Modules like Protect, Monitor, Minileven, or Manage are the exception, though :)

Most of our modules' settings (like Comments, Subscriptions, Sharing, Likes, Markdown, Contact Forms, Tiled Galleries, Carousel, Post By Email, Spellchecking, Custom CSS) are embedded in existing core dashboard pages, and that won't change any time soon (or at least it was my understanding that it won't). While these settings will now be available in the new Jetpack interface as well, they will remain available in their old location.

**Comment by richardmuscat** [comment]
Ok but won't we want to update them to reflect the new ui at some point?

(Sorry, I'm not trying to create work! I'm just trying to avoid surprises :-) )

**Comment by jeherve** [comment]
I think we're on the same page :) We should update them to reflect the new UI. I just don't think it should be a blocker for 4.2, as I mentioned [in my first reply](https://github.com/Automattic/jetpack/issues/4050#issuecomment-223267228). We will be able to update all those screenshots slowly, as we stumble across them.

**Comment by RCowles** [comment]
@jeherve I just wanted to checkin - how is the plan coming along for doc updates? Anything you need a hand with?

**Comment by jeherve** [comment]
@RCowles I think I'll post on the P2 when time comes, if needed!

**Comment by RCowles** [comment]
Sounds good! Thanks again for taking point on this.
