### ISSUE TITLE
Holiday snow causes jitter/shake on sites with ar/Arabic language

### ISSUE THREAD

**Issue by philnick206** [Automattic/jetpack#40569]
### Impacted plugin

Jetpack

### Quick summary

Activating holiday snow on a site with "ar" set as the site language will cause a jitter/shake to appear when viewing the site in a browser.

![Image](https://github.com/user-attachments/assets/8eca6a22-4c3c-423c-b029-98b527251e89)

### Steps to reproduce

1. Activate holiday snow on site
2. Ensure language is set to 'ar'
3. View site in a browser

### A clear and concise description of what you expected to happen.

Snow should be visible but nothing else

### What actually happened

Snow is visible but horizontal bars on browser flicker (even though there is no content off the page), screen can appear to shake

https://github.com/user-attachments/assets/04ef10f6-1640-41b4-b702-03616193be10

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

Tested on Twenty Twenty Four theme.
Reported in 9159191-zd-a8c

**Comment by Robertght** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated 
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated, but I don't see a screen shake, but a horizontal scroll that appears briefly from time to time.

📌 ACTIONS
- Triaged
- I lowered the priority to normal.

@jeherve I'm cc'ing you as I don't know who is the snow owner 😆

**Comment by jeherve** [comment]
I can reproduce, it happens with any RTL language. It would appear that the document width is bumped with the flakes, thus causing the horizontal scrollbar to come up.

This is something that would need to be fixed in the upstream library I'm afraid. I attempted to play with some of the customization options (namely `flakeLeftOffset` and `flakeRightOffset`, but no luck. I may try to play with this some more in the future, but realistically it may make more sense to switch to a different implementation entirely, possibly a CSS-only one.
