### ISSUE TITLE
Stats are not aligned to user's local time

### ISSUE THREAD

**Issue by dzver** [Automattic/jetpack#40591]
### Impacted plugin

Jetpack

### Quick summary

I got a report from Zendesk: 9153038-zen

A user reported that ever since daylight savings, the stats reset 1h before midnight. I've observed similar misalignments on my personal blog:

<img width="511" alt="Image" src="https://github.com/user-attachments/assets/4d94af8d-9d97-4614-9fbb-d310484df71f" />

It indicates I wrote two posts on that day and zero on the day before. In reality, from my point of view, I had one post each day:

<img width="401" alt="Image" src="https://github.com/user-attachments/assets/c0934f13-7b90-433e-838d-9f4bb9e9ad8b" />

### Steps to reproduce

- Post at 23-23:59 local time somewhere outside of GMT
- The post seems to be attached to the next day

There might be other ways to reproduce that, as what mentioned in the ticket

### A clear and concise description of what you expected to happen.

The stats should be consistent between different screens - either local time only, or GMT only.

### What actually happened

Inconsistency in stats. I see a post being posted on two different dates depending on where I click. It's particularly confusing if the timezone changes.

### Impact

Most (> 50%)

### Available workarounds?

There is no user impact

**Comment by Robertght** [comment]
I believe this is pretty much related to these three reports:

https://github.com/Automattic/wp-calypso/issues/16186 > https://github.com/Automattic/wp-calypso/issues/76912

https://github.com/Automattic/wp-calypso/issues/47000
https://github.com/Automattic/jetpack/issues/28557

@jeherve since I don't have a way to force the steps to replicate this issue, could you also double check to see if it's the same as 76912 please?

**Comment by jeherve** [comment]
Yep, looks like the same issue. I'll close this issue in favor of https://github.com/Automattic/wp-calypso/issues/76912
