### ISSUE TITLE
General: Remove Open Sans

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4124]
Core got rid of a few weeks ago, in [#36753-core](https://core.trac.wordpress.org/ticket/36753). Maybe it's time for us to do something similar?

**Comment by richardmuscat** [comment]
This should be 4.3.1 or 4.4

**Comment by MichaelArestad** [comment]
@richardmuscat I'm happy to remove it. We need to remove it or things will be wonky within wp-admin. Neither Calypso or wp-admin will use Open Sans.

**Comment by richardmuscat** [comment]
I want to whittle down the number of things we are over-committing to achieving for JPR v1. Small things like this add up. If its been in core for weeks already then it can't be that serious?

**Comment by s-a-s-k-i-a** [comment]
Actually it is important to me as a user who likes a slim site. Any unnecessarily loaded fonts do not add up to a slim site.

There was a reason why WordPress core got rid of the font. Jetpack should do this too. Period.

Sorry for being this blunt, but Open Sans font loading is causing trouble anyways in current (stable) release: 
Have a look at this:
https://wordpress.org/support/topic/jetpack-css-404-error-in-site-statistics/

When applying the fix suggested by one of your employees on page 2 of above mentioned thread, I am getting a parse error in console, due to invalid version tags in font url.

well please just get rid of Open Sans.. 

Thanks!

**Comment by RafaelDeJongh** [comment]
I was endlessly searching why my site was loading a Google Font I was nowhere using on my site! This is pretty much annoying to have another request for a font that could be replaced with basic sans-serif.

I really do vote for removing it or at least an option to disable it!

**Comment by jeherve** [comment]
@s-a-s-k-i-a @RafaelDeJongh  This issue was fixed in #7446 and #7645. Open Sans is gone again.
