### ISSUE TITLE
Gallery broken by wp js reference error

### ISSUE THREAD

**Issue by korneelwever** [Automattic/jetpack#4179]
Somehow my galleries are broken, the console gives a rather ambiguous statement:
ReferenceError: wp is not defined in tiled-gallery.js

#### What I expected
Working galleries.

#### What happened instead
Link to the image.

#### Steps to reproduce the issue
See https://onemanengine.com/misfit-announces-speedo-shine-2/

See inspector.

**Comment by jeherve** [comment]
Could you try to deactivate CloudFlare's Rocket Loader, and let us know if it helps?

**Comment by BrianBourn** [comment]
Getting the same console error on any single post with a tiled gallery & carousel.

EX: https://inspiredimperfection.com/adventures/railtown-1897-state-historic-park-in-jamestown-california/

Reverted previous Jetpack versions & 3.9.7 is the latest version that the tiled galleries & carousel worked (site is now running 4.0.4).

**Comment by jeherve** [comment]
cc @eliorivero since it was most likely created by c99b1200aba9ef8cb9e021f7136073069941eec0.

I'm not sure why I can't reproduce, though.

Would it help if we changed all references to something like this?

```js
if ( 'undefined' !== typeof wp && wp.customize && wp.customize.selectiveRefresh  ) {
```

@BrianBourn or @korneelwever Could you give that a try, replace line 163 in `modules/tiled-gallery/tiled-gallery/tiled-gallery.js` by the line above, and let me know if it helps?

**Comment by BrianBourn** [comment]
That appears to fix it - thanks so much for the quick reply!

**Comment by korneelwever** [comment]
Rocketloader works for me!
