### ISSUE TITLE
Gallery Widget Fails Under WordPress 3.9-beta3

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#437]
When attempting to add images to the Gallery widget in Jetpack, no media selector is shown with following error in console:

`TypeError: media.controller.WidgetGalleryEdit is not a constructor`

**Comment by Vixxd** [comment]
I am still getting this problem on 4.3 - clicking 'choose images' does nothing, and trying to preview a page with an empty gallery prompts the following error:


Warning: trim() expects parameter 1 to be string, array given in /home/.../public_html/wordpress/wp-content/plugins/jetpack/modules/widgets/gallery.php on line 297

Warning: Cannot modify header information - headers already sent by (output started at /home/.../public_html/wordpress/wp-content/plugins/jetpack/modules/widgets/gallery.php:297) in /home/.../public_html/wordpress/wp-includes/pluggable.php on line 1207

**Comment by jeherve** [comment]
@Vixxd Your problem seems different from the one originally reported in this issue. I also cannot seem to be able to reproduce the problem on my end.

Could you try to deactivate all other plugins on your site, one at a time, to see if you can narrow things down to a conflict with another plugin?

Let us know what you find here, or [via email](http://jetpack.me/contact-support/).
