### ISSUE TITLE
Admin Page: add "Back" navigation item to dashboard

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4482]
#### Steps to reproduce the issue
1. Go to Jetpack > Dashboard
2. Click on the Security Settings icon:
   ![screen shot 2016-07-21 at 5 17 11 pm](https://cloud.githubusercontent.com/assets/426388/17028177/fa9f4a00-4f66-11e6-96a6-5a28cf7e3b4c.png)
3. The Security page loads, but no option to go back is offered.

It would be nice to implement something like in Calypso:

![screen shot 2016-07-21 at 5 16 15 pm](https://cloud.githubusercontent.com/assets/426388/17028200/0c5577ce-4f67-11e6-908b-406e6ee0565a.png)

**Comment by MichaelArestad** [comment]
This is a weird thing to add because it would be conditional. For example, if you navigate to settings with any other method, it wouldn't fit well.

What if, instead of adding a back button to the settings, we try something slightly different?

The problem is that it's a weird interaction to go from At a Glance to the Settings section with the settings icon because they haven't been introduced to how to navigate around between Jetpack and its settings.

We have a few options.
1. When a user clicks the settings icon, they go to a view that has no tabs, but does have a back button and section label with the settings underneath.
2. We remove the settings icon and call it a day (not ideal).
3. We remove the settings icon, but let them know they can get to settings with a pointer (message that pops up and is all "Hey buddy! Settings are over here, pal!"). Also not ideal.
4. We add a Settings/Dashboard toggle that Jeff and I experimented with in the past.

@jeffgolenski thoughts?

**Comment by jeffgolenski** [comment]
This is a tough one to navigate around (see what I did there?!)

As @jeherve said, it would be _nice_ to have something like this, and even nicer if we were consistent with calypso, but...

I feel like this is one of those issues where the user only gets lost once and then realized how the new Jetpack works. Doubly so if they've been using Jetpack already since there's currently the settings area and the jetpack admin landing page (the one with 3 columns in < 4.2).

I think we can eliminate this issue not by adding a back button, but by eliminating the disconnect for the user with a prominent nav item that's always visual (ie. #4 on michaels list).

As I've been using this version of Jetpack, it's nice to have the Dashboard and Setting links on the sidebar for larger screens, but it's annoying on smaller ones where the sidebar nav is collapsed. 

I'm still in favor of using this method of navigation for our top tier...

<img width="965" alt="screen shot 2016-08-23 at 5 30 51 pm" src="https://cloud.githubusercontent.com/assets/214813/17910546/4c1b2a0c-6957-11e6-845a-7fda9be9560c.png">

This way both tiers of navigation are fairly close to each other, as opposed to the current sidebar & and horizontal section nav

In fact, I wouldn't even be opposed to having it in both locations, really.

We just need to keep in mind with this UI that we make get a lot of bad feedback because humans hate change and this UI is much different. But the UI is logical and will only take a single experience to learn – hopefully.

**Comment by robertdall** [comment]
Where is the setting link that use to be on the top of the page. I clicked all three links that are their. One is the dashboard, but you call also call it at a glance? Lets call it one thing and stick to it ok? It can be "at a glance" or it can be "dashboard" but it can't be both.

There is no link in the header that show you the setting page. You have to go into the WordPress menu Bar to find that settings link and then click on to find the Jetpack modules that you want to edit.

Also Apps and Plans links start with large adds for WordPress apps and WordPress.com Advertisements and not related Jetpack Functionality.

So out of three links on the front page one has a confusing title that doesn't show all that jetpack is actually capable of and two are glorified adds for Automattic projects.

Disappointing to say the least.

**Comment by jeherve** [comment]
@robertdall Did you mean to post this here? It doesn't seem related to the back button we discussed on this issue, and you left the exact same comment on #4821.

**Comment by robertdall** [comment]
Then delete it. I got to get back to actual work.

**Comment by jeherve** [comment]
I'll close this in favor of #4821
