### ISSUE TITLE
Add an option to force two-step authentication

### ISSUE THREAD

**Issue by HardeepAsrani** [Automattic/jetpack#457]
I activated two-step authentication using SSO module. However, I can still login directly if I opt not to use sign in with WordPress.com option. There should be an option in SSO configure page to force two-step authentication option.

**Comment by ebinnion** [comment]
Hello there @HardeepAsrani and others,

I have recently been working on the Jetpack SSO module, and I believe that you can get the functionality you need by combining two filters:

```php
<?php
add_filter( 'jetpack_remove_login_form ', '__return_true' );
add_filter( 'jetpack_sso_require_two_step', '__return_true' );
```

The first filter will hide the login form, as well as prevent logins via POST. It has not yet been tested with login via XML-RPC though. That is something that I will consider though.

The second filter would require that a user have enabled Two-Step Authentication for their WordPress account.

I went ahead and updated the SSO documentation so that it mentions filters that can be used for SSO. You can find that documentation here:

https://jetpack.com/support/sso/

Please let me know if I can help further.
