### ISSUE TITLE
Admin Page: Sitemaps display a notice when a site is set to private.

### ISSUE THREAD

**Issue by zinigor** [Automattic/jetpack#4651]
#### Steps to reproduce the issue
- Make sure that you have sitemaps enabled.
- Set the site to disallow indexing by search engines.
- Observe the notice on the Jetpack admin page that moves masthead down.

![screenshot from 2016-08-04 14-46-45](https://cloud.githubusercontent.com/assets/374293/17400790/fc0521f4-5a5a-11e6-8a5c-65c07949168c.png)

**Comment by eliorivero** [comment]
I followed those steps and couldn't reproduce because the notice only appears once after the activation of Sitemaps. Here's the order of steps that reproduce this:
- set site to discourage indexing
- go to Jetpack react and activate Sitemaps
- reload
the notice is now visible. If you reload again, the notice is gone. To see it again, deactivate and activate Sitemaps again.

**Comment by samhotchkiss** [comment]
I was unable to reproduce this at all, I can't get that notice to pop up.

I did, however, run into this:
![image](https://cloud.githubusercontent.com/assets/574752/17558233/260d6454-5ed7-11e6-8b4c-298d879365df.png)

That "Link to old settings" needs to go...

**Comment by eliorivero** [comment]
@samhotchkiss try doing a `npm run distclean`, `npm run clean` and `npm run build` to build everything again, this is the current:

<img width="731" alt="captura de pantalla 2016-08-10 a las 11 58 31" src="https://cloud.githubusercontent.com/assets/1041600/17558313/8e50d55a-5ef0-11e6-85b2-39fdcee023e4.png">
