### ISSUE TITLE
Network Activate: Notice looks out of place

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#4794]
After network activating Jetpack today, I saw this notice:

![screen shot 2016-08-15 at 11 32 36 am](https://cloud.githubusercontent.com/assets/1126811/17671335/2d364760-62dc-11e6-9e02-5777f9ab5c2b.png)

It seems a bit out of place since the text is larger than the notice below it.

Also, what if I don't want the individual site admins to manage their Jetpack connections? This can be handled in `Jetpack > Settings` from Network Admin, but should we let admins know where to override that?

To repro:
- Create a multisite
- Install Jetpack in Network Admin
- Network activate

**Comment by ebinnion** [comment]
Similarly, this is the notice that displays when connecting a site in `Jetpack > Sites` in Network Admin:


![screen shot 2016-08-15 at 11 49 49 am](https://cloud.githubusercontent.com/assets/1126811/17671900/ea7cf3f8-62de-11e6-9092-bc8c389dc024.png)

**Comment by MichaelArestad** [comment]
Similarly: 

![image](https://cloud.githubusercontent.com/assets/1123119/18894077/a37d73ca-84c5-11e6-8a48-05e5a53e5fc2.png)

Visible from the dashboard of a network site, but not the primary.

**Comment by jeherve** [comment]
Related: #3877

**Comment by MichaelArestad** [comment]
I think really the solution here is to reuse the visuals/components we show for single sites, but with a different goal. Instead of encouraging immediate connection of the site, we should encourage individual connections. Probably something similar in design to the JITM banners we have been using, but with different content.

We also should make sure that _every_ notice from Jetpack follows the styles of notices or banners from Calypso.

I think this is going to require two or three PRs to address. One or two for styling fixes and one for the copy update (the first screenshot). I'll follow up with mockups shortly.

**Comment by MichaelArestad** [comment]
The current view of the Jetpack page on the network admin also needs to change. It looks like this:

![image](https://user-images.githubusercontent.com/1123119/37212008-0af15f72-236b-11e8-9202-bf2927948315.png)

**Comment by MichaelArestad** [comment]
I propose we reuse this thing @jeffgolenski made and @joanrho finessed, but with copy designed for multisite users. On individual sites, it would be the normal one, but on the network admin and on the Jetpack page, it would look like this:

![image](https://user-images.githubusercontent.com/1123119/37212175-87b4433a-236b-11e8-800a-545ab1d84db9.png)

**Comment by rickybanister** [comment]
@MichaelArestad how come that banner doesn't have a 'set up' button in it? Did you remove it from that screenshot or is there some other circumstance happening?

Since we would have to modify the copy to use that for multisite users we probably want to simplify it a bit, perhaps ditch the tabs on the left and link out to more info on jetpack.com if need be.

**Comment by MichaelArestad** [comment]
> @MichaelArestad how come that banner doesn't have a 'set up' button in it? Did you remove it from that screenshot or is there some other circumstance happening?

@rickybanister There is no set up button because this is the view of the Network Admin. It isn't a site as much as an admin panel. Setup can only happen on the Network sites themselves.

In the copy there's a bit of an explanation as well:
> To get started, an admin of each site on the multisite network must set up Jetpack.

**Comment by rickybanister** [comment]
So it already exists in the dashboard of the network's main site and you're simply proposing that we use it in the network admin as well after the plugin has been network activated, is that accurate?

**Comment by MichaelArestad** [comment]
> So it already exists in the dashboard of the network's main site and you're simply proposing that we use it in the network admin as well after the plugin has been network activated, is that accurate?

That is accurate.

**Comment by crunnells** [comment]
The PR addressing this has been closed: https://github.com/Automattic/jetpack/pull/9121#issuecomment-484281968

Probably worth closing this issue as well.
