### ISSUE TITLE
Admin Page: missing Site Stats menu

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5007]
One of the most popular Jetpack menu items today is the Site Stats submenu:

![screen shot 2016-08-29 at 17 46 49](https://cloud.githubusercontent.com/assets/426388/18057502/9548c29e-6e10-11e6-9130-2362d0463dc5.png)

Unfortunately, that submenu is gone in Jetpack 4.3. It might cause some confusion for site owners who don't use the Stats dashboard widget; they won't know how to access their stats anymore.

I think we should add that menu item back.

The lack of a menu item also makes navigation to stats more difficult when you're on any dashboard page besides the main dashboard; until 4.3, you could access stats in one click, from the Jetpack menu. Now, that one-click option is limited to folks starting from the main dashboard, thanks to the "View All" button in the Stats widget.

**Comment by dereksmart** [comment]
This was a design decision @MichaelArestad @jeffgolenski

**Comment by MichaelArestad** [comment]
Let's leave it out this release. I want people to find the At a Glance dashboard.

**Comment by jeffgolenski** [comment]
It will initially create some slight confusion amongst current jetpack users the first time they see the new Jetpack – but now stats will be viewed on the new dashboard and there is a CTA to direct them to detailed stats. I don't anticipate this being an issue.

**Comment by jeffgolenski** [comment]
Scratch the last comment I made. Per a conversation in slack, @jeherve brought up several good points. Going to work on bringing this back:

<img width="755" alt="screen shot 2016-08-29 at 11 58 51 am" src="https://cloud.githubusercontent.com/assets/214813/18057982/495cfde4-6de0-11e6-90d1-6cc20f8ddc6e.png">

I can't recall why it was removed in the first place, but the link to old stats and wpcom stats should be present.

**Comment by timmyc** [comment]
People <3 stats.  When we initially launched calypso stats, there was quite a bit of _interesting_ feedback... we too had a link to the "old" stats which helped with some of the feedback.  Eventually we moved to hiding the old stats link for new users - not certain if that is something that can be done in JP or not.

**Comment by jeffgolenski** [comment]
Enhanced with: https://github.com/Automattic/jetpack/pull/5021

**Comment by jeherve** [comment]
Also requested here:
https://wordpress.org/support/topic/new-stats-well-stink/#post-8155244

**Comment by v18** [comment]
Requested in 2821250-t

**Comment by jeherve** [comment]
Also requested here:
https://wordpress.org/support/topic/put-old-stats-back-in-the-nav-bar-boooo/

**Comment by chaselivingston** [comment]
2823467-t

**Comment by samhotchkiss** [comment]
2833939-t

**Comment by jeherve** [comment]
Some more feedback:

- https://wordpress.org/support/topic/re-add-stats-to-jetpack-sub-menu/
- 2846673-t
- 2846574-t
- 2846045-t
- 2825271-t
- 2826795-t
- https://wordpress.org/support/topic/old-statistic-in-sitemenu/#post-8194050
- https://wordpress.org/support/topic/is-it-possible-to-make-old-stats-view-default-view/
- 2843541-t

**Comment by antermoia** [comment]
As a user, I'd like to add an element to the discussion here: number of clicks to get where I want, and the time it takes to get there. It's two clicks on "Jetpack" and then "Stats" and the stats are then loading **instantly.**

Since JP 4.3 I'm clicking on "Jetpack", then "Dashboard" (takes time to load), then "View Old Stats" (sorry, designers of the new stats page). It's slower.

 - or -

I click on "Dashboard" (takes time to load) then find the "Site Stats" widget, and the small/grey "View All" button to get to the stats.

In terms of clicks and/or efficiency, both of the new solutions are a step back.

From my perspective, the **easiest** solution by far would be to add the small 48-hour stats that I see when I'm logged in and visit my own site to the /wp-admin back end header bar - it would unify the appearance of the header bar between site frontend and backend as well, and be far more logical.

**Comment by jeherve** [comment]
> the easiest solution by far would be to add the small 48-hour stats that I see when I'm logged in and visit my own site to the /wp-admin back end header bar

Related: #621
