### ISSUE TITLE
Activating modules throws No route was found matching the URL and request method error

### ISSUE THREAD

**Issue by defries** [Automattic/jetpack#5110]
#### Steps to reproduce the issue
Installed Jetpack 4.2.2 yesterday on a site for the first time. Configured a few modules. Today, I wanted to continue and do the rest but updated to 4.3 first. After the update went to the settings screen and clicked on the switch to activate the module which threw an error.

#### What I expected
The comments module to be activated

#### What happened instead
Got presented with the following error: `Comments failed to activate. Error: No route was found matching the URL and request method`.

**Comment by eliorivero** [comment]
This might be due to your server not supporting the PUT request method. You can verify this if you go to Jetpack admin in Chrome, press Cmd+i in OS X or F12 in Windows to open Chrome dev tools. Go to Network tab, and try activating Comments.
You should see something like this only that the Status Code won't be 200 in your case (and the circle will be in red) if the method is not admitted
<img width="818" alt="no-put" src="https://cloud.githubusercontent.com/assets/1041600/18314904/70e24998-74eb-11e6-9320-52ce7d569269.png">

If that's the case, it's a known issue and it has a patch already at https://github.com/Automattic/jetpack/pull/5100 and Jetpack 4.3.1 will be released later today which will solve this issue.

**Comment by defries** [comment]
Not sure we're talking about the same thing here. This is what I see:
![jetpack_issue](https://cloud.githubusercontent.com/assets/411524/18315340/ebb2e6de-7516-11e6-94a9-bed3926c9694.png)

Other sites on the same server don't see this issue.

**Comment by eliorivero** [comment]
Yeah, this is the case, try clicking the line in red with the 404.

**Comment by defries** [comment]
![jetpack_network_error](https://cloud.githubusercontent.com/assets/411524/18315487/7b35cf10-7517-11e6-9b9f-7a576edf7a24.png)

Yeah, that's the same alright, except it's not happening on all sites on that server.

**Comment by eliorivero** [comment]
It's ok, it will be fixed with the PR. Thanks for confirming! 👍 

Will close now since #5100 will fix it. Feel free to open a new one if after updating to 4.3.1 you see any issue.
