### ISSUE TITLE
Subscriptions/Publicize: Provide UI to confirm sub was successfully submitted

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#5151]
Within wp-admin, there is no indication that a post was successfully send to e-mail subscribers or Publicize services.

We should add one to help site admins get a better sense of where problems lie (exposing the failure data that wp.com has for a failed Pub connection or having a reasonable belief that WP.com sent the e-mails and that an issue might with a specific end user, etc).

I'd like to figure out a scope for this sooner rather than later so we can pinpoint an accurate milestone.

**Comment by jeherve** [comment]
From #8925

Suggestion: after publishing a post, you get this from core WP:

![screen shot 2018-02-23 at 8 45 59 am](https://user-images.githubusercontent.com/108942/36602724-fdfc08a8-1875-11e8-98fa-9f518d8571ab.png)

I think we could relatively easily do something like:

![screen shot 2018-02-23 at 8 46 48 am](https://user-images.githubusercontent.com/108942/36602777-1ace0dc8-1876-11e8-8780-9bd3e0e60b42.png)

**Comment by keoshi** [comment]
I second the motion to use core's notice for this.

**Comment by enejb** [comment]
Before I go and add this. 

one problem that I see is that as the post saves we don't have the information but only the instructions to tell .com is we should send an email and if we should publicize the post. But not if we did so. Since that happends in a few different async processes. 

We could create a different api endpoint that would tell us then what worked and what didn't.

So knowing the above do we still want to tell the publisher that we publicized to LinkedIn? Or can we say something like. 

`Post published, and sending out the emails and publicizing to LinkedIn. ` 

Instead
