### ISSUE TITLE
Widgets: review links included in all widgets for compliance with Google guidelines

### ISSUE THREAD

**Issue by annezazuu** [Automattic/jetpack#5160]
reported in 2824478-t with a link here:

http://searchengineland.com/google-reminds-webmasters-widget-links-webmaster-guidelines-258393

"Google shared that while many widgets can enhance your web site experience, “some widgets add links to a site that a webmaster did not editorially place and contain anchor text that the webmaster does not control.” Google explained “because these links are not naturally placed, they’re considered a violation of Google Webmaster Guidelines.”

Are we going to make a change to the links in light of this?

**Comment by jeherve** [comment]
I'm not sure the image widget qualifies as a widget inserting unnatural links. It may only include one link, and that link will only be there if the site owner decided to add it.

Looking at the different widgets available in Jetpack, I can think of 2 widgets inserting links that are not fully controlled by the site owner, and that could be changed to `nofollow` in Jetpack:

- Top Posts Widget: since that widget only lists posts from one's own site, I don't think we should be adding `nofollow` to those links.
- [Display Posts Widget](https://jetpack.com/support/extra-sidebar-widgets/display-wordpress-posts-widget/): that widget may include many links, all pointing to a third-party website. That site was chosen by the site owner though. I'm not sure about that one, to be honest. I'll defer to someone who knows more about SEO than I do. :)

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
