### ISSUE TITLE
Infinite scroll: Mobile browser crashes on 100+ images per post

### ISSUE THREAD

**Issue by skmasq** [Automattic/jetpack#5303]
#### Steps to reproduce the issue
1. Create a project with 100+ images in gallery that will load via infinite scroll (you can see a live post here [http://www.soundofatastylife.com/portfolio/morocco-adventure/]
2. Access said post via mobile (tested on iOS Chrome (will flicker and crash) or iOS Safari (will load and show message that it failed to load the website))

#### What I expected
That images will not be loaded all at once.

#### What happened instead
When debugging with chrome developer tools, it seems that initially it loads 5-8 images and then the process starts to load each 1-2 seconds extra 5-8 images and continues until all images have been queued to download. 

#### Questions
1. Is this intended behavior to load all images periodically overtime in small packets, or is the behavior intended to load when images are in viewport? (which I would like to do in my case)
2. Can you guide me where in your code I should do the viewport check implementation?

Thanks, any direction is appreciated greatly!

**Comment by jeherve** [comment]
Since you're looking at a single post, [Jetpack's Infinite Scroll module](https://jetpack.com/support/infinite-scroll/) won't be used; the module is only available on themes that support it, and on archive or index pages that list several posts (like the home page).

Looking at that post, you seem to be using a standard WordPress gallery to display your (gorgeous) pictures. Jetpack consequently won't have any impact on the way the images are loaded, even if the page is loaded via mobile. WordPress itself won't change anything in the way the images are loaded either.

If you'd like images to load as you scroll, you'd need to install a Lazy Load plugin like [this one](https://wordpress.org/plugins/lazy-load/). There are [other Lazy Load plugins in the plugin directory](https://wordpress.org/plugins/tags/lazy-load), so I'd suggest checking reviews an picking one that seems to work best on your site.

I hope this clarifies things a bit.

**Comment by skmasq** [comment]
@jeherve thanks, got me in the right direction, adjusted existing image preloader and adjusted lazy loader and made it working, now it's loading beautifully fast :)
