### ISSUE TITLE
Widget Visibility: store slugs instead of post/term IDs

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#545]
Widget Visibility stores post/term IDs. In some cases (like when exporting and importing content with the core exporter and importer), post IDs can change.

This usually wouldn't be a problem, but when migrating site options from one site to another via [this plugin](http://wordpress.org/plugins/options-importer/), the widget visibility options are ported over from the previous site, but the post IDs don't match anymore.

Would it make sense to start storing post slugs instead of IDs? And if we were to do so, how would we manage permalink structure changes, as well as slug changes?

Suggested in 1838791-t

**Comment by georgestephanis** [comment]
Due to the way existing stuff is structured, and the fact that there can be duplicate slugs (for example, of taxonomies with different parents, I believe?) I don't think that this is worth the time or energy to changeover.  The migration from old IDs to Slugs would be a nightmare on its own.

I'd sooner see a secondary plugin that handles migration from old site to new site for when IDs change.  Perhaps an admin page that lists all widgets with visibility conditions, and lets the user manually select which it should refer to?

The most I'd be willing to consider is having the plugin store the slug of whatever when it's saved as a note for future reference, but not actually use it anywhere, but that's a bit of a stretch and not something I personally feel would be worth the team building out.

Recommending to close.

**Comment by jeherve** [comment]
Closing. :+1:
