### ISSUE TITLE
Integrate WordAds into Jetpack

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/jetpack#5465]
Synopsis: Add WordAds functionality into Jetpack to allow Jetpack users to sell advertising on their sites

**Responsible:** @dbspringer

Outstanding:

- [x] Finalize Settings location/UX
- [x] Add logic so that it's only available to paid accounts

**User experience:**
Per discussions in the 4.4 Check-in hangout, the v1 version of WordAds in Jetpack is going to be a simple on/off setting with an optional header unit and widgets.

The flow for accepting new WordAds users via Jetpack/gating the module to paying customers is still TBD, but mechanisms exist within the WordPress.com codebase to accomplish those actions and can quickly be leveraged once they're decided.

Otherwise, assuming the site is approved for WordAds literally the only thing the user needs to do is turn on the module and they'll get a 300x250 (mrec) ad unit below the content of the first post. Optionally, the user can turn on a leaderboard unit at the top and any number of units as a widget.

**Technical approach:**
The standalone self-hosted WordPress plugin [AdControl](https://wordpress.org/plugins/radcontrol/) has been ported and refactored into the existing Jetpack module framework. Additionally, the admin menu has been updated to utilize the new React frameworks. Otherwise, the module utilizes all the existing WordAds/WordPress.com code similar to how AdControl did.

**Designs**:

Optional leaderboard unit
<img width="767" alt="screen shot 2016-11-02 at 4 32 33 pm" src="https://cloud.githubusercontent.com/assets/273708/19951265/1473b754-a11a-11e6-821c-a491092acb13.png">

Belowpost (the standard unit) and optional sidebar unit (in widesky configuration)
<img width="1222" alt="screen shot 2016-11-02 at 4 33 01 pm" src="https://cloud.githubusercontent.com/assets/273708/19951281/2d437602-a11a-11e6-9983-9301f3055f2c.png">

Deactivated WordAds in Engagement tab
<img width="766" alt="screen shot 2016-11-02 at 4 37 14 pm" src="https://cloud.githubusercontent.com/assets/273708/19951351/bbc74af2-a11a-11e6-9b33-a4d70ebfe7a5.png">

Activated WordAds in Engagement tab
<img width="736" alt="screen shot 2016-11-02 at 4 38 24 pm" src="https://cloud.githubusercontent.com/assets/273708/19951362/cba72db6-a11a-11e6-9997-4a897770e447.png">

Activated WordAds missing requirements (needs styling help)
<img width="740" alt="screen shot 2016-11-02 at 4 44 11 pm" src="https://cloud.githubusercontent.com/assets/273708/19951478/a0c538b2-a11b-11e6-9b8d-f70ab99aa2cd.png">

Complete: 99%

Difficulty:  8

Last Updated: 2016-11-02 (by @dbspringer)

**Comment by rickybanister** [comment]
After a nice chat with @MichaelArestad and @dbspringer we came to a few conclusions. @MichaelArestad has a few ideas about the UI (forthcoming) and we were able to simplify a few other aspects.

> Activated WordAds missing requirements (needs styling help)

We should be able to remove the need for this view almost entirely for two reasons: 

1. users with a plan will get auto-approved into the WordAds program so we don't have to talk about waiting for application approval
**2. we should move the WordAds Terms of Service into the Jetpack / WordPress.com Terms of Service so that they have already been approved by the user at the time they purchase a plan, thus further negating any steps outside of selecting where to show the ads and where to send the checks.**

cc @beaulebens @richardmuscat 

Do we need to involve @pesieminski with this?

**Comment by beaulebens** [comment]
How does this jive with the new settings layouts/system, which doesn't look like the above?

I also think we need to make sure that WordAds is marked up in the same way as other premium features ("PRO" button), however that works with the new settings UI.

If you have to turn WordAds on pro-actively (which I think you should), then we could just include something in there that says "by enabling and using WordAds, you agree to the [Terms of Service]". I don't know exactly what the WordAds ToS looks like, but I'm not a huge fan of just rolling it in for all users to accept, unless there's minimal difference from the existing one. I also don't know if that covers things retro-actively (e.g. users who are already connected/have a plan, who see this new feature and then go and use it).

**Comment by pesieminski** [comment]
Right, I don't think the rolling in to wordpress.com terms would work retroactively, but could do it prospectively.

If there is a step where the user has to do *anything* though (add their address, bank account, or just turn the thing on), by clicking "submit", it should be pretty trival to add the terms link at that step I think...and it's much more defensible if that separate link is there, and they agree to it.

The TOS for WordAds is here, FYI: https://wordpress.com/tos-wordads/

**Comment by rickybanister** [comment]
> How does this jive with the new settings layouts/system, which doesn't look like the above?

There's an updated design forthcoming. @MichaelArestad didn't get a chance to post it yesterday. 

> I also think we need to make sure that WordAds is marked up in the same way as other premium features ("PRO" button), however that works with the new settings UI.

Also forthcoming.

> If you have to turn WordAds on pro-actively (which I think you should), then we could just include something in there that says "by enabling and using WordAds, you agree to the [Terms of Service]"

The new design (forthcoming) no longer has a 'turn this module on' toggle, instead uses a toggle to turn on the bottom-of-post ad unit, but we can certainly 

1. include a link to the tos and say 'if you turn this on you agree'
2. or have a modal or alert type thing saying that you must agree first

But going forward I do think we should prospectively include the WordAds TOS in with the .com/jetpack TOS.

**Comment by MichaelArestad** [comment]
Something like this:

![image](https://cloud.githubusercontent.com/assets/1123119/20019067/c685c572-a287-11e6-914b-3b4954aae895.png)

**Comment by MichaelArestad** [comment]
But with better copy.

**Comment by pesieminski** [comment]
>> But going forward I do think we should prospectively include the WordAds TOS in with the .com/jetpack TOS.

This is a good idea, and not hard to do. Will add it to the list. Once we add it as part of a major release (where all users are notified of the change), we can be comfortable that all existing users are picked up by the new terms, with all new ones agreeing to them on signup/connection of Jetpack.

At this point we'd be able to take out the separate opt in for WordAds terms. But can't do it before then, because we'd have some users (basically those who have already set up their Jetpack/WordPress.com accounts) who would fall through the cracks. 

For WordAds, this isn't a theoretical concern actually. We get a fair number of disputes, threats, etc...and have to implement these terms more than most others. :)

**Comment by rickybanister** [comment]
Thanks @pesieminski, that's very helpful to know!

**Comment by samhotchkiss** [comment]
This is merged-- all that's left to do is get the lawyers involved...

**Comment by jeherve** [comment]
> all that's left to do is get the lawyers involved

Detailed list of things left to do in p1HpG7-3Jr-p2

**Comment by jeherve** [comment]
TOS changes were added in #6074. Closing this.
