### ISSUE TITLE
Tiled Galleries: Usage of requestAnimationFrame limited to Chrome-based browsers

### ISSUE THREAD

**Issue by PatTheMav** [Automattic/jetpack#5492]
Consider this an improvement request - in `tiled-gallery.js` on line `157` the following piece of code can be found:

```
if ( window.chrome && requestAnimationFrame ) {
	attachResizeInAnimationFrames( tiledGalleries );
} else {
	attachPlainResize( tiledGalleries );
}
```

Safari supports `requestAnimationFrame` since version 6.1, Firefox since v23, Internet Explorer since v10 according to MDN. If this API is used for performance reasons, it might be better to extend its usage to browsers other than Google Chrome.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

The comment above the code mentioned also provides more details about this implementation:

https://github.com/Automattic/jetpack/blob/a158ca33d5b651eaae58b71616a9c552866f8ed2/modules/tiled-gallery/tiled-gallery/tiled-gallery.js#L156-L160
