### ISSUE TITLE
JSON API: "Jetpack 3.3 is required" error on WordPress.com

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#5501]
I haven't been able to reproduce this, but I've seen two instances so far in which the users are seeing this error, and our debugger is reporting a 403 for the API. Toggling it off and then back on on the user's site fixes it.

2902967-t
2901159-t

**Comment by samhotchkiss** [comment]
Closing as the API is no longer optional...

**Comment by kraftbj** [comment]
It happens more when WP.com doesn't think Jetpack is at the latest version—I think by checking the `jetpack_version` for the shadow site on WP.com. When it hasn't been synced or something is failing, so it doesn't sync over, WP.com will think the user is not running a modern version of JP.

The debugger 403ing is because we make a generic API request—we don't piggyback from WP.com—so the JSON API module being deactivated will return it.
