### ISSUE TITLE
SEO Tools: add JSON LD support

### ISSUE THREAD

**Issue by hrsetyono** [Automattic/jetpack#5556]
As of now, Jetpack automatically added Open Graph tag. I feel this feature should be improved and made into "SEO" module.

SEO module should be light and work automagically, not as feature-packed as Yoast.

Features suggestion:

- Add OG tag (the same way now)
- Add "description" tag
- Add JSON LD script after `the_content` for Post and WooCommerce's Product (if installed). It should have filters for adding our own CPT.
- Add **Logo** field in Customizer, this logo can then be used for JSON LD `publisher` value.
- Improved **Excerpt** metabox with Google search preview and Recommended letter count. [Reference](https://help.ghost.org/hc/en-us/article_attachments/210471908/meta-descrip-tag.jpg).
- Rearrange the `wp_title` format for each Taxonomy and CPT. (Maybe this one is bit on the heavy side, but good to have)

Having this as module means we can turn it off in case we want to use Yoast or other SEO plugin.

What do you think?

Thanks

**Comment by jeherve** [comment]
Thanks for the feedback!

Since there are multiple suggestions in your issue, I'll break this down into separate issues for better tracking.

> Add "description" tag

This will be included in the upcoming SEO Tools module that will be available in Jetpack 4.4. You can check #5307 to find out more.

> Rearrange the wp_title format for each Taxonomy and CPT. (Maybe this one is bit on the heavy side, but good to have)

Some of this will be part #5307, although I haven't tested that feature with custom taxonomies and CPT yet. We'll test this in the coming few days.

> Add JSON LD script after the_content for Post and WooCommerce's Product (if installed). It should have filters for adding our own CPT.

For reference: http://json-ld.org/ 
Let's keep this issue as master issue for JSON LD support in Jetpack's new SEO Tools module. 👍 

> Add Logo field in Customizer, this logo can then be used for JSON LD publisher value.

This is already part of WordPress Core itself:
https://codex.wordpress.org/Theme_Logo

It doesn't support JSON LD though.

> Improved Excerpt metabox with Google search preview and Recommended letter count.

This could be a good addition to the Excerpt metabox, and to the SEO Tools module. I've tracked this here:
https://github.com/Automattic/wp-calypso/issues/9242

**Comment by hrsetyono** [comment]
Thanks for the reply. Appreciated it.

I'm not sure whether this issue should be marked as Closed, if it does, then do close it.

Regards,

**Comment by brbrr** [comment]
Closing this as most of these features already available in SEO tools module.
