### ISSUE TITLE
VideoPress: broken icon when uploading video

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5626]
> I clicked Media > Library > Add New, and then drag/dropped a video there. It appeared to upload/process, but then showed a broken image😦

<img width="151" alt="screen-shot-2016-11-11-at-4-54-54-pm" src="https://cloud.githubusercontent.com/assets/426388/20263708/4194d84c-aa68-11e6-81f2-df3d6d990726.png">

> When i refreshed that page, it showed the generic WordPress video icon, instead of (ideally) some sort of thumbnail from the video itself, or (at least) something that indicates VideoPress is active. Maybe a Jetpack-icon-emblazoned video icon that indicates it’s processing, or something?

<img width="160" alt="screen-shot-2016-11-11-at-4-55-35-pm" src="https://cloud.githubusercontent.com/assets/426388/20263717/4a73c338-aa68-11e6-905e-2495683c87ac.png">

p2JiWH-1tm-p2

**Comment by dbtlr** [comment]
It will only show the thumbnail once the transcoder processes, which can take upwards of 5-minutes, depending on the size of the upload. Usually, it is much faster though, however, will only appear on a refresh after the update occurs, since it would require a large scale change to the default media library to have it poll for changes and update later. Totally possible, but not happening any time soon.

In terms of the broken image, do you know what the src="" on that image was? The API returns a link to the local video thumbnail image (that appeared on refresh), it is strange that it didn't load the first time and I'd be interested to see what happened so I can track it down.

In terms of what image to use, I'd love to see a more custom "VideoPress processing" type thumbnail here instead, but as of now we don't have such a thing.

**Comment by jeherve** [comment]
cc @beaulebens, who originally reported the issue.

**Comment by beaulebens** [comment]
I'm not seeing this now, because I'm getting a 500 error on every attempt to upload a video :(

Might be because I reset my database on this testing site, and it's clashing on IDs or something?

**Comment by dbtlr** [comment]
That might do it, you need to disconnect from wpcom to get a new shadow
site as well

**Comment by beaulebens** [comment]
Do I need a new shadow site? If the URL stays the same? Shouldn't it just
use the same one? That's what the rest of Jetpack does.

**Comment by dbtlr** [comment]
It does, but if you cleared out your local database, then your shadow site now has all your old posts still. 

VideoPress actually does not use the shadow site in any way. The VideoPress architecture is completely separate. I was just conjecturing based on you saying you cleared the database, that it might cause errors if the shadow site was not cleared as well.

**Comment by jeherve** [comment]
Closing as duplicate of #5877
