### ISSUE TITLE
After the Deadline: atd.min.css loaded on all dashboard pages

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5640]
#### Steps to reproduce the issue

1. Activate the AtD module.
2. Load any dashboard page.
3. You'll notice that the following CSS file is loaded: `modules/after-the-deadline/atd.min.css?ver=20150715'`

It would be nice to only load it when the editor is loaded.

**Comment by ebinnion** [comment]
In my testing, it wasn't all admin pages. There is some logic for deciding which pages to load the scripts and css in here: https://github.com/Automattic/jetpack/blob/master/modules/after-the-deadline.php#L286-L310

I'm going to suggest we close this for now since those default seem reasonable to me.

**Comment by jeherve** [comment]
That makes sense. Why do we need to load it on `admin.php` though? Is there a post editor on one of the main admin pages?

**Comment by ebinnion** [comment]
I'm not 100% on that. But, I could look into that a bit later.
