### ISSUE TITLE
Jetpack Portfolio Featured Image Share Issue

### ISSUE THREAD

**Issue by DragonflyUnleashed** [Automattic/jetpack#5734]
Hello there --

I am new to posting on GitHub. Doing so as directed by Anne McCarthy of Jetpack Customer Service.

**Here's the issue:**  

I wanted to bring Jetpack and WordPress' attention to a matter which I find hard to believe isn't known, but it's very possible it isn't.

When sharing images from a Portfolio gallery to Facebook and Twitter (only two I tested), the images are not following any type of convention (is that the right word) for a post featured image.

When you share a blog post with a featured image, the featured image will fit into both Facebook and Twitter's formats, such as any blog shared from here:  http://trinityenergyprogression.com/blog.

However, from what I can tell from three sites I've tested this on, if a post is created via the Jetpack Portfolio, and then shared from the website, the images are NOT conforming to the same standards as a featured image in a blog post.  

For horizontal images, either the top of the image is cut off or when the image hits a certain minimum size, Facebook attempts to force the horizontal image into a square; thus cutting off even more of the image.

**Here's where you can check it out:**

The three development sites I've tested this on are as follows (first two are Organic Themes, the third is Avada):

1 ) http://newtao.jpmaney.com/thoughts

2 ) http://tao-not-dow.org/tao-not-dow 

3 ) http://testdev.eileenbild.com/news-media/365-days-of-gratitude 

I've spent well over 6 hours investigating this issue with 3 of those hours spent Sunday literally creating different sizes images and testing them. ; I was a bit stir crazy by then.

I've posted the various size images I troubleshot and tested this on at this link:   http://newtao.jpmaney.com/thoughts.

You'll see a series of images with a guy on a mountain top and the words start with "Wear out the soles .... ".  I've indicated the size of the image in fluorescent bold green on the image.  

If you click on each image one-by-one AND then SHARE to Facebook or Twitter, you'll find that none of the images (except the clearly vertical ones)  fit into the size of the Facebook window, even when I've changed image sizes by mere pixels.  

**Expectations and rationale for resolving this issue:**

LOL, I'm sure it's obvious why to resolve this issue. No use having a gallery with images which are carefully crafted to not have them able to be properly shared in the usual social media.  

At minimum, I believe I was expecting the images shared from the Portfolio to at least follow the standard 600x315 Facebook size.   

**Other details:**

I am on a hard-wired ASUS desktop PC (maxxed out gaming machine) on updated Windows10 and updated Chrome.  I've had friends other than the ones I'm helping out with sites test it out to make sure they have the same experience.  They do.  

I kind of find this incredulous because when sharing a blog with a featured image, there is generally no issue .. the featured image size is accommodated.   Although I do have this kind of geiger counter of stumbling across weird issues; have had it for years and encountered it with companies such as Citicorp (3 times), Comcast, web.com (formerly Interland), etc. 

Again, since I'm new at this, not a clue what next steps are except to post here. 

Oh yea, and I mistakenly created a new issue, not here in Jetpack.  I'm not seeing how to delete it.  

Have fun!

Thank you for your consideration,
~ Laurel

**Comment by DragonflyUnleashed** [comment]
Hi there --

How do I request a second look at this issue, instead of it being sidelined?  Given this is a featured image, and the coding already exists to have featured images handled in a particular way when sharing ... wouldn't this be a relatively easy fix?

Thank you,
~ Laurel

**Comment by jeherve** [comment]
> However, from what I can tell from three sites I've tested this on, if a post is created via the Jetpack Portfolio, and then shared from the website, the images are NOT conforming to the same standards as a featured image in a blog post.

In my tests, the same thing happens when using the same image in a blog post.

Here is a post on a test site of mine:

![screen shot 2016-11-23 at 12 32 33](https://cloud.githubusercontent.com/assets/426388/20560329/1366afb4-b179-11e6-895f-1fc48642a183.png)

And here is the original Portfolio post on your site:

![screen shot 2016-11-23 at 12 32 38](https://cloud.githubusercontent.com/assets/426388/20560332/15eceff0-b179-11e6-8f14-956c167064c4.png)

That's to be expected as Facebook does not know or care about the post type: it doesn't have access to that information. Facebook only relies on one thing to build its post previews: [Open Graph Meta Tags](http://ogp.me/). You can use 3 different meta tags to define an image to be used by Facebook in its post preview:
- `og:image`, displaying an image URL.
- `og:image:width` to define the image width.
- `og:image:height` to define the image height.

Here is how the tags look like on your site, for [this post](http://newtao.jpmaney.com/portfolio/shoes-473x315/):

```html
<meta property="og:image" content="http://newtao.jpmaney.com/wp-content/uploads/2016/11/soles-of-your-shoes-1-473x315.jpg" />
<meta property="og:image:width" content="473" />
<meta property="og:image:height" content="315" />
```

The tags are correct. They match the image size, and the image that's used there is [the post's full, non-cropped featured image](http://newtao.jpmaney.com/wp-content/uploads/2016/11/soles-of-your-shoes-1-473x315.jpg):

`http://newtao.jpmaney.com/wp-content/uploads/2016/11/soles-of-your-shoes-1-473x315.jpg`

The tags happen to be added by Jetpack right now, but if you were to use another plugin to manage Open Graph Meta Tags on your site, the tags would still be the same.

What Facebook does with that information is outside of your control, and it's not something you can change from within a plugin. You can learn more about Facebook processes the images [here](https://developers.facebook.com/docs/sharing/best-practices#images).

There are a few things Facebook recommends, that will help you influence the way the images will be displayed:

> Use images that are at least 1200 x 630 pixels for the best display on high resolution devices. At the minimum, you should use images that are 600 x 315 pixels to display link page posts with larger images. Images can be up to 8MB in size.

> the aspect ratio for images is the same across desktop and mobile News Feed. **Try to keep your images as close to 1.91:1 aspect ratio as possible** to display the full image in News Feed without any cropping.

> Images appear in a rectangular format. **You should use a 1.91:1 image ratio, such as 600 x 314 px.**

If you plan on resizing your images to match that image ratio, you'll also want to follow the recommendations [here](http://stackoverflow.com/a/34051854/1045686):

> be wary of white backgrounds around the edge of your image. Facebook will automatically crop off white edges and use the cropped result. This will reduce the size and potentially change the dimensions of your image.

So what does this mean in practice?

**To make sure Facebook doesn't crop your images in its previews, you'll need to respect the 1.91:1 image ratio.** A 1200x630px image is perfect. 600x315px works too. 473x315px, like in your example, won't work because it's not the correct image ratio.

Here is what it would look like when resizing your example to match the requirements:

![resized-photo](https://cloud.githubusercontent.com/assets/426388/20560798/6c7a66d4-b17b-11e6-9d4d-8fb8c55e6385.png)

And here is how it looks on Facebook:

![screen shot 2016-11-23 at 12 51 47](https://cloud.githubusercontent.com/assets/426388/20560834/a1be6016-b17b-11e6-8239-04eea6c56aaf.png)

To test and see what preview Facebook will generate, you can use [Facebook's Debug tool](https://developers.facebook.com/tools/debug/).
