### ISSUE TITLE
How to connect Jetpack on localhost.dev?

### ISSUE THREAD

**Issue by corysimmons** [Automattic/jetpack#5766]
```
Error Details: The Jetpack server was unable to communicate with your site https://foo.dev [IXR -32300: transport error: http_request_failed cURL error 7: Failed to connect to foo.dev port 443: Connection refused]
```

Is it even possible to develop Jetpack on a localhost site?

**Comment by corysimmons** [comment]
https://github.com/Automattic/jetpack/issues/1079#issuecomment-54381841 seems to fix this.

**Comment by corysimmons** [comment]
Nevermind, almost everything is "unavailable in dev mode"...

How can I go about styling certain features (e.g. Jetpack comments) locally?

**Comment by jeherve** [comment]
> almost everything is "unavailable in dev mode".

All the features that rely on a WordPress.com connection won't be available in development mode.

There are 2 ways around this:

1. Use something like [ngrok](https://ngrok.com/) to make your local dev environment publicly accessible.
2. Work from a live sandbox or a staging site.

**Comment by corysimmons** [comment]
Thoughts on providing some dummy data (if the user is in development mode) so users don't have to expose their insecure local machines to the public, or work with the latency of a staging site?

Otherwise, I don't see the point in development mode even existing.

**Comment by jeherve** [comment]
> Thoughts on providing some dummy data (if the user is in development mode)

Yep, we've discussed about this in #385. Nothing has been implemented yet, but that would definitely be a nice addition.

> expose their insecure local machines to the public

One way to work around some of this would be to use Docker, for example, so you're only exposing a web server running inside a container.

> work with the latency of a staging site?

You could use something like [Unison](https://www.cis.upenn.edu/~bcpierce/unison/) to edit files locally and keep them in sync with your sandbox. That makes development on a live sandbox a lot smoother. It also allows you to use a full IDE like PHPStorm, with the perks that it offers (Code Sniffer, auto-completion, and the like).

> Otherwise, I don't see the point in development mode even existing.

Almost half of the Jetpack modules (18 out of 38) as well as all the [theme tools](https://github.com/Automattic/jetpack/tree/master/modules/theme-tools) do not rely on WordPress.com and can consequently be used in Development Mode. While you may not use all those modules, it's still good to be able to configure and customize them locally.

That said, Dev mode is obviously not the perfect answer, as you've discovered. Feel free to jump in and share your ideas to improve the feature in #385!

**Comment by corysimmons** [comment]
Alright, thanks for the info. I don't have time to learn Docker right now. Will do my part and add a thumb to that issue.

**Comment by dsawardekar** [comment]
@jeherve To your comment above about using Ngrok. Would it be possible to do this on vip-quickstart? I can follow up with a PR if you can point me in the right direction.

I'm currently trying to debug an issue with Photon. Some images are being correctly served by the Photon CDN while ther images that use `wp_get_attachment_image` are being ignored. I need to setup a working jetpack copy of our production environment to reproduce this issue on our staging environment.

**Comment by jeherve** [comment]
@dsawardekar To debug Photon issues, it would probably be best to use a live sandbox to make sure you remove all possible connection issues from the equation.

That said, while I haven't personally tried using ngrok and VIP Quickstart, I assume you should be able to follow some of the instructions here to get it to work, since VIP Quickstart uses Vagrant:
http://zachwills.net/setting-up-ngrok-and-vvv-to-share-your-local-wordpress-environment-with-the-world/
http://stackoverflow.com/a/33376313/1045686

**Comment by dsawardekar** [comment]
Thanks @jeherve I was able to setup this up with the links above. Seems like the issue is limited to inline images inside post content. Other images are served correctly. Following up separately on zendesk.

**Comment by hubertnguyen** [comment]
@jeherve , does it mean that if my site mydomain.com is connected to WP, I could debug Jetpack via staging.mydomain.com? 

Also, staging areas are typically protected with an HTTP AUTH password to prevent people and bots from accessing. Wouldn't that be a problem for Jetpack? 

The other solution is to have a server that cannot be resolved by the public DNS system (I'd edit my host file to access it), but it seems like the connection to Jetpack (Jetpack-->server) would be severed too.  

Debugging Photon-related issues is very cumbersome and at the moment we had to disable the image acceleration (using wordpress.com CDN URL rewrite) because there were some bugs that we cannot reproduce offline.

**Comment by jeherve** [comment]
@hubertnguyen If your staging domain is publicly accessible, you will be able to connect Jetpack to WordPress.com there.

If you've added a level of authentication that applies to all requests, including those of WordPress.com, then you won't be able to connect Jetpack to WordPress.com there.

**Comment by hubertnguyen** [comment]
@jeherve , typically the staging stuff would be protected by a basic HTTP Auth at least.
