### ISSUE TITLE
Subscription message for existing subscribers

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#5812]
#### Steps to reproduce the issue
Subscribe to a Jetpack site via the subscribe widget.
Confirm your subscription
Try to subscribe again

#### What I expected
A message telling me I was already subscribed

#### What happened instead
The same success message as the first time I subscribed

Sometimes users may forget they had subscribed (maybe the emails are going to spam) and then they wonder why they can't subscribe.

Is there a reason we can't notify people that they are already subscribed, and show a link to manage their subscriptions?

2945355-t

**Comment by seejacobscott** [comment]
To expand on this, a message that shows to someone that is pending would be fantastic, with instructions to check their email, or visit subscribe.wordpress.com to manage their subscriptions would be fantastic.

**Comment by aheckler** [comment]
I can't repro this (sort of). When I try to subscribe to a site I'm already subscribed to, I see a warning that I've blocked emails from WordPress.com (when I have done no such thing).

**Comment by Stoyan0v** [comment]
This has been addressed in #6603. Regarding the "Pending" error message, I don't think that this is possible.  Currently the widget uses the ["pending"](https://github.com/Automattic/jetpack/blob/master/modules/subscriptions.php#L459) status to display the [success message](https://github.com/Automattic/jetpack/blob/master/modules/subscriptions.php#L527), and I think that there is no "success" status at all. 

If we [change](https://github.com/Automattic/jetpack/commit/49e331bc350905548833cae0f638a3000c59cfca) the "subscribe" method to return error when the status is pending we will never see the success message, but pending message only.
An example how messages will if we make this change:

**When the user is already subscribed**

Before:

![before](https://cldup.com/ls1qCNBzZE-3000x3000.png)

After:

![after](https://cldup.com/KYicCqPurp-2000x2000.png)

**When the subscription is pending**

Before:

![before](https://cldup.com/zxxqP8MpEp-3000x3000.png)

After:

![after](https://cldup.com/o1ayU5kc1Y-3000x3000.png)

As you can see, the success message is never displayed.

**Comment by gititon** [comment]
I tested this and found that it did give me a message that I was already subscribed when I tried to subscribe to it again after confirming:

<img width="344" alt="screen shot 2018-03-20 at 11 40 08 am" src="https://user-images.githubusercontent.com/3246867/37675994-1ac04c98-2c4d-11e8-8a50-78a709f84d55.png">

I added the link to manage subscriptions as requested in this PR, https://github.com/Automattic/jetpack/pull/9093/, so that it looks like this:

<img width="320" alt="screen shot 2018-03-20 at 11 41 01 am" src="https://user-images.githubusercontent.com/3246867/37676054-3ed8e6ee-2c4d-11e8-9e97-2e96dc69c4b0.png">

(This has not been merged yet but should be soon) 

Please reopen if any additional work is required.
