### ISSUE TITLE
Contact Info Widget: Jetpack gives error if Google API key has a referrer

### ISSUE THREAD

**Issue by stephenharris** [Automattic/jetpack#5814]
#### Steps to reproduce the issue

1. Create a Google API key
2. Use "HTTP referrers" for the key restriction, and enter the domain the key is to be used on.
3. Add Contact Info Widget, add the key and supply an address (check 'show map')
4. View the widget

#### What I expected
To see a map

#### What happened instead
I did not see map :). Returning the widget admin you see a message *Sorry. We can not plot this address. A map will not be displayed. Is the address formatted correctly?*

Digging into this, the response from the geocode call is:

```
{
   "error_message" : "Browser API keys cannot have referer restrictions when used with this API.",
   "results" : [],
   "status" : "REQUEST_DENIED"
}
```

The issue is that the widget is using the geocode API in a way which requires a key to be restricted by IP address (if it all). However, it then uses the same key in the browser, which should be restricted by HTTP referrer. 

The upshot being is that if you wish to use the map feature you need to provide a key which is open to abuse by quota thieves. 

#### Potential solutions:

1. Provide two key settings for each of the two services
2. Remove the geocode check
3. Look for 'REQUEST_DENIED' and silently ignore the geocode check in that instance.

**Comment by jeherve** [comment]
I can't seem to be able to reproduce the issue. The map is displayed nicely on my end, even when using a restriction by HTTP referrers for my key:

![screen shot 2016-12-08 at 15 53 36](https://cloud.githubusercontent.com/assets/426388/21014485/8e292f60-bd5e-11e6-9945-be25bed93f1b.png)

That said, maybe I didn't do my geocode API request at the same time as you did.

> Returning the widget admin you see a message Sorry. We can not plot this address. A map will not be displayed. Is the address formatted correctly?

What happens when you delete that widget and create a new one? Are you able to save widget settings with your address, and then and only then check the map option and add the API Key?

**Comment by lancewillett** [comment]
Closing as no reply yet — feel free to re-open if still an issue.
