### ISSUE TITLE
Contact Form: Safari autofill prevents name/email fields from being typable

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#5819]
#### Steps to reproduce the issue
1. Open a Jetpack Contact Form in Safari.
2. Select a name or email field.
3. Try to type if the autofill icon appears in the field.
#### What I expected
The text should've begun appearing filled in
#### What happened instead
No text appeared.

![contact_form_problem](https://cloud.githubusercontent.com/assets/831377/20972948/a0feecec-bc64-11e6-9996-024d129356fa.gif)

**Comment by umairaijaz86** [comment]
Were you able to resolve this ? 

I had the same issue with safari and contact form 7 , the issue was the way safari rendered the CSS , was using bootstrap so it was .form-control on my textbox,  and specifically the height, after a certain px height safari hid the text even though the text value is in the textbox. making the height auto resolved my issue. 

hope that helps..
