### ISSUE TITLE
Shortcodes: ensure editor-views (previews) for each Jetpack shortcode

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5908]
Synopsis: WordPress now allows you to preview each embed and shortcode inside the editor. It would be nice if all Jetpack shortcodes supported this.

Responsible: tdb

User experience: Once this is implemented, pasting a shortcode in the editor should transform it into a preview.

Complete: 0

Difficulty:  40

Last Updated: December 15, 2016 (by @jeherve)

**Comment by jeherve** [comment]
Related:
https://github.com/Automattic/gm2016-grunion-editor

**Comment by davewarfel** [comment]
I realize this is a low priority, but it's been a year since it was initially brought up, and I'd just like to voice my support for it.

Especially for the slideshow view of a Jetpack gallery... when you have 10+ slideshows on one page, it would save A TON of room in the editor. Here's an example of one slideshow I have with 5 images, and how much space it occupies in the editor.

![jetpack-slideshow-preview-in-editor](https://user-images.githubusercontent.com/783021/33347463-2b4b44aa-d450-11e7-87c6-34afe43f40bf.gif)

Thanks, as always, for be open to feedback.

**Comment by MichaelArestad** [comment]
We're going to close this for now because not all shortcodes are going to preview. Instead, some will be aliased as blocks and should oembed/preview. We will instead create issues individually if compatibility presents a problem.
