### ISSUE TITLE
Social Media Icons Widget: Add support for LinkedIn company pages

### ISSUE THREAD

**Issue by lancewillett** [Automattic/jetpack#6010]
Enhancement to existing widget: add support to LinkedIn profile link to enable linking to a company instead of an individual LinkedIn user profile.

This is oft-requested by WP.com customers, internal ref 7555-wpcom — at least 15-20 votes so far to add this.

> Currently, the LinkedIn username only works for personal profiles with the URL format https://www.linkedin.com/in/USERNAME
>
> Company pages on LinkedIn have the format https://www.linkedin.com/company/USERNAME
>
> It would be nice to add support for company pages so that business sites can use this widget to link to their company’s page.

This one is tough because this widget is intended to be super-simple, linking to individual user accounts.

We'd need to rewrite it a little bit to allow either:

1) Enter username or full URL (which would help with YouTube and LinkedIn)
2) Use existing Publicize accounts for this user and site to pre-fill the URLs automatically — see ​https://github.com/Automattic/jetpack/issues/2272 and ​https://github.com/Automattic/jetpack/pull/3218

It'd also be nice to add a help link next to each entry field to point to a documentation page on how to get the username or profile URL.

**Comment by gracie** [comment]
+1 from #569170-chat

**Comment by jeherve** [comment]
Until this is implemented, the `jetpack_social_media_icons_widget_array` filter allows one to add a LinkedIn Company page to the widget:
https://developer.jetpack.com/hooks/jetpack_social_media_icons_widget_array/

**Comment by jeherve** [comment]
#6047 offers one approach, and #6016 is another take on how to solve that problem.

**Comment by Jstachurski** [comment]
+1 from 260552-hc

**Comment by deanpeart** [comment]
This is probably a very slap-dash workaround, but I have found that by entering the URL with a leading '../' will at least cause the icon to direct to your company page. A quick example:

Currently, entering "company/example-company" into the plugin actually results in a URL of "linkedin.com/in/company/example-company", because the plugin adds the preceding "linkedin.com/in".

However, if you enter "../company/example-company", this causes the resulting URL to essentially go into the /in/ sub-directory on LinkedIn, but then jump back up to just linkedin.com/, and then append your page address, so the resulting URL becomes "linkedin.com/company/example-company".

I'm sure that there are plenty of other features that this won't fix, but it has allowed my icons to link to my LinkedIn page when clicked.

**Comment by deanpeart** [comment]
Immediately after working out my aforementioned very slap-dash workaround, I scrolled up and discovered that [#6016](https://github.com/Automattic/jetpack/pull/6016) fixes this, so I have now just used the full URL. Should this now be marked as closed?

**Comment by jeherve** [comment]
@deanpeart You're correct. Closing. Thanks for the heads up!
