### ISSUE TITLE
Sync: Syncing after upgrading seems to be spiking resources

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#6041]
Copying this issue over from a report by @macmanx2.

We're getting a few tickets of sites WSOD'ing or 500'ing (with a memory error on the log) when folks update Jetpack from the Dashboard.

With the help of DreamHost, we’ve identified that the update itself is fine, but Jetpack immediately hitting xmlrpc.php on top of that is what’s pushing it over the edge.

```
[Wed Jan 04 03:38:49 2017] [error] [client IP] Premature end of script headers: xmlrpc.php, referer: .../xmlrpc.php?for=jetpack&token=...&timestamp=1483529927&nonce=...&body-hash=...&signature=...
```

Additionally, Mika Epstein from DreamHost has been repeatedly alerted of usage spikes on her LiquidWeb VPS that correlated with exactly when Jetpack was updated each time (no additional details besides the basic emailed alert were available), so it would appear that we are spiking resources on updates, but it only appears to be affecting certain hosting providers where the limit is low.

**Comment by Ipstenu** [comment]
I managed to get a copy of the error because it happened again last night when I added a site to Jetpack. It's not just the upgrade, it's whenever it runs the sync, it runs a little heavy.

At roughly 19:00 PT I added a new site to Jetpack. It had maybe three posts at the time of being added. About 20 min later I got this email alert:

Time:         Wed Jan  4 19:22:24 2017 -0800
Account:      Account Name
Resource:     Process Time
Exceeded:     1898 > 1800 (seconds)

It went on to tell me that PHP was doing 'a lot' (it's a pretty common alert I get when PHP jobs take 'too long' to finish) but it wasn't going to kill, since it was only 98 seconds over the limit. The error did not repeat, which is expected. When I checked the logs, I saw that it was hitting xmlrpc.php.

The machine is a dual core with 2G memory and PHP is set to 128M. That particular site was brand new, but I saw the same alerts when Jetpack was upgraded on my other sites (and yeah, totally on my crazy site that eats data for breakfast ;) ).

**Comment by kraftbj** [comment]
Having the JP API off _shouldn't_ be related. The module, all in all, is whether to allow third-party API access (e.g. you want interact with XYZ developer's app that uses the WP.com API). The module would, on the site-level, indicate if a user is able to authorize/use the WP.com API like that. _Shouldn't_, but I'll let a dev give final word :)

**Comment by Ipstenu** [comment]
I was under the impression that the sync prioritized api over xmlrpc, and if so, that _miiiiiight_ be why. Since xmlrpc is ... not efficient ;)

**Comment by kraftbj** [comment]
Everything happens over XMLRPC, though. The API module is old naming—it refers to the WP.com API before there was a WP REST API. A wp.com API request is proxied through WP.com and passed through XMLRPC to the Jetpack site. We're working on that, specifically making sure the authentication process works, yadda yadda, but for now, anything between WP.com and a Jetpack site is over XMLRPC.

**Comment by enejb** [comment]
@Ipstenu can you see if https://github.com/Automattic/jetpack/pull/5996 fixes your issue. 
that PR limits full sync to 30 seconds at a time.

**Comment by Ipstenu** [comment]
Installed. I'll keep an eye on the alerts tonight.

**Comment by aheckler** [comment]
Noting here that this originated with 2986086-t.

**Comment by Ipstenu** [comment]
So far this seems to be working well. No more server alerts in 15 hours.

**Comment by lezama** [comment]
Also, #6045 should improve the overload on JP upgrade.
