### ISSUE TITLE
Open Graph: improvements to getimagesize changes

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6061]
Follow up to #5602

https://github.com/Automattic/jetpack/pull/5602#discussion_r94916400

> Blavatars are hosted remotely (on Gravatar), so calling `attachment_url_to_postid` with a Blavatar URL will always fail.

@mjangda Could you give us more details to reproduce the issue, so we can take a closer look?

Thanks!

https://github.com/Automattic/jetpack/pull/5602#discussion_r94916504

**Comment by mjangda** [comment]
> Blavatars are hosted remotely (on Gravatar), so calling attachment_url_to_postid with a Blavatar URL will always fail.

Ah, actually, looks like we've changed things a bit and the `blavatar_*` attempt to use use the site icon first.

My concern is mostly that for Blavatars that are served from `gravatar.com`. For example, on `matt.blog`, the Blavatar URL is `http://1.gravatar.com/blavatar/1dda380e30f5105e49d00ff16adc24a4?s=96`. For this URL, the function `attachment_url_to_postid` will never work since that image is hosted on Gravatar servers not locally on the site so it's a waste to call the function.

**Comment by mjangda** [comment]
The [second thing I flagged](https://github.com/Automattic/jetpack/pull/5602#discussion_r94916504) should be pretty self-explanatory but let me know if there are any questions:

> Instead of doing a reverse lookup using `attachment_url_to_postid` which can be very slow on big sites, can we just call `get_option( 'site_icon' )` to get the id?

**Comment by mjangda** [comment]
> Instead of doing a reverse lookup using attachment_url_to_postid which can be very slow on big sites, can we just call get_option( 'site_icon' ) to get the id?

This was addressed in #6303
