### ISSUE TITLE
VideoPress: Consistency/grammar fixes

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6077]
Current VideoPress card in settings looks like this:

<img width="781" alt="screen shot 2017-01-11 at 8 19 40 pm" src="https://cloud.githubusercontent.com/assets/108942/21875770/903188d2-d83b-11e6-81f1-5e481602b91e.png">

- [x] Should have a period after "Powerful, simple..." subheading, to match other modules.
- [ ] The main explanation text should not be grey/italics (which comes from having the class `jp-form-setting-explanation`)

**Comment by jeherve** [comment]
Maybe we could add the remaining quota there as well? #6003

All in all, I feel we're not doing a great job at explaining the feature here. What will happen when I upload a video via Add Media? I could already do that before, without paying anything, and my videos were ad-free, unbranded, lightweight, and responsive. What does the feature change? What's in it for me?

Should we maybe explain where the videos are uploaded, why it's good to serve videos from a CDN (save bandwidth, serve videos faster, ...), what are the differences with the default video player (videos are converted so they can be played anywhere, in any browser, on any device), ...

**Comment by dereksmart** [comment]
Opened #6085 that adds the period for consistency.  

@beaulebens I assumed what happened is that you upgraded in the past, activated VideoPress, and then removed your subscription before deactivating the module?  

I'm seeing this with no plan and VideoPress deactivated: 
![screen shot 2017-01-12 at 10 16 46 am](https://cloud.githubusercontent.com/assets/7129409/21895429/b6b62a1a-d8b0-11e6-9a1c-47ef2863bcba.png)

We should probably make sure to deactivate VideoPress automatically if we don't detect a plan anymore, but worst case for now is they try to use it and it won't work, since the real magic relies on the plan.  

We should tackle the improved description/verbiage and also the auto-deactivation in the next point release.

**Comment by dereksmart** [comment]
Re-opening for further consideration on the points in my last comment for future release.

**Comment by beaulebens** [comment]
Thanks @dereksmart. I think you're right because I did another clean install and saw what you highlighted.

**Comment by beaulebens** [comment]
Closing as redundant with the new settings UI,
