### ISSUE TITLE
Comments: Add allow logged in user option on the Jetpack Comments form

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#6313]
Currently we do not allow the 'logged user in only' option to be passed to the Jetpack Comments form.

This still requires further investigation. If it is even possible or if it is something that is theme dependent. But the idea is that we would lock down the Jetpack Comments form if the user has the option set in the Settings -> Discussion.

**Comment by jeherve** [comment]
I'm not sure I understand. Whenever I check that option in Discussion Settings, the Jetpack form disappears, as expected.

Do you mean to display the Jetpack form to logged in users as well? If so, what would be the benefit? Since the user is already logged in, they don't need any of the social features the Jetpack comment form would provide.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
