### ISSUE TITLE
Comments/Subscriptions: Create option for "Subscribe" checkboxes to be pre-filled. 

### ISSUE THREAD

**Issue by seejacobscott** [Automattic/jetpack#6422]
User in 3058348-t is requesting the ability to have an option for the 
" Notify me of new comments via email"
and
"Notify me of new posts via email" checkboxes pre-filled when someone is leaving a comment. 

https://cloudup.com/cNDg3b4m_zQ

It looks like this may be attached to something in the WordPress.com side. In the course of the ticket we attempted to add a "checked" attribute into the coding of /jetpack/modules/subscriptions.php but after further digging it appears as though those options are coming from an iframe from WP.com.

**Comment by Fi0navar** [comment]
This would be very helpful for me and - doing a search of the input code, it seems that others are doing this with the core WP Subscription feature. Unfortunate it cannot be done with Jetpack however.

**Comment by jeherve** [comment]
Arguments can be made for both sides, but I'm not sure we would want to make the Jetpack Subscription process opt-out instead of otp-in. Sending 2 subscription confirmation emails (one for the blog, one for the comments on the post) just because you forgot to uncheck the checkboxes seems like a bad practice to me. It could be confusing for some readers, pushing them to mark the emails as spam because they don't know why they received them, and consequently decreasing email deliverability for all subscriptions for everyone using WordPress.com and Jetpack.

I'd be tempted to mark this as `wontfix`, and I would recommend deactivating Jetpack's Comments module and using WordPress' own comment form if you would like more control over the subscription checkboxes. You will then be able to use JavaScript to check the boxes by default, without having to make any changes to Jetpack's plugin files:
http://nathangiesbrecht.com/check-all-checkboxes-chrome-javascript

Here is a bit more reading about subscriptions checkboxes and the opt-in vs. opt-out debate:
https://www.campaignmonitor.com/blog/email-marketing/2010/12/when-it-comes-to-opt-in-newsletter-forms-un-checked-is-best/
https://www.sitepoint.com/marketing-optin-vs-optout-checkboxes/

**Comment by jeherve** [comment]
@samhotchkiss Would you mind weighing in on this?

**Comment by Fi0navar** [comment]
Well I have read all of those and have been dealing with JetPack hoping this would work - hence why this was created. I prefer the JetPack environment fwiiw. If it does not happen, well there you are then.

**Comment by samhotchkiss** [comment]
I'm going to have to side with @jeherve on this, and agree with his reasoning here.  Sorry!
