### ISSUE TITLE
Publicize to Facebook doesn't appear to work for scheduled posts

### ISSUE THREAD

**Issue by arjenlentz** [Automattic/jetpack#6577]
#### Steps to reproduce the issue

Enable Jetpack Publicize to Facebook, Twitter
Create a post to be published in the future

#### What I expected

Post gets published, new items appear on Twitter and Facebook.

#### What happened instead

All except the Facebook post happen.
Note that an immediately published item does generate a Facebook post, so the basic connection works.

**Comment by jeherve** [comment]
I can't seem to reproduce on my end. The problem is most likely specific to your site configuration and the plugins you currently use on your site.

Can you please use Jetpack's Debugger module to send us some more information about your site?

<ol>
<li>Go to the Jetpack page in your dashboard.</li>
<li>Click on the <strong>Debug</strong> link appearing at the bottom of the page.</li>
<li>Click the link that says <strong>"click here to contact Jetpack support."</strong></li>
<li>Fill in the description box and your name and email address.</li>
<li>Click the "Contact Support" button to send us the debug results privately. <strong>It's best not to post this information here, as it contains private details about your site.</strong></li>
</ol>
Thanks!

**Comment by arjenlentz** [comment]
It doesn't Publicize to Google+ either on a scheduled post.
@jeherve I'd appreciate you looking at this - as far as I can tell from the code, there are no external issues possible for this segment of the functionality. If there is a problem with this, it's inside the Jetpack Publicize code making a logic error somewhere.

Hopping this via "Happiness Engineers" rather than developers does not make me happy, or make progress.

**Comment by jeherve** [comment]
>  don't see how this can be affected by other config or plugins though

Many different factors can restrict a post's synchronization with WordPress.com, its submission to different Social Networks on our end, or whether each Social Network accepts or rejects the submission. Something on your site is getting in the way, and we need to find out what.

Luckily, my colleagues have experience with this and will help you debug this and figure out what's going on. If it appears that we can make improvements to Jetpack to work around that problem on your site we will, and one of my colleagues will create a new issue with the necessary details, and you'll be able to subscribe there.

Sending us the debug results should consequently be helpful in starting this debug process.

Thank you!

**Comment by arjenlentz** [comment]
Found it - not all the account connections were shared.

/wp-admin/options-general.php?page=sharing

Issue: The "(shared)" indicator is tiny.
Solution: Make it bigger, and perhaps also have an indicator "not shared".

And it doesn't indicate which user is the one that's accessing the social media account, so with multiple people managing aspects of a site and aspects of the external interactions, this is very unclear - you can't tell from the page for whom the posting will work and for whom it won't.

**Comment by jeherve** [comment]
I'm glad to hear that one of our Happiness Engineers was able to help!

You'll be happy to hear that we've already made some changes to make Shared connections clearer if you manage your Publicize settings via [the WordPress.com interface](https://wordpress.com/sharing/):

![screen shot 2017-03-13 at 10 23 18](https://cloud.githubusercontent.com/assets/426388/23848361/38b60526-07d7-11e7-9d2e-c6ac93bae794.png)

We'll bring some of those UI changes to your self-hosted dashboard soon!

**Comment by arjenlentz** [comment]
Ah, that's good news @jeherve - that looks much clearer.
thanks
