### ISSUE TITLE
Admin Page: improve checkbox status in Firefox

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6581]
The checkboxes displayed in Jetpack Admin Settings display differently depending on your browser:

Here is how it looks in Chrome Version 56.0.2924.87 (64-bit), on Mac:

![screen shot 2017-03-06 at 22 39 52](https://cloud.githubusercontent.com/assets/426388/23652469/61fe7af6-0329-11e7-8908-7cd4b54f21c8.png)

And in Firefox 51.0.1 (64-bit), on Mac:

![screen shot 2017-03-06 at 22 40 59](https://cloud.githubusercontent.com/assets/426388/23652477/6952958a-0329-11e7-8fd5-81542fd151a6.png)

In Firefox, the checkboxes look a lot better when I remove a `-moz-appearance: none;` rule:

![screen shot 2017-03-06 at 22 49 29](https://cloud.githubusercontent.com/assets/426388/23652494/80d61f56-0329-11e7-9b29-492061ad0a29.png)

It would be nice to update the checkboxes to get a similar look across browsers.

**Comment by singerb** [comment]
FYI the issue I originally reported was on Windows. Realized I never said that. :-(

**Comment by jeherve** [comment]
@singerb Could you post screenshots of how things look like for you on Windows? Thanks!

**Comment by singerb** [comment]
Here we go!

Chrome, looks fine:

![chrome-settings](https://cloud.githubusercontent.com/assets/2600397/23708705/c79e5cd8-040e-11e7-9535-3e00aa3f08c5.png)

Firefox, checkbox checked but nothing showing:

![firefox-bad-settings](https://cloud.githubusercontent.com/assets/2600397/23708727/dbf1d5fc-040e-11e7-9ffc-e0179cb34765.png)

Firefox, checkbox checked and `-moz-appearance: none` removed:

![firefox-mod-css-settings](https://cloud.githubusercontent.com/assets/2600397/23708757/f4c034fc-040e-11e7-8353-4f041db2c5c2.png)

**Comment by ashleighaxios** [comment]
Will the current settings work will make this issue obsolete? Cc @MichaelArestad @eliorivero

**Comment by eliorivero** [comment]
It won't be an issue with checkboxes... because we no longer have checkboxes! :D But it's now an issue with radio buttons.
The reason is that WP core uses `:before` to add the styling, which works fine in Chrome

<img width="429" alt="captura de pantalla 2017-03-23 a las 10 24 44" src="https://cloud.githubusercontent.com/assets/1041600/24249813/7071bb84-0fb3-11e7-86a6-0fe648098d31.png">

but not in Firefox

<img width="419" alt="captura de pantalla 2017-03-23 a las 10 24 38" src="https://cloud.githubusercontent.com/assets/1041600/24249812/70680972-0fb3-11e7-8628-26fe24d674c6.png">

and that's because Firefox adheres to [the standard](https://www.w3.org/TR/CSS21/generate.html#before-after-content) and doesn't allow `:before` in `input` elements since they're not a container of other elements like `span`, `div` or `p` are.

**Comment by MichaelArestad** [comment]
@eliorivero nice. I think we can live this for now since it matches core behavior, but might be a nice future improvement.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
