### ISSUE TITLE
Widget Visibility: rules disappear when updating from 4.6 to 4.7.

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6596]
I haven't been able to reproduce on my own sites just yet, but this appears to be an issue for multiple users after updating from Jetpack 4.6 to Jetpack 4.7.

#### Steps to reproduce the issue

1. Start from a site running Jetpack 4.6.
2. Go to Appearance > Widgets and set up some widgets with custom visibility rules.

![screen shot 2017-03-07 at 22 27 21](https://cloud.githubusercontent.com/assets/426388/23678994/91d41102-0386-11e7-90bb-c727b2e95a47.png)

4. Update to Jetpack 4.7.
5. The rules don't appear anymore in the widget settings, but are still applied on the front end.

This was most likely introduced in ##6333.

To figure this out **we'll need to know the exact set of rules that disappeared upon update. It may be limited to specific rules (e.g. #6595).**

----
Reported here:
- 3096698-t
- https://wordpress.org/support/topic/jetpack-4-7-upgrade-removes-widget-visibilitys-original-settings/

**Comment by dereksmart** [comment]
Ok, so I did some very extensive testing and found some things.

Starting on 4.6, I added a widget for each single rule.  I did this for both `show` and `hide`.  

See the full list here: https://cloudup.com/cb98P8kSEpU

The good news is that **the only rule that cleared on upgrade** was the `post type` rule (#6595).  As we know already, these post types will have to be reset by using the `pages` option instead. 

**_HOWEVER_**
I also tested with _multiple_ `or` rules as well.  I found that If there were `post type` rules assigned in the `or` conditionals, on upgrade not only was the `post type` cleared, but the children rules of all the other `or`s below it seemed to be cleared.  I think images will better describe what happens: 

Rules on 4.6: 
![screen shot 2017-03-07 at 6 07 27 pm](https://cloud.githubusercontent.com/assets/7129409/23682440/cf32d3aa-0361-11e7-81d8-e1639a9b4a2f.png)

Rules after upgrading to 4.7:
![screen shot 2017-03-07 at 6 08 40 pm](https://cloud.githubusercontent.com/assets/7129409/23682452/d739aede-0361-11e7-9936-f4136b0b259f.png)

_**This looks worse than it actually is**_
In my testing, although the rules were not visible in the dropdowns, the widget visibility was still following the rules set (i.e. showing/hiding the widgets on the correct pages, minus the post type rule of course).  Also, in order to "fix" this, all you have to do is click `save`, and you should see the dropdowns propagate with the correct values.

**Comment by zinigor** [comment]
I agree, I'd say that the only real problem here is the JS error that is fixed by #6600. Feel free to reopen if there are additional problems that need to be fixed here.
