### ISSUE TITLE
Featured Content: Posts are returned when no tag is chosen.

### ISSUE THREAD

**Issue by anastis** [Automattic/jetpack#6607]
It seems there is bug where seemingly random featured posts are returned when there is no tag chosen from the Customizer.

#### Steps to reproduce the issue
In a clean WordPress installation, install/activate Jetpack and a theme that provides support for Featured Content, such as [Automattic's Shoreditch](https://wpcom-themes.svn.automattic.com/shoreditch/) 
Import the Theme Unit Test file, or create some content.
Make sure a tag "featured" doesn't exist at all.
Make sure some other tags exists and have posts assigned.
Go to Customizer -> Featured Content and make sure "Tag name" is empty.
Save and exit the customizer.
 
#### What I expected
No featured posts should appear.
#### What happened instead
Featured posts appear.

Digging in, Jetpack calls `get_term_by( 'name', $settings['tag-name'], 'post_tag' );` in https://github.com/Automattic/jetpack/blob/master/modules/theme-tools/featured-content.php#L215 
When `$settings['tag-name']` is empty however, WordPress returns a seemingly random term object instead of a falsey value (in my tests it looks like it returns the tag with the lowest term_id).

**Comment by Stoyan0v** [comment]
@anastis Do you use the code from WordPress trunk? I mean, not just 4.7.3, but the development version (https://github.com/WordPress/WordPress)?

I tried to fix this one today, but the `get_term_by` call, you have referenced, returns `false`.

The issue occurs when you use the development version, because the `get_term_by` logic has been changed few months ago ( https://core.trac.wordpress.org/changeset/38677 ).
There is a missing condition that needs to check if the value is empty, and because of that, there is a missing clause in SQL query. I have reported this already: [link](https://core.trac.wordpress.org/ticket/21760#comment:122)

Since the `get_term_by` modification is not part of the core for now, this is more WordPress, than Jetpack issue.

**Comment by anastis** [comment]
@Stoyan0v ah yes, totally forgot to report here the WP version. Yes, that's on the trunk. 
Noticed it during a WP.com theme review, and since everyone's required to work on trunk, well, it totally slipped my mind.

The reviewer suggested reporting it here first, since it's touching a bit of both WordPress and Jetpack. I mean, an empty check (from on this side) would prevent the issue, wouldn't it?

**Comment by Stoyan0v** [comment]
@anastis thanks!
We can check if the value is empty, before calling `get_term_by`, but it's not necessary.

By default the function will return the term object/array if it exists, and `false` if the value is empty or if there is a `WP_Error` ( if the taxonomy is invalid ).

We rely on the fact that we will receive `false` if the value is empty and that's why there is no need to check the it. We just [check](https://github.com/Automattic/jetpack/blob/master/modules/theme-tools/featured-content.php#L219) the response.

**Comment by Stoyan0v** [comment]
The issue has been [addressed in the Core,](https://core.trac.wordpress.org/ticket/21760#comment:127) so this ticket should be closed.

cc @jeherve
