### ISSUE TITLE
Tiled Galleries should be disabled when Photon is disabled

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#6618]
Basically, Tiled Galleries silently use photon even when it is disabled. This is problematic because if photon is breaking on a site (like mine) then you can't use tiled galleries even though it looks like you can.

Alternatively, we could make Tiled Galleries work without Photon when Photon is off. Thoughts?

**Comment by jeherve** [comment]
If we change the current behaviour, we'll need to review a lot of other features in Jetpack. Tiled Galleries is not the only module that uses Photon even if the module is off. Related Posts come to mind, as well as the Top Posts widget for example.

> we could make Tiled Galleries work without Photon when Photon is off.

This wouldn't be great performance-wise, since you'd be loading full size images and then resizing them with CSS. But I guess we could warn the user in the admin, and let them know that they're not using the feature to its full potential.

**Comment by MichaelArestad** [comment]
@jeherve but it's better than them just breaking which is the current behavior. Also, there are responsive images available in core.

**Comment by jeherve** [comment]
Agreed 👍

**Comment by dereksmart** [comment]
This is happening already.  TG/Photon are controlled by the same toggle both ways (activation/deactivation)
