### ISSUE TITLE
Carousel: JavaScript in some gallery settings

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6638]
In #6306, we made some changes to the way carousels are loaded. Unfortunately, in some situations it now creates the following JavaScript error:
`Uncaught TypeError: Cannot read property 'split' of undefined`
On line 451 of `modules/carousel/jetpack-carousel.js`

You can reproduce the issue [here](http://temp.tilestonesource.com/century-wood-series/). I unfortunately haven't been able to reproduce the issue on my end. It seems to happen in some cases in in-page galleries, sometimes in slideshows.

Reported here:
- https://wordpress.org/support/topic/installing-jetpack-4-7-breaks-some-tiled-galleries/
- https://wordpress.org/support/topic/4-7-update-breaks-slideshow-on-pages/

**Comment by jeherve** [comment]
cc @thingalon; I'm hoping you might be able to help with this since you touched that code last month :)

Thanks!

**Comment by Stoyan0v** [comment]
I've checked the [page link](http://temp.tilestonesource.com/century-wood-series/) provided in [this ticket](https://wordpress.org/support/topic/installing-jetpack-4-7-breaks-some-tiled-galleries/) and it seems that the issue is not related to `jetpack-carousel.js`


The client is using the gallery shortcode and the Carousel, but its gallery is located in bottom right side. The issue is that there are some images wrapped in an `a > div` tags ( for example "Ash 318-62-721", "Saddle 318-62-720" etc). 
I am not sure that they have been added using shortcodes and it looks like they have been added manually. The Image parent is a `div` tag and since it doesn't have href attribute we see this error.

cc @jeherve maybe we should [check](https://github.com/Automattic/jetpack/blob/master/modules/carousel/jetpack-carousel.js#L441) if the parent is an 'a' tag first?

**Comment by Stoyan0v** [comment]
UPDATE: I was able to reproduce this issue [here](http://preview.stoyan0v.com/sample-post/), but using Text editor. Here is the [code](https://gist.github.com/Stoyan0v/caa692e5e60149d27e3f4d40105068f3). I still think that such code can't be added using shortcodes or site builder, but only manually.

**Comment by jeherve** [comment]
> I am not sure that they have been added using shortcodes and it looks like they have been added manually. 

They used a gallery shortcode, but their outside container is indeed custom. That shouldn't stop them from using galleries though.

> maybe we should check if the parent is an a tag first?

Yes, I think we should add an additional check for these edge cases.

**Comment by richardmtl** [comment]
Noting that in 3165784-t the user said they still had the same bug even with 4.8.2, but I don't have further info from them because they've decided to turn off the Carousel module to solve their problem. Noting here regardless just in case it continues to crop up.
