### ISSUE TITLE
Widget Visibility Taxonomy All Pages Shows Widget on Pages That "could" Use Taxonomy, but Don't

### ISSUE THREAD

**Issue by pmciano** [Automattic/jetpack#6730]
After creating a custom taxonomy for pages, a user set a widget's visibility to **All pages** for a specific grouping:

![Widget Settings](https://www.evernote.com/l/Ati9OGA7rf5LT4cPWpL9iuOpHQuB5bSHHOwB/image.png)

Instead of appearing on just pages that were in the chosen grouping, it also appeared on pages that *could* have been assigned to that grouping, but were not.

3097313-t

**Comment by kraftbj** [comment]
It seems like there's a couple of ways this option could go?

1. "All pages" means all pages that that taxonomy /could/ be used on, which is what happes now.
2. All pages that uses _any_ term within that taxonomy.

We do the first here: https://github.com/Automattic/jetpack/blob/master/modules/widget-visibility/widget-conditions.php#L621

We could either change the behavior or add an option here for "any term". It hasn't come up since categories are required and I just don't think anyone has thought of wanting a case to show only on posts that were tagged with anything.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
