### ISSUE TITLE
Sharing: Linking to disabled UI in Calypso

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6762]
Now that we have a "Sharing" tab within Settings, we're linking primarily over to Calypso to control those features. The problem is that if those modules are deactivated under the hood, then when you get to the page on Calypso, you get a basically broken experience:

Click either of the link-cards on these blocks;
![screen shot 2017-03-24 at 5 03 28 pm](https://cloud.githubusercontent.com/assets/108942/24363940/8c5d914c-12ce-11e7-8383-174ec13a7775.png)

end up here;
![screen shot 2017-03-27 at 9 20 38 am](https://cloud.githubusercontent.com/assets/108942/24363982/ac0286f6-12ce-11e7-99ea-dc4972650cef.png)

at the URL: https://wordpress.com/sharing/buttons/undefined

I think this is because if you try to hit the "Connections" panel with Publicize disabled, then you're directed to the Sharing Buttons panel. If that's also disabled, then everything breaks.

Ideally we need those UIs to work regardless of if the modules are enabled remotely, but I'm filing this here as well because currently the broken flow is initiated here in Jetpack.

**Comment by oskosk** [comment]
I've come up with three possible solutions to this. The three will take more time than expected as the original code is *really* locked down to just work if the sharedaddy and publicize modules are enabled. 

**Solution 1**

Remove every redirect from the controller, remove the locks for the UI, remove the notices warning about sharedaddy being deactivated and about older versions of Jetpack, remove other deep redirects, mock the object that's supposed to be returned by the API `/sharing-buttons` which only works if the module is enabled, make the save buton enable sharedady on save, make the save button enable Likes module if the likes setting is checked. 

This alternative is being worked in #12766

Currently the sharing buttons tab is 95% functional in this PR. Stuff started breaking by unexpected situations due to the removal of the locks that were preventing any render if the modules were disabled. 

Still need to implement everything related to Publicize

**Solution 2**

_Tested on a branch without PR_

Automagically enable the modules if the user reaches the `/sharing/buttons` or `/sharing/` tabs.

This will demand a thorough review because we need to touch the site reducer for udpating `options.active_modules` array after a module is activated. We still need to handle Likes activation somehow


**Solution 3**

_Tested on a branch without PR_

Put an **activate Sharing** toggle on top of sharing settings. Make the save button magically activate LIkes module. if the likes checkbox is checked. 

In all three cases, error handling if the activation failed is quite messy and things break due to version/module locks that are everywhere in the code. 

*Writing this down as I don't think this will be easily shipped today. Stuff will also require design review as we're introducing practically a new interface, there are checkbox there that probably need to mutate into toggles, etc*

**Comment by jeherve** [comment]
This has been fixed since the link doesn't appear if the module isn't active anymore:

![screenshot 2017-06-02 at 13 06 18](https://cloud.githubusercontent.com/assets/426388/26723326/56abdff4-4794-11e7-8425-52859208c382.png)
