### ISSUE TITLE
Update .mo files for partly translated W.org languages to latest approved strings

### ISSUE THREAD

**Issue by joendotcom** [Automattic/jetpack#6780]
#### Summary
Jetpack .mo files for languages that are not fully translated on translate.wordpress.org must be manually updated to include latest approved strings. Current strings need updating.
**(Ref 3119563-t)**

#### Steps to Reproduce
1. Change site language to Czech (cs_CZ)
1. Create a page with a gallery and enable carousel.
1. Open said page and click on gallery to open carousel.

#### Expected Result
Text in comment box below image shown in Czech ("Napište komentář...").

#### Actual Result
Text in comment box below image shown in English ("Write a Comment...").

##### Translated & approved string in in GlotPress:
https://translate.wordpress.org/projects/wp-plugins/jetpack/stable/cs/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=610280&filters%5Btranslation_id%5D=27572271

##### Screenshot:
![carousel_text_not_translated](https://cloud.githubusercontent.com/assets/8905369/24380527/2091e3b8-134c-11e7-9542-2babc25852c5.png)

**Comment by jeherve** [comment]
@zinigor Do you think you could take a look? I believe this may be because:
1. We haven't run `tools/export-translations.php` in a long time.
2. You added a 50% translation threshold in fb54ae9108a23fbe6a9f41f3f995df233b832cc3, so .mo files for the languages that have very few translations never get updated in Jetpack. In this case, should we just delete the whole .mo file from Jetpack, since it never gets updated anyway?
