### ISSUE TITLE
Sitemaps: 404 error when trying to load the sitemap

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6819]
Problem introduced in #5503

#### Steps to reproduce the issue

1. Go to Jetpack > Settings in your dashboard, and enable the Sitemaps module.
2. Go to `http://yoursite.com/sitemap.xml`
3. In some cases, all you will get is a 404 error page:

This seems to happen here:
https://github.com/Automattic/jetpack/blob/master/modules/sitemaps/sitemaps.php#L140-L142

Reported in p8oabR-1p-p2

**Comment by eliorivero** [comment]
The only way I found to reproduce this is to go to the database and delete the posts of `jp_sitemap_master` type.

It looks like `schedule_sitemap_generation()` is not running so `Jetpack_Sitemap_Builder::update_sitemap()` is never called. Maybe we should call it when the module is activated.

The non-WP 404 page occurs due to the use of `die` instead of `wp_die` passing 404 as response argument.

I'll continue looking into this.

**Comment by eliorivero** [comment]
Found a couple of issues, but fixing them doesn't fix this issue

`sitemap-librarian.php`
```
jp_sitemap_filename( MASTER_SITEMAP_TYPE ),
```
should be
```
jp_sitemap_filename( JP_MASTER_SITEMAP_TYPE ),
```
This line also calls `jp_sitemap_filename` without a second parameter and that functions expects it.
