### ISSUE TITLE
Sitemaps: image sitemaps do not display in browser

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6822]
Image sitemaps, although listing all images on a site, don't appear to load in the browser. Here is an example:
https://jeremy.hu/image-sitemap-1.xml

If you view source you'll see that the sitemap contents are indeed there.

**Comment by nbloomf** [comment]
It looks like some strings need to be entity encoded.

For example, see [this line](https://github.com/Automattic/jetpack/blob/1ceeede50b918654b16c12d42f72acd06ea37ef8/modules/sitemaps/sitemap-builder.php#L1258).

**Comment by dereksmart** [comment]
The images seem to load for my image sitemap 

https://dereksmart.wpsandbox.me/image-sitemap-1.xml

**Comment by beaulebens** [comment]
I don't know if it's related, but I am seeing this on one of my test sites where WP Super Cache is installed. WPSC is including its output at the bottom of the sitemap output:

```
<!-- Dynamic page generated in 0.664 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-04-04 15:44:48 -->

<!-- Compression = gzip -->
```

I ran the entire output through an XML validator, and it looks like at least part of the problem is escaping. We are allowing through `&` characters in image titles, which are not allowed in XML. We need to either encode them directly, or just wrap all `title` elements in `cdata`.

**Comment by macmanx2** [comment]
Just adding a note here that Google is rejecting the image sitemaps as invalid, I assume due to the character encoding issue (as that's all the third-party validators seem to be highlighting, I really with Google provided their own validator).

**Comment by lamdayap** [comment]
user reported similar issue in 3162307-t

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/google-is-unable-to-read-the-sitemap-of-my-blog-2/

**Comment by kraftbj** [comment]
Need to apply `the_title_rss` filters which will apply the same filters as Core.

**Comment by macmanx2** [comment]
user reported same issue in 3211788-t

**Comment by macmanx2** [comment]
user reported same issue in 3232464-t
