### ISSUE TITLE
Admin Page: support block does not appear under Jetpack > Settings

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6859]
#### Steps to reproduce the issue

1. Go to Jetpack > Settings.
2. Play with features a bit.
3. A question pops up. Scroll down to the bottom of page; I'd expect the support block there, it used to be there in past Jetpack releases.
4. It's not there anymore.

**Comment by eliorivero** [comment]
Support block is always there for me (except in the Apps tab, and it has been that way by design since we initially launched it). Perhaps your build is corrupted?

<img width="761" alt="captura de pantalla 2017-04-03 a las 10 28 01" src="https://cloud.githubusercontent.com/assets/1041600/24611364/3c791a72-1858-11e7-86d8-5d9a40ba1b2b.png">

**Comment by jeherve** [comment]
I actually can't reproduce anymore. Weird. Closing.
