### ISSUE TITLE
Publicize: Only publishes to accounts connected by original JP user

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#687]
There is currently a failure for Twitter to publicize to the correct account.

Steps to Reproduce:

1. On a new site, connect the site to Jetpack using WPCOM Account A using the local site admin.
2. Connect to Twitter via Settings->Sharing using Twitter Account 1.
3. Do *not* select option to share with all users.
4. Post a new post. Post shared with Twitter Account 1.
5. Create a new user (tested with Administrator)
6. Log out of local site, WPcom and Twitter.

7. Under the new user account, connect the user to WordPress.com using WPCOM Account B.
8. Connect to Twitter via Settings->Sharing using Twitter Account 2.
9. Do *not* select option to share with all users.
10. Post a new post. Notice in the Publish box that Twitter Account 2 is listed.

Expected:
The second post to publish to Twitter Account 2 only.

Actual:
The second post publishes to Twitter Account 1 only.

Reported in 1845527-t and confirmed by me on a test site. Does not occur on WordPress.com.

cc: @justinshreve

**Comment by kraftbj** [comment]
Noting that we're seeing a number of reports of this reoccurring. Have not yet independently confirmed yet.

**Comment by kraftbj** [comment]
@csonnek and I confirmed this came back:
1. On a WP site with JP/Publicize activated.
2. The main admin user who activated Jetpack add a Twitter account, shared.
3. A secondary user, linked to JP, adds a non-shared Twitter account.
3. Main user publishes a post -> Publishes to shared Twitter account :+1: 
4. Secondary user publishes a post -> Publishes to shared Twitter account, does NOT publish to secondary user's individual Twitter account.

**Comment by FellowTuts** [comment]
I admit that this issue is with G+ too with slight change. Facing the issue since last one year.

1. On a WP site with JP/Publicize activated.
2. The main admin user who activated Jetpack add a G+ account, non-shared.
2. The main admin user who activated Jetpack add a G+ account, shared.
3. A secondary user, linked to JP, adds a non-shared G+ account.
3. Main user publishes a post -> Publishes to shared G+ account :+1: and publishes on non-shared G+ :+1: 
4. Secondary user publishes a post -> Publishes to shared G+ account, does NOT publish to secondary user's individual G+ account.

Post by main user: http://fellowtuts.com/informative/what-is-android-brief-introduction-to-android/ Two G+ shared link at end of post.
![main](https://cloud.githubusercontent.com/assets/7893638/6313235/5fa96602-b9c6-11e4-87af-2308a6198c4e.png)


Post by secondary user: http://fellowtuts.com/jquery/5-ways-to-disable-right-click-using-jquery-or-javascript/ Only one G+ shared link at end of post.

![sec](https://cloud.githubusercontent.com/assets/7893638/6313237/6da88d3c-b9c6-11e4-9956-da0bdea0c103.png)

**Comment by jkudish** [comment]
This has been fixed (in a more complete fashion -- we missed something last time) on the WordPress.com side. Please let me know if any of the related issues persist.

**Comment by kraftbj** [comment]
Thanks @jkudish. @csonnek and I reran our tests and confirmed.

**Comment by rudzki** [comment]
Report in 2216563-t as well. /cc @justinshreve
