### ISSUE TITLE
Masterbar: add button to visit site

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6877]
With the new Masterbar, you can get to the front end by clicking My Sites, then your site at the top of the list. it's not obvious at first, though.

> have you planned to replace the “Visit Site” link with something else? I have always used it before and now I keep looking for it, not finding, and instead opening a new tab and copying the URL without the wp-admin part.

@rickybanister came up with a possible solution:

<img width="295" alt="o6kzggcdn--2000x2000" src="https://cloud.githubusercontent.com/assets/426388/24625531/947ab40e-18af-11e7-8907-aae04ef5566c.png">

Before we implement this, we need to be sure it will scale well in other languages.

**Comment by rickybanister** [comment]
I tried out a few translations of 'visit' across maybe 30 languages. Mostly it's a short word since it's fairly common and non-technical. In Finnish it's 9 characters. In Indonesian it's 11. And in Lithuanian it's 12.

I think it can still work with a text button—we already have the same constraint with the nav items below.

**Comment by rickybanister** [comment]
cc @mtias

**Comment by vindl** [comment]
* Should we add this to WordPress.com masterbar too?
* Should we show this button on WP admin pages only?

**Comment by rickybanister** [comment]
I'm waiting to see if there's more support for this solution, but I would propose changing to this pattern in Calypso and on the WordPress.com frontend masterbar
