### ISSUE TITLE
Settings UI: automatically save each setting instead of relying on a "Save Settings" button

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6891]
> why should I be looking and clicking a Save Settings button, if on the majority of modules the settings are saved automatically?

> React allows us to track state changes on virtually every interaction component, so there’s no reason why we can’t auto-save when changing radio buttons.

Discussion here: p8oabR-1p-p2#comment-210

**Comment by jeherve** [comment]
cc @keoshi

**Comment by keoshi** [comment]
Now that we have the [intermediary state back](https://github.com/Automattic/jetpack/pull/6871) this could be especially valuable.

**Comment by zinigor** [comment]
I wanted to create a separate issue, but I think the problem fits in the scope of this one.

When you try to toggle several things at once you can get a temporarily incorrect state of the UI because one request returns new data while the other one is still running. I can get the error almost every time when I try to trigger changes on both custom content types and on minileven.

I think we need to restrict settings changes to one request at a time.

**Comment by jeherve** [comment]
Closing as duplicate of #6860
