### ISSUE TITLE
Align Jetpack Site stats block with Calypso

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#6976]
I think we should align the two stats blocks.

Pros:
* consistent experience
* can start utilizing Calypso insights block in tandem
* can switch to use the tab navigation ([if we move plans)](https://github.com/Automattic/jetpack/issues/6973) for days/weeks/months/insights?
* less unique code to maintain (if we can keep it in sync with Calypso...)

Cons:
* less dashboard-y?
* maybe that's not a bad thing?

I'm also open to other ideas.

#### Current JP stats block
![image](https://cloud.githubusercontent.com/assets/1123119/25024268/6f2d7288-205a-11e7-8877-2bab92bda500.png)

#### Current Calypso stats block
![image](https://cloud.githubusercontent.com/assets/1123119/25024278/79cdb428-205a-11e7-9d0d-1d2e2fdf87ed.png)

**Comment by eeeeevon13** [comment]
Now that we have this callout to drive people to Calypso stats, I feel like this issue is no longer valid. We're actually trying to promote Calypso stats as "enhanced"
<img width="1262" alt="Screenshot 2020-06-08 15 10 04" src="https://user-images.githubusercontent.com/49159284/84075740-453e7400-a99a-11ea-966e-206f22925e6a.png">
Going to close this for now, @scottsweb  @folletto  let me know if I've missed anything.

**Comment by scottsweb** [comment]
@eeeeevon13 - the screenshot you have shared there is the old stats view in Jetpack (one of three stats views). I believe this issue is looking to update the stats dashboard on the Jetpack dashboard, to be more similar (if not the same) to the one on WordPress.com.

There would be some advantages to doing that still (it might mean we can retire the view you found for example)... although with the length of time this has been open, it seems unlikely to happen soon.
