### ISSUE TITLE
Remove the Protect card from the JP Dashboard

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#6979]
While this is kind of a fun stat to see, I don't it's current iteration is particularly helpful or inspiring. Perhaps we can remove it for now, but revisit the idea in a future iteration.

![image](https://cloud.githubusercontent.com/assets/1123119/25054905/f7636c9e-211c-11e7-8df5-19560dc91174.png)

CC @jeffgolenski @rickybanister @richardmuscat

**Comment by jessefriedman** [comment]
I have to disagree with this path. Protect is a highly valuable "set it and forget" it feature. It's important to make sure users understand the value in the feature. 

If they aren't reminded by it, or by the fact that every site, even theirs is under bother based brute force attack they are left uneducated and unaware of the problem.

**Comment by jeffgolenski** [comment]
There are an awful lot of folks who love to see this stat. I think it definitely loses value if it disappears. There's a ton of ways we can improve this though. Maybe work it into the expanded stats within the dashboard somehow... like we do with akismet?

**Comment by samhotchkiss** [comment]
Protect Count Forever!

It's a great constant reminder of what we're doing, and gives them a powerful reminder of WHY they shouldn't remove Jetpack.

**Comment by jeherve** [comment]
Closing for now, but we can reopen once we have a redesigned version / mockup of that card.

**Comment by MichaelArestad** [comment]
@samhotchkiss @jessefriedman @jeffgolenski This stat isn't actionable (doesn't encourage either interaction with the site/stats or encourage upgrades) and does not give any idea of how much it has changed. It doesn't let the user know much of value. I'm not opposed to moving it elsewhere, but I'm pretty sure it's taking up prime real estate without much benefit.

**Comment by jessefriedman** [comment]
I disagree that a stat needs to be actionable to have it take up real estate. It's absolutely valuable to both the user and to Jetpack.

**Comment by rickybanister** [comment]
I'm interested in hearing opinions from folks that didn't work on Brute Protect :)

I don't feel I fall in either camp here, I think that number is useless, which makes that card in its current form useless. It doesn't tell me whether '139' is good or bad, is that more or less than usual, is that more or less than other sites like mine? Should I be worried or feel good about 139? Should I upgrade my hosting because of that number? Should I turn on SSO and turn off my login form? Can I even do that? If I don't have monitor turned on how will I know if Protect fails to protect me? If I don't have backups and scans active how will I fix my site if Protect fails me? 

We need to stop thinking in terms of 'features' and think in terms of a security 'blanket'. All of these cards and notifications need to encourage me to create a complete security solution. This card should say 'We blocked 139 attacks this week, that's twice as much as last week. You don't need to lose sleep, but we recommend you turn on SSO and shut off your login form. While you're at it you might want to pay for a higher tier of our service in case your site is taken down by some other form of attack.' 

That would actually be useful to me, a total systems novice.

**Comment by jessefriedman** [comment]
I'm sure it may look biased considering the original Brute Protect employees may be the ones fighting for the data to remain. I assure you it's more than sentimentality. Jetpack Protect is the most important free security feature included with Jetpack. When users see that we have blocked just 1 attack, they understand that their site is vulnerable and that hackers do not discriminate.

**Comment by rickybanister** [comment]
Any thoughts on the rest of my comment @jessefriedman?

**Comment by dereksmart** [comment]
Quoting Muscat (not from BP) from related issue #6978 

> I don't think we should remove them simply because they're not helpful/inspiring enough (taking your comment from #6979) until we have an idea of how to make the dashboard as a whole more helpful/inspiring.

> While they may not be super useful, they serve a purpose which will be neglected if we just removed them.

No matter what background someone has, it's true that this card shows that Jetpack is doing something of value.  I like the idea of expanding on this to make it even more helpful, but not the idea of removing it just because it's there.

**Comment by richardmuscat** [comment]
@rickybanister please se my related comments here: https://github.com/Automattic/jetpack/issues/6978

You raise a lot of good questions in your comment but I don't think the answer to any of them is to remove the protect and photon cards without a replacement :-)

**Comment by rickybanister** [comment]
@richardmuscat, your comment there makes total sense and I think is 100% in line with my comment above:

> I think that number is useless, which makes that card in its **current form** useless

I don't want to remove it, I want to improve it, iteratively and quickly. 

I'll re-raise my questions above—for any Brute Protect folks or any other folks, are there easy and quick ways we can provide users with more context for how Protect is actively helping? The all-time attacks prevented number shows users _something_ about Jetpack helping protect them, but I would love to be able to show users more, or ensure they have more than just Protect 'protecting' them since it's not enough on its own. 

Here are a few quick ideas (from a security novice, someone that just wants to turn on a big master switch and never think about it again):
* We display the date they first activated protect so there is slightly added context: `Jetpack has blocked 139 attacks since June 1 2016` That would at least give them two data points.
* We turn this card into a security health card, not just a Protect card. If they only have Protect active, but not SSO, no backups, no scans, no monitor, no autoupdates then we show one green checkbox and several somewhat alarming red Xs that link them to activate those other features. Let them know that they need a total security solution to really be safe.
* Similar to the previous idea, we could show 'tips' for other features that are related to active features that a user already loves. 'You like photon, you should get video'. 'You feel safe with Protect, you'd like uptime monitoring notifications'. We never really did much to algorithmically sell our features.
* We could explain better in-context how protect works, while explaining some of the other vulnerabilities sites can have (similar to the idea above, but more of a whitepaper than a tool).
* We could correlate attacks to other site events—did a post go viral leaving them more exposed with new traffic vectors? Is that how ddos even works?
* A graph of attacks over time, showing the long-term value of Protect, or showing that attacks can come at any time. 
* Maybe we just make these cards more compact so they have less impact if the data doesn't change very often. This would create more room in the 'hierarchy' of the dash to show timely alerts or upgrade banners. Currently everything is the same 'noise level' which probably prompted this and the photon removal issues. 

Those were just a few ideas off the top of my head, hopefully refocusing this debate toward tangible ways to quickly improve the dash.

**Comment by richardmuscat** [comment]
@rickybanister disagree that the card and info are useless. 

You put forward a lot of interesting ideas but I thought the issue was that Michael want to remove the card.

IMO, this issue and the photon one should be closed and then the whole thing addressed holistically when/if we have a proper second iteration of the dashboard.

**Comment by richardmuscat** [comment]
@rickybanister / @MichaelArestad -- a quick addendum as I just noticed this.

[This comment](https://jetpack.com/2017/04/19/protection-from-common-form-of-hacking/#comments) from a user just in this week:

> According to my dashboard, Jetpack has blocked 12,572 malicious attempts on my site.

I strongly think that decisions of these sorts need to be extremely user-informed rather than based on personal preference. In _this user's_ opinion (not mine) the stat is useful. Makes him happy enough that he left a comment just to back up the blog post content. Unsolicited.

I think before we make UI decisions (especially about stats) we need to be surveying users and running user tests. I believe for a while we had a link on the dashboard asking users what they want to see in the dashboard -- have you looked at that?

**Comment by MichaelArestad** [comment]
This seems to have heated up. Let's keep this conversation civil, please. I am looking into the data. I did ask you all for your feedback on earlier posts for a reason and I did CC you @richardmuscat as I knew you would have insight. This was intended for discussion, not immediate implementation. If you would like to move this conversation elsewhere, I am happy to oblige.

The idea to remove this was not made in a vacuum and we are considering the dashboard holistically, I assure you.

**Comment by georgestephanis** [comment]
> I'm interested in hearing opinions from folks that didn't work on Brute Protect :)

I'm very much in favor of the number being there, it's a perception thing.  Demonstrates value.  I'd be fine merging it into the same status box that says how many spam comments we've nuked for them too.

**Comment by eliorivero** [comment]
I'm also in favor of keeping the number there. It shows that the Protect module is actually doing something, and something very important.

This is another element that would make users ask themselves "oh but if I deactivate Jetpack I will lose the protection against malicious attacks" if they ever consider deactivating Jetpack.

It would cause confusion to remove this since users will not know what Protect is doing. They might even think it's bloatware or something similar.

**Comment by macmanx2** [comment]
From a support perspective, a decent-but-not-huge number of users have contacted us to ask what the number means, and after an explanation, they are very happy to have it.

No one has contacted us to ask how to remove it or to let us know that they don't like it.

There is room for improvement (as evidenced by users contacting us to find out what it means), perhaps even a separate Security Dashboard, but removing it entirely seems like the wrong first step to that.

Without this counter, Protect would be an invisible feature. Users would have to consider locking themselves out of their site if they wanted to see if it was working (or contact support "I don't think Protect is working."). At the very least, this number let's them know that Protect is doing something.

In comparison, Photon is largely an invisible feature, and we do get support requests asking us to confirm if it's working or not. Some day, something like a "Bandwidth Saved" meter would be awesome as proof that Photon is working, but that would be a gargantuan task to build. Protect's counter is already there, it works, let's keep it that way until we can make it better. :)

**Comment by rickybanister** [comment]
>a decent-but-not-huge number of users have contacted us to ask what the number means, and after an explanation, they are very happy to have it.

I think that sort of explains where I was coming from—the number doesn't mean a whole lot to me. Rather than remove it, I'd like to hear what folks think we could do to provide context around it. Perhaps it's just adding a label like `Without Jetpack protecting your site it could have been infiltrated 975 times` (not exact wording, but I hope you get what I mean). 

Same for photon—calculating bandwidth would be huge, but the user could do a really vague multiplication of their site traffic times the number of mbs we have uploaded to Photon (calcing the total media upload I imagine is a much easier for us).

**Comment by jeherve** [comment]
> I'd like to hear what folks think we could do to provide context around it. 

In my experience, context is indeed what most people need; once they understand that each increment of that number is a good thing, because it means one more person or bot got blocked from accessing their site, they're all good. Although I often go into more details, so folks understand that it's normal for any WordPress site to be attacked by bots as soon as it's public, and that it doesn't mean they are being targeted.

**Comment by rickybanister** [comment]
What if we made the box more 'timely'. If we've blocked an attack today or this week we could say `1 attack prevented today, 975 since July 2014` or `23 attacks blocked this week, 975 all time`. That at least reminds them that the risk is ongoing and we continually have their back.

**Comment by jeffgolenski** [comment]
@rickybanister that's exactly what we should be doing. or even moving to a more visually appealing representation like a graph so we can add it into our stats arena. 

I remember working on some preliminary design concepts with this right when we first started working at automattic. I remember there being a lot of conversation about it being technically difficult to do? @samhotchkiss @dereksmart

**Comment by samhotchkiss** [comment]
It has some technical hurdles, but it's not impossible.

That said, I'm probably the best person to do it, and I'm about to go on leave for a while, so it'd be best if we can circle back around in August when I'm back

**Comment by rickybanister** [comment]
Why is that? Is something lacking documentation?

**Comment by samhotchkiss** [comment]
It's just that I'm much more intimately familiar with that code, especially since the refactor a couple years ago, so it would probably take someone else at least 3x as long

**Comment by jeherve** [comment]
Related: #5162
