### ISSUE TITLE
Warning: Missing argument 2 for Jetpack_Photon::filter_srcset_array()

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#7075]
I have at least one ticket with this error, and possibly more. If you google it, you get at least 500 results, so other sites are experiencing it. The original report came in 3180619-t. Here's the full error, which is displayed on the site:

> Warning: Missing argument 2 for Jetpack_Photon::filter_srcset_array(), called in
/home1/golfingl/public_html/wp-includes/class-wp-hook.php on line 298 and
defined in
/home1/golfingl/public_html/wp-content/plugins/jetpack/class.photon.php on line
629

>Warning: Missing argument 3 for Jetpack_Photon::filter_srcset_array(), called in
/home1/golfingl/public_html/wp-includes/class-wp-hook.php on line 298 and
defined in
/home1/golfingl/public_html/wp-content/plugins/jetpack/class.photon.php on line
629

>Warning: Missing argument 4 for Jetpack_Photon::filter_srcset_array(), called in
/home1/golfingl/public_html/wp-includes/class-wp-hook.php on line 298 and
defined in
/home1/golfingl/public_html/wp-content/plugins/jetpack/class.photon.php on line
629

>Warning: Invalid argument supplied for foreach() in
/home1/golfingl/public_html/wp-content/plugins/jetpack/class.photon.php on line
632

Spotted on sites using WordPress 4.7.4 and Jetpack 4.8.2.

I suppose that this could be a plugin conflict or theme conflict, but at least one of the sites in question is using a WordPress.com theme. I will ask that they do the plugin dance.

**Comment by richardmtl** [comment]
Many of the site affected are using the [Fluida](https://wordpress.org/themes/fluida/) theme.

**Comment by richardmtl** [comment]
Another report in 3179754-t

**Comment by kraftbj** [comment]
I'm thinking this is from a theme/plugin running the same filter that our function is hooked on without passing everything to it. 

https://github.com/Automattic/jetpack/blob/223c2d906ac66722c5ede88019ba4faf5f0b25b1/class.photon.php#L629 for our impacted line.

In Fludia, it is due to this line https://themes.trac.wordpress.org/browser/fluida/1.3.2/includes/loop.php#L246

I wrote in to the theme's dev at https://wordpress.org/support/topic/php-warning-due-to-wp_calculate_image_srcset-filter/ and proposed a PR #7090 that would defensively code it on our end.

**Comment by richardmtl** [comment]
3184075-t

**Comment by richardmtl** [comment]
3185663-t
