### ISSUE TITLE
Sharing : Text only Facebook button shows count in a blue patch

### ISSUE THREAD

**Issue by nagpai** [Automattic/jetpack#7196]
#### Steps to reproduce the issue
1. Enable sharing buttons on a test site
2. From My Sites >> Sharing >> Sharing Buttons >> Button styles , choose Text Only buttons
3. Create a post and share it at least once on facebook
4. Check the sharing button, you will see the count displayed in a blue patch 

![sharing-bug-fb-icon](https://cloud.githubusercontent.com/assets/4162931/26167745/5169191c-3b55-11e7-98da-532d26a6802d.png)

#### What I expected
Only text buttons
#### What happened instead
I could see the count as well in an ugly blue patch

#321969-hc

**Comment by jeherve** [comment]
The non-circular design of the sharing count seems to be caused by the theme; it overwrites the default sharing styles.

The count itself is there by design; sharing counts are added to all button styles, even "Text Only" buttons. To disable sharing counts on a Jetpack site, you can use the `jetpack_sharing_counts` filter:
https://developer.jetpack.com/hooks/jetpack_sharing_counts/
