### ISSUE TITLE
jetpack needs a cleanup on notices and warnings

### ISSUE THREAD

**Issue by lvnilesh** [Automattic/jetpack#7332]
PHP Notice:  Trying to get property of non-object in /var/www/html/wp-content/themes/x/framework/functions/global/classes.php on line 422

PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/wp-content/plugins/jetpack/sync/class.jetpack-sync-module-updates.php on line 203

**Comment by kraftbj** [comment]
The first notice appears to be related to the theme. Can you provide more context for the Jetpack connection.

The second notice will be fixed via https://github.com/Automattic/jetpack/pull/7326 . Generally, it would be due to some theme information that is expected not being present.

I'm going to close this, but pending context for the first notice, we can reopen it.

**Comment by lvnilesh** [comment]
Thanks.
