### ISSUE TITLE
Image Sitemap displays pages which aren't published yet - 404 for crawlers!

### ISSUE THREAD

**Issue by Ne0Logic** [Automattic/jetpack#7333]
#### Steps to reproduce the issue
Install WordPress and Jetpack. Activate the sitemaps. Add a post with images and schedule it for publication in the future. Visit the image-sitemap-1.xml generated by JetPack.

#### What I expected
Only the images of pages and posts which have been published.

#### What happened instead
All images, including those of posts scheduled for publication in the future. Not only the image is there, but also a link to the page on which the image will appear:
```
<url>
  <loc>https://site/?p=202</loc>
  <lastmod>2017-05-27T23:18:44Z</lastmod>
  <image:image>
    <image:loc>https://_site_/wp-content/uploads/2017/05/imagename.jpg</image:loc>
    <image:title>image title</image:title>
  </image:image>
</url>
```
(Site, image name and image title have been replaced.)

Result: search engine crawlers try to reach those pages, but as they haven't been published yet, they get a 404 error.

**Comment by Ne0Logic** [comment]
@zinigor the issue is in jetpack/modules/sitemaps/sitemap-librarian.php

The function query_**posts**_after_id used to create the sitemap of posts and pages does...
```sql
SELECT * 
FROM $wpdb->posts
WHERE post_status='publish'
	AND post_type IN ($post_types_list)
	AND ID>%d
ORDER BY ID ASC
LIMIT %d;
```

... thus clearly taking into account the post status, while the function query_**images**_after_id used in the creation of the image sitemap does...
```sql
SELECT *
FROM $wpdb->posts
WHERE post_type='attachment'
	AND post_mime_type IN ('image/jpeg','image/png','image/gif')
	AND ID>%d
ORDER BY ID ASC
LIMIT %d;
```

... not taking into account the post status of the parent at all. My first reflex was to join with the posts table on post_parent with post_status='publish' on the joined parent. However there are a number of images which aren't in a parent post (like the logo etc) and they have post_parent 0. So my solution now is to add a condition to the WHERE clause:
```sql
SELECT *
FROM $wpdb->posts
WHERE post_type='attachment'
	AND post_mime_type IN ('image/jpeg','image/png','image/gif')
	AND ID>%d
	AND post_parent IN (
		SELECT 0 FROM dual
		UNION
		SELECT ID FROM wp_posts WHERE post_status='publish'
	)
ORDER BY ID ASC
LIMIT %d;
```

The 0 allows all non-post related images to appear. Other images are only included if their parent is in status 'publish'.

Hope this helps!

**Comment by zinigor** [comment]
Thank you, that will definitely help! I'm currently working on some Sitemap improvements as well (#7335), and will take this into account.

**Comment by vinerz** [comment]
Hey guys! I work with composer auto-install from wpackagist on my Heroku setup, is there any workaround I can add now to prevent this data from leaking on the sitemap?

**Comment by zinigor** [comment]
@vinerz until this is fixed you can use a filter to skip adding images to the sitemap. It's called `jetpack_sitemap_image_skip_post`, and you can use it something like this:
```
add_filter( 'jetpack_sitemap_image_skip_post', 'jetpack_filter_sitemap_images', 2, 10 );

function jetpack_filter_sitemap_images( $add, $post ) {
    // add your checks on the $post object here
   return true; // or return false in case you need to skip the image
}
```
This filter will only run on sitemap generation, not on every sitemap load, so it will not slow your sitemap down.

Please let me know if it doesn't work or you had something else in mind.

**Comment by vinerz** [comment]
@zinigor sounds awesome mate! Thanks for sharing this solution!

**Comment by Ne0Logic** [comment]
Any updates on this?

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/jetpack-4-8-image-sitemap-bug/

**Comment by nk111** [comment]
Is there any ETA for a fix? I mean it's about 5 months now. This is really a big issue. Not only images of unpublished posts are included in the sitemap but basically ALL images. 
I use a plugin to sync my media library with my lightroom photo catalog to have all my best shots ready for publishing in wordpress. So i have hundreds of unpulished images. They all get referenced in jetpack's image sitemap. And all have an url like this:
https://domain/XXXX where XXXX is basically the id of the image. All these links in the sitemap result in 404 errors of course. I already get warning from google about the very high number of 404s on my site.
Please get this fixed soon!

**Comment by jeherve** [comment]
> Is there any ETA for a fix? I mean it's about 5 months now. This is really a big issue.

Unfortunately I do not have an ETA yet but I'll see if I can bump the priority of this.

In the meantime, I'm afraid I can only recommend the solution that my colleague @zinigor posted above.

> All these links in the sitemap result in 404 errors of course.

That is odd. Those links should return regular attachment pages that will display the images since they are public, whether they are not attached to any post or attached to a draft. By default WordPress considers all images public, as soon as they are in your Media Library. Do you use a plugin to make those unattached images private?

**Comment by nk111** [comment]
The problem here is that the images have been uploaded (by the lightroom sync plugin)  with an empty title (because i missed a setting to use the filename as title if title is empty) thus having wordpress generating permalinks using the attachment ID! 

Then in case of 4 digit IDs the url rewrite rules of wordpress rewrite a permalink like:

https://domain/8458
to
https://domain/index.php?year=8458

which results in the 404s

So, i recognize this is a very special case but nevertheless i would really appreciate a fixed sitemap generation.

**Comment by jeherve** [comment]
That makes sense, and it looks like something we should address as well, because those links will always return a 404 then, even when you want them to be published.

Could you contact us via [this contact form](https://jetpack.com/contact-support/?rel=support) to give us more details about your site so we can run some tests with you?

Thanks!

**Comment by nk111** [comment]
Thanks. In the meantime i put up a filtering solution like suggested by @zinigor 

Whoever wants to try this too, be aware that the logic is just the other way around. You have to return TRUE if want the image to be SKIPPED and FALSE if you want it in included!

Here is what i use now:
`add_filter( 'jetpack_sitemap_image_skip_post', 'jetpack_filter_sitemap_images', 2, 10 );

function jetpack_filter_sitemap_images( $add, $post ) {
  // add your checks on the $post object here
  $permalink = get_permalink( get_post( $post->post_parent ) );
  if ( '' == $permalink ) {
    $permalink = get_permalink( $post );
  }
  $re = '/^http(?:s?):\/\/DOMAIN\.TOPLEVEL\/([0-9]{4})\/?$/m';
  if (get_post_status($post->ID) != 'publish' || preg_match($re,$permalink)) {
    return true; // return TRUE in case you want to SKIP the image
  }
  return false;
}`

Note that 
`get_post_status($post->ID)`
returns the status of the PARENT post in case of attachments.

The preg_match check excludes images with 4 digit numeric permalinks because they would result in 404s.

If you want to exclude images not linked to any article or page you could add another check like this
`$post->post_parent != 0`

**Comment by nk111** [comment]
Another issue with the image sitemap is that it totally ignores the featured images of my posts. In my theme the featured post image is displayed right above the content area. This is usually the main element of the post. None of these images are included in the image sitemap because they are technically no image attachments?!

**Comment by jeherve** [comment]
> Another issue with the image sitemap is that it totally ignores the featured images of my posts. 

Could you start a new issue with some examples, so we can take a closer look?

Thanks!

**Comment by zinigor** [comment]
This issue can be solved by using [an existing Jetpack filter](https://developer.jetpack.com/hooks/jetpack_sitemap_image_sitemap_item/). This code snippet will let you only use images that are attached to a post, and that post is public:
```
add_filter( 'jetpack_sitemap_image_skip_post', 'jetpack_sitemap_image_skip', 10, 2 );

function jetpack_sitemap_image_skip( $skip, $post ) {
	if ( 0 === $post->post_parent ) {
		// Skip unattached images.
		return false;
	}

	if ( 'publish' !== get_post_status( $post->post_parent ) ) {
		// Skip images with an unpublished parent post
		return false;
	}

	return $skip;
}
```

**Comment by brbrr** [comment]
I've re-tested this issue and it is fixed in bleeding edge version. 

Now all images whenever it added to a scheduled post, uploaded via media, re-used from not-yet-published post, or added together with newly published post - they all have the same structure:

```
<url>
  <loc>https://nasty-cephalopod-219.jurassic.ninja/pexels-photo-1035591/</loc>
  <lastmod>2018-05-02T14:33:05Z</lastmod>
  <image:image>
    <image:loc>https://nasty-cephalopod-219.jurassic.ninja/wp-content/uploads/2018/05/pexels-photo-1035591.jpeg</image:loc>
    <image:title>pexels-photo-1035591</image:title>
    <image:caption/>
  </image:image>
</url>
```
