### ISSUE TITLE
VideoPress: Deselecting "Enable Sharing" Does Not Remove Direct Link to Video

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/jetpack#7352]
#### Steps to reproduce the issue

1. Create a post and add a Video with VideoPress.
2. Open Attachment Page for the embedded video.
3. Deselect the option "Display share menu and allow viewers to embed or download this video"
4. Open post.
5. Click the video title to open the video directly with the videopress URL.
6. Notice the Share Option remains.

![screen shot on 2017-06-15 at 15 3a34 3a03](https://user-images.githubusercontent.com/22805865/27198434-289efcd0-51e0-11e7-8611-914aba0b7343.png)

Example post: https://worldowhite.com/2017/06/05/test-video/
Direct link to video: https://videopress.com/v/ovWPwVlN

#### What I expected

In WordPress.com, this does not happen. Consider this support document:

https://jetpack.com/support/videopress/

The title is there, but there is no link to the video file.

Can we remove that link in the title? Otherwise we are advertising a service that we're not actually offering.

**Comment by dbtlr** [comment]
This was due to a bug in WPCOM with how Jetpack signatures are compared that appears to have been introduced when a PHP 7 compatibility fix was applied. I'm not sure if there were any other failures in Jetpack, as this was code related to Jetpack in general, but this should be repaired and working now.

**Comment by zinigor** [comment]
Please reopen this issue if the problems persist.
