### ISSUE TITLE
Comments: Removes all actions on comment_form_after

### ISSUE THREAD

**Issue by chrisaldrich** [Automattic/jetpack#7357]
#### Steps to reproduce the issue
On a self-hosted install (tested with the standard 2016 theme) with the [webmention plugin](https://wordpress.org/plugins/webmention/) (installed/activated) and JetPack (installed/activated) with the setting "Let readers use WordPress.com, Twitter, Facebook, or Google+ accounts to comment" activated under "Discussions"

#### What I expected
Underneath the typical comments form I expected to be able to see a short piece of text explaining what a webmention is along with an input box for a permalink URL followed by a "Ping Me" button, pictured below.

![pingme](https://user-images.githubusercontent.com/5882943/27245513-c8a342c0-52a0-11e7-9895-9c897d5e44f1.PNG)

#### What happened instead
The modified comments box takes over the entire section of that part of the page and doesn't allow it to display anything which hooks in below it.

If I disable the WP/Twitter/FB/G+ account options, then the expected webmention form shows up properly.

There's also a potential CSS bug in that if a user begins entering a long segment of text, the UI "moves" down the page and can eventually disappear making it impossible to click the "Post Comment" button or choose the two "notify me" checkboxes. One would generally expect the form to have its own scroll bar and the post button to stay in place.

#### Additional information
Like the webmention plugin, another example of a plugin which isn't allowed to be hooked in underneath the traditional comments box is [this citation plugin](https://github.com/pfefferle/wordpress-indie-cite).

Cross reference: https://github.com/pfefferle/wordpress-webmention/issues/143

**Comment by kraftbj** [comment]
That's somewhat intentional.

Webmentions use `comment_form_after` to hook in after the comment form ( https://github.com/pfefferle/wordpress-webmention/blob/master/webmention.php#L63 ) and, since Jetpack is trying to take over the comment form, we remove everything on that hook ( https://github.com/Automattic/jetpack/blob/master/modules/comments/comments.php#L115 ).

@beaulebens I realize this was eons ago now, but I think you might have the best operational knowledge of that decision when Highlander was built. Is removing all of the actions on the after hook needed? Would hooking very early (priority 0?) and then flush the buffer and injecting the Highlander form work?

**Comment by kraftbj** [comment]
As an aside, I haven't written this up yet for internal discussion, but I would like us to evaluate the "modern" open web standards that are coming out -- webmentions, websub (formerly PubSubHubbub), jsonfeed, etc -- and see how we/WP.com could play nicely with them. Micro.blog supports these and, in the interest of an open and interchangeable web, I'd like us to keep it all in mind. ( cc: @iandunn )

**Comment by jeherve** [comment]
👍 

Somewhat related: #477
