### ISSUE TITLE
Sharing buttons are added to the rest API output

### ISSUE THREAD

**Issue by ramiy** [Automattic/jetpack#7361]
Visit your sites rest API output. The post excerpt has sharing buttons - it shouldn't be there. I expect to see the sharing buttons only on the front-end, not anywhere else.

#### Steps to reproduce the issue

Change to your sites URL: https://codepen.io/rami/pen/qjEXLQ

#### What I expecte

I expect to see the post excerpt (no sharing buttons).

#### What happened instead

I get the post excerpt with the sharing buttons.

#### How to fix

When adding share buttons to the post excerpt, it should check if it's not `is_feed()` or `is_trackback()` or `is_embed()` or rest API output.

**Comment by jeherve** [comment]
Related: #4601

@ramiy I can't seem to reproduce the issue with my own site right now. Could you let me know what your sharing settings (under Settings > Sharing) were when you originally reported this issue?

**Comment by ramiy** [comment]
@jeherve 

![jetpack-sharing-settings](https://user-images.githubusercontent.com/576623/30161409-044d3c08-93d9-11e7-8bdd-9f9d10691d57.png)

**Comment by jeherve** [comment]
Thanks! Could you click on "Configure your sharing buttons" and show me your settings there?

**Comment by ramiy** [comment]
@jeherve 

![jetpack-sharing-config](https://user-images.githubusercontent.com/576623/30168072-0554a1a0-93f1-11e7-853d-f1a577307a03.png)

**Comment by jeherve** [comment]
I can reproduce now, thank you!

**Comment by brbrr** [comment]
I was able to reproduce this issue with bleeding edge Jetpack 6.2-beta-18674-03a5e33-master.

Steps to reproduce this issue:
1. Create new JN site, connect it
1. Check "Front Page, Archive Pages, and Search Results" option in "Show sharing button on" (Settings > Sharing > Configure your sharing buttons)
1. Go to https://YOUR-JN-SITE/wp-json/wp/v2/posts/?_embed&per_page=5&author=1
1. Execute this JS in console: `JSON.parse(document.getElementsByTagName('pre')[0].innerHTML)[0].excerpt.rendered`
Output should not include html tags for sharing buttons

**Comment by ramiy** [comment]
The bug still exists...

**Comment by jeherve** [comment]
Related PR: #25346 
Maybe extending things to never add the sharing buttons to the API in any context may help us here.

@wojtekn @danielbachhuber It's only been 6 months, but I already struggle remembering the exact details of our conversations in #24896 and #25346. Was there a specific reason to have the sharing buttons shown in API responses in some specific use-cases?

Interestingly, the Likes, which also get hooked to `the_content`, do not get added in many non-traditional contexts:
https://github.com/Automattic/jetpack/blob/3104e377ae2d45ad2d4ffadfd839cee47aa871df/projects/plugins/jetpack/modules/likes.php#L270-L277

Maybe we should do something similar for the sharing buttons, instead of checking for the `edit` context?
https://github.com/Automattic/jetpack/blob/3104e377ae2d45ad2d4ffadfd839cee47aa871df/projects/plugins/jetpack/modules/sharedaddy/sharing-service.php#L963

**Comment by jeherve** [comment]
This came up again in this thread:
https://wordpress.org/support/topic/annoying-interaction-with-jetpack-social/

**Comment by danielbachhuber** [comment]
> Was there a specific reason to have the sharing buttons shown in API responses in some specific use-cases?

I think this was a side effect (intentional or unintentional) of @wojtekn's decision. I was in favor of the more limited "fix": https://github.com/Automattic/newspack-blocks/pull/1190

**Comment by wojtekn** [comment]
@danielbachhuber I think it's not right. The decision we've made didn't enable sharing buttons anywhere. 

Before the fix, the sharing buttons were included in all API responses, both in the frontend and in the editor. The final fix we came up with was hiding them from API responses that are returned in the editor context. Here is the discussion:

https://github.com/Automattic/jetpack/pull/25346#discussion_r934658643

**Comment by danielbachhuber** [comment]
@wojtekn Oh, good find. I guess I never replied on that thread, because my preference was for the more limited change in the first place.

**Comment by wojtekn** [comment]
@jeherve, as regards the fix for the ActivityPub plugin behavior - the safest option would be to check how it currently gets the post content, see if we can identify such a request in a similar way to the `context` parameter, and modify the condition.

Alternatively, we could use the longer condition you showed to remove sharing buttons for all possible AJAX requests. However, I don't know if there is any case in which we would like to get post content with buttons via the AJAX.

**Comment by jeherve** [comment]
> Before the fix, the sharing buttons were included in all API responses, both in the frontend and in the editor. The final fix we came up with was hiding them from API responses that are returned in the editor context.

Right. This very issue has existed for years, it isn't new. If anything, the work you've done in #25346 has limited the scope of the issue.

Yet it remains in some scenarios, like in the thread about the ActivityPub plugin above. 

We can certainly attempt to fix things for that plugin in particular, but I wonder if we need to display the buttons in some API context at all. 

To take an example, check the `content` field in this API request:
- https://jeherve.com/wp-json/wp/v2/posts/22

I don't think the buttons' markup would ever be useful in this scenario. But are there scenarios when we rely on an API query to display content (and buttons) on a site's frontend, where the buttons' scripts and styles are loaded?

**Comment by danielbachhuber** [comment]
> We can certainly attempt to fix things for that plugin in particular, but I wonder if we need to display the buttons in some API context at all.

I agree that buttons shouldn't be included in API responses. Removing them presents some back compat concerns, but I think it's defensible to break back compat in this case.

**Comment by pfefferle** [comment]
ActivityPub has a massive use of Content Negotiation... Every Page, Post and the Author URL might be queried with a different Accept Header (`application/activity+json`) what about deactivating the sharing buttons also for mime-types other than `text/html`, or at least disable it for JSON requests (`wp_is_json_request`)?

**Comment by jeherve** [comment]
I created a follow-up issue for ActivityPub in #29435
