### ISSUE TITLE
VideoPress: Auto-activate on a supported paid plan?

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#7362]
When purchasing a paid plan for Jetpack which includes VideoPress, customers still have to access their settings and specifically activate VideoPress.

Would it make sense to auto-activate it upon plan purchase? I've ran into trying to debug VideoPress on a personal site and @seejacobscott tripped himself up the same way by purchasing a plan, then trying to upload a video, which fails.

**Comment by beaulebens** [comment]
I don't necessarily think that we should auto-activate it, because unless users understand that, they're likely to be annoyed and surprised to find that their videos are not longer being uploaded to their local Media Library at all.

I _do_ think we should make things much clearer, and encourage them to activate it immediately though. We added something related in https://github.com/Automattic/jetpack/pull/8700

**Comment by jeffgolenski** [comment]
@beaulebens @kraftbj Perhaps it makes sense to group this into the NUX checklist @joanrho is working on here p6TEKc-1Qp

Joan, does that make sense to do? I feel like we're starting to rely on JITMs a little too much for everything and a central location of to-dos for the customer makes a lot of sense

**Comment by joanrho** [comment]
@beaulebens @kraftbj @jeffgolenski to start, I don't see this becoming a checklist item until our first iteration of that is launched and we see how that performs. This should be a Feature card on the My Plan page and be towards the top—this feature card already exists in my mocksup on https://github.com/Automattic/wp-calypso/issues/22691

**Comment by jeffgolenski** [comment]
@joanrho Yeah that sounds good Joan, thanks! 

Perhaps we can work a quick "enable this now" blurb into a welcome email? @richardmuscat + @bubel  ??

**Comment by jeffgolenski** [comment]
Just revisiting this issue. I've made some mockups to help alleviate this issue. I think maybe some carefully placed JITMs may help this scenario. 

Instead of focusing on getting this in everyone's face immediately (see send a bunch of emails and a lot happens once a plan is purchased), how about we consider placing enable JITMs in particular places if and when a customer goes to upload or manage their media. This way we inform them right when it counts (hence just in time message). This JITM would only display for post-purchase folks who have plans with VideoPress / Video CDN. Once enabled or dismissed they wouldn't see it again.

I've targeted 5 locations (3 in wp-admin, 2 in calypso thus far)

![video cdn - add media wp-admin](https://user-images.githubusercontent.com/214813/37229720-035b2f98-23b3-11e8-984a-7fcc2313cd93.png)
![video cdn - calypso add media](https://user-images.githubusercontent.com/214813/37229721-036ac174-23b3-11e8-931a-1a6d99291b73.png)
![video cdn - calypso media](https://user-images.githubusercontent.com/214813/37229723-037e4a14-23b3-11e8-9bf0-44b2ab2043ff.png)
![video cdn - media library wp-admin](https://user-images.githubusercontent.com/214813/37229724-038cdd0e-23b3-11e8-9e8e-30cd0502c0df.png)
![video cdn - upload media wp-admin](https://user-images.githubusercontent.com/214813/37229725-039a1b2c-23b3-11e8-9b9f-09515cdeb2ce.png)

cc @kraftbj @beaulebens (@nicoleckohler for editing my terrible verbiage) @richardmuscat and @withinboredom

**Comment by beaulebens** [comment]
I like those mocks @jeffgolenski. @withinboredom how many of these on-screen positions match up with where JITMs are loadable currently? I think some of these are a bit different (e.g. JITMs display right up the top of the page, and I'm not sure about them inside the media dialog?)

Also, note that https://github.com/Automattic/jetpack/pull/8985 adds inline toggles for enabling features when you first purchase a plan.

**Comment by withinboredom** [comment]
I think (I'll have to check) that we can inject them in the media dialog (I think there used to be a jitm there) ... Wherever we can put a div via a hook, we can put a jitm (it just might require a release). They'll take ~100% of the container width by default, if I recall the css correctly.

**Comment by MichaelArestad** [comment]
I think since our positioning and goals for Jetpack have changed a bit, we should close this for now. Perhaps we can bake it into another flow down the line.
