### ISSUE TITLE
Broken codes inside <pre> tag

### ISSUE THREAD

**Issue by 082net** [Automattic/jetpack#7442]
#### Steps to reproduce the issue
- Install 'crayon-syntax-highlighter' plugin
- Insert any codes including &lt;div&gt; tag with crayon (&lt;object&gt;, &lt;embed&gt;, &lt;iframe&gt;, &lt;script&gt;) .

#### What I expected
- Codes inside &lt;pre&gt; and &lt;code&gt; block saved normaly

#### What happened instead

- Codes inside &lt;pre&gt; and &lt;code&gt; block were broken

#### What I want
- bypass "Filter_Embedded_HTML_Objects::filter" for &lt;pre&gt; and &lt;code&gt; blocks
- OR option to disable shortcodes

**Comment by mboynes** [comment]
`class.filter-embedded-html-objects.php` hooks into `pre_kses` and therefore manipulates anything that passes through `wp_kses()`, not just post content. This is dangerously vague and introduces a lot of potential conflict with themes and plugins that are responsibly sanitizing HTML content.

I would also offer that this is probably not a "good first bug" or "good for community" ticket as it is currently labeled.

**Comment by jeherve** [comment]
This seems to be the problem that was reported in #6809. Let's continue this conversation there.

**Comment by designsimply** [comment]
I tried testing this and was unable to reproduce the problem. Here are the steps I used:

1. Start with a WordPress site that has Jetpack installed and activated.
1. Install and activate the [Crayon Syntax Highlighter](https://wordpress.org/plugins/crayon-syntax-highlighter/) plugin. (I used v2.8.4 for testing.) 
1. Create and publish a post with some code in it using `<pre>` and `<code>` tags.
1. View the post and make sure the code renders as expected.

<strong>Result:</strong> code in `<pre>` tags gets rendered with special syntax highlighting while code in `<code>` tags does not and neither looks to have errors in the code.

![screen shot 2018-05-02 at wed may 2 4 34 18 pm](https://user-images.githubusercontent.com/1119271/39552570-0af59010-4e27-11e8-916c-750b7261e466.png)
<sup>Seen at https://orthodox-cross.jurassic.ninja/2018/05/02/syntax-highlighting-test-post/ using WordPress 4.9.5, Jetpack 6.1, and Crayon Syntax Highlighter 2.8.4 and tested with Firefox 59.0.2 on macOS 10.13.4.</sup>

<strong>Sample Code</strong>

```
<pre>add_filter('comment_form_defaults', 'tinymce_comment_enable');
function tinymce_comment_enable ( $args ) {
    ob_start();
    wp_editor('', 'comment', array('tinymce'));
    $args['comment_field'] = ob_get_clean();
    return $args;
}
</pre>

<code>
add_filter('comment_form_defaults', 'tinymce_comment_enable');
function tinymce_comment_enable ( $args ) {
ob_start();
wp_editor('', 'comment', array('tinymce'));
$args['comment_field'] = ob_get_clean();
return $args;
}
</code>

<pre><div>This is a div inside a pre tag.</div></pre>

<code><div>This is a div inside a code tag.</div></code>
```

<strong>Note:</strong> Crayon Syntax Highlighter currently has 50,000+ active installations and a 4.5 rating based on 143 ratings.

<strong>Note:</strong> this may be relevant to #6809, however, I am posting here because I decided to test Crayon Syntax Highlighter first and if this issue is resolved I may try to get a test version of the OptinMonster plugin separately for #6809 (from what I can see you need to pay $108 to start using it at the lowest priced plan).

@082net may I ask if the problem you reported is still happening using similar testing steps that I have used above? Are my testing steps good?
