### ISSUE TITLE
Crop-Thumbnails plugin not compatible with Photon

### ISSUE THREAD

**Issue by cena** [Automattic/jetpack#7466]
Using the [Crop-Thumbnails plugin](https://wordpress.org/plugins/crop-thumbnails/) with Photon enabled leads to unexpected/undesired image results:

[without Photon: ](https://cena.blog/wp-content/uploads/2017/07/pumpkindoom-2000x1200.jpg)

[with Photon: ](https://i2.wp.com/cena.blog/wp-content/uploads/2017/07/pumpkindoom.jpg?zoom=2&resize=2000%2C1200&ssl=1)

It appears that Photon is not compatible with the Crop-Thumbnails plugin.  Can we add something to Jettpack so the conflict is surfaced when it occurs?

reported in #3322086-t and confirmed by me.

**Comment by jeherve** [comment]
That's an expected behaviour as Photon doesn't use cropped images; it creates its own crop based on the original image.

You can find out more about this here:
https://wordpress.org/support/topic/photon-crop-thumbnails/#post-7432935

You can, however, use filters to customize the way Photon crops images:
https://jetpack.com/2013/07/17/use-photon-to-serve-post-thumbnails-with-custom/
