### ISSUE TITLE
Sharing: add a WhatsApp sharing button

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#755]
Related:
http://whatsapp-sharing.com/

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/whatsapp-share?replies=1#post-

**Comment by elliott-stocks** [comment]
+1 to this! We had to implement it with a custom service.

If no one is currently tackling this I'd be happy to contribute.

**Comment by richardmtl** [comment]
@elliott-stocks do it! No-one's working on this at the moment, so feel free to work on a PR for it; thanks!

**Comment by swissspidy** [comment]
+1 for this. I just wanted to add WhatsApp as a custom provider, but it's not possible because of the `esc_url_raw` call in the `new_service()` method ([example](https://github.com/Automattic/jetpack/blob/c55697060646b1e03b79c19e402c746ab4441bcc/modules/sharedaddy/sharing-service.php#L82)), which disallows using `whatsapp://`or any other protocol.

**Comment by jeherve** [comment]
@swissspidy Yeah, you'd have to add that service through a separate plugin, like in [this example](https://github.com/jeherve/mwp-sharing-jetpack).

**Comment by valeriosouza** [comment]
I create one addon https://wordpress.org/plugins/whatsapp-jetpack-button/

**Comment by jeherve** [comment]
Fixed in #4096
