### ISSUE TITLE
Comment Likes: Fails to load when using the Epoch plugin

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#7568]
When using Epoch ( https://wordpress.org/plugins/epoch/ ), comment likes do not load. I haven't investigated further to determine exactly where the breakdown is, if we should mark them as conflicting or determine how to make them work together.

props @thejeffr0 for the report.

**Comment by eliorivero** [comment]
As soon as I install and activate, I see it throws this in front end.
```
Notice: Undefined index: options in wp-content/plugins/epoch/classes/core.php on line 190
```
There are a couple of issues in the plugin that makes it impossible to work with Jetpack. It's not the fact that they use their own template, because they're applying the filter `comment_text` which we use to inject Comment Likes. The issue is that they don't have $wp_query and $post set in the environment. This leads to one of our conditions that we use to determine if likes will be shown, `Jetpack_Likes_Settings->is_likes_visible()` to throw false. Even when I replaced it with a boolean to pass it, I stumbled upon another one: $comment is not defined. This is throwing an issue from core itself. In the test, I also short circuited this to bypass it, but just with these two stones in the road it's clear that it won't work. One last issue remains after bypassing this: since the comments are loaded asynchronously it seems the script that replaces the star and Loading... isn't loaded at the right time, so even after shortcircuiting those issues it still won't display.
If they update the plugin to make those globals available in the environment, we might have a shot at the last issue, but without the first two solved we won't move forward.
For all this, we're marking Epoch as incompatible for now https://github.com/Automattic/jetpack/pull/7574

**Comment by Vernal** [comment]
We'll keep an eye on this for future development on Epoch. For now #7574 is a good approach. I'll update here when we resolve things on our end.

**Comment by ronalfy** [comment]
I've gotten most of the way there with duplication on the PHP side of things. The remaining piece is the `loading` as @eliorivero mentioned. I cannot for the life of me get things to load on the JS side. So I'm essentially at the last step perhaps?
