### ISSUE TITLE
Ads: Placement Configuration

### ISSUE THREAD

**Issue by CelesteGodwin** [Automattic/jetpack#7582]
Hello,

I installed a new theme and noticed ads showing up everywhere under post excerpts. On archives there was just one post under the first post shown, but on widgets that show excerpts it was a mess. They were shown even in sliders.

This is extremely annoying, I do not need so many. I also noticed some themes filter this out or just get the excerpts directly and then apply the filters they need. This is cumbersome somewhat and requires extra coding. 

Please add some checkboxes in order to be able to choose where to show the ads, at the end of a post or page, at the end of excerpts, in archives ... etc. 

Other people coding around this is not the answer, pease take this seriously. A few checkboxes would be easy to add. If you can't make this soon then consider adding some internal filters or something in order to be able to configure this programatically. I looked for those kinds of filters but there are a few that just do what the buttons in the admin section do.

Thank you

**Comment by glasgowshipyard** [comment]
@CelesteGodwin In the absence of the ability to place very well, I settled on creating new widget areas and user jetpack widget visibility to control when they show and under which circumstances. It's not a perfect solution, but it's a great starting point I think. Maybe give that a go.

**Comment by CelesteGodwin** [comment]
Hi glasgowshipyard, thank you for your reply.

I know I can place ad widgests and set visibility, but this does not help with the issue at all.
I am talking about the filter on hook "the_excerpt", which automatically inserts ads below the excerpts if ads below posts setting is turned on.

Imagine having 3 or 6 widgets on the front static page, every one of them having at least 3 posts, all showing up excerpts, and below them showing ads, that means at least 6 or more blocks of ads on the same page....

Settings are needed to be able to remove ads from excerpts. Now, I need to use other ways of getting excerpts in order to bypass this behaviour.

**Comment by dbspringer** [comment]
Howdy @CelesteGodwin,
There seems to be an issue with some themes that utilize the_excerpt in curious ways that we're looking into for the next release. In the mean time, you can add the following action to your functions.php (or in a separate plugin) to disable ads appearing in excerpts.

```php
add_action( 'wp_head', 'remove_wordads_excerpt' );
function remove_wordads_excerpt() {
	global $wordads;
	remove_filter( 'the_excerpt', array( $wordads, 'insert_ad' ) );
}
```

> Please add some checkboxes in order to be able to choose where to show the ads, at the end of a post or page, at the end of excerpts, in archives ... etc.

This is also slated for the next release (the code has already been written). Our POV is that we wanted to make this as simple/straightforward for our users as possible, but the complexities of theme variations have prompted us to include more options for our users.

Otherwise, the following filters also exist that make it possible to control where/when ads show up and do what they say on the tin (just pass them to true value e.g. `add_filter( 'wordads_inpost_disable' , '__return_true' );`):
* `wordads_inpost_disable`
* `wordads_header_disable`

**Comment by CelesteGodwin** [comment]
Ok, thanks for that, that's what I did.

Just add a button so it's easier :).

**Comment by rclations** [comment]
Looks like this has been resolved, but adding some info for others that may stumble onto this issue looking for answers. We recently added some documentation on the hooks available for controlling ad placements here:
https://wordads.co/2018/02/07/how-to-control-jetpack-ad-placements-using-hooks/
