### ISSUE TITLE
Mobile Theme: Clarify user-facing wording

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/jetpack#7602]
While supporting users in the WordPress.org forums, we run across a large number of users who've activated the Jetpack Mobile Theme without realizing the consequences.

When they look at their site on their phone, they are confused as to why it doesn't look anything like the theme they selected and set up so carefully, and frustrated that they can't figure out how to get the site looking as they intended.

We then have to show users how to deactivate the Jetpack mobile theme, explaining that it's not needed, since their theme is already responsive and mobile-ready.

A forum volunteer suggested that this could be averted if we tweak the wording in the Jetpack settings.

**Current wording**

> Enable the Jetpack Mobile theme

**Context**

![jetpack wpmtl test site wordpress](https://user-images.githubusercontent.com/7662449/29031753-3c00422e-7b5d-11e7-81c6-78ac62bedc39.png)

**Possible new wording**

> Enable the Jetpack Mobile theme. This option is not necessary if your theme is already responsive/mobile-friendly.

Would love @Automattic/editorial input on the wording here.

**Examples of users activating the mobile theme and then being confused**

https://wordpress.org/support/topic/mobile-view-not-working-properly-different-from-desktop-view/

https://wordpress.org/support/topic/dara-does-not-look-friendly-with-cell-phones/

https://wordpress.org/support/topic/incorrect-theme-in-mobile-browsers/

https://wordpress.org/support/topic/how-to-disable-wordpress-default-mobile-theme-on-smartphone/

**Comment by michelleweber** [comment]
Suggest being as direct and clear as possible: 

> Enable the Jetpack Mobile theme. If your theme is already responsive/mobile-friendly, this is not recommended. (or: not necessary)

The thing that jumps out at me here is not so much the wording, but whether we can respond to the obvious next question: how do I know if my theme is responsive? But since this is .org, I'm not sure there's a good answer, since it's not like we can link to a theme showcase page. Maybe a pop-up with something like "Most themes created in the past few years are already fully responsive. If you're not sure about your theme, check the theme's documentation or get in touch with the theme developer."

**Comment by jeherve** [comment]
Related: #7036 and #7396, where this wording was previously updated.
