### ISSUE TITLE
Add user authentication endpoints

### ISSUE THREAD

**Issue by cr101** [Automattic/jetpack#7635]
We are currently building a React-powered web app using the WordPress REST API and I need to add user authentication. 
I was looking through the wp-calypso code and I noticed that they are using the user authentication endpoints below which is exactly what I need for our project:

```
https://wordpress.com/wp-login.php?action=login-endpoint
https://wordpress.com/wp-login.php?action=social-login-endpoint
https://wordpress.com/wp-login.php?action=logout-endpoint
```

The above endpoints are used in [wp-calypso](https://github.com/Automattic/wp-calypso/blob/master/client/state/login/actions.js)

**Comment by zinigor** [comment]
I'm not sure how you're planning to use these endpoints. Can you just use whatever is provided with the existing [WordPress.com REST API](https://developer.wordpress.com/docs/api/)? If you WordPress users are connected to WordPress.com with Jetpack, all they will need to use the API is to be logged in to WordPress.com.

**Comment by cr101** [comment]
@zinigor We are using the WordPress core REST API and not the WordPress.com REST API to build our React-powered app. Our app users are not connected to WordPress.com
Would it be possible for Jectpack to make these endpoints available for WordPress core?

**Comment by zinigor** [comment]
I'm sorry, but I still don't understand the problem. You're saying that Calypso endpoints are exactly what you need for your project. How would you imagine using them, or some other endpoints like them?
From what I know, there's a very nicely documented way to use WordPress REST API by authenticated and non-authenticated users. If you need authentication, you can just have your users authenticate with WordPress the usual way and make your requests like this: https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/.
Is that what you're planning to do?

**Comment by cr101** [comment]
I'm not building your typical WordPress theme using PHP but I'm building a decoupled (or "headless") WordPress web application using React and the WordPress REST API.
I'm looking for WordPress REST API endpoints to use for user registration and user login.

**Comment by jeherve** [comment]
> I'm looking for WordPress REST API endpoints to use for user registration and user login.

I'm afraid this may not be the best place to suggest new default endpoints to be added to the core WP REST API. You would need to make that suggestion to the Core WP REST API team:
https://core.trac.wordpress.org/
https://make.wordpress.org/chat/

If it is decided to add new default endpoints to the core WP REST API, we at Automattic will be happy to jump in and share our experience from building our own authentication endpoints on WordPress.com.
That said, I'm sure our experience would be very interesting, since WordPress.com is very different from all the default WP installations out there. 

I hope this clarifies things a bit. For now, and as @zinigor suggested, you could use the WordPress.com REST API in your project or develop your own authentication solution on top of the REST API by following the link Igor posted above.
