### ISSUE TITLE
Ads: Add Filter to Allow Editing of "Advertisements" Title

### ISSUE THREAD

**Issue by glasgowshipyard** [Automattic/jetpack#7647]
After having established that this doesn't interfere with the wordads T & C's, I'd love to be able to edit the title "Advertisements" and perhaps add my own HTML and CSS (to the title, not the ad).

As I use ads in widgets and control visibility, I will be able to suppress ads if User roles are met - purchased through woocommerce memberships.

**Comment by jeherve** [comment]
> After having established that this doesn't interfere with the wordads T & C's

cc @dbspringer who can confirm whether this sounds reasonable.

**Comment by glasgowshipyard** [comment]
@jeherve If you'd like to discuss my thoughts on this (or about manipulating visibility in widgets) further, let me know. I'd love to help.

**Comment by dbspringer** [comment]
Unfortunately, `Advertisements` above the ad is something that Google/Bing/et al enforce pretty strictly, so it's not something we're keen to open. You're welcome to add your own CSS to the container, but it's not recommended to alter the elements too heavily.

Otherwise, utilizing the filters `wordads_inpost_disable` and `wordads_header_disable` set to true should allow you to selectively hide advertisements. If you want to ensure none of the code gets run for some of the users you can do something like this:

```php
add_action( 'wp', 'disable_wordads_selectively' );
function disable_wordads_selectively() {
	global $wordads;
	if ( <whatever reason you want to disable> ) {
		remove_action( 'wp_head', array( $wordads, 'insert_head_meta' ), 20 );
		remove_action( 'wp_head', array( $wordads, 'insert_head_iponweb' ), 30 );
		remove_action( 'wp_enqueue_scripts', array( $wordads, 'enqueue_scripts' ) );
		remove_filter( 'the_content', array( $wordads, 'insert_ad' ) );
		remove_filter( 'the_excerpt', array( $wordads, 'insert_ad' ) );
	}
}
```

**Comment by glasgowshipyard** [comment]
@dbspringer Bummer. I was under the impression it used to have an HTML link the title, something I would have liked to have been able to alter (directing users to membership where ads are suppressed).

Thanks for the code above though, I think this will really help me out.
