### ISSUE TITLE
Infinite scroll not working properly : only next page is displayed

### ISSUE THREAD

**Issue by nicolinuxfr** [Automattic/jetpack#7655]
#### Steps to reproduce the issue

Here’s what I did to activate infinite scrolling on archive pages for my blog ([https://voiretmanger.fr](https://voiretmanger.fr)) : 

In `functions.php`, here’s the code used : 

```
function voiretmanger_infinite_scroll_init() {
    add_theme_support( 'infinite-scroll', array(
		'container' => 'content’,
		'footer' => false,
		'render' => 'voiretmanger_infinite_scroll_render',
		'posts_per_page' => 8,
		'wrapper' => false,
    ) );
}
add_action( 'after_setup_theme', 'voiretmanger_infinite_scroll_init' );


function voiretmanger_infinite_scroll_render() {
	get_template_part('liste', 'archives');
}

add_filter( 'infinite_scroll_query_args', 'jetpack_infinite_scroll_query_args' );
```

And here’s the custom render : 

```
<div class="fukol-grid" id="content">
<?php // Début de la boucle
	
	while ( have_posts() ) : the_post(); ?>
		
		<?php $featuredImage = wp_get_attachment_image_src(get_post_thumbnail_id(), "large", true); ?>

		<article id="post-<?php the_ID(); ?>" class="post">
		<a href="<?php the_permalink(); ?>" title="<?php printf( esc_attr__( 'Lien direct vers %s', 'autofocus' ), the_title_attribute( 'echo=0' ) ); ?>" rel="bookmark">
			<div class="image" style="background-image: url(<?php echo $featuredImage[0]; ?>); <?php if( get_post_meta($post->ID, 'position', true) ) ?> background-position: <?php echo get_post_meta($post->ID, 'position', true); ?> ;">
				<header><h2 class="post-title"><?php the_title(); ?></h2></header>
			</div>
		</a>
		</article><!-- #post-## -->

<?php endwhile; // Fin de la boucle ?>
</div>
```

If you need more context, the whole theme of my blog is available on GitHub : https://github.com/nicolinuxfr/voiretmanger

#### What I expected

Load every posts using a button, for a taxonomy or on a date archive. Posts are sorted by date.

#### What happened instead

The first infinite loading is correct, the next 8 posts are added as expected. But then, Jetpack does not load the next 8 posts, it duplicates the 8 previous one. And it does that infinitely, so I can’t reach older posts.

Here’s what it looks like :

![jetpack-infinite-scroll-not-working mov](https://user-images.githubusercontent.com/2078386/29456419-d12cbf4c-8415-11e7-8e6b-2f5db7828790.gif)

Let me know if you need more information !

**Comment by nicolinuxfr** [comment]
I noticed I have this error in my logs when I click the Infinite Scroll button. Maybe it will help ?

```
25/Aug/2017:09:29:48 +0200 [ERROR 0 /] PHP message: PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, function 'jetpack_infinite_scroll_query_args' not found or invalid function name in /home/www/sites/voiretmanger/wp-includes/class-wp-hook.php on line 298
PHP message: PHP Warning:  array_merge(): Argument #1 is not an array in /home/www/sites/voiretmanger/wp-content/plugins/jetpack/modules/infinite-scroll/infinity.php on line 1413
```

**Comment by jeherve** [comment]
You'll want to start by removing `add_filter( 'infinite_scroll_query_args', 'jetpack_infinite_scroll_query_args' );`. It is useless here, since you do not have any function named `jetpack_infinite_scroll_query_args`.

That won't help with the duplication though.

This is caused by the way your theme is built. It seems you're using custom functions to customize each one of the post queries in your theme (by filtering `pre_get_posts` and `found_posts` for example, or by changing the default loop arguments in `index.php`. Those changes to the number of posts per page, the display of sticky posts, and the offset value for each query apply to all loops on your site, including the ones handled by Infinite Scroll.

To solve this issue, I would recommend playing with those functions you've added and removing what's not needed so the main loop is a standard loop.
If you want to keep using a custom loop, you'll need to use Jetpack filters to introduce those custom query args to Infinite Scroll as well.

I hope this helps!

**Comment by nicolinuxfr** [comment]
Well, deleting this line did in fact fixed my problem ! 😳

At least, its seems it's working much better now. I will check more closely to see if I need to edit something else but…

Thanks for your efficient help, as always. 👍
