### ISSUE TITLE
Change license to "GPL-2.0 or later" please.

### ISSUE THREAD

**Issue by nextgenthemes** [Automattic/jetpack#7876]
Following up on #6609. At the time of writing I actually do not get why it was closed.

Would be great if as much code as possible on Jetpack could be licensed in the recommended way. Quoting wp.org

> We strongly recommend using the same license as WordPress — “GPLv2 or later.”

I originally come here for the carousel I just realized that the main file actually has "GPL2+" in it, I am probably remembering this wrong but I thought everything was v2 only. 

https://github.com/Automattic/jetpack/search?utf8=%E2%9C%93&q=GPL2&type=
https://github.com/Automattic/jetpack/search?utf8=%E2%9C%93&q=GPLv2

* Post Widget
* Soundcloud shortcode
* https://github.com/Automattic/jetpack/blob/master/modules/carousel/jetpack-carousel.php

are still GPL2 only.

**Comment by brbrr** [comment]
Done in #7879

**Comment by co3k** [comment]
I've posted similar question to your support forum. https://wordpress.org/support/topic/a-part-of-jetpack-plugin-might-not-be-licensed-under-the-gpl-v2-or-later/

https://github.com/Automattic/jetpack/pull/7879 fixed the license file only. The pointed out files are  still GPL v2 (not GPL v2 or later).

Especially I worry about "Soundcloud shortcode". The original source code describes about the license as "GPL v2" (only). https://wordpress.org/plugins/soundcloud-shortcode/#8221 
I understand the original author is not your team so you can't change license of this file to "GPL v2 or later" by GPL v2's restriction without the original author's consent. If so, we can't treated this plugin as "GPL v2 or later" because we must apply licenses with no conflicts as a whole.

**Comment by jeherve** [comment]
@co3k Thanks for the feedback. We'll take a closer look at this and get back to you as soon as we have news.

Internal reference: p1HpG7-3SA-p2#comment-36391

**Comment by nextgenthemes** [comment]
I think they actually can not even legally make the entire project GPL 2.0 or later without the authors of those individual components of the files mentions specifically agreeing to a license change.

**Comment by jeherve** [comment]
To follow up on this, I've reached out to the authors of the original SoundCloud shortcode plugin about this. I'll let you know once we make progress on this.

> I think they actually can not even legally make the entire project GPL 2.0 or later without the authors of those individual components of the files mentioned specifically agreeing to a license change.

Jetpack itself can be licensed as GPLv2 or later: GPLv2 code is compatible with GPLv2+ so that is not an issue here. You can read more about this and check the table here:
https://www.gnu.org/licenses/gpl-faq.en.html#AllCompatibility

**Comment by nextgenthemes** [comment]
So is seems this is allowed, did not know that and its very confusing to me.

> 1: You must follow the terms of GPLv2 when incorporating the code in this case. You cannot take advantage of terms in later versions of the GPL.

> 2: While you may release your project (either your original work and/or work that you received and modified) under GPLv2-or-later in this case, note that the other code you're using must remain under GPLv2 only. As long as your project depends on that code, you won't be able to upgrade the license of your project to GPLv3-or-later, and the work as a whole (any combination of both your project and the other code) can only be conveyed under the terms of GPLv2.

GPLv2 is NOT compatible with GPLv3 (for example) and therefore authors releasing their code with GPLv2 did not agree to "or later" so if a project includes code from GPLv2 but licenses itself with "or later" this gives the impression that people can include it in GPLv3 projects. But they are not if there is GPLv2 code in it from authors who were never asked about "or later"? That would be like forcing a re-license by a mother project. I think it should be noted in the LICENSE file somehow that there is code in there that is NOT "or later" even if the mother project is. I do not even like that fact that his **is** allowed.

So I guess this means I can include a mother project "as is" in a GPLv3 project but I can not use portions of it that are GPLv2? That "can only be conveyed under the terms of GPLv2" part got me stuck. I do not get it. Or you can you just slap the license on there but nobody can actually use the code as if its "GPLv2 or later" ??? This makes no sense to me.

Anyway the authors will probably agree to it anyway, just saying. I personally, unlike many others, am a but fan of GPLv3 (without or later, because I do not just agree to whatever they come up with). I planned something that I did not release anyway so for now I am not even invested in this case at this point but that compat info is confusing to me.

**Comment by jeherve** [comment]
> I think it should be noted in the LICENSE file somehow that there is code in there that is NOT "or later" even if the mother project is. 

Yes, we may end up doing that for clarity, but before I do so I'm waiting to hear from the original authors of the GPLv2-licensed original plugin. If they can update the license to GPLv2+ in the original codebase that would make things clearer for everyone.

> So I guess this means I can include a mother project "as is" in a GPLv3 project but I can not use portions of it that are GPLv2? 

GPLv3 is different from GPLv2 or from GPLv2+. The table I posted earlier shows this with some extra details. It's helpful whenever you need to know what licenses are compatible with each other.
