### ISSUE TITLE
Slideshow Gallery: Images aren't run through Photon

### ISSUE THREAD

**Issue by melchoyce** [Automattic/jetpack#7891]
This past weekend I ran into an issue where slideshow images don't seem to be run through Photon, making them very large and slow to load. You can see it in action here: https://ftmpanama.com/

**Comment by dereksmart** [comment]
Noting that the mentioned site is hosted on wp.com, but we should try to reproduce this in Jetpack first as it might just be a code sync issue.

**Comment by jeherve** [comment]
I cannot reproduce the issue in Jetpack; the images use Photon on Jetpack sites if the feature is active.

I'm afraid this is not a code sync issue either; it's just that Photon isn't there to parse the content and transform all image links on WordPress.com sites.

@melchoyce It seems it might be best to recreate this issue on wpcom.trac, since the issue is limited to wpcom. I've checked, and it doesn't look like this was reported before.

Thanks!

**Comment by lancewillett** [comment]
The quick answer to this is that no WP.com Trac ticket is needed because we've stopped serving WP.com site images through Photon. (Internal ref: p3topS-mu-p2 — from what I understand this doesn't affect Jetpack sites at this time.)
