### ISSUE TITLE
Monitor: WordPress.com notifications are fugly

### ISSUE THREAD

**Issue by melchoyce** [Automattic/jetpack#7892]
These notifications are pretty wonky y'all:

<img width="412" alt="screen shot 2017-09-28 at 11 40 24 am" src="https://user-images.githubusercontent.com/2846578/30977056-6ce33e72-a444-11e7-8bbc-1b580c34a423.png">
<img width="409" alt="screen shot 2017-09-28 at 11 44 26 am" src="https://user-images.githubusercontent.com/2846578/30977055-6cdcf724-a444-11e7-9896-0faeac14b386.png">
<img width="399" alt="screen shot 2017-09-28 at 11 40 46 am" src="https://user-images.githubusercontent.com/2846578/30977059-6cf808f2-a444-11e7-9643-e420612fbc2a.png">
<img width="401" alt="screen shot 2017-09-28 at 11 44 31 am" src="https://user-images.githubusercontent.com/2846578/30977057-6cef4820-a444-11e7-85f6-d0b0937a7899.png">

cc @rickybanister @MichaelArestad @jeffgolenski @keoshi

**Comment by ebinnion** [comment]
@enejb - These are a11n only, yea?

**Comment by MichaelArestad** [comment]
@melchoyce Is your site icon white?

**Comment by melchoyce** [comment]
Nope. Now that my site's back up, it appears to be loading it: 

![image](https://user-images.githubusercontent.com/2846578/30977760-8b1b5a62-a446-11e7-90c9-09979c03dea9.png)

**Comment by MichaelArestad** [comment]
Oh! Nifty bug! Good catch!

**Comment by melchoyce** [comment]
🙇

**Comment by melchoyce** [comment]
> I'm guessing it relies on the image coming from the site itself which doesn't work when the site is down.

Yeah, I caught the "your site is back online" notification pretty much immediately, so it likely didn't have time to load the favicon now that my site was back up.

**Comment by dmsnell** [comment]
Seems like we could change the behavior in the notifications builder to send a different icon when the site is down.

**Comment by MichaelArestad** [comment]
@dmsnell I agree. Want to take a stab at it?

**Comment by dmsnell** [comment]
Nope :smile:

Maybe in a week or two? I'm pretty AFK at the moment as I onboard into everything Jetpack

**Comment by enejb** [comment]
I think this is still A11C only but would have to check. The url for the image should come from photon so even if the site is down the icon should still work. 

@melchoyce can you double check that the url is coming from photon? 

@MichaelArestad if you want to come up with a site icon for when the site is down that could work as well. I would be happy to update it.

**Comment by melchoyce** [comment]
> @melchoyce can you double check that the url is coming from photon?

It is 👍

**Comment by jeherve** [comment]
**More info about this feature**

Related discussions:
- p1HpG7-3GK-p2
- p77Llu-3cG-p2

Commits:
- D3547-code
- r146796-wpcom

> The url for the image should come from photon so even if the site is down the icon should still work.

Not necessarily, though; the Photon URL would only work if the image was cached by Photon in the past. Since we are requesting a specific image size for that notification, it may happen that this image was never requested before, and thus never cached. Photon will then attempt to cache the image, and will fail if the site (and the static files) is down.

> if you want to come up with a site icon for when the site is down that could work as well. I would be happy to update it.

@enejb Would you like me to move this issue to wpcom, since that's where the code lives?

**Comment by enejb** [comment]
@melchoyce Thank you. 
@jeherve I think leaving it here is fine. Since it is only related to Jetpack sites.

**Comment by v18** [comment]
This notification was jarring for me to look at as well!

<img width="813" alt="jp-monitor-notification" src="https://user-images.githubusercontent.com/11487924/37001223-c7d5a89e-2093-11e8-919d-65dc268e11b9.png">

Also the time is not listed in **my** timezone (the important one), but in UTC.

Also, the text is a bit vague! Let me know if you want me to open new issues for those two new problems ^

**Comment by keoshi** [comment]
@dmsnell do you have the bandwidth to take care of this as part of this week's fixtheflows?

**Comment by rickybanister** [comment]
- [ ] swap the info icon for the offline lightning bolt icon
- [ ] alignment of the info icon in the expanded view for more information about monitor
- [ ] local time, not utc time
- [ ] @melchoyce your site was missing a blavatar, was that site's blavatar just solid white or was that some other issue? I know we used to have trouble with Jetpack blavatars, that may have since been resolved, could you confirm?
- [ ] fix the copy to remove the 'if you're concerned'. Instead it should say `To learn more about your site's status you may want to get in touch with your hosting provider. Jetpack will continue to monitor your site and let you know when it's back online.`

@dmsnell any chance you could assist with any of those changes this week?

**Comment by melchoyce** [comment]
My site icon wasn't white, and it reappeared once my site came back up.

How can I confirm?

**Comment by rickybanister** [comment]
Hrm, you might need to make your site go offline. I guess with Monitor turned on you could edit something in a core file to purposefully break something? @oskosk can you recommend a good way to manually trigger monitor to detect the site being down?

**Comment by roccotripaldi** [comment]
I recently merged https://code.a8c.com/D11036 which improves the copy, and adds an illustrations. I'll make some time to address the other fixes mentioned here.

**Comment by rickybanister** [comment]
Thanks @roccotripaldi!

**Comment by beaulebens** [comment]
These look much nicer now, so I'm going to close this issue.

![screen shot 2018-04-19 at 9 27 26 am](https://user-images.githubusercontent.com/108942/39001614-eea6d342-43b3-11e8-9de0-8c92d291b9f5.png)
