### ISSUE TITLE
Feature request: Infinite Scroll - Place entire posts on single scrollable page

### ISSUE THREAD

**Issue by tnosugar** [Automattic/jetpack#79]
I would like to know whether it is possible to implement the infinite scroll feature in jetpack so that it displays entire pages in one continuous scrollable page, as in www.qz.com.

So, The idea would be to load an entire new page as you scroll from one post to another (placing tcomments and the comment box in an expandable div). And this should be implementable at Category, Tag and (somehow) Page level.

Best regards

**Comment by dereksmart** [comment]
As this would be a nice feature, it's not something that will be part of Jetpack core.  However, @danielbachhuber if there's any filters or something we can provide that will help your standalone plugin?

**Comment by dereksmart** [comment]
@danielbachhuber Please reopen if you can think of any hooks or something we can add to help your plugin

**Comment by jeherve** [comment]
Also requested here:
https://wordpress.org/plugins/infinite-transporter/i

Worth noting that this was implemented in [this plugin](https://wordpress.org/plugins/infinite-transporter/), and it looks like the plugin was based off Jetpack's Infinite Scroll module:
https://github.com/tomharrigan/transporter/blob/master/transporter.php

cc @eliorivero, since we talked about a somewhat related feature not that long ago.

**Comment by jeherve** [comment]
Also in p1HpG7-4su-p2

**Comment by brbrr** [comment]
Is this feature is still needed? I agree with @dereksmart's statement that this feature would not be a part of Jetpack core.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Comment by MuhammedSwalihct** [comment]
@jeherve mentioned in one of the discussions that the feature won't be implemented because it will need different templates for different themes. I've tried this plugin https://wordpress.org/plugins/infinite-transporter/ which seems like created based on the Jetpack infinite scroll code. It works, but not perfectly. It was last updated 5 years ago.

From what I can understand, the only major difference would be the requirement to create a template file that can be used to generate the posts. Apart from that, it is "doable". In my opinion, it is such a wastage of the amazing Infinite Scroll code that already exists on Jetpack.

I am not getting into the benefits of Infinite Scroll, you already know the benefits like increased pageviews, user engagements, etc. So, it is definitely a crucial feature.

Apart from that, unlike many other features, there isn't a single plugin on the market (that is actively maintained), which enables the infinitely scrolling on single posts.

So, if the user can create their own template files for specific themes and make the feature work, I don't think Jetpack team will have to make it compatible with every single theme out there. Webmasters can find their own way. There are theme developers and a large community that will help each other with any specific theme that can make use of the feature in Jetpack.

The only thing that the Jetpack team would have to do is making it a bit simple. Everything except the functions or files that are specific to the themes. And maybe provide a doc or something on how to make it work with different themes. Where to put the template code, etc.

Considering about thinking this feature will be a great achievement for every single Jetpack user. Most of the big sites such as CNET already taking advantage of the feature. And an average WordPress user has no plugins to do that except if they pay large amounts to developers. The only plugin that was working (the ALNP) also stopped providing updates a year back.

**Comment by geoffguillain** [comment]
You will find a working example using Jetpack infinite scroll on single post pages on George's [blog post](https://georgestephanis.wordpress.com/2021/05/24/jetpack-infinite-scroll-for-single-posts/)

He is using the `infinite_scroll_archive_supported` hook to add support for the single template while the `infinite_scroll_js_settings` will let us personalize the JS settings for the single page template.
