### ISSUE TITLE
Changed Domain and Image Links are broken

### ISSUE THREAD

**Issue by pfinstir** [Automattic/jetpack#7961]
I built a WP website and use the Jetpack plugin to create an attractive gallery.  I changed the domain, from the subdomain new.almondtreemanor.com to almondtreemanor.com.  All of the images were migrated to the new domain.

However, now that the website is live, on some of the pages, there are no images.  Instead, the links show that the images are being pulled from the old domain.  I checked the media library (the new domain has been updated) and the wpcontent file on the host.  The images are all there, however, they are pulling from the old domain.

I conducted a search for the http://i2 URL and learned it is generated from Photon.  How do I fix this?  My client is furious and to be honest, I can't blame them.  The site was fine, until I changed the URL and the images didn't change with it.  

![screenshot-almondtreemanor com-2017-10-09-19-14-36-479](https://user-images.githubusercontent.com/20993107/31362486-b82801d4-ad26-11e7-8bd0-bab274016ac8.png)

**Comment by jeherve** [comment]
> The images are all there, however, they are pulling from the old domain.

[Photon](https://jetpack.com/support/photon/) does indeed add the `i*.wp.com` prefix in front of your image URLs, but it does not handle the original image domain. It does not make any changes to how the images are stored in your database either.

If some of the image URLs were not updated when you switched from one domain to another, it is most likely that the old domain is still referenced in a few areas of your database.

I would recommend that you run a search and replace to catch all instances of the old domain in your database and replace by the new domain; if all images have been transferred to the new site you will then be all set!

**Comment by pfinstir** [comment]
All of the images in WordPress  in the media library, that are resident in WP, have the correct URL.  In addition, all of the images in the wpcontent, were transferred.

The images that aren’t in a gallery arrear correctly.  Only the gallery images, that are preceded by URL, that starts with i2, are the ones that are not showing up.

I looked for the links, before writing you.  I even spoke with the host, who could see the images.  No such luck.  My only recourse, if you can’t help, is to do all of the work again.  The images were all fine, prior to the move.  Only the gallery images didn’t change.

Loren

**Comment by pfinstir** [comment]
This does not resolve my issue.  And actually, it’s not true.  The old domain doesn’t exist.  It was a sub domain.  The only way I was able to identify the source was through research.  The host can see the images and so can I in wpcontent.

Several others have mentioned this same problem.  Thanks for nothing.  My site doesn’t work.

**Comment by jeherve** [comment]
Thanks for the extra details.

> that are preceded by URL, that starts with i2

That prefix is added by Jetpack to render the tiled galleries, but the rest of the image path is handled by your theme. If you were to deactivate the Jetpack plugin, the images should still use the old URL, and thus be broken. Could you give that a try, and give me a link to one of the posts where you inserted a gallery, so I can take a closer look? This should allow us to rule out any plugin conflicts with your issue. Alternatively you could disable the Tiled Gallery option and the results would be the same: the `i*.wp.com` would disappear but the rest of the image path would still be wrong.

> The images that aren’t in a gallery arrear correctly.

The path of single images is set in the `post_content` itself, and if those images are displayed properly that means that you managed to find and replace all instances of the old URL within `post_content`.

However, the gallery image paths do not appear in `post_content` since all what it stored there is [a shortcode](https://codex.wordpress.org/Gallery_Shortcode); the image paths are then automatically built by WordPress based on your site options as well as any constants that may overwrite those options in your site's `wp-config.php`.

Note that this is only true for the galleries creating using WordPress; if you used a different plugin to create galleries or sliders or if your theme includes such an option, it is possible that this plugin or theme uses a different method to generate the image paths. In this case I would recommend checking the plugin / theme options to find out more.

Could you run some tests and let me know what you find?

Thanks!

**Comment by WRUSHgadget** [comment]
> This does not resolve my issue. And actually, it’s not true. The old domain doesn’t exist. It was a sub domain. The only way I was able to identify the source was through research. The host can see the images and so can I in wpcontent.
> 
> Several others have mentioned this same problem. Thanks for nothing. My site doesn’t work.

This is why I stopped using Jetpack image speed up, it causes more problems that it fixes.  i use CWV official google cache. 
Even with a search and replace it will ruin the i2 image links.

Use /best search and replace, then manually search posts with the i2  etc, copy that URL in the search, and replace with just your domain without the jetpack front part.
