### ISSUE TITLE
Sharing: Feature suggestion: expose `jetpack_sharing_counts` filter to the UI

### ISSUE THREAD

**Issue by timdream** [Automattic/jetpack#7995]
I would love to be able to turn off sharing count from the UI. I currently do that in `wp-config.php` to suppress XHR requests (see #5189) whenever a page loads.

I believe this also has tracking concern: it means whenever the page loads `facebook.com` gets a ping (along with your identity if the 3rd-party cookie wasn't turned off).

**Comment by jeherve** [comment]
I'm afraid I am going to have to close this as won't fix. Most Jetpack users want the sharing counts (and in fact would want sharing counts for more services). That's why we opted to use only a filter to turn the counts off; we would not want to clutter the interface with an option that most users won't need.

If you think more people would be interested in a UI, you could create a plugin and release it in the plugin directory; if the plugin becomes popular we will know that including such an option in Jetpack may be worth thinking about.

Thank you.
