### ISSUE TITLE
Fatal error triggered by Jetpack_JSON_API_Plugins_Endpoint

### ISSUE THREAD

**Issue by galbaras** [Automattic/jetpack#8011]
Looks like Jetpack isn't running "init", so when "admin_init" is run, some bits go missing. In this case, VTMIN_Rules_UI is defined during "init", and since it's not defined during "admin_init", I'm guessing that "init" was skipped.

```
[15-Oct-2017 12:01:16 UTC] PHP Fatal error:  Uncaught Error: Class 'VTMIN_Rules_UI' not found in /public_html/wp-content/plugins/minimum-purchase-for-wp-e-commerce/vt-minimum-purchase.php:149
Stack trace:
#0 /home/site/public_html/wp-includes/class-wp-hook.php(298): VTMIN_Controller->vtmin_admin_init('')
#1 /home/site/public_html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array)
#2 /home/site/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /home/site/public_html/wp-content/plugins/jetpack/json-endpoints/jetpack/class.jetpack-json-api-plugins-endpoint.php(137): do_action('admin_init')
#4 /home/site/public_html/wp-content/plugins/jetpack/json-endpoints/jetpack/class.jetpack-json-api-plugins-endpoint.php(37): Jetpack_JSON_API_Plugins_Endpoint->get_plugins()
#5 /home/site/public_html/wp-content/plugins/jetpack/json-endpoints/jetpack/class.jetpack-json-api-endpoint.php(30): Jetpack_JSON_API_Plugins_Endpoint->result()
#6 /home/site/public_html/wp-content/plugins/jetpack/clas in /public_html/wp-content/plugins/minimum-purchase-for-wp-e-commerce/vt-minimum-purchase.php on line 149
```

**Comment by zinigor** [comment]
Hello! Thank you for reporting that problem!

Can you tell us a little more about how it happens? Particularly I'm interested in:
* What are you trying to do when this happens? Are you trying to use the WordPress.com admin area?
* Is your Jetpack up to date? The reason I'm asking is that I can't find the `do_action` call in the stack trace you have posted in `Jetpack_JSON_API_Plugins_Endpoint` class.

@enejb do you have any idea how that stack trace could look like this?

**Comment by enejb** [comment]
@zinigor I came across this before with a different plugin and it got fixed in master with https://github.com/Automattic/jetpack/pull/7944
The plugins api endpoint used to do do_action( 'admin_init') in order to figure out what the plugins settings links were supposed to be. This worked most of the time but some plugins had issues with it. Plugins that do funky things like redirects when they are fist installed and the hooks for redirects get added to admin_init action. 
The fix doesn't call admin_init in the plugins endpoint any more (since plugins don't expected admin_init to be called there ) instead it uses a persistant cache of the values and returns it in the api.

@galbaras can you confirm that the latest version of Jetpack fixes this for you. You can use the Jetpack beta plugin to help you test this. You can grab a copy here https://jetpack.com/download-jetpack-beta/

**Comment by galbaras** [comment]
I'm using the latest Jetpack version and my guess is that Jetpack is being called remotely, which means that the issue isn't triggered by some manual action. If there is a way to trigger this, please let me know.

#7944 sure looks like it adds do_action( 'admin_init') to the code, but not do_action( 'init' ), which seems to be causing the issue here. Rather than paste the other plugin's code here, you can download it [here](https://1drv.ms/u/s!AvYtwWI4b_-wlkBDGYhLD0x2u_0N).

**Comment by zinigor** [comment]
@galbaras this code path is executed when you are using WordPress.com settings screen - the API endpoint returns available plugins to be managed in the console. I'm able to get my server to go through that code just by opening a settings screen for my site: https://wordpress.com/settings/general/my.site.url.example.com

#7944 actually removes the `do_action` call from the plugin getter method, so it should be fine. I'd be great if you could test the latest beta and tell us if that fixes the problem for you.

**Comment by galbaras** [comment]
Visiting https://wordpress.com/settings/security/pacificsprings.com.au seems to register this error.

As you can tell from the above misreading of the pull request, I'm no Github expert ;P What else changed in the beta release? Where do I find that information?

**Comment by jeherve** [comment]
> What else changed in the beta release? Where do I find that information?

We haven't hit Beta yet, but you could use [our Beta plugin](https://jetpack.com/beta/) to install Bleeding Edge on your site:
![screenshot 2017-10-19 at 12 17 36](https://user-images.githubusercontent.com/426388/31766317-835ce818-b4c7-11e7-98e0-045463add48d.png)

This Alpha version of Jetpack includes many changes, and you can find a changelog listing the more important changes in #7947.
You could also use GitHub to get a full list of commits and changes since the last stable release:
https://github.com/Automattic/jetpack/compare/branch-5.4...master

**Comment by galbaras** [comment]
Thanks, Jeremy. I don't actually have a test site for this, sorry, and applying a beta release, let alone alpha, to a busy business site is too risky for me.

The good news is that this issue doesn't seem to get in the way of wp.com getting information from the site, and as long as social sharing works, I'm OK to wait for a GA fix.

**Comment by jeherve** [comment]
Alright. In this case I'll close this issue. Feel free to comment again if the problems remain once you get the next stable release on your site. Thanks!
