### ISSUE TITLE
Widgets: gallery type not saved in WordPress' new Gallery widget

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#8113]
#### Steps to reproduce the issue

1. Start on a site running WordPress 4.9.
2. In Appearance > Widgets, find the new core Gallery widget.
3. Drag it to your sidebar, create a new gallery.
4. Choose a custom gallery type such as the ones provided by Jetpack, i.e. Slideshow
5. Save your widget settings.

On the site, the widget will not use that custom gallery type.
In wp-admin, if you edit that gallery in your widget settings, the gallery type is back to default, thumbnail grid.

This may be a core issue if Core is supposed to save the gallery type as well.

**Comment by oskosk** [comment]
For the records:
1. This happens when the Tiled Galleries modules is disabled.
     We are just hooking into core's filter if TIled Galleries is active. As you pointed out Jeremy, we also try too hook the `slideshow` gallery type into the media gallery types.

The result looks like this

![image](https://user-images.githubusercontent.com/746152/32391122-b4693378-c0af-11e7-91b4-d23cb8e7d095.png)

* The `slideshow` type is on the list
* But as **Tiled Galleries** is inactive, we haven't hooked for letting core save the `type` of the Gallery.

**Comment by oskosk** [comment]
This is being addressed in #8116.
