### ISSUE TITLE
Sitemaps: Only include images attached to published and public pages

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#8138]
When using the image sitemap, it currently includes all of the images in the media library. Since sometimes people upload images meant for future posts or are not meant for public consumption (though not locked down), we should investigate only including images that are attached to published and public pages.

Thoughts?

p7DVsv-3I9-p2 Related: #7333

**Comment by zinigor** [comment]
There's currently a way to do it [using a filter](https://github.com/Automattic/jetpack/issues/7333#issuecomment-343550386). But I agree, we need to work on this.

**Comment by kraftbj** [comment]
1427530-zen

**Comment by kraftbj** [comment]
This can result in errors when the image sitemap is attempting to direct someone to a non-public page.

**Comment by foleynotrose** [comment]
Hi @kraftbj and @jeherve: 

This problem came up for a WordPress.com user and an MGS search led me here. 8291431-zd-a8c (starting from 28 June 2024) 

It's my understanding from this closed GH issue that Jetpack Sitemaps should no longer be showing images which are not actually part of a published post. 

Their image sitemaps shows all images in their media library, as does the image sitemap on my test site. 

Has this problem reappeared?

**Comment by jeherve** [comment]
> Has this problem reappeared?

I don't believe so. The problem outlined here was a bit different: we wanted to ensure that if an image was part of a post that was not published yet, it would not be part of the sitemap.

We could, however, consider excluding images that are not attached to any post as well, images that were uploaded under Media > Library instead of through the post editor. I worry this may exclude too many images though, since there may be many unattached images that folks want to be public. Images uploaded via third-party services (like the mobile apps) can sometimes be unattached, for example.

**Comment by foleynotrose** [comment]
> The problem outlined here was a bit different: we wanted to ensure that if an image was part of a post that was not published yet, it would not be part of the sitemap.

OK! That is not how I interpreted the outline of the problem by @kraftbj. 

> We could, however, consider excluding images that are not attached to any post as well, images that were uploaded under Media > Library instead of through the post editor.

So I guess this would be a feature request, and for now I can tell the user to [use a filter](https://github.com/Automattic/jetpack/issues/7333#issuecomment-343550386)? 

Or that they need to delete any images from their Media Library that they don't want on their image sitemap? (I'm not sure if they're not technically savvy enough to enable a filter.

**Comment by jeherve** [comment]
> I guess this would be a feature request, and for now I can tell the user to https://github.com/Automattic/jetpack/issues/7333#issuecomment-343550386?

Right, this may be the best approach for now.

**Comment by ajaykj** [comment]
I have shared both options with the user. Closing this issue again.
