### ISSUE TITLE
Remove devicepx-jetpack.js 

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#820]
Currently 'devicepx-jetpack.js' called the zoomImages function every second. 
How can we improve this function?

**Comment by kasparsd** [comment]
This is a very serious issue because it's forcing the browser to recalculate and redraw the whole layout in case of Safari. Here is the sequence of events:

![jetpack-zoomimages-recalc](https://cloud.githubusercontent.com/assets/169055/12531209/6670d0fc-c1fd-11e5-9374-13cac7d0b8ee.png)

and here is the offending part:

![jetpack-changing-dom](https://cloud.githubusercontent.com/assets/169055/12531214/74f7e444-c1fd-11e5-93d5-d1dcfc7e0f9d.png)

which is called every second as @enejb mentioned:

![jetpack-zoomimages-loop](https://cloud.githubusercontent.com/assets/169055/12531218/87126ab4-c1fd-11e5-90e3-8756956b6bf6.png)

**Comment by kraftbj** [comment]
I'd like us to look at devicepx-jetpack.js overall. Now that Photon supports responsive imaging, how useful is devicepx? Can we reduce/drop usage of devicepx in addition to making this more efficient.

**Comment by BrookeDot** [comment]
I'll go ahead and re-name this issue "Remove Device devicepx-jetpack.js" Since that sounds like the desired result for this issue.

**Comment by jeherve** [comment]
> I would recommend perhaps making the script still filterable but not loaded by default.

That's the approach we discussed in #1850. I'm going to close this issue as duplicate, since they're mostly the same now.
