### ISSUE TITLE
Comments: Check JavaScript against refactored WP Core.

### ISSUE THREAD

**Issue by peterwilsoncc** [Automattic/jetpack#8294]
WordPress commit [42360](https://core.trac.wordpress.org/changeset/42360) updates the comment reply JavaScript to be unobtrusive. 

The `onclick` attribute has been removed and replaced with JS events. Replacing the global should still work but it would be dandy if the Jetpack team could confirm this.

cc @georgestephanis

**Comment by zinigor** [comment]
Thank you for reporting this! A lot of things have changed since the time of the report, so I'm going to close the issue for now. Unfortunately, we don't have the resources to go through the repository and convert all JS to unobtrusive.
However, if you know a certain behavior where converting to unobtrusive JavaScript would help the UX degrade gracefully in current Jetpack interface, please either open a new issue or comment here.
