### ISSUE TITLE
Search: Optionally allow search box to be added to filters widget

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#8372]
There's a disconnect between the search filters widget and the fact that it doesn't provide a search box. One way that we can address this is by allowing users to display a search box by clicking a checkbox.

Here is a sample mockup from @gibrown:

![first-pass-copy-3](https://user-images.githubusercontent.com/1126811/34126398-0a2e7468-e3ff-11e7-8e5e-7b4e7af7eed0.png)

**Comment by ebinnion** [comment]
This issue is being created to list remaining tasks after merging #8358

**Comment by gibrown** [comment]
Additional details:
- When titles are left as empty, then let's not show anything. I can imagine a case where the user only wants the list of filters with no headings, and right now that is not possible
- The "preview results and filtering on a search page" only needs to get displayed when not on a search page. I wonder if we should even grey everything out when not on a search page? Maybe should just highlight it and put it at the top. The link should stay within the customizer, but perform a search that has actual results. Can we easily just take the most common tag or category and use that as the search term?
- Would be good to have a way to rearrange the order of filters in the same way that widgets can get rearranged
- Let's set the default number of items to 5 for everything
- If the user does not have a Pro account, we should display a link to jetpack.com/pricing.

**Comment by gibrown** [comment]
#8412 gets us closer. A few notes on things I tried to do that I couldn't figure out.

1. When the title of the filter is empty we display a title that is created from the name of the filter plus a number. This is used as the key in the aggregation sent to the api, and then just output to the user as is. I think when the user has the filter title set to blank we should not output anything, but because of the way it is tied to the keys of the aggregation this looks like a significant refactoring.

2. The widget control design has a link to the search page within the customizer. I couldn't figure out where the link should go to or how it would work within the customizer. I think the search we should run should just search for the top tag/category like so:

```
<p><?php
	$top_tags = get_terms( array(
		'taxonomy' => array( 'post_tag', 'category' ),
		'orderby' => 'count',
		'order' => 'DESC',
		'number' => 1,
	) );
	if ( empty( $top_tags ) ) {
		$url = '';
	} else {
		$url = $top_tags[0]->name;
	}
	//esc_html( sprintf( __( '' ) ); ?>
</p>
```

3. Was thinking we should advertise the feature inside of the widget, but the widget is disabled unless the plan supports it and the feature is turned on. Wasn't obvious to me how or whether we want to change this. Here is the link I was thinking of adding to the customizer form

```
if( ! Jetpack::active_plan_supports( 'search' ) ) {
	?>
		<div class="<?php echo esc_attr( $classes ); ?>">
			<p><a href="https://jetpack.com/support/search">
				<?php esc_html( "Improve your visitor's search experience by upgrading to Jetpack Professional." ); ?>
			</a></p>
		</div>
	<?php
	return;
}
```

**Comment by gibrown** [comment]
I've removed this from the 5.7 milestone because the PR addresses a lot of it, and I don't think there is enough time to get the rest into 5.7.

The current changes are still a big improvement.

**Comment by ebinnion** [comment]
Closing in favor of separate issues I've created and linked back to this issue.

I have not yet created an issue for:

> The widget control design has a link to the search page within the customizer. I couldn't figure out where the link should go to or how it would work within the customizer. I think the search we should run should just search for the top tag/category like so:

I'm not sure what this means. Asked for clarification in Slack and will add an issue if it needs to be addressed.
