### ISSUE TITLE
Photon messed up PNG images with transparency

### ISSUE THREAD

**Issue by htdat** [Automattic/jetpack#8417]
#### Steps to reproduce the issue

1. Upload the following PNG file to a self-hosted site (one of two files, I am uploading the ZIP file also to make sure GitHub not change anything in the PNG file). 

* ZIP : [website-logo-testing.png.zip](https://github.com/Automattic/jetpack/files/1584670/website-logo-testing.png.zip)
* PNG: [website-logo-testing.png](https://user-images.githubusercontent.com/10045087/34324914-a52c3324-e8b4-11e7-8c51-25e2ecf8590f.png)

2. Add it to a post content. 

3. Enable Photon. 

#### What I expected

Normally, like this (without Photon active)
![image](https://user-images.githubusercontent.com/10045087/34324936-3a0b3cc4-e8b5-11e7-9009-2bcbc3d1ce09.png)

#### What happened instead

There is a pink color for transparency (when Photon is active) 
![image](https://user-images.githubusercontent.com/10045087/34324941-627f7e22-e8b5-11e7-8410-7026a906bf97.png)

#### Other info: 

Tix: 851149-zen

**Comment by arunsathiya** [comment]
Can confirm this is happening with me too. Tried it last night, and yes Photon shows a pink background for all my PNG images.

**Comment by jeherve** [comment]
cc @darthhexx

**Comment by darthhexx** [comment]
The source image is not specifying the correct colour type according to the PNG specification. If you run (you will need GraphicsMagick installed):
> gm identify -verbose Image.png | grep 'Png:IHDR.color-type'

You will see it is set to **2**, but it should be set to **6**. Ref: https://www.w3.org/TR/PNG-Chunks.html

To fix the source image, you will need to re-save by using Gimp to export it as PNG (or some similar tool) and then re-upload the image. Magically the background will be transparent, because Gimp fixes the issue automatically. You can confirm this via CLI too, by performing the same command as above and you will see the type is now **6**.

@arunsathiya if all your PNGs are showing this same defect, please can you send me your test site URL so I can check them out. Thanks.
