### ISSUE TITLE
Widgets: Social icons: handle alternative .tld for each service

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/jetpack#8422]
**Steps to reproduce**: Open the widgets section on WordPress.com Customizer and choose Jetpack's social icons widget. Enter a regional (local) Pinterest link like `https://www.pinterest.co.uk/arunsathiya`

**Expectation**: The Pinterest icon shows up.

**Result**: The Pinterest icon does not show up.

![image](https://user-images.githubusercontent.com/18581859/34362376-f8b1de46-ea98-11e7-98b9-bf9d55bc6ffa.png)

**Suggestion**: Pinterest icon shows up only if global Pinterest links like `https://www.pinterest.com/arunsathiya` are entered. It is suggested that Pinterest icon shows up for any regional Pinterest links too.

**References**: [Seen on this WordPress.com forum thread](https://en.forums.wordpress.com/topic/social-media-link-pinterest?replies=2).

**Comment by kathrynwp** [comment]
cc @thomasguillot

**Comment by arunsathiya** [comment]
Related issue: Pinterest ccTLD links to show relevant icon on menus: https://github.com/Automattic/wp-calypso/issues/23900

**Comment by jeherve** [comment]
Also in 1194308-zen

**Comment by thehenrybyrd** [comment]
Ran into this again in 7651558-hc.

To reproduce:
On any WordPress.com site, head to My Site > Customize > Widgets and add the Social Icons widget.
Add a social icon with a pinterest.co.uk URL such as https://www.pinterest.co.uk/testing/
Then, add another one with the same URL - but .com instead of .co.uk, such as https://www.pinterest.com/testing/
Note that the first shows a generic link icon, while the second shows the Pinterest icon.

It does look like https://github.com/Automattic/wp-calypso/issues/23900 is roughly the same issue, just a bit broader (referring to multiple ccTLDs).
I notice both Arun and I have reported this in relation to WordPress.com sites. Sounds like WordPress.com pulls this from Jetpack, so fixing it in Jetpack would also fix the WordPress.com issue.

**However, this is also an issue with the Social Links Menu.**
To reproduce, grab a WordPress.com site with a theme that supports the Social Links Menu, such as Dara or Radcliffe 2.
Head into My Site > Customize > Menus > Social (create a social menu if necessary)
Add a social icon with a pinterest.co.uk URL such as https://www.pinterest.co.uk/testing/
Then, add another one with the same URL - but .com instead of .co.uk, such as https://www.pinterest.com/testing/
Note that the first shows a generic link icon, while the second shows the Pinterest icon.

**Do the Social Links Menu and Social Icons Widget share the same functionality?**
It looks like it - but if not can someone let me know where to report this for the Social Links Menu?
