### ISSUE TITLE
Lazy images module doesn't work with Apostrophe theme

### ISSUE THREAD

**Issue by StefMattana** [Automattic/jetpack#8490]
**Steps to reproduce the issue**
- Activate Aphostrophe on site with the blog page set as homepage
- Enable Lazy images
- Load the home page
 
**What I expected**
- Featured Images loading okay 

**What happened instead**
Featured Images don’t appear:   
<img width="555" alt="lazy images not working" src="https://user-images.githubusercontent.com/11662998/34714043-0add0adc-f520-11e7-98cb-dfb833808266.png">
  
The posts with no feat. images set up display the theme default place holder as normal:
<img width="728" alt="lazy images not working with not-feat images on" src="https://user-images.githubusercontent.com/11662998/34714050-128d3e82-f520-11e7-9e1e-c92c7ef8b998.png">

The feat images, for the record, [are loading okay](http://dailypinner.eraniapinnera.com/wp-content/plugins/jetpack/modules/lazy-images/images/1x1.trans.gif)
  
Not sure if it’s related with [this Divi issue](https://github.com/Automattic/jetpack/issues/8190)

I thought it could be a general issue Lazy Images might have with this kind of themes, but on Cubic, for example, it works okay :)

**Comment by jeherve** [comment]
Setting priority to Low since this theme is now retired. That does not mean we should not try to understand what's happening here, though :)

@StefMattana Do you think you could try to update to Apostrophe 2, and see if the problem remains?
https://wordpress.com/theme/apostrophe-2

For reference, here is the theme that is affected:
https://wpcom-themes.svn.automattic.com/apostrophe/

It looks like it uses `get_the_post_thumbnail()`:
https://wpcom-themes.svn.automattic.com/apostrophe/content.php

**Comment by jeherve** [comment]
Possibly related: #8499

@StefMattana Maybe you could try to test the patch on your site, see how it goes?

**Comment by StefMattana** [comment]
Lazy Images break the feat images also when active on Apostrophe 2 :(

**Comment by ebinnion** [comment]
After a quick look, I can see that the `data-lazy-src` isn't being add as an attribute to the image, so the JS never picks it up.

```
<img width="248" height="248" src="http://ericbinnion.com/wp-content/plugins/jetpack/modules/lazy-images/images/1x1.trans.gif" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="">
```
