### ISSUE TITLE
Development Mode: Notice in React admin looks off

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#8491]
In a support ticket, a user sent in a screenshot of our wp-admin admin page, and I noticed that the reason for the site being in development mode looks a bit janky.

<img width="1091" alt="screen shot 2018-01-09 at 1 01 56 pm" src="https://user-images.githubusercontent.com/1126811/34738063-811734e4-f53d-11e7-80ea-7f03dbc0e30c.png">

I would expect the "Your site url..." to be aligned left with "Currently in development mode..."

**Comment by sanketio** [comment]
Hey @ebinnion,

It would be nice. But if this list has more then one entry then it would be difficult to understand. 

So I suggest to introduce list with points. Please check below screenshot:

![screen shot 2018-01-12 at 10 36 10 pm](https://user-images.githubusercontent.com/7807348/34886455-0d0ab09a-f7e9-11e7-8eca-5ffd33382e03.png)

This way it be more understandable when one of the list has large sentence like below screenshot:

![screen shot 2018-01-12 at 10 40 19 pm](https://user-images.githubusercontent.com/7807348/34886629-9c003d1a-f7e9-11e7-93f7-1b81340c7d29.png)

Let me know your thoughts on this, so that I can send PR accordingly.

**Comment by ebinnion** [comment]
Hey @sanketio - That looks good to me, but let's ping one of our designers and get some input from them as well. cc @rickybanister @jeffgolenski

**Comment by rickybanister** [comment]
I think the bullet points are a nice improvement. Make it so!

**Comment by ebinnion** [comment]
Hey @sanketio - if you'll submit that PR and tag me, I'll be glad to review it and get it in!

**Comment by sanketio** [comment]
Hey @ebinnion 

Please check #8516. Let me know if you need any changes in that.

**Comment by jeherve** [comment]
fixed in #8516
