### ISSUE TITLE
Search: Allow user to set sub-header via widget instead of hard-coding

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#8553]
Currently, the sub-heading in the filters widget are h4. Let's not do that. 😄 

One option seems to be setting the filters and current filters section to have the same heading as the main widget heading. That will probably look ok.

But, I think the most ideal solution would be to default to the same widget heading, and then allow the user to choose a different heading, perhaps `h[1-6]`?

**Comment by gibrown** [comment]
Hmmm, just a drop down in the customizer that defaults to h4? I switched to h4 because it looked better in a number of themes.

**Comment by ebinnion** [comment]
In the theme above, the smaller header is actually an `h2` while the larger one is an `h4`, and that's a default theme.

I'd suggest that we default to using the same header that is used for all widgets, which is configured by the theme, and then optionally allow users to fine-tune it from a dropdown perhaps.

**Comment by gibrown** [comment]
That sounds good.

**Comment by MichaelArestad** [comment]
I am hesitant to use the same header as the widget titles visually. It makes each grouping look like a different widget rather than a filter that works with search.

The big question I have is:
**How can we change the design of the filters to help the user associate them with the search bar?**

I don't yet have a great answer for this. It's not so easy to add a border or a background. We could do both in a way that looks good on most things. Perhaps the answer is in how they appear, but I think that doesn't solve for the current build as much as the fancy JS version later on.

For now, my best answer is to override the theme's widget header styles in just the search widget to be the same size as the text, have no background color, use the same color as the text, and be a heavier weight than the text. Then we can control the spacing a little better maybe?
