### ISSUE TITLE
Jumpstart: Provide an option to activate recommended features even if dismissed

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#8561]
If a user initially dismisses the "Activate Recommended Features" dialog it would be nice to have a way for them to get back to that and enable it if they so choose.

**Comment by beaulebens** [comment]
This might end up being handled by the checklist work coming from @joanrho and @rickybanister

**Comment by rickybanister** [comment]
I think this fits squarely into that category. Do we feel it's safe to close this as 'wontfix' since it will be precluded by the new checklist (a better and more explicit experience than jumpstart in my opinion?)

**Comment by beaulebens** [comment]
Fine by me. Done.

**Comment by simison** [comment]
I had a thought and found this issue — commenting here just for the record:

Current experience with Jumpstart is _“I just activate Jetpack and enable all these recommended features”_. Having _“I want to optimise my setup”_ -option for tech-savvy users could make influencers write articles like _“How to optimise your Jetpack setup”_ instead of _"Jetpack comes with all this bloat"_.

Does "checklist" cover use case like that? Imagine you'd want everything off by default and enable just a few features, as well have a one-page view of everything that's activated.

**Comment by rickybanister** [comment]
I would say yes, our checklist will accommodate that scenario. You can either specify 'not right now' or similar for every item, or perhaps we can provide a kind of 'skip this whole thing, I'll do it manually' link.

**Comment by rickybanister** [comment]
It's important to remember that that's going to be a very small minority of our users.
