### ISSUE TITLE
Subscriptions / Publicize: Unsupported shortcodes not stripped from email notifications

### ISSUE THREAD

**Issue by csonnek** [Automattic/jetpack#869]
When a user uses a shortcode that isn't part of Jetpack in a blog post, the actual shortcode is sent via the email notification to subscribers in the body of the email rather than being stripped out. For example:

`[dropcap custom_class="normal"]L[/dropcap]orem ipsum...` 

In the blog post, it looks like this: http://d.pr/i/niwT

But in the email, the full shortcode `[dropcap custom_class="normal"]L[/dropcap]orem ipsum...` is displayed in the email. 

I recommend that shortcodes that aren't supported by Jetpack be stripped in the email notifications to avoid the emails being unreadable for subscribers. 

**Related differential:** D3112-code

**Comment by moraitis** [comment]
The solution I would like to see is run `do_shortcode()` to the full length post, then strip out all the HTML that are not the allowed HTML email tags. The allowed HTML email tags could be p, a, strong, em, img, and so on.

So if someone has short code that adds disclaimers or other content they would like in the HTML email, it will not get deleted they way that `strip_shortcode()` would. For my site we have gray boxes around recipes that are made with shortcode, so `strip_shortcode()` would delete the most important part of the post.

I am curious where the source for the posts are gathered by Jetpack to make the emails. I tried modifying the RSS feed, but that does not seem to be the source.

**Comment by jenhooks** [comment]
Also reported here: 2076027-t

**Comment by richardmtl** [comment]
Also 2094857-t

**Comment by jenhooks** [comment]
2108180-t

**Comment by chaselivingston** [comment]
2109247-t

**Comment by samhotchkiss** [comment]
@moraitis - I like this direction

Since the emails get sent from WordPress.com, not your local server, maybe we add a custom field on the post called `rendered_content`, where we store the content after do_shortcode has been run on it?

Anybody have any thoughts on this idea?  Not sure if it's just crazy talk...

**Comment by jenhooks** [comment]
2133205-t

**Comment by jenhooks** [comment]
2138537-t

**Comment by sarahmonster** [comment]
2169486-t

**Comment by richterd** [comment]
Hi there, as I have the same problem I would like to know where the post content is requested... One solution would be to provide a filter so that one can define what content shall be used, or in which way the shortcodes shall be handled. Greetings

**Comment by mikeyarce** [comment]
Also reported here 2186273-t

**Comment by jenhooks** [comment]
2207703-t

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/subscription-shortcodes-not-being-processed-in-email-output?replies=1&view=all

**Comment by jeherve** [comment]
Also reported here:
https://twitter.com/sadhchyme/status/608646647283761152

**Comment by Kaikoloren** [comment]
Hello, we have this exact problem in with our emails. Unwanted Visual Composer code is showing up un-rendered and making the posts look terrible. Has their been any progress on this issue? I noticed that it's been an issue for over a year as I've looked around for possible solutions.

**Comment by fikrirasyid** [comment]
I got similar issue here. Is it possible to provide filters when Jetpack is preparing the post to be synced so plugin / theme can add support by hooking and modifying the shortcode in `post_content`?

Or.. maybe parse the content by using `the_content` filter then kses-ing the output when preparing the post to be synced?

Either way, having this solved will help a lot.

CMIIW anyway: after reading the source code looks like the code responsible for preparing the data to be synced to JP server is `Jetpack_Sync->sync()`, isn't it?

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/subscribe-widget-new-post-e-mail?replies=7&view=all#post-7132092

**Comment by kraftbj** [comment]
Noting that there's an internal team that has this on their radar (how to handle unsupported shortcodes so improve the parity of display between wp.com-served functions and the local JP site). cc: @beaulebens as an FYI of one usage of the ultimate outcome of the team's work.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/code-showing-up-when-a-post-is-made?replies=3&view=all#post-7175714

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/jetpack-email-subscription-feature-showing-coding-even-with-read-more-tag

**Comment by Benunc** [comment]
So, Jetpack pulls straight from the database, or what? Why not pull the post content from the RSS feed, as most shortcodes send processed outputs to the RSS feeds?

I'm still confused where Jetpack gets the content. Straight from the database?

**Comment by jeherve** [comment]
> Straight from the database?

Yes, your post content is synchronized with WordPress.com when you publish the post.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/subscribe-email-not-showing-images

**Comment by csonnek** [comment]
#2312389-t

**Comment by roccotripaldi** [comment]
I like the direction that @samhotchkiss has proposed. I'm going to add it to 3.8, so it can be appropriately assigned. I'm not sure why it has the 'Mercury' label. Maybe because it will require more syncing?

**Comment by beaulebens** [comment]
Yep, we're going to need to handle this via much better syncing of content, specifically in this case, fully-rendered (shortcodes already processed) and then synced. We'll still need to sanitize it on output, and potentially strip some things out on WP.com via `kses`, but we can get a much better starting point by processing shortcodes and syncing that data over, instead of just the raw content.

**Comment by richterd** [comment]
Would be good to also perform __() on the content to allow translatable texts....

**Comment by jeherve** [comment]
@richterd Could you open a new issue for that particular trouble you're having? That seems to be a bit different from the shortcode issue mentioned in this issue.

Thanks!

**Comment by csonnek** [comment]
Also in #2342763-t

**Comment by mkrdip** [comment]
I'm adding my two cents, adding manual excerpt to each post resolves this issue temporarily. I tried it with Divi theme from Elegant Themes.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/subscription-widget-garbled-code-mails?replies=1&view=all

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/emails-to-subscribers-includes-shortcakes?replies=1&view=all

**Comment by jenhooks** [comment]
2454197-t

**Comment by richardmtl** [comment]
2481237-t

**Comment by brdhouse** [comment]
It seems like a simple solution to all this would be if Jetpack had an intermediate step to review/edit/approve/send this translation of the content before it's cross-posted.

**Comment by jb510** [comment]
Is there any intent on the JetPack team to fix this so that plugin/theme shortcodes work? or is the only road map getting better at stripping out shortcodes even when they're critical to the content being displayed?

**Comment by kraftbj** [comment]
@jb510 There hasn't been a technical decision made yet. There are some hurdles with returning rendered content (how to sanitize it for e-mail? How do handle column-forming shortcodes in the context of Publicize content?) that we'd need to explore a bit. @beaulebens's comment above stands: https://github.com/Automattic/jetpack/issues/869#issuecomment-136392207

**Comment by beaulebens** [comment]
Yep, as mentioned above, fixing this with the way that Jetpack currently works depends entirely on improving the way that we sync content to WordPress.com (which is where things like Publicize and email subscriptions actually get sent from). 

We're actively working on how to improve that, but don't have a solid plan just yet (there are short and long term considerations to all of the possible approaches we've looked at, so we're trying to figure out something that balances the two). All of that to say yes, we do intend to fix it, and yes, as of right now, there is a team of people actively looking at how to handle this.

**Comment by jb510** [comment]
TY. I do understand the hurdles and am glad you are intent on working on it (after 18 months wasn't sure there was actually interest). 

It seems like it'd be simple to just pull from the RSS feed (which is what I had always assumed occurred before discovering you're pull post_content directly via API).  I get it's never _that_ simple, but that's what many similar "post by email" solutions use.

**Comment by TamieDearen** [comment]
So this has been a problem since 2014 and we're no closer to a solution?!!! I just put up my first post on my new wordpress website using jetpack for my transfered subscribers, and they were sent a huge email full of shortcode! Why was there no warning about this issue before you let me look like an idiot? What is the temporary solution for someone like me, who is not adept at understanding these issue or the solution? Is there another plugin that will perform the same function without these problems? One that recognizes the shortcode or reads from the RSS feed? Or is there a way to send a summary or preview the email and make changes before it sends gibberish to all of my followers? (If they haven't all unfollowed after receiving the unreadable email...)


[fullwidth backgroundcolor="" backgroundimage="" backgroundrepeat="no-repeat" backgroundposition="center center" backgroundattachment="scroll" video_webm="" video_mp4="" video_ogv="" video_preview_image="" overlay_color="" overlay_opacity="0.5" video_mute="yes" video_loop="yes" fade="no" bordersize="0px" bordercolor="" borderstyle="solid" paddingtop="20px" paddingbottom="20px" paddingleft="0px" paddingright="0px" menu_anchor="" equal_height_columns="no" hundred_percent="no" class="" id=""][one_half last="no" spacing="yes" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" border_size="0px" border_color="" border_style="" padding="" class="" id=""][fusion_text]

[/fusion_text][/one_half][one_half last="yes" spacing="yes" background_color="" background_image="" background_repeat="no-repeat" background_position="center center" border_size="2px" border_color="#1fa3c1" border_style="solid" padding="" class="" id=""][fusion_text]

/fusion_text][/one_half][/fullwidth][fullwidth backgroundcolor="" backgroundimage="" backgroundrepeat="no-repeat" backgroundposition="left top" backgroundattachment="scroll" video_webm="" video_mp4="" video_ogv="" video_preview_image="" overlay_color="" overlay_opacity="0.5" video_mute="yes" video_loop="yes" fade="no" bordersize="0px" bordercolor="" borderstyle="solid" paddingtop="20px" paddingbottom="20px" paddingleft="0px" paddingright="0px" menu_anchor="" equal_height_columns="no" hundred_percent="no" class="" id=""][one_half last="no" spacing="yes" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" border_size="2 px" border_color="#1fa3c1" border_style="solid" padding="" class="" id=""][fusion_text]An Excerpt from Alora: The Wander-Jewel  (Book One of the Alora Series)

**Comment by jeherve** [comment]
> So this has been a problem since 2014 and we're no closer to a solution?

We're working on it. You can follow the discussion above to find out more.

> Why was there no warning about this issue before you let me look like an idiot?

I'm afraid we do not output any warning about the use of shortcodes in the post editor, sorry about that.

> What is the temporary solution for someone like me, who is not adept at understanding these issue or the solution?

Until the problem is fixed, there are 2 alternatives to work around the issue:

- If you go to Settings > Reading in your dashboard, you can change your Feed Settings to "Summary". Once you save your changes, all subscription emails will only include an excerpt of your post, with a link to continue reading on the site. You can set a custom excerpt thanks to the excerpt box below the editor.
- If your Feed settings are set to "Full Post", you can split the content of each one of your blog posts in 2 parts thanks to the More tag:
`<!--more-->`

Everything that is above the More tag will appear on your home page and in the subscription emails, followed by a link inviting users to click to continue reading; everything that is below that tag will only appear on the post's page. You could consequently place your shortcodes below that tag.

You can read more about it here:
http://en.support.wordpress.com/splitting-content/more-tag/

I hope this helps.

**Comment by TamieDearen** [comment]
Yes! Thank you so much! This sounds simple enough that even I can handle it.

**Comment by TamieDearen** [comment]
Thank you for your quick reply!

**Comment by TamieDearen** [comment]
This "Summary" fix did not work at all. The shortcode appears a the very
beginning of the email. I must say I'm disgusted. I have a hard time
believing the people who developed the JetPack plug-in don't know how to
fix this issue. I suspect, you don't want to fix the issue, as that might
force people to abandon their self-hosted sites.

Whatever the reason, I see that there is no hope of a solution, since none
has been "found" since 2014. However, I will do my best to warn everyone
out there who might unwittingly use the JetPack plugin, as I did, without
knowing they might drive away their followers with emails full of shortcode
instead of content.

**Comment by TamieDearen** [comment]
This "Summary" fix did not work at all. The shortcode appears a the very beginning of the email. I must say I'm disgusted. I have a hard time believing the people who developed the JetPack plug-in don't know how to fix this issue. I suspect, you don't want to fix the issue, as that might force people to abandon their self-hosted sites.

Whatever the reason, I see that there is no hope of a solution, since none has been "found" since 2014. However, I will do my best to warn everyone out there who might unwittingly use the JetPack plugin, as I did, without knowing they might drive away their followers with emails full of shortcode instead of content.

**Comment by jeherve** [comment]
@TamieDearen Both work-arounds appear to work on my end. If that didn't work on your end, could you [send us an email](http://jetpack.me/contact-support/) with more details about your site, so we can take a closer look?

Thanks!

> Whatever the reason, I see that there is no hope of a solution

You can check the discussion above to learn more about the issues behind the bug, and the possible solutions we've discussed. We will find a solution!

**Comment by TamieDearen** [comment]
Thanks for responding. With the help of some more computer-literate friends in my Facebook group, I have determined a solution that works for now. Essentially, I'm bypassing the editor on my website with Advanced Excerpt (from Delicious Brains) which takes me to the plain wordpress editor for the beginning of the post. This allows me to write a custom excerpt for the emails. After the beginning of the post, I'm actually switching back to my website editor, which gives me a much nicer appearance to the blog post than the wordpress editor. It's complicated and cumbersome, but it's working. Perhaps it will help someone else in my same situation.

**Comment by PriteshDas** [comment]
Almost two years down the line and this issue is still screwing our those all important emails. The easiest method that has worked for me is to temporarily remove any short-code from first two paragraphs of my post just before hit the publish button. Wait for a moment of two and and revert back to the previous version that has all those short codes.

**Comment by TamieDearen** [comment]
Thank you. That seems to be working. :D

**Comment by PriteshDas** [comment]
@TamieDearen - Glad it helped you.

**Comment by chaselivingston** [comment]
2557736-t

**Comment by carinapilar** [comment]
2571487-t

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/content-of-post-in-subscriber-email-a-problem?replies=1&view=all

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/publicize-problems-posting-to-g-page?replies=7&view=all#post-8189109

**Comment by jenhooks** [comment]
2605908-t

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/subscription-picture?replies=1&view=all

**Comment by davoraltman** [comment]
2634106-t

**Comment by macmanx2** [comment]
2637908-t

**Comment by macmanx2** [comment]
2622751-t

**Comment by seejacobscott** [comment]
2662749-t

**Comment by bassplayer7** [comment]
Has there been any progress on this bug? 

Would you guys consider adding an option to blacklist shortcodes as an interim fix? Or is there a hook or filter I could use (or that could be added) to remove the codes myself before the post content goes up to Automattic?

**Comment by csonnek** [comment]
Also: 
https://wordpress.org/support/topic/sent-emails-contain-builder-code-instead-of-text?replies=1

**Comment by annezazuu** [comment]
2674122-t for the better click to tweet plugin

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/cloaking-plugin-code-showing-in-subscriptions-new-post-email?replies=1&view=all

**Comment by jeherve** [comment]
Also reported in 2680025-t

**Comment by kraftbj** [comment]
For everyone following along, as @beaulebens mentioned earlier ( https://github.com/Automattic/jetpack/issues/869#issuecomment-176403611 ), we need to change quite a bit about how Jetpack passes content to WordPress.com in order to resolve this. We are currently testing the next generation of this process that would give us the building blocks to greatly improve this experience. There isn't anything more firm to share with timelines and whatnot, but did want to let you all know it _is_ still very much being worked on.

**Comment by v18** [comment]
2699598-t

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/en-and-in-publicize-post?replies=1&view=all

**Comment by RCowles** [comment]
Also reported in:
2724287-t

**Comment by RCowles** [comment]
2727001-t

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/error-in-widgets-subscription-tickets?replies=1&view=all

**Comment by danjjohnson** [comment]
Another report: 2747161-t

**Comment by ntpixels** [comment]
2748670-t

**Comment by jeherve** [comment]
Also reported in https://wordpress.org/support/topic/issue-with-jetpack-publicize-and-google?replies=1&view=all

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/jetpack-subscription-emails-in-multiple-languages-qtranslate-x/

**Comment by annezazuu** [comment]
2821321-t

**Comment by lamdayap** [comment]
1272800-t

**Comment by annezazuu** [comment]
2862547-t

**Comment by vparkhere** [comment]
2862411-t

**Comment by bikedorkjon** [comment]
2909535-t

**Comment by vparkhere** [comment]
2913905-t

**Comment by fransimo** [comment]
+1

**Comment by seejacobscott** [comment]
2952616-t

**Comment by alexjgustafson** [comment]
2948323-t

**Comment by pmciano** [comment]
2958794-t

**Comment by gravityrail** [comment]
This should now be 99.9% fixed. We are handling 200+ popular shortcodes in the email sending routines in WPCOM.

**Comment by gravityrail** [comment]
And with the sync shortcode tags above coming out in JP 4.5, that should get us to 99.9% (100% is not possible since it's impossible to always distinguish between a real shortcode and a word in [brackets])

**Comment by jenhooks** [comment]
3138886-t

**Comment by lamdayap** [comment]
reported here 3268670-t for nextgen gallery plugin's shortcode

**Comment by lamdayap** [comment]
3298847-t 

Shortcode [Ad] is appearing in their publicized posts. Unsure if this is coming from a plugin or their theme.
