### ISSUE TITLE
VideoPress: .mov and .avi files uploaded in Media > Add New cannot be embedded

### ISSUE THREAD

**Issue by druesome** [Automattic/jetpack#8752]
Steps to reproduce:

**wp-admin panel**

1. Visit Media > Add New in wp-admin panel of an AT or self-hosted site
2. Upload a .mov or .avi file (ie `sample_iTunes.mov`)
3. Create a new post via Posts > Add New
4. Click Add Media and select the recently uploaded .mov file

Expected: video file is embedded

Actual: A link to the video is inserted

`<a href="https://domain.com/wp-content/uploads/2018/02/sample_iTunes.mov">sample_iTunes</a>`

**Calypso dashboard**

1. Create a new post via Blog Posts > Add
2. Click Add > Media and select the same .mov file (`sample_iTunes.mov`)

Expected: video file is embedded

Actual: An embed shortcode for the video is inserted:

`[video src="https://domain.com/wp-content/uploads/2018/02/sample_iTunes.mov" height="480" width="640"][/video]`

But shortcode isn't recognized on the published work, and shows up as a regular link.

Screenshot:

<img src="http://cld.wthms.co/h8lb83+" width="600" />

Results can be replicated by following the same steps above for .avi files.

This works fine with .mp4 files uploaded in the same way.

#940306-zen

**Comment by jeherve** [comment]
`.mov` and `.avi` files aren't supported by most browsers, so netiher the embed nor the shortcode will work when using those extensions.

As per the codex:

> You can use the following options to define specific filetypes, allowing for graceful fallbacks:
> 'mp4', 'm4v', 'webm', 'ogv', 'wmv', 'flv'
-- https://codex.wordpress.org/Video_Shortcode

If you were to use VideoPress instead of uploading the videos to the site's media library, the video would be converted, and you would be able to insert a VideoPress shortcode instead, or a VideoPress URL.

If you meant to use VideoPress, but it did not seem to be triggered, I would recommend making sure that the feature is enabled under Jetpack > Settings, and then trying to upload the video via the post editor directly, with "Add Media". Let me know how that goes!

**Comment by druesome** [comment]
Thank you @jeherve for the clarification!  Apparently I was looking at the wrong place for reference (https://en.support.wordpress.com/videopress/).  Since the videos were not uploaded to VideoPress, that page doesn't apply. :D I've replied to the user, giving them the steps to upload to VideoPress.
