### ISSUE TITLE
Site isn’t visible to me via Calypso if I’m not Jetpack primary user

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#8756]
### What happened
As an admin of a wp.org site, I cannot see the site via **My Sites** in wp.com if I'm not Jetpack primary user.

Jetpack primary user can see the site via wp.com as well see me at wp.com **People**-list marked as an admin.

### What I expected
To be able to fully see and control the site since I’m listed as an admin even at wp.com

**Comment by simison** [comment]
_Not quite sure how to tag this and I'm assuming there might be a related issue somewhere but I couldn't find any._ @jeherve?

**Comment by jeherve** [comment]
> I cannot see the site via My Sites in wp.com if I'm not Jetpack primary user.

I believe that is the expected behaviour. You should, however, see the site once you've connected the site to your own WordPress.com account. If you go to the Jetpack menu in wp-admin, you should see a notice at the top inviting you to link your own account. Once you've done that, ownership of the site won't change but you too will be able to remotely manage the site via WordPress.com.

Let me know how that goes!

> Not quite sure how to tag this

Don't worry about it, I take care of the labels during daily triage :)

**Comment by simison** [comment]
>I believe that is the expected behaviour. You should, however, see the site once you've connected the site to your own WordPress.com account.

Right on, this is correct!

It's clear to me now that I know how it's supposed to work but there's probably some room to improve explaining all this to our users.

I'll close this one anyway.
