### ISSUE TITLE
Lazy Load Blocks Shortcake Plugin Image Comparison

### ISSUE THREAD

**Issue by mrjarbenne** [Automattic/jetpack#8785]
When Lazy Load is activated, Shortcake Bakery (which includes an Image Comparison shortcode rendered through juxtapose.js) fails to render. I've reported the issue on that repo as well (https://github.com/wp-shortcake/shortcake-bakery/issues/218), but solving this may require Lazy Load to filter additional elements, as was required for avatars previously: 

https://github.com/Automattic/lazy-load/commit/d6045f66b60b4874c4b13e50fdbe5a2a0550a83f

**Comment by zinigor** [comment]
Thanks for reporting this, we'll take a look!
cc @ebinnion

**Comment by ebinnion** [comment]
Hello @mrjarbenne –

I've added the ability to bypass processing lazy images that have a certain class in #8787. I've also added a couple of filters so that plugins/theme can add extra classes to skip and or skip based on a given image's attributes.

This won't fix the issue with Shortcode Bakery out of the box since I didn't see any classes or attributes that were specific to Shortcode Bakery in their code: https://github.com/wp-shortcake/shortcake-bakery/blob/eb99eec95bcfc323e113d92db1f5b44f52e34336/inc/shortcodes/class-image-comparison.php#L112-L129.

As a note, they do add `data-label` and `data-credit` but those seem generic enough that we may not want to filter out all images with those attributes present.

I'm curious what you think of this approach.
