### ISSUE TITLE
Search: Use update_widget_callback instead of update_option

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#8815]
While working on adding tracks values to search widget, I added some gnarly code that listens to all option updates, checks if the `widget_jetpack-search-filters` option is being updated, and then does a diff on the new and old value to see if the widget is being updated.

That's mmm... not great. At the time, I didn't consider the `widget_update_callback` hook because I figured it was just used to short-circuit saving of the widget. Now I believe we can probably use the `widget_update_callback` hook and remove the diffing logic.

Here are some links to the code I'm mentioning:

https://github.com/Automattic/jetpack/blob/baf39348d549ccfe32e7ebc99c8414877ef3cf73/modules/search/class.jetpack-search.php#L189

https://github.com/Automattic/jetpack/blob/baf39348d549ccfe32e7ebc99c8414877ef3cf73/modules/search/class.jetpack-search.php#L1756-L1771

https://github.com/Automattic/jetpack/blob/baf39348d549ccfe32e7ebc99c8414877ef3cf73/modules/search/class.jetpack-search-helpers.php#L368-L446

**Comment by eliorivero** [comment]
I've been checking this and found that while `widget_update_callback` is applied when a widget is added or updated, it's not when it's deleted. You check that the code in core
https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-widget.php#L405
goes through a different branch when a widget is deleted, and `widget_update_callback` is never called in that branch.
Will close this since, for our tracking purposes, what you wrote is complete.
