### ISSUE TITLE
Search: sort box overlapping search box

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#8828]
It looks like our sort box could probably use some better styling in some themes.

In both twentyfifteen and twentysixteen the front end sort box is slightly overlapping the search box

![screen shot 2018-02-13 at 10 29 14 am](https://user-images.githubusercontent.com/820871/36164483-b0a3d47e-10a9-11e8-8255-63705ccd7676.png)

Kinda related to #8742, but I think this was probably introduced in #8737

**Comment by Viper007Bond** [comment]
I can't reproduce this on my Windows machine. Do you have `define( 'SCRIPT_DEBUG', true );` in your `wp-config.php` so that the scripts and stylesheets load individually, or alternately have you done `yarn build` lately and cleared your browser cache?

We have some top padding on that `div` already:

https://github.com/Automattic/jetpack/blob/5.8/modules/search/css/search-widget-frontend.css#L20

![firefox_2018-02-13_17-12-55](https://user-images.githubusercontent.com/406254/36183100-a7f02c8c-10e1-11e8-9d06-17d9f912eec2.png)

![firefox_2018-02-13_17-12-44](https://user-images.githubusercontent.com/406254/36183108-ab925888-10e1-11e8-9fab-4506398c8661.png)

**Comment by gibrown** [comment]
OK, ya looks like once I ran `yarn build` I now am seeing the correct styling.

Sorry about the false alarm, have now enabled `script_debug` Thanks!
