### ISSUE TITLE
Incorrect usage of jetpack_verification_validate results in a warning.

### ISSUE THREAD

**Issue by zinigor** [Automattic/jetpack#8848]
Originally [reported](https://wordpress.org/support/topic/jetpack-error-when-using-the-website-verification-services/) in the support forum. 

#### Steps to reproduce the issue
I’m trying to add meta tags (from Google, Yandex, Bing and Pinterest to my site in the Tools section).

Each time I press Save, I get the following:

```
Warning: Parameter 1 to jetpack_verification_validate() expected to be a reference, value given in /srv/disk1/2556167/www/andiepasdedeux.com/wp-includes/class-wp-hook.php on line 288

Warning: Cannot modify header information – headers already sent by (output started at /srv/disk1/2556167/www/andiepasdedeux.com/wp-includes/class-wp-hook.php:288) in /srv/disk1/2556167/www/andiepasdedeux.com/wp-includes/pluggable.php on line 1216
```

#### What I expected

No warnings should have been raised.

**Comment by ohknowledge** [comment]
Warning: Parameter 1 to jetpack_verification_validate() expected to be a reference, value given in /home/ohknogfp/public_html/wp-includes/class-wp-hook.php on line 288

Warning: Cannot modify header information - headers already sent by (output started at /home/ohknogfp/public_html/wp-includes/class-wp-hook.php:288) in /home/ohknogfp/public_html/wp-includes/pluggable.php on line 1216
issue please help me
Thank you

**Comment by david-binda** [comment]
This does not seem to be just a matter of a Warnings, but it is actually breaking the "Website Verification Services" tool located in Tools page in wp-admin which is using different route, than the REST API powered Settings page found under Jetpack => Traffic.

The Tools interface uses `register_setting` and the `jetpack_verification_validate` is used as `sanitize_callback` ( [#](https://github.com/Automattic/jetpack/blob/814e8bb12f57faf30647ebc67a706964fd9e7a78/modules/verification-tools/blog-verification-tools.php#L35) ), the function is then not obtaining `$verification_services_codes` as a reference ( due to [the way `sanitize_option` calls it's filters](https://core.trac.wordpress.org/browser/tags/4.9/src/wp-includes/formatting.php#L4314) ) and thus changes the value of codes to `null` which prevents the metas from being saved, which breaks the feature.

I'm not sure what would be the best way to fix this. Perhaps not using the value as reference on neither place, and use the `$value = jetpack_verification_validate( $value )` construct in places for which the reference was introduced?

**Comment by csonnek** [comment]
Also reported in 1019578-zen

**Comment by gravityrail** [comment]
I believe this is now being fixed as part of other work
