### ISSUE TITLE
Lazy Images: Images don't load after hitting "Older Posts" - Divi theme

### ISSUE THREAD

**Issue by seejacobscott** [Automattic/jetpack#8854]
With Lazy Images enabled while using the Divi theme, on the blog page the featured images load in the post preview, but after clicking "Older Posts" the images do not show on the second page. 

Issue is occurring here: https://seasons-of-smiles.com/dental-blog

First page of blog posts: 

![](http://cld.wthms.co/0jGSP3+)
Image Link: http://cld.wthms.co/0jGSP3

After clicking "Older Posts":

![](http://cld.wthms.co/mS4dwm+)
Image Link: http://cld.wthms.co/mS4dwm

Reported in 961050-zen

The user may disable the Lazy images feature until this is solved.

**Comment by ebinnion** [comment]
This is likely still an issue as I haven't explicitly added integration between Lazy Loaded images and Divi. I did add a new `jetpack_lazy_images_load` event that Divi, or the user, can tie in to:

```
jQuery( 'body' ).trigger( 'jetpack_lazy_images_load' );
```

**Comment by aloeveraitalia** [comment]
Hello, 
I'm a Divi user since 1,5 years and get to this page because of the problem you described above. I have the same problem and one really super kind Jetpage-supporter told me of this topic. 

I tried the suggestion of StefMattana and tried 4 way (simply because I did not really understand which is the right one): 
with the plugin suggestest, tried to put the scribt in both fields the Plugin offers: 
it does not worked

Thank I also tried without using the Plugin an put the code in 
Divi-Themeoption - Integration - head-field
Divi-Themeoption - Integration - Body-field

Nothing worked out. 
I discovered this Divi-Jetpack-conflict only yesterday. 

I made those steps for https://www.aloeveraonline.it but I have also other webpages with the same problem. 

Maybe I understand the problem of visualization for the images on the “2. Page” for blog module:

Normaly when you click on a link AFTER in your browser you see the destination link (the address where you are).
something like that: https://www.aloeveraonline.it/aloe-hand-soap-sapone-liquido-allaloe-vera-della-forever-living-products/ (this is one of the articles of the blog module in which I try to visualize the featured image) 

BUT 
When you are at 
www.aloeveraonline.it e go with the mouse on “post precedenti” you see the destination page www.aloeveraonline.it/page/2 in the browser but when you click on it in the browser is NOT written www.aloeveraonline.it/page/2 but only: www.aloeveraonline.it 
Try to click on the REAL-destination page here: 
www.aloeveraonline.it/page/2
and magically you can see the images – BEEING on the 2. Page!!! 

That is funny! 
I also tried to DEACTIVATE the Jetpack-Lazy-Load function and use a Lazy Load Plugin: same problem. 

I will write now to Divi. This topic here is nearly one year old. They should try to fix this problem! 

Greetings, Martina from Italy

**Comment by aloeveraitalia** [comment]
I solved the problem DEACTIVATING the lazy load function in Jetpack and cleaning all (browser, cache of the homepage and Cloudflare): 
Greetings, Martina

**Comment by StefMattana** [comment]
Thanks, @aloeveraitalia, for the followup! 

Sorry you had to deactivate the Lazy Images feature; I recommend you to try re-enabling it soon again when you get Jetpack updated to its next version(s), as the feature will be improved, and eventually it might work with your current site settings. 

Please don't hesitate to re-open the issue here if you have any further questions or need more help :)

**Comment by NdegwaJulius** [comment]
I'm still facing the same issue . 'Images don't load after hitting "Older Posts"
'
