### ISSUE TITLE
Sharing: Official Pinterest button misaligned

### ISSUE THREAD

**Issue by alaczek** [Automattic/jetpack#8883]
When switching to "Official buttons" option in sharing module, the Pinterest button is displaying slightly lower then other sharing buttons. This does not seem to be theme specific (I was able to reproduce in Apostrophe 2, Toujours, Twenty Seventeen) and the issue is visible on the settings page in Calypso as well.

#### Steps to reproduce the issue
1. Navigate to Sharing > Sharing Buttons in Calypso.
2. Enable a few services, including Pinterest.
3. Select "Official Buttons" under Button style.
4. Save and view a post/page.

#### What I expected
I expected all the buttons to be aligned. 

#### What happened instead
The Pinterest button is displayed slightly lower then others.

### Screenshots
Calypso settings page:
![image](https://user-images.githubusercontent.com/4550351/36401146-95531538-1629-11e8-8210-410908e1cd3d.png)

Front end:
![image](https://user-images.githubusercontent.com/4550351/36401171-c02b1d32-1629-11e8-82df-cd01cf20a5e7.png)

**Comment by arunsathiya** [comment]
#2144105-hc

**Comment by torres126** [comment]
Still an issue, along with the LinkedIn one.

**Comment by torres126** [comment]
PR in #12037

**Comment by kylemcph** [comment]
Another user report of the Pinterest button being misaligned.

12101491-hc

I have tested this, and the issue seems to be fixed on simple sites, but not AT sites: 

![](https://cld.wthms.co/PJxSat+)
Direct link to image: https://cld.wthms.co/PJxSat

Screenshot is from Twenty Nineteen theme, but every WordPress.com theme tried produced the same result.
