### ISSUE TITLE
Enhancement: Include "plan expiring" banner within plugin and calypso

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#8948]
When you have a Jetpack plan which is expiring, there's no indication within the plugin, nor within Calypso (except for on the "Manage Purchases" view).

Aside from the email that's sent out, we should include a banner in:
1) Calypso 
2) Jetpack dashboard within wp-admin
3) Main dashboard of wp-admin

I want to implement the multiline JITM that myself and @withinboredom built out **in order to provide a more personalized experience** to reduce churn. Based on whatever plan the user has, we should **list their top 3 most used features** that will be lost if the plan expires.

I realize that may be a bit of logic to write, so if that's too much, perhaps we add three generally popular features that they stand to lose (see mockup below).

**Example visual on the jetpack dashboard:**

![plan-expiring-jitm](https://user-images.githubusercontent.com/214813/36797653-79d328cc-1c76-11e8-8abd-5aa7ad98c9dd.jpg)

**The professional plan expiry JITM should read:** 
Line 1: "Your Jetpack Professional subscription expires in 1 month!"
Line 2: "Don't lose out on these great Professional features"

Bulleted list:
* most used feature
* 2nd most used feature
* 3rd most used feature

[link]Renew now[/link]

This way the JITM is much more personalized and will hopefully motivate folks to renew. And the multiline JITMs are already built, just not in use. 

@richardmuscat @nicoleckohler I'd like your thoughts on the personalization and verbiage. cc @bubel so we can stay consistent with the emails. cc @beaulebens who initially made the suggestion

**Comment by bubel** [comment]
Love this idea. I'm not sure how much sense it makes to try and figure out "most used/loved/valued" features within this context; my gut is that it's going to be a lot of work to get right. Maybe something for a future iteration, but I think it's worth trying something simpler as the first step. For a site like the one in the screenshot, I think we can even bypass the list for now (we can't send HTML, so that would have to be looked at) and just focus on maybe the backups/security feature. If, for some reason, they don't have that activated (or there's some kind of issue preventing usage), we can shoot for a more generic notice — but we should probably do something more if we find that's the case.

Previously, Rob and I chatted about retention JITMs like this but more so focused on activating/discovering valuable features that the customer hasn't yet tapped into. I think this fits well in with those potential versions when we get to them.

We should also consider only showing this to customers who have disabled auto-renew.

**Comment by withinboredom** [comment]
I'm thinking only showing this to annual plan owners for now, 30 days is way too far out for monthly subs (which are likely always expiring within 30ish days).

**Comment by bubel** [comment]
> I'm thinking only showing this to annual plan owners for now

Yes, absolutely.

**Comment by nicoleckohler** [comment]
I love this idea. If personalization is too hard/out of scope I definitely agree with picking the three most "valuable" features in each plan and highlighting those as a potential loss.

A thought for a potential A/B test on this would be to not show the JITM until something like 7 days before, and see if the urgency increases renewals (theory being that 30 days = "oh i'll get around to it," a week or less = "ah crap").

**Comment by nicoleckohler** [comment]
Also re: wording, I'd just call them "valuable" features or something similar (instead of "professional" which is what appears in the current mockup).

**Comment by bubel** [comment]
> I'd just call them "valuable" features or something similar

Agreed.

**Comment by withinboredom** [comment]
![image](https://user-images.githubusercontent.com/1883296/37037615-aec5386e-2120-11e8-80ef-08211904d53e.png)

I changed the wording a bit, we don't have any way to send a list... but we can see how this works as is, I suppose.

I also will make it show at most 5 times, with 2 weeks between showing.

**Comment by withinboredom** [comment]
We now have checkboxes!

![image](https://user-images.githubusercontent.com/1883296/37039961-baf6b738-2126-11e8-97a6-508273ee10fc.png)

It'll require a jetpack release, but as shown above will be what's shown in a non-compatible release.

**Comment by withinboredom** [comment]
Getting D10698-code merged, then will open the jetpack pr

**Comment by nicoleckohler** [comment]
Let's keep the "valuable features" wording I proposed and add a period at the end of the line (which I think is standard for most JITMs?) -- I think that makes the most sense.

If we need more context around what that means or can't always show the checklist, maybe we could add a link to a pricing page from the message?

**Comment by jeffgolenski** [comment]
@withinboredom @nicoleckohler 

Just digging in now! So, for a v.1 I really like the idea of a general statement like "Valuable features" but in further iterations I'd really like to get more personalized feature listing specific to personal, premium, and professional plans to communicate that the features we're listing are part of said plan.

So does it make sense to change this string to say: 
> "Don't lose out on these valuable features that are part of your [plan name] plan" ?

@withinboredom At this point do we have a different message conditional set up to display a slightly different JITM based on their plan level? I'll want to jump in and customize the svg icons (each plan has a different one). You currently have it just as the logo (totally fine for now). 

**Data**

Also for tracking! This is a big one. We're going to need to see how many folks see this JITM and how many folks actually click renew and who dismisses it. However, since folks may renew via email messages or whatnot, I wonder if its possible to cross-ref that data to get a better picture of how successful our new JITM and renew emails are in comparison to overall paid churn. cc @bubel

**Comment by nicoleckohler** [comment]
> So does it make sense to change this string

It could be a _bit_ repetitive as you've suggested (repeating the plan name) -- maybe:

> Don't lose out on the valuable features your plan provides:

Eh?

**Comment by jeffgolenski** [comment]
@nicoleckohler 

"Don't lose out on the valuable features your plan provides"

sold!

**Comment by withinboredom** [comment]
Hey @jeffgolenski ... I opened the PR that will parse the lists. #8991 It could reeally use your love on that... I attempted but I think I just made it worse and reverted it. I do not have an eye for alignment haha.

I also invented a way to make jitms super personalized, so we can make do that kind of stuff. I would avoid referencing "the list" because anyone using Jetpack 5.9 or below won't be able to see the list. However, we can target a jitm that is using greater than 5.9 with different content.

We can customize the list of features per user/site/plan or whatever. Totally up to suggestions, but my hypothesis is that spending a lot of time on it will have diminishing returns. I think if we just came up with a static list per plan, we'd be all set.

> I'll want to jump in and customize the svg icons (each plan has a different one). You currently have it just as the logo (totally fine for now).

You can add icons just like the original logo ... or the woo one. I'd personally recommend keeping the Jetpack one so that when the jitm shows up in other parts of wp-admin, the user knows right away that it's for Jetpack. New icons would only show in Jetpack 6.0 or higher too... since we can't send svg's over the wire (which we may be able to do in the future, btw).

**Comment by jeffgolenski** [comment]
@withinboredom 

Awesome man. Just for some clarity:

Are you saying that pre-5.9 folks will just see a basic message like this:

![image](https://user-images.githubusercontent.com/1883296/37037615-aec5386e-2120-11e8-80ef-08211904d53e.png)


and 5.9 and afterwards will see the checklist? If so, can we write a conditional so the subtitle for pre-5.9 is different from 5.9+? So we have better context for folks.

**pre-5.9 can read**: "Don't lose out on the valuable features your plan provides [learn more text link]" > pricing grid on jetpack.com
**5.9+ can read:** "Don't lose out on these valuable features:" then the list below

> We can customize the list of features per user/site/plan or whatever. Totally up to suggestions, but my hypothesis is that spending a lot of time on it will have diminishing returns. I think if we just came up with a static list per plan, we'd be all set.

Yeah, I'm happy to go with that for now. I'll add some features to the list in your PR soon.

>I 'd personally recommend keeping the Jetpack one so that when the jitm shows up in other parts of wp-admin, the user knows right away that it's for Jetpack.

Great idea. we'll keep the jetpack low-gow

**Comment by withinboredom** [comment]
6.0+ will get the list, 5.9 is already almost ready for release, IIRC.

**Comment by withinboredom** [comment]
and yes, we can have different subtitles for different versions (might be worth having a flag to denote "new" features in a plan for this jitm and style them appropriately)

**Comment by jeffgolenski** [comment]
FYI: further chat in the PR: https://github.com/Automattic/jetpack/pull/8991
