### ISSUE TITLE
Jetpack Markdown for BBPress users

### ISSUE THREAD

**Issue by jessefriedman** [Automattic/jetpack#8952]
It's been reported that Jetpack markdown doesn't currently work in BBPress forum posts. 

@mattwiebe has pointed us in an interesting direction that this might be a rather easy fix: ```add_post_type_support( 'markdown', 'BBPRESS_POST_TYPE' )```

BBPress users would definitely benefit from fixing this issue. 

cc/ @chriscoyier

**Comment by mattwiebe** [comment]
Looks more like:

```php
add_post_type_support( bbp_get_topic_post_type(), 'wpcom-markdown' );
add_post_type_support( bbp_get_reply_post_type(), 'wpcom-markdown' );
```

Not sure what the Forum content type does, but then we'd also do

```php
add_post_type_support( bbp_get_forum_post_type(), 'wpcom-markdown' );
```

@kraftbj told me it could go in https://github.com/Automattic/jetpack/blob/master/3rd-party/bbpress.php

**Comment by kraftbj** [comment]
We would need to wrap it in a check for those functions since we haven't built out a smarter way of including 3rd-party compat stuff (eventually https://github.com/Automattic/jetpack/blob/196b803d26fa8b68e86229dfb1c2437ae9d0ff2a/3rd-party/3rd-party.php ), but that file would be the perfect place for it.

**Comment by kraftbj** [comment]
That seems to work @mattwiebe. Something is borking on my testing box, so going to fix that up, confirm, and can put together a patch.
