### ISSUE TITLE
Search: Enable search terms to be highlighted in search results

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#8959]
> When a user inputs a search term, we'd like Elastic Search or Jetpack search to be able to highlight the terms they were searching for in the results. There's no clear way to do that from what i can tell. 

973091-zen

**Comment by gibrown** [comment]
Any details on how they would like the results displayed? Do they want configuration options for it?

We've done this in some places and one challenge will be how to generically insert it into the theme.

**Comment by danjjohnson** [comment]
They didn't specify, but I've asked for further details.

**Comment by skumar1st** [comment]
This is very basic requirement.
Search term should highlight on search result page, when user search any sentence.
Must add this feature on priority.
Thanks..

**Comment by snowmads** [comment]
A Jetpack customer today recommended the following search display option, if it's possible: 

> "Our site's home page has the Search feature on it.  When entering a search term, it brings up our blog topics that contain the search term (showing just several lines from each blog page without showing the search term requested).   It would be great, if upon selecting one of the hits, that page would open and have the search term highlighted.  An optional characteristic would have the new page open to the location with the first instance of the search word. Thanks, and keep up the great work."

 in 4546891-chat

**Comment by jbmanos** [comment]
I am a customer and I am interested in this feature.  I have used relevanssi pro in WP installs and it has this feature where the excerpt shown on the search results list has the search term highlighted in context.  It permits the user to have an even better search experience and get the information they seek much faster.

Relevanssi has an example of the feature right on their front page.  (https://www.relevanssi.com)

**Comment by gibrown** [comment]
Since this popped up as "stale", just wanted to update here that we have a prototype we are working on that does this. Still needs a lot of work to work in all themes, but here is what it is looking like in twentysixteen:

<img width="857" alt="Screen Shot 2019-10-03 at 10 07 54 AM" src="https://user-images.githubusercontent.com/820871/66144283-ca7cb800-e5c5-11e9-8e9c-c0659336b060.png">

It is also coupled with instant search and filtering which is a fairly major feature so I don't want to put a timeline on exactly when we will be fully releasing it and recommending it for production sites.

**Comment by gibrown** [comment]
Marking this as done since the instant search prototype does have highlighting (even though it is not yet fully released).
