### ISSUE TITLE
Theme Appetite- Jetpack vs WPML plugin

### ISSUE THREAD

**Issue by singer1281** [Automattic/jetpack#9068]
Hi all,
on my website I'm using Appetite theme (with jetpack as required) and the WPML plugin to have it both in Italian and in English (second language).
It happens that, when I switch to English, the home page sometimes is not displaying the featured content slideshow. I've got two different featured pages (the Italian one and the English one) for the slideshow and the tag is set only in the Italian one (otherwise, the English featured page will be displayed also in th Italian Home Page).

[HOME_en.txt](https://github.com/Automattic/jetpack/files/1821467/HOME_en.txt)

As you can see from the code in the attachmente HOME_en-txt, the hero class is not loading anything about the featured content, dispite what is done in the Italian home page:
[HOME_it.txt](https://github.com/Automattic/jetpack/files/1821468/HOME_it.txt)

So, do you have any suggestion to me? I don't know if it is something related to cache, as sometimes it is working and sometimes not...but I would like it to work anytime.

The site is: www.cyclingvenicelagoon.com

Thanks for your support!

Daniela

**Comment by jeherve** [comment]
Since the problem appears to be related to a conflict between your theme and the WPML plugin, and since your theme is a Premium theme, I would recommend that you contact the theme author for help here:
https://themesharbor.com/contacts/

They may have already had reports about the problem from other WPML users, and may be able to help.
