### ISSUE TITLE
Issues with signing out from an Atomic front end in mobile (and Desktop) Safari

### ISSUE THREAD

**Issue by frontdevde** [Automattic/jetpack#9082]
Currently, it is not possible to sign out on mobile Safari from the front end of an Atomic site. For a detailed description of the issue and investigation so far see p4k3M4-2qr-p2 (internal reference).

#### Steps to reproduce the issue

- Sign in on an Atomic site
- Navigate to the front end
- Try to sign out

#### What I expected

- Clicking the sign out button should log out the user

#### What happened instead

- Nothing happens when clicking the sign out button

**Comment by jeherve** [comment]
Could you give this another try with the current Bleeding edge version of the Jetpack plugin, thanks to the [Beta plugin](https://jetpack.com/beta/)?

I wonder if the issue may have been fixed by the different fixes we've made to the masterbar recently, like #9012

Thank you!

Possibly related: #7529
