### ISSUE TITLE
Monitor: toggles can be confusing

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#9086]
It's not obvious what on/off toggles for the Monitor feature exactly toggle.

This came up when working on adding these toggles to Jetpack (#9084).

### At Calypso:
![image](https://user-images.githubusercontent.com/87168/37652947-dd8d6d58-2c45-11e8-9541-e4fe0992eeeb.png)

There's also additional toggle behind feature flag and not in prod yet:
![image](https://user-images.githubusercontent.com/87168/37652737-32f60ac6-2c45-11e8-978e-ad74cf8061e1.png)

### At Jetpack dashboard:
![image](https://user-images.githubusercontent.com/87168/37652861-9804ebee-2c45-11e8-8917-c466f0a6eda6.png)

## Notes:

- When Monitor is off, Dashboard text mentions "notifications", not emails:
    > _"Activate Monitor to receive notifications if your site goes down."_

    To me "notifications" kinda mean emails but others might expect to see "notifications" on their phone apps while they check their emails super rarely.

- "Activate monitor" is a link, not a toggle. Compare to Protect:
    ![image](https://user-images.githubusercontent.com/87168/37653589-1baad4c0-2c48-11e8-8aaa-b69de34b8006.png)

- If I toggle monitor on from the Dashboard, both toggles at Calypso turn on. 👌 

- If I toggle "email notifications" _off_, does that mean that my monitor is on but nobody gets notified? What's the use case for this toggle? 🤔 It would be more simple to just have this on/off and send notifications via all channels possible (it's your site down, after all). 

- If I toggle "email notifications" _off_ (and leave the monitor _on_), at Dashboard I still see the text about emails: 

    > _"If we think your site is down, you will receive an email."_

    ![image](https://user-images.githubusercontent.com/87168/37653085-503a8336-2c46-11e8-9591-da68f00eae44.png)

- The toggle that's not in production yet basically toggles "notifications via notifications"... 🤔 

- The text during initial Jetpack connect speaks about "notifications" (not emails):
    ![image](https://user-images.githubusercontent.com/87168/37655523-47b67776-2c4e-11e8-8e93-b6593d1b7cae.png)

- @enejb commented elsewhere: _"that option seems to be per user and we seem to be treating it like it is related to the site"_

**Comment by rickybanister** [comment]
There's a lot of feedback here, thanks for all of it!

From my perspective here are the actionable bits:

- [ ] In settings: change the settings header text from `Jetpack Monitor` to `Uptime monitoring`
- [ ] In the Jetpack dashboard: change the 'activate monitor' link to mirror the protect card's toggle exactly
- [ ] I don't really see value in providing a setting to turn off the WordPress.com notification. If their site goes down we should tell them about it. Adding a setting for email makes sense because the email is 'additional'. We also don't give them a choice whether to hide monitor events from their activity log, so we shouldn't really need to do so for notifications. If they don't want to be notified they should turn the feature off entirely, as you say.
- [ ] We should clean up the copy to make it say 'notifications and emails' if we are speaking generally about the feature, and mention notifications and emails more explicitly when talking about settings.
