### ISSUE TITLE
AtD: ensure that it gets triggered and can check text in Gutenberg blocks

### ISSUE THREAD

**Issue by jeffpaul** [Automattic/jetpack#9128]
#### Steps to reproduce the issue
[Source issue is in the Gutenberg repo](https://github.com/WordPress/gutenberg/issues/3284).

#### What I expected
AtD should not throw errors when utilizing Gutenberg.

#### What happened instead
Error `edit.getParam().join is not a function` on opening a post with Gutenberg.

**Comment by jeffpaul** [comment]
@nosolosw are you still seeing this issue with AtD when using Gutenberg?

**Comment by nosolosw** [comment]
I enabled the "Check your spelling, style, and grammar" section (and all the items within) and I don't see any error now.  Let me know if I should anything else.

**Comment by jeherve** [comment]
Thanks for giving it another try. I'll leave this issue open for now, but rephrase the title, as we still have some work to do to make sure AtD is fully compatible with Gutenberg.

**Comment by nosolosw** [comment]
Ha! I've found how to reproduce it: it the post/page has a classic block I get the `edit.getParam() is not a function` error.

**Comment by johngodley** [comment]
Adding that I also experienced this when using Gutenberg to open an old post that gets converted to a classic block:

`atdCore.setIgnoreStrings( editor.getParam( 'atd_ignore_strings', [] ).join(',') );`

From https://github.com/Automattic/jetpack/blob/f8078c2cd12ac508334da2fb08e37a92cf283c14/modules/after-the-deadline/tinymce/editor_plugin.js#L94

The problem seems to be that the `editor.getParam( 'atd_ignore_strings', [] )` is returning the string `[""]` (i.e an array encoded as a string). The `.join` is then incorrectly applied.

If I add something to the Jetpack 'ignored phrases' setting then the string is `["test"]`

Disabling AtD stops the problem.

**Comment by bazza** [comment]
@mdawaffe  - can you take a look at this one?  Looks like you worked on it previously :)
