### ISSUE TITLE
Google Analytics Tracking Code Placed Incorrectly

### ISSUE THREAD

**Issue by joendotcom** [Automattic/jetpack#9129]
#### Summary

User reports that this issue causes trouble with Google Analytics tracking. 

Referenced in 1036031-zen.

#### Steps to reproduce the issue

0. Starting from a test site with Google Analytics tracking: https://joentest1.mystagingwebsite.com/
1. View page source
2. Search for `<!-- Jetpack Google Analytics -->`

#### What I expected

Google Analytics tracking code is shown as outlined in [this article](https://support.google.com/analytics/answer/1008080?hl=en&visit_id=1-636573456400247366-2318498962&rd=1):

> right after the `<head>` tag on each page of your site. 

#### What happened instead

Google Analytics code is not inside `<head>` and instead appears on line 328 (on the test site).

<img width="496" alt="screen shot 2018-03-22 at 21 39 07" src="https://user-images.githubusercontent.com/8905369/37797368-e58a8628-2e19-11e8-9c24-96b182c5b25e.png">

**Comment by georgestephanis** [comment]
The code on or about line 328 (bottom of the `<body>` tag) is:

```
<!-- Jetpack Google Analytics -->
			<script type='text/javascript'>
				var _gaq = _gaq || [];
				_gaq.push(['_setAccount', 'UA-123456789-1']);
_gaq.push(['_trackPageview']);
				(function() {
					var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
					ga.src = ('https:' === document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
					var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
				})();
			</script>
```

which doesn't line up with the output of the `Jetpack_Google_Analytics_Universal::wp_head()` method --

https://github.com/Automattic/jetpack/blob/d34545c34895a993a810561770a5faa17b588166/modules/google-analytics/classes/wp-google-analytics-universal.php#L40-L84

but does match the `Jetpack_Google_Analytics_Legacy::insert_code()` method:

https://github.com/Automattic/jetpack/blob/74e6013c339abb8db4a054fca6a4d8fc54fe4e4d/modules/google-analytics/classes/wp-google-analytics-legacy.php#L56-L118

which is run in the footer --

https://github.com/Automattic/jetpack/blob/74e6013c339abb8db4a054fca6a4d8fc54fe4e4d/modules/google-analytics/classes/wp-google-analytics-legacy.php#L22

The legacy is run instead of the universal code, as  evaluates to false:

https://github.com/Automattic/jetpack/blob/2bcd0a02b635b8dd1a0784659aa2a07dce4235b9/modules/google-analytics/wp-google-analytics.php#L53-L57
https://github.com/Automattic/jetpack/blob/8a61841a7069d459443384a778e7389688ad29ed/modules/google-analytics/classes/wp-google-analytics-options.php#L45-L48

which came from https://github.com/Automattic/jetpack/pull/8182 by @allendav to add support for the newer universal analytics js.

The linked article in the original issue is for gtag.js tracking, which I think is yet another form of google analytics that we may not be explicitly supporting?  I'm unsure, but would defer to @allendav on that.

**Comment by rtrevellyan** [comment]
As far as I know, gtag.js is simply the 'latest and greatest' version of the tracking code.

**Comment by georgestephanis** [comment]
Looks like gtag is inclusive of a number of other google stuff as well, such as Google Tag Manager -- 

https://www.lunametrics.com/blog/2017/12/12/what-is-gtag-google-analytics/

As such, it may be a "do not ever ever ever run on WordPress.com sites" tag as it can allow the inclusion of arbitrary Javascript and lead to XSS attacks on user accounts from malicious wp.com subdomains running nasty custom js that we ordinarily would block.

**Comment by georgestephanis** [comment]
@allendav Would it be bad to have non-eCommerce ways to switch a site to using the universal tag?

https://github.com/Automattic/wp-calypso/blob/48e65376175054f54659ce50b2316b3e60b37a37/client/my-sites/site-settings/form-analytics-stores.jsx#L97-L105

I suppose we could also just do something like

```php
add_filter( 'option_jetpack_wga', 'force_jetpack_ga_to_universal' );
function force_jetpack_ga_to_universal( $value ) {
    if ( is_array( $value ) ) {
        $value['enh_ec_tracking'] = true;
    }
    return $value;
} );
```

**Comment by rtrevellyan** [comment]
I see @jeherve marked this low priority. Of course, I don't know how you determine bug priority, but I just want to reiterate that this issue makes Jetpack's GA module useless to me.

**Comment by allendav** [comment]
@georgestephanis wrote

> Would it be bad to have non-eCommerce ways to switch a site to using the universal tag?

It would not be bad. Besides a filter like yours, we also have to allow analytics.js to be added when WooCommerce isn't present. I am also trying to remember why I set the priority for wp_head for Jetpack_Google_Analytics_Universal so high (as @rtrevellyan noted it should be near the top, not near the bottom of the head ). Will have a patch shortly to allow for all this. Sorry for the delay.

cc @rtrevellyan

**Comment by allendav** [comment]
@georgestephanis @rtrevellyan @joendotcom - feedback welcome - https://github.com/Automattic/jetpack/pull/9333

**Comment by allendav** [comment]
Hi @rtrevellyan - the jetpack module used to be ga.js only, and then in Jetpack 5.6 I was asked to port the analytics.js code for eCommerce from another plugin to Jetpack. At the time, I wasn't even aware of gtag.js's existence.

Perhaps a future version of this module will add gtag.js support and/or support enabling analytics.js without the filter - please feel free to create such issues if you'd like.

**Comment by simison** [comment]
Still an issue.

![image](https://user-images.githubusercontent.com/87168/93307420-9ec00580-f809-11ea-86be-c3caa7facf34.png)
