### ISSUE TITLE
Publicize: Sharing: Twitter: WordPress.com doesn't need to know who I follow

### ISSUE THREAD

**Issue by allendav** [Automattic/jetpack#9188]
When connecting publicize to Twitter, four grants are requested for WordPress.com

- Read Tweets from your timeline.
- See who you follow, and follow new people.
- Update your profile.
- Post Tweets for you.

Of these, publicize only needs the last one. There is especially no reason for WordPress.com to need to see who I follow, follow people on my behalf, or update my profile.

<img width="697" alt="screen shot 2018-03-25 at 8 10 05 am" src="https://user-images.githubusercontent.com/1595739/38098032-c7c8e122-332b-11e8-869a-c8ae0149e74b.png">

**Comment by codebykat** [comment]
FYI the "who you follow" is used to get a total count, which is used on the stats page and in the Follow widget.

Anyhow, from Twitter's docs, it doesn't look like there's a way to limit the scope: https://developer.twitter.com/en/docs/basics/authentication/overview/application-permission-model

We need "read and write access" in order to post tweets to the user's timeline, and that appears to come with access to update the profile and follow people.

> This permission level permits read and write access to Twitter resources, including the ability to read a user’s Tweets, home timeline, and profile information; and to post Tweets, follow users, or update elements of a user’s profile information. It does not allow access to read or send Direct Messages.

That being said, we can (and arguably should) add documentation about what information we actually use and store.

**Comment by codebykat** [comment]
Note to self (or whoever): there may be a way to include links to this messaging in Twitter's oAuth dialog. Elsewhere on the page they say

> To use this permission, the application settings must be configured to point to valid privacy policy and terms of service URLs via apps.twitter.com so that users understand the terms under which their email address may be used and stored.

**Comment by jeherve** [comment]
Closing since the feature is no longer available.
