### ISSUE TITLE
Admin Page: Dashboard item actions wraps if titles are long

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#9219]
When testing with another language, like Spanish, the action notice gets moved to a new line given that the Dashboard item title is a little bit longer than expected.

#### Steps to reproduce the issue

* On a site with Jetpack active.
* Switch to a language like Spanish.
* Expect the dashboard items to look like this::
<img src="https://user-images.githubusercontent.com/746152/38256950-bf37effe-3735-11e8-854b-e3113d8d5497.png" width=300 />

#### What I expected

* Nothing in particular, but something like what we show in English.

<img src="https://user-images.githubusercontent.com/746152/38257056-f2ad606c-3735-11e8-9d5f-6f22a4574b49.png" width=300 />

#### What happened instead

* The action notice gets wrapped to a new line

**Comment by oskosk** [comment]
cc @keoshi

**Comment by keoshi** [comment]
Thanks for the ping @oskosk — not sure if there's anything we can do here. This depends on the space available on a given screen, and the notice is wrapping correctly given the amount of space it has on the right, because it's being pushed by the text. I imagine this is visible even on a larger screen with German, for example.

I do see that the notice isn't translated though, which might make things worse once it is (breaking line earlier in larger devices/screens).

**Comment by oskosk** [comment]
oh, it is translated, this was just a screenshot from my local environment misisng some files.

**Comment by keoshi** [comment]
@oskosk going through some of the `Needs Design Review` issues/PRs and this stuck out to me again. Any ideas on how to deal with these? I think this is expected behavior given the amount of space available on the screen, but would also be interesting in solving it in a smart way.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
