### ISSUE TITLE
Lazy Images: Load Images for Printing

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/jetpack#9232]
Lazy Images currently prevents printing images on posts and pages. 

To replicate:
1. Activate Lazy Images.
2. View a post or page with images.
3. Print.
4. Notice (in Chrome) that the preview is missing images. 

Deactivate Lazy Images and print works as expected. 

Reported here: https://wordpress.org/support/topic/lazy-load-and-printing/

**Comment by julia-smith** [comment]
Hi there! My team just ran into this issue – are there any updates or documented workarounds? Thanks!

**Comment by jeherve** [comment]
@julia-smith I'm afraid we don't have a workaround yet, short of deactivating the Lazy Images feature on your site. We'll update this issue when we make progress on this.

**Comment by tmmbecker** [comment]
Still an issue.

**Comment by tmmbecker** [comment]
Still a thing, Stalebot!

**Comment by anomiex** [comment]
This turns out to be a tricky thing to fix. We can trigger loading of the lazy images on print, but we can't delay the print itself until the images actually load. So the best we can do is notify the user that images are still loading and advise them to cancel it themselves and re-print.

Even the browser-native `loading="lazy"` in Chrome [doesn't currently handle printing correctly](https://bugs.chromium.org/p/chromium/issues/detail?id=875403), and they have many more options.
