### ISSUE TITLE
Using Corporate theme on AT site causes issue with EU Cookie Law widget

### ISSUE THREAD

**Issue by xpurichan** [Automattic/jetpack#9244]
#### Steps to reproduce the issue
1. SSP to fressingfieldbaptist.church
2. Enable the EU Cookie Law (Jetpack) widget in the theme customizer and save changes
3. Visit fressingfieldbaptist.church
4. Accept cookies using the banner at the top of the page, the banner then goes away
5. Despite cookies being accepted the website is inoperable (example: can't use the primary menu to visit different site pages)
Without this widget the website operates fine.

#### What I expected
I expected to see the cookie banner at the top of the page, approve the use of cookies, and then to be able to use the site as normal (such as use menu items to access different pages of the site).

#### What happened instead
The website is not operable after accepting cookies.
(example: can't use the primary menu to visit different site pages)

#### Additional information
I was able to replicate this exact problem on my personal AT site with the Corporate theme applied.

Ticket and user information can be found in 1065580-zen

**Comment by jeherve** [comment]
The look of the widget is controlled via CSS, and we force the widget to appear above everything else on the page so it is never under another element. That's an issue on your site because of how the footer widget area is built. Luckily you can solve this with a bit of CSS, like so:

```css
.widget_eu_cookie_law_widget {
    top: unset !important;
}
```

I fixed it for this user and replied.
