### ISSUE TITLE
In the subscription email the caption of an image is not shown correctly

### ISSUE THREAD

**Issue by GamesToEnjoy** [Automattic/jetpack#9284]
#### Steps to reproduce the issue
Check an subscription email which contains an image with a caption.

#### What I expected
In WordPress the caption of an image is shown below the image with thinner font.

#### What happened instead
The caption appears at the center of the page and with the same font as the rest of the text.

**Here is a screenshot of the email with the wrong caption marked in red:**
![wrong](https://user-images.githubusercontent.com/38309820/38666027-9f6d47ce-3e46-11e8-80db-31d8e98820f8.PNG)

**Here is a screenshot of the post in the WordPress site:**
![correct](https://user-images.githubusercontent.com/38309820/38666150-f588dc86-3e46-11e8-8c94-03f95edcddd4.PNG)

**Comment by jeherve** [comment]
Could you point me to the post itself, so I can take a closer look at the markup used there?

Thank you!

**Comment by GamesToEnjoy** [comment]
Here is the post: [http://kodibeginner.com/install-reddit-viewer-kodi/](url)

Thank you!

**Comment by jeherve** [comment]
Thank you! This is odd, it seems to work well in my tests:

<img width="682" alt="screenshot 2018-04-12 at 11 27 25" src="https://user-images.githubusercontent.com/426388/38668596-8817b66a-3e44-11e8-9617-8f2f752ea4cf.png">

Could you let me know which email client you use, and if you run into the same issue in another client?

**Comment by GamesToEnjoy** [comment]
My email client is Hotmail and it happens there, I didn't test it with a different client.

**Comment by jeherve** [comment]
> My email client is Hotmail and it happens there, I didn't test it with a different client.

Thank you. I was able to reproduce the issue in Hotmail (Outlook.com).

<img width="732" alt="screenshot 2018-04-12 at 21 20 00" src="https://user-images.githubusercontent.com/426388/38699154-8bb88120-3e97-11e8-872e-595806dfb4a6.png">

Looking at the email's source, it appears that Outlook strips the `figcaption` HTML element that is used to display captions:
https://www.w3schools.com/tags/tag_figcaption.asp

Compare Outlook.com:

<img width="452" alt="screenshot 2018-04-12 at 21 22 56" src="https://user-images.githubusercontent.com/426388/38699288-e6cca848-3e97-11e8-9e81-4dc4907735fa.png">

With Gmail:

<img width="423" alt="screenshot 2018-04-12 at 21 23 42" src="https://user-images.githubusercontent.com/426388/38699295-ecb48a1e-3e97-11e8-84e5-49380e372f14.png">

At this point, I would recommend that you report this bug to Outlook.com, as it will affect the styling of all emails including captions.

> the email you got is a bit different as you didn't get the "Read more of this post" link as I did but the rest of the post.

Yes, that is because I did not include any more content in my first test post.
