### ISSUE TITLE
Add "i" icon with explanation next to "Manage security on WordPress.com"

### ISSUE THREAD

**Issue by nozomimimi** [Automattic/jetpack#9300]
As part of Jetpack dashboard improvement initiative (p6TEKc-1WA-p2), and to remove confusion around managing security on WordPress.com (instead of your own site) we decided to add "i" icon next to "Manage security on WordPress.com" to explain to users why they should do it/why it's like that.

I'd like to get help with a copy from someone more versed in Jetpack (because I don't even know why myself... :) )

[![https://gyazo.com/9e63bc33a57a4ccae100d6d8fb67d138](https://i.gyazo.com/9e63bc33a57a4ccae100d6d8fb67d138.png)](https://gyazo.com/9e63bc33a57a4ccae100d6d8fb67d138)

[![https://gyazo.com/ac498ddf9063e73fcea73611b6bcab20](https://i.gyazo.com/ac498ddf9063e73fcea73611b6bcab20.png)](https://gyazo.com/ac498ddf9063e73fcea73611b6bcab20)

**Comment by benhuberman** [comment]
Taking a step back here for a second, this is _very_ disorienting. We're giving the user a fork in the road to do nominally the same thing (only with more options in one place than in the other place). I don't know that any single bit of copy could resolve this tension effectively (though it doesn't hurt to try), so I wonder if there's a way to focus on what we'd like the user to do / achieve here. If the goal is to steer them to WP.com, does it make sense to have the cogwheel? If we want to prioritize the settings on their site, why add a link to WP.com in the first place (and are the two extra security features enough of an incentive for clicking away)? Actually, do we need either? Can't the WP.com link be a CTA in its own block / embedded in one of the existing blocks on that screen? The intent of this change is to avoid confusion, which is really welcome, but the confusion seems to be baked in. 

In case the current direction is one you're all set on pursuing for now and still need copy for this area, I'd recommend something like the following:
- I'd change the "main" copy to something like:
> Access more security options on WordPress.com.

The idea being that you want the user to already know _why_ they should even consider going elsewhere (i.e. "more").

- In the tooltip copy, I'd try to sell the benefits with more specificity, e.g.:
> Give your site an extra layer of protection with downtime monitoring and spam filtering.

Do you think that might work, @keoshi ? Happy to think of other directions, or, in case the above design changes into something less potentially confusing, happy to work on messaging for whatever alternative you end up with.

**Comment by keoshi** [comment]
I 100% agree with you, @benhuberman — this one is not easy to solve, and we've created this confusion. The tooltip in particular could quickly become outdated when we release any more features on dotcom, but have to wait for a JP release to update it.

What do you mean by this?

> Can't the WP.com link be a CTA in its own block / embedded in one of the existing blocks on that screen?

Think I like the idea, but not sure if I understand it fully.

cc'ing @MichaelArestad since you've worked on settings and might have a better solution for this experience fork.

**Comment by benhuberman** [comment]
> What do you mean by this?

@keoshi It was just an inelegant way of proposing to move the link to the WP.com settings to another element on that page -- like the CTA of another feature block, or alternatively, a new element that introduces the "advanced" features on WP.com with a link there. Basically: instead of framing it as a choice, make it into one of the available options on this screen. That said, I haven't looked at that screen as a whole with too much attention, so it might not be a great solution after all. (Though still less confusing, to me anyway, than the current state.)

**Comment by scottsweb** [comment]
Due to the age of this issue and given that is what not resolved, I would like to close it. 

I think there is a bigger issue here beyond just the copy we use. We are providing links to settings on the dashboard screen. A clear split between settings and the dashboard seems simpler. 

We are also not repeating this pattern for the performance section of the 'at a glance' screen.
