### ISSUE TITLE
Default Privacy Policy in EU Cookie Widget

### ISSUE THREAD

**Issue by jaswrks** [Automattic/jetpack#9512]
A fork of https://github.com/Automattic/jetpack/pull/9373#issuecomment-387562454

In the EU cookie widget, the privacy policy URL could auto populate with the URL corresponding to the core setting for the privacy policy page ID (`wp_page_for_privacy_policy`) if present.

**Comment by kevko** [comment]
Nice. 

We'd also want to make it easy & obvious for people to add Jetpack's cookie details using core's privacy policy builder. (Maybe even require it as a future ennhancement). Otherwise we'd be encouraging folks to omit key details, which could be quite bad for Jetpack and its users. 

Sorry if that was obvious, but just want to make sure we're clear it's a two-step process.

**Comment by kevko** [comment]
Perhaps we should create another issue for drafting that language and making sure it's set up in the right function is added in Jetpack to be included in core's PP builder?

**Comment by rclations** [comment]
We'll push out a JITM directing users to the Privacy Policy Helper tool, so this should be resolved when #9564 merges.
