### ISSUE TITLE
GDPR Checkbox in comments form

### ISSUE THREAD

**Issue by jadelaop** [Automattic/jetpack#9574]
Hello, could you add the GDPR checkbox in comments form?

Is necessary by GDPR to check every time when a comment is posted...

Thank you!!

**Comment by htdat** [comment]
On https://wordpress.org/news/2018/05/wordpress-4-9-6-privacy-and-maintenance-release/, there is a new option under each comment box (not Jetpack): 

> Logged-out commenters will be given a choice on whether their name, email address, and website are saved in a cookie on their browser.

It looks [this](https://i0.wp.com/wordpress.org/news/files/2018/05/comments-border.png?w=1264&ssl=1).

---- 

Another request: 1172614-zen

**Comment by jeherve** [comment]
After discussing about this internally, we'll close this GitHub issue as `wontfix`.

There are a few valid ways to be transparent and compliant about cookies that a site uses to enable its features, like comment form auto complete. The way we chose is to include information about the cookies we use (including the comment cookies) in our cookie policy which you can read [here](https://automattic.com/cookies/). If you want to alert users to the use of these kinds of cookies on your site, you can do that using the cookie and consent tools that we’ve recently added to Jetpack, [here](https://jetpack.com/support/extra-sidebar-widgets/eu-cookie-law-widget/).

**Comment by jadelaop** [comment]
I disagree with this solution...

I believe that GDPR needs a checkbox at every form submission with personal data, including comments.

https://wordpress.org/support/topic/comments-does-not-display-gdpr-compliant-comment-consent-checkbox/

**Comment by jeherve** [comment]
@jadelaop If you or your own legal counsel disagree with that decision, I would recommend that you deactivate Jetpack's Comment form option under Jetpack > Settings > Discussion in your dashboard. Your site will then display the default comment form again, that includes a checkbox.

**Comment by jadelaop** [comment]
I made that. Thank you.

**Comment by johnstonesnow** [comment]
It is over a year and half since this was closed, and I don't like the way it was closed either. 
I am a legal expert on DPA and GDPR (privacy laws generally). It is beyond dispute now that GDPR specifically requires all sites collecting data (not just cookies) to 'obtain explicit consent' from users, consent to the storage and processing of the submitted data, PRIOR to clicking submit. The default wordpress comments shows that they acknowledge this, as do every other modern GDPR-compliant plugin for any type of information submission, be it an email list subsription, a comment form, or any other submission form. 

Will you PLEASE consider adding this simple option so that Jetpack comments stay with the game. I desperately want to use Jetpack comments because of the added functionality of social logins. I have spent two days trying to find a solution and I can't (without learning to code and writing something bespoke). 

GDPR Consent is not to be trifled with, and no self-respecting website owner would wish to be in breach of it. Please make it so that we can use Jetpack comments without breaking the law in the EU.

**Comment by jeherve** [comment]
@johnstonesnow I see you've opened a new issue about this #14118. I'll reply there.

**Comment by johnstonesnow** [comment]
Thanks
