### ISSUE TITLE
Ads: Feature Request - add Leaderboard option to Ad display widget

### ISSUE THREAD

**Issue by glasgowshipyard** [Automattic/jetpack#9582]
Friends,

This is a request to be able to add the _Leaderboard_ ad similar to the one that can be displayed at the top of the site, to the widget, or a question as to the reason or justification why it cannot be selected.

Cheers!

**Comment by danmaze** [comment]
I've seen another instance of this feature/enhancement request in 4552415-zen.

> I have a specific location I want the top ad for word ads to load. I want it to load directly below the Navigation menu, instead of the top left corner of the page, as that looks trashy. 

> The location I want it just seems to me to be the most optimal placement for design and layout consistency, and quality.

> Is there a way using either div ID tags, shortcode, or even php calls that I can specify where the top leaderboard ad should load?

They eventually figured out a hacky solution to the problem which has the downside of being incompatible with future Jetpack updates (I've already informed them about that):

> For future reference, what I did was disabled Top Ads in the Jetpack Settings, then modified the class-wordads-sidebar-widget.php file to add ‘leaderboard’ under the $allowed_tags private static array. So I changed it from:

> private static $allowed_tags = array ('mrec', 'widesckycraper');

> to;

> private static $allowed_tags = array( 'mrec', 'wideskyscraper', 'leaderboard' );

> This made it so the widget allows me to insert a leaderboard ad where I actually want it to be placed. Why the widget didn’t allow this out of the box is beyond me, but it worked perfectly.

The solution seems pretty straightforward: Add the "leaderboard" option to the `$allowed_tags`, so that users can add leaderboard ads wherever they want on their page using widgets.

**Comment by cphilleo** [comment]
This has been fixed on #22016
