### ISSUE TITLE
WhatsApp sharing button has invalid space

### ISSUE THREAD

**Issue by gillespieza** [Automattic/jetpack#9591]
The WhatsApp sharing button has an invalid space in the href tag which causes the page to fail HTML validation. The `href` tag includes an un-escaped space between the post title and the post url.

Example output:
`
<a rel="nofollow" data-shared="" class="share-jetpack-whatsapp sd-button" href="https://api.whatsapp.com/send?text=Freedom%20Isn%27t%20Free http%3A%2F%2Fwww.mydomain.com%2Ffilm%2Ffreedom-isnt-free%2F" target="_blank" title="Click to share on WhatsApp">
`

**Comment by Dec0y-jb** [comment]
I've initiated a Pull Request for this (#9615)

**Comment by Dec0y-jb** [comment]
Hi @dereksmart and @oskosk - Did something go wrong with my submission? Thanks,

Joe

**Comment by oskosk** [comment]
@Dec0y-jb nothing wrong. It's being shipped with Jetpack 6.2 on June 5th. If you were worrying about the log above ^ related to a revert PR. It's just that, this revert PR had a bad commit message from a weird rebase or so and GitHub crosslinked here, but it's not reverted.

I'm closing this one as it's fixed by #9615. Thanks!
