### ISSUE TITLE
Add query strings to Photon URL using ?q= not working. 

### ISSUE THREAD

**Issue by iamdharmesh** [Automattic/jetpack#9685]
Hello There, 

I have enabled Add query strings to Photon URL using `jetpack_photon_add_query_string_to_domain` it working at jetpack end but I am not getting proper image from photon. 

for example: 
**My Image URL is:**
https://knawatp7-h3cc5pdv.netdna-ssl.com/EY134-2.jpg?w=1000&h=1000&v3

**This is what Jetpack convert it.**
http://i0.wp.com/knawatp7-h3cc5pdv.netdna-ssl.com/EY134-2.jpg?q=w%3D1000%26h%3D1000%26v3&resize=300%2C300&ssl=1

It looks like Jetpack is doing its job but Photon server is not process image properly.

Can you please check. is that something which is I am doing wrong.

Thanks,
Dharmesh

**Comment by zinigor** [comment]
Hello! Thanks for reporting the problem!

It looks like you're trying to use Photon in a way that it's not really meant to be used. You can see that it tries to retrieve an image from your server, but it doesn't use the query string in a way that you expect it to. Instead it encodes it and passes it as a parameter with the name `q=`. So instead of an image, your server returns [this](http://knawatp7-h3cc5pdv.netdna-ssl.com/EY134-2.jpg?q=w%3D1000%26h%3D1000%26v3).

If you can use the query string that's passed in the `q` parameter instead of `w` and `h`, Photon should work properly.

Let us know if we can help with anything else.

**Comment by iamdharmesh** [comment]
Hello @zinigor , 

Thanks for you response. 

URL I have given is correct and its really meant to use like this. I have debugged issue deep and found that issue it at photon. It ignores query strings. So, for example for image url like ​https://example.com/image.jpg?param1=1&param2, it serve image from ​https://example.com/image.jpg and ignore query string. 

I have seen comment in Jetpack that "Photon doesn't support query strings so we ignore them. This setting is Photon Server dependent."

https://github.com/Automattic/jetpack/blob/0899aa4384a78f576d2997b0bcbadb041d091965/functions.photon.php#L161-L172

So, I am keeping issue closed because this issue is not related to jetpack.

Thanks.
