### ISSUE TITLE
Performance Settings: Verbiage adjustments

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#9709]
**Currently:**
<img width="786" alt="screen shot 2018-06-07 at 3 54 46 pm" src="https://user-images.githubusercontent.com/214813/41124351-b7f663a2-6a6f-11e8-87d4-05caa1a4ada5.png">

**Proposed:**
<img width="754" alt="screen shot 2018-06-07 at 4 20 05 pm" src="https://user-images.githubusercontent.com/214813/41124358-bb4a6486-6a6f-11e8-8a81-e3e734fc23b9.png">

**Title change:** "speed up your site" to "Performance & speed"
**Toggle description change 01:** "Serve images from our servers" to "Serve images from our global CDN"
**Toggle description change 02:** "Lazy load images" to "Enable Lazy load images"

> Jetpack's free global Content Delivery Network (CDN) will automatically optimize your images for every size device and deliver them from the server location nearest to your visitors location. This results in images loading super fast the moment someone visits your site. As a bonus, when images are uploaded to our CDN, they won't subtract from your hosting plan space!

> Improve your site's speed by only loading images visible on the screen. New images will load just before they scroll into view. This allows viewers to see images load immediately, rather than having to wait for them all load before they show on screen.

@benhuberman any recommendations for tightening these two descriptions up so they're a little more concise?

**Comment by benhuberman** [comment]
I commented [here](https://github.com/Automattic/wp-calypso/issues/25329#issuecomment-395486785) re: the destination language/labels.

**Comment by benhuberman** [comment]
Sure thing, @jeffgolenski.

First, a couple of small things: 
- In the title "Speed & performance," shouldn't "performance" be capped as well, since I'm assuming it's in title case? (If we use sentence case for these title elsewhere, no worries!)
- In the lazy load toggle, it seems off that "Lazy" is capped. if you'd like to treat "lazy load" as a formal feature name (which I'm not saying you should, but if you were to), then it should probable be something like "Enable Lazy Loading for images"
- I really think there should be a hyphen when using "lazy-load" as a verb, e.g. "lazy-load your images on the page" vs. when using it as the feature name, e.g. "Lazy loading images."

For the copy, how about...
- CDN (235 chars instead of 369):
> Jetpack's global Content Delivery Network (CDN) optimizes images so your visitors enjoy the fastest experience regardless of device or location. It also helps you save space on your hosting plan, since images are stored on our servers.

- Lazy load (165 chars instead of 252):
> Lazy-loading images improve your site's speed and create a smoother viewing experience. Images will load as visitors scroll down the screen, instead of all at once. 

These are both significantly shorter -- I just wanted to stay as concise as possible to increase the chance people actually read this before hitting the toggle :)
But let me know if you think I pushed it too far.

**Comment by simison** [comment]
>In the title "Speed & performance," shouldn't "performance" be capped as well, since I'm assuming it's in title case? (If we use sentence case for these title elsewhere, no worries!)

Everything else is sentence case. :thumbsup:

**Comment by benhuberman** [comment]
Great, thanks for confirming!
