### ISSUE TITLE
Comment settings: verbiage enhancements

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#9741]
**Current:**
<img width="756" alt="screen shot 2018-06-12 at 4 26 15 pm" src="https://user-images.githubusercontent.com/214813/41315628-110bcc6a-6e5e-11e8-9b6a-612e35e51892.png">

**Proposed:**

![jetpack-enhanced-comments-after](https://user-images.githubusercontent.com/214813/41316667-ee8475d6-6e60-11e8-8b38-28234e711421.png)

> **Enhanced comments:**
> 
> Drive more interaction with your content — let your visitors use their Twitter, Facebook, Google+, or WordPress.com accounts to comment on your posts.

toggle: change to "Enable enhanced comments"

> **Comment options**
>
> Customize the way in which your visitors can interact with your posts even more by enabling Markdown, comment likes, and dynamic popup business cards over their Gravatar images.

Toggles: turn the visible "learn more | privacy information" links into the i icon to match our existing design patterns, please!

**Comment by benhuberman** [comment]
The updated copy looks good to me! What I still wonder about, @jeffgolenski, is whether we need some explanation as to why people need these accounts to comment in the first place. If you don't think it's crucial, no worries. If you think it might be worth explaining in a couple of words, maybe something like this could work:
> Drive more interaction with your content — your visitors can establish their identity using their Twitter, Facebook, Google+, or WordPress.com accounts when they comment on your posts.

Re: "Enhanced comments," if this is something discussed already / elsewhere, I'll stand down, but I'm not sure how compelling the change is here. Saying something is "enhanced" doesn't add a lot of meaning unless it's compared to some other, more basic state of things -- and in this context, would users know what this is an enhancement of? I have doubts. My vote would be to stick with "Comments," but again, if this was part of a broader conversation, this isn't a hill I'd die on, either. :)

 For the comment options, I wonder if there's a whole lot of value added by naming the options in the intro copy, since they're then repeated just below (with a tooltip option for more information). What if we keep the intro more general?
> Comment options
>
> Make your comments section a more inviting and customized space for interaction.

**Comment by scottsweb** [comment]
Some changes were made to the comments card as part of copy sprint 1.0 https://github.com/Automattic/jetpack/pull/12757

Closing as stale
