### ISSUE TITLE
Genericons: Add support for Medium

### ISSUE THREAD

**Issue by andpiazza** [Automattic/jetpack#9881]
Add icons for Medium in Genericons

**Comment by jeherve** [comment]
We've wound down the inclusion of social logos in Genericons, and instead we've moved towards a different method for enqueuing icons. This method is what's used in the new Social Media Icons widget, and in the Social Menus theme tool included in Jetpack.

That new method can use SVG, and already includes a Medium icon:
https://wpcalypso.wordpress.com/devdocs/design/social-logos
https://github.com/Automattic/social-logos/blob/master/svg-min/medium.svg

I would recommend that you switch over to using Social Logos if possible.

**Comment by andpiazza** [comment]
Hello @jeherve: I understand Genericons is deprecated and Social Logos is the preferred font per #106 
**Issue**: Jetpack invokes Genericons for Social Media Icons on sidebar: https://jetpack.com/support/extra-sidebar-widgets/social-media-icons/
**Question**: How can I properly use Social Logos on the widget if Jetpack is invoking Genericons?

**Comment by andpiazza** [comment]
Thanks @jeherve ! New widget works.

1. RSS Feed didn't work for my link: https://octanage.podbean.com/feed.xml
How does the code identify RSS feed to use the proper icon?
2. I understand Social Logos is the new font: https://github.com/Automattic/social-logos
However, I couldn't find documentation on how to personalize the appearance of icons so asking here for pointers:
a. what's the proper CSS class to adjust font size?
b. can we expand the icons used beyond these?
- List: https://en.support.wordpress.com/widgets/social-media-icons-widget/#available-icons
- Visual: https://wpcalypso.wordpress.com/devdocs/design/social-logos
c. how do I use Genericons Neue instead of (the limited set of) Social Logos?

**Comment by jeherve** [comment]
> How does the code identify RSS feed to use the proper icon?

We look for `feed/`.

> a. what's the proper CSS class to adjust font size?

It's different from the past widget since the icons are now svg icons. You can use your browser's developer tools to target the icons and change the way they look. The widget settings also include an option to change the size of the widget.

> b. can we expand the icons used beyond these?

That is not possible right now.

> how do I use Genericons Neue instead of (the limited set of) Social Logos?

That is not an option. You would have to dequeue our logos and enqueue your own instead. At this point, it may be easier to use a custom HTML widget.

**Comment by andpiazza** [comment]
thanks again @jeherve. Very helpful:
1. added the / to feed and it worked. However, besides the need to document these requirements, many RSS feeds in .xml files may not allow for the / to be added. A "feed" lookup might be more comprehensive
2. a, b, c: since Social Logos is a limited set and were implemented via SVG without the possibility of immediate CSS tweaking, I'll open a thread to discuss Social Logos documentation and enhancements on https://github.com/Automattic/social-logos/issues
(NEW) 3. First noticed today: regardless size selection (S, M, L), Social Logos icons are blown out of proportion in my website. Not sure what happened: I didn't make any change, and the initial presentation had the sizes right. Will post and move this conversation to https://github.com/Automattic/social-logos/issues

thanks again for the explanation @jeherve!

**Comment by jeherve** [comment]
> A "feed" lookup might be more comprehensive

We could indeed be less specific, but we would then have to account for other potential uses of the word `feed` in URLs. That is something we can definitely do though! 👍 	I took note of it in #10662

> regardless size selection (S, M, L), Social Logos icons are blown out of proportion in my website.

This points towards issues with CSS on your site. I would recommend that you reach out to our support team via this contact form and we will help you figure this out:
https://jetpack.com/contact-support/?rel=support

No need to post on GitHub about this as the issue is specific to your site.

Thank you!
