### ISSUE TITLE
Social logos font-face declaration is incorrect.

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [Automattic/jetpack#9895]
The font-face declaration here is incorrect. 

https://github.com/Automattic/jetpack/blob/5509709f167140e3997e0001c9ab98da10ca78c0/_inc/social-logos/social-logos.css#L5

Hence, Chrome downloads the eot file.

**Comment by zinigor** [comment]
Hello! Thanks for your input! 
Can you tell us more about why it is incorrect, and what is your way of reproducing the problem? Please update the issue so that it follows the [contributor guidelines](https://github.com/Automattic/jetpack/blob/master/.github/CONTRIBUTING.md#create-bug-reports) so that we can be sure what needs fixing.

Thank you!

**Comment by zinigor** [comment]
Also, can you take a look at this issue and see if it's the same problem? If it is, I'd rather close this issue and continue the discussion there:
#7148

**Comment by vijayaraghavanramanan** [comment]
Yeah get the same message. I'll close it. 

I think it happens because there are two font face declarations. The "bullet proof font-face syntax" requires only one block for @font-face.
