### ISSUE TITLE
CPTs: Disabling CPT causes old slugs to redirect to main page

### ISSUE THREAD

**Issue by TorelTwiddler** [Automattic/jetpack#995]
Somewhat related to #949, when the CPT module is disabled, it still takes control of the old slug. For example, "www.site.com/portfolio/" displays the content of "www.site.com", ignoring any posts or pages using the portfolio slug.

**Comment by jeherve** [comment]
I can't seem to be able to reproduce the issue anymore. Closing.

**Comment by starr109** [comment]
I am having this same issue. I have a page created that has the url www.site.com/portfolio/. When I view the page, it tries to pull up the Jetpack Portfolio archives instead of the page I created. After disabling Jetpack Portfolio, the /portfolio/ slug redirects to the homepage. I am trying to use the /portfolio/ slug for a custom page, but that URL seems to be unusable after enabling and disabling Jetpack Portfolio.

**Comment by jeherve** [comment]
@starr109 	If the problem remains after disabling Jetpack Portfolio, the problem may be caused by something else.

I would recommend that you try this all again, but between each change, try to save your permalink options again under Settings > Permalinks in your dashboard. This will force WordPress to refresh all rules that may impact your site.

**Comment by starr109** [comment]
Thanks Jeremy. Refreshing the permalinks solved the issue.
