### ISSUE TITLE
Jetpack Mobile Theme does not display featured image

### ISSUE THREAD

**Issue by dericleeyy** [Automattic/jetpack#9953]
## Summary
Jetpack mobile theme does not display featured image even if the option is enabled.

## Steps to Reproduce

1. Enable Jetpack Mobile theme and enable *Show featured images*
2. Create a post with a featured image
3. Load the post in Jetpack Mobile theme

### Expected Result
The featured image should appear top of the post

### Actual Result
The featured image is not loaded

**Comment by jeherve** [comment]
Are you able to see the featured image when looking at the site's home page on mobile? The featured image may not appear on single posts, but it should appear on the home page.

To display featured images on the post pages as well, one can install this little plugin:
https://wordpress.org/plugins/jetpack-mobile-theme-featured-images/

**Comment by nerdysandy** [comment]
This was also reported on zen-1893355 

With regards to @jeherve 's comment: In this case, the user was trying to see this on site's home page. I was able to replicate the issue.

**Comment by jeherve** [comment]
@nerdysandy That site uses a static front page, and not the default list of recent posts on their front page. As such, you don't get to see a list of the most recent blog posts with their featured image when you visit their site's front page on mobile; you only see that one static page.

Closing this issue now since the previous report was left unanswered.
