### ISSUE TITLE
Max date count doesn't show exact.

### ISSUE THREAD

**Issue by sleepless-se** [Automattic/jetpack#9961]
#### Steps to reproduce the issue

1.When I open this page  ./wp-admin/admin.php?page=jetpack#/dashboard
2.max date count shows  "%(number)s"

**Comment by abidhahmed** [comment]
Hi,

Thanks for the report! Please let us know the following in order to help you further:

1. Which version of Jetpack are you running?
2. What's the language/locale of your Wordpress Core / Jetpack?
3. Do you see any JavaScript console errors on the page?

Any further information would be highly appreciated and would help us get to this issue faster. Thanks!

**Comment by jeherve** [comment]
I can't seem to reproduce on my end at the moment. I'll close this issue for now, but feel free to comment again with some more details about your setup if you still experience issues!
