### ISSUE TITLE
jQuery not defined error with Markdown enabled

### ISSUE THREAD

**Issue by andreasnrb** [Automattic/jetpack#9989]
#### Steps to reproduce the issue

1. Use plugin Elementor
2. Activate Markdown support in JetPack
3. Edit page with Elementor

#### What I expected
No error messages in console.
#### What happened instead
jQuery not defined.

#### Propsed fix.
Don't assume jQuery is loaded before calling it. See  https://github.com/Automattic/jetpack/blob/ce014ac3535437b9dd930486601650f344252d01/modules/markdown/easy-markdown.php#L453

**Comment by jeherve** [comment]
I ran some tests, and it appears that Elementor itself removes most scripts that usually load on the edit screen, including jQuery, to then reload it later on its own. To remove all those scripts, they do the following:
https://github.com/pojome/elementor/blob/0cfd51b929e9bbd8ddcd495350d443767a863124/includes/editor.php#L105-L109
https://github.com/pojome/elementor/commit/5879b80c6a33bca86c4f069ec09117dae945de6e

Jetpack's Markdown module, however, adds its JavaScript by hooking into another hook, `after_wp_tiny_mce`, to indicate that its script must load after TinyMCE scripts, that also rely on jQuery.
Since Elementor does not remove anything that's hooked there yet, it creates the issue. I created a PR here to let the Elementor folks know and offer a fix:
https://github.com/pojome/elementor/pull/5686

Closing this issue now.
